In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import average_precision_score
from sklearn.model_selection import StratifiedKFold
from pyod.models.deep_svdd import DeepSVDD
import sys
import scrapbook as sb

sys.path.append('..')
from utils import reshape_to_numpy, interpolate_missing_values, denoise_data, compute_spectrograms, time_avg_pooling

In [2]:
seed = 1
sampling_rate = 10
nperseg=64
noverlap=32
accel_cutoff = 0.4
accel_order = 30
gyro_cutoff = 0.6
gyro_order = 20
batch_size = 32
epochs = 100
hidden_neurons = [128, 64, 32]
n_splits = 5

In [3]:
# Parameters
seed = 26

In [4]:
rng = np.random.RandomState(seed)

In [5]:
data = pd.read_parquet("../data/GBG500.parquet")
data

,ride_id,time_index,ax,ay,az,rx,ry,rz
0,005043f1a7520cebf1e17fd166a00a3190e2433530f236...,0,-2.512796,-9.385012,-1.053078,-0.009155,0.009155,-0.201416
1,005043f1a7520cebf1e17fd166a00a3190e2433530f236...,100,-2.491268,-9.385012,-1.079390,-0.036621,0.027465,-0.155639
2,005043f1a7520cebf1e17fd166a00a3190e2433530f236...,200,-2.534324,-9.382022,-1.030952,0.036621,0.027465,-0.073242
3,005043f1a7520cebf1e17fd166a00a3190e2433530f236...,300,-2.488278,-9.383218,-1.091948,-0.045776,0.036621,-0.183105
4,005043f1a7520cebf1e17fd166a00a3190e2433530f236...,400,-2.483494,-9.382022,-1.100320,-0.045776,0.027465,-0.192260
...,...,...,...,...,...,...,...,...
1529542,ffb6f2f5dc6ba768d88dc0bc1af4cad235526aa9e24168...,241300,0.459862,-9.140430,-3.318900,1.556396,-0.091552,0.274658
1529543,ffb6f2f5dc6ba768d88dc0bc1af4cad235526aa9e24168...,241400,0.455676,-9.140430,-3.321292,1.583861,-0.119018,0.274658
1529544,ffb6f2f5dc6ba768d88dc0bc1af4cad235526aa9e24168...,241500,0.459862,-9.139832,-3.317704,1.583861,-0.109863,0.274658
1529545,ffb6f2f5dc6ba768d88dc0bc1af4cad235526aa9e24168...,241600,0.456274,-9.142224,-3.321292,1.574707,-0.137329,0.283813
1529546,ffb6f2f5dc6ba768d88dc0bc1af4cad235526aa9e24168...,241700,0.458666,-9.139832,-3.320694,1.574707,-0.137329,0.274658

In [6]:
labels = pd.read_csv("../data/GBG500_labels.csv")
labels.columns = labels.columns.str.lower()
ride_order_df = pd.DataFrame({"ride_id": data["ride_id"].unique()})
labels_sorted = ride_order_df.merge(
    labels,
    on="ride_id",
    how="left"
)
labels_sorted

                                               ride_id        label
0    005043f1a7520cebf1e17fd166a00a3190e2433530f236...         Safe
1    00d223cb7aecc9c0cc5871e32a6c45027a068eba07c572...     Reckless
2    02288a4aeca044203394e982e76b87818021dea2b34df9...         Safe
3    0236bdcf13d473ea24d97f5eaeea459f257dffac005694...  Bad weather
4    0238e5dd85143f1b6c59b200bc32f14361b8fc84c51a87...         Safe
..                                                 ...          ...
495  fe5d7f84d692bbccad8bd566a3ad5c3108fa9f90acd671...         Safe
496  fe67169632306d4668b2affedef510df2cb43e2fb41220...         Safe
497  fee44667fdc8ab4995c702fc3bd36178de0b1ca2c64687...         Safe
498  ff79b2e945b93c2a5efc3a06365267b3a160e7849ba57d...         Safe
499  ffb6f2f5dc6ba768d88dc0bc1af4cad235526aa9e24168...         Safe

[500 rows x 2 columns]

In [7]:
data_np = reshape_to_numpy(
    data,
    features = ["ax", "ay", "az", "rx", "ry", "rz"],
    max_timestamps = 4800
)

data_np_clean = interpolate_missing_values(
    data_np,
    method='linear',
    limit=None
)

data_np_clean = denoise_data(
    data=data_np_clean,
    accel_indices=[0, 1, 2],
    gyro_indices=[3, 4, 5],
    accel_cutoff=accel_cutoff,
    accel_order=accel_order,
    gyro_cutoff=gyro_cutoff,
    gyro_order=gyro_order,
)

In [8]:
# Compute spectrograms for all rides
spectrograms_array = compute_spectrograms(data_np_clean, sampling_rate, nperseg, noverlap)
spectrograms_array.shape

(500, 149, 6, 33)

In [9]:
# Aggregate spectrograms using time-averaged pooling
X_feat = time_avg_pooling(spectrograms_array)
X_feat.shape

(500, 198)

In [10]:
# 5-fold stratified CV with Deep SVDD
skf = StratifiedKFold(n_splits=n_splits, shuffle=True, random_state=rng.randint(1000))
y_true = (labels_sorted['label'] == 'Reckless').astype(int).values
anomaly_scores = np.full(len(y_true), np.nan)

for fold, (train_idx, test_idx) in enumerate(skf.split(X_feat, y_true)):
    sc = StandardScaler()
    X_train = sc.fit_transform(X_feat[train_idx])
    X_test = sc.transform(X_feat[test_idx])

    np.random.seed(rng.randint(1000))
    model = DeepSVDD(
        n_features=X_train.shape[1],
        hidden_neurons=hidden_neurons,
        epochs=epochs,
        batch_size=batch_size,
        random_state=rng.randint(1000),
    )
    model.fit(X_train)
    anomaly_scores[test_idx] = model.decision_function(X_test)
    print(f"Fold {fold+1}/{n_splits} done")

Epoch 1/100, Loss: 1.5760063007473946
Epoch 2/100, Loss: 1.4101946130394936
Epoch 3/100, Loss: 1.5183211900293827
Epoch 4/100, Loss: 1.4865358918905258
Epoch 5/100, Loss: 1.493664439767599
Epoch 6/100, Loss: 1.4633923061192036
Epoch 7/100, Loss: 1.5876053608953953
Epoch 8/100, Loss: 1.5735607333481312
Epoch 9/100, Loss: 1.4890321977436543
Epoch 10/100, Loss: 1.633191667497158
Epoch 11/100, Loss: 1.4973999485373497
Epoch 12/100, Loss: 1.648085094988346
Epoch 13/100, Loss: 1.6505354791879654
Epoch 14/100, Loss: 1.452618569135666
Epoch 15/100, Loss: 1.5776635892689228

Epoch 16/100, Loss: 1.4890705309808254
Epoch 17/100, Loss: 1.616627987474203
Epoch 18/100, Loss: 1.5546594373881817
Epoch 19/100, Loss: 1.5930058173835278
Epoch 20/100, Loss: 1.6105603612959385
Epoch 21/100, Loss: 1.4883886575698853
Epoch 22/100, Loss: 1.4596171490848064
Epoch 23/100, Loss: 1.6688117422163486
Epoch 24/100, Loss: 1.3869864270091057
Epoch 25/100, Loss: 1.692107405513525
Epoch 26/100, Loss: 1.6332714706659317
Epoch 27/100, Loss: 1.7315750867128372
Epoch 28/100, Loss: 1.642834085971117
Epoch 29/100, Loss: 1.472186852246523
Epoch 30/100, Loss: 1.3427846245467663

Epoch 31/100, Loss: 1.485952291637659
Epoch 32/100, Loss: 1.5585597194731236
Epoch 33/100, Loss: 1.5207415781915188
Epoch 34/100, Loss: 1.4317724592983723
Epoch 35/100, Loss: 1.6300997771322727
Epoch 36/100, Loss: 1.677630040794611
Epoch 37/100, Loss: 1.5124827660620213
Epoch 38/100, Loss: 1.2873146794736385
Epoch 39/100, Loss: 1.5419403426349163
Epoch 40/100, Loss: 1.4744836054742336
Epoch 41/100, Loss: 1.6042334847152233
Epoch 42/100, Loss: 1.6105320453643799
Epoch 43/100, Loss: 1.499986957758665
Epoch 44/100, Loss: 1.5139587670564651
Epoch 45/100, Loss: 1.5602581016719341

Epoch 46/100, Loss: 1.5215534642338753
Epoch 47/100, Loss: 1.6715049147605896
Epoch 48/100, Loss: 1.4982102364301682
Epoch 49/100, Loss: 1.4798654094338417
Epoch 50/100, Loss: 1.5051529370248318
Epoch 51/100, Loss: 1.4769093096256256
Epoch 52/100, Loss: 1.426700048148632
Epoch 53/100, Loss: 1.4889186322689056
Epoch 54/100, Loss: 1.6488387361168861
Epoch 55/100, Loss: 1.5594786629080772
Epoch 56/100, Loss: 1.5239310748875141
Epoch 57/100, Loss: 1.5796367414295673
Epoch 58/100, Loss: 1.5091656148433685
Epoch 59/100, Loss: 1.5118295811116695
Epoch 60/100, Loss: 1.4665532857179642

Epoch 61/100, Loss: 1.6830243207514286
Epoch 62/100, Loss: 1.5878595560789108
Epoch 63/100, Loss: 1.540950920432806
Epoch 64/100, Loss: 1.5356835722923279
Epoch 65/100, Loss: 1.568246517330408
Epoch 66/100, Loss: 1.5857978723943233
Epoch 67/100, Loss: 1.4317760095000267
Epoch 68/100, Loss: 1.6616735272109509
Epoch 69/100, Loss: 1.3928481861948967
Epoch 70/100, Loss: 1.6813493147492409
Epoch 71/100, Loss: 1.7034926116466522
Epoch 72/100, Loss: 1.4044187739491463
Epoch 73/100, Loss: 1.5297305919229984
Epoch 74/100, Loss: 1.4731372222304344
Epoch 75/100, Loss: 1.5751546248793602

Epoch 76/100, Loss: 1.5400442741811275
Epoch 77/100, Loss: 1.5442855507135391
Epoch 78/100, Loss: 1.5452832207083702
Epoch 79/100, Loss: 1.4986914806067944
Epoch 80/100, Loss: 1.536004513502121
Epoch 81/100, Loss: 1.422265000641346
Epoch 82/100, Loss: 1.551820807158947
Epoch 83/100, Loss: 1.5058277808129787
Epoch 84/100, Loss: 1.4373804479837418
Epoch 85/100, Loss: 1.4261802211403847
Epoch 86/100, Loss: 1.6549320481717587
Epoch 87/100, Loss: 1.3764088451862335
Epoch 88/100, Loss: 1.4458405189216137
Epoch 89/100, Loss: 1.5214761197566986
Epoch 90/100, Loss: 1.6313866823911667

Epoch 91/100, Loss: 1.5314467772841454
Epoch 92/100, Loss: 1.666026048362255
Epoch 93/100, Loss: 1.5417347438633442
Epoch 94/100, Loss: 1.411083847284317
Epoch 95/100, Loss: 1.4155272617936134
Epoch 96/100, Loss: 1.504242841154337
Epoch 97/100, Loss: 1.3789912201464176
Epoch 98/100, Loss: 1.4160328581929207
Epoch 99/100, Loss: 1.5636247731745243
Epoch 100/100, Loss: 1.7364571169018745
Fold 1/5 done
Epoch 1/100, Loss: 2.1811435520648956
Epoch 2/100, Loss: 2.204519532620907
Epoch 3/100, Loss: 2.080821171402931
Epoch 4/100, Loss: 2.2927857413887978

Epoch 5/100, Loss: 2.0372479781508446
Epoch 6/100, Loss: 2.1015526950359344
Epoch 7/100, Loss: 2.0603819862008095
Epoch 8/100, Loss: 2.0800290554761887
Epoch 9/100, Loss: 2.197391599416733
Epoch 10/100, Loss: 2.1018495112657547
Epoch 11/100, Loss: 2.1048656553030014
Epoch 12/100, Loss: 2.091608941555023
Epoch 13/100, Loss: 2.055366538465023
Epoch 14/100, Loss: 2.031403936445713
Epoch 15/100, Loss: 2.1889361888170242
Epoch 16/100, Loss: 1.9740507826209068
Epoch 17/100, Loss: 2.103004403412342
Epoch 18/100, Loss: 2.0964371785521507
Epoch 19/100, Loss: 2.1315975040197372

Epoch 20/100, Loss: 2.023994006216526
Epoch 21/100, Loss: 2.1054292917251587
Epoch 22/100, Loss: 2.1726666539907455
Epoch 23/100, Loss: 2.1080798134207726
Epoch 24/100, Loss: 2.167315922677517
Epoch 25/100, Loss: 2.06068829447031
Epoch 26/100, Loss: 2.1530504897236824
Epoch 27/100, Loss: 2.1508446410298347
Epoch 28/100, Loss: 2.1280414015054703
Epoch 29/100, Loss: 2.1041266322135925
Epoch 30/100, Loss: 1.9990702345967293
Epoch 31/100, Loss: 2.1133525148034096
Epoch 32/100, Loss: 2.2181825041770935
Epoch 33/100, Loss: 2.072481244802475
Epoch 34/100, Loss: 2.1926249116659164

Epoch 35/100, Loss: 2.022227890789509
Epoch 36/100, Loss: 2.0876333862543106
Epoch 37/100, Loss: 2.0760523453354836
Epoch 38/100, Loss: 2.0447257086634636
Epoch 39/100, Loss: 2.0897995457053185
Epoch 40/100, Loss: 2.01168305426836
Epoch 41/100, Loss: 2.15199376642704
Epoch 42/100, Loss: 1.9859236106276512
Epoch 43/100, Loss: 2.1063190400600433
Epoch 44/100, Loss: 2.1180310398340225
Epoch 45/100, Loss: 2.110243983566761
Epoch 46/100, Loss: 2.090652495622635
Epoch 47/100, Loss: 2.0962706729769707
Epoch 48/100, Loss: 2.2597248926758766
Epoch 49/100, Loss: 2.1896957978606224

Epoch 50/100, Loss: 2.330457977950573
Epoch 51/100, Loss: 2.15677247941494
Epoch 52/100, Loss: 2.124081999063492
Epoch 53/100, Loss: 2.102518443018198
Epoch 54/100, Loss: 2.086296908557415
Epoch 55/100, Loss: 2.1575175151228905
Epoch 56/100, Loss: 2.113745369017124
Epoch 57/100, Loss: 2.0284957736730576
Epoch 58/100, Loss: 2.1747075021266937
Epoch 59/100, Loss: 2.0869885608553886
Epoch 60/100, Loss: 2.201958119869232
Epoch 61/100, Loss: 2.219717286527157
Epoch 62/100, Loss: 2.1182510182261467
Epoch 63/100, Loss: 2.0479042530059814
Epoch 64/100, Loss: 2.123522736132145

Epoch 65/100, Loss: 2.0566974580287933
Epoch 66/100, Loss: 2.139181725680828
Epoch 67/100, Loss: 2.0959157422184944
Epoch 68/100, Loss: 2.1344739571213722
Epoch 69/100, Loss: 2.050543040037155
Epoch 70/100, Loss: 2.0535392686724663
Epoch 71/100, Loss: 2.08984088152647
Epoch 72/100, Loss: 2.0656308382749557
Epoch 73/100, Loss: 2.102314203977585
Epoch 74/100, Loss: 2.102966796606779
Epoch 75/100, Loss: 2.1411272138357162
Epoch 76/100, Loss: 2.103750318288803
Epoch 77/100, Loss: 2.069233685731888
Epoch 78/100, Loss: 2.0024081468582153
Epoch 79/100, Loss: 2.095724418759346

Epoch 80/100, Loss: 2.1735935509204865
Epoch 81/100, Loss: 2.122618518769741
Epoch 82/100, Loss: 2.153377078473568
Epoch 83/100, Loss: 2.092982418835163
Epoch 84/100, Loss: 2.047924719750881
Epoch 85/100, Loss: 2.0659152194857597
Epoch 86/100, Loss: 2.037543386220932
Epoch 87/100, Loss: 2.153202660381794
Epoch 88/100, Loss: 2.183294914662838
Epoch 89/100, Loss: 2.0669992938637733
Epoch 90/100, Loss: 2.2733190059661865
Epoch 91/100, Loss: 2.113986976444721
Epoch 92/100, Loss: 2.048414319753647
Epoch 93/100, Loss: 2.068143829703331
Epoch 94/100, Loss: 2.1151557490229607

Epoch 95/100, Loss: 2.1796070262789726
Epoch 96/100, Loss: 2.227877490222454
Epoch 97/100, Loss: 2.1027063205838203
Epoch 98/100, Loss: 2.2027828320860863
Epoch 99/100, Loss: 2.133323609828949
Epoch 100/100, Loss: 2.1812914982438087
Fold 2/5 done
Epoch 1/100, Loss: 2.2000844180583954
Epoch 2/100, Loss: 2.0769486278295517
Epoch 3/100, Loss: 2.1246574372053146
Epoch 4/100, Loss: 2.057196967303753
Epoch 5/100, Loss: 2.0327863842248917
Epoch 6/100, Loss: 2.0733883157372475
Epoch 7/100, Loss: 2.1180423721671104
Epoch 8/100, Loss: 2.13912932574749

Epoch 9/100, Loss: 1.9493778347969055
Epoch 10/100, Loss: 2.1436742544174194
Epoch 11/100, Loss: 2.146360732614994
Epoch 12/100, Loss: 2.309689998626709
Epoch 13/100, Loss: 2.0050970911979675
Epoch 14/100, Loss: 2.0675182193517685
Epoch 15/100, Loss: 2.1140571609139442
Epoch 16/100, Loss: 2.02719284594059
Epoch 17/100, Loss: 2.213801085948944
Epoch 18/100, Loss: 2.144115187227726
Epoch 19/100, Loss: 2.275993712246418
Epoch 20/100, Loss: 2.068068452179432
Epoch 21/100, Loss: 2.1021856665611267
Epoch 22/100, Loss: 2.1510675251483917
Epoch 23/100, Loss: 1.9143607914447784

Epoch 24/100, Loss: 2.05172099173069
Epoch 25/100, Loss: 2.510412886738777
Epoch 26/100, Loss: 2.076361060142517
Epoch 27/100, Loss: 2.0391546562314034
Epoch 28/100, Loss: 2.150910399854183
Epoch 29/100, Loss: 2.2101795598864555
Epoch 30/100, Loss: 2.1749858260154724
Epoch 31/100, Loss: 2.0381460189819336
Epoch 32/100, Loss: 2.1575250551104546
Epoch 33/100, Loss: 2.1069354116916656
Epoch 34/100, Loss: 2.057104028761387
Epoch 35/100, Loss: 2.0377943366765976
Epoch 36/100, Loss: 2.116900645196438
Epoch 37/100, Loss: 2.1643558740615845
Epoch 38/100, Loss: 1.986723318696022

Epoch 39/100, Loss: 2.1042636185884476
Epoch 40/100, Loss: 2.046381860971451
Epoch 41/100, Loss: 2.070617191493511
Epoch 42/100, Loss: 1.9914105758070946
Epoch 43/100, Loss: 2.1113757640123367
Epoch 44/100, Loss: 2.0469689443707466
Epoch 45/100, Loss: 2.0174898877739906
Epoch 46/100, Loss: 2.1120168566703796
Epoch 47/100, Loss: 2.0914291217923164
Epoch 48/100, Loss: 1.904890775680542
Epoch 49/100, Loss: 2.1658006086945534
Epoch 50/100, Loss: 2.1595660969614983
Epoch 51/100, Loss: 2.0102539882063866
Epoch 52/100, Loss: 2.111590586602688
Epoch 53/100, Loss: 2.2240742668509483
Epoch 54/100, Loss: 2.197373129427433

Epoch 55/100, Loss: 2.1065307408571243
Epoch 56/100, Loss: 1.858871839940548
Epoch 57/100, Loss: 2.1503110453486443
Epoch 58/100, Loss: 2.1144809648394585
Epoch 59/100, Loss: 2.101295091211796
Epoch 60/100, Loss: 2.029197782278061
Epoch 61/100, Loss: 2.075673796236515
Epoch 62/100, Loss: 2.1921894624829292
Epoch 63/100, Loss: 2.0842290744185448
Epoch 64/100, Loss: 2.0582458153367043
Epoch 65/100, Loss: 2.0912434980273247
Epoch 66/100, Loss: 2.000090144574642
Epoch 67/100, Loss: 1.9500728249549866
Epoch 68/100, Loss: 2.287144862115383
Epoch 69/100, Loss: 2.0267644971609116
Epoch 70/100, Loss: 2.190278597176075
Epoch 71/100, Loss: 2.191448912024498

Epoch 72/100, Loss: 2.10269445925951
Epoch 73/100, Loss: 2.1160116866230965
Epoch 74/100, Loss: 2.076871618628502
Epoch 75/100, Loss: 2.0495689138770103
Epoch 76/100, Loss: 2.1367611959576607
Epoch 77/100, Loss: 2.0476179271936417
Epoch 78/100, Loss: 2.283114828169346
Epoch 79/100, Loss: 2.1663514897227287
Epoch 80/100, Loss: 2.0495093688368797
Epoch 81/100, Loss: 2.0171238631010056
Epoch 82/100, Loss: 2.6289993673563004
Epoch 83/100, Loss: 2.165440134704113
Epoch 84/100, Loss: 1.9689717292785645
Epoch 85/100, Loss: 1.9592921659350395
Epoch 86/100, Loss: 2.040944702923298
Epoch 87/100, Loss: 2.3436386957764626
Epoch 88/100, Loss: 2.1029953733086586
Epoch 89/100, Loss: 2.536425031721592

Epoch 90/100, Loss: 2.3844481632113457
Epoch 91/100, Loss: 2.22340427339077
Epoch 92/100, Loss: 2.1449261531233788
Epoch 93/100, Loss: 2.1549116522073746
Epoch 94/100, Loss: 2.228604018688202
Epoch 95/100, Loss: 2.0879025533795357
Epoch 96/100, Loss: 2.0510480254888535
Epoch 97/100, Loss: 2.0343457013368607
Epoch 98/100, Loss: 2.0738512948155403
Epoch 99/100, Loss: 2.1227004900574684
Epoch 100/100, Loss: 2.0040684416890144
Fold 3/5 done
Epoch 1/100, Loss: 2.4117097929120064
Epoch 2/100, Loss: 2.3659022226929665
Epoch 3/100, Loss: 2.4728485345840454
Epoch 4/100, Loss: 2.3672677129507065
Epoch 5/100, Loss: 2.5326125621795654

Epoch 6/100, Loss: 2.443823426961899
Epoch 7/100, Loss: 2.370697110891342
Epoch 8/100, Loss: 2.4207267463207245
Epoch 9/100, Loss: 2.474340431392193
Epoch 10/100, Loss: 2.4836030825972557
Epoch 11/100, Loss: 2.321320228278637
Epoch 12/100, Loss: 2.847835883498192
Epoch 13/100, Loss: 2.3411905169487
Epoch 14/100, Loss: 2.4806967601180077
Epoch 15/100, Loss: 2.556319199502468
Epoch 16/100, Loss: 2.3491987735033035
Epoch 17/100, Loss: 2.208238147199154
Epoch 18/100, Loss: 2.137122243642807
Epoch 19/100, Loss: 2.4372049048542976
Epoch 20/100, Loss: 2.366427071392536
Epoch 21/100, Loss: 2.3852542117238045

Epoch 22/100, Loss: 2.5000556483864784
Epoch 23/100, Loss: 2.0880389027297497
Epoch 24/100, Loss: 2.164307102560997
Epoch 25/100, Loss: 2.219312533736229
Epoch 26/100, Loss: 2.2746497243642807
Epoch 27/100, Loss: 2.207967169582844
Epoch 28/100, Loss: 2.3387105762958527
Epoch 29/100, Loss: 2.5488318726420403
Epoch 30/100, Loss: 2.2908504605293274
Epoch 31/100, Loss: 2.2783453539013863
Epoch 32/100, Loss: 2.313403971493244
Epoch 33/100, Loss: 2.3735477924346924
Epoch 34/100, Loss: 2.249347895383835
Epoch 35/100, Loss: 2.368124894797802
Epoch 36/100, Loss: 2.2807214111089706
Epoch 37/100, Loss: 2.2949856519699097
Epoch 38/100, Loss: 2.240121439099312

Epoch 39/100, Loss: 2.2971674129366875
Epoch 40/100, Loss: 2.286021701991558
Epoch 41/100, Loss: 2.3917913138866425
Epoch 42/100, Loss: 2.2325830683112144
Epoch 43/100, Loss: 2.4180290922522545
Epoch 44/100, Loss: 2.2264739871025085
Epoch 45/100, Loss: 2.404010146856308
Epoch 46/100, Loss: 2.2937865555286407
Epoch 47/100, Loss: 2.35096388310194
Epoch 48/100, Loss: 2.1940964981913567
Epoch 49/100, Loss: 2.242512196302414
Epoch 50/100, Loss: 2.3205122277140617
Epoch 51/100, Loss: 2.373816817998886
Epoch 52/100, Loss: 2.380946770310402
Epoch 53/100, Loss: 2.346137620508671
Epoch 54/100, Loss: 2.3249553814530373
Epoch 55/100, Loss: 2.2885745763778687

Epoch 56/100, Loss: 2.5037651509046555
Epoch 57/100, Loss: 2.162964142858982
Epoch 58/100, Loss: 2.497180312871933
Epoch 59/100, Loss: 2.4800743460655212
Epoch 60/100, Loss: 2.47868449985981
Epoch 61/100, Loss: 2.5175262317061424
Epoch 62/100, Loss: 2.2157139033079147
Epoch 63/100, Loss: 2.2930313125252724
Epoch 64/100, Loss: 2.3962414786219597
Epoch 65/100, Loss: 2.7270491048693657
Epoch 66/100, Loss: 2.4606203511357307
Epoch 67/100, Loss: 2.2550422102212906
Epoch 68/100, Loss: 2.357467070221901
Epoch 69/100, Loss: 2.335328131914139
Epoch 70/100, Loss: 2.423154518008232
Epoch 71/100, Loss: 2.372471682727337
Epoch 72/100, Loss: 2.5109950453042984

Epoch 73/100, Loss: 2.2917020842432976
Epoch 74/100, Loss: 2.340882331132889
Epoch 75/100, Loss: 2.267617665231228
Epoch 76/100, Loss: 2.371325582265854
Epoch 77/100, Loss: 2.5260082855820656
Epoch 78/100, Loss: 2.4405262246727943
Epoch 79/100, Loss: 2.9024710208177567
Epoch 80/100, Loss: 2.418527252972126
Epoch 81/100, Loss: 2.5087140426039696
Epoch 82/100, Loss: 2.223901279270649
Epoch 83/100, Loss: 2.3922614976763725
Epoch 84/100, Loss: 2.435053363442421
Epoch 85/100, Loss: 2.2991844192147255
Epoch 86/100, Loss: 2.6411788016557693
Epoch 87/100, Loss: 2.3425167314708233
Epoch 88/100, Loss: 2.2804938182234764
Epoch 89/100, Loss: 2.362889386713505

Epoch 90/100, Loss: 2.4310812577605247
Epoch 91/100, Loss: 2.3192906975746155
Epoch 92/100, Loss: 2.2179123014211655
Epoch 93/100, Loss: 2.226577527821064
Epoch 94/100, Loss: 2.288371831178665
Epoch 95/100, Loss: 2.1998133808374405
Epoch 96/100, Loss: 2.440026767551899
Epoch 97/100, Loss: 2.2581823021173477
Epoch 98/100, Loss: 2.286504030227661
Epoch 99/100, Loss: 2.348806604743004
Epoch 100/100, Loss: 2.51340714097023
Fold 4/5 done
Epoch 1/100, Loss: 3.1764830723404884
Epoch 2/100, Loss: 3.051513522863388
Epoch 3/100, Loss: 2.9204344004392624
Epoch 4/100, Loss: 3.1048143059015274
Epoch 5/100, Loss: 3.1333889216184616

Epoch 6/100, Loss: 2.6764108017086983
Epoch 7/100, Loss: 2.8566412180662155
Epoch 8/100, Loss: 2.919983685016632
Epoch 9/100, Loss: 3.2612997218966484
Epoch 10/100, Loss: 3.1062570735812187
Epoch 11/100, Loss: 2.8610827922821045
Epoch 12/100, Loss: 2.530995585024357
Epoch 13/100, Loss: 3.416241332888603
Epoch 14/100, Loss: 3.627016067504883
Epoch 15/100, Loss: 3.1446744427084923
Epoch 16/100, Loss: 2.8559430539608
Epoch 17/100, Loss: 2.9772177934646606
Epoch 18/100, Loss: 3.0254060477018356
Epoch 19/100, Loss: 2.9935083612799644
Epoch 20/100, Loss: 3.064151242375374
Epoch 21/100, Loss: 2.955917350947857
Epoch 22/100, Loss: 3.2388317212462425

Epoch 23/100, Loss: 3.002299524843693
Epoch 24/100, Loss: 3.0610792338848114
Epoch 25/100, Loss: 2.9687558114528656
Epoch 26/100, Loss: 3.0065947771072388
Epoch 27/100, Loss: 3.1212934628129005
Epoch 28/100, Loss: 3.212507799267769
Epoch 29/100, Loss: 3.097028322517872
Epoch 30/100, Loss: 2.928538478910923
Epoch 31/100, Loss: 2.9397723376750946
Epoch 32/100, Loss: 2.993879556655884
Epoch 33/100, Loss: 3.3094514831900597
Epoch 34/100, Loss: 3.153268724679947
Epoch 35/100, Loss: 3.1296671107411385
Epoch 36/100, Loss: 3.1417132169008255
Epoch 37/100, Loss: 2.970839485526085
Epoch 38/100, Loss: 3.016925446689129

Epoch 39/100, Loss: 3.0871793180704117
Epoch 40/100, Loss: 2.9706321358680725
Epoch 41/100, Loss: 3.021490439772606
Epoch 42/100, Loss: 2.676651395857334
Epoch 43/100, Loss: 2.9706802740693092
Epoch 44/100, Loss: 3.64944801479578
Epoch 45/100, Loss: 3.009517341852188
Epoch 46/100, Loss: 2.8534215837717056
Epoch 47/100, Loss: 2.5237711369991302
Epoch 48/100, Loss: 3.0215930864214897
Epoch 49/100, Loss: 2.805106222629547
Epoch 50/100, Loss: 3.0218217745423317
Epoch 51/100, Loss: 2.9715711548924446
Epoch 52/100, Loss: 3.1917323246598244
Epoch 53/100, Loss: 2.8017403408885
Epoch 54/100, Loss: 3.0803227722644806
Epoch 55/100, Loss: 2.955692395567894

Epoch 56/100, Loss: 2.906125947833061
Epoch 57/100, Loss: 2.965343862771988
Epoch 58/100, Loss: 2.9218457639217377
Epoch 59/100, Loss: 3.2209587693214417
Epoch 60/100, Loss: 3.102122724056244
Epoch 61/100, Loss: 3.0384407490491867
Epoch 62/100, Loss: 2.9603912234306335
Epoch 63/100, Loss: 2.849942147731781
Epoch 64/100, Loss: 2.843621276319027
Epoch 65/100, Loss: 2.6417638286948204
Epoch 66/100, Loss: 2.969975098967552
Epoch 67/100, Loss: 2.902518130838871
Epoch 68/100, Loss: 3.1087865382432938
Epoch 69/100, Loss: 3.1249598041176796
Epoch 70/100, Loss: 2.839758314192295
Epoch 71/100, Loss: 3.1386661753058434
Epoch 72/100, Loss: 2.673202730715275
Epoch 73/100, Loss: 3.0130535513162613

Epoch 74/100, Loss: 3.5693419873714447
Epoch 75/100, Loss: 4.026500716805458
Epoch 76/100, Loss: 2.9535139724612236
Epoch 77/100, Loss: 2.908988893032074
Epoch 78/100, Loss: 3.1252824664115906
Epoch 79/100, Loss: 2.907545745372772
Epoch 80/100, Loss: 2.921198569238186
Epoch 81/100, Loss: 3.043905258178711
Epoch 82/100, Loss: 3.0331126675009727
Epoch 83/100, Loss: 2.9983664751052856
Epoch 84/100, Loss: 3.200675390660763
Epoch 85/100, Loss: 3.025908149778843
Epoch 86/100, Loss: 2.9589397311210632
Epoch 87/100, Loss: 2.9790817350149155
Epoch 88/100, Loss: 3.1162178069353104
Epoch 89/100, Loss: 3.185323715209961
Epoch 90/100, Loss: 3.176822856068611

Epoch 91/100, Loss: 2.8927143067121506
Epoch 92/100, Loss: 3.0754183754324913
Epoch 93/100, Loss: 2.905463181436062
Epoch 94/100, Loss: 2.9743983820080757
Epoch 95/100, Loss: 2.8917686119675636
Epoch 96/100, Loss: 3.122270978987217
Epoch 97/100, Loss: 3.1170518696308136
Epoch 98/100, Loss: 3.67029095441103
Epoch 99/100, Loss: 3.034867450594902
Epoch 100/100, Loss: 3.0662756636738777
Fold 5/5 done

In [11]:
ap = average_precision_score(y_true, anomaly_scores)
print(f"Deep SVDD AP (5-fold CV) = {ap:.4f}")
sb.glue("GBG500_ap_spectral_deep_svdd", float(ap))

Deep SVDD AP (5-fold CV) = 0.6450