In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import average_precision_score
from sklearn.model_selection import StratifiedKFold
from pyod.models.deep_svdd import DeepSVDD
import sys
import scrapbook as sb

sys.path.append('..')
from utils import reshape_to_numpy, interpolate_missing_values, denoise_data, compute_spectrograms, time_avg_pooling

In [2]:
seed = 1
sampling_rate = 10
nperseg=64
noverlap=32
accel_cutoff = 0.4
accel_order = 30
gyro_cutoff = 0.6
gyro_order = 20
batch_size = 32
epochs = 100
hidden_neurons = [128, 64, 32]
n_splits = 5

In [3]:
# Parameters
seed = 8

In [4]:
rng = np.random.RandomState(seed)

In [5]:
data = pd.read_parquet("../data/GBG500.parquet")
data

,ride_id,time_index,ax,ay,az,rx,ry,rz
0,005043f1a7520cebf1e17fd166a00a3190e2433530f236...,0,-2.512796,-9.385012,-1.053078,-0.009155,0.009155,-0.201416
1,005043f1a7520cebf1e17fd166a00a3190e2433530f236...,100,-2.491268,-9.385012,-1.079390,-0.036621,0.027465,-0.155639
2,005043f1a7520cebf1e17fd166a00a3190e2433530f236...,200,-2.534324,-9.382022,-1.030952,0.036621,0.027465,-0.073242
3,005043f1a7520cebf1e17fd166a00a3190e2433530f236...,300,-2.488278,-9.383218,-1.091948,-0.045776,0.036621,-0.183105
4,005043f1a7520cebf1e17fd166a00a3190e2433530f236...,400,-2.483494,-9.382022,-1.100320,-0.045776,0.027465,-0.192260
...,...,...,...,...,...,...,...,...
1529542,ffb6f2f5dc6ba768d88dc0bc1af4cad235526aa9e24168...,241300,0.459862,-9.140430,-3.318900,1.556396,-0.091552,0.274658
1529543,ffb6f2f5dc6ba768d88dc0bc1af4cad235526aa9e24168...,241400,0.455676,-9.140430,-3.321292,1.583861,-0.119018,0.274658
1529544,ffb6f2f5dc6ba768d88dc0bc1af4cad235526aa9e24168...,241500,0.459862,-9.139832,-3.317704,1.583861,-0.109863,0.274658
1529545,ffb6f2f5dc6ba768d88dc0bc1af4cad235526aa9e24168...,241600,0.456274,-9.142224,-3.321292,1.574707,-0.137329,0.283813
1529546,ffb6f2f5dc6ba768d88dc0bc1af4cad235526aa9e24168...,241700,0.458666,-9.139832,-3.320694,1.574707,-0.137329,0.274658

In [6]:
labels = pd.read_csv("../data/GBG500_labels.csv")
labels.columns = labels.columns.str.lower()
ride_order_df = pd.DataFrame({"ride_id": data["ride_id"].unique()})
labels_sorted = ride_order_df.merge(
    labels,
    on="ride_id",
    how="left"
)
labels_sorted

                                               ride_id        label
0    005043f1a7520cebf1e17fd166a00a3190e2433530f236...         Safe
1    00d223cb7aecc9c0cc5871e32a6c45027a068eba07c572...     Reckless
2    02288a4aeca044203394e982e76b87818021dea2b34df9...         Safe
3    0236bdcf13d473ea24d97f5eaeea459f257dffac005694...  Bad weather
4    0238e5dd85143f1b6c59b200bc32f14361b8fc84c51a87...         Safe
..                                                 ...          ...
495  fe5d7f84d692bbccad8bd566a3ad5c3108fa9f90acd671...         Safe
496  fe67169632306d4668b2affedef510df2cb43e2fb41220...         Safe
497  fee44667fdc8ab4995c702fc3bd36178de0b1ca2c64687...         Safe
498  ff79b2e945b93c2a5efc3a06365267b3a160e7849ba57d...         Safe
499  ffb6f2f5dc6ba768d88dc0bc1af4cad235526aa9e24168...         Safe

[500 rows x 2 columns]

In [7]:
data_np = reshape_to_numpy(
    data,
    features = ["ax", "ay", "az", "rx", "ry", "rz"],
    max_timestamps = 4800
)

data_np_clean = interpolate_missing_values(
    data_np,
    method='linear',
    limit=None
)

data_np_clean = denoise_data(
    data=data_np_clean,
    accel_indices=[0, 1, 2],
    gyro_indices=[3, 4, 5],
    accel_cutoff=accel_cutoff,
    accel_order=accel_order,
    gyro_cutoff=gyro_cutoff,
    gyro_order=gyro_order,
)

In [8]:
# Compute spectrograms for all rides
spectrograms_array = compute_spectrograms(data_np_clean, sampling_rate, nperseg, noverlap)
spectrograms_array.shape

(500, 149, 6, 33)

In [9]:
# Aggregate spectrograms using time-averaged pooling
X_feat = time_avg_pooling(spectrograms_array)
X_feat.shape

(500, 198)

In [10]:
# 5-fold stratified CV with Deep SVDD
skf = StratifiedKFold(n_splits=n_splits, shuffle=True, random_state=rng.randint(1000))
y_true = (labels_sorted['label'] == 'Reckless').astype(int).values
anomaly_scores = np.full(len(y_true), np.nan)

for fold, (train_idx, test_idx) in enumerate(skf.split(X_feat, y_true)):
    sc = StandardScaler()
    X_train = sc.fit_transform(X_feat[train_idx])
    X_test = sc.transform(X_feat[test_idx])

    np.random.seed(rng.randint(1000))
    model = DeepSVDD(
        n_features=X_train.shape[1],
        hidden_neurons=hidden_neurons,
        epochs=epochs,
        batch_size=batch_size,
        random_state=rng.randint(1000),
    )
    model.fit(X_train)
    anomaly_scores[test_idx] = model.decision_function(X_test)
    print(f"Fold {fold+1}/{n_splits} done")

Epoch 1/100, Loss: 2.035590909421444
Epoch 2/100, Loss: 2.038944721221924
Epoch 3/100, Loss: 1.9562358856201172
Epoch 4/100, Loss: 2.048598773777485
Epoch 5/100, Loss: 2.0083866007626057
Epoch 6/100, Loss: 2.692954808473587
Epoch 7/100, Loss: 2.0466955676674843
Epoch 8/100, Loss: 2.021146610379219
Epoch 9/100, Loss: 1.9365567862987518
Epoch 10/100, Loss: 1.9462097063660622
Epoch 11/100, Loss: 1.9640254229307175
Epoch 12/100, Loss: 2.029901944100857
Epoch 13/100, Loss: 1.7801090329885483
Epoch 14/100, Loss: 1.878258928656578
Epoch 15/100, Loss: 2.037112422287464
Epoch 16/100, Loss: 1.9873804822564125

Epoch 17/100, Loss: 2.087942972779274
Epoch 18/100, Loss: 2.028234124183655
Epoch 19/100, Loss: 2.0892146602272987
Epoch 20/100, Loss: 1.9030761495232582
Epoch 21/100, Loss: 1.950657095760107
Epoch 22/100, Loss: 1.8684012219309807
Epoch 23/100, Loss: 1.9059557989239693
Epoch 24/100, Loss: 2.050698347389698
Epoch 25/100, Loss: 2.02660808339715
Epoch 26/100, Loss: 2.0105938240885735
Epoch 27/100, Loss: 1.8917210027575493
Epoch 28/100, Loss: 2.0764621198177338
Epoch 29/100, Loss: 2.1205920167267323
Epoch 30/100, Loss: 1.8832296431064606
Epoch 31/100, Loss: 2.0839821323752403
Epoch 32/100, Loss: 1.952197503298521

Epoch 33/100, Loss: 2.1421943083405495
Epoch 34/100, Loss: 2.07781945168972
Epoch 35/100, Loss: 1.974451258778572
Epoch 36/100, Loss: 1.931841529905796
Epoch 37/100, Loss: 1.8454245440661907
Epoch 38/100, Loss: 2.038918759673834
Epoch 39/100, Loss: 1.9542393386363983
Epoch 40/100, Loss: 1.8785130232572556
Epoch 41/100, Loss: 1.9968030750751495
Epoch 42/100, Loss: 1.7827986776828766
Epoch 43/100, Loss: 2.511078178882599
Epoch 44/100, Loss: 1.8793429136276245
Epoch 45/100, Loss: 1.8408079072833061
Epoch 46/100, Loss: 2.5177888944745064

Epoch 47/100, Loss: 2.026148594915867
Epoch 48/100, Loss: 2.044952653348446
Epoch 49/100, Loss: 2.0708787962794304
Epoch 50/100, Loss: 2.1373640447854996
Epoch 51/100, Loss: 2.1401063799858093
Epoch 52/100, Loss: 1.8039430603384972
Epoch 53/100, Loss: 1.9509591832756996
Epoch 54/100, Loss: 2.068114586174488
Epoch 55/100, Loss: 2.1389994472265244
Epoch 56/100, Loss: 1.9984481558203697
Epoch 57/100, Loss: 1.974209651350975
Epoch 58/100, Loss: 1.9878541678190231

Epoch 59/100, Loss: 2.0264325961470604
Epoch 60/100, Loss: 1.830891266465187
Epoch 61/100, Loss: 1.8077306896448135
Epoch 62/100, Loss: 1.8558809384703636
Epoch 63/100, Loss: 1.9782431051135063
Epoch 64/100, Loss: 2.0259906724095345
Epoch 65/100, Loss: 1.9748735427856445
Epoch 66/100, Loss: 1.8983824700117111
Epoch 67/100, Loss: 1.9890545904636383
Epoch 68/100, Loss: 1.9332358613610268
Epoch 69/100, Loss: 1.9606510028243065
Epoch 70/100, Loss: 1.8933763056993484
Epoch 71/100, Loss: 2.220673307776451
Epoch 72/100, Loss: 2.097820498049259
Epoch 73/100, Loss: 2.0060611814260483

Epoch 74/100, Loss: 1.827919114381075
Epoch 75/100, Loss: 1.9676616564393044
Epoch 76/100, Loss: 1.8590073809027672
Epoch 77/100, Loss: 1.8270047008991241
Epoch 78/100, Loss: 1.9222270101308823
Epoch 79/100, Loss: 1.9277726262807846
Epoch 80/100, Loss: 1.9269029200077057
Epoch 81/100, Loss: 1.9084524363279343
Epoch 82/100, Loss: 2.0434971004724503
Epoch 83/100, Loss: 1.8381147980690002
Epoch 84/100, Loss: 2.367273911833763
Epoch 85/100, Loss: 1.9717152789235115

Epoch 86/100, Loss: 1.928056538105011
Epoch 87/100, Loss: 2.0162508115172386
Epoch 88/100, Loss: 1.906334139406681
Epoch 89/100, Loss: 1.9818108156323433
Epoch 90/100, Loss: 2.039982460439205
Epoch 91/100, Loss: 2.0384167283773422
Epoch 92/100, Loss: 2.1133465990424156
Epoch 93/100, Loss: 2.091307319700718
Epoch 94/100, Loss: 1.8694876655936241
Epoch 95/100, Loss: 1.9440338015556335
Epoch 96/100, Loss: 1.8966989442706108
Epoch 97/100, Loss: 1.7836813554167747
Epoch 98/100, Loss: 2.037873886525631
Epoch 99/100, Loss: 2.2005879133939743
Epoch 100/100, Loss: 1.8737406507134438
Fold 1/5 done
Epoch 1/100, Loss: 2.384431876242161

Epoch 2/100, Loss: 2.4651391208171844
Epoch 3/100, Loss: 2.5592226162552834
Epoch 4/100, Loss: 2.5750185698270798
Epoch 5/100, Loss: 2.7354434579610825
Epoch 6/100, Loss: 2.7326226010918617
Epoch 7/100, Loss: 2.5337869375944138
Epoch 8/100, Loss: 2.6252157390117645
Epoch 9/100, Loss: 2.603145495057106
Epoch 10/100, Loss: 2.6102465987205505
Epoch 11/100, Loss: 2.5996445044875145
Epoch 12/100, Loss: 2.6294879019260406
Epoch 13/100, Loss: 2.4182838946580887
Epoch 14/100, Loss: 2.5354152396321297
Epoch 15/100, Loss: 2.5114318281412125
Epoch 16/100, Loss: 2.526178203523159
Epoch 17/100, Loss: 2.5429006665945053
Epoch 18/100, Loss: 2.4897868633270264

Epoch 19/100, Loss: 2.672932803630829
Epoch 20/100, Loss: 2.421118639409542
Epoch 21/100, Loss: 2.4433676078915596
Epoch 22/100, Loss: 2.586346708238125
Epoch 23/100, Loss: 2.4385557398200035
Epoch 24/100, Loss: 2.570920541882515
Epoch 25/100, Loss: 2.5761870816349983
Epoch 26/100, Loss: 2.467975489795208
Epoch 27/100, Loss: 2.5471803545951843
Epoch 28/100, Loss: 2.5090153366327286
Epoch 29/100, Loss: 2.517194390296936
Epoch 30/100, Loss: 2.436179392039776
Epoch 31/100, Loss: 2.599092975258827
Epoch 32/100, Loss: 2.464854247868061
Epoch 33/100, Loss: 2.586402289569378

Epoch 34/100, Loss: 2.783761754631996
Epoch 35/100, Loss: 2.5247894003987312
Epoch 36/100, Loss: 2.4546743407845497
Epoch 37/100, Loss: 2.4828929230570793
Epoch 38/100, Loss: 2.552184723317623
Epoch 39/100, Loss: 2.553244926035404
Epoch 40/100, Loss: 2.4388381466269493
Epoch 41/100, Loss: 2.4597108140587807
Epoch 42/100, Loss: 2.5168203189969063
Epoch 43/100, Loss: 2.423851765692234
Epoch 44/100, Loss: 2.4969361051917076
Epoch 45/100, Loss: 2.502368852496147
Epoch 46/100, Loss: 2.560562290251255
Epoch 47/100, Loss: 2.6209970265626907
Epoch 48/100, Loss: 2.4423826560378075
Epoch 49/100, Loss: 2.49372436106205
Epoch 50/100, Loss: 2.4442609921097755
Epoch 51/100, Loss: 2.5221177265048027

Epoch 52/100, Loss: 2.3391730040311813
Epoch 53/100, Loss: 2.5789739564061165
Epoch 54/100, Loss: 2.443583272397518
Epoch 55/100, Loss: 2.497242256999016
Epoch 56/100, Loss: 2.4478709921240807
Epoch 57/100, Loss: 2.5215984880924225
Epoch 58/100, Loss: 2.4099035784602165
Epoch 59/100, Loss: 2.4900223165750504
Epoch 60/100, Loss: 2.4643851965665817
Epoch 61/100, Loss: 2.5796019434928894
Epoch 62/100, Loss: 2.657603695988655
Epoch 63/100, Loss: 2.5763073414564133

Epoch 64/100, Loss: 2.514380007982254
Epoch 65/100, Loss: 2.412224620580673
Epoch 66/100, Loss: 2.470866061747074
Epoch 67/100, Loss: 2.425392299890518
Epoch 68/100, Loss: 2.493645027279854
Epoch 69/100, Loss: 2.45107588917017
Epoch 70/100, Loss: 2.463631398975849
Epoch 71/100, Loss: 2.466764748096466
Epoch 72/100, Loss: 2.5479302629828453
Epoch 73/100, Loss: 2.5576618388295174
Epoch 74/100, Loss: 2.48125322163105
Epoch 75/100, Loss: 2.479802094399929

Epoch 76/100, Loss: 2.3842138051986694
Epoch 77/100, Loss: 2.5598530545830727
Epoch 78/100, Loss: 2.5571798607707024
Epoch 79/100, Loss: 2.5574609339237213
Epoch 80/100, Loss: 2.324846051633358
Epoch 81/100, Loss: 2.499620757997036
Epoch 82/100, Loss: 2.4861390069127083
Epoch 83/100, Loss: 2.528210297226906
Epoch 84/100, Loss: 2.5929351076483727
Epoch 85/100, Loss: 2.4108445271849632
Epoch 86/100, Loss: 2.5318032652139664
Epoch 87/100, Loss: 2.552686557173729

Epoch 88/100, Loss: 2.5751176923513412
Epoch 89/100, Loss: 2.460782751441002
Epoch 90/100, Loss: 2.480435833334923
Epoch 91/100, Loss: 2.4818561673164368
Epoch 92/100, Loss: 2.616720698773861
Epoch 93/100, Loss: 2.406190887093544
Epoch 94/100, Loss: 2.5547773391008377
Epoch 95/100, Loss: 2.5468671321868896
Epoch 96/100, Loss: 2.6098629981279373
Epoch 97/100, Loss: 2.481174625456333
Epoch 98/100, Loss: 2.56722042709589
Epoch 99/100, Loss: 2.560614638030529

Epoch 100/100, Loss: 2.5541332736611366
Fold 2/5 done
Epoch 1/100, Loss: 3.232546530663967
Epoch 2/100, Loss: 2.8067950569093227
Epoch 3/100, Loss: 2.6203158982098103
Epoch 4/100, Loss: 2.855728290975094
Epoch 5/100, Loss: 2.370744600892067
Epoch 6/100, Loss: 2.5380201414227486
Epoch 7/100, Loss: 2.557707466185093
Epoch 8/100, Loss: 2.5683508291840553
Epoch 9/100, Loss: 2.6979565024375916
Epoch 10/100, Loss: 2.3818856328725815

Epoch 11/100, Loss: 2.362195886671543
Epoch 12/100, Loss: 2.4743542596697807
Epoch 13/100, Loss: 2.562569998204708
Epoch 14/100, Loss: 2.5638871863484383
Epoch 15/100, Loss: 2.4487306773662567
Epoch 16/100, Loss: 2.5321380868554115
Epoch 17/100, Loss: 2.7284800335764885
Epoch 18/100, Loss: 2.55169927328825
Epoch 19/100, Loss: 2.639336135238409
Epoch 20/100, Loss: 2.525347650051117
Epoch 21/100, Loss: 2.7272606566548347
Epoch 22/100, Loss: 2.6155777275562286
Epoch 23/100, Loss: 2.6439853236079216
Epoch 24/100, Loss: 2.8769491612911224
Epoch 25/100, Loss: 2.5761186107993126
Epoch 26/100, Loss: 2.5682868659496307
Epoch 27/100, Loss: 2.592571847140789

Epoch 28/100, Loss: 2.5832555294036865
Epoch 29/100, Loss: 2.430124543607235
Epoch 30/100, Loss: 2.6984391063451767
Epoch 31/100, Loss: 2.666302964091301
Epoch 32/100, Loss: 2.5255403965711594
Epoch 33/100, Loss: 2.5855634436011314
Epoch 34/100, Loss: 2.528534583747387
Epoch 35/100, Loss: 2.5271594673395157
Epoch 36/100, Loss: 2.5981492027640343
Epoch 37/100, Loss: 2.570345014333725
Epoch 38/100, Loss: 2.401296339929104

Epoch 39/100, Loss: 2.5098241716623306
Epoch 40/100, Loss: 3.0682981684803963
Epoch 41/100, Loss: 2.385073035955429
Epoch 42/100, Loss: 2.4586007595062256
Epoch 43/100, Loss: 2.7894423976540565
Epoch 44/100, Loss: 2.235477536916733
Epoch 45/100, Loss: 2.5647019296884537
Epoch 46/100, Loss: 2.714662626385689
Epoch 47/100, Loss: 2.613914154469967
Epoch 48/100, Loss: 2.5643235072493553
Epoch 49/100, Loss: 2.583017200231552

Epoch 50/100, Loss: 2.7654535472393036
Epoch 51/100, Loss: 2.539341554045677
Epoch 52/100, Loss: 2.588409073650837
Epoch 53/100, Loss: 2.653663106262684
Epoch 54/100, Loss: 2.582805596292019
Epoch 55/100, Loss: 2.932071551680565
Epoch 56/100, Loss: 2.605177439749241
Epoch 57/100, Loss: 2.5360930040478706
Epoch 58/100, Loss: 2.552177481353283
Epoch 59/100, Loss: 2.542413428425789
Epoch 60/100, Loss: 2.4881415218114853

Epoch 61/100, Loss: 2.381932035088539
Epoch 62/100, Loss: 2.4770788103342056
Epoch 63/100, Loss: 2.9574077874422073
Epoch 64/100, Loss: 2.2998670041561127
Epoch 65/100, Loss: 2.681305579841137
Epoch 66/100, Loss: 2.6303540021181107
Epoch 67/100, Loss: 2.4403840228915215
Epoch 68/100, Loss: 2.7166014537215233
Epoch 69/100, Loss: 2.609224498271942
Epoch 70/100, Loss: 2.558942995965481
Epoch 71/100, Loss: 2.282281309366226
Epoch 72/100, Loss: 2.6430268585681915
Epoch 73/100, Loss: 2.5545517057180405
Epoch 74/100, Loss: 2.670659624040127

Epoch 75/100, Loss: 2.4813452437520027
Epoch 76/100, Loss: 2.6013502702116966
Epoch 77/100, Loss: 2.7146293371915817
Epoch 78/100, Loss: 2.3768585845828056
Epoch 79/100, Loss: 2.619005464017391
Epoch 80/100, Loss: 2.6010193079710007
Epoch 81/100, Loss: 2.524661384522915
Epoch 82/100, Loss: 2.4524672776460648
Epoch 83/100, Loss: 2.6830590069293976
Epoch 84/100, Loss: 2.6586095467209816
Epoch 85/100, Loss: 2.639730840921402
Epoch 86/100, Loss: 2.5384766086935997
Epoch 87/100, Loss: 2.4547375813126564
Epoch 88/100, Loss: 2.583059623837471
Epoch 89/100, Loss: 2.7565717101097107
Epoch 90/100, Loss: 2.871328204870224
Epoch 91/100, Loss: 2.749597392976284
Epoch 92/100, Loss: 2.22945936024189

Epoch 93/100, Loss: 2.5566214695572853
Epoch 94/100, Loss: 2.933718428015709
Epoch 95/100, Loss: 2.345874570310116
Epoch 96/100, Loss: 2.515239715576172
Epoch 97/100, Loss: 3.470166116952896
Epoch 98/100, Loss: 2.488664634525776
Epoch 99/100, Loss: 2.346038918942213
Epoch 100/100, Loss: 3.0283680632710457
Fold 3/5 done
Epoch 1/100, Loss: 3.9671020060777664
Epoch 2/100, Loss: 3.1112251952290535
Epoch 3/100, Loss: 2.9259586930274963
Epoch 4/100, Loss: 2.9471253976225853
Epoch 5/100, Loss: 3.088786616921425
Epoch 6/100, Loss: 3.314453460276127
Epoch 7/100, Loss: 2.895092412829399
Epoch 8/100, Loss: 3.1126224026083946
Epoch 9/100, Loss: 3.8123213052749634

Epoch 10/100, Loss: 3.163464553654194
Epoch 11/100, Loss: 3.053460568189621
Epoch 12/100, Loss: 3.0259105786681175
Epoch 13/100, Loss: 2.6565504670143127
Epoch 14/100, Loss: 3.0025357604026794
Epoch 15/100, Loss: 3.1028615534305573
Epoch 16/100, Loss: 3.6211559027433395
Epoch 17/100, Loss: 2.959384173154831
Epoch 18/100, Loss: 2.879977747797966
Epoch 19/100, Loss: 2.8863750621676445
Epoch 20/100, Loss: 3.159853518009186
Epoch 21/100, Loss: 3.0550744608044624
Epoch 22/100, Loss: 3.225010462105274
Epoch 23/100, Loss: 3.229846775531769
Epoch 24/100, Loss: 3.266118034720421
Epoch 25/100, Loss: 3.054772526025772
Epoch 26/100, Loss: 3.1324398517608643
Epoch 27/100, Loss: 3.057793468236923

Epoch 28/100, Loss: 2.971134528517723
Epoch 29/100, Loss: 2.7121861428022385
Epoch 30/100, Loss: 3.1513169184327126
Epoch 31/100, Loss: 3.232170470058918
Epoch 32/100, Loss: 3.1317637264728546
Epoch 33/100, Loss: 3.0491736978292465
Epoch 34/100, Loss: 3.227212682366371
Epoch 35/100, Loss: 3.2920399010181427
Epoch 36/100, Loss: 2.8994625210762024
Epoch 37/100, Loss: 3.196800410747528
Epoch 38/100, Loss: 3.0759040862321854
Epoch 39/100, Loss: 3.0967395529150963
Epoch 40/100, Loss: 3.075092151761055
Epoch 41/100, Loss: 3.3560444116592407
Epoch 42/100, Loss: 3.0997941195964813
Epoch 43/100, Loss: 3.138813093304634
Epoch 44/100, Loss: 2.9196625351905823

Epoch 45/100, Loss: 3.085271954536438
Epoch 46/100, Loss: 3.1458791941404343
Epoch 47/100, Loss: 3.02774316072464
Epoch 48/100, Loss: 2.9943654984235764
Epoch 49/100, Loss: 2.9302705377340317
Epoch 50/100, Loss: 3.2822085916996
Epoch 51/100, Loss: 3.166944697499275
Epoch 52/100, Loss: 3.050940990447998
Epoch 53/100, Loss: 2.9478639513254166
Epoch 54/100, Loss: 3.784739628434181
Epoch 55/100, Loss: 2.9970958679914474
Epoch 56/100, Loss: 3.325492411851883
Epoch 57/100, Loss: 2.987930618226528
Epoch 58/100, Loss: 2.901959903538227
Epoch 59/100, Loss: 2.9494300186634064
Epoch 60/100, Loss: 3.105750061571598
Epoch 61/100, Loss: 3.082272380590439

Epoch 62/100, Loss: 2.9706256836652756
Epoch 63/100, Loss: 3.0450368970632553
Epoch 64/100, Loss: 3.2573942244052887
Epoch 65/100, Loss: 3.0783072263002396
Epoch 66/100, Loss: 3.076694831252098
Epoch 67/100, Loss: 2.875021316111088
Epoch 68/100, Loss: 3.204455643892288
Epoch 69/100, Loss: 3.0438493192195892
Epoch 70/100, Loss: 3.8145439624786377
Epoch 71/100, Loss: 2.988244965672493
Epoch 72/100, Loss: 2.9040988981723785

Epoch 73/100, Loss: 2.9406067430973053
Epoch 74/100, Loss: 3.232424259185791
Epoch 75/100, Loss: 2.9294838830828667
Epoch 76/100, Loss: 3.1065749153494835
Epoch 77/100, Loss: 2.839080661535263
Epoch 78/100, Loss: 3.0894570648670197
Epoch 79/100, Loss: 3.0860660523176193
Epoch 80/100, Loss: 3.045544385910034
Epoch 81/100, Loss: 3.17899726331234
Epoch 82/100, Loss: 2.9174295142292976
Epoch 83/100, Loss: 3.4178380370140076
Epoch 84/100, Loss: 3.2676724195480347
Epoch 85/100, Loss: 2.9732050597667694
Epoch 86/100, Loss: 3.1631930097937584

Epoch 87/100, Loss: 3.1202768832445145
Epoch 88/100, Loss: 3.64155612885952
Epoch 89/100, Loss: 3.1168903559446335
Epoch 90/100, Loss: 2.903384208679199
Epoch 91/100, Loss: 3.224092498421669
Epoch 92/100, Loss: 2.9458827674388885
Epoch 93/100, Loss: 2.969621554017067
Epoch 94/100, Loss: 3.1210209280252457
Epoch 95/100, Loss: 3.0798298567533493
Epoch 96/100, Loss: 3.006627842783928
Epoch 97/100, Loss: 3.091969847679138

Epoch 98/100, Loss: 3.108518809080124
Epoch 99/100, Loss: 2.9934698045253754
Epoch 100/100, Loss: 3.0318931341171265
Fold 4/5 done
Epoch 1/100, Loss: 2.0758172161877155
Epoch 2/100, Loss: 2.1549310833215714
Epoch 3/100, Loss: 2.1594626158475876
Epoch 4/100, Loss: 2.214481897652149
Epoch 5/100, Loss: 2.4757151007652283
Epoch 6/100, Loss: 2.3296359553933144
Epoch 7/100, Loss: 2.4651268124580383
Epoch 8/100, Loss: 2.384293109178543

Epoch 9/100, Loss: 2.2231451719999313
Epoch 10/100, Loss: 2.2231158688664436
Epoch 11/100, Loss: 2.1949318051338196
Epoch 12/100, Loss: 2.4576037377119064
Epoch 13/100, Loss: 2.0813424065709114
Epoch 14/100, Loss: 2.3507664501667023
Epoch 15/100, Loss: 2.1597819328308105
Epoch 16/100, Loss: 2.3991792500019073
Epoch 17/100, Loss: 2.2069081887602806
Epoch 18/100, Loss: 2.334941118955612
Epoch 19/100, Loss: 2.4317609071731567
Epoch 20/100, Loss: 2.4473768323659897
Epoch 21/100, Loss: 2.46500513702631
Epoch 22/100, Loss: 2.3237848430871964
Epoch 23/100, Loss: 2.156114637851715

Epoch 24/100, Loss: 2.3063539266586304
Epoch 25/100, Loss: 2.294897384941578
Epoch 26/100, Loss: 2.3735892549157143
Epoch 27/100, Loss: 2.2660916596651077
Epoch 28/100, Loss: 2.399079903960228
Epoch 29/100, Loss: 2.267690859735012
Epoch 30/100, Loss: 2.459335871040821
Epoch 31/100, Loss: 2.3566762506961823
Epoch 32/100, Loss: 2.343326300382614
Epoch 33/100, Loss: 2.0943276807665825
Epoch 34/100, Loss: 2.1681156754493713
Epoch 35/100, Loss: 2.22190473228693
Epoch 36/100, Loss: 2.065957024693489
Epoch 37/100, Loss: 2.110607512295246
Epoch 38/100, Loss: 2.1557332053780556
Epoch 39/100, Loss: 2.2892086803913116
Epoch 40/100, Loss: 2.18908528983593

Epoch 41/100, Loss: 2.308377258479595
Epoch 42/100, Loss: 2.439729429781437
Epoch 43/100, Loss: 2.4535649716854095
Epoch 44/100, Loss: 2.104226239025593
Epoch 45/100, Loss: 1.9645323753356934
Epoch 46/100, Loss: 2.2162512689828873
Epoch 47/100, Loss: 2.2816765159368515
Epoch 48/100, Loss: 2.177124708890915
Epoch 49/100, Loss: 2.4936850890517235
Epoch 50/100, Loss: 2.4189577028155327
Epoch 51/100, Loss: 2.256023198366165
Epoch 52/100, Loss: 2.482049509882927
Epoch 53/100, Loss: 2.1862968653440475
Epoch 54/100, Loss: 2.1736282482743263
Epoch 55/100, Loss: 2.265537090599537
Epoch 56/100, Loss: 1.960379771888256
Epoch 57/100, Loss: 2.364606484770775
Epoch 58/100, Loss: 2.202732138335705

Epoch 59/100, Loss: 2.211122378706932
Epoch 60/100, Loss: 2.4874259755015373
Epoch 61/100, Loss: 2.0714286640286446
Epoch 62/100, Loss: 2.095571029931307
Epoch 63/100, Loss: 2.2666308656334877
Epoch 64/100, Loss: 2.3340419307351112
Epoch 65/100, Loss: 2.3695829287171364
Epoch 66/100, Loss: 2.434673562645912
Epoch 67/100, Loss: 2.4114246517419815
Epoch 68/100, Loss: 2.0692432895302773
Epoch 69/100, Loss: 2.3084555491805077
Epoch 70/100, Loss: 2.2604740485548973
Epoch 71/100, Loss: 2.4218231216073036
Epoch 72/100, Loss: 2.35936526209116

Epoch 73/100, Loss: 2.216894492506981
Epoch 74/100, Loss: 2.1559871211647987
Epoch 75/100, Loss: 2.3359364569187164
Epoch 76/100, Loss: 2.1161911860108376
Epoch 77/100, Loss: 2.1582909524440765
Epoch 78/100, Loss: 2.4130637645721436
Epoch 79/100, Loss: 2.3991457670927048
Epoch 80/100, Loss: 2.3202975392341614
Epoch 81/100, Loss: 2.2830350026488304
Epoch 82/100, Loss: 2.392579033970833
Epoch 83/100, Loss: 2.2696264907717705
Epoch 84/100, Loss: 2.330961287021637
Epoch 85/100, Loss: 2.1996250450611115
Epoch 86/100, Loss: 2.32193610817194
Epoch 87/100, Loss: 2.440689541399479
Epoch 88/100, Loss: 2.407063849270344
Epoch 89/100, Loss: 2.1940606385469437
Epoch 90/100, Loss: 2.4633685871958733

Epoch 91/100, Loss: 2.490214169025421
Epoch 92/100, Loss: 2.3499632477760315
Epoch 93/100, Loss: 2.1541339829564095
Epoch 94/100, Loss: 2.2994924634695053
Epoch 95/100, Loss: 2.156476490199566
Epoch 96/100, Loss: 2.282227136194706
Epoch 97/100, Loss: 2.3149693980813026
Epoch 98/100, Loss: 2.1778949350118637
Epoch 99/100, Loss: 2.291918210685253
Epoch 100/100, Loss: 2.3710713982582092
Fold 5/5 done

In [11]:
ap = average_precision_score(y_true, anomaly_scores)
print(f"Deep SVDD AP (5-fold CV) = {ap:.4f}")
sb.glue("GBG500_ap_spectral_deep_svdd", float(ap))

Deep SVDD AP (5-fold CV) = 0.7265