In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import average_precision_score
from sklearn.model_selection import StratifiedKFold
from pyod.models.deep_svdd import DeepSVDD
import sys
import scrapbook as sb

sys.path.append('..')
from utils import reshape_to_numpy, interpolate_missing_values, denoise_data, compute_spectrograms, time_avg_pooling

In [2]:
seed = 1
sampling_rate = 10
nperseg=64
noverlap=32
accel_cutoff = 0.4
accel_order = 30
gyro_cutoff = 0.6
gyro_order = 20
batch_size = 32
epochs = 100
hidden_neurons = [128, 64, 32]
n_splits = 5

In [3]:
# Parameters
seed = 15

In [4]:
rng = np.random.RandomState(seed)

In [5]:
data = pd.read_parquet("../data/GBG500.parquet")
data

,ride_id,time_index,ax,ay,az,rx,ry,rz
0,005043f1a7520cebf1e17fd166a00a3190e2433530f236...,0,-2.512796,-9.385012,-1.053078,-0.009155,0.009155,-0.201416
1,005043f1a7520cebf1e17fd166a00a3190e2433530f236...,100,-2.491268,-9.385012,-1.079390,-0.036621,0.027465,-0.155639
2,005043f1a7520cebf1e17fd166a00a3190e2433530f236...,200,-2.534324,-9.382022,-1.030952,0.036621,0.027465,-0.073242
3,005043f1a7520cebf1e17fd166a00a3190e2433530f236...,300,-2.488278,-9.383218,-1.091948,-0.045776,0.036621,-0.183105
4,005043f1a7520cebf1e17fd166a00a3190e2433530f236...,400,-2.483494,-9.382022,-1.100320,-0.045776,0.027465,-0.192260
...,...,...,...,...,...,...,...,...
1529542,ffb6f2f5dc6ba768d88dc0bc1af4cad235526aa9e24168...,241300,0.459862,-9.140430,-3.318900,1.556396,-0.091552,0.274658
1529543,ffb6f2f5dc6ba768d88dc0bc1af4cad235526aa9e24168...,241400,0.455676,-9.140430,-3.321292,1.583861,-0.119018,0.274658
1529544,ffb6f2f5dc6ba768d88dc0bc1af4cad235526aa9e24168...,241500,0.459862,-9.139832,-3.317704,1.583861,-0.109863,0.274658
1529545,ffb6f2f5dc6ba768d88dc0bc1af4cad235526aa9e24168...,241600,0.456274,-9.142224,-3.321292,1.574707,-0.137329,0.283813
1529546,ffb6f2f5dc6ba768d88dc0bc1af4cad235526aa9e24168...,241700,0.458666,-9.139832,-3.320694,1.574707,-0.137329,0.274658

In [6]:
labels = pd.read_csv("../data/GBG500_labels.csv")
labels.columns = labels.columns.str.lower()
ride_order_df = pd.DataFrame({"ride_id": data["ride_id"].unique()})
labels_sorted = ride_order_df.merge(
    labels,
    on="ride_id",
    how="left"
)
labels_sorted

                                               ride_id        label
0    005043f1a7520cebf1e17fd166a00a3190e2433530f236...         Safe
1    00d223cb7aecc9c0cc5871e32a6c45027a068eba07c572...     Reckless
2    02288a4aeca044203394e982e76b87818021dea2b34df9...         Safe
3    0236bdcf13d473ea24d97f5eaeea459f257dffac005694...  Bad weather
4    0238e5dd85143f1b6c59b200bc32f14361b8fc84c51a87...         Safe
..                                                 ...          ...
495  fe5d7f84d692bbccad8bd566a3ad5c3108fa9f90acd671...         Safe
496  fe67169632306d4668b2affedef510df2cb43e2fb41220...         Safe
497  fee44667fdc8ab4995c702fc3bd36178de0b1ca2c64687...         Safe
498  ff79b2e945b93c2a5efc3a06365267b3a160e7849ba57d...         Safe
499  ffb6f2f5dc6ba768d88dc0bc1af4cad235526aa9e24168...         Safe

[500 rows x 2 columns]

In [7]:
data_np = reshape_to_numpy(
    data,
    features = ["ax", "ay", "az", "rx", "ry", "rz"],
    max_timestamps = 4800
)

data_np_clean = interpolate_missing_values(
    data_np,
    method='linear',
    limit=None
)

data_np_clean = denoise_data(
    data=data_np_clean,
    accel_indices=[0, 1, 2],
    gyro_indices=[3, 4, 5],
    accel_cutoff=accel_cutoff,
    accel_order=accel_order,
    gyro_cutoff=gyro_cutoff,
    gyro_order=gyro_order,
)

In [8]:
# Compute spectrograms for all rides
spectrograms_array = compute_spectrograms(data_np_clean, sampling_rate, nperseg, noverlap)
spectrograms_array.shape

(500, 149, 6, 33)

In [9]:
# Aggregate spectrograms using time-averaged pooling
X_feat = time_avg_pooling(spectrograms_array)
X_feat.shape

(500, 198)

In [10]:
# 5-fold stratified CV with Deep SVDD
skf = StratifiedKFold(n_splits=n_splits, shuffle=True, random_state=rng.randint(1000))
y_true = (labels_sorted['label'] == 'Reckless').astype(int).values
anomaly_scores = np.full(len(y_true), np.nan)

for fold, (train_idx, test_idx) in enumerate(skf.split(X_feat, y_true)):
    sc = StandardScaler()
    X_train = sc.fit_transform(X_feat[train_idx])
    X_test = sc.transform(X_feat[test_idx])

    np.random.seed(rng.randint(1000))
    model = DeepSVDD(
        n_features=X_train.shape[1],
        hidden_neurons=hidden_neurons,
        epochs=epochs,
        batch_size=batch_size,
        random_state=rng.randint(1000),
    )
    model.fit(X_train)
    anomaly_scores[test_idx] = model.decision_function(X_test)
    print(f"Fold {fold+1}/{n_splits} done")

Epoch 1/100, Loss: 2.5789029970765114
Epoch 2/100, Loss: 2.6586594730615616
Epoch 3/100, Loss: 2.714067041873932
Epoch 4/100, Loss: 2.5687753409147263
Epoch 5/100, Loss: 2.3362646475434303
Epoch 6/100, Loss: 2.8832333609461784
Epoch 7/100, Loss: 2.3314481042325497
Epoch 8/100, Loss: 2.9881894513964653
Epoch 9/100, Loss: 2.8491171449422836
Epoch 10/100, Loss: 2.390319839119911
Epoch 11/100, Loss: 2.622142069041729
Epoch 12/100, Loss: 2.738435171544552
Epoch 13/100, Loss: 2.5588227286934853
Epoch 14/100, Loss: 2.445123016834259
Epoch 15/100, Loss: 2.6755814030766487
Epoch 16/100, Loss: 2.5508252009749413
Epoch 17/100, Loss: 2.6369319409132004
Epoch 18/100, Loss: 2.3864798322319984

Epoch 19/100, Loss: 3.0649977922439575
Epoch 20/100, Loss: 2.420788623392582
Epoch 21/100, Loss: 2.664231337606907
Epoch 22/100, Loss: 2.615966349840164
Epoch 23/100, Loss: 2.7308124229311943
Epoch 24/100, Loss: 2.640966333448887
Epoch 25/100, Loss: 2.4419243782758713
Epoch 26/100, Loss: 2.3015841245651245
Epoch 27/100, Loss: 2.5224331840872765
Epoch 28/100, Loss: 2.3971783742308617
Epoch 29/100, Loss: 2.629357486963272
Epoch 30/100, Loss: 2.4893036633729935

Epoch 31/100, Loss: 2.5335932299494743
Epoch 32/100, Loss: 2.772405691444874
Epoch 33/100, Loss: 2.747854046523571
Epoch 34/100, Loss: 2.475302740931511
Epoch 35/100, Loss: 2.622665837407112
Epoch 36/100, Loss: 2.6804391369223595
Epoch 37/100, Loss: 2.5834754183888435
Epoch 38/100, Loss: 2.769499033689499
Epoch 39/100, Loss: 2.603186570107937
Epoch 40/100, Loss: 2.588120475411415
Epoch 41/100, Loss: 2.587360478937626
Epoch 42/100, Loss: 2.477099873125553
Epoch 43/100, Loss: 2.552118182182312
Epoch 44/100, Loss: 2.7188212797045708

Epoch 45/100, Loss: 2.6325052604079247
Epoch 46/100, Loss: 2.4601808711886406
Epoch 47/100, Loss: 2.604835532605648
Epoch 48/100, Loss: 2.648418106138706
Epoch 49/100, Loss: 2.724471129477024
Epoch 50/100, Loss: 2.596586264669895
Epoch 51/100, Loss: 2.502923868596554
Epoch 52/100, Loss: 2.446785405278206
Epoch 53/100, Loss: 2.5515106692910194
Epoch 54/100, Loss: 2.590499997138977
Epoch 55/100, Loss: 2.701975777745247
Epoch 56/100, Loss: 2.619287133216858

Epoch 57/100, Loss: 2.6640863195061684
Epoch 58/100, Loss: 2.5473972484469414
Epoch 59/100, Loss: 2.4409705474972725
Epoch 60/100, Loss: 3.035548411309719
Epoch 61/100, Loss: 2.493886820971966
Epoch 62/100, Loss: 2.518955811858177
Epoch 63/100, Loss: 3.2668636068701744
Epoch 64/100, Loss: 2.5041882023215294
Epoch 65/100, Loss: 2.683095544576645
Epoch 66/100, Loss: 2.700582079589367
Epoch 67/100, Loss: 2.6260511577129364
Epoch 68/100, Loss: 2.291816495358944

Epoch 69/100, Loss: 2.7359423264861107
Epoch 70/100, Loss: 2.5031787529587746
Epoch 71/100, Loss: 2.6875481083989143
Epoch 72/100, Loss: 2.562275804579258
Epoch 73/100, Loss: 2.5801110044121742
Epoch 74/100, Loss: 3.1885619312524796
Epoch 75/100, Loss: 2.554350644350052
Epoch 76/100, Loss: 2.7127224802970886
Epoch 77/100, Loss: 2.5533696338534355
Epoch 78/100, Loss: 2.5410261526703835
Epoch 79/100, Loss: 2.4989601597189903
Epoch 80/100, Loss: 2.5984823629260063
Epoch 81/100, Loss: 2.510769486427307
Epoch 82/100, Loss: 2.395886428654194

Epoch 83/100, Loss: 2.436665378510952
Epoch 84/100, Loss: 2.6767032518982887
Epoch 85/100, Loss: 2.384810231626034
Epoch 86/100, Loss: 2.5112926959991455
Epoch 87/100, Loss: 2.5916881635785103
Epoch 88/100, Loss: 2.7661782428622246
Epoch 89/100, Loss: 2.6283796429634094
Epoch 90/100, Loss: 2.583834730088711
Epoch 91/100, Loss: 2.477509744465351
Epoch 92/100, Loss: 2.5324883088469505
Epoch 93/100, Loss: 2.608205199241638
Epoch 94/100, Loss: 2.290323533117771
Epoch 95/100, Loss: 2.339232809841633
Epoch 96/100, Loss: 2.636896602809429
Epoch 97/100, Loss: 2.7402053102850914
Epoch 98/100, Loss: 2.6430919468402863
Epoch 99/100, Loss: 3.0600646510720253

Epoch 100/100, Loss: 2.7702685594558716
Fold 1/5 done
Epoch 1/100, Loss: 1.6036612913012505
Epoch 2/100, Loss: 1.8327768221497536
Epoch 3/100, Loss: 1.7601223029196262
Epoch 4/100, Loss: 1.8099783286452293
Epoch 5/100, Loss: 1.7287934944033623
Epoch 6/100, Loss: 1.727878712117672
Epoch 7/100, Loss: 1.5842876583337784
Epoch 8/100, Loss: 1.7328814417123795
Epoch 9/100, Loss: 1.791760414838791
Epoch 10/100, Loss: 2.122243769466877
Epoch 11/100, Loss: 1.7755928114056587
Epoch 12/100, Loss: 1.6888795420527458
Epoch 13/100, Loss: 1.7730647549033165
Epoch 14/100, Loss: 1.7594834193587303
Epoch 15/100, Loss: 1.728502955287695
Epoch 16/100, Loss: 1.7655551545321941

Epoch 17/100, Loss: 1.8269696421921253
Epoch 18/100, Loss: 1.6551220268011093
Epoch 19/100, Loss: 1.6402459517121315
Epoch 20/100, Loss: 1.7932054325938225
Epoch 21/100, Loss: 1.757637195289135
Epoch 22/100, Loss: 1.7262436859309673
Epoch 23/100, Loss: 1.6893934309482574
Epoch 24/100, Loss: 1.8198014572262764
Epoch 25/100, Loss: 1.719915434718132
Epoch 26/100, Loss: 1.8729776218533516
Epoch 27/100, Loss: 1.6523199081420898
Epoch 28/100, Loss: 1.8950436189770699
Epoch 29/100, Loss: 1.7306410893797874
Epoch 30/100, Loss: 1.8508225604891777
Epoch 31/100, Loss: 1.7500827684998512
Epoch 32/100, Loss: 1.7991123273968697
Epoch 33/100, Loss: 1.7765223868191242
Epoch 34/100, Loss: 1.6823573485016823
Epoch 35/100, Loss: 1.839979663491249

Epoch 36/100, Loss: 1.6345576010644436
Epoch 37/100, Loss: 1.6137545965611935
Epoch 38/100, Loss: 1.7458528354763985
Epoch 39/100, Loss: 1.7627587616443634
Epoch 40/100, Loss: 1.6905412636697292
Epoch 41/100, Loss: 1.8094109445810318
Epoch 42/100, Loss: 1.7830656543374062
Epoch 43/100, Loss: 1.8532538786530495
Epoch 44/100, Loss: 1.8172853738069534
Epoch 45/100, Loss: 1.6968513876199722
Epoch 46/100, Loss: 1.7847221493721008
Epoch 47/100, Loss: 1.7991712242364883
Epoch 48/100, Loss: 1.7747405469417572
Epoch 49/100, Loss: 1.8061928004026413
Epoch 50/100, Loss: 1.8360428363084793
Epoch 51/100, Loss: 2.153095670044422
Epoch 52/100, Loss: 1.7560666725039482
Epoch 53/100, Loss: 1.7882960252463818

Epoch 54/100, Loss: 1.590799506753683
Epoch 55/100, Loss: 1.8851313367486
Epoch 56/100, Loss: 1.748374618589878
Epoch 57/100, Loss: 1.740750938653946
Epoch 58/100, Loss: 1.5995236560702324
Epoch 59/100, Loss: 1.6779375448822975
Epoch 60/100, Loss: 1.7631803713738918
Epoch 61/100, Loss: 1.7224828377366066
Epoch 62/100, Loss: 1.6137493327260017
Epoch 63/100, Loss: 1.6781542040407658
Epoch 64/100, Loss: 1.7955137714743614
Epoch 65/100, Loss: 1.6858612708747387
Epoch 66/100, Loss: 1.6974770352244377
Epoch 67/100, Loss: 1.6946593075990677
Epoch 68/100, Loss: 1.829280748963356
Epoch 69/100, Loss: 1.6679052710533142
Epoch 70/100, Loss: 1.6302953884005547
Epoch 71/100, Loss: 1.7245930582284927

Epoch 72/100, Loss: 1.836229581385851
Epoch 73/100, Loss: 1.6996668353676796
Epoch 74/100, Loss: 1.8106214329600334
Epoch 75/100, Loss: 1.7886535562574863
Epoch 76/100, Loss: 1.771302293986082
Epoch 77/100, Loss: 1.8450170010328293
Epoch 78/100, Loss: 1.7307689227163792
Epoch 79/100, Loss: 1.7478626295924187
Epoch 80/100, Loss: 1.5707639046013355
Epoch 81/100, Loss: 1.4947731792926788
Epoch 82/100, Loss: 1.6822508051991463
Epoch 83/100, Loss: 1.8310075774788857
Epoch 84/100, Loss: 1.769812062382698
Epoch 85/100, Loss: 1.7204275354743004
Epoch 86/100, Loss: 1.7345301657915115
Epoch 87/100, Loss: 1.6306964866816998
Epoch 88/100, Loss: 2.0680748149752617

Epoch 89/100, Loss: 1.660926066339016
Epoch 90/100, Loss: 1.75987608730793
Epoch 91/100, Loss: 1.7257401645183563
Epoch 92/100, Loss: 1.8085259646177292
Epoch 93/100, Loss: 1.7355571165680885
Epoch 94/100, Loss: 1.6629014126956463
Epoch 95/100, Loss: 1.6775983832776546
Epoch 96/100, Loss: 1.8184698931872845
Epoch 97/100, Loss: 1.7222353592514992
Epoch 98/100, Loss: 1.738583229482174
Epoch 99/100, Loss: 1.6041105911135674
Epoch 100/100, Loss: 1.6621651202440262
Fold 2/5 done
Epoch 1/100, Loss: 1.8636359199881554
Epoch 2/100, Loss: 1.8938867300748825
Epoch 3/100, Loss: 2.1549940183758736

Epoch 4/100, Loss: 2.1870710849761963
Epoch 5/100, Loss: 1.9543020874261856
Epoch 6/100, Loss: 1.9617104530334473
Epoch 7/100, Loss: 2.0080634132027626
Epoch 8/100, Loss: 2.1128337010741234
Epoch 9/100, Loss: 2.231249764561653
Epoch 10/100, Loss: 2.1377294659614563
Epoch 11/100, Loss: 2.117980919778347
Epoch 12/100, Loss: 2.2027243971824646
Epoch 13/100, Loss: 2.1684021577239037
Epoch 14/100, Loss: 1.986750178039074
Epoch 15/100, Loss: 2.1889722272753716
Epoch 16/100, Loss: 2.059612348675728
Epoch 17/100, Loss: 2.2557938024401665
Epoch 18/100, Loss: 2.0559391900897026
Epoch 19/100, Loss: 1.9890405014157295
Epoch 20/100, Loss: 2.1871501728892326

Epoch 21/100, Loss: 2.084686763584614
Epoch 22/100, Loss: 2.1260654032230377
Epoch 23/100, Loss: 2.1610252782702446
Epoch 24/100, Loss: 2.0342383608222008
Epoch 25/100, Loss: 2.0041040182113647
Epoch 26/100, Loss: 2.160819485783577
Epoch 27/100, Loss: 2.1818676367402077
Epoch 28/100, Loss: 2.2657753452658653
Epoch 29/100, Loss: 2.033021092414856
Epoch 30/100, Loss: 2.0237430706620216
Epoch 31/100, Loss: 2.1678799241781235
Epoch 32/100, Loss: 2.0933530628681183
Epoch 33/100, Loss: 1.9852142855525017
Epoch 34/100, Loss: 2.2040355503559113
Epoch 35/100, Loss: 2.1039948984980583
Epoch 36/100, Loss: 2.370097354054451
Epoch 37/100, Loss: 2.047021195292473

Epoch 38/100, Loss: 2.2950988560914993
Epoch 39/100, Loss: 2.2134471386671066
Epoch 40/100, Loss: 2.0038939639925957
Epoch 41/100, Loss: 1.8760970085859299
Epoch 42/100, Loss: 2.096499226987362
Epoch 43/100, Loss: 2.03517634421587
Epoch 44/100, Loss: 2.1151604875922203
Epoch 45/100, Loss: 2.2537508085370064
Epoch 46/100, Loss: 1.8949755132198334
Epoch 47/100, Loss: 2.037173680961132
Epoch 48/100, Loss: 2.099441558122635
Epoch 49/100, Loss: 1.9621936082839966
Epoch 50/100, Loss: 2.9362214654684067
Epoch 51/100, Loss: 2.1917154043912888
Epoch 52/100, Loss: 2.0647727251052856
Epoch 53/100, Loss: 2.0243517085909843
Epoch 54/100, Loss: 2.1427532881498337

Epoch 55/100, Loss: 1.990773320198059
Epoch 56/100, Loss: 2.0401114150881767
Epoch 57/100, Loss: 2.0588440373539925
Epoch 58/100, Loss: 2.265851929783821
Epoch 59/100, Loss: 2.126929648220539
Epoch 60/100, Loss: 2.045157417654991
Epoch 61/100, Loss: 2.215601660311222
Epoch 62/100, Loss: 2.0514018908143044
Epoch 63/100, Loss: 2.1908995509147644
Epoch 64/100, Loss: 2.248705044388771
Epoch 65/100, Loss: 1.981664463877678
Epoch 66/100, Loss: 2.15081687271595
Epoch 67/100, Loss: 2.1386286914348602
Epoch 68/100, Loss: 1.967319279909134
Epoch 69/100, Loss: 2.2150785624980927
Epoch 70/100, Loss: 2.0192756280303
Epoch 71/100, Loss: 2.2728075981140137
Epoch 72/100, Loss: 2.05756539106369

Epoch 73/100, Loss: 1.9978318139910698
Epoch 74/100, Loss: 2.0418932288885117
Epoch 75/100, Loss: 2.1710629016160965
Epoch 76/100, Loss: 2.1394261717796326
Epoch 77/100, Loss: 1.8784552440047264
Epoch 78/100, Loss: 1.9822550788521767
Epoch 79/100, Loss: 2.210097797214985
Epoch 80/100, Loss: 2.0211383774876595
Epoch 81/100, Loss: 2.0048304200172424
Epoch 82/100, Loss: 2.242820657789707
Epoch 83/100, Loss: 1.9203355982899666
Epoch 84/100, Loss: 1.9575233161449432
Epoch 85/100, Loss: 1.9703455492854118

Epoch 86/100, Loss: 2.160047985613346
Epoch 87/100, Loss: 2.0709272250533104
Epoch 88/100, Loss: 2.224792867898941
Epoch 89/100, Loss: 1.9248420372605324
Epoch 90/100, Loss: 1.9969920739531517
Epoch 91/100, Loss: 1.8654760792851448
Epoch 92/100, Loss: 2.168544739484787
Epoch 93/100, Loss: 1.9973969832062721
Epoch 94/100, Loss: 2.2178571671247482
Epoch 95/100, Loss: 2.0252795368433
Epoch 96/100, Loss: 1.9750659316778183
Epoch 97/100, Loss: 2.1129662096500397
Epoch 98/100, Loss: 2.682696111500263
Epoch 99/100, Loss: 2.0873628705739975
Epoch 100/100, Loss: 2.0132870748639107
Fold 3/5 done

Epoch 1/100, Loss: 2.2318694293498993
Epoch 2/100, Loss: 2.2688859552145004
Epoch 3/100, Loss: 2.1369758024811745
Epoch 4/100, Loss: 2.2131101563572884
Epoch 5/100, Loss: 2.2660151943564415
Epoch 6/100, Loss: 2.030821517109871
Epoch 7/100, Loss: 2.3757633417844772
Epoch 8/100, Loss: 2.346117414534092
Epoch 9/100, Loss: 2.225499100983143
Epoch 10/100, Loss: 2.3440500125288963
Epoch 11/100, Loss: 2.197584807872772
Epoch 12/100, Loss: 2.126890294253826
Epoch 13/100, Loss: 2.2279090583324432
Epoch 14/100, Loss: 2.121269591152668
Epoch 15/100, Loss: 2.316099539399147

Epoch 16/100, Loss: 2.245125576853752
Epoch 17/100, Loss: 2.2241462394595146
Epoch 18/100, Loss: 2.1331838965415955
Epoch 19/100, Loss: 2.0237875282764435
Epoch 20/100, Loss: 2.4774497970938683
Epoch 21/100, Loss: 2.185574769973755
Epoch 22/100, Loss: 2.152274377644062
Epoch 23/100, Loss: 2.3200757429003716
Epoch 24/100, Loss: 2.0793191492557526
Epoch 25/100, Loss: 2.355017699301243
Epoch 26/100, Loss: 2.220025710761547
Epoch 27/100, Loss: 2.1946114227175713
Epoch 28/100, Loss: 2.220348186790943
Epoch 29/100, Loss: 2.1580264642834663
Epoch 30/100, Loss: 2.1680197715759277

Epoch 31/100, Loss: 2.256785698235035
Epoch 32/100, Loss: 2.185990549623966
Epoch 33/100, Loss: 2.1000011414289474
Epoch 34/100, Loss: 2.2185030058026314
Epoch 35/100, Loss: 2.1802210584282875
Epoch 36/100, Loss: 2.1594040021300316
Epoch 37/100, Loss: 2.14847581833601
Epoch 38/100, Loss: 2.322340242564678
Epoch 39/100, Loss: 2.1906600669026375
Epoch 40/100, Loss: 2.3364226073026657
Epoch 41/100, Loss: 2.3830519691109657
Epoch 42/100, Loss: 2.3017029762268066
Epoch 43/100, Loss: 2.257469028234482
Epoch 44/100, Loss: 2.221527799963951
Epoch 45/100, Loss: 2.0800009220838547

Epoch 46/100, Loss: 2.5197607949376106
Epoch 47/100, Loss: 2.2256350815296173
Epoch 48/100, Loss: 2.05907429009676
Epoch 49/100, Loss: 2.070169672369957
Epoch 50/100, Loss: 2.593551851809025
Epoch 51/100, Loss: 2.0358227863907814
Epoch 52/100, Loss: 2.0515519976615906
Epoch 53/100, Loss: 2.1753653585910797
Epoch 54/100, Loss: 2.4012541025877
Epoch 55/100, Loss: 2.1768297255039215
Epoch 56/100, Loss: 2.26819234341383
Epoch 57/100, Loss: 2.391184486448765
Epoch 58/100, Loss: 2.25301081687212
Epoch 59/100, Loss: 2.27809539437294
Epoch 60/100, Loss: 2.282273881137371

Epoch 61/100, Loss: 2.1806271970272064
Epoch 62/100, Loss: 2.1906310841441154
Epoch 63/100, Loss: 2.238804005086422
Epoch 64/100, Loss: 2.118365429341793
Epoch 65/100, Loss: 2.176208510994911
Epoch 66/100, Loss: 2.0854760706424713
Epoch 67/100, Loss: 2.2893311232328415
Epoch 68/100, Loss: 2.2843360006809235
Epoch 69/100, Loss: 2.2326145470142365
Epoch 70/100, Loss: 2.1619309931993484

Epoch 71/100, Loss: 2.211548961699009
Epoch 72/100, Loss: 2.1359133198857307
Epoch 73/100, Loss: 2.150993227958679
Epoch 74/100, Loss: 2.065769262611866
Epoch 75/100, Loss: 2.3773841187357903
Epoch 76/100, Loss: 2.0945242010056973
Epoch 77/100, Loss: 2.189788945019245
Epoch 78/100, Loss: 2.3215141743421555
Epoch 79/100, Loss: 2.1712162271142006

Epoch 80/100, Loss: 2.153345726430416
Epoch 81/100, Loss: 2.2047490552067757
Epoch 82/100, Loss: 2.2269606813788414
Epoch 83/100, Loss: 2.3202323615550995
Epoch 84/100, Loss: 2.286827005445957
Epoch 85/100, Loss: 2.257254384458065
Epoch 86/100, Loss: 2.0831467285752296
Epoch 87/100, Loss: 2.013403296470642
Epoch 88/100, Loss: 2.2833155691623688
Epoch 89/100, Loss: 2.26895322650671
Epoch 90/100, Loss: 2.2505547627806664
Epoch 91/100, Loss: 2.1447212398052216

Epoch 92/100, Loss: 2.092673346400261
Epoch 93/100, Loss: 2.1821541488170624
Epoch 94/100, Loss: 2.3066748827695847
Epoch 95/100, Loss: 2.1423270627856255
Epoch 96/100, Loss: 2.183534264564514
Epoch 97/100, Loss: 2.0997408404946327
Epoch 98/100, Loss: 2.0960742831230164
Epoch 99/100, Loss: 2.1526538878679276
Epoch 100/100, Loss: 2.315491147339344
Fold 4/5 done
Epoch 1/100, Loss: 4.161603018641472
Epoch 2/100, Loss: 4.116669729351997

Epoch 3/100, Loss: 4.112962305545807
Epoch 4/100, Loss: 4.060575395822525
Epoch 5/100, Loss: 4.394624814391136
Epoch 6/100, Loss: 4.16779650747776
Epoch 7/100, Loss: 4.191466778516769
Epoch 8/100, Loss: 4.322228729724884
Epoch 9/100, Loss: 4.2314585745334625
Epoch 10/100, Loss: 4.182399243116379
Epoch 11/100, Loss: 4.388348281383514
Epoch 12/100, Loss: 4.085901215672493
Epoch 13/100, Loss: 4.013535216450691
Epoch 14/100, Loss: 4.056321054697037

Epoch 15/100, Loss: 4.132256329059601
Epoch 16/100, Loss: 4.073682442307472
Epoch 17/100, Loss: 3.966894507408142
Epoch 18/100, Loss: 4.193882957100868
Epoch 19/100, Loss: 4.113178014755249
Epoch 20/100, Loss: 4.3545816242694855
Epoch 21/100, Loss: 4.270813509821892
Epoch 22/100, Loss: 4.581146836280823
Epoch 23/100, Loss: 4.118707954883575
Epoch 24/100, Loss: 4.178633406758308
Epoch 25/100, Loss: 4.561549320816994
Epoch 26/100, Loss: 4.085565507411957

Epoch 27/100, Loss: 4.119617909193039
Epoch 28/100, Loss: 4.040943309664726
Epoch 29/100, Loss: 3.8883678913116455
Epoch 30/100, Loss: 4.217856138944626
Epoch 31/100, Loss: 4.395914748311043
Epoch 32/100, Loss: 4.278393283486366
Epoch 33/100, Loss: 4.2350674867630005
Epoch 34/100, Loss: 4.243020445108414
Epoch 35/100, Loss: 4.291436389088631
Epoch 36/100, Loss: 4.085977211594582
Epoch 37/100, Loss: 4.242215156555176

Epoch 38/100, Loss: 4.376639291644096
Epoch 39/100, Loss: 4.211314618587494
Epoch 40/100, Loss: 4.233187600970268
Epoch 41/100, Loss: 4.041118435561657
Epoch 42/100, Loss: 3.9293599724769592
Epoch 43/100, Loss: 3.8435450941324234
Epoch 44/100, Loss: 4.47228667140007
Epoch 45/100, Loss: 4.110880717635155
Epoch 46/100, Loss: 4.0565405189991
Epoch 47/100, Loss: 4.2038091868162155

Epoch 48/100, Loss: 4.152287989854813
Epoch 49/100, Loss: 4.314691826701164
Epoch 50/100, Loss: 4.15459805727005
Epoch 51/100, Loss: 4.220604956150055
Epoch 52/100, Loss: 4.171986594796181
Epoch 53/100, Loss: 4.366397708654404
Epoch 54/100, Loss: 4.1750060468912125
Epoch 55/100, Loss: 4.16479130089283
Epoch 56/100, Loss: 4.123158738017082
Epoch 57/100, Loss: 4.325121626257896
Epoch 58/100, Loss: 4.07977519929409
Epoch 59/100, Loss: 4.365240827202797
Epoch 60/100, Loss: 4.211534008383751

Epoch 61/100, Loss: 4.114695996046066
Epoch 62/100, Loss: 4.208595126867294
Epoch 63/100, Loss: 4.214175537228584
Epoch 64/100, Loss: 4.16544497013092
Epoch 65/100, Loss: 4.197631552815437
Epoch 66/100, Loss: 4.232948139309883
Epoch 67/100, Loss: 4.0798221081495285
Epoch 68/100, Loss: 4.386285424232483
Epoch 69/100, Loss: 3.9993532299995422
Epoch 70/100, Loss: 4.230748504400253
Epoch 71/100, Loss: 4.271113455295563
Epoch 72/100, Loss: 4.1680581867694855

Epoch 73/100, Loss: 4.401632562279701
Epoch 74/100, Loss: 4.135488912463188
Epoch 75/100, Loss: 4.313650622963905
Epoch 76/100, Loss: 4.093475446105003
Epoch 77/100, Loss: 4.1605531722307205
Epoch 78/100, Loss: 4.250165045261383
Epoch 79/100, Loss: 4.196987837553024
Epoch 80/100, Loss: 4.250782534480095
Epoch 81/100, Loss: 4.063557341694832
Epoch 82/100, Loss: 4.6746761947870255
Epoch 83/100, Loss: 4.380501076579094
Epoch 84/100, Loss: 4.21792796254158

Epoch 85/100, Loss: 4.138033777475357
Epoch 86/100, Loss: 4.254954665899277
Epoch 87/100, Loss: 4.1587091982364655
Epoch 88/100, Loss: 4.131085827946663
Epoch 89/100, Loss: 4.224187925457954
Epoch 90/100, Loss: 4.3412803411483765
Epoch 91/100, Loss: 4.17736092209816
Epoch 92/100, Loss: 4.134124547243118
Epoch 93/100, Loss: 4.324079245328903
Epoch 94/100, Loss: 4.17545747756958

Epoch 95/100, Loss: 4.309278905391693
Epoch 96/100, Loss: 4.382511928677559
Epoch 97/100, Loss: 4.231472909450531
Epoch 98/100, Loss: 4.271222323179245
Epoch 99/100, Loss: 4.538745433092117
Epoch 100/100, Loss: 4.367295816540718
Fold 5/5 done

In [11]:
ap = average_precision_score(y_true, anomaly_scores)
print(f"Deep SVDD AP (5-fold CV) = {ap:.4f}")
sb.glue("GBG500_ap_spectral_deep_svdd", float(ap))

Deep SVDD AP (5-fold CV) = 0.5743