In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import average_precision_score
from sklearn.model_selection import StratifiedKFold
from pyod.models.deep_svdd import DeepSVDD
import sys
import scrapbook as sb

sys.path.append('..')
from utils import reshape_to_numpy, interpolate_missing_values, denoise_data, compute_spectrograms, time_avg_pooling

In [2]:
seed = 1
sampling_rate = 10
nperseg=64
noverlap=32
accel_cutoff = 0.4
accel_order = 30
gyro_cutoff = 0.6
gyro_order = 20
batch_size = 32
epochs = 100
hidden_neurons = [128, 64, 32]
n_splits = 5

In [3]:
# Parameters
seed = 6

In [4]:
rng = np.random.RandomState(seed)

In [5]:
data = pd.read_parquet("../data/GBG500.parquet")
data

,ride_id,time_index,ax,ay,az,rx,ry,rz
0,005043f1a7520cebf1e17fd166a00a3190e2433530f236...,0,-2.512796,-9.385012,-1.053078,-0.009155,0.009155,-0.201416
1,005043f1a7520cebf1e17fd166a00a3190e2433530f236...,100,-2.491268,-9.385012,-1.079390,-0.036621,0.027465,-0.155639
2,005043f1a7520cebf1e17fd166a00a3190e2433530f236...,200,-2.534324,-9.382022,-1.030952,0.036621,0.027465,-0.073242
3,005043f1a7520cebf1e17fd166a00a3190e2433530f236...,300,-2.488278,-9.383218,-1.091948,-0.045776,0.036621,-0.183105
4,005043f1a7520cebf1e17fd166a00a3190e2433530f236...,400,-2.483494,-9.382022,-1.100320,-0.045776,0.027465,-0.192260
...,...,...,...,...,...,...,...,...
1529542,ffb6f2f5dc6ba768d88dc0bc1af4cad235526aa9e24168...,241300,0.459862,-9.140430,-3.318900,1.556396,-0.091552,0.274658
1529543,ffb6f2f5dc6ba768d88dc0bc1af4cad235526aa9e24168...,241400,0.455676,-9.140430,-3.321292,1.583861,-0.119018,0.274658
1529544,ffb6f2f5dc6ba768d88dc0bc1af4cad235526aa9e24168...,241500,0.459862,-9.139832,-3.317704,1.583861,-0.109863,0.274658
1529545,ffb6f2f5dc6ba768d88dc0bc1af4cad235526aa9e24168...,241600,0.456274,-9.142224,-3.321292,1.574707,-0.137329,0.283813
1529546,ffb6f2f5dc6ba768d88dc0bc1af4cad235526aa9e24168...,241700,0.458666,-9.139832,-3.320694,1.574707,-0.137329,0.274658

In [6]:
labels = pd.read_csv("../data/GBG500_labels.csv")
labels.columns = labels.columns.str.lower()
ride_order_df = pd.DataFrame({"ride_id": data["ride_id"].unique()})
labels_sorted = ride_order_df.merge(
    labels,
    on="ride_id",
    how="left"
)
labels_sorted

                                               ride_id        label
0    005043f1a7520cebf1e17fd166a00a3190e2433530f236...         Safe
1    00d223cb7aecc9c0cc5871e32a6c45027a068eba07c572...     Reckless
2    02288a4aeca044203394e982e76b87818021dea2b34df9...         Safe
3    0236bdcf13d473ea24d97f5eaeea459f257dffac005694...  Bad weather
4    0238e5dd85143f1b6c59b200bc32f14361b8fc84c51a87...         Safe
..                                                 ...          ...
495  fe5d7f84d692bbccad8bd566a3ad5c3108fa9f90acd671...         Safe
496  fe67169632306d4668b2affedef510df2cb43e2fb41220...         Safe
497  fee44667fdc8ab4995c702fc3bd36178de0b1ca2c64687...         Safe
498  ff79b2e945b93c2a5efc3a06365267b3a160e7849ba57d...         Safe
499  ffb6f2f5dc6ba768d88dc0bc1af4cad235526aa9e24168...         Safe

[500 rows x 2 columns]

In [7]:
data_np = reshape_to_numpy(
    data,
    features = ["ax", "ay", "az", "rx", "ry", "rz"],
    max_timestamps = 4800
)

data_np_clean = interpolate_missing_values(
    data_np,
    method='linear',
    limit=None
)

data_np_clean = denoise_data(
    data=data_np_clean,
    accel_indices=[0, 1, 2],
    gyro_indices=[3, 4, 5],
    accel_cutoff=accel_cutoff,
    accel_order=accel_order,
    gyro_cutoff=gyro_cutoff,
    gyro_order=gyro_order,
)

In [8]:
# Compute spectrograms for all rides
spectrograms_array = compute_spectrograms(data_np_clean, sampling_rate, nperseg, noverlap)
spectrograms_array.shape

(500, 149, 6, 33)

In [9]:
# Aggregate spectrograms using time-averaged pooling
X_feat = time_avg_pooling(spectrograms_array)
X_feat.shape

(500, 198)

In [10]:
# 5-fold stratified CV with Deep SVDD
skf = StratifiedKFold(n_splits=n_splits, shuffle=True, random_state=rng.randint(1000))
y_true = (labels_sorted['label'] == 'Reckless').astype(int).values
anomaly_scores = np.full(len(y_true), np.nan)

for fold, (train_idx, test_idx) in enumerate(skf.split(X_feat, y_true)):
    sc = StandardScaler()
    X_train = sc.fit_transform(X_feat[train_idx])
    X_test = sc.transform(X_feat[test_idx])

    np.random.seed(rng.randint(1000))
    model = DeepSVDD(
        n_features=X_train.shape[1],
        hidden_neurons=hidden_neurons,
        epochs=epochs,
        batch_size=batch_size,
        random_state=rng.randint(1000),
    )
    model.fit(X_train)
    anomaly_scores[test_idx] = model.decision_function(X_test)
    print(f"Fold {fold+1}/{n_splits} done")

Epoch 1/100, Loss: 1.4000700786709785
Epoch 2/100, Loss: 1.4122405387461185
Epoch 3/100, Loss: 1.3905235901474953
Epoch 4/100, Loss: 1.3950827568769455
Epoch 5/100, Loss: 1.2326299510896206
Epoch 6/100, Loss: 1.4894364848732948
Epoch 7/100, Loss: 1.289279442280531
Epoch 8/100, Loss: 1.5154844596982002
Epoch 9/100, Loss: 1.2628880441188812
Epoch 10/100, Loss: 1.3203544467687607
Epoch 11/100, Loss: 1.4104238450527191
Epoch 12/100, Loss: 1.3319209478795528
Epoch 13/100, Loss: 1.3053989112377167
Epoch 14/100, Loss: 1.407683502882719
Epoch 15/100, Loss: 1.365093819797039
Epoch 16/100, Loss: 1.337565552443266

Epoch 17/100, Loss: 1.6887242309749126
Epoch 18/100, Loss: 1.2880054339766502
Epoch 19/100, Loss: 1.4856287650763988
Epoch 20/100, Loss: 1.3348507769405842
Epoch 21/100, Loss: 1.4191299080848694
Epoch 22/100, Loss: 1.487378068268299
Epoch 23/100, Loss: 1.3423905037343502
Epoch 24/100, Loss: 1.4582550004124641
Epoch 25/100, Loss: 1.4147736132144928
Epoch 26/100, Loss: 1.300187662243843
Epoch 27/100, Loss: 1.4057817868888378
Epoch 28/100, Loss: 1.4002045914530754
Epoch 29/100, Loss: 1.4700747169554234
Epoch 30/100, Loss: 1.3800175450742245
Epoch 31/100, Loss: 1.3599779680371284
Epoch 32/100, Loss: 1.5599861815571785
Epoch 33/100, Loss: 1.3522536642849445

Epoch 34/100, Loss: 1.2589447125792503
Epoch 35/100, Loss: 1.3883154392242432
Epoch 36/100, Loss: 1.2423914819955826
Epoch 37/100, Loss: 1.4485097602009773
Epoch 38/100, Loss: 1.2880879454314709
Epoch 39/100, Loss: 1.4177812710404396
Epoch 40/100, Loss: 1.3368647806346416
Epoch 41/100, Loss: 1.464466132223606
Epoch 42/100, Loss: 1.4659354165196419
Epoch 43/100, Loss: 1.3627199828624725
Epoch 44/100, Loss: 1.3525348864495754
Epoch 45/100, Loss: 1.3668945245444775
Epoch 46/100, Loss: 1.3457831032574177
Epoch 47/100, Loss: 1.2840848937630653
Epoch 48/100, Loss: 1.2822114154696465
Epoch 49/100, Loss: 1.4170645661652088
Epoch 50/100, Loss: 1.438298862427473

Epoch 51/100, Loss: 1.5186695866286755
Epoch 52/100, Loss: 1.4176189936697483
Epoch 53/100, Loss: 1.434770330786705
Epoch 54/100, Loss: 1.4674342200160027
Epoch 55/100, Loss: 1.518006343394518
Epoch 56/100, Loss: 1.279622919857502
Epoch 57/100, Loss: 1.3170118369162083
Epoch 58/100, Loss: 1.4796951971948147
Epoch 59/100, Loss: 1.5139099173247814
Epoch 60/100, Loss: 1.5026703365147114
Epoch 61/100, Loss: 1.4082512855529785
Epoch 62/100, Loss: 1.4576994515955448
Epoch 63/100, Loss: 1.465553816407919
Epoch 64/100, Loss: 1.4919172786176205
Epoch 65/100, Loss: 1.4594531431794167
Epoch 66/100, Loss: 1.4508749395608902
Epoch 67/100, Loss: 1.3995425701141357

Epoch 68/100, Loss: 1.4571795798838139
Epoch 69/100, Loss: 1.470329910516739
Epoch 70/100, Loss: 1.4017417803406715
Epoch 71/100, Loss: 1.3280435241758823
Epoch 72/100, Loss: 1.3413340784609318
Epoch 73/100, Loss: 1.4034566022455692
Epoch 74/100, Loss: 1.3937992602586746
Epoch 75/100, Loss: 1.3905913531780243
Epoch 76/100, Loss: 1.3378792107105255
Epoch 77/100, Loss: 1.4912447892129421
Epoch 78/100, Loss: 1.4982197545468807
Epoch 79/100, Loss: 1.4392056837677956
Epoch 80/100, Loss: 1.3311544433236122
Epoch 81/100, Loss: 1.4342388585209846
Epoch 82/100, Loss: 1.4107463210821152
Epoch 83/100, Loss: 1.4195230528712273

Epoch 84/100, Loss: 1.438060887157917
Epoch 85/100, Loss: 1.4245407432317734
Epoch 86/100, Loss: 1.3961406275629997
Epoch 87/100, Loss: 1.3017848320305347
Epoch 88/100, Loss: 1.392869595438242
Epoch 89/100, Loss: 1.3996262848377228
Epoch 90/100, Loss: 1.387239146977663
Epoch 91/100, Loss: 1.3058597519993782
Epoch 92/100, Loss: 1.4599546156823635
Epoch 93/100, Loss: 1.3072580099105835
Epoch 94/100, Loss: 1.4663333371281624
Epoch 95/100, Loss: 1.374305009841919
Epoch 96/100, Loss: 1.3856318071484566
Epoch 97/100, Loss: 1.4273198917508125
Epoch 98/100, Loss: 1.4094437062740326
Epoch 99/100, Loss: 1.3703991025686264
Epoch 100/100, Loss: 1.402896225452423

Fold 1/5 done
Epoch 1/100, Loss: 2.6652239337563515
Epoch 2/100, Loss: 2.6885373815894127
Epoch 3/100, Loss: 2.5907356292009354
Epoch 4/100, Loss: 2.493538998067379
Epoch 5/100, Loss: 2.7196171283721924
Epoch 6/100, Loss: 2.5619329065084457
Epoch 7/100, Loss: 2.6971883848309517
Epoch 8/100, Loss: 2.6248512491583824
Epoch 9/100, Loss: 2.586255431175232
Epoch 10/100, Loss: 2.6425909772515297
Epoch 11/100, Loss: 2.6411766931414604
Epoch 12/100, Loss: 2.6443374156951904
Epoch 13/100, Loss: 2.629954107105732
Epoch 14/100, Loss: 2.6436111107468605
Epoch 15/100, Loss: 2.6131888031959534
Epoch 16/100, Loss: 2.864250108599663

Epoch 17/100, Loss: 2.664373889565468
Epoch 18/100, Loss: 2.595685735344887
Epoch 19/100, Loss: 2.5351850017905235
Epoch 20/100, Loss: 2.59095960855484
Epoch 21/100, Loss: 2.650439292192459
Epoch 22/100, Loss: 2.6297468841075897
Epoch 23/100, Loss: 2.513177663087845
Epoch 24/100, Loss: 2.7853169441223145
Epoch 25/100, Loss: 2.5454283356666565
Epoch 26/100, Loss: 2.760030873119831
Epoch 27/100, Loss: 2.6323951333761215
Epoch 28/100, Loss: 2.675904020667076
Epoch 29/100, Loss: 2.5073974579572678
Epoch 30/100, Loss: 2.726435109972954
Epoch 31/100, Loss: 2.6491315439343452
Epoch 32/100, Loss: 2.569924257695675

Epoch 33/100, Loss: 2.6749852895736694
Epoch 34/100, Loss: 2.7362426295876503
Epoch 35/100, Loss: 2.624482996761799
Epoch 36/100, Loss: 2.764193296432495
Epoch 37/100, Loss: 2.7234330475330353
Epoch 38/100, Loss: 2.732035353779793
Epoch 39/100, Loss: 2.5497555285692215
Epoch 40/100, Loss: 2.813970625400543
Epoch 41/100, Loss: 2.5912765339016914
Epoch 42/100, Loss: 2.5753592401742935
Epoch 43/100, Loss: 2.65386151522398
Epoch 44/100, Loss: 3.206408604979515
Epoch 45/100, Loss: 2.5481363609433174
Epoch 46/100, Loss: 2.5907332748174667
Epoch 47/100, Loss: 2.7509406954050064

Epoch 48/100, Loss: 2.8408273011446
Epoch 49/100, Loss: 2.5322469025850296
Epoch 50/100, Loss: 2.7638364136219025
Epoch 51/100, Loss: 2.691392309963703
Epoch 52/100, Loss: 2.6308012902736664
Epoch 53/100, Loss: 2.651452951133251
Epoch 54/100, Loss: 2.8154347762465477
Epoch 55/100, Loss: 2.6526751667261124
Epoch 56/100, Loss: 2.658654935657978
Epoch 57/100, Loss: 3.049768887460232
Epoch 58/100, Loss: 2.6295579075813293
Epoch 59/100, Loss: 2.6191593557596207
Epoch 60/100, Loss: 2.6040497049689293
Epoch 61/100, Loss: 2.872631624341011
Epoch 62/100, Loss: 2.6065835803747177
Epoch 63/100, Loss: 2.7155723571777344
Epoch 64/100, Loss: 2.680810511112213

Epoch 65/100, Loss: 2.800187163054943
Epoch 66/100, Loss: 2.67200618237257
Epoch 67/100, Loss: 2.6606949642300606
Epoch 68/100, Loss: 2.7204370498657227
Epoch 69/100, Loss: 2.6410598903894424
Epoch 70/100, Loss: 2.7474982738494873
Epoch 71/100, Loss: 2.7105662897229195
Epoch 72/100, Loss: 2.735253967344761
Epoch 73/100, Loss: 2.6539986804127693
Epoch 74/100, Loss: 2.739516742527485
Epoch 75/100, Loss: 2.540608584880829
Epoch 76/100, Loss: 2.747519016265869
Epoch 77/100, Loss: 2.685599334537983
Epoch 78/100, Loss: 2.6080470457673073
Epoch 79/100, Loss: 2.7002264857292175
Epoch 80/100, Loss: 2.5651170015335083
Epoch 81/100, Loss: 2.6557022407650948

Epoch 82/100, Loss: 2.722678668797016
Epoch 83/100, Loss: 2.541827365756035
Epoch 84/100, Loss: 2.5447687953710556
Epoch 85/100, Loss: 2.4947950690984726
Epoch 86/100, Loss: 2.8021040111780167
Epoch 87/100, Loss: 2.7397278174757957
Epoch 88/100, Loss: 2.7247938066720963
Epoch 89/100, Loss: 2.6453794836997986
Epoch 90/100, Loss: 2.653295114636421
Epoch 91/100, Loss: 2.6414285451173782
Epoch 92/100, Loss: 2.7504043132066727
Epoch 93/100, Loss: 2.7928997352719307
Epoch 94/100, Loss: 2.6916227862238884
Epoch 95/100, Loss: 2.852132074534893
Epoch 96/100, Loss: 2.6411126628518105
Epoch 97/100, Loss: 2.7885432988405228
Epoch 98/100, Loss: 2.7182586044073105

Epoch 99/100, Loss: 2.5075587555766106
Epoch 100/100, Loss: 2.714135453104973
Fold 2/5 done
Epoch 1/100, Loss: 2.360407754778862
Epoch 2/100, Loss: 2.479403890669346
Epoch 3/100, Loss: 2.3859443590044975
Epoch 4/100, Loss: 2.7312453538179398
Epoch 5/100, Loss: 2.559209108352661
Epoch 6/100, Loss: 2.3663578554987907
Epoch 7/100, Loss: 2.400211878120899
Epoch 8/100, Loss: 2.4582128822803497
Epoch 9/100, Loss: 2.6622879281640053
Epoch 10/100, Loss: 2.6193483024835587
Epoch 11/100, Loss: 2.4202570617198944
Epoch 12/100, Loss: 2.5121031403541565
Epoch 13/100, Loss: 2.514081671833992

Epoch 14/100, Loss: 2.494052328169346
Epoch 15/100, Loss: 2.370834708213806
Epoch 16/100, Loss: 2.5807036459445953
Epoch 17/100, Loss: 2.5492832213640213
Epoch 18/100, Loss: 2.445230022072792
Epoch 19/100, Loss: 2.528731919825077
Epoch 20/100, Loss: 2.5399299412965775
Epoch 21/100, Loss: 2.60951978713274
Epoch 22/100, Loss: 2.6336434707045555
Epoch 23/100, Loss: 2.4454177021980286
Epoch 24/100, Loss: 2.4907509684562683
Epoch 25/100, Loss: 2.6026848554611206
Epoch 26/100, Loss: 2.436345286667347
Epoch 27/100, Loss: 2.4088883697986603
Epoch 28/100, Loss: 2.5377089828252792
Epoch 29/100, Loss: 2.4058049097657204

Epoch 30/100, Loss: 2.5576495081186295
Epoch 31/100, Loss: 2.5341923981904984
Epoch 32/100, Loss: 2.440581999719143
Epoch 33/100, Loss: 2.619620732963085
Epoch 34/100, Loss: 2.465426169335842
Epoch 35/100, Loss: 2.5100822001695633
Epoch 36/100, Loss: 2.425926834344864
Epoch 37/100, Loss: 2.5047822147607803
Epoch 38/100, Loss: 2.595991186797619
Epoch 39/100, Loss: 2.4288190975785255
Epoch 40/100, Loss: 2.635677419602871
Epoch 41/100, Loss: 2.514555051922798
Epoch 42/100, Loss: 2.4356811940670013
Epoch 43/100, Loss: 2.7649355679750443
Epoch 44/100, Loss: 2.641360819339752
Epoch 45/100, Loss: 2.584851734340191

Epoch 46/100, Loss: 2.4567261338233948
Epoch 47/100, Loss: 2.2671897560358047
Epoch 48/100, Loss: 2.639283962547779
Epoch 49/100, Loss: 2.424835629761219
Epoch 50/100, Loss: 2.4020666033029556
Epoch 51/100, Loss: 2.4675620570778847
Epoch 52/100, Loss: 2.593655616044998
Epoch 53/100, Loss: 2.4672640040516853
Epoch 54/100, Loss: 2.364797569811344
Epoch 55/100, Loss: 2.475776843726635
Epoch 56/100, Loss: 2.490631826221943
Epoch 57/100, Loss: 2.5124694481492043
Epoch 58/100, Loss: 2.476961389183998
Epoch 59/100, Loss: 2.733938157558441
Epoch 60/100, Loss: 2.756919041275978
Epoch 61/100, Loss: 2.5595565363764763

Epoch 62/100, Loss: 2.4365879595279694
Epoch 63/100, Loss: 2.5522238686680794
Epoch 64/100, Loss: 2.465578317642212
Epoch 65/100, Loss: 2.450217589735985
Epoch 66/100, Loss: 2.7598845064640045
Epoch 67/100, Loss: 2.511177808046341
Epoch 68/100, Loss: 2.356168530881405
Epoch 69/100, Loss: 2.6280553117394447
Epoch 70/100, Loss: 2.5103551745414734
Epoch 71/100, Loss: 2.5101140066981316
Epoch 72/100, Loss: 2.526095889508724
Epoch 73/100, Loss: 2.4339463263750076
Epoch 74/100, Loss: 2.4585990011692047
Epoch 75/100, Loss: 2.585301861166954
Epoch 76/100, Loss: 2.5581368058919907
Epoch 77/100, Loss: 2.4767686501145363
Epoch 78/100, Loss: 2.5752047896385193

Epoch 79/100, Loss: 2.7382477298378944
Epoch 80/100, Loss: 2.47271641343832
Epoch 81/100, Loss: 2.5166942924261093
Epoch 82/100, Loss: 2.616491459310055
Epoch 83/100, Loss: 2.3408062756061554
Epoch 84/100, Loss: 2.447263479232788
Epoch 85/100, Loss: 2.470194026827812
Epoch 86/100, Loss: 2.5006931871175766
Epoch 87/100, Loss: 2.4649586230516434
Epoch 88/100, Loss: 2.5017039701342583
Epoch 89/100, Loss: 2.6727546229958534
Epoch 90/100, Loss: 2.5036991834640503
Epoch 91/100, Loss: 2.4976266473531723
Epoch 92/100, Loss: 2.70964278280735

Epoch 93/100, Loss: 2.368029445409775
Epoch 94/100, Loss: 2.5511447489261627
Epoch 95/100, Loss: 2.6791623532772064
Epoch 96/100, Loss: 2.6864159777760506
Epoch 97/100, Loss: 2.502037823200226
Epoch 98/100, Loss: 2.5985192582011223
Epoch 99/100, Loss: 2.4944223314523697
Epoch 100/100, Loss: 2.5038396529853344
Fold 3/5 done
Epoch 1/100, Loss: 2.30722413957119
Epoch 2/100, Loss: 2.2120120897889137

Epoch 3/100, Loss: 2.1699262112379074
Epoch 4/100, Loss: 2.0883986055850983
Epoch 5/100, Loss: 2.2386826798319817
Epoch 6/100, Loss: 2.0694132447242737
Epoch 7/100, Loss: 1.9945399165153503
Epoch 8/100, Loss: 2.404773771762848
Epoch 9/100, Loss: 2.2228787392377853
Epoch 10/100, Loss: 2.2035379856824875
Epoch 11/100, Loss: 2.3284798935055733
Epoch 12/100, Loss: 2.2781358286738396
Epoch 13/100, Loss: 2.289304204285145
Epoch 14/100, Loss: 2.113796927034855

Epoch 15/100, Loss: 2.143068239092827
Epoch 16/100, Loss: 2.159834273159504
Epoch 17/100, Loss: 2.225179724395275
Epoch 18/100, Loss: 2.1655097603797913
Epoch 19/100, Loss: 2.196576163172722
Epoch 20/100, Loss: 2.3325072899460793
Epoch 21/100, Loss: 2.66109711676836
Epoch 22/100, Loss: 2.2363806068897247
Epoch 23/100, Loss: 2.05950465798378
Epoch 24/100, Loss: 2.018082618713379
Epoch 25/100, Loss: 2.425511308014393
Epoch 26/100, Loss: 2.1135197058320045
Epoch 27/100, Loss: 2.0204832926392555
Epoch 28/100, Loss: 2.148258589208126
Epoch 29/100, Loss: 2.0863261446356773
Epoch 30/100, Loss: 2.2659099623560905
Epoch 31/100, Loss: 2.3574339896440506
Epoch 32/100, Loss: 2.21888317912817

Epoch 33/100, Loss: 2.2828675284981728
Epoch 34/100, Loss: 2.2555731534957886
Epoch 35/100, Loss: 2.2809831351041794
Epoch 36/100, Loss: 1.8889721110463142
Epoch 37/100, Loss: 2.1611235812306404
Epoch 38/100, Loss: 2.153357908129692
Epoch 39/100, Loss: 2.233092688024044
Epoch 40/100, Loss: 3.0347670689225197
Epoch 41/100, Loss: 2.1635626703500748
Epoch 42/100, Loss: 2.2021841406822205
Epoch 43/100, Loss: 2.136560581624508
Epoch 44/100, Loss: 2.181592658162117
Epoch 45/100, Loss: 2.19582586735487
Epoch 46/100, Loss: 2.159682258963585
Epoch 47/100, Loss: 2.3106614723801613
Epoch 48/100, Loss: 2.3779137954115868
Epoch 49/100, Loss: 2.2285893112421036
Epoch 50/100, Loss: 2.3174269273877144

Epoch 51/100, Loss: 2.5446488559246063
Epoch 52/100, Loss: 2.0517828315496445
Epoch 53/100, Loss: 2.3510706424713135
Epoch 54/100, Loss: 2.1527887657284737
Epoch 55/100, Loss: 2.4375216141343117
Epoch 56/100, Loss: 2.3031263425946236
Epoch 57/100, Loss: 2.3187011927366257
Epoch 58/100, Loss: 2.0302106142044067
Epoch 59/100, Loss: 2.2545255571603775
Epoch 60/100, Loss: 2.104490205645561
Epoch 61/100, Loss: 2.0713293254375458
Epoch 62/100, Loss: 2.365294925868511
Epoch 63/100, Loss: 2.1448982283473015
Epoch 64/100, Loss: 2.1691432744264603
Epoch 65/100, Loss: 2.1235584430396557
Epoch 66/100, Loss: 2.0219852700829506
Epoch 67/100, Loss: 2.2171543911099434
Epoch 68/100, Loss: 2.360769771039486

Epoch 69/100, Loss: 2.314392603933811
Epoch 70/100, Loss: 2.284847177565098
Epoch 71/100, Loss: 2.1467638090252876
Epoch 72/100, Loss: 2.0861621648073196
Epoch 73/100, Loss: 2.0819877684116364
Epoch 74/100, Loss: 2.2021908685564995
Epoch 75/100, Loss: 2.654559902846813
Epoch 76/100, Loss: 2.337772451341152
Epoch 77/100, Loss: 2.1152459159493446
Epoch 78/100, Loss: 2.3416852727532387
Epoch 79/100, Loss: 2.286903828382492
Epoch 80/100, Loss: 2.8218817934393883
Epoch 81/100, Loss: 2.3488226905465126
Epoch 82/100, Loss: 2.0917415022850037

Epoch 83/100, Loss: 2.1368223130702972
Epoch 84/100, Loss: 2.1755053848028183
Epoch 85/100, Loss: 2.0425878688693047
Epoch 86/100, Loss: 2.3387174233794212
Epoch 87/100, Loss: 2.094004601240158
Epoch 88/100, Loss: 2.2353023812174797
Epoch 89/100, Loss: 2.1628877073526382
Epoch 90/100, Loss: 2.0951621159911156
Epoch 91/100, Loss: 2.413015194237232
Epoch 92/100, Loss: 2.1334463357925415
Epoch 93/100, Loss: 2.217481091618538
Epoch 94/100, Loss: 2.1782804504036903
Epoch 95/100, Loss: 2.3546190708875656
Epoch 96/100, Loss: 2.1188036277890205
Epoch 97/100, Loss: 2.227291390299797
Epoch 98/100, Loss: 2.3329259417951107
Epoch 99/100, Loss: 2.2208802700042725
Epoch 100/100, Loss: 2.199764631688595

Fold 4/5 done
Epoch 1/100, Loss: 2.0095726773142815
Epoch 2/100, Loss: 2.141309440135956
Epoch 3/100, Loss: 2.2750056385993958
Epoch 4/100, Loss: 2.375983476638794
Epoch 5/100, Loss: 2.3596439138054848
Epoch 6/100, Loss: 2.406363897025585
Epoch 7/100, Loss: 2.5046425238251686
Epoch 8/100, Loss: 2.669432520866394
Epoch 9/100, Loss: 2.390384405851364
Epoch 10/100, Loss: 2.2599776089191437
Epoch 11/100, Loss: 2.1432944238185883
Epoch 12/100, Loss: 2.264244981110096
Epoch 13/100, Loss: 2.3495067358016968
Epoch 14/100, Loss: 2.216595880687237
Epoch 15/100, Loss: 2.150565579533577

Epoch 16/100, Loss: 2.1621114872395992
Epoch 17/100, Loss: 2.199875373393297
Epoch 18/100, Loss: 2.689953997731209
Epoch 19/100, Loss: 2.2636181339621544
Epoch 20/100, Loss: 2.153865173459053
Epoch 21/100, Loss: 2.2473758533596992
Epoch 22/100, Loss: 2.1741527542471886
Epoch 23/100, Loss: 2.5968958660960197
Epoch 24/100, Loss: 2.2638440877199173
Epoch 25/100, Loss: 2.400472968816757
Epoch 26/100, Loss: 2.2050453200936317
Epoch 27/100, Loss: 2.3369380608201027
Epoch 28/100, Loss: 2.34361232817173
Epoch 29/100, Loss: 2.4147112369537354
Epoch 30/100, Loss: 2.2431678362190723
Epoch 31/100, Loss: 2.181264828890562

Epoch 32/100, Loss: 2.3400937356054783
Epoch 33/100, Loss: 2.036870487034321
Epoch 34/100, Loss: 2.211562357842922
Epoch 35/100, Loss: 2.3876927495002747
Epoch 36/100, Loss: 2.5258486345410347
Epoch 37/100, Loss: 2.404580947011709
Epoch 38/100, Loss: 2.233687900006771
Epoch 39/100, Loss: 2.351795054972172
Epoch 40/100, Loss: 2.6135549396276474
Epoch 41/100, Loss: 2.2246375754475594
Epoch 42/100, Loss: 2.445409819483757
Epoch 43/100, Loss: 2.4637438878417015
Epoch 44/100, Loss: 2.1500295847654343
Epoch 45/100, Loss: 2.335910454392433
Epoch 46/100, Loss: 2.558194674551487
Epoch 47/100, Loss: 2.376335419714451
Epoch 48/100, Loss: 2.2098120525479317

Epoch 49/100, Loss: 2.174972601234913
Epoch 50/100, Loss: 2.2131516449153423
Epoch 51/100, Loss: 2.2226167917251587
Epoch 52/100, Loss: 2.0799076296389103
Epoch 53/100, Loss: 2.4665712118148804
Epoch 54/100, Loss: 2.1724989637732506
Epoch 55/100, Loss: 2.603059135377407
Epoch 56/100, Loss: 2.458616778254509
Epoch 57/100, Loss: 2.3096629455685616
Epoch 58/100, Loss: 2.3616713881492615
Epoch 59/100, Loss: 2.4119348898530006
Epoch 60/100, Loss: 2.3473062962293625
Epoch 61/100, Loss: 2.315369926393032
Epoch 62/100, Loss: 2.408671498298645
Epoch 63/100, Loss: 2.613143488764763
Epoch 64/100, Loss: 1.994130365550518
Epoch 65/100, Loss: 2.5769308358430862
Epoch 66/100, Loss: 2.230331815779209

Epoch 67/100, Loss: 2.1761606447398663
Epoch 68/100, Loss: 2.301442250609398
Epoch 69/100, Loss: 2.258133575320244
Epoch 70/100, Loss: 2.3123017475008965
Epoch 71/100, Loss: 2.277169607579708
Epoch 72/100, Loss: 2.360477566719055
Epoch 73/100, Loss: 2.4118953570723534
Epoch 74/100, Loss: 2.2916463762521744
Epoch 75/100, Loss: 2.319044142961502
Epoch 76/100, Loss: 2.373064339160919
Epoch 77/100, Loss: 2.419935055077076
Epoch 78/100, Loss: 2.274188496172428
Epoch 79/100, Loss: 2.2847035825252533
Epoch 80/100, Loss: 2.3860160410404205

Epoch 81/100, Loss: 2.290680855512619
Epoch 82/100, Loss: 2.2508343532681465
Epoch 83/100, Loss: 2.120074190199375
Epoch 84/100, Loss: 2.3333514630794525
Epoch 85/100, Loss: 2.2625382021069527
Epoch 86/100, Loss: 2.3843043223023415
Epoch 87/100, Loss: 2.518029600381851
Epoch 88/100, Loss: 2.2166390866041183
Epoch 89/100, Loss: 2.9113278165459633
Epoch 90/100, Loss: 2.2757507786154747
Epoch 91/100, Loss: 2.1614979952573776
Epoch 92/100, Loss: 2.170806936919689
Epoch 93/100, Loss: 2.302172675728798
Epoch 94/100, Loss: 2.1931201219558716
Epoch 95/100, Loss: 2.4784863516688347
Epoch 96/100, Loss: 2.2799884602427483
Epoch 97/100, Loss: 2.0526215322315693

Epoch 98/100, Loss: 2.254490502178669
Epoch 99/100, Loss: 2.1597000621259212
Epoch 100/100, Loss: 2.3372506126761436
Fold 5/5 done

In [11]:
ap = average_precision_score(y_true, anomaly_scores)
print(f"Deep SVDD AP (5-fold CV) = {ap:.4f}")
sb.glue("GBG500_ap_spectral_deep_svdd", float(ap))

Deep SVDD AP (5-fold CV) = 0.4243