In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import average_precision_score
from sklearn.model_selection import StratifiedKFold
from pyod.models.deep_svdd import DeepSVDD
import sys
import scrapbook as sb

sys.path.append('..')
from utils import reshape_to_numpy, interpolate_missing_values, denoise_data, compute_spectrograms, time_avg_pooling

In [2]:
seed = 1
sampling_rate = 10
nperseg=64
noverlap=32
accel_cutoff = 0.4
accel_order = 30
gyro_cutoff = 0.6
gyro_order = 20
batch_size = 32
epochs = 100
hidden_neurons = [128, 64, 32]
n_splits = 5

In [3]:
# Parameters
seed = 18

In [4]:
rng = np.random.RandomState(seed)

In [5]:
data = pd.read_parquet("../data/GBG500.parquet")
data

,ride_id,time_index,ax,ay,az,rx,ry,rz
0,005043f1a7520cebf1e17fd166a00a3190e2433530f236...,0,-2.512796,-9.385012,-1.053078,-0.009155,0.009155,-0.201416
1,005043f1a7520cebf1e17fd166a00a3190e2433530f236...,100,-2.491268,-9.385012,-1.079390,-0.036621,0.027465,-0.155639
2,005043f1a7520cebf1e17fd166a00a3190e2433530f236...,200,-2.534324,-9.382022,-1.030952,0.036621,0.027465,-0.073242
3,005043f1a7520cebf1e17fd166a00a3190e2433530f236...,300,-2.488278,-9.383218,-1.091948,-0.045776,0.036621,-0.183105
4,005043f1a7520cebf1e17fd166a00a3190e2433530f236...,400,-2.483494,-9.382022,-1.100320,-0.045776,0.027465,-0.192260
...,...,...,...,...,...,...,...,...
1529542,ffb6f2f5dc6ba768d88dc0bc1af4cad235526aa9e24168...,241300,0.459862,-9.140430,-3.318900,1.556396,-0.091552,0.274658
1529543,ffb6f2f5dc6ba768d88dc0bc1af4cad235526aa9e24168...,241400,0.455676,-9.140430,-3.321292,1.583861,-0.119018,0.274658
1529544,ffb6f2f5dc6ba768d88dc0bc1af4cad235526aa9e24168...,241500,0.459862,-9.139832,-3.317704,1.583861,-0.109863,0.274658
1529545,ffb6f2f5dc6ba768d88dc0bc1af4cad235526aa9e24168...,241600,0.456274,-9.142224,-3.321292,1.574707,-0.137329,0.283813
1529546,ffb6f2f5dc6ba768d88dc0bc1af4cad235526aa9e24168...,241700,0.458666,-9.139832,-3.320694,1.574707,-0.137329,0.274658

In [6]:
labels = pd.read_csv("../data/GBG500_labels.csv")
labels.columns = labels.columns.str.lower()
ride_order_df = pd.DataFrame({"ride_id": data["ride_id"].unique()})
labels_sorted = ride_order_df.merge(
    labels,
    on="ride_id",
    how="left"
)
labels_sorted

                                               ride_id        label
0    005043f1a7520cebf1e17fd166a00a3190e2433530f236...         Safe
1    00d223cb7aecc9c0cc5871e32a6c45027a068eba07c572...     Reckless
2    02288a4aeca044203394e982e76b87818021dea2b34df9...         Safe
3    0236bdcf13d473ea24d97f5eaeea459f257dffac005694...  Bad weather
4    0238e5dd85143f1b6c59b200bc32f14361b8fc84c51a87...         Safe
..                                                 ...          ...
495  fe5d7f84d692bbccad8bd566a3ad5c3108fa9f90acd671...         Safe
496  fe67169632306d4668b2affedef510df2cb43e2fb41220...         Safe
497  fee44667fdc8ab4995c702fc3bd36178de0b1ca2c64687...         Safe
498  ff79b2e945b93c2a5efc3a06365267b3a160e7849ba57d...         Safe
499  ffb6f2f5dc6ba768d88dc0bc1af4cad235526aa9e24168...         Safe

[500 rows x 2 columns]

In [7]:
data_np = reshape_to_numpy(
    data,
    features = ["ax", "ay", "az", "rx", "ry", "rz"],
    max_timestamps = 4800
)

data_np_clean = interpolate_missing_values(
    data_np,
    method='linear',
    limit=None
)

data_np_clean = denoise_data(
    data=data_np_clean,
    accel_indices=[0, 1, 2],
    gyro_indices=[3, 4, 5],
    accel_cutoff=accel_cutoff,
    accel_order=accel_order,
    gyro_cutoff=gyro_cutoff,
    gyro_order=gyro_order,
)

In [8]:
# Compute spectrograms for all rides
spectrograms_array = compute_spectrograms(data_np_clean, sampling_rate, nperseg, noverlap)
spectrograms_array.shape

(500, 149, 6, 33)

In [9]:
# Aggregate spectrograms using time-averaged pooling
X_feat = time_avg_pooling(spectrograms_array)
X_feat.shape

(500, 198)

In [10]:
# 5-fold stratified CV with Deep SVDD
skf = StratifiedKFold(n_splits=n_splits, shuffle=True, random_state=rng.randint(1000))
y_true = (labels_sorted['label'] == 'Reckless').astype(int).values
anomaly_scores = np.full(len(y_true), np.nan)

for fold, (train_idx, test_idx) in enumerate(skf.split(X_feat, y_true)):
    sc = StandardScaler()
    X_train = sc.fit_transform(X_feat[train_idx])
    X_test = sc.transform(X_feat[test_idx])

    np.random.seed(rng.randint(1000))
    model = DeepSVDD(
        n_features=X_train.shape[1],
        hidden_neurons=hidden_neurons,
        epochs=epochs,
        batch_size=batch_size,
        random_state=rng.randint(1000),
    )
    model.fit(X_train)
    anomaly_scores[test_idx] = model.decision_function(X_test)
    print(f"Fold {fold+1}/{n_splits} done")

Epoch 1/100, Loss: 1.692725345492363
Epoch 2/100, Loss: 1.9669364467263222
Epoch 3/100, Loss: 1.9197255373001099
Epoch 4/100, Loss: 1.83103908598423
Epoch 5/100, Loss: 1.9040411449968815
Epoch 6/100, Loss: 1.8124796971678734
Epoch 7/100, Loss: 1.717642068862915
Epoch 8/100, Loss: 1.7601259611546993
Epoch 9/100, Loss: 1.8498362302780151
Epoch 10/100, Loss: 1.7338418439030647
Epoch 11/100, Loss: 1.7632333785295486
Epoch 12/100, Loss: 1.8648235648870468
Epoch 13/100, Loss: 1.6694864332675934
Epoch 14/100, Loss: 1.7675227001309395
Epoch 15/100, Loss: 1.8617753759026527
Epoch 16/100, Loss: 1.6875642463564873

Epoch 17/100, Loss: 1.9315064921975136
Epoch 18/100, Loss: 1.785671778023243
Epoch 19/100, Loss: 1.735267847776413
Epoch 20/100, Loss: 1.7336498126387596
Epoch 21/100, Loss: 1.7880814373493195
Epoch 22/100, Loss: 1.9616932943463326
Epoch 23/100, Loss: 1.8707548156380653
Epoch 24/100, Loss: 1.7820031866431236
Epoch 25/100, Loss: 1.7179906144738197
Epoch 26/100, Loss: 2.0922293812036514
Epoch 27/100, Loss: 1.8126768320798874
Epoch 28/100, Loss: 1.7987233735620975
Epoch 29/100, Loss: 1.9646203443408012
Epoch 30/100, Loss: 1.7384355962276459
Epoch 31/100, Loss: 1.878514289855957

Epoch 32/100, Loss: 1.885160431265831
Epoch 33/100, Loss: 1.839644767343998
Epoch 34/100, Loss: 1.7938988395035267
Epoch 35/100, Loss: 1.9747425019741058
Epoch 36/100, Loss: 1.6581925749778748
Epoch 37/100, Loss: 1.677140273153782
Epoch 38/100, Loss: 1.9331705793738365
Epoch 39/100, Loss: 2.0151083692908287
Epoch 40/100, Loss: 1.8422158807516098
Epoch 41/100, Loss: 1.8164277374744415
Epoch 42/100, Loss: 1.866200402379036
Epoch 43/100, Loss: 1.9105495363473892
Epoch 44/100, Loss: 2.0434958934783936
Epoch 45/100, Loss: 1.800289049744606
Epoch 46/100, Loss: 1.7771769165992737

Epoch 47/100, Loss: 1.785683996975422
Epoch 48/100, Loss: 1.8109031841158867
Epoch 49/100, Loss: 1.8745597898960114
Epoch 50/100, Loss: 1.8677250072360039
Epoch 51/100, Loss: 1.8742422014474869
Epoch 52/100, Loss: 1.9063385054469109
Epoch 53/100, Loss: 1.8262516111135483
Epoch 54/100, Loss: 1.9586573727428913
Epoch 55/100, Loss: 1.9341682270169258
Epoch 56/100, Loss: 1.792044848203659
Epoch 57/100, Loss: 1.8129101917147636
Epoch 58/100, Loss: 1.8498599380254745
Epoch 59/100, Loss: 1.7518300265073776
Epoch 60/100, Loss: 1.8901315331459045
Epoch 61/100, Loss: 1.7703371793031693

Epoch 62/100, Loss: 1.8360568769276142
Epoch 63/100, Loss: 1.9011006727814674
Epoch 64/100, Loss: 1.753777876496315
Epoch 65/100, Loss: 1.8559686094522476
Epoch 66/100, Loss: 1.715373434126377
Epoch 67/100, Loss: 1.7239386141300201
Epoch 68/100, Loss: 2.024063415825367
Epoch 69/100, Loss: 1.842509388923645
Epoch 70/100, Loss: 1.9768280312418938
Epoch 71/100, Loss: 1.802429810166359
Epoch 72/100, Loss: 1.8402618765830994
Epoch 73/100, Loss: 1.7036347463726997
Epoch 74/100, Loss: 1.882582649588585
Epoch 75/100, Loss: 1.8327658027410507
Epoch 76/100, Loss: 1.8648527711629868

Epoch 77/100, Loss: 1.7663549073040485
Epoch 78/100, Loss: 1.8503996506333351
Epoch 79/100, Loss: 1.8572237715125084
Epoch 80/100, Loss: 1.9956909194588661
Epoch 81/100, Loss: 1.7831996455788612
Epoch 82/100, Loss: 1.8049800768494606
Epoch 83/100, Loss: 1.6255484968423843
Epoch 84/100, Loss: 1.9403606578707695
Epoch 85/100, Loss: 1.6873956620693207
Epoch 86/100, Loss: 1.8764903135597706
Epoch 87/100, Loss: 1.6502734646201134
Epoch 88/100, Loss: 1.8587321788072586
Epoch 89/100, Loss: 1.8700378015637398
Epoch 90/100, Loss: 1.6811399161815643
Epoch 91/100, Loss: 1.8712807446718216
Epoch 92/100, Loss: 1.9449700489640236
Epoch 93/100, Loss: 1.915159858763218
Epoch 94/100, Loss: 1.9612372443079948

Epoch 95/100, Loss: 1.82844839990139
Epoch 96/100, Loss: 1.7263567224144936
Epoch 97/100, Loss: 2.3664902970194817
Epoch 98/100, Loss: 1.6564500629901886
Epoch 99/100, Loss: 1.816070333123207
Epoch 100/100, Loss: 1.7319325059652328
Fold 1/5 done
Epoch 1/100, Loss: 2.77486003190279
Epoch 2/100, Loss: 2.5674181133508682
Epoch 3/100, Loss: 2.6046813391149044
Epoch 4/100, Loss: 2.826778583228588
Epoch 5/100, Loss: 2.9731737300753593
Epoch 6/100, Loss: 2.8854755982756615
Epoch 7/100, Loss: 2.895872585475445
Epoch 8/100, Loss: 2.9713233783841133
Epoch 9/100, Loss: 3.1478884667158127
Epoch 10/100, Loss: 2.855192683637142
Epoch 11/100, Loss: 3.0730268359184265

Epoch 12/100, Loss: 2.6516654938459396
Epoch 13/100, Loss: 3.3404309302568436
Epoch 14/100, Loss: 2.9454425573349
Epoch 15/100, Loss: 3.071028232574463
Epoch 16/100, Loss: 2.737303704023361
Epoch 17/100, Loss: 3.1241667196154594
Epoch 18/100, Loss: 3.1374777257442474
Epoch 19/100, Loss: 2.977506071329117
Epoch 20/100, Loss: 2.9498258531093597
Epoch 21/100, Loss: 3.009260654449463
Epoch 22/100, Loss: 2.593631461262703
Epoch 23/100, Loss: 3.1571523919701576
Epoch 24/100, Loss: 2.9221173971891403
Epoch 25/100, Loss: 2.8573432117700577
Epoch 26/100, Loss: 2.7104570120573044
Epoch 27/100, Loss: 2.8972637206315994
Epoch 28/100, Loss: 2.846833199262619
Epoch 29/100, Loss: 2.9227421656250954
Epoch 30/100, Loss: 2.867811419069767

Epoch 31/100, Loss: 2.8187450617551804
Epoch 32/100, Loss: 2.919886663556099
Epoch 33/100, Loss: 2.9666512608528137
Epoch 34/100, Loss: 2.9935465902090073
Epoch 35/100, Loss: 2.7996630370616913
Epoch 36/100, Loss: 3.1923729926347733
Epoch 37/100, Loss: 2.745144158601761
Epoch 38/100, Loss: 2.7827135175466537
Epoch 39/100, Loss: 2.6571669057011604
Epoch 40/100, Loss: 2.682936728000641
Epoch 41/100, Loss: 2.7177877575159073
Epoch 42/100, Loss: 2.892448879778385
Epoch 43/100, Loss: 2.838780477643013
Epoch 44/100, Loss: 3.407293565571308
Epoch 45/100, Loss: 3.083950214087963
Epoch 46/100, Loss: 2.7916615158319473
Epoch 47/100, Loss: 2.6698266714811325
Epoch 48/100, Loss: 2.6380217373371124

Epoch 49/100, Loss: 2.732995644211769
Epoch 50/100, Loss: 2.8098543137311935
Epoch 51/100, Loss: 2.6030305474996567
Epoch 52/100, Loss: 3.0314837619662285
Epoch 53/100, Loss: 2.6371883675456047
Epoch 54/100, Loss: 2.903497464954853
Epoch 55/100, Loss: 2.838977001607418
Epoch 56/100, Loss: 3.808531381189823
Epoch 57/100, Loss: 2.7346963211894035
Epoch 58/100, Loss: 3.4807097241282463
Epoch 59/100, Loss: 2.9293882250785828
Epoch 60/100, Loss: 2.779210112988949
Epoch 61/100, Loss: 3.0268475860357285
Epoch 62/100, Loss: 2.956474594771862
Epoch 63/100, Loss: 3.665071740746498
Epoch 64/100, Loss: 3.132485866546631
Epoch 65/100, Loss: 2.704156555235386
Epoch 66/100, Loss: 2.4101010262966156

Epoch 67/100, Loss: 2.7299823835492134
Epoch 68/100, Loss: 3.0738928765058517
Epoch 69/100, Loss: 2.7874129712581635
Epoch 70/100, Loss: 2.864824153482914
Epoch 71/100, Loss: 2.820487894117832
Epoch 72/100, Loss: 3.0172745883464813
Epoch 73/100, Loss: 2.8855846524238586
Epoch 74/100, Loss: 2.7492156624794006
Epoch 75/100, Loss: 2.74147592484951
Epoch 76/100, Loss: 3.144384041428566
Epoch 77/100, Loss: 2.749966710805893
Epoch 78/100, Loss: 2.73648951202631
Epoch 79/100, Loss: 3.3646533265709877
Epoch 80/100, Loss: 2.6997457295656204
Epoch 81/100, Loss: 2.955952674150467
Epoch 82/100, Loss: 2.987809509038925
Epoch 83/100, Loss: 3.4625001326203346

Epoch 84/100, Loss: 2.650643989443779
Epoch 85/100, Loss: 3.1559775322675705
Epoch 86/100, Loss: 2.8336039781570435
Epoch 87/100, Loss: 2.8808048218488693
Epoch 88/100, Loss: 2.6549602448940277
Epoch 89/100, Loss: 2.9591230377554893
Epoch 90/100, Loss: 2.895325891673565
Epoch 91/100, Loss: 2.9613595083355904
Epoch 92/100, Loss: 2.6327192410826683
Epoch 93/100, Loss: 2.737941488623619
Epoch 94/100, Loss: 2.9979747906327248
Epoch 95/100, Loss: 2.782675713300705
Epoch 96/100, Loss: 3.554745502769947
Epoch 97/100, Loss: 2.830015331506729
Epoch 98/100, Loss: 2.9767022132873535
Epoch 99/100, Loss: 2.899412401020527
Epoch 100/100, Loss: 3.020629845559597
Fold 2/5 done

Epoch 1/100, Loss: 2.345614843070507
Epoch 2/100, Loss: 2.5002530589699745
Epoch 3/100, Loss: 2.7180824279785156
Epoch 4/100, Loss: 2.490541882812977
Epoch 5/100, Loss: 2.467513009905815
Epoch 6/100, Loss: 2.648679733276367
Epoch 7/100, Loss: 2.505253531038761
Epoch 8/100, Loss: 2.5520488023757935
Epoch 9/100, Loss: 2.652640365064144
Epoch 10/100, Loss: 2.4372177943587303
Epoch 11/100, Loss: 2.275155730545521
Epoch 12/100, Loss: 2.400148294866085
Epoch 13/100, Loss: 2.3707135021686554
Epoch 14/100, Loss: 2.562551163136959
Epoch 15/100, Loss: 2.41156155616045
Epoch 16/100, Loss: 2.602739080786705
Epoch 17/100, Loss: 2.95745263248682

Epoch 18/100, Loss: 2.5098530873656273
Epoch 19/100, Loss: 2.4786278530955315
Epoch 20/100, Loss: 2.4984955862164497
Epoch 21/100, Loss: 2.593896619975567
Epoch 22/100, Loss: 2.3657128736376762
Epoch 23/100, Loss: 2.6604229360818863
Epoch 24/100, Loss: 2.3361202627420425
Epoch 25/100, Loss: 2.562196008861065
Epoch 26/100, Loss: 2.610264964401722
Epoch 27/100, Loss: 2.5083393678069115
Epoch 28/100, Loss: 2.582916244864464
Epoch 29/100, Loss: 2.1919223070144653
Epoch 30/100, Loss: 2.45653422921896
Epoch 31/100, Loss: 2.467330366373062
Epoch 32/100, Loss: 2.4465148225426674
Epoch 33/100, Loss: 2.5634650364518166
Epoch 34/100, Loss: 2.6053527295589447
Epoch 35/100, Loss: 2.5682648196816444

Epoch 36/100, Loss: 2.442353703081608
Epoch 37/100, Loss: 2.6837569065392017
Epoch 38/100, Loss: 2.168925330042839
Epoch 39/100, Loss: 2.4865792542696
Epoch 40/100, Loss: 2.518452502787113
Epoch 41/100, Loss: 2.451853886246681
Epoch 42/100, Loss: 2.2568138763308525
Epoch 43/100, Loss: 2.643066428601742
Epoch 44/100, Loss: 2.547584690153599
Epoch 45/100, Loss: 2.5639950782060623
Epoch 46/100, Loss: 2.547895446419716
Epoch 47/100, Loss: 2.6853223368525505
Epoch 48/100, Loss: 2.511818937957287
Epoch 49/100, Loss: 2.3353981375694275
Epoch 50/100, Loss: 3.373228244483471
Epoch 51/100, Loss: 2.378606915473938
Epoch 52/100, Loss: 2.553343579173088

Epoch 53/100, Loss: 2.435799717903137
Epoch 54/100, Loss: 2.952117256820202
Epoch 55/100, Loss: 2.435347191989422
Epoch 56/100, Loss: 2.458306424319744
Epoch 57/100, Loss: 2.6679893732070923
Epoch 58/100, Loss: 2.361879274249077
Epoch 59/100, Loss: 2.3232461810112
Epoch 60/100, Loss: 2.4567927345633507
Epoch 61/100, Loss: 2.3907262831926346
Epoch 62/100, Loss: 2.395785443484783
Epoch 63/100, Loss: 2.477277271449566
Epoch 64/100, Loss: 2.420208901166916
Epoch 65/100, Loss: 2.3089924827218056
Epoch 66/100, Loss: 2.16806460916996
Epoch 67/100, Loss: 2.503563016653061
Epoch 68/100, Loss: 2.472332000732422
Epoch 69/100, Loss: 2.503735691308975

Epoch 70/100, Loss: 2.5000499933958054
Epoch 71/100, Loss: 2.5739358589053154
Epoch 72/100, Loss: 2.327362596988678
Epoch 73/100, Loss: 2.7742536813020706
Epoch 74/100, Loss: 2.35732264816761
Epoch 75/100, Loss: 2.8043832033872604
Epoch 76/100, Loss: 2.6773992478847504
Epoch 77/100, Loss: 2.4012190774083138
Epoch 78/100, Loss: 2.5975329354405403
Epoch 79/100, Loss: 2.4435938224196434
Epoch 80/100, Loss: 2.5215325728058815
Epoch 81/100, Loss: 2.488702856004238
Epoch 82/100, Loss: 2.218936450779438
Epoch 83/100, Loss: 2.356625646352768
Epoch 84/100, Loss: 2.5798602402210236
Epoch 85/100, Loss: 2.628885231912136
Epoch 86/100, Loss: 2.543179988861084

Epoch 87/100, Loss: 2.4766842499375343
Epoch 88/100, Loss: 2.4543448090553284
Epoch 89/100, Loss: 2.3871483132243156
Epoch 90/100, Loss: 2.27917592972517
Epoch 91/100, Loss: 2.3622180595993996
Epoch 92/100, Loss: 2.1131345108151436
Epoch 93/100, Loss: 2.6164295002818108
Epoch 94/100, Loss: 2.680830292403698
Epoch 95/100, Loss: 2.4775806441903114
Epoch 96/100, Loss: 2.7764571979641914
Epoch 97/100, Loss: 2.4923343881964684
Epoch 98/100, Loss: 3.3930222019553185
Epoch 99/100, Loss: 2.4358193278312683
Epoch 100/100, Loss: 2.5775807201862335
Fold 3/5 done
Epoch 1/100, Loss: 1.9741262644529343
Epoch 2/100, Loss: 2.028437025845051

Epoch 3/100, Loss: 2.052248790860176
Epoch 4/100, Loss: 2.15574998408556
Epoch 5/100, Loss: 2.0517695993185043
Epoch 6/100, Loss: 2.203311324119568
Epoch 7/100, Loss: 2.0936514735221863
Epoch 8/100, Loss: 2.159747861325741
Epoch 9/100, Loss: 2.2398552522063255
Epoch 10/100, Loss: 2.219967268407345
Epoch 11/100, Loss: 2.0563090443611145
Epoch 12/100, Loss: 2.1580303460359573
Epoch 13/100, Loss: 2.1214572191238403
Epoch 14/100, Loss: 2.1648637652397156
Epoch 15/100, Loss: 2.240876317024231
Epoch 16/100, Loss: 2.110672026872635
Epoch 17/100, Loss: 2.065515875816345
Epoch 18/100, Loss: 2.178707592189312
Epoch 19/100, Loss: 2.096242778003216
Epoch 20/100, Loss: 2.0588891953229904

Epoch 21/100, Loss: 2.093065485358238
Epoch 22/100, Loss: 2.1789311543107033
Epoch 23/100, Loss: 2.0612343922257423
Epoch 24/100, Loss: 2.1273383498191833
Epoch 25/100, Loss: 2.163064122200012
Epoch 26/100, Loss: 2.158557653427124
Epoch 27/100, Loss: 2.150946870446205
Epoch 28/100, Loss: 2.062954820692539
Epoch 29/100, Loss: 2.1822399720549583
Epoch 30/100, Loss: 2.2591913640499115
Epoch 31/100, Loss: 2.149580731987953
Epoch 32/100, Loss: 2.1171093434095383
Epoch 33/100, Loss: 2.118276461958885
Epoch 34/100, Loss: 2.0676987767219543
Epoch 35/100, Loss: 2.2081784829497337
Epoch 36/100, Loss: 2.1527128145098686
Epoch 37/100, Loss: 2.1840504556894302

Epoch 38/100, Loss: 2.1490022242069244
Epoch 39/100, Loss: 2.057438939809799
Epoch 40/100, Loss: 2.0669178143143654
Epoch 41/100, Loss: 1.9943465143442154
Epoch 42/100, Loss: 2.1023105829954147
Epoch 43/100, Loss: 2.145550362765789
Epoch 44/100, Loss: 2.0867356583476067
Epoch 45/100, Loss: 2.2229228764772415
Epoch 46/100, Loss: 2.1435863822698593
Epoch 47/100, Loss: 2.106045790016651
Epoch 48/100, Loss: 2.080090008676052
Epoch 49/100, Loss: 2.1031141206622124
Epoch 50/100, Loss: 2.1048759669065475
Epoch 51/100, Loss: 2.1367082595825195
Epoch 52/100, Loss: 2.109324671328068
Epoch 53/100, Loss: 2.1507278084754944

Epoch 54/100, Loss: 2.1374075785279274
Epoch 55/100, Loss: 2.089859127998352
Epoch 56/100, Loss: 2.047173924744129
Epoch 57/100, Loss: 2.0737777575850487
Epoch 58/100, Loss: 1.9809444323182106
Epoch 59/100, Loss: 2.2268525883555412
Epoch 60/100, Loss: 2.1747958585619926
Epoch 61/100, Loss: 2.044242650270462
Epoch 62/100, Loss: 2.3024189695715904
Epoch 63/100, Loss: 2.0478961169719696
Epoch 64/100, Loss: 1.9531072974205017
Epoch 65/100, Loss: 2.1216835156083107
Epoch 66/100, Loss: 2.1854473799467087
Epoch 67/100, Loss: 2.1582799181342125
Epoch 68/100, Loss: 2.073236420750618
Epoch 69/100, Loss: 2.2303878143429756
Epoch 70/100, Loss: 2.111639976501465

Epoch 71/100, Loss: 2.1264670193195343
Epoch 72/100, Loss: 2.188460737466812
Epoch 73/100, Loss: 2.1298454999923706
Epoch 74/100, Loss: 2.097766675055027
Epoch 75/100, Loss: 2.0798343122005463
Epoch 76/100, Loss: 2.2051316872239113
Epoch 77/100, Loss: 2.1289169788360596
Epoch 78/100, Loss: 2.2728712931275368
Epoch 79/100, Loss: 2.00860133767128
Epoch 80/100, Loss: 2.069416858255863
Epoch 81/100, Loss: 2.1833751648664474
Epoch 82/100, Loss: 2.337534539401531
Epoch 83/100, Loss: 2.070963703095913
Epoch 84/100, Loss: 2.1559742987155914
Epoch 85/100, Loss: 2.161380350589752
Epoch 86/100, Loss: 2.1265933215618134
Epoch 87/100, Loss: 2.1571116521954536

Epoch 88/100, Loss: 2.0720978155732155
Epoch 89/100, Loss: 2.051615245640278
Epoch 90/100, Loss: 2.080662839114666
Epoch 91/100, Loss: 2.155398428440094
Epoch 92/100, Loss: 2.2019763812422752
Epoch 93/100, Loss: 2.1064633205533028
Epoch 94/100, Loss: 2.2521084398031235
Epoch 95/100, Loss: 2.2446217462420464
Epoch 96/100, Loss: 2.0201303511857986
Epoch 97/100, Loss: 2.211037814617157
Epoch 98/100, Loss: 2.129165366292
Epoch 99/100, Loss: 2.0472869277000427
Epoch 100/100, Loss: 2.17033139616251
Fold 4/5 done
Epoch 1/100, Loss: 1.912755310535431

Epoch 2/100, Loss: 1.9422736018896103
Epoch 3/100, Loss: 1.8874351978302002
Epoch 4/100, Loss: 2.068989872932434
Epoch 5/100, Loss: 2.011026106774807
Epoch 6/100, Loss: 1.8300782069563866
Epoch 7/100, Loss: 1.956071399152279
Epoch 8/100, Loss: 1.914707489311695
Epoch 9/100, Loss: 1.926443636417389
Epoch 10/100, Loss: 1.872468151152134
Epoch 11/100, Loss: 1.8352277055382729
Epoch 12/100, Loss: 1.8734712302684784
Epoch 13/100, Loss: 1.9046349599957466
Epoch 14/100, Loss: 1.9493777379393578
Epoch 15/100, Loss: 2.1060987785458565
Epoch 16/100, Loss: 1.8051854744553566

Epoch 17/100, Loss: 1.9608663842082024
Epoch 18/100, Loss: 1.972487896680832
Epoch 19/100, Loss: 1.907586082816124
Epoch 20/100, Loss: 1.8538376092910767
Epoch 21/100, Loss: 1.9740628376603127
Epoch 22/100, Loss: 1.8732135742902756
Epoch 23/100, Loss: 2.062835417687893
Epoch 24/100, Loss: 1.8252014070749283
Epoch 25/100, Loss: 2.022556610405445
Epoch 26/100, Loss: 2.045382894575596
Epoch 27/100, Loss: 1.9406553879380226
Epoch 28/100, Loss: 1.8475739359855652
Epoch 29/100, Loss: 2.039665050804615
Epoch 30/100, Loss: 1.953427940607071

Epoch 31/100, Loss: 1.983086235821247
Epoch 32/100, Loss: 1.9201165288686752
Epoch 33/100, Loss: 1.910988986492157
Epoch 34/100, Loss: 1.9445706829428673
Epoch 35/100, Loss: 1.8006140291690826
Epoch 36/100, Loss: 1.8409696370363235
Epoch 37/100, Loss: 1.9978749752044678
Epoch 38/100, Loss: 1.7855301052331924
Epoch 39/100, Loss: 1.9194257780909538
Epoch 40/100, Loss: 1.8755347728729248
Epoch 41/100, Loss: 1.8945243805646896
Epoch 42/100, Loss: 1.9755487367510796
Epoch 43/100, Loss: 1.8724564462900162
Epoch 44/100, Loss: 2.027404997497797
Epoch 45/100, Loss: 2.2164450362324715

Epoch 46/100, Loss: 1.8370799347758293
Epoch 47/100, Loss: 1.9169185683131218
Epoch 48/100, Loss: 1.8481809347867966
Epoch 49/100, Loss: 2.4083909392356873
Epoch 50/100, Loss: 1.8222885057330132
Epoch 51/100, Loss: 1.964023657143116
Epoch 52/100, Loss: 1.830587387084961
Epoch 53/100, Loss: 1.985455073416233
Epoch 54/100, Loss: 2.001792810857296
Epoch 55/100, Loss: 2.122680865228176
Epoch 56/100, Loss: 1.8583987951278687
Epoch 57/100, Loss: 1.8526252508163452
Epoch 58/100, Loss: 1.9959837421774864
Epoch 59/100, Loss: 1.9254021868109703
Epoch 60/100, Loss: 2.00465901941061

Epoch 61/100, Loss: 1.8986409902572632
Epoch 62/100, Loss: 1.8861589953303337
Epoch 63/100, Loss: 2.3944770619273186
Epoch 64/100, Loss: 1.9790023565292358
Epoch 65/100, Loss: 1.8934567980468273
Epoch 66/100, Loss: 2.0494469627738
Epoch 67/100, Loss: 1.7573874853551388
Epoch 68/100, Loss: 1.96956317871809
Epoch 69/100, Loss: 1.9297779873013496
Epoch 70/100, Loss: 1.9553316831588745
Epoch 71/100, Loss: 1.9287704899907112
Epoch 72/100, Loss: 1.9916669055819511
Epoch 73/100, Loss: 2.1905850991606712
Epoch 74/100, Loss: 1.8894234597682953
Epoch 75/100, Loss: 1.846837617456913
Epoch 76/100, Loss: 1.970505565404892

Epoch 77/100, Loss: 2.009673148393631
Epoch 78/100, Loss: 1.9786780774593353
Epoch 79/100, Loss: 2.004308633506298
Epoch 80/100, Loss: 2.268220268189907
Epoch 81/100, Loss: 1.902095027267933
Epoch 82/100, Loss: 1.8331909254193306
Epoch 83/100, Loss: 1.9257634207606316
Epoch 84/100, Loss: 1.98174349963665
Epoch 85/100, Loss: 1.820245884358883
Epoch 86/100, Loss: 1.8534337282180786

Epoch 87/100, Loss: 1.8432433120906353
Epoch 88/100, Loss: 2.0190740451216698
Epoch 89/100, Loss: 1.8779736831784248
Epoch 90/100, Loss: 1.8347297087311745
Epoch 91/100, Loss: 1.908999279141426
Epoch 92/100, Loss: 2.021515592932701
Epoch 93/100, Loss: 2.047103226184845
Epoch 94/100, Loss: 1.8811439611017704
Epoch 95/100, Loss: 1.9998201951384544
Epoch 96/100, Loss: 2.0452053397893906

Epoch 97/100, Loss: 1.9229722768068314
Epoch 98/100, Loss: 1.9835537672042847
Epoch 99/100, Loss: 1.9130484387278557
Epoch 100/100, Loss: 2.075090378522873
Fold 5/5 done

In [11]:
ap = average_precision_score(y_true, anomaly_scores)
print(f"Deep SVDD AP (5-fold CV) = {ap:.4f}")
sb.glue("GBG500_ap_spectral_deep_svdd", float(ap))

Deep SVDD AP (5-fold CV) = 0.4982