In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import average_precision_score
from sklearn.model_selection import StratifiedKFold
from pyod.models.deep_svdd import DeepSVDD
import sys
import scrapbook as sb

sys.path.append('..')
from utils import reshape_to_numpy, interpolate_missing_values, denoise_data, compute_spectrograms, time_avg_pooling

In [2]:
seed = 1
sampling_rate = 10
nperseg=64
noverlap=32
accel_cutoff = 0.4
accel_order = 30
gyro_cutoff = 0.6
gyro_order = 20
batch_size = 32
epochs = 100
hidden_neurons = [128, 64, 32]
n_splits = 5

In [3]:
# Parameters
seed = 28

In [4]:
rng = np.random.RandomState(seed)

In [5]:
data = pd.read_parquet("../data/GBG500.parquet")
data

,ride_id,time_index,ax,ay,az,rx,ry,rz
0,005043f1a7520cebf1e17fd166a00a3190e2433530f236...,0,-2.512796,-9.385012,-1.053078,-0.009155,0.009155,-0.201416
1,005043f1a7520cebf1e17fd166a00a3190e2433530f236...,100,-2.491268,-9.385012,-1.079390,-0.036621,0.027465,-0.155639
2,005043f1a7520cebf1e17fd166a00a3190e2433530f236...,200,-2.534324,-9.382022,-1.030952,0.036621,0.027465,-0.073242
3,005043f1a7520cebf1e17fd166a00a3190e2433530f236...,300,-2.488278,-9.383218,-1.091948,-0.045776,0.036621,-0.183105
4,005043f1a7520cebf1e17fd166a00a3190e2433530f236...,400,-2.483494,-9.382022,-1.100320,-0.045776,0.027465,-0.192260
...,...,...,...,...,...,...,...,...
1529542,ffb6f2f5dc6ba768d88dc0bc1af4cad235526aa9e24168...,241300,0.459862,-9.140430,-3.318900,1.556396,-0.091552,0.274658
1529543,ffb6f2f5dc6ba768d88dc0bc1af4cad235526aa9e24168...,241400,0.455676,-9.140430,-3.321292,1.583861,-0.119018,0.274658
1529544,ffb6f2f5dc6ba768d88dc0bc1af4cad235526aa9e24168...,241500,0.459862,-9.139832,-3.317704,1.583861,-0.109863,0.274658
1529545,ffb6f2f5dc6ba768d88dc0bc1af4cad235526aa9e24168...,241600,0.456274,-9.142224,-3.321292,1.574707,-0.137329,0.283813
1529546,ffb6f2f5dc6ba768d88dc0bc1af4cad235526aa9e24168...,241700,0.458666,-9.139832,-3.320694,1.574707,-0.137329,0.274658

In [6]:
labels = pd.read_csv("../data/GBG500_labels.csv")
labels.columns = labels.columns.str.lower()
ride_order_df = pd.DataFrame({"ride_id": data["ride_id"].unique()})
labels_sorted = ride_order_df.merge(
    labels,
    on="ride_id",
    how="left"
)
labels_sorted

                                               ride_id        label
0    005043f1a7520cebf1e17fd166a00a3190e2433530f236...         Safe
1    00d223cb7aecc9c0cc5871e32a6c45027a068eba07c572...     Reckless
2    02288a4aeca044203394e982e76b87818021dea2b34df9...         Safe
3    0236bdcf13d473ea24d97f5eaeea459f257dffac005694...  Bad weather
4    0238e5dd85143f1b6c59b200bc32f14361b8fc84c51a87...         Safe
..                                                 ...          ...
495  fe5d7f84d692bbccad8bd566a3ad5c3108fa9f90acd671...         Safe
496  fe67169632306d4668b2affedef510df2cb43e2fb41220...         Safe
497  fee44667fdc8ab4995c702fc3bd36178de0b1ca2c64687...         Safe
498  ff79b2e945b93c2a5efc3a06365267b3a160e7849ba57d...         Safe
499  ffb6f2f5dc6ba768d88dc0bc1af4cad235526aa9e24168...         Safe

[500 rows x 2 columns]

In [7]:
data_np = reshape_to_numpy(
    data,
    features = ["ax", "ay", "az", "rx", "ry", "rz"],
    max_timestamps = 4800
)

data_np_clean = interpolate_missing_values(
    data_np,
    method='linear',
    limit=None
)

data_np_clean = denoise_data(
    data=data_np_clean,
    accel_indices=[0, 1, 2],
    gyro_indices=[3, 4, 5],
    accel_cutoff=accel_cutoff,
    accel_order=accel_order,
    gyro_cutoff=gyro_cutoff,
    gyro_order=gyro_order,
)

In [8]:
# Compute spectrograms for all rides
spectrograms_array = compute_spectrograms(data_np_clean, sampling_rate, nperseg, noverlap)
spectrograms_array.shape

(500, 149, 6, 33)

In [9]:
# Aggregate spectrograms using time-averaged pooling
X_feat = time_avg_pooling(spectrograms_array)
X_feat.shape

(500, 198)

In [10]:
# 5-fold stratified CV with Deep SVDD
skf = StratifiedKFold(n_splits=n_splits, shuffle=True, random_state=rng.randint(1000))
y_true = (labels_sorted['label'] == 'Reckless').astype(int).values
anomaly_scores = np.full(len(y_true), np.nan)

for fold, (train_idx, test_idx) in enumerate(skf.split(X_feat, y_true)):
    sc = StandardScaler()
    X_train = sc.fit_transform(X_feat[train_idx])
    X_test = sc.transform(X_feat[test_idx])

    np.random.seed(rng.randint(1000))
    model = DeepSVDD(
        n_features=X_train.shape[1],
        hidden_neurons=hidden_neurons,
        epochs=epochs,
        batch_size=batch_size,
        random_state=rng.randint(1000),
    )
    model.fit(X_train)
    anomaly_scores[test_idx] = model.decision_function(X_test)
    print(f"Fold {fold+1}/{n_splits} done")

Epoch 1/100, Loss: 2.197641499340534
Epoch 2/100, Loss: 2.1034573912620544
Epoch 3/100, Loss: 2.268039681017399
Epoch 4/100, Loss: 1.9000130593776703
Epoch 5/100, Loss: 2.185005411505699
Epoch 6/100, Loss: 1.993408903479576
Epoch 7/100, Loss: 2.0773750990629196
Epoch 8/100, Loss: 2.095249779522419
Epoch 9/100, Loss: 2.0037931725382805
Epoch 10/100, Loss: 2.0640319287776947
Epoch 11/100, Loss: 2.0715248361229897
Epoch 12/100, Loss: 2.144304037094116
Epoch 13/100, Loss: 2.0215093791484833
Epoch 14/100, Loss: 2.008163385093212
Epoch 15/100, Loss: 2.10538037866354
Epoch 16/100, Loss: 2.0341575890779495

Epoch 17/100, Loss: 2.1124786883592606
Epoch 18/100, Loss: 2.157105468213558
Epoch 19/100, Loss: 1.9844173341989517
Epoch 20/100, Loss: 2.1042960956692696
Epoch 21/100, Loss: 2.044911168515682
Epoch 22/100, Loss: 2.1488266810774803
Epoch 23/100, Loss: 2.0672109723091125
Epoch 24/100, Loss: 2.1177002415060997
Epoch 25/100, Loss: 2.143313191831112
Epoch 26/100, Loss: 2.2186058089137077
Epoch 27/100, Loss: 2.1570766866207123
Epoch 28/100, Loss: 2.055360049009323
Epoch 29/100, Loss: 2.012472502887249
Epoch 30/100, Loss: 2.1227529644966125
Epoch 31/100, Loss: 1.9785341694951057
Epoch 32/100, Loss: 2.122814364731312
Epoch 33/100, Loss: 2.209723763167858
Epoch 34/100, Loss: 1.9840946346521378

Epoch 35/100, Loss: 2.075393594801426
Epoch 36/100, Loss: 2.061026230454445
Epoch 37/100, Loss: 2.0370782762765884
Epoch 38/100, Loss: 2.116681769490242
Epoch 39/100, Loss: 2.051518552005291
Epoch 40/100, Loss: 1.979932963848114
Epoch 41/100, Loss: 2.0222917199134827
Epoch 42/100, Loss: 2.161152794957161
Epoch 43/100, Loss: 2.0052982419729233
Epoch 44/100, Loss: 2.0985744521021843
Epoch 45/100, Loss: 2.060255527496338
Epoch 46/100, Loss: 2.1805930137634277
Epoch 47/100, Loss: 2.0947221219539642
Epoch 48/100, Loss: 2.1263668835163116
Epoch 49/100, Loss: 2.0071008503437042
Epoch 50/100, Loss: 2.033387005329132
Epoch 51/100, Loss: 2.0291795432567596
Epoch 52/100, Loss: 2.1422637701034546

Epoch 53/100, Loss: 2.095602311193943
Epoch 54/100, Loss: 1.97611615806818
Epoch 55/100, Loss: 2.0717583373188972
Epoch 56/100, Loss: 2.1038626953959465
Epoch 57/100, Loss: 2.0998651906847954
Epoch 58/100, Loss: 2.0661893039941788
Epoch 59/100, Loss: 2.1636747494339943
Epoch 60/100, Loss: 2.240234814584255
Epoch 61/100, Loss: 2.0566466003656387
Epoch 62/100, Loss: 2.1769784539937973
Epoch 63/100, Loss: 2.007634863257408
Epoch 64/100, Loss: 2.060677945613861
Epoch 65/100, Loss: 2.0346013233065605
Epoch 66/100, Loss: 2.006625972688198
Epoch 67/100, Loss: 1.946480743587017
Epoch 68/100, Loss: 2.155524328351021
Epoch 69/100, Loss: 2.0912512987852097
Epoch 70/100, Loss: 2.131161689758301
Epoch 71/100, Loss: 1.9261947274208069

Epoch 72/100, Loss: 2.026010826230049
Epoch 73/100, Loss: 2.0376590341329575
Epoch 74/100, Loss: 2.0950805321335793
Epoch 75/100, Loss: 2.1233443692326546
Epoch 76/100, Loss: 2.1298495829105377
Epoch 77/100, Loss: 2.084210619330406
Epoch 78/100, Loss: 2.1411179900169373
Epoch 79/100, Loss: 2.008297950029373
Epoch 80/100, Loss: 1.9695505499839783
Epoch 81/100, Loss: 2.088477559387684
Epoch 82/100, Loss: 2.1283552274107933
Epoch 83/100, Loss: 1.9960079416632652
Epoch 84/100, Loss: 2.098350666463375
Epoch 85/100, Loss: 2.0622854456305504
Epoch 86/100, Loss: 2.103075250983238
Epoch 87/100, Loss: 2.0626955181360245
Epoch 88/100, Loss: 2.0692440271377563
Epoch 89/100, Loss: 2.175697334110737
Epoch 90/100, Loss: 2.1663927361369133

Epoch 91/100, Loss: 2.0049830228090286
Epoch 92/100, Loss: 2.1113083511590958
Epoch 93/100, Loss: 2.0943255722522736
Epoch 94/100, Loss: 2.061525233089924
Epoch 95/100, Loss: 2.1736143827438354
Epoch 96/100, Loss: 1.9590709209442139
Epoch 97/100, Loss: 1.9310404807329178
Epoch 98/100, Loss: 1.984002761542797
Epoch 99/100, Loss: 2.099447213113308
Epoch 100/100, Loss: 2.189551331102848
Fold 1/5 done
Epoch 1/100, Loss: 2.329576686024666
Epoch 2/100, Loss: 2.387310840189457
Epoch 3/100, Loss: 2.3961183950304985
Epoch 4/100, Loss: 2.747247900813818
Epoch 5/100, Loss: 2.2985468059778214
Epoch 6/100, Loss: 2.448646664619446
Epoch 7/100, Loss: 2.5500799864530563
Epoch 8/100, Loss: 2.482451196759939

Epoch 9/100, Loss: 2.3302926793694496
Epoch 10/100, Loss: 2.478193588554859
Epoch 11/100, Loss: 2.4850037544965744
Epoch 12/100, Loss: 2.3230971097946167
Epoch 13/100, Loss: 2.7117569521069527
Epoch 14/100, Loss: 2.4324435219168663
Epoch 15/100, Loss: 2.462108835577965
Epoch 16/100, Loss: 2.6910004317760468
Epoch 17/100, Loss: 2.5709520876407623
Epoch 18/100, Loss: 2.6256657168269157
Epoch 19/100, Loss: 2.3771950528025627
Epoch 20/100, Loss: 2.461291290819645
Epoch 21/100, Loss: 2.301200680434704
Epoch 22/100, Loss: 2.265876829624176
Epoch 23/100, Loss: 2.456816628575325
Epoch 24/100, Loss: 2.4165362417697906
Epoch 25/100, Loss: 2.51554599404335
Epoch 26/100, Loss: 2.414338804781437

Epoch 27/100, Loss: 2.305084116756916
Epoch 28/100, Loss: 2.6336472257971764
Epoch 29/100, Loss: 2.448410950601101
Epoch 30/100, Loss: 2.3874551355838776
Epoch 31/100, Loss: 2.6283789053559303
Epoch 32/100, Loss: 2.4393424093723297
Epoch 33/100, Loss: 2.4689325392246246
Epoch 34/100, Loss: 2.4212301820516586
Epoch 35/100, Loss: 2.5845315530896187
Epoch 36/100, Loss: 2.4116910621523857
Epoch 37/100, Loss: 2.5052030980587006
Epoch 38/100, Loss: 2.5299577862024307
Epoch 39/100, Loss: 2.45432198792696
Epoch 40/100, Loss: 2.597915716469288
Epoch 41/100, Loss: 2.5472760275006294
Epoch 42/100, Loss: 2.3314286693930626
Epoch 43/100, Loss: 2.4672611355781555
Epoch 44/100, Loss: 2.14834713190794
Epoch 45/100, Loss: 2.704653836786747

Epoch 46/100, Loss: 2.4696070179343224
Epoch 47/100, Loss: 2.2116630151867867
Epoch 48/100, Loss: 2.624776855111122
Epoch 49/100, Loss: 2.298380456864834
Epoch 50/100, Loss: 2.5750425159931183
Epoch 51/100, Loss: 2.9739775210618973
Epoch 52/100, Loss: 2.7104246765375137
Epoch 53/100, Loss: 2.4361538141965866
Epoch 54/100, Loss: 2.6351887360215187
Epoch 55/100, Loss: 2.643801487982273
Epoch 56/100, Loss: 2.3437865376472473
Epoch 57/100, Loss: 2.387306682765484
Epoch 58/100, Loss: 2.4726159870624542
Epoch 59/100, Loss: 2.400539346039295
Epoch 60/100, Loss: 2.379935748875141
Epoch 61/100, Loss: 2.374071218073368
Epoch 62/100, Loss: 2.485807791352272
Epoch 63/100, Loss: 2.335048347711563
Epoch 64/100, Loss: 3.226182971149683

Epoch 65/100, Loss: 2.5835584700107574
Epoch 66/100, Loss: 2.360649671405554
Epoch 67/100, Loss: 2.675161190330982
Epoch 68/100, Loss: 2.6568243578076363
Epoch 69/100, Loss: 2.3303436674177647
Epoch 70/100, Loss: 2.607027180492878
Epoch 71/100, Loss: 2.4048796743154526
Epoch 72/100, Loss: 2.4900721050798893
Epoch 73/100, Loss: 2.6649360582232475
Epoch 74/100, Loss: 2.639820922166109
Epoch 75/100, Loss: 2.607916735112667
Epoch 76/100, Loss: 2.271467886865139
Epoch 77/100, Loss: 2.555260792374611
Epoch 78/100, Loss: 2.487929217517376
Epoch 79/100, Loss: 2.38666357845068
Epoch 80/100, Loss: 2.2296899259090424
Epoch 81/100, Loss: 2.379956789314747
Epoch 82/100, Loss: 2.5089350566267967
Epoch 83/100, Loss: 2.5186912827193737

Epoch 84/100, Loss: 2.6040285900235176
Epoch 85/100, Loss: 2.460319459438324
Epoch 86/100, Loss: 2.4316709488630295
Epoch 87/100, Loss: 2.337822765111923
Epoch 88/100, Loss: 2.5500840544700623
Epoch 89/100, Loss: 2.44965136051178
Epoch 90/100, Loss: 2.6379008442163467
Epoch 91/100, Loss: 2.6218973584473133
Epoch 92/100, Loss: 2.298917070031166
Epoch 93/100, Loss: 2.7195670381188393
Epoch 94/100, Loss: 2.4841744154691696
Epoch 95/100, Loss: 2.5104474276304245
Epoch 96/100, Loss: 2.434192880988121
Epoch 97/100, Loss: 2.465021848678589
Epoch 98/100, Loss: 2.5669635757803917
Epoch 99/100, Loss: 2.4287493266165257
Epoch 100/100, Loss: 2.542882453650236
Fold 2/5 done
Epoch 1/100, Loss: 2.962629795074463

Epoch 2/100, Loss: 3.830363631248474
Epoch 3/100, Loss: 3.293807774782181
Epoch 4/100, Loss: 3.1236565113067627
Epoch 5/100, Loss: 3.1697197631001472
Epoch 6/100, Loss: 3.5360099971294403
Epoch 7/100, Loss: 3.3196230977773666
Epoch 8/100, Loss: 3.037150204181671
Epoch 9/100, Loss: 3.73588614910841
Epoch 10/100, Loss: 3.8155273497104645
Epoch 11/100, Loss: 3.605716221034527
Epoch 12/100, Loss: 3.541672319173813
Epoch 13/100, Loss: 3.556340739130974
Epoch 14/100, Loss: 3.6556970328092575
Epoch 15/100, Loss: 3.744310736656189
Epoch 16/100, Loss: 3.7627755850553513
Epoch 17/100, Loss: 3.9933051764965057
Epoch 18/100, Loss: 2.9619100689888
Epoch 19/100, Loss: 3.6745860129594803
Epoch 20/100, Loss: 3.2036676332354546

Epoch 21/100, Loss: 3.7844705879688263
Epoch 22/100, Loss: 3.5358193665742874
Epoch 23/100, Loss: 3.5145162492990494
Epoch 24/100, Loss: 3.7057689651846886
Epoch 25/100, Loss: 3.6499700471758842
Epoch 26/100, Loss: 3.576198771595955
Epoch 27/100, Loss: 3.1151010021567345
Epoch 28/100, Loss: 3.784535735845566
Epoch 29/100, Loss: 3.4649551808834076
Epoch 30/100, Loss: 2.912521705031395
Epoch 31/100, Loss: 3.115746036171913
Epoch 32/100, Loss: 3.7850707545876503
Epoch 33/100, Loss: 3.789783626794815
Epoch 34/100, Loss: 3.6792252212762833
Epoch 35/100, Loss: 2.9977923184633255
Epoch 36/100, Loss: 3.477871850132942
Epoch 37/100, Loss: 3.536911964416504

Epoch 38/100, Loss: 3.6712819188833237
Epoch 39/100, Loss: 3.5287966653704643
Epoch 40/100, Loss: 3.3937845081090927
Epoch 41/100, Loss: 3.7770979031920433
Epoch 42/100, Loss: 3.474868893623352
Epoch 43/100, Loss: 3.624749720096588
Epoch 44/100, Loss: 3.7679669559001923
Epoch 45/100, Loss: 3.919633261859417
Epoch 46/100, Loss: 3.6314257085323334
Epoch 47/100, Loss: 3.7560580670833588
Epoch 48/100, Loss: 2.985976465046406
Epoch 49/100, Loss: 3.5465500950813293
Epoch 50/100, Loss: 3.605791836977005
Epoch 51/100, Loss: 3.8451607823371887
Epoch 52/100, Loss: 3.6679995208978653
Epoch 53/100, Loss: 3.514657348394394
Epoch 54/100, Loss: 3.6375283151865005

Epoch 55/100, Loss: 3.5103465169668198
Epoch 56/100, Loss: 3.314719758927822
Epoch 57/100, Loss: 3.3006076589226723
Epoch 58/100, Loss: 3.613025449216366
Epoch 59/100, Loss: 3.8553429022431374
Epoch 60/100, Loss: 4.726839944720268
Epoch 61/100, Loss: 3.2574557065963745
Epoch 62/100, Loss: 3.645697481930256
Epoch 63/100, Loss: 3.601061135530472
Epoch 64/100, Loss: 3.6549649238586426
Epoch 65/100, Loss: 3.1692454665899277
Epoch 66/100, Loss: 3.0658678263425827
Epoch 67/100, Loss: 3.7799957990646362
Epoch 68/100, Loss: 3.398440048098564
Epoch 69/100, Loss: 3.7052845135331154
Epoch 70/100, Loss: 3.64473856985569
Epoch 71/100, Loss: 3.684480845928192
Epoch 72/100, Loss: 3.068750247359276

Epoch 73/100, Loss: 3.4627755433321
Epoch 74/100, Loss: 3.8268578201532364
Epoch 75/100, Loss: 3.5901341140270233
Epoch 76/100, Loss: 3.5045863315463066
Epoch 77/100, Loss: 3.8282659128308296
Epoch 78/100, Loss: 3.476794049143791
Epoch 79/100, Loss: 3.744076117873192
Epoch 80/100, Loss: 3.6706313341856003
Epoch 81/100, Loss: 3.6032878905534744
Epoch 82/100, Loss: 3.37708055973053
Epoch 83/100, Loss: 3.4278321266174316
Epoch 84/100, Loss: 3.6849523931741714
Epoch 85/100, Loss: 3.6440617740154266
Epoch 86/100, Loss: 3.4813244491815567
Epoch 87/100, Loss: 3.2493932768702507
Epoch 88/100, Loss: 3.663193479180336
Epoch 89/100, Loss: 3.5025289803743362
Epoch 90/100, Loss: 3.7310067266225815

Epoch 91/100, Loss: 3.5067910850048065
Epoch 92/100, Loss: 3.5283353477716446
Epoch 93/100, Loss: 3.497608855366707
Epoch 94/100, Loss: 4.184490159153938
Epoch 95/100, Loss: 3.6358211636543274
Epoch 96/100, Loss: 3.7268767282366753
Epoch 97/100, Loss: 3.601905807852745
Epoch 98/100, Loss: 3.6150729656219482
Epoch 99/100, Loss: 3.761625714600086
Epoch 100/100, Loss: 3.483482226729393
Fold 3/5 done
Epoch 1/100, Loss: 1.9607529751956463
Epoch 2/100, Loss: 2.1262515261769295
Epoch 3/100, Loss: 2.045340307056904
Epoch 4/100, Loss: 2.0288741514086723
Epoch 5/100, Loss: 2.0039231665432453
Epoch 6/100, Loss: 2.039890617132187
Epoch 7/100, Loss: 2.141756996512413

Epoch 8/100, Loss: 2.0001704320311546
Epoch 9/100, Loss: 2.1562492921948433
Epoch 10/100, Loss: 1.908386081457138
Epoch 11/100, Loss: 1.7901822179555893
Epoch 12/100, Loss: 1.9829638600349426
Epoch 13/100, Loss: 2.0670575499534607
Epoch 14/100, Loss: 2.1133626848459244
Epoch 15/100, Loss: 1.8507482334971428
Epoch 16/100, Loss: 2.0621281638741493
Epoch 17/100, Loss: 2.1066786721348763
Epoch 18/100, Loss: 2.1042518094182014
Epoch 19/100, Loss: 1.9481187239289284
Epoch 20/100, Loss: 1.9016613066196442
Epoch 21/100, Loss: 1.9042123556137085
Epoch 22/100, Loss: 1.8937241435050964
Epoch 23/100, Loss: 1.799929141998291
Epoch 24/100, Loss: 2.0485737323760986
Epoch 25/100, Loss: 2.0768336579203606

Epoch 26/100, Loss: 2.0605678409337997
Epoch 27/100, Loss: 2.1315771713852882
Epoch 28/100, Loss: 1.7660403698682785
Epoch 29/100, Loss: 2.0195862874388695
Epoch 30/100, Loss: 1.8728827349841595
Epoch 31/100, Loss: 1.9238213673233986
Epoch 32/100, Loss: 2.0941997319459915
Epoch 33/100, Loss: 1.821552887558937
Epoch 34/100, Loss: 1.9722038060426712
Epoch 35/100, Loss: 1.9228522777557373
Epoch 36/100, Loss: 2.100547604262829
Epoch 37/100, Loss: 2.0344858542084694
Epoch 38/100, Loss: 2.1133208759129047
Epoch 39/100, Loss: 2.5963221937417984
Epoch 40/100, Loss: 2.0823129788041115
Epoch 41/100, Loss: 1.761936753988266
Epoch 42/100, Loss: 1.9929538369178772
Epoch 43/100, Loss: 2.1160226836800575

Epoch 44/100, Loss: 1.7520423606038094
Epoch 45/100, Loss: 1.9756112918257713
Epoch 46/100, Loss: 2.0060859844088554
Epoch 47/100, Loss: 1.990723080933094
Epoch 48/100, Loss: 2.454270027577877
Epoch 49/100, Loss: 1.9389497712254524
Epoch 50/100, Loss: 2.0830005183815956
Epoch 51/100, Loss: 1.7255856171250343
Epoch 52/100, Loss: 2.1163196489214897
Epoch 53/100, Loss: 1.916241705417633
Epoch 54/100, Loss: 2.0561997443437576
Epoch 55/100, Loss: 2.004853993654251
Epoch 56/100, Loss: 1.9214507043361664
Epoch 57/100, Loss: 1.785540983080864
Epoch 58/100, Loss: 2.0946365296840668
Epoch 59/100, Loss: 1.9688231982290745
Epoch 60/100, Loss: 2.0409568697214127
Epoch 61/100, Loss: 1.8219688758254051

Epoch 62/100, Loss: 1.8199911713600159
Epoch 63/100, Loss: 1.9443561397492886
Epoch 64/100, Loss: 1.8622507229447365
Epoch 65/100, Loss: 1.9994545876979828
Epoch 66/100, Loss: 2.005760908126831
Epoch 67/100, Loss: 2.01224522292614
Epoch 68/100, Loss: 2.0214579477906227
Epoch 69/100, Loss: 1.9339552894234657
Epoch 70/100, Loss: 2.0470988154411316
Epoch 71/100, Loss: 1.723422884941101
Epoch 72/100, Loss: 1.929084911942482
Epoch 73/100, Loss: 2.0743715912103653
Epoch 74/100, Loss: 2.02605526894331
Epoch 75/100, Loss: 2.0641931742429733
Epoch 76/100, Loss: 2.1148995235562325
Epoch 77/100, Loss: 2.126204803586006
Epoch 78/100, Loss: 1.8327032402157784
Epoch 79/100, Loss: 2.03107800334692

Epoch 80/100, Loss: 2.0144419744610786
Epoch 81/100, Loss: 2.1073060631752014
Epoch 82/100, Loss: 1.912673994898796
Epoch 83/100, Loss: 1.9341566413640976
Epoch 84/100, Loss: 1.990620069205761
Epoch 85/100, Loss: 1.8040545135736465
Epoch 86/100, Loss: 2.1722118332982063
Epoch 87/100, Loss: 1.9212101101875305
Epoch 88/100, Loss: 1.7862693294882774
Epoch 89/100, Loss: 1.7821357175707817
Epoch 90/100, Loss: 2.0815088525414467
Epoch 91/100, Loss: 1.995041474699974
Epoch 92/100, Loss: 2.5192296653985977
Epoch 93/100, Loss: 2.1155450716614723
Epoch 94/100, Loss: 2.003954663872719
Epoch 95/100, Loss: 1.9774658307433128
Epoch 96/100, Loss: 1.8676327653229237
Epoch 97/100, Loss: 1.8183413222432137

Epoch 98/100, Loss: 1.8125021383166313
Epoch 99/100, Loss: 2.0949425622820854
Epoch 100/100, Loss: 1.9329508692026138
Fold 4/5 done
Epoch 1/100, Loss: 3.511793941259384
Epoch 2/100, Loss: 3.1628982350230217
Epoch 3/100, Loss: 3.1931224018335342
Epoch 4/100, Loss: 3.4020801782608032
Epoch 5/100, Loss: 3.239334285259247
Epoch 6/100, Loss: 3.2000604569911957
Epoch 7/100, Loss: 3.1094093173742294
Epoch 8/100, Loss: 2.9382815286517143
Epoch 9/100, Loss: 3.167568653821945
Epoch 10/100, Loss: 3.152605287730694
Epoch 11/100, Loss: 2.9741734713315964
Epoch 12/100, Loss: 3.2486874386668205
Epoch 13/100, Loss: 3.446987599134445

Epoch 14/100, Loss: 3.002586677670479
Epoch 15/100, Loss: 2.8854245841503143
Epoch 16/100, Loss: 3.281598888337612
Epoch 17/100, Loss: 3.7681609392166138
Epoch 18/100, Loss: 3.0966435074806213
Epoch 19/100, Loss: 3.1095192283391953
Epoch 20/100, Loss: 2.9145189076662064
Epoch 21/100, Loss: 4.053644925355911
Epoch 22/100, Loss: 3.2476799339056015
Epoch 23/100, Loss: 2.958944760262966
Epoch 24/100, Loss: 3.431309148669243
Epoch 25/100, Loss: 3.053533412516117
Epoch 26/100, Loss: 3.348450519144535
Epoch 27/100, Loss: 3.1383545100688934
Epoch 28/100, Loss: 3.0817159712314606
Epoch 29/100, Loss: 3.1698731034994125
Epoch 30/100, Loss: 3.314773142337799
Epoch 31/100, Loss: 3.1730280071496964

Epoch 32/100, Loss: 3.2552197873592377
Epoch 33/100, Loss: 3.1878790855407715
Epoch 34/100, Loss: 3.094450607895851
Epoch 35/100, Loss: 3.4356422126293182
Epoch 36/100, Loss: 3.2057368010282516
Epoch 37/100, Loss: 3.031627871096134
Epoch 38/100, Loss: 3.17599555850029
Epoch 39/100, Loss: 3.069014571607113
Epoch 40/100, Loss: 3.207079455256462
Epoch 41/100, Loss: 3.239220291376114
Epoch 42/100, Loss: 3.417769968509674
Epoch 43/100, Loss: 3.024542883038521
Epoch 44/100, Loss: 3.658106580376625
Epoch 45/100, Loss: 2.957817792892456
Epoch 46/100, Loss: 3.0554649010300636
Epoch 47/100, Loss: 3.070489540696144
Epoch 48/100, Loss: 2.9114611372351646
Epoch 49/100, Loss: 3.115012049674988

Epoch 50/100, Loss: 3.4526122510433197
Epoch 51/100, Loss: 3.161310702562332
Epoch 52/100, Loss: 3.1628807485103607
Epoch 53/100, Loss: 3.1698489636182785
Epoch 54/100, Loss: 3.1389021426439285
Epoch 55/100, Loss: 3.2719816416502
Epoch 56/100, Loss: 2.9701423943042755
Epoch 57/100, Loss: 3.0663625299930573
Epoch 58/100, Loss: 3.2816782370209694
Epoch 59/100, Loss: 3.0453875362873077
Epoch 60/100, Loss: 2.977781556546688
Epoch 61/100, Loss: 3.010690361261368
Epoch 62/100, Loss: 3.29070732742548
Epoch 63/100, Loss: 3.0745151937007904
Epoch 64/100, Loss: 2.9713243395090103
Epoch 65/100, Loss: 3.1959098801016808
Epoch 66/100, Loss: 3.497666671872139
Epoch 67/100, Loss: 3.099194511771202

Epoch 68/100, Loss: 2.972221925854683
Epoch 69/100, Loss: 2.9578044340014458
Epoch 70/100, Loss: 3.150180399417877
Epoch 71/100, Loss: 3.146047279238701
Epoch 72/100, Loss: 3.403188556432724
Epoch 73/100, Loss: 3.3454139977693558
Epoch 74/100, Loss: 3.081625320017338
Epoch 75/100, Loss: 3.182291731238365
Epoch 76/100, Loss: 3.3790200501680374
Epoch 77/100, Loss: 3.0498039722442627
Epoch 78/100, Loss: 3.4634112417697906
Epoch 79/100, Loss: 2.8468977957963943
Epoch 80/100, Loss: 2.9797577559947968
Epoch 81/100, Loss: 2.889573812484741
Epoch 82/100, Loss: 3.3207975029945374
Epoch 83/100, Loss: 3.3415857404470444
Epoch 84/100, Loss: 3.0566868036985397
Epoch 85/100, Loss: 3.025391273200512

Epoch 86/100, Loss: 3.4018818587064743
Epoch 87/100, Loss: 3.1833122596144676
Epoch 88/100, Loss: 3.0944306030869484
Epoch 89/100, Loss: 3.2491058707237244
Epoch 90/100, Loss: 2.8912365436553955
Epoch 91/100, Loss: 3.3020853996276855
Epoch 92/100, Loss: 2.8503749296069145
Epoch 93/100, Loss: 3.343048021197319
Epoch 94/100, Loss: 3.28144271671772
Epoch 95/100, Loss: 3.206214025616646
Epoch 96/100, Loss: 3.0208367705345154
Epoch 97/100, Loss: 2.9983511865139008
Epoch 98/100, Loss: 3.312765471637249
Epoch 99/100, Loss: 3.2777613699436188
Epoch 100/100, Loss: 3.060284301638603
Fold 5/5 done

In [11]:
ap = average_precision_score(y_true, anomaly_scores)
print(f"Deep SVDD AP (5-fold CV) = {ap:.4f}")
sb.glue("GBG500_ap_spectral_deep_svdd", float(ap))

Deep SVDD AP (5-fold CV) = 0.7386