In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import average_precision_score
from sklearn.model_selection import StratifiedKFold
from pyod.models.deep_svdd import DeepSVDD
import sys
import scrapbook as sb

sys.path.append('..')
from utils import reshape_to_numpy, interpolate_missing_values, denoise_data, compute_spectrograms, time_avg_pooling

In [2]:
seed = 1
sampling_rate = 10
nperseg=64
noverlap=32
accel_cutoff = 0.4
accel_order = 30
gyro_cutoff = 0.6
gyro_order = 20
batch_size = 32
epochs = 100
hidden_neurons = [128, 64, 32]
n_splits = 5

In [3]:
# Parameters
seed = 2

In [4]:
rng = np.random.RandomState(seed)

In [5]:
data = pd.read_parquet("../data/GBG500.parquet")
data

,ride_id,time_index,ax,ay,az,rx,ry,rz
0,005043f1a7520cebf1e17fd166a00a3190e2433530f236...,0,-2.512796,-9.385012,-1.053078,-0.009155,0.009155,-0.201416
1,005043f1a7520cebf1e17fd166a00a3190e2433530f236...,100,-2.491268,-9.385012,-1.079390,-0.036621,0.027465,-0.155639
2,005043f1a7520cebf1e17fd166a00a3190e2433530f236...,200,-2.534324,-9.382022,-1.030952,0.036621,0.027465,-0.073242
3,005043f1a7520cebf1e17fd166a00a3190e2433530f236...,300,-2.488278,-9.383218,-1.091948,-0.045776,0.036621,-0.183105
4,005043f1a7520cebf1e17fd166a00a3190e2433530f236...,400,-2.483494,-9.382022,-1.100320,-0.045776,0.027465,-0.192260
...,...,...,...,...,...,...,...,...
1529542,ffb6f2f5dc6ba768d88dc0bc1af4cad235526aa9e24168...,241300,0.459862,-9.140430,-3.318900,1.556396,-0.091552,0.274658
1529543,ffb6f2f5dc6ba768d88dc0bc1af4cad235526aa9e24168...,241400,0.455676,-9.140430,-3.321292,1.583861,-0.119018,0.274658
1529544,ffb6f2f5dc6ba768d88dc0bc1af4cad235526aa9e24168...,241500,0.459862,-9.139832,-3.317704,1.583861,-0.109863,0.274658
1529545,ffb6f2f5dc6ba768d88dc0bc1af4cad235526aa9e24168...,241600,0.456274,-9.142224,-3.321292,1.574707,-0.137329,0.283813
1529546,ffb6f2f5dc6ba768d88dc0bc1af4cad235526aa9e24168...,241700,0.458666,-9.139832,-3.320694,1.574707,-0.137329,0.274658

In [6]:
labels = pd.read_csv("../data/GBG500_labels.csv")
labels.columns = labels.columns.str.lower()
ride_order_df = pd.DataFrame({"ride_id": data["ride_id"].unique()})
labels_sorted = ride_order_df.merge(
    labels,
    on="ride_id",
    how="left"
)
labels_sorted

                                               ride_id        label
0    005043f1a7520cebf1e17fd166a00a3190e2433530f236...         Safe
1    00d223cb7aecc9c0cc5871e32a6c45027a068eba07c572...     Reckless
2    02288a4aeca044203394e982e76b87818021dea2b34df9...         Safe
3    0236bdcf13d473ea24d97f5eaeea459f257dffac005694...  Bad weather
4    0238e5dd85143f1b6c59b200bc32f14361b8fc84c51a87...         Safe
..                                                 ...          ...
495  fe5d7f84d692bbccad8bd566a3ad5c3108fa9f90acd671...         Safe
496  fe67169632306d4668b2affedef510df2cb43e2fb41220...         Safe
497  fee44667fdc8ab4995c702fc3bd36178de0b1ca2c64687...         Safe
498  ff79b2e945b93c2a5efc3a06365267b3a160e7849ba57d...         Safe
499  ffb6f2f5dc6ba768d88dc0bc1af4cad235526aa9e24168...         Safe

[500 rows x 2 columns]

In [7]:
data_np = reshape_to_numpy(
    data,
    features = ["ax", "ay", "az", "rx", "ry", "rz"],
    max_timestamps = 4800
)

data_np_clean = interpolate_missing_values(
    data_np,
    method='linear',
    limit=None
)

data_np_clean = denoise_data(
    data=data_np_clean,
    accel_indices=[0, 1, 2],
    gyro_indices=[3, 4, 5],
    accel_cutoff=accel_cutoff,
    accel_order=accel_order,
    gyro_cutoff=gyro_cutoff,
    gyro_order=gyro_order,
)

In [8]:
# Compute spectrograms for all rides
spectrograms_array = compute_spectrograms(data_np_clean, sampling_rate, nperseg, noverlap)
spectrograms_array.shape

(500, 149, 6, 33)

In [9]:
# Aggregate spectrograms using time-averaged pooling
X_feat = time_avg_pooling(spectrograms_array)
X_feat.shape

(500, 198)

In [10]:
# 5-fold stratified CV with Deep SVDD
skf = StratifiedKFold(n_splits=n_splits, shuffle=True, random_state=rng.randint(1000))
y_true = (labels_sorted['label'] == 'Reckless').astype(int).values
anomaly_scores = np.full(len(y_true), np.nan)

for fold, (train_idx, test_idx) in enumerate(skf.split(X_feat, y_true)):
    sc = StandardScaler()
    X_train = sc.fit_transform(X_feat[train_idx])
    X_test = sc.transform(X_feat[test_idx])

    np.random.seed(rng.randint(1000))
    model = DeepSVDD(
        n_features=X_train.shape[1],
        hidden_neurons=hidden_neurons,
        epochs=epochs,
        batch_size=batch_size,
        random_state=rng.randint(1000),
    )
    model.fit(X_train)
    anomaly_scores[test_idx] = model.decision_function(X_test)
    print(f"Fold {fold+1}/{n_splits} done")

Epoch 1/100, Loss: 2.147749327123165
Epoch 2/100, Loss: 2.4087895154953003
Epoch 3/100, Loss: 2.193440265953541
Epoch 4/100, Loss: 2.403915151953697
Epoch 5/100, Loss: 2.5157173722982407
Epoch 6/100, Loss: 2.2789569422602654
Epoch 7/100, Loss: 2.305187076330185
Epoch 8/100, Loss: 2.414927676320076
Epoch 9/100, Loss: 2.5809671580791473
Epoch 10/100, Loss: 2.6208155751228333
Epoch 11/100, Loss: 2.177956350147724
Epoch 12/100, Loss: 2.3877772465348244
Epoch 13/100, Loss: 2.1228640004992485
Epoch 14/100, Loss: 3.045818828046322
Epoch 15/100, Loss: 2.9479726552963257
Epoch 16/100, Loss: 2.516314558684826

Epoch 17/100, Loss: 3.1239450499415398
Epoch 18/100, Loss: 2.538935214281082
Epoch 19/100, Loss: 2.4380269944667816
Epoch 20/100, Loss: 2.368872694671154
Epoch 21/100, Loss: 2.5496943295001984
Epoch 22/100, Loss: 2.3887137174606323
Epoch 23/100, Loss: 2.2447522282600403
Epoch 24/100, Loss: 2.444135844707489
Epoch 25/100, Loss: 2.46483451128006
Epoch 26/100, Loss: 2.7844764664769173
Epoch 27/100, Loss: 2.530507802963257
Epoch 28/100, Loss: 2.5426403880119324
Epoch 29/100, Loss: 2.494924359023571
Epoch 30/100, Loss: 2.4162238612771034
Epoch 31/100, Loss: 2.5552395582199097
Epoch 32/100, Loss: 2.3321240544319153

Epoch 33/100, Loss: 2.3493190482258797
Epoch 34/100, Loss: 2.2264853790402412
Epoch 35/100, Loss: 2.3759646378457546
Epoch 36/100, Loss: 2.7457101196050644
Epoch 37/100, Loss: 2.3223207890987396
Epoch 38/100, Loss: 2.4946498423814774
Epoch 39/100, Loss: 2.216513507068157
Epoch 40/100, Loss: 2.2187631353735924
Epoch 41/100, Loss: 2.4319026321172714
Epoch 42/100, Loss: 2.5322042405605316
Epoch 43/100, Loss: 2.112500250339508
Epoch 44/100, Loss: 2.3747209310531616
Epoch 45/100, Loss: 2.368357352912426
Epoch 46/100, Loss: 2.5519075468182564
Epoch 47/100, Loss: 2.945165164768696

Epoch 48/100, Loss: 2.2935241609811783
Epoch 49/100, Loss: 2.2455827221274376
Epoch 50/100, Loss: 2.308924086391926
Epoch 51/100, Loss: 2.4245763570070267
Epoch 52/100, Loss: 2.383218601346016
Epoch 53/100, Loss: 2.20985134691
Epoch 54/100, Loss: 2.2958069816231728
Epoch 55/100, Loss: 2.369023822247982
Epoch 56/100, Loss: 2.398487150669098
Epoch 57/100, Loss: 2.416868209838867
Epoch 58/100, Loss: 2.24892071634531
Epoch 59/100, Loss: 2.4147263690829277
Epoch 60/100, Loss: 2.4118506759405136

Epoch 61/100, Loss: 2.6037214398384094
Epoch 62/100, Loss: 2.575387641787529
Epoch 63/100, Loss: 2.5572927370667458
Epoch 64/100, Loss: 2.253600537776947
Epoch 65/100, Loss: 2.5198887810111046
Epoch 66/100, Loss: 2.5602486208081245
Epoch 67/100, Loss: 2.461237385869026
Epoch 68/100, Loss: 2.444426454603672
Epoch 69/100, Loss: 2.474324733018875
Epoch 70/100, Loss: 2.2677334919571877
Epoch 71/100, Loss: 2.232625260949135
Epoch 72/100, Loss: 2.4961933717131615
Epoch 73/100, Loss: 2.4369896352291107
Epoch 74/100, Loss: 2.3756589218974113
Epoch 75/100, Loss: 2.2483744770288467
Epoch 76/100, Loss: 2.5645241364836693

Epoch 77/100, Loss: 2.2620255053043365
Epoch 78/100, Loss: 2.3201329112052917
Epoch 79/100, Loss: 2.5101066902279854
Epoch 80/100, Loss: 2.392060585319996
Epoch 81/100, Loss: 2.3754364773631096
Epoch 82/100, Loss: 2.459792912006378
Epoch 83/100, Loss: 2.2170257344841957
Epoch 84/100, Loss: 2.06699101626873
Epoch 85/100, Loss: 2.5454696118831635
Epoch 86/100, Loss: 2.304316520690918
Epoch 87/100, Loss: 2.1958516389131546
Epoch 88/100, Loss: 2.3788891583681107
Epoch 89/100, Loss: 2.2857339307665825
Epoch 90/100, Loss: 2.43846894800663
Epoch 91/100, Loss: 2.1477591767907143
Epoch 92/100, Loss: 2.2121195644140244

Epoch 93/100, Loss: 2.3298356980085373
Epoch 94/100, Loss: 2.518129773437977
Epoch 95/100, Loss: 2.435267746448517
Epoch 96/100, Loss: 2.2263850048184395
Epoch 97/100, Loss: 2.5400682389736176
Epoch 98/100, Loss: 2.286283999681473
Epoch 99/100, Loss: 2.226023942232132
Epoch 100/100, Loss: 2.4628747403621674
Fold 1/5 done
Epoch 1/100, Loss: 2.4165478348731995
Epoch 2/100, Loss: 2.214167036116123
Epoch 3/100, Loss: 2.1402132138609886
Epoch 4/100, Loss: 2.189629316329956
Epoch 5/100, Loss: 2.2204825803637505
Epoch 6/100, Loss: 2.0474985167384148
Epoch 7/100, Loss: 2.1727447137236595
Epoch 8/100, Loss: 2.549441836774349

Epoch 9/100, Loss: 2.147537276148796
Epoch 10/100, Loss: 2.1318401396274567
Epoch 11/100, Loss: 2.303306967020035
Epoch 12/100, Loss: 2.2362750470638275
Epoch 13/100, Loss: 2.2041463255882263
Epoch 14/100, Loss: 2.06874381005764
Epoch 15/100, Loss: 2.2773042246699333
Epoch 16/100, Loss: 2.160812236368656
Epoch 17/100, Loss: 2.4694335609674454
Epoch 18/100, Loss: 2.088454157114029
Epoch 19/100, Loss: 2.328285001218319
Epoch 20/100, Loss: 2.1199740171432495
Epoch 21/100, Loss: 2.55267546325922
Epoch 22/100, Loss: 2.042743131518364
Epoch 23/100, Loss: 2.339658662676811

Epoch 24/100, Loss: 2.3755256608128548
Epoch 25/100, Loss: 2.081987526267767
Epoch 26/100, Loss: 2.1817123629152775
Epoch 27/100, Loss: 2.1718429550528526
Epoch 28/100, Loss: 2.186793692409992
Epoch 29/100, Loss: 2.243856832385063
Epoch 30/100, Loss: 1.9377531558275223
Epoch 31/100, Loss: 2.1134527772665024
Epoch 32/100, Loss: 2.021397028118372
Epoch 33/100, Loss: 2.159785605967045
Epoch 34/100, Loss: 2.0396808460354805
Epoch 35/100, Loss: 2.0752533823251724
Epoch 36/100, Loss: 2.251766584813595
Epoch 37/100, Loss: 1.9215209260582924
Epoch 38/100, Loss: 2.1749070063233376

Epoch 39/100, Loss: 2.3622452951967716
Epoch 40/100, Loss: 1.967484526336193
Epoch 41/100, Loss: 2.3863805532455444
Epoch 42/100, Loss: 1.934904307126999
Epoch 43/100, Loss: 2.1847154423594475
Epoch 44/100, Loss: 1.9720860123634338
Epoch 45/100, Loss: 2.0637284219264984
Epoch 46/100, Loss: 2.2219105437397957
Epoch 47/100, Loss: 2.262442648410797
Epoch 48/100, Loss: 2.012703999876976
Epoch 49/100, Loss: 2.2309764102101326
Epoch 50/100, Loss: 2.204918749630451
Epoch 51/100, Loss: 2.387559548020363
Epoch 52/100, Loss: 2.3931475281715393
Epoch 53/100, Loss: 2.3532641157507896
Epoch 54/100, Loss: 1.8520341217517853
Epoch 55/100, Loss: 2.0442475974559784
Epoch 56/100, Loss: 2.2553827315568924

Epoch 57/100, Loss: 2.49628983438015
Epoch 58/100, Loss: 2.0109526365995407
Epoch 59/100, Loss: 2.2721595242619514
Epoch 60/100, Loss: 2.6667579635977745
Epoch 61/100, Loss: 1.9524555429816246
Epoch 62/100, Loss: 1.9849710538983345
Epoch 63/100, Loss: 2.278118848800659
Epoch 64/100, Loss: 2.2017306461930275
Epoch 65/100, Loss: 2.242527484893799
Epoch 66/100, Loss: 1.9752883687615395
Epoch 67/100, Loss: 1.980161502957344
Epoch 68/100, Loss: 2.0480064302682877
Epoch 69/100, Loss: 2.332905150949955
Epoch 70/100, Loss: 2.2141590490937233
Epoch 71/100, Loss: 2.200804591178894
Epoch 72/100, Loss: 2.1141159012913704
Epoch 73/100, Loss: 2.0849013179540634
Epoch 74/100, Loss: 2.415972612798214

Epoch 75/100, Loss: 2.0362286679446697
Epoch 76/100, Loss: 2.146802172064781
Epoch 77/100, Loss: 2.2111708000302315
Epoch 78/100, Loss: 2.318540573120117
Epoch 79/100, Loss: 1.9700023829936981
Epoch 80/100, Loss: 2.1450880989432335
Epoch 81/100, Loss: 1.981478102505207
Epoch 82/100, Loss: 2.0245149061083794
Epoch 83/100, Loss: 2.1370313987135887
Epoch 84/100, Loss: 2.2822951450943947
Epoch 85/100, Loss: 2.187018744647503
Epoch 86/100, Loss: 2.3363185450434685
Epoch 87/100, Loss: 2.276962533593178

Epoch 88/100, Loss: 2.2595645040273666
Epoch 89/100, Loss: 3.018124498426914
Epoch 90/100, Loss: 1.9404043853282928
Epoch 91/100, Loss: 2.2386879585683346
Epoch 92/100, Loss: 2.090031363070011
Epoch 93/100, Loss: 2.502332739531994
Epoch 94/100, Loss: 1.9983780533075333
Epoch 95/100, Loss: 2.4158065132796764
Epoch 96/100, Loss: 2.249598167836666
Epoch 97/100, Loss: 2.979093447327614
Epoch 98/100, Loss: 2.257288470864296
Epoch 99/100, Loss: 2.1931447125971317
Epoch 100/100, Loss: 2.295243889093399
Fold 2/5 done
Epoch 1/100, Loss: 3.797822915017605

Epoch 2/100, Loss: 3.8975363671779633
Epoch 3/100, Loss: 3.3682479709386826
Epoch 4/100, Loss: 3.6220570728182793
Epoch 5/100, Loss: 5.042842634022236
Epoch 6/100, Loss: 3.607947215437889
Epoch 7/100, Loss: 3.5857953056693077
Epoch 8/100, Loss: 3.8799555972218513
Epoch 9/100, Loss: 4.793699711561203
Epoch 10/100, Loss: 3.710671156644821
Epoch 11/100, Loss: 3.7180966213345528
Epoch 12/100, Loss: 3.8083702623844147
Epoch 13/100, Loss: 3.7595436200499535
Epoch 14/100, Loss: 3.4279273599386215
Epoch 15/100, Loss: 4.224543526768684
Epoch 16/100, Loss: 3.8454673662781715
Epoch 17/100, Loss: 3.6162089407444
Epoch 18/100, Loss: 3.7935646399855614

Epoch 19/100, Loss: 3.90932909399271
Epoch 20/100, Loss: 3.521504022181034
Epoch 21/100, Loss: 3.4261333271861076
Epoch 22/100, Loss: 4.16970457136631
Epoch 23/100, Loss: 3.7523395344614983
Epoch 24/100, Loss: 3.8838408067822456
Epoch 25/100, Loss: 3.759565107524395
Epoch 26/100, Loss: 3.8336554393172264
Epoch 27/100, Loss: 4.084083490073681
Epoch 28/100, Loss: 3.838493935763836
Epoch 29/100, Loss: 4.128452055156231
Epoch 30/100, Loss: 3.7058689892292023
Epoch 31/100, Loss: 3.822772614657879
Epoch 32/100, Loss: 3.653801716864109
Epoch 33/100, Loss: 3.468740053474903
Epoch 34/100, Loss: 3.990635871887207

Epoch 35/100, Loss: 3.722794510424137
Epoch 36/100, Loss: 3.423419125378132
Epoch 37/100, Loss: 3.768051326274872
Epoch 38/100, Loss: 3.4488999024033546
Epoch 39/100, Loss: 3.773825094103813
Epoch 40/100, Loss: 3.6318079084157944
Epoch 41/100, Loss: 4.051363125443459
Epoch 42/100, Loss: 3.678840085864067
Epoch 43/100, Loss: 3.7704415693879128
Epoch 44/100, Loss: 4.104204870760441
Epoch 45/100, Loss: 3.974648416042328
Epoch 46/100, Loss: 3.833862230181694
Epoch 47/100, Loss: 4.00076362490654

Epoch 48/100, Loss: 3.622918300330639
Epoch 49/100, Loss: 3.775895267724991
Epoch 50/100, Loss: 3.9960951805114746
Epoch 51/100, Loss: 3.8323635905981064
Epoch 52/100, Loss: 3.8369766175746918
Epoch 53/100, Loss: 3.6003625243902206
Epoch 54/100, Loss: 4.105172738432884
Epoch 55/100, Loss: 3.7669083401560783
Epoch 56/100, Loss: 3.6998984962701797
Epoch 57/100, Loss: 3.597810387611389
Epoch 58/100, Loss: 3.6526720374822617
Epoch 59/100, Loss: 3.8062414079904556
Epoch 60/100, Loss: 3.7098821625113487
Epoch 61/100, Loss: 3.154447816312313
Epoch 62/100, Loss: 3.7237519025802612
Epoch 63/100, Loss: 3.975735180079937

Epoch 64/100, Loss: 4.700269691646099
Epoch 65/100, Loss: 4.02628343552351
Epoch 66/100, Loss: 3.802396386861801
Epoch 67/100, Loss: 3.683422662317753
Epoch 68/100, Loss: 4.323483660817146
Epoch 69/100, Loss: 3.830176033079624
Epoch 70/100, Loss: 3.814593955874443
Epoch 71/100, Loss: 3.5324773713946342
Epoch 72/100, Loss: 3.9068481251597404
Epoch 73/100, Loss: 3.777843050658703
Epoch 74/100, Loss: 3.77439484000206
Epoch 75/100, Loss: 3.7001046016812325
Epoch 76/100, Loss: 3.9604934006929398
Epoch 77/100, Loss: 3.9322408363223076
Epoch 78/100, Loss: 3.911509670317173
Epoch 79/100, Loss: 3.639858901500702
Epoch 80/100, Loss: 3.550419218838215
Epoch 81/100, Loss: 3.5742639675736427

Epoch 82/100, Loss: 3.9163996800780296
Epoch 83/100, Loss: 3.9314819276332855
Epoch 84/100, Loss: 3.8652948439121246
Epoch 85/100, Loss: 3.657291293144226
Epoch 86/100, Loss: 3.579100474715233
Epoch 87/100, Loss: 3.608496442437172
Epoch 88/100, Loss: 4.136093631386757
Epoch 89/100, Loss: 4.076384410262108
Epoch 90/100, Loss: 3.6448024287819862
Epoch 91/100, Loss: 3.7258395478129387
Epoch 92/100, Loss: 3.5402022004127502
Epoch 93/100, Loss: 3.879294641315937
Epoch 94/100, Loss: 3.9031244069337845

Epoch 95/100, Loss: 3.5149999409914017
Epoch 96/100, Loss: 3.592317320406437
Epoch 97/100, Loss: 4.002878524363041
Epoch 98/100, Loss: 3.810499429702759
Epoch 99/100, Loss: 3.510278284549713
Epoch 100/100, Loss: 4.324452966451645
Fold 3/5 done
Epoch 1/100, Loss: 2.4573803767561913
Epoch 2/100, Loss: 2.4071623235940933
Epoch 3/100, Loss: 2.652401402592659
Epoch 4/100, Loss: 2.395730346441269
Epoch 5/100, Loss: 2.347942493855953
Epoch 6/100, Loss: 2.366742730140686
Epoch 7/100, Loss: 2.4651311114430428
Epoch 8/100, Loss: 2.4426372796297073
Epoch 9/100, Loss: 2.393772155046463
Epoch 10/100, Loss: 2.3818454667925835

Epoch 11/100, Loss: 2.3873517960309982
Epoch 12/100, Loss: 2.565378911793232
Epoch 13/100, Loss: 2.5219023525714874
Epoch 14/100, Loss: 2.5185339152812958
Epoch 15/100, Loss: 2.5694029182195663
Epoch 16/100, Loss: 2.48538376390934
Epoch 17/100, Loss: 2.3937399238348007
Epoch 18/100, Loss: 2.455274000763893
Epoch 19/100, Loss: 2.43083792924881
Epoch 20/100, Loss: 2.4111653566360474
Epoch 21/100, Loss: 2.3723371997475624
Epoch 22/100, Loss: 2.5095808282494545
Epoch 23/100, Loss: 2.4448904395103455
Epoch 24/100, Loss: 2.3117997273802757
Epoch 25/100, Loss: 2.4749277532100677

Epoch 26/100, Loss: 2.406624212861061
Epoch 27/100, Loss: 2.3904523253440857
Epoch 28/100, Loss: 2.4653334468603134
Epoch 29/100, Loss: 2.5148068368434906
Epoch 30/100, Loss: 2.44572089612484
Epoch 31/100, Loss: 2.4075073897838593
Epoch 32/100, Loss: 2.332127772271633
Epoch 33/100, Loss: 2.389614202082157
Epoch 34/100, Loss: 2.3120078444480896
Epoch 35/100, Loss: 2.506728872656822
Epoch 36/100, Loss: 2.3745495676994324
Epoch 37/100, Loss: 2.3339610397815704
Epoch 38/100, Loss: 2.336620345711708
Epoch 39/100, Loss: 2.4147333949804306

Epoch 40/100, Loss: 2.4002018719911575
Epoch 41/100, Loss: 2.472175106406212
Epoch 42/100, Loss: 2.3817999958992004
Epoch 43/100, Loss: 2.4912634789943695
Epoch 44/100, Loss: 2.4290370792150497
Epoch 45/100, Loss: 2.4118067026138306
Epoch 46/100, Loss: 2.501355305314064
Epoch 47/100, Loss: 2.420174762606621
Epoch 48/100, Loss: 2.344505302608013
Epoch 49/100, Loss: 2.3607238084077835
Epoch 50/100, Loss: 2.341013714671135
Epoch 51/100, Loss: 2.3726235032081604
Epoch 52/100, Loss: 2.3314399868249893
Epoch 53/100, Loss: 2.369078628718853
Epoch 54/100, Loss: 2.4108486995100975
Epoch 55/100, Loss: 2.5220282077789307

Epoch 56/100, Loss: 2.392158880829811
Epoch 57/100, Loss: 2.3750663474202156
Epoch 58/100, Loss: 2.456670306622982
Epoch 59/100, Loss: 2.4271179884672165
Epoch 60/100, Loss: 2.325746089220047
Epoch 61/100, Loss: 2.4150881469249725
Epoch 62/100, Loss: 2.404698930680752
Epoch 63/100, Loss: 2.4975481182336807
Epoch 64/100, Loss: 2.425223931670189
Epoch 65/100, Loss: 2.3847203999757767
Epoch 66/100, Loss: 2.47402323782444
Epoch 67/100, Loss: 2.352010056376457
Epoch 68/100, Loss: 2.5079914033412933
Epoch 69/100, Loss: 2.383719190955162
Epoch 70/100, Loss: 2.5058940574526787
Epoch 71/100, Loss: 2.408189743757248

Epoch 72/100, Loss: 2.401296339929104
Epoch 73/100, Loss: 2.448591724038124
Epoch 74/100, Loss: 2.4348270520567894
Epoch 75/100, Loss: 2.4820251762866974
Epoch 76/100, Loss: 2.343798205256462
Epoch 77/100, Loss: 2.343390703201294
Epoch 78/100, Loss: 2.4318918734788895
Epoch 79/100, Loss: 2.3118075504899025
Epoch 80/100, Loss: 2.56601545214653
Epoch 81/100, Loss: 2.531123384833336
Epoch 82/100, Loss: 2.29232881963253
Epoch 83/100, Loss: 2.467919535934925
Epoch 84/100, Loss: 2.4594354331493378
Epoch 85/100, Loss: 2.410741798579693
Epoch 86/100, Loss: 2.4622755721211433

Epoch 87/100, Loss: 2.504580296576023
Epoch 88/100, Loss: 2.2653573900461197
Epoch 89/100, Loss: 2.458619639277458
Epoch 90/100, Loss: 2.4908153861761093
Epoch 91/100, Loss: 2.2470276430249214
Epoch 92/100, Loss: 2.3381380885839462
Epoch 93/100, Loss: 2.3782298862934113
Epoch 94/100, Loss: 2.359472408890724
Epoch 95/100, Loss: 2.495703622698784
Epoch 96/100, Loss: 2.301005780696869
Epoch 97/100, Loss: 2.5595443844795227
Epoch 98/100, Loss: 2.390671744942665
Epoch 99/100, Loss: 2.4171496108174324
Epoch 100/100, Loss: 2.3948643654584885
Fold 4/5 done
Epoch 1/100, Loss: 1.789710707962513
Epoch 2/100, Loss: 1.857341155409813

Epoch 3/100, Loss: 1.6829613372683525
Epoch 4/100, Loss: 1.759406678378582
Epoch 5/100, Loss: 1.8023733869194984
Epoch 6/100, Loss: 1.7388904504477978
Epoch 7/100, Loss: 1.740037176758051
Epoch 8/100, Loss: 1.7119864448904991
Epoch 9/100, Loss: 1.7467803359031677
Epoch 10/100, Loss: 1.7832026258111
Epoch 11/100, Loss: 1.739525392651558
Epoch 12/100, Loss: 1.874273706227541
Epoch 13/100, Loss: 1.8415158987045288
Epoch 14/100, Loss: 1.6937733069062233
Epoch 15/100, Loss: 1.949782107025385
Epoch 16/100, Loss: 1.682899110019207
Epoch 17/100, Loss: 1.8487346470355988
Epoch 18/100, Loss: 1.812009982764721

Epoch 19/100, Loss: 1.8468545079231262
Epoch 20/100, Loss: 1.825742781162262
Epoch 21/100, Loss: 1.8475959450006485
Epoch 22/100, Loss: 1.8572969734668732
Epoch 23/100, Loss: 1.868689101189375
Epoch 24/100, Loss: 1.7259899154305458
Epoch 25/100, Loss: 1.6644654870033264
Epoch 26/100, Loss: 1.7783468961715698
Epoch 27/100, Loss: 1.713342271745205
Epoch 28/100, Loss: 1.5641064792871475
Epoch 29/100, Loss: 1.830206073820591
Epoch 30/100, Loss: 1.7279253117740154
Epoch 31/100, Loss: 1.8490411639213562
Epoch 32/100, Loss: 1.734615758061409
Epoch 33/100, Loss: 1.8052632883191109
Epoch 34/100, Loss: 1.8507509529590607

Epoch 35/100, Loss: 1.756764505058527
Epoch 36/100, Loss: 2.3500542119145393
Epoch 37/100, Loss: 1.631834976375103
Epoch 38/100, Loss: 1.7707170471549034
Epoch 39/100, Loss: 1.74472576379776
Epoch 40/100, Loss: 1.6696427091956139
Epoch 41/100, Loss: 1.9398043230175972
Epoch 42/100, Loss: 1.907216690480709
Epoch 43/100, Loss: 1.8962179943919182
Epoch 44/100, Loss: 1.830005906522274
Epoch 45/100, Loss: 1.8679482638835907
Epoch 46/100, Loss: 1.740936018526554
Epoch 47/100, Loss: 1.9514999836683273
Epoch 48/100, Loss: 1.9345941059291363
Epoch 49/100, Loss: 1.7973622046411037
Epoch 50/100, Loss: 1.7811032868921757

Epoch 51/100, Loss: 1.8020205050706863
Epoch 52/100, Loss: 1.873071439564228
Epoch 53/100, Loss: 1.8789538331329823
Epoch 54/100, Loss: 1.7857509665191174
Epoch 55/100, Loss: 1.8519399426877499
Epoch 56/100, Loss: 1.9762152209877968
Epoch 57/100, Loss: 1.712748870253563
Epoch 58/100, Loss: 1.6706449761986732
Epoch 59/100, Loss: 2.0426502376794815
Epoch 60/100, Loss: 1.8082281947135925
Epoch 61/100, Loss: 1.7852383330464363
Epoch 62/100, Loss: 2.0032310634851456
Epoch 63/100, Loss: 1.969694696366787
Epoch 64/100, Loss: 1.9165821932256222

Epoch 65/100, Loss: 2.2047003395855427
Epoch 66/100, Loss: 1.6952616944909096
Epoch 67/100, Loss: 1.895364210009575
Epoch 68/100, Loss: 1.8994276449084282
Epoch 69/100, Loss: 1.7172924615442753
Epoch 70/100, Loss: 1.8522237576544285
Epoch 71/100, Loss: 1.8849355019629002
Epoch 72/100, Loss: 1.8061016872525215
Epoch 73/100, Loss: 1.871707834303379
Epoch 74/100, Loss: 1.7465487942099571
Epoch 75/100, Loss: 1.7860144227743149
Epoch 76/100, Loss: 1.8710075728595257
Epoch 77/100, Loss: 1.685319434851408
Epoch 78/100, Loss: 1.8454430513083935
Epoch 79/100, Loss: 1.8044353760778904
Epoch 80/100, Loss: 1.8174819126725197

Epoch 81/100, Loss: 1.8851303532719612
Epoch 82/100, Loss: 1.889739267528057
Epoch 83/100, Loss: 1.7390306517481804
Epoch 84/100, Loss: 1.674478717148304
Epoch 85/100, Loss: 1.7857228256762028
Epoch 86/100, Loss: 1.820204734802246
Epoch 87/100, Loss: 1.7014538645744324
Epoch 88/100, Loss: 1.8901257254183292
Epoch 89/100, Loss: 1.7947192192077637
Epoch 90/100, Loss: 1.872559692710638
Epoch 91/100, Loss: 1.8186496272683144
Epoch 92/100, Loss: 1.745573129504919
Epoch 93/100, Loss: 1.7490531131625175
Epoch 94/100, Loss: 1.8072412684559822
Epoch 95/100, Loss: 1.8174058124423027
Epoch 96/100, Loss: 1.7361905314028263
Epoch 97/100, Loss: 1.9045740216970444

Epoch 98/100, Loss: 1.8595040291547775
Epoch 99/100, Loss: 1.8009655810892582
Epoch 100/100, Loss: 2.002383593469858
Fold 5/5 done

In [11]:
ap = average_precision_score(y_true, anomaly_scores)
print(f"Deep SVDD AP (5-fold CV) = {ap:.4f}")
sb.glue("GBG500_ap_spectral_deep_svdd", float(ap))

Deep SVDD AP (5-fold CV) = 0.6075