In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import average_precision_score
from sklearn.model_selection import StratifiedKFold
from pyod.models.deep_svdd import DeepSVDD
import sys
import scrapbook as sb

sys.path.append('..')
from utils import reshape_to_numpy, interpolate_missing_values, denoise_data, compute_spectrograms, time_avg_pooling

In [2]:
seed = 1
sampling_rate = 10
nperseg=64
noverlap=32
accel_cutoff = 0.4
accel_order = 30
gyro_cutoff = 0.6
gyro_order = 20
batch_size = 32
epochs = 100
hidden_neurons = [128, 64, 32]
n_splits = 5

In [3]:
# Parameters
seed = 1

In [4]:
rng = np.random.RandomState(seed)

In [5]:
data = pd.read_parquet("../data/GBG500.parquet")
data

,ride_id,time_index,ax,ay,az,rx,ry,rz
0,005043f1a7520cebf1e17fd166a00a3190e2433530f236...,0,-2.512796,-9.385012,-1.053078,-0.009155,0.009155,-0.201416
1,005043f1a7520cebf1e17fd166a00a3190e2433530f236...,100,-2.491268,-9.385012,-1.079390,-0.036621,0.027465,-0.155639
2,005043f1a7520cebf1e17fd166a00a3190e2433530f236...,200,-2.534324,-9.382022,-1.030952,0.036621,0.027465,-0.073242
3,005043f1a7520cebf1e17fd166a00a3190e2433530f236...,300,-2.488278,-9.383218,-1.091948,-0.045776,0.036621,-0.183105
4,005043f1a7520cebf1e17fd166a00a3190e2433530f236...,400,-2.483494,-9.382022,-1.100320,-0.045776,0.027465,-0.192260
...,...,...,...,...,...,...,...,...
1529542,ffb6f2f5dc6ba768d88dc0bc1af4cad235526aa9e24168...,241300,0.459862,-9.140430,-3.318900,1.556396,-0.091552,0.274658
1529543,ffb6f2f5dc6ba768d88dc0bc1af4cad235526aa9e24168...,241400,0.455676,-9.140430,-3.321292,1.583861,-0.119018,0.274658
1529544,ffb6f2f5dc6ba768d88dc0bc1af4cad235526aa9e24168...,241500,0.459862,-9.139832,-3.317704,1.583861,-0.109863,0.274658
1529545,ffb6f2f5dc6ba768d88dc0bc1af4cad235526aa9e24168...,241600,0.456274,-9.142224,-3.321292,1.574707,-0.137329,0.283813
1529546,ffb6f2f5dc6ba768d88dc0bc1af4cad235526aa9e24168...,241700,0.458666,-9.139832,-3.320694,1.574707,-0.137329,0.274658

In [6]:
labels = pd.read_csv("../data/GBG500_labels.csv")
labels.columns = labels.columns.str.lower()
ride_order_df = pd.DataFrame({"ride_id": data["ride_id"].unique()})
labels_sorted = ride_order_df.merge(
    labels,
    on="ride_id",
    how="left"
)
labels_sorted

                                               ride_id        label
0    005043f1a7520cebf1e17fd166a00a3190e2433530f236...         Safe
1    00d223cb7aecc9c0cc5871e32a6c45027a068eba07c572...     Reckless
2    02288a4aeca044203394e982e76b87818021dea2b34df9...         Safe
3    0236bdcf13d473ea24d97f5eaeea459f257dffac005694...  Bad weather
4    0238e5dd85143f1b6c59b200bc32f14361b8fc84c51a87...         Safe
..                                                 ...          ...
495  fe5d7f84d692bbccad8bd566a3ad5c3108fa9f90acd671...         Safe
496  fe67169632306d4668b2affedef510df2cb43e2fb41220...         Safe
497  fee44667fdc8ab4995c702fc3bd36178de0b1ca2c64687...         Safe
498  ff79b2e945b93c2a5efc3a06365267b3a160e7849ba57d...         Safe
499  ffb6f2f5dc6ba768d88dc0bc1af4cad235526aa9e24168...         Safe

[500 rows x 2 columns]

In [7]:
data_np = reshape_to_numpy(
    data,
    features = ["ax", "ay", "az", "rx", "ry", "rz"],
    max_timestamps = 4800
)

data_np_clean = interpolate_missing_values(
    data_np,
    method='linear',
    limit=None
)

data_np_clean = denoise_data(
    data=data_np_clean,
    accel_indices=[0, 1, 2],
    gyro_indices=[3, 4, 5],
    accel_cutoff=accel_cutoff,
    accel_order=accel_order,
    gyro_cutoff=gyro_cutoff,
    gyro_order=gyro_order,
)

In [8]:
# Compute spectrograms for all rides
spectrograms_array = compute_spectrograms(data_np_clean, sampling_rate, nperseg, noverlap)
spectrograms_array.shape

(500, 149, 6, 33)

In [9]:
# Aggregate spectrograms using time-averaged pooling
X_feat = time_avg_pooling(spectrograms_array)
X_feat.shape

(500, 198)

In [10]:
# 5-fold stratified CV with Deep SVDD
skf = StratifiedKFold(n_splits=n_splits, shuffle=True, random_state=rng.randint(1000))
y_true = (labels_sorted['label'] == 'Reckless').astype(int).values
anomaly_scores = np.full(len(y_true), np.nan)

for fold, (train_idx, test_idx) in enumerate(skf.split(X_feat, y_true)):
    sc = StandardScaler()
    X_train = sc.fit_transform(X_feat[train_idx])
    X_test = sc.transform(X_feat[test_idx])

    np.random.seed(rng.randint(1000))
    model = DeepSVDD(
        n_features=X_train.shape[1],
        hidden_neurons=hidden_neurons,
        epochs=epochs,
        batch_size=batch_size,
        random_state=rng.randint(1000),
    )
    model.fit(X_train)
    anomaly_scores[test_idx] = model.decision_function(X_test)
    print(f"Fold {fold+1}/{n_splits} done")

Epoch 1/100, Loss: 2.5978553742170334
Epoch 2/100, Loss: 2.5701739862561226
Epoch 3/100, Loss: 2.5223330929875374
Epoch 4/100, Loss: 2.6874880641698837
Epoch 5/100, Loss: 2.5918658524751663
Epoch 6/100, Loss: 2.764392450451851
Epoch 7/100, Loss: 2.554467089474201
Epoch 8/100, Loss: 2.56683087348938
Epoch 9/100, Loss: 2.661341220140457
Epoch 10/100, Loss: 2.6067812219262123
Epoch 11/100, Loss: 2.5758905336260796
Epoch 12/100, Loss: 2.5233954787254333
Epoch 13/100, Loss: 2.6408369094133377
Epoch 14/100, Loss: 2.5808050110936165
Epoch 15/100, Loss: 2.650073178112507
Epoch 16/100, Loss: 2.593384772539139
Epoch 17/100, Loss: 2.532645121216774

Epoch 18/100, Loss: 2.6037988290190697
Epoch 19/100, Loss: 2.516862116754055
Epoch 20/100, Loss: 2.671688497066498
Epoch 21/100, Loss: 2.597827598452568
Epoch 22/100, Loss: 2.6977747455239296
Epoch 23/100, Loss: 2.4480183348059654
Epoch 24/100, Loss: 2.557854577898979
Epoch 25/100, Loss: 2.4833518341183662
Epoch 26/100, Loss: 2.572628654539585
Epoch 27/100, Loss: 2.5557193905115128
Epoch 28/100, Loss: 2.7147995308041573
Epoch 29/100, Loss: 2.58649979531765
Epoch 30/100, Loss: 2.6399931982159615
Epoch 31/100, Loss: 2.7250454276800156

Epoch 32/100, Loss: 2.603483185172081
Epoch 33/100, Loss: 2.585220128297806
Epoch 34/100, Loss: 2.67693629860878
Epoch 35/100, Loss: 2.603554427623749
Epoch 36/100, Loss: 2.661882109940052
Epoch 37/100, Loss: 2.6167358309030533
Epoch 38/100, Loss: 2.502002216875553
Epoch 39/100, Loss: 2.787282131612301
Epoch 40/100, Loss: 2.65914586186409
Epoch 41/100, Loss: 2.528372645378113
Epoch 42/100, Loss: 2.582917094230652
Epoch 43/100, Loss: 2.5529686510562897

Epoch 44/100, Loss: 2.545245297253132
Epoch 45/100, Loss: 2.6335377246141434
Epoch 46/100, Loss: 2.488495096564293
Epoch 47/100, Loss: 2.5992800295352936
Epoch 48/100, Loss: 2.5166738107800484
Epoch 49/100, Loss: 2.6619278863072395
Epoch 50/100, Loss: 2.6787101477384567
Epoch 51/100, Loss: 2.393850952386856
Epoch 52/100, Loss: 2.5380784571170807
Epoch 53/100, Loss: 2.6131972447037697
Epoch 54/100, Loss: 2.5839807763695717
Epoch 55/100, Loss: 2.587231360375881
Epoch 56/100, Loss: 2.580062784254551
Epoch 57/100, Loss: 2.648818925023079

Epoch 58/100, Loss: 2.576160356402397
Epoch 59/100, Loss: 2.575393468141556
Epoch 60/100, Loss: 2.7617015466094017
Epoch 61/100, Loss: 2.6056589633226395
Epoch 62/100, Loss: 2.540405161678791
Epoch 63/100, Loss: 2.7455796524882317
Epoch 64/100, Loss: 2.6250236704945564
Epoch 65/100, Loss: 2.566180557012558
Epoch 66/100, Loss: 2.6509545370936394
Epoch 67/100, Loss: 2.6148820519447327
Epoch 68/100, Loss: 2.5552605390548706
Epoch 69/100, Loss: 2.5970800295472145
Epoch 70/100, Loss: 2.667554423213005
Epoch 71/100, Loss: 2.5260137170553207
Epoch 72/100, Loss: 2.589924566447735
Epoch 73/100, Loss: 2.4482452273368835

Epoch 74/100, Loss: 2.4968142583966255
Epoch 75/100, Loss: 2.629865400493145
Epoch 76/100, Loss: 2.6963174790143967
Epoch 77/100, Loss: 2.5399925857782364
Epoch 78/100, Loss: 2.6904050037264824
Epoch 79/100, Loss: 2.6535286903381348
Epoch 80/100, Loss: 2.629297785460949
Epoch 81/100, Loss: 2.5757235512137413
Epoch 82/100, Loss: 2.560074619948864
Epoch 83/100, Loss: 2.574689954519272
Epoch 84/100, Loss: 2.639969475567341
Epoch 85/100, Loss: 2.5580833703279495
Epoch 86/100, Loss: 2.7218015119433403
Epoch 87/100, Loss: 2.6819533109664917
Epoch 88/100, Loss: 2.546296738088131
Epoch 89/100, Loss: 2.5540008544921875
Epoch 90/100, Loss: 2.6150566786527634
Epoch 91/100, Loss: 2.5828978195786476

Epoch 92/100, Loss: 2.5714825093746185
Epoch 93/100, Loss: 2.6368718296289444
Epoch 94/100, Loss: 2.472440578043461
Epoch 95/100, Loss: 2.6048368513584137
Epoch 96/100, Loss: 2.5580613538622856
Epoch 97/100, Loss: 2.5470683947205544
Epoch 98/100, Loss: 2.7396915927529335
Epoch 99/100, Loss: 2.5074659287929535
Epoch 100/100, Loss: 2.5614146068692207
Fold 1/5 done
Epoch 1/100, Loss: 1.4624992981553078
Epoch 2/100, Loss: 1.4801969602704048
Epoch 3/100, Loss: 1.5814167261123657
Epoch 4/100, Loss: 1.4465317875146866
Epoch 5/100, Loss: 1.6526739671826363
Epoch 6/100, Loss: 1.4616858959197998

Epoch 7/100, Loss: 1.6206527650356293
Epoch 8/100, Loss: 1.63951625674963
Epoch 9/100, Loss: 1.4427499920129776
Epoch 10/100, Loss: 1.4907797873020172
Epoch 11/100, Loss: 1.6347898617386818
Epoch 12/100, Loss: 1.5733645483851433
Epoch 13/100, Loss: 1.4729581400752068
Epoch 14/100, Loss: 1.5596255734562874
Epoch 15/100, Loss: 1.5744849890470505
Epoch 16/100, Loss: 1.6191456019878387
Epoch 17/100, Loss: 1.544838197529316
Epoch 18/100, Loss: 1.5197991393506527
Epoch 19/100, Loss: 1.4927184730768204
Epoch 20/100, Loss: 1.506745308637619
Epoch 21/100, Loss: 1.565416693687439
Epoch 22/100, Loss: 1.535933457314968

Epoch 23/100, Loss: 1.5432394593954086
Epoch 24/100, Loss: 1.579442024230957
Epoch 25/100, Loss: 1.6127749755978584
Epoch 26/100, Loss: 1.576695129275322
Epoch 27/100, Loss: 1.4121651202440262
Epoch 28/100, Loss: 1.6971950829029083
Epoch 29/100, Loss: 1.4973359480500221
Epoch 30/100, Loss: 1.5598099157214165
Epoch 31/100, Loss: 1.5847774147987366
Epoch 32/100, Loss: 1.6967206746339798
Epoch 33/100, Loss: 1.4975010380148888
Epoch 34/100, Loss: 1.5432669520378113
Epoch 35/100, Loss: 1.6013949066400528
Epoch 36/100, Loss: 1.658660851418972
Epoch 37/100, Loss: 1.5061666741967201
Epoch 38/100, Loss: 1.6509162336587906

Epoch 39/100, Loss: 1.506488285958767
Epoch 40/100, Loss: 1.5761682018637657
Epoch 41/100, Loss: 1.5988134741783142
Epoch 42/100, Loss: 1.545982226729393
Epoch 43/100, Loss: 1.427454598248005
Epoch 44/100, Loss: 1.5412695035338402
Epoch 45/100, Loss: 1.6296263597905636
Epoch 46/100, Loss: 1.5477513819932938
Epoch 47/100, Loss: 1.4967205226421356
Epoch 48/100, Loss: 1.4851150885224342
Epoch 49/100, Loss: 1.6569720357656479
Epoch 50/100, Loss: 1.607361488044262
Epoch 51/100, Loss: 1.4706277772784233
Epoch 52/100, Loss: 1.9074974581599236
Epoch 53/100, Loss: 1.6101343557238579
Epoch 54/100, Loss: 1.5570254065096378

Epoch 55/100, Loss: 1.6856739297509193
Epoch 56/100, Loss: 1.5298821218311787
Epoch 57/100, Loss: 1.553172368556261
Epoch 58/100, Loss: 1.5427576079964638
Epoch 59/100, Loss: 1.5639040991663933
Epoch 60/100, Loss: 1.577342540025711
Epoch 61/100, Loss: 1.5893305614590645
Epoch 62/100, Loss: 1.4461609795689583
Epoch 63/100, Loss: 1.5157084837555885
Epoch 64/100, Loss: 1.5665193796157837
Epoch 65/100, Loss: 1.5347309112548828
Epoch 66/100, Loss: 1.4930806383490562
Epoch 67/100, Loss: 1.4871707260608673
Epoch 68/100, Loss: 1.5427210852503777
Epoch 69/100, Loss: 1.5926460921764374
Epoch 70/100, Loss: 1.6353387162089348
Epoch 71/100, Loss: 1.6098798662424088
Epoch 72/100, Loss: 1.4929910451173782

Epoch 73/100, Loss: 1.5977799817919731
Epoch 74/100, Loss: 1.6552179604768753
Epoch 75/100, Loss: 1.4165347516536713
Epoch 76/100, Loss: 1.5616895407438278
Epoch 77/100, Loss: 1.5350681841373444
Epoch 78/100, Loss: 1.4433187693357468
Epoch 79/100, Loss: 1.6353148519992828
Epoch 80/100, Loss: 1.5602016001939774
Epoch 81/100, Loss: 1.597933892160654
Epoch 82/100, Loss: 1.4706759303808212
Epoch 83/100, Loss: 1.5234882310032845
Epoch 84/100, Loss: 1.4760348796844482
Epoch 85/100, Loss: 1.6079633459448814
Epoch 86/100, Loss: 1.4916860833764076
Epoch 87/100, Loss: 1.6093372479081154
Epoch 88/100, Loss: 1.5780612900853157

Epoch 89/100, Loss: 1.5972279980778694
Epoch 90/100, Loss: 1.625839687883854
Epoch 91/100, Loss: 1.5571863055229187
Epoch 92/100, Loss: 1.5522325336933136
Epoch 93/100, Loss: 1.4211017414927483
Epoch 94/100, Loss: 1.5093951113522053
Epoch 95/100, Loss: 1.596796803176403
Epoch 96/100, Loss: 1.5191651359200478
Epoch 97/100, Loss: 1.4568866267800331
Epoch 98/100, Loss: 1.4517583847045898
Epoch 99/100, Loss: 1.5669415220618248
Epoch 100/100, Loss: 1.5323161035776138
Fold 2/5 done
Epoch 1/100, Loss: 1.9019524231553078
Epoch 2/100, Loss: 1.8983913958072662
Epoch 3/100, Loss: 1.9741250649094582
Epoch 4/100, Loss: 2.205509565770626
Epoch 5/100, Loss: 2.0817954912781715

Epoch 6/100, Loss: 2.030613087117672
Epoch 7/100, Loss: 2.1281641125679016
Epoch 8/100, Loss: 2.1825427189469337
Epoch 9/100, Loss: 1.991750456392765
Epoch 10/100, Loss: 2.108050934970379
Epoch 11/100, Loss: 2.008499827235937
Epoch 12/100, Loss: 2.069675400853157
Epoch 13/100, Loss: 1.9131288900971413
Epoch 14/100, Loss: 2.1055121570825577
Epoch 15/100, Loss: 1.9443519860506058
Epoch 16/100, Loss: 2.1378058567643166
Epoch 17/100, Loss: 1.9723934680223465
Epoch 18/100, Loss: 2.0936832651495934
Epoch 19/100, Loss: 2.1451500430703163
Epoch 20/100, Loss: 1.97187789529562
Epoch 21/100, Loss: 2.0597093999385834
Epoch 22/100, Loss: 2.073294974863529

Epoch 23/100, Loss: 2.0223618671298027
Epoch 24/100, Loss: 2.0032006800174713
Epoch 25/100, Loss: 2.0575252696871758
Epoch 26/100, Loss: 1.9839672669768333
Epoch 27/100, Loss: 2.073881007730961
Epoch 28/100, Loss: 1.8741696178913116
Epoch 29/100, Loss: 2.228911094367504
Epoch 30/100, Loss: 2.3366069346666336
Epoch 31/100, Loss: 1.9453972727060318
Epoch 32/100, Loss: 2.039074629545212
Epoch 33/100, Loss: 2.0718781650066376
Epoch 34/100, Loss: 1.9414159953594208
Epoch 35/100, Loss: 1.8207171708345413
Epoch 36/100, Loss: 2.0417483784258366
Epoch 37/100, Loss: 2.023121200501919
Epoch 38/100, Loss: 1.9170721843838692
Epoch 39/100, Loss: 2.1385095715522766

Epoch 40/100, Loss: 1.7700700089335442
Epoch 41/100, Loss: 1.8610715121030807
Epoch 42/100, Loss: 2.0817340090870857
Epoch 43/100, Loss: 2.1004668921232224
Epoch 44/100, Loss: 2.0115912407636642
Epoch 45/100, Loss: 2.102541394531727
Epoch 46/100, Loss: 2.1485500931739807
Epoch 47/100, Loss: 1.892282821238041
Epoch 48/100, Loss: 1.9344146847724915
Epoch 49/100, Loss: 1.8985256850719452
Epoch 50/100, Loss: 2.0775168165564537
Epoch 51/100, Loss: 2.037537395954132
Epoch 52/100, Loss: 2.2473463639616966
Epoch 53/100, Loss: 2.0225748494267464
Epoch 54/100, Loss: 1.9715325236320496

Epoch 55/100, Loss: 2.1009876281023026
Epoch 56/100, Loss: 2.1034100130200386
Epoch 57/100, Loss: 1.8873652890324593
Epoch 58/100, Loss: 1.993600606918335
Epoch 59/100, Loss: 2.083233341574669
Epoch 60/100, Loss: 2.263840153813362
Epoch 61/100, Loss: 2.0105383470654488
Epoch 62/100, Loss: 2.124165691435337
Epoch 63/100, Loss: 2.1285716965794563
Epoch 64/100, Loss: 2.1137551963329315
Epoch 65/100, Loss: 1.8821553513407707
Epoch 66/100, Loss: 1.7287825047969818

Epoch 67/100, Loss: 2.094528179615736
Epoch 68/100, Loss: 1.9491330087184906
Epoch 69/100, Loss: 2.0156857296824455
Epoch 70/100, Loss: 2.0651313737034798
Epoch 71/100, Loss: 1.9450335949659348
Epoch 72/100, Loss: 1.9667584598064423
Epoch 73/100, Loss: 2.089255563914776
Epoch 74/100, Loss: 2.3118710592389107
Epoch 75/100, Loss: 2.236722268164158
Epoch 76/100, Loss: 2.0577279403805733
Epoch 77/100, Loss: 2.02677258849144
Epoch 78/100, Loss: 2.250095874071121
Epoch 79/100, Loss: 2.2365372106432915

Epoch 80/100, Loss: 1.9377999007701874
Epoch 81/100, Loss: 1.8543561697006226
Epoch 82/100, Loss: 2.080629847943783
Epoch 83/100, Loss: 1.9332427009940147
Epoch 84/100, Loss: 2.0098010823130608
Epoch 85/100, Loss: 1.9644832089543343
Epoch 86/100, Loss: 2.038289152085781
Epoch 87/100, Loss: 2.1240090429782867
Epoch 88/100, Loss: 2.1107805743813515
Epoch 89/100, Loss: 2.0507822781801224
Epoch 90/100, Loss: 2.292903058230877
Epoch 91/100, Loss: 2.174198091030121
Epoch 92/100, Loss: 1.9383791834115982
Epoch 93/100, Loss: 1.9140594080090523
Epoch 94/100, Loss: 1.9676968455314636

Epoch 95/100, Loss: 2.1601352840662003
Epoch 96/100, Loss: 2.0226931422948837
Epoch 97/100, Loss: 2.090690664947033
Epoch 98/100, Loss: 2.1436912193894386
Epoch 99/100, Loss: 1.9252566918730736
Epoch 100/100, Loss: 2.0999893620610237
Fold 3/5 done
Epoch 1/100, Loss: 3.1340611204504967
Epoch 2/100, Loss: 3.0034139826893806
Epoch 3/100, Loss: 2.8572817146778107
Epoch 4/100, Loss: 3.153192602097988
Epoch 5/100, Loss: 2.9757256880402565

Epoch 6/100, Loss: 3.146200329065323
Epoch 7/100, Loss: 2.967823326587677
Epoch 8/100, Loss: 3.1588052809238434
Epoch 9/100, Loss: 3.088418796658516
Epoch 10/100, Loss: 3.1481175497174263
Epoch 11/100, Loss: 2.9074964448809624
Epoch 12/100, Loss: 3.0239572152495384
Epoch 13/100, Loss: 2.94216188788414
Epoch 14/100, Loss: 3.1983951404690742
Epoch 15/100, Loss: 3.1150295734405518
Epoch 16/100, Loss: 3.00584913790226
Epoch 17/100, Loss: 3.18306140601635
Epoch 18/100, Loss: 2.97444324195385
Epoch 19/100, Loss: 3.2337356507778168

Epoch 20/100, Loss: 2.9567383006215096
Epoch 21/100, Loss: 3.004002019762993
Epoch 22/100, Loss: 3.232652947306633
Epoch 23/100, Loss: 3.189763233065605
Epoch 24/100, Loss: 2.9284476339817047
Epoch 25/100, Loss: 2.994279943406582
Epoch 26/100, Loss: 3.0536531656980515
Epoch 27/100, Loss: 2.970105394721031
Epoch 28/100, Loss: 3.0498768985271454
Epoch 29/100, Loss: 2.9888071939349174
Epoch 30/100, Loss: 3.1266349107027054
Epoch 31/100, Loss: 3.691263273358345
Epoch 32/100, Loss: 3.0579358637332916
Epoch 33/100, Loss: 3.0495391115546227
Epoch 34/100, Loss: 3.0147124528884888
Epoch 35/100, Loss: 3.1177610903978348
Epoch 36/100, Loss: 3.15361388027668
Epoch 37/100, Loss: 3.0651642084121704

Epoch 38/100, Loss: 2.943555101752281
Epoch 39/100, Loss: 2.8145128414034843
Epoch 40/100, Loss: 3.067485064268112
Epoch 41/100, Loss: 3.080367937684059
Epoch 42/100, Loss: 3.1476268619298935
Epoch 43/100, Loss: 3.1034972220659256
Epoch 44/100, Loss: 3.0732166916131973
Epoch 45/100, Loss: 2.989732339978218
Epoch 46/100, Loss: 3.006117433309555
Epoch 47/100, Loss: 3.0923843383789062
Epoch 48/100, Loss: 3.0357011929154396
Epoch 49/100, Loss: 3.1110347509384155
Epoch 50/100, Loss: 2.952095240354538
Epoch 51/100, Loss: 3.067668169736862
Epoch 52/100, Loss: 3.015475921332836
Epoch 53/100, Loss: 2.961770810186863
Epoch 54/100, Loss: 2.9813917726278305
Epoch 55/100, Loss: 2.962531127035618

Epoch 56/100, Loss: 3.1151964738965034
Epoch 57/100, Loss: 3.056340903043747
Epoch 58/100, Loss: 2.985559180378914
Epoch 59/100, Loss: 2.9755057990550995
Epoch 60/100, Loss: 3.191900372505188
Epoch 61/100, Loss: 2.9559655860066414
Epoch 62/100, Loss: 3.1750677973031998
Epoch 63/100, Loss: 3.1015940234065056
Epoch 64/100, Loss: 2.966889478266239
Epoch 65/100, Loss: 3.1429265066981316
Epoch 66/100, Loss: 3.214815989136696
Epoch 67/100, Loss: 3.089777171611786
Epoch 68/100, Loss: 3.0415768772363663
Epoch 69/100, Loss: 2.9629071801900864

Epoch 70/100, Loss: 3.1025411784648895
Epoch 71/100, Loss: 2.994657278060913
Epoch 72/100, Loss: 3.0498387664556503
Epoch 73/100, Loss: 2.859577476978302
Epoch 74/100, Loss: 2.990735203027725
Epoch 75/100, Loss: 2.944477364420891
Epoch 76/100, Loss: 3.06840880215168
Epoch 77/100, Loss: 3.46794331073761
Epoch 78/100, Loss: 2.941116914153099
Epoch 79/100, Loss: 3.149797201156616
Epoch 80/100, Loss: 2.9926366358995438
Epoch 81/100, Loss: 3.1609174609184265
Epoch 82/100, Loss: 3.041589319705963
Epoch 83/100, Loss: 3.112572282552719
Epoch 84/100, Loss: 3.02283925563097

Epoch 85/100, Loss: 3.099511206150055
Epoch 86/100, Loss: 3.06224861741066
Epoch 87/100, Loss: 2.8663038462400436
Epoch 88/100, Loss: 3.0909276753664017
Epoch 89/100, Loss: 2.8615175932645798
Epoch 90/100, Loss: 3.0355965048074722
Epoch 91/100, Loss: 3.243382342159748
Epoch 92/100, Loss: 3.2526929453015327
Epoch 93/100, Loss: 3.0942503064870834
Epoch 94/100, Loss: 3.1336060389876366
Epoch 95/100, Loss: 2.907604344189167
Epoch 96/100, Loss: 3.000942647457123
Epoch 97/100, Loss: 3.0603446662425995
Epoch 98/100, Loss: 3.0415075719356537

Epoch 99/100, Loss: 2.9137823060154915
Epoch 100/100, Loss: 3.1074067428708076
Fold 4/5 done
Epoch 1/100, Loss: 1.709770880639553
Epoch 2/100, Loss: 1.7043244317173958
Epoch 3/100, Loss: 1.7171140760183334
Epoch 4/100, Loss: 1.7352739199995995
Epoch 5/100, Loss: 1.6495706662535667
Epoch 6/100, Loss: 1.8524816036224365
Epoch 7/100, Loss: 1.5981109738349915
Epoch 8/100, Loss: 1.7299650236964226
Epoch 9/100, Loss: 1.9199366122484207
Epoch 10/100, Loss: 1.5722087286412716
Epoch 11/100, Loss: 1.8434892371296883

Epoch 12/100, Loss: 1.889136642217636
Epoch 13/100, Loss: 1.7496926486492157
Epoch 14/100, Loss: 1.7603242918848991
Epoch 15/100, Loss: 1.8283860608935356
Epoch 16/100, Loss: 1.8497755825519562
Epoch 17/100, Loss: 1.8325670510530472
Epoch 18/100, Loss: 1.7561369389295578
Epoch 19/100, Loss: 1.6817635893821716
Epoch 20/100, Loss: 1.8226016983389854
Epoch 21/100, Loss: 1.757915884256363
Epoch 22/100, Loss: 1.81444101780653
Epoch 23/100, Loss: 1.7643269449472427
Epoch 24/100, Loss: 1.694946363568306

Epoch 25/100, Loss: 1.8813604786992073
Epoch 26/100, Loss: 1.749869666993618
Epoch 27/100, Loss: 1.821544572710991
Epoch 28/100, Loss: 1.8371695578098297
Epoch 29/100, Loss: 1.8111427649855614
Epoch 30/100, Loss: 1.8033717945218086
Epoch 31/100, Loss: 1.7741137221455574
Epoch 32/100, Loss: 1.6618517264723778
Epoch 33/100, Loss: 1.7539436668157578
Epoch 34/100, Loss: 1.745054453611374
Epoch 35/100, Loss: 1.7059742510318756
Epoch 36/100, Loss: 1.7488672137260437
Epoch 37/100, Loss: 1.850600853562355

Epoch 38/100, Loss: 1.807386189699173
Epoch 39/100, Loss: 1.7638419643044472
Epoch 40/100, Loss: 1.7357196062803268
Epoch 41/100, Loss: 1.7889071255922318
Epoch 42/100, Loss: 1.7892185747623444
Epoch 43/100, Loss: 1.7955934554338455
Epoch 44/100, Loss: 1.859212450683117
Epoch 45/100, Loss: 1.7827570736408234
Epoch 46/100, Loss: 1.7524181082844734
Epoch 47/100, Loss: 1.7726173251867294
Epoch 48/100, Loss: 1.8707883059978485
Epoch 49/100, Loss: 1.83320152759552
Epoch 50/100, Loss: 1.746676567941904
Epoch 51/100, Loss: 1.7732801586389542
Epoch 52/100, Loss: 1.7340330258011818
Epoch 53/100, Loss: 1.5665863752365112
Epoch 54/100, Loss: 1.7478958405554295

Epoch 55/100, Loss: 1.7186877354979515
Epoch 56/100, Loss: 1.888500228524208
Epoch 57/100, Loss: 1.7843251153826714
Epoch 58/100, Loss: 2.0168623626232147
Epoch 59/100, Loss: 1.968844436109066
Epoch 60/100, Loss: 1.6896231696009636
Epoch 61/100, Loss: 1.7176074832677841
Epoch 62/100, Loss: 1.7713027074933052
Epoch 63/100, Loss: 1.8133211210370064
Epoch 64/100, Loss: 1.866812601685524
Epoch 65/100, Loss: 1.7656779289245605
Epoch 66/100, Loss: 1.7854989543557167
Epoch 67/100, Loss: 1.846178650856018
Epoch 68/100, Loss: 1.8227030858397484

Epoch 69/100, Loss: 1.8822631686925888
Epoch 70/100, Loss: 2.0660286471247673
Epoch 71/100, Loss: 1.874046877026558
Epoch 72/100, Loss: 1.8572660088539124
Epoch 73/100, Loss: 1.8613182082772255
Epoch 74/100, Loss: 1.7234709784388542
Epoch 75/100, Loss: 1.8159572929143906
Epoch 76/100, Loss: 1.8357220143079758
Epoch 77/100, Loss: 1.6524041816592216
Epoch 78/100, Loss: 1.6691348850727081
Epoch 79/100, Loss: 1.784796066582203
Epoch 80/100, Loss: 1.8777738884091377
Epoch 81/100, Loss: 1.8177912160754204
Epoch 82/100, Loss: 1.6400406211614609
Epoch 83/100, Loss: 1.6829278022050858
Epoch 84/100, Loss: 1.8645168393850327

Epoch 85/100, Loss: 1.8190896734595299
Epoch 86/100, Loss: 1.7971790879964828
Epoch 87/100, Loss: 1.8402887061238289
Epoch 88/100, Loss: 1.8027028366923332
Epoch 89/100, Loss: 1.8608281761407852
Epoch 90/100, Loss: 1.717595174908638
Epoch 91/100, Loss: 1.7499251961708069
Epoch 92/100, Loss: 1.670396476984024
Epoch 93/100, Loss: 1.8306901082396507
Epoch 94/100, Loss: 1.790362760424614
Epoch 95/100, Loss: 1.7438544854521751
Epoch 96/100, Loss: 1.8269555419683456
Epoch 97/100, Loss: 1.7907740026712418
Epoch 98/100, Loss: 1.843907169997692

Epoch 99/100, Loss: 1.8050856813788414
Epoch 100/100, Loss: 1.7676104232668877
Fold 5/5 done

In [11]:
ap = average_precision_score(y_true, anomaly_scores)
print(f"Deep SVDD AP (5-fold CV) = {ap:.4f}")
sb.glue("GBG500_ap_spectral_deep_svdd", float(ap))

Deep SVDD AP (5-fold CV) = 0.3626