In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import average_precision_score
from sklearn.model_selection import StratifiedKFold
from pyod.models.deep_svdd import DeepSVDD
import sys
import scrapbook as sb

sys.path.append('..')
from utils import reshape_to_numpy, interpolate_missing_values, denoise_data, compute_spectrograms, time_avg_pooling

In [2]:
seed = 1
sampling_rate = 10
nperseg=64
noverlap=32
accel_cutoff = 0.4
accel_order = 30
gyro_cutoff = 0.6
gyro_order = 20
batch_size = 32
epochs = 100
hidden_neurons = [128, 64, 32]
n_splits = 5

In [3]:
# Parameters
seed = 4

In [4]:
rng = np.random.RandomState(seed)

In [5]:
data = pd.read_parquet("../data/GBG500.parquet")
data

,ride_id,time_index,ax,ay,az,rx,ry,rz
0,005043f1a7520cebf1e17fd166a00a3190e2433530f236...,0,-2.512796,-9.385012,-1.053078,-0.009155,0.009155,-0.201416
1,005043f1a7520cebf1e17fd166a00a3190e2433530f236...,100,-2.491268,-9.385012,-1.079390,-0.036621,0.027465,-0.155639
2,005043f1a7520cebf1e17fd166a00a3190e2433530f236...,200,-2.534324,-9.382022,-1.030952,0.036621,0.027465,-0.073242
3,005043f1a7520cebf1e17fd166a00a3190e2433530f236...,300,-2.488278,-9.383218,-1.091948,-0.045776,0.036621,-0.183105
4,005043f1a7520cebf1e17fd166a00a3190e2433530f236...,400,-2.483494,-9.382022,-1.100320,-0.045776,0.027465,-0.192260
...,...,...,...,...,...,...,...,...
1529542,ffb6f2f5dc6ba768d88dc0bc1af4cad235526aa9e24168...,241300,0.459862,-9.140430,-3.318900,1.556396,-0.091552,0.274658
1529543,ffb6f2f5dc6ba768d88dc0bc1af4cad235526aa9e24168...,241400,0.455676,-9.140430,-3.321292,1.583861,-0.119018,0.274658
1529544,ffb6f2f5dc6ba768d88dc0bc1af4cad235526aa9e24168...,241500,0.459862,-9.139832,-3.317704,1.583861,-0.109863,0.274658
1529545,ffb6f2f5dc6ba768d88dc0bc1af4cad235526aa9e24168...,241600,0.456274,-9.142224,-3.321292,1.574707,-0.137329,0.283813
1529546,ffb6f2f5dc6ba768d88dc0bc1af4cad235526aa9e24168...,241700,0.458666,-9.139832,-3.320694,1.574707,-0.137329,0.274658

In [6]:
labels = pd.read_csv("../data/GBG500_labels.csv")
labels.columns = labels.columns.str.lower()
ride_order_df = pd.DataFrame({"ride_id": data["ride_id"].unique()})
labels_sorted = ride_order_df.merge(
    labels,
    on="ride_id",
    how="left"
)
labels_sorted

                                               ride_id        label
0    005043f1a7520cebf1e17fd166a00a3190e2433530f236...         Safe
1    00d223cb7aecc9c0cc5871e32a6c45027a068eba07c572...     Reckless
2    02288a4aeca044203394e982e76b87818021dea2b34df9...         Safe
3    0236bdcf13d473ea24d97f5eaeea459f257dffac005694...  Bad weather
4    0238e5dd85143f1b6c59b200bc32f14361b8fc84c51a87...         Safe
..                                                 ...          ...
495  fe5d7f84d692bbccad8bd566a3ad5c3108fa9f90acd671...         Safe
496  fe67169632306d4668b2affedef510df2cb43e2fb41220...         Safe
497  fee44667fdc8ab4995c702fc3bd36178de0b1ca2c64687...         Safe
498  ff79b2e945b93c2a5efc3a06365267b3a160e7849ba57d...         Safe
499  ffb6f2f5dc6ba768d88dc0bc1af4cad235526aa9e24168...         Safe

[500 rows x 2 columns]

In [7]:
data_np = reshape_to_numpy(
    data,
    features = ["ax", "ay", "az", "rx", "ry", "rz"],
    max_timestamps = 4800
)

data_np_clean = interpolate_missing_values(
    data_np,
    method='linear',
    limit=None
)

data_np_clean = denoise_data(
    data=data_np_clean,
    accel_indices=[0, 1, 2],
    gyro_indices=[3, 4, 5],
    accel_cutoff=accel_cutoff,
    accel_order=accel_order,
    gyro_cutoff=gyro_cutoff,
    gyro_order=gyro_order,
)

In [8]:
# Compute spectrograms for all rides
spectrograms_array = compute_spectrograms(data_np_clean, sampling_rate, nperseg, noverlap)
spectrograms_array.shape

(500, 149, 6, 33)

In [9]:
# Aggregate spectrograms using time-averaged pooling
X_feat = time_avg_pooling(spectrograms_array)
X_feat.shape

(500, 198)

In [10]:
# 5-fold stratified CV with Deep SVDD
skf = StratifiedKFold(n_splits=n_splits, shuffle=True, random_state=rng.randint(1000))
y_true = (labels_sorted['label'] == 'Reckless').astype(int).values
anomaly_scores = np.full(len(y_true), np.nan)

for fold, (train_idx, test_idx) in enumerate(skf.split(X_feat, y_true)):
    sc = StandardScaler()
    X_train = sc.fit_transform(X_feat[train_idx])
    X_test = sc.transform(X_feat[test_idx])

    np.random.seed(rng.randint(1000))
    model = DeepSVDD(
        n_features=X_train.shape[1],
        hidden_neurons=hidden_neurons,
        epochs=epochs,
        batch_size=batch_size,
        random_state=rng.randint(1000),
    )
    model.fit(X_train)
    anomaly_scores[test_idx] = model.decision_function(X_test)
    print(f"Fold {fold+1}/{n_splits} done")

Epoch 1/100, Loss: 5.336466647684574
Epoch 2/100, Loss: 4.427559971809387
Epoch 3/100, Loss: 4.887803874909878
Epoch 4/100, Loss: 4.232090674340725
Epoch 5/100, Loss: 4.701523512601852
Epoch 6/100, Loss: 4.699500605463982
Epoch 7/100, Loss: 5.182018645107746
Epoch 8/100, Loss: 5.3094410970807076
Epoch 9/100, Loss: 5.066309295594692
Epoch 10/100, Loss: 5.653543680906296
Epoch 11/100, Loss: 4.553400136530399
Epoch 12/100, Loss: 4.745679385960102
Epoch 13/100, Loss: 4.7852074801921844
Epoch 14/100, Loss: 4.937862932682037
Epoch 15/100, Loss: 4.43836784362793
Epoch 16/100, Loss: 5.0347418785095215

Epoch 17/100, Loss: 5.021825611591339
Epoch 18/100, Loss: 4.72497995942831
Epoch 19/100, Loss: 4.902732104063034
Epoch 20/100, Loss: 4.510999973863363
Epoch 21/100, Loss: 4.503953341394663
Epoch 22/100, Loss: 6.2422881200909615
Epoch 23/100, Loss: 4.6992509588599205
Epoch 24/100, Loss: 4.318152032792568
Epoch 25/100, Loss: 4.90099635720253
Epoch 26/100, Loss: 4.841448109596968
Epoch 27/100, Loss: 4.425222299993038
Epoch 28/100, Loss: 4.614585906267166
Epoch 29/100, Loss: 4.707480914890766
Epoch 30/100, Loss: 4.232269994914532
Epoch 31/100, Loss: 4.554698757827282
Epoch 32/100, Loss: 4.79944459348917

Epoch 33/100, Loss: 4.901455968618393
Epoch 34/100, Loss: 4.492105171084404
Epoch 35/100, Loss: 4.150566920638084
Epoch 36/100, Loss: 5.0284358859062195
Epoch 37/100, Loss: 4.624787986278534
Epoch 38/100, Loss: 3.832557510584593
Epoch 39/100, Loss: 5.079403266310692
Epoch 40/100, Loss: 5.007844872772694
Epoch 41/100, Loss: 4.932151526212692
Epoch 42/100, Loss: 4.339665375649929
Epoch 43/100, Loss: 5.22596737742424
Epoch 44/100, Loss: 4.500931583344936
Epoch 45/100, Loss: 4.938420355319977
Epoch 46/100, Loss: 3.97709821164608
Epoch 47/100, Loss: 4.473969668149948
Epoch 48/100, Loss: 3.9296439588069916

Epoch 49/100, Loss: 4.1910750940442085
Epoch 50/100, Loss: 4.00892511382699
Epoch 51/100, Loss: 3.757429152727127
Epoch 52/100, Loss: 4.987947799265385
Epoch 53/100, Loss: 4.66007287427783
Epoch 54/100, Loss: 4.272987544536591
Epoch 55/100, Loss: 5.039771109819412
Epoch 56/100, Loss: 4.475351549685001
Epoch 57/100, Loss: 4.637935105711222
Epoch 58/100, Loss: 5.004638805985451
Epoch 59/100, Loss: 4.631642863154411
Epoch 60/100, Loss: 4.972450755536556
Epoch 61/100, Loss: 4.519320346415043
Epoch 62/100, Loss: 3.879102848470211

Epoch 63/100, Loss: 4.630123391747475
Epoch 64/100, Loss: 4.943734481930733
Epoch 65/100, Loss: 4.519789393991232
Epoch 66/100, Loss: 3.793685205280781
Epoch 67/100, Loss: 4.333407573401928
Epoch 68/100, Loss: 4.583724834024906
Epoch 69/100, Loss: 4.311988525092602
Epoch 70/100, Loss: 4.558416172862053
Epoch 71/100, Loss: 4.673612654209137
Epoch 72/100, Loss: 4.355059280991554
Epoch 73/100, Loss: 4.450515426695347
Epoch 74/100, Loss: 4.486964210867882
Epoch 75/100, Loss: 5.000582858920097
Epoch 76/100, Loss: 5.0884543135762215
Epoch 77/100, Loss: 5.074480377137661
Epoch 78/100, Loss: 5.17362717539072

Epoch 79/100, Loss: 5.235865615308285
Epoch 80/100, Loss: 4.5353604927659035
Epoch 81/100, Loss: 6.224984422326088
Epoch 82/100, Loss: 4.751306217163801
Epoch 83/100, Loss: 3.8706070631742477
Epoch 84/100, Loss: 4.6819209307432175
Epoch 85/100, Loss: 5.239625819027424
Epoch 86/100, Loss: 5.405872993171215
Epoch 87/100, Loss: 4.617831148207188
Epoch 88/100, Loss: 4.480222657322884
Epoch 89/100, Loss: 3.789371818304062
Epoch 90/100, Loss: 4.796165034174919
Epoch 91/100, Loss: 4.326095186173916
Epoch 92/100, Loss: 4.914957284927368
Epoch 93/100, Loss: 4.091666668653488
Epoch 94/100, Loss: 3.944505825638771

Epoch 95/100, Loss: 4.578778259456158
Epoch 96/100, Loss: 5.065914787352085
Epoch 97/100, Loss: 4.606270603835583
Epoch 98/100, Loss: 5.173597097396851
Epoch 99/100, Loss: 4.565046787261963
Epoch 100/100, Loss: 4.882535021752119
Fold 1/5 done
Epoch 1/100, Loss: 3.2627411410212517
Epoch 2/100, Loss: 3.0961865335702896
Epoch 3/100, Loss: 3.3383677303791046
Epoch 4/100, Loss: 3.458607755601406
Epoch 5/100, Loss: 3.430439844727516
Epoch 6/100, Loss: 3.3747000321745872
Epoch 7/100, Loss: 3.49113467335701
Epoch 8/100, Loss: 3.3977165818214417
Epoch 9/100, Loss: 3.252703182399273

Epoch 10/100, Loss: 3.601662613451481
Epoch 11/100, Loss: 3.374152697622776
Epoch 12/100, Loss: 3.2329518869519234
Epoch 13/100, Loss: 3.5660279989242554
Epoch 14/100, Loss: 3.505693294107914
Epoch 15/100, Loss: 3.189772680401802
Epoch 16/100, Loss: 3.2084242329001427
Epoch 17/100, Loss: 3.485264480113983
Epoch 18/100, Loss: 3.3662882149219513
Epoch 19/100, Loss: 3.4652865678071976
Epoch 20/100, Loss: 3.457817405462265
Epoch 21/100, Loss: 3.395684093236923
Epoch 22/100, Loss: 3.245384767651558
Epoch 23/100, Loss: 3.584693767130375
Epoch 24/100, Loss: 3.0542071908712387
Epoch 25/100, Loss: 3.3956000432372093

Epoch 26/100, Loss: 3.0608224347233772
Epoch 27/100, Loss: 4.043010361492634
Epoch 28/100, Loss: 3.3570309430360794
Epoch 29/100, Loss: 3.5145507007837296
Epoch 30/100, Loss: 3.2737830206751823
Epoch 31/100, Loss: 3.4563345909118652
Epoch 32/100, Loss: 3.135309047996998
Epoch 33/100, Loss: 3.4536399990320206
Epoch 34/100, Loss: 3.347938396036625
Epoch 35/100, Loss: 3.368995927274227
Epoch 36/100, Loss: 3.211531199514866
Epoch 37/100, Loss: 3.4778389036655426
Epoch 38/100, Loss: 4.281417839229107
Epoch 39/100, Loss: 3.2425748333334923

Epoch 40/100, Loss: 3.3216913416981697
Epoch 41/100, Loss: 3.353305384516716
Epoch 42/100, Loss: 3.6730365604162216
Epoch 43/100, Loss: 3.9846203848719597
Epoch 44/100, Loss: 3.4183438792824745
Epoch 45/100, Loss: 3.145302824676037
Epoch 46/100, Loss: 3.1225465834140778
Epoch 47/100, Loss: 3.4245614409446716
Epoch 48/100, Loss: 3.3158728629350662
Epoch 49/100, Loss: 3.155517280101776
Epoch 50/100, Loss: 3.386646904051304
Epoch 51/100, Loss: 3.1426302790641785
Epoch 52/100, Loss: 3.2629677802324295
Epoch 53/100, Loss: 3.1560386195778847

Epoch 54/100, Loss: 3.0506772249937057
Epoch 55/100, Loss: 3.3587902262806892
Epoch 56/100, Loss: 3.4555305168032646
Epoch 57/100, Loss: 3.260525219142437
Epoch 58/100, Loss: 3.4243033826351166
Epoch 59/100, Loss: 3.3122432082891464
Epoch 60/100, Loss: 3.422840304672718
Epoch 61/100, Loss: 3.268992356956005
Epoch 62/100, Loss: 3.267689563333988
Epoch 63/100, Loss: 2.9998163506388664
Epoch 64/100, Loss: 3.574683003127575
Epoch 65/100, Loss: 3.048346661031246
Epoch 66/100, Loss: 3.0631255581974983
Epoch 67/100, Loss: 3.3731968998908997
Epoch 68/100, Loss: 2.927196577191353
Epoch 69/100, Loss: 3.4142151325941086
Epoch 70/100, Loss: 3.5321144834160805

Epoch 71/100, Loss: 3.2261020615696907
Epoch 72/100, Loss: 3.3367835506796837
Epoch 73/100, Loss: 3.11200437694788
Epoch 74/100, Loss: 3.480259194970131
Epoch 75/100, Loss: 3.421487018465996
Epoch 76/100, Loss: 3.482594318687916
Epoch 77/100, Loss: 3.4536541253328323
Epoch 78/100, Loss: 3.15742227435112
Epoch 79/100, Loss: 3.6488209664821625
Epoch 80/100, Loss: 3.489057555794716
Epoch 81/100, Loss: 3.5279874056577682
Epoch 82/100, Loss: 3.081861861050129
Epoch 83/100, Loss: 3.4301480501890182
Epoch 84/100, Loss: 3.1966045051813126
Epoch 85/100, Loss: 3.112367458641529
Epoch 86/100, Loss: 3.189931310713291
Epoch 87/100, Loss: 3.15403750538826
Epoch 88/100, Loss: 3.417874224483967
Epoch 89/100, Loss: 2.858936697244644

Epoch 90/100, Loss: 3.3956195190548897
Epoch 91/100, Loss: 3.4229863584041595
Epoch 92/100, Loss: 3.241672605276108
Epoch 93/100, Loss: 3.2911248952150345
Epoch 94/100, Loss: 3.239522658288479
Epoch 95/100, Loss: 3.3754091784358025
Epoch 96/100, Loss: 3.050334617495537
Epoch 97/100, Loss: 3.3390266597270966
Epoch 98/100, Loss: 3.463027596473694
Epoch 99/100, Loss: 4.135828413069248
Epoch 100/100, Loss: 3.217926450073719
Fold 2/5 done

Epoch 1/100, Loss: 2.9326719120144844
Epoch 2/100, Loss: 2.9688140749931335
Epoch 3/100, Loss: 2.897834151983261
Epoch 4/100, Loss: 2.9119801223278046
Epoch 5/100, Loss: 2.5971035957336426
Epoch 6/100, Loss: 2.9362591952085495
Epoch 7/100, Loss: 2.7025285959243774
Epoch 8/100, Loss: 2.8831161484122276
Epoch 9/100, Loss: 2.935160331428051
Epoch 10/100, Loss: 2.8594046607613564
Epoch 11/100, Loss: 2.877226799726486
Epoch 12/100, Loss: 3.02423095703125
Epoch 13/100, Loss: 3.30283335596323

Epoch 14/100, Loss: 2.796418935060501
Epoch 15/100, Loss: 2.87589081376791
Epoch 16/100, Loss: 2.7722296193242073
Epoch 17/100, Loss: 2.700301870703697
Epoch 18/100, Loss: 2.8546607196331024
Epoch 19/100, Loss: 2.9150132834911346
Epoch 20/100, Loss: 2.542444087564945
Epoch 21/100, Loss: 2.497075729072094
Epoch 22/100, Loss: 2.7309316396713257
Epoch 23/100, Loss: 2.8966255486011505
Epoch 24/100, Loss: 3.0777396634221077
Epoch 25/100, Loss: 2.859464719891548
Epoch 26/100, Loss: 2.8901632502675056
Epoch 27/100, Loss: 2.9192292988300323
Epoch 28/100, Loss: 2.7326127886772156
Epoch 29/100, Loss: 2.8846323788166046
Epoch 30/100, Loss: 2.71766559779644
Epoch 31/100, Loss: 2.6814560517668724

Epoch 32/100, Loss: 3.0392149910330772
Epoch 33/100, Loss: 2.768302358686924
Epoch 34/100, Loss: 2.7460104674100876
Epoch 35/100, Loss: 2.7250660732388496
Epoch 36/100, Loss: 3.072744406759739
Epoch 37/100, Loss: 3.0002900287508965
Epoch 38/100, Loss: 2.800664208829403
Epoch 39/100, Loss: 2.8659314960241318
Epoch 40/100, Loss: 2.736391544342041
Epoch 41/100, Loss: 2.6860991418361664
Epoch 42/100, Loss: 2.960908867418766
Epoch 43/100, Loss: 2.6181731522083282
Epoch 44/100, Loss: 2.82093445956707
Epoch 45/100, Loss: 2.557354435324669
Epoch 46/100, Loss: 2.6893868148326874
Epoch 47/100, Loss: 2.6937958896160126
Epoch 48/100, Loss: 2.9065667912364006
Epoch 49/100, Loss: 2.7888877242803574
Epoch 50/100, Loss: 2.8613073006272316

Epoch 51/100, Loss: 3.0515668392181396
Epoch 52/100, Loss: 3.0226790010929108
Epoch 53/100, Loss: 2.706321805715561
Epoch 54/100, Loss: 3.82754335552454
Epoch 55/100, Loss: 2.7057837024331093
Epoch 56/100, Loss: 2.613074965775013
Epoch 57/100, Loss: 2.927093006670475
Epoch 58/100, Loss: 2.6583331525325775
Epoch 59/100, Loss: 2.976645976305008
Epoch 60/100, Loss: 2.5674334093928337
Epoch 61/100, Loss: 3.131321430206299
Epoch 62/100, Loss: 2.6930642426013947
Epoch 63/100, Loss: 2.9952926114201546
Epoch 64/100, Loss: 2.540509343147278
Epoch 65/100, Loss: 2.777808390557766
Epoch 66/100, Loss: 2.896054469048977
Epoch 67/100, Loss: 3.1605657562613487
Epoch 68/100, Loss: 2.6203131452202797

Epoch 69/100, Loss: 2.8704753518104553
Epoch 70/100, Loss: 3.0924443155527115
Epoch 71/100, Loss: 2.649700812995434
Epoch 72/100, Loss: 2.7004846930503845
Epoch 73/100, Loss: 2.906147487461567
Epoch 74/100, Loss: 2.655051626265049
Epoch 75/100, Loss: 3.0360267385840416
Epoch 76/100, Loss: 2.936994545161724
Epoch 77/100, Loss: 2.9628109335899353
Epoch 78/100, Loss: 3.054104581475258
Epoch 79/100, Loss: 2.788020558655262
Epoch 80/100, Loss: 2.745770685374737
Epoch 81/100, Loss: 2.7319495007395744
Epoch 82/100, Loss: 2.836279846727848
Epoch 83/100, Loss: 2.9111669957637787
Epoch 84/100, Loss: 3.972770355641842
Epoch 85/100, Loss: 2.88876024633646

Epoch 86/100, Loss: 2.868707612156868
Epoch 87/100, Loss: 2.520162381231785
Epoch 88/100, Loss: 2.830935314297676
Epoch 89/100, Loss: 3.0808262676000595
Epoch 90/100, Loss: 2.586370959877968
Epoch 91/100, Loss: 2.836693398654461
Epoch 92/100, Loss: 2.794078953564167
Epoch 93/100, Loss: 2.691905491054058
Epoch 94/100, Loss: 2.607414849102497
Epoch 95/100, Loss: 2.8139400333166122
Epoch 96/100, Loss: 2.5374780893325806
Epoch 97/100, Loss: 2.8136845007538795
Epoch 98/100, Loss: 2.9582241103053093

Epoch 99/100, Loss: 3.059697464108467
Epoch 100/100, Loss: 2.823652558028698
Fold 3/5 done
Epoch 1/100, Loss: 2.273290753364563
Epoch 2/100, Loss: 2.428892567753792
Epoch 3/100, Loss: 2.4050475731492043
Epoch 4/100, Loss: 2.348768152296543
Epoch 5/100, Loss: 2.3061069026589394
Epoch 6/100, Loss: 2.4150595515966415
Epoch 7/100, Loss: 2.2338728606700897
Epoch 8/100, Loss: 2.2081639915704727
Epoch 9/100, Loss: 2.3810756504535675
Epoch 10/100, Loss: 2.4390899166464806

Epoch 11/100, Loss: 2.51890616863966
Epoch 12/100, Loss: 2.284170053899288
Epoch 13/100, Loss: 2.44973211735487
Epoch 14/100, Loss: 2.347142107784748
Epoch 15/100, Loss: 2.4834020733833313
Epoch 16/100, Loss: 2.401733711361885
Epoch 17/100, Loss: 2.3995505645871162
Epoch 18/100, Loss: 2.5552761554718018
Epoch 19/100, Loss: 2.238304555416107
Epoch 20/100, Loss: 2.418597511947155
Epoch 21/100, Loss: 2.442806161940098
Epoch 22/100, Loss: 2.3759827688336372
Epoch 23/100, Loss: 2.531955122947693
Epoch 24/100, Loss: 2.496039889752865

Epoch 25/100, Loss: 2.4387679025530815
Epoch 26/100, Loss: 2.38830054551363
Epoch 27/100, Loss: 2.627332217991352
Epoch 28/100, Loss: 2.3804334551095963
Epoch 29/100, Loss: 2.26608806848526
Epoch 30/100, Loss: 2.4032128900289536
Epoch 31/100, Loss: 2.307637929916382
Epoch 32/100, Loss: 2.311298221349716
Epoch 33/100, Loss: 2.443037435412407
Epoch 34/100, Loss: 2.2687285393476486
Epoch 35/100, Loss: 2.332620248198509
Epoch 36/100, Loss: 2.4026250764727592
Epoch 37/100, Loss: 2.622733399271965
Epoch 38/100, Loss: 2.3047624826431274
Epoch 39/100, Loss: 2.6277419179677963
Epoch 40/100, Loss: 2.366306319832802

Epoch 41/100, Loss: 2.5176476538181305
Epoch 42/100, Loss: 2.424542248249054
Epoch 43/100, Loss: 2.5042766258120537
Epoch 44/100, Loss: 2.32192699611187
Epoch 45/100, Loss: 2.401970051229
Epoch 46/100, Loss: 2.466135822236538
Epoch 47/100, Loss: 2.2485293447971344
Epoch 48/100, Loss: 2.3819482252001762
Epoch 49/100, Loss: 2.451771780848503
Epoch 50/100, Loss: 2.3474246487021446
Epoch 51/100, Loss: 2.361421711742878
Epoch 52/100, Loss: 2.297122061252594
Epoch 53/100, Loss: 2.242956131696701
Epoch 54/100, Loss: 2.605019301176071
Epoch 55/100, Loss: 2.2356222346425056
Epoch 56/100, Loss: 2.349780037999153
Epoch 57/100, Loss: 2.4154906570911407

Epoch 58/100, Loss: 2.4921875670552254
Epoch 59/100, Loss: 2.4244106709957123
Epoch 60/100, Loss: 2.391667902469635
Epoch 61/100, Loss: 2.3858660608530045
Epoch 62/100, Loss: 2.314613528549671
Epoch 63/100, Loss: 2.287608005106449
Epoch 64/100, Loss: 2.32001855969429
Epoch 65/100, Loss: 2.480052202939987
Epoch 66/100, Loss: 2.4440716207027435
Epoch 67/100, Loss: 2.3890426978468895
Epoch 68/100, Loss: 2.316254697740078
Epoch 69/100, Loss: 2.4293735697865486
Epoch 70/100, Loss: 2.336972087621689
Epoch 71/100, Loss: 2.4643025770783424
Epoch 72/100, Loss: 2.3931021690368652
Epoch 73/100, Loss: 2.263323001563549
Epoch 74/100, Loss: 2.286369673907757

Epoch 75/100, Loss: 2.487981379032135
Epoch 76/100, Loss: 2.445190578699112
Epoch 77/100, Loss: 2.3835221007466316
Epoch 78/100, Loss: 2.532909944653511
Epoch 79/100, Loss: 2.2791402637958527
Epoch 80/100, Loss: 2.326497808098793
Epoch 81/100, Loss: 2.393911376595497
Epoch 82/100, Loss: 2.413371331989765
Epoch 83/100, Loss: 2.398351415991783
Epoch 84/100, Loss: 2.2869819179177284
Epoch 85/100, Loss: 2.533213049173355
Epoch 86/100, Loss: 2.544384650886059
Epoch 87/100, Loss: 2.36159298568964
Epoch 88/100, Loss: 2.4676683843135834
Epoch 89/100, Loss: 2.5258466973900795
Epoch 90/100, Loss: 2.393847316503525
Epoch 91/100, Loss: 2.3392621129751205

Epoch 92/100, Loss: 2.349449060857296
Epoch 93/100, Loss: 2.460505485534668
Epoch 94/100, Loss: 2.5301737263798714
Epoch 95/100, Loss: 2.3942437544465065
Epoch 96/100, Loss: 2.4005666449666023
Epoch 97/100, Loss: 2.4581735655665398
Epoch 98/100, Loss: 2.376643992960453
Epoch 99/100, Loss: 2.556930288672447
Epoch 100/100, Loss: 2.4854540452361107
Fold 4/5 done
Epoch 1/100, Loss: 1.6199886053800583
Epoch 2/100, Loss: 1.5586601421236992
Epoch 3/100, Loss: 1.6617933474481106
Epoch 4/100, Loss: 1.6676767766475677
Epoch 5/100, Loss: 1.5718318447470665
Epoch 6/100, Loss: 1.6876376830041409

Epoch 7/100, Loss: 1.6827089861035347
Epoch 8/100, Loss: 1.7216559648513794
Epoch 9/100, Loss: 1.6629111468791962
Epoch 10/100, Loss: 1.7464562058448792
Epoch 11/100, Loss: 1.6339589282870293
Epoch 12/100, Loss: 1.6703692451119423
Epoch 13/100, Loss: 1.6343950740993023
Epoch 14/100, Loss: 1.7048676162958145
Epoch 15/100, Loss: 1.607242651283741
Epoch 16/100, Loss: 1.7777292057871819
Epoch 17/100, Loss: 1.5479817539453506
Epoch 18/100, Loss: 1.561333142220974

Epoch 19/100, Loss: 1.654556266963482
Epoch 20/100, Loss: 1.715258151292801
Epoch 21/100, Loss: 1.639320321381092
Epoch 22/100, Loss: 1.6335574761033058
Epoch 23/100, Loss: 1.6802558153867722
Epoch 24/100, Loss: 1.6527568027377129
Epoch 25/100, Loss: 1.6854702234268188
Epoch 26/100, Loss: 1.6137456893920898
Epoch 27/100, Loss: 1.6391795761883259
Epoch 28/100, Loss: 1.6317285597324371
Epoch 29/100, Loss: 1.5274123921990395
Epoch 30/100, Loss: 1.6306227892637253

Epoch 31/100, Loss: 1.6101294197142124
Epoch 32/100, Loss: 1.5985709354281425
Epoch 33/100, Loss: 1.735482957214117
Epoch 34/100, Loss: 1.6108217984437943
Epoch 35/100, Loss: 1.715334925800562
Epoch 36/100, Loss: 1.4584328010678291
Epoch 37/100, Loss: 1.6513813063502312
Epoch 38/100, Loss: 1.5908118337392807
Epoch 39/100, Loss: 1.646794132888317
Epoch 40/100, Loss: 1.6363883577287197
Epoch 41/100, Loss: 1.57907073199749
Epoch 42/100, Loss: 1.611301340162754
Epoch 43/100, Loss: 1.685856193304062
Epoch 44/100, Loss: 1.5988257564604282
Epoch 45/100, Loss: 1.590913712978363

Epoch 46/100, Loss: 1.7580182403326035
Epoch 47/100, Loss: 1.6120598763227463
Epoch 48/100, Loss: 1.440895576030016
Epoch 49/100, Loss: 1.532054789364338
Epoch 50/100, Loss: 1.6232518218457699
Epoch 51/100, Loss: 1.6230058073997498
Epoch 52/100, Loss: 1.5580409578979015
Epoch 53/100, Loss: 1.6027279198169708
Epoch 54/100, Loss: 1.655973207205534
Epoch 55/100, Loss: 1.6179752871394157
Epoch 56/100, Loss: 1.680672101676464
Epoch 57/100, Loss: 1.6919737979769707
Epoch 58/100, Loss: 2.0763083770871162
Epoch 59/100, Loss: 1.6952888444066048
Epoch 60/100, Loss: 1.5411339476704597
Epoch 61/100, Loss: 1.7106698900461197

Epoch 62/100, Loss: 1.7895470783114433
Epoch 63/100, Loss: 1.5543040856719017
Epoch 64/100, Loss: 1.7117766924202442
Epoch 65/100, Loss: 1.7357519194483757
Epoch 66/100, Loss: 1.5932913571596146
Epoch 67/100, Loss: 1.6505579352378845
Epoch 68/100, Loss: 1.7150020487606525
Epoch 69/100, Loss: 1.7231722995638847
Epoch 70/100, Loss: 1.7225563079118729
Epoch 71/100, Loss: 1.6455223709344864
Epoch 72/100, Loss: 1.5787992179393768
Epoch 73/100, Loss: 1.5915232971310616
Epoch 74/100, Loss: 1.54524327814579

Epoch 75/100, Loss: 1.5454238019883633
Epoch 76/100, Loss: 1.639875888824463
Epoch 77/100, Loss: 1.5850922651588917
Epoch 78/100, Loss: 1.5263638868927956
Epoch 79/100, Loss: 1.7866041027009487
Epoch 80/100, Loss: 1.6994411163032055
Epoch 81/100, Loss: 1.6751151606440544
Epoch 82/100, Loss: 1.727410763502121
Epoch 83/100, Loss: 1.5852045342326164
Epoch 84/100, Loss: 1.6899943947792053
Epoch 85/100, Loss: 1.7047208473086357
Epoch 86/100, Loss: 1.5742567032575607
Epoch 87/100, Loss: 1.8286241069436073
Epoch 88/100, Loss: 1.7142039313912392
Epoch 89/100, Loss: 1.6268597096204758
Epoch 90/100, Loss: 1.6584280952811241
Epoch 91/100, Loss: 1.6351808793842793

Epoch 92/100, Loss: 1.7221543081104755
Epoch 93/100, Loss: 1.6873083114624023
Epoch 94/100, Loss: 1.4756432324647903
Epoch 95/100, Loss: 1.6183889545500278
Epoch 96/100, Loss: 1.6305514983832836
Epoch 97/100, Loss: 1.6693402230739594
Epoch 98/100, Loss: 1.52052753418684
Epoch 99/100, Loss: 1.5582422316074371
Epoch 100/100, Loss: 1.5941206514835358
Fold 5/5 done

In [11]:
ap = average_precision_score(y_true, anomaly_scores)
print(f"Deep SVDD AP (5-fold CV) = {ap:.4f}")
sb.glue("GBG500_ap_spectral_deep_svdd", float(ap))

Deep SVDD AP (5-fold CV) = 0.5516