In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import average_precision_score
from sklearn.model_selection import StratifiedKFold
from pyod.models.deep_svdd import DeepSVDD
import sys
import scrapbook as sb

sys.path.append('..')
from utils import reshape_to_numpy, interpolate_missing_values, denoise_data, compute_spectrograms, time_avg_pooling

In [2]:
seed = 1
sampling_rate = 10
nperseg=64
noverlap=32
accel_cutoff = 0.4
accel_order = 30
gyro_cutoff = 0.6
gyro_order = 20
batch_size = 32
epochs = 100
hidden_neurons = [128, 64, 32]
n_splits = 5

In [3]:
# Parameters
seed = 23

In [4]:
rng = np.random.RandomState(seed)

In [5]:
data = pd.read_parquet("../data/GBG500.parquet")
data

,ride_id,time_index,ax,ay,az,rx,ry,rz
0,005043f1a7520cebf1e17fd166a00a3190e2433530f236...,0,-2.512796,-9.385012,-1.053078,-0.009155,0.009155,-0.201416
1,005043f1a7520cebf1e17fd166a00a3190e2433530f236...,100,-2.491268,-9.385012,-1.079390,-0.036621,0.027465,-0.155639
2,005043f1a7520cebf1e17fd166a00a3190e2433530f236...,200,-2.534324,-9.382022,-1.030952,0.036621,0.027465,-0.073242
3,005043f1a7520cebf1e17fd166a00a3190e2433530f236...,300,-2.488278,-9.383218,-1.091948,-0.045776,0.036621,-0.183105
4,005043f1a7520cebf1e17fd166a00a3190e2433530f236...,400,-2.483494,-9.382022,-1.100320,-0.045776,0.027465,-0.192260
...,...,...,...,...,...,...,...,...
1529542,ffb6f2f5dc6ba768d88dc0bc1af4cad235526aa9e24168...,241300,0.459862,-9.140430,-3.318900,1.556396,-0.091552,0.274658
1529543,ffb6f2f5dc6ba768d88dc0bc1af4cad235526aa9e24168...,241400,0.455676,-9.140430,-3.321292,1.583861,-0.119018,0.274658
1529544,ffb6f2f5dc6ba768d88dc0bc1af4cad235526aa9e24168...,241500,0.459862,-9.139832,-3.317704,1.583861,-0.109863,0.274658
1529545,ffb6f2f5dc6ba768d88dc0bc1af4cad235526aa9e24168...,241600,0.456274,-9.142224,-3.321292,1.574707,-0.137329,0.283813
1529546,ffb6f2f5dc6ba768d88dc0bc1af4cad235526aa9e24168...,241700,0.458666,-9.139832,-3.320694,1.574707,-0.137329,0.274658

In [6]:
labels = pd.read_csv("../data/GBG500_labels.csv")
labels.columns = labels.columns.str.lower()
ride_order_df = pd.DataFrame({"ride_id": data["ride_id"].unique()})
labels_sorted = ride_order_df.merge(
    labels,
    on="ride_id",
    how="left"
)
labels_sorted

                                               ride_id        label
0    005043f1a7520cebf1e17fd166a00a3190e2433530f236...         Safe
1    00d223cb7aecc9c0cc5871e32a6c45027a068eba07c572...     Reckless
2    02288a4aeca044203394e982e76b87818021dea2b34df9...         Safe
3    0236bdcf13d473ea24d97f5eaeea459f257dffac005694...  Bad weather
4    0238e5dd85143f1b6c59b200bc32f14361b8fc84c51a87...         Safe
..                                                 ...          ...
495  fe5d7f84d692bbccad8bd566a3ad5c3108fa9f90acd671...         Safe
496  fe67169632306d4668b2affedef510df2cb43e2fb41220...         Safe
497  fee44667fdc8ab4995c702fc3bd36178de0b1ca2c64687...         Safe
498  ff79b2e945b93c2a5efc3a06365267b3a160e7849ba57d...         Safe
499  ffb6f2f5dc6ba768d88dc0bc1af4cad235526aa9e24168...         Safe

[500 rows x 2 columns]

In [7]:
data_np = reshape_to_numpy(
    data,
    features = ["ax", "ay", "az", "rx", "ry", "rz"],
    max_timestamps = 4800
)

data_np_clean = interpolate_missing_values(
    data_np,
    method='linear',
    limit=None
)

data_np_clean = denoise_data(
    data=data_np_clean,
    accel_indices=[0, 1, 2],
    gyro_indices=[3, 4, 5],
    accel_cutoff=accel_cutoff,
    accel_order=accel_order,
    gyro_cutoff=gyro_cutoff,
    gyro_order=gyro_order,
)

In [8]:
# Compute spectrograms for all rides
spectrograms_array = compute_spectrograms(data_np_clean, sampling_rate, nperseg, noverlap)
spectrograms_array.shape

(500, 149, 6, 33)

In [9]:
# Aggregate spectrograms using time-averaged pooling
X_feat = time_avg_pooling(spectrograms_array)
X_feat.shape

(500, 198)

In [10]:
# 5-fold stratified CV with Deep SVDD
skf = StratifiedKFold(n_splits=n_splits, shuffle=True, random_state=rng.randint(1000))
y_true = (labels_sorted['label'] == 'Reckless').astype(int).values
anomaly_scores = np.full(len(y_true), np.nan)

for fold, (train_idx, test_idx) in enumerate(skf.split(X_feat, y_true)):
    sc = StandardScaler()
    X_train = sc.fit_transform(X_feat[train_idx])
    X_test = sc.transform(X_feat[test_idx])

    np.random.seed(rng.randint(1000))
    model = DeepSVDD(
        n_features=X_train.shape[1],
        hidden_neurons=hidden_neurons,
        epochs=epochs,
        batch_size=batch_size,
        random_state=rng.randint(1000),
    )
    model.fit(X_train)
    anomaly_scores[test_idx] = model.decision_function(X_test)
    print(f"Fold {fold+1}/{n_splits} done")

Epoch 1/100, Loss: 2.562464617192745
Epoch 2/100, Loss: 3.0825773775577545
Epoch 3/100, Loss: 3.2747222185134888
Epoch 4/100, Loss: 3.1173048615455627
Epoch 5/100, Loss: 3.0672856718301773
Epoch 6/100, Loss: 2.976446993649006
Epoch 7/100, Loss: 3.1036886982619762
Epoch 8/100, Loss: 2.830881841480732
Epoch 9/100, Loss: 3.196855530142784
Epoch 10/100, Loss: 3.6492850109934807
Epoch 11/100, Loss: 2.617651127278805
Epoch 12/100, Loss: 2.7386743426322937
Epoch 13/100, Loss: 2.71440452337265
Epoch 14/100, Loss: 3.014733076095581
Epoch 15/100, Loss: 2.97062174230814
Epoch 16/100, Loss: 2.9356360882520676
Epoch 17/100, Loss: 2.9588484540581703

Epoch 18/100, Loss: 2.957296662032604
Epoch 19/100, Loss: 3.1859570741653442
Epoch 20/100, Loss: 3.2414165288209915
Epoch 21/100, Loss: 2.7384480088949203
Epoch 22/100, Loss: 3.379339098930359
Epoch 23/100, Loss: 3.450148805975914
Epoch 24/100, Loss: 3.3471796587109566
Epoch 25/100, Loss: 3.80577552318573
Epoch 26/100, Loss: 3.7541777342557907
Epoch 27/100, Loss: 2.845496214926243
Epoch 28/100, Loss: 3.3125612139701843

Epoch 29/100, Loss: 3.406961739063263
Epoch 30/100, Loss: 3.3818040788173676
Epoch 31/100, Loss: 2.740839086472988
Epoch 32/100, Loss: 3.3032310605049133
Epoch 33/100, Loss: 2.8672487288713455
Epoch 34/100, Loss: 3.101403683423996
Epoch 35/100, Loss: 3.615751586854458
Epoch 36/100, Loss: 2.996363252401352
Epoch 37/100, Loss: 3.07197854667902
Epoch 38/100, Loss: 3.0923559442162514
Epoch 39/100, Loss: 3.100825823843479

Epoch 40/100, Loss: 3.103971891105175
Epoch 41/100, Loss: 3.4001335874199867
Epoch 42/100, Loss: 2.9466065913438797
Epoch 43/100, Loss: 3.2437249198555946
Epoch 44/100, Loss: 3.5384989827871323
Epoch 45/100, Loss: 3.4338733106851578
Epoch 46/100, Loss: 3.3928795903921127
Epoch 47/100, Loss: 3.6676183715462685
Epoch 48/100, Loss: 3.1889449805021286
Epoch 49/100, Loss: 3.337876372039318
Epoch 50/100, Loss: 3.5777102187275887

Epoch 51/100, Loss: 3.5681047514081
Epoch 52/100, Loss: 3.122712768614292
Epoch 53/100, Loss: 3.3732605054974556
Epoch 54/100, Loss: 3.2642814740538597
Epoch 55/100, Loss: 2.9634354896843433
Epoch 56/100, Loss: 3.4347823560237885
Epoch 57/100, Loss: 3.1214505806565285
Epoch 58/100, Loss: 2.784368373453617
Epoch 59/100, Loss: 3.2281971126794815
Epoch 60/100, Loss: 3.2450340017676353
Epoch 61/100, Loss: 3.362050585448742

Epoch 62/100, Loss: 3.206954374909401
Epoch 63/100, Loss: 2.8468344286084175
Epoch 64/100, Loss: 3.1016262993216515
Epoch 65/100, Loss: 3.4680862203240395
Epoch 66/100, Loss: 2.7573335021734238
Epoch 67/100, Loss: 3.152739316225052
Epoch 68/100, Loss: 3.5863983407616615
Epoch 69/100, Loss: 2.7481682002544403
Epoch 70/100, Loss: 3.039190225303173
Epoch 71/100, Loss: 2.998035617172718
Epoch 72/100, Loss: 2.9851621612906456

Epoch 73/100, Loss: 2.7193840593099594
Epoch 74/100, Loss: 2.923842817544937
Epoch 75/100, Loss: 2.937124125659466
Epoch 76/100, Loss: 3.016439288854599
Epoch 77/100, Loss: 3.3137236535549164
Epoch 78/100, Loss: 2.837434783577919
Epoch 79/100, Loss: 3.020691856741905
Epoch 80/100, Loss: 3.221056528389454
Epoch 81/100, Loss: 3.021873079240322
Epoch 82/100, Loss: 3.3511081635951996
Epoch 83/100, Loss: 3.401785969734192

Epoch 84/100, Loss: 3.644964426755905
Epoch 85/100, Loss: 3.036256365478039
Epoch 86/100, Loss: 3.2981960773468018
Epoch 87/100, Loss: 2.8066062554717064
Epoch 88/100, Loss: 3.2067044004797935
Epoch 89/100, Loss: 3.2794862389564514
Epoch 90/100, Loss: 3.368297502398491
Epoch 91/100, Loss: 3.41894144564867
Epoch 92/100, Loss: 2.958826445043087
Epoch 93/100, Loss: 2.944016642868519
Epoch 94/100, Loss: 2.7307289764285088
Epoch 95/100, Loss: 3.3178791850805283
Epoch 96/100, Loss: 2.697026737034321
Epoch 97/100, Loss: 3.603512294590473
Epoch 98/100, Loss: 3.634706012904644

Epoch 99/100, Loss: 2.8544286265969276
Epoch 100/100, Loss: 2.9871964529156685
Fold 1/5 done
Epoch 1/100, Loss: 2.669222556054592
Epoch 2/100, Loss: 2.560126818716526
Epoch 3/100, Loss: 2.619192913174629
Epoch 4/100, Loss: 2.6453491747379303
Epoch 5/100, Loss: 2.6037996783852577
Epoch 6/100, Loss: 2.651245139539242
Epoch 7/100, Loss: 2.63286817073822
Epoch 8/100, Loss: 2.603190638124943
Epoch 9/100, Loss: 2.587267965078354
Epoch 10/100, Loss: 2.6873529255390167
Epoch 11/100, Loss: 2.639033004641533
Epoch 12/100, Loss: 2.6697837114334106

Epoch 13/100, Loss: 2.5748860836029053
Epoch 14/100, Loss: 2.603487677872181
Epoch 15/100, Loss: 2.6279859989881516
Epoch 16/100, Loss: 2.8565726578235626
Epoch 17/100, Loss: 2.588856816291809
Epoch 18/100, Loss: 2.839828610420227
Epoch 19/100, Loss: 2.718742087483406
Epoch 20/100, Loss: 2.6323855966329575
Epoch 21/100, Loss: 2.7029363438487053
Epoch 22/100, Loss: 2.5342836678028107
Epoch 23/100, Loss: 2.4990092292428017
Epoch 24/100, Loss: 2.650226876139641
Epoch 25/100, Loss: 2.8107362911105156
Epoch 26/100, Loss: 2.517714612185955
Epoch 27/100, Loss: 2.681220754981041

Epoch 28/100, Loss: 2.538521334528923
Epoch 29/100, Loss: 2.6854544281959534
Epoch 30/100, Loss: 2.5880536288022995
Epoch 31/100, Loss: 2.800674483180046
Epoch 32/100, Loss: 2.5318747386336327
Epoch 33/100, Loss: 2.606844902038574
Epoch 34/100, Loss: 2.582330495119095
Epoch 35/100, Loss: 2.6640414595603943
Epoch 36/100, Loss: 2.5107154846191406
Epoch 37/100, Loss: 2.6902163475751877
Epoch 38/100, Loss: 2.759254977107048
Epoch 39/100, Loss: 2.61124599725008
Epoch 40/100, Loss: 2.626602068543434
Epoch 41/100, Loss: 2.5337316170334816
Epoch 42/100, Loss: 2.604350060224533

Epoch 43/100, Loss: 2.7135841846466064
Epoch 44/100, Loss: 2.60575532913208
Epoch 45/100, Loss: 2.7291775718331337
Epoch 46/100, Loss: 2.656269073486328
Epoch 47/100, Loss: 2.526664651930332
Epoch 48/100, Loss: 2.682268448174
Epoch 49/100, Loss: 2.6245134472846985
Epoch 50/100, Loss: 2.6701012402772903
Epoch 51/100, Loss: 2.670191243290901
Epoch 52/100, Loss: 2.696089394390583
Epoch 53/100, Loss: 2.59185653924942
Epoch 54/100, Loss: 2.608619309961796
Epoch 55/100, Loss: 2.571189410984516
Epoch 56/100, Loss: 2.47970000654459
Epoch 57/100, Loss: 2.586333081126213

Epoch 58/100, Loss: 2.5440173223614693
Epoch 59/100, Loss: 2.7193311974406242
Epoch 60/100, Loss: 2.6846706941723824
Epoch 61/100, Loss: 2.6163657680153847
Epoch 62/100, Loss: 2.71934125572443
Epoch 63/100, Loss: 2.520056165754795
Epoch 64/100, Loss: 2.7331322580575943
Epoch 65/100, Loss: 2.6137959957122803
Epoch 66/100, Loss: 2.7367284148931503
Epoch 67/100, Loss: 2.653296113014221
Epoch 68/100, Loss: 2.656647428870201
Epoch 69/100, Loss: 2.6107042953372
Epoch 70/100, Loss: 2.4715627506375313
Epoch 71/100, Loss: 2.6368774250149727
Epoch 72/100, Loss: 2.624804638326168

Epoch 73/100, Loss: 2.5550101175904274
Epoch 74/100, Loss: 2.637327805161476
Epoch 75/100, Loss: 2.579974591732025
Epoch 76/100, Loss: 2.6262084767222404
Epoch 77/100, Loss: 2.6856511533260345
Epoch 78/100, Loss: 2.6903989613056183
Epoch 79/100, Loss: 2.650165043771267
Epoch 80/100, Loss: 2.7603545486927032
Epoch 81/100, Loss: 2.706618033349514
Epoch 82/100, Loss: 2.5708856880664825
Epoch 83/100, Loss: 2.7411025017499924
Epoch 84/100, Loss: 2.7117134630680084
Epoch 85/100, Loss: 2.7461454942822456
Epoch 86/100, Loss: 2.8598829358816147
Epoch 87/100, Loss: 2.623741887509823

Epoch 88/100, Loss: 2.6192176192998886
Epoch 89/100, Loss: 2.7711915522813797
Epoch 90/100, Loss: 2.601179949939251
Epoch 91/100, Loss: 2.750028483569622
Epoch 92/100, Loss: 2.6275577768683434
Epoch 93/100, Loss: 2.8530246540904045
Epoch 94/100, Loss: 2.6749343872070312
Epoch 95/100, Loss: 2.637613072991371
Epoch 96/100, Loss: 2.5867798179388046
Epoch 97/100, Loss: 2.6432184875011444
Epoch 98/100, Loss: 2.5797067508101463
Epoch 99/100, Loss: 2.608516849577427
Epoch 100/100, Loss: 2.674369364976883
Fold 2/5 done
Epoch 1/100, Loss: 2.079384461045265

Epoch 2/100, Loss: 2.087123066186905
Epoch 3/100, Loss: 1.8940157294273376
Epoch 4/100, Loss: 2.092953536659479
Epoch 5/100, Loss: 1.9828480556607246
Epoch 6/100, Loss: 2.717895943671465
Epoch 7/100, Loss: 2.109543304890394
Epoch 8/100, Loss: 2.0030432790517807
Epoch 9/100, Loss: 2.1466224417090416
Epoch 10/100, Loss: 2.0828917920589447
Epoch 11/100, Loss: 2.253765918314457
Epoch 12/100, Loss: 2.116389699280262
Epoch 13/100, Loss: 2.20803914219141
Epoch 14/100, Loss: 1.9202560894191265
Epoch 15/100, Loss: 2.2705229818820953
Epoch 16/100, Loss: 3.012272883206606

Epoch 17/100, Loss: 2.214836098253727
Epoch 18/100, Loss: 1.915705494582653
Epoch 19/100, Loss: 2.0104062892496586
Epoch 20/100, Loss: 2.0261091589927673
Epoch 21/100, Loss: 2.020579222589731
Epoch 22/100, Loss: 1.947190247476101
Epoch 23/100, Loss: 2.0142292864620686
Epoch 24/100, Loss: 2.232366006821394
Epoch 25/100, Loss: 2.121818631887436
Epoch 26/100, Loss: 2.41661561653018
Epoch 27/100, Loss: 1.7594530917704105
Epoch 28/100, Loss: 2.2731247767806053
Epoch 29/100, Loss: 2.1722820922732353
Epoch 30/100, Loss: 2.116797346621752
Epoch 31/100, Loss: 1.9793028682470322

Epoch 32/100, Loss: 1.9515014700591564
Epoch 33/100, Loss: 1.846803080290556
Epoch 34/100, Loss: 1.762333258986473
Epoch 35/100, Loss: 2.113341763615608
Epoch 36/100, Loss: 2.010994963347912
Epoch 37/100, Loss: 2.2452007681131363
Epoch 38/100, Loss: 2.243381578475237
Epoch 39/100, Loss: 1.8275761529803276
Epoch 40/100, Loss: 2.1786161735653877
Epoch 41/100, Loss: 1.9697942845523357
Epoch 42/100, Loss: 1.9458140283823013
Epoch 43/100, Loss: 2.021988745778799
Epoch 44/100, Loss: 1.8303284347057343
Epoch 45/100, Loss: 2.180169250816107
Epoch 46/100, Loss: 2.02585419267416

Epoch 47/100, Loss: 1.9680257067084312
Epoch 48/100, Loss: 2.0607846304774284
Epoch 49/100, Loss: 1.9727436229586601
Epoch 50/100, Loss: 2.3274437710642815
Epoch 51/100, Loss: 2.024712949991226
Epoch 52/100, Loss: 3.0602690763771534
Epoch 53/100, Loss: 1.951401598751545
Epoch 54/100, Loss: 2.033098090440035
Epoch 55/100, Loss: 2.1995063088834286
Epoch 56/100, Loss: 1.7614653557538986
Epoch 57/100, Loss: 2.214367091655731
Epoch 58/100, Loss: 2.021199084818363
Epoch 59/100, Loss: 1.986395739018917
Epoch 60/100, Loss: 1.9109915159642696
Epoch 61/100, Loss: 2.0933342054486275

Epoch 62/100, Loss: 2.31375452876091
Epoch 63/100, Loss: 2.27471412345767
Epoch 64/100, Loss: 2.5713231302797794
Epoch 65/100, Loss: 2.608618538826704
Epoch 66/100, Loss: 2.1563130542635918
Epoch 67/100, Loss: 2.0266791991889477
Epoch 68/100, Loss: 1.6962511986494064
Epoch 69/100, Loss: 2.0815457813441753
Epoch 70/100, Loss: 2.027420938014984
Epoch 71/100, Loss: 2.155609581619501
Epoch 72/100, Loss: 2.1664424762129784
Epoch 73/100, Loss: 2.3121584467589855
Epoch 74/100, Loss: 1.897509502246976
Epoch 75/100, Loss: 2.139804106205702
Epoch 76/100, Loss: 1.995855312794447

Epoch 77/100, Loss: 2.15215665102005
Epoch 78/100, Loss: 1.8343530669808388
Epoch 79/100, Loss: 2.012783955782652
Epoch 80/100, Loss: 1.8348578326404095
Epoch 81/100, Loss: 2.203381635248661
Epoch 82/100, Loss: 2.31258512288332
Epoch 83/100, Loss: 2.0039259791374207
Epoch 84/100, Loss: 2.129547029733658
Epoch 85/100, Loss: 2.4342331141233444
Epoch 86/100, Loss: 1.7448370233178139
Epoch 87/100, Loss: 2.0502027422189713
Epoch 88/100, Loss: 2.25348874181509
Epoch 89/100, Loss: 2.0241025537252426
Epoch 90/100, Loss: 1.949919205158949
Epoch 91/100, Loss: 2.154505729675293

Epoch 92/100, Loss: 2.2083502411842346
Epoch 93/100, Loss: 1.9193481132388115
Epoch 94/100, Loss: 2.303297847509384
Epoch 95/100, Loss: 2.3303122222423553
Epoch 96/100, Loss: 2.0105326883494854
Epoch 97/100, Loss: 2.0048320107162
Epoch 98/100, Loss: 2.1665753796696663
Epoch 99/100, Loss: 2.145985893905163
Epoch 100/100, Loss: 2.251095164567232
Fold 3/5 done
Epoch 1/100, Loss: 1.9364330992102623
Epoch 2/100, Loss: 2.0838886946439743
Epoch 3/100, Loss: 1.8913548439741135
Epoch 4/100, Loss: 2.007548861205578
Epoch 5/100, Loss: 1.7550195530056953
Epoch 6/100, Loss: 1.9010444656014442
Epoch 7/100, Loss: 2.029848590493202

Epoch 8/100, Loss: 2.068975366652012
Epoch 9/100, Loss: 1.7092590406537056
Epoch 10/100, Loss: 1.7403634190559387
Epoch 11/100, Loss: 2.0686963200569153
Epoch 12/100, Loss: 1.9466577768325806
Epoch 13/100, Loss: 1.8333518877625465
Epoch 14/100, Loss: 2.099478669464588
Epoch 15/100, Loss: 1.8543928861618042
Epoch 16/100, Loss: 2.1254043877124786
Epoch 17/100, Loss: 1.9235867634415627
Epoch 18/100, Loss: 1.8128381669521332
Epoch 19/100, Loss: 2.088753677904606
Epoch 20/100, Loss: 2.1220853216946125
Epoch 21/100, Loss: 1.8848256319761276
Epoch 22/100, Loss: 1.9805245772004128
Epoch 23/100, Loss: 1.874115139245987
Epoch 24/100, Loss: 1.8075164034962654

Epoch 25/100, Loss: 1.9315251111984253
Epoch 26/100, Loss: 2.046051688492298
Epoch 27/100, Loss: 1.8562095314264297
Epoch 28/100, Loss: 1.802381120622158
Epoch 29/100, Loss: 1.798160508275032
Epoch 30/100, Loss: 1.8654708340764046
Epoch 31/100, Loss: 1.9515442475676537
Epoch 32/100, Loss: 2.0111812129616737
Epoch 33/100, Loss: 2.054183177649975
Epoch 34/100, Loss: 1.8051981404423714
Epoch 35/100, Loss: 2.0656503587961197
Epoch 36/100, Loss: 1.9381773695349693
Epoch 37/100, Loss: 1.851850911974907
Epoch 38/100, Loss: 2.0294896066188812
Epoch 39/100, Loss: 1.838594563305378
Epoch 40/100, Loss: 1.785779681056738
Epoch 41/100, Loss: 1.975720226764679

Epoch 42/100, Loss: 1.8851429969072342
Epoch 43/100, Loss: 1.8259573876857758
Epoch 44/100, Loss: 1.9407414495944977
Epoch 45/100, Loss: 1.7345668151974678
Epoch 46/100, Loss: 1.9087421894073486
Epoch 47/100, Loss: 1.891422115266323
Epoch 48/100, Loss: 2.0657322108745575
Epoch 49/100, Loss: 2.079111434519291
Epoch 50/100, Loss: 1.8136254101991653
Epoch 51/100, Loss: 2.0602428913116455
Epoch 52/100, Loss: 2.038697987794876
Epoch 53/100, Loss: 2.1148168966174126
Epoch 54/100, Loss: 1.9691959023475647
Epoch 55/100, Loss: 2.0186208114027977
Epoch 56/100, Loss: 2.022658161818981
Epoch 57/100, Loss: 2.1424624249339104
Epoch 58/100, Loss: 2.03655406832695
Epoch 59/100, Loss: 1.9623815640807152

Epoch 60/100, Loss: 1.8579470738768578
Epoch 61/100, Loss: 1.9395665377378464
Epoch 62/100, Loss: 2.054059885442257
Epoch 63/100, Loss: 2.0822944417595863
Epoch 64/100, Loss: 2.0617480985820293
Epoch 65/100, Loss: 2.129224516451359
Epoch 66/100, Loss: 2.5382624939084053
Epoch 67/100, Loss: 2.103247195482254
Epoch 68/100, Loss: 2.094763457775116
Epoch 69/100, Loss: 1.97293321788311
Epoch 70/100, Loss: 1.873658962547779
Epoch 71/100, Loss: 1.9183796420693398
Epoch 72/100, Loss: 2.0648269802331924
Epoch 73/100, Loss: 1.6916249319911003
Epoch 74/100, Loss: 1.9655845686793327
Epoch 75/100, Loss: 2.0076994746923447
Epoch 76/100, Loss: 1.8122449070215225
Epoch 77/100, Loss: 2.082262448966503

Epoch 78/100, Loss: 1.7862888425588608
Epoch 79/100, Loss: 1.7574222460389137
Epoch 80/100, Loss: 1.938290886580944
Epoch 81/100, Loss: 1.9929097890853882
Epoch 82/100, Loss: 1.96070097386837
Epoch 83/100, Loss: 2.2195157632231712
Epoch 84/100, Loss: 1.953733652830124
Epoch 85/100, Loss: 1.9847071021795273
Epoch 86/100, Loss: 1.9818311482667923
Epoch 87/100, Loss: 1.9370136931538582
Epoch 88/100, Loss: 1.9990345314145088
Epoch 89/100, Loss: 2.0933611020445824
Epoch 90/100, Loss: 2.3080219104886055
Epoch 91/100, Loss: 1.9154008105397224
Epoch 92/100, Loss: 1.989196378737688
Epoch 93/100, Loss: 1.6707135438919067
Epoch 94/100, Loss: 1.882789134979248
Epoch 95/100, Loss: 1.9512217715382576

Epoch 96/100, Loss: 1.996413141489029
Epoch 97/100, Loss: 2.2930763699114323
Epoch 98/100, Loss: 2.07919904589653
Epoch 99/100, Loss: 1.8903814628720284
Epoch 100/100, Loss: 1.925132304430008
Fold 4/5 done
Epoch 1/100, Loss: 2.8159131184220314
Epoch 2/100, Loss: 2.7464849054813385
Epoch 3/100, Loss: 3.017599120736122
Epoch 4/100, Loss: 3.033588781952858
Epoch 5/100, Loss: 2.8614243268966675
Epoch 6/100, Loss: 2.9308991879224777
Epoch 7/100, Loss: 2.8661879301071167
Epoch 8/100, Loss: 2.9061611965298653
Epoch 9/100, Loss: 2.7656391635537148
Epoch 10/100, Loss: 2.975885108113289
Epoch 11/100, Loss: 2.81227957457304
Epoch 12/100, Loss: 3.0033750385046005

Epoch 13/100, Loss: 2.8621731400489807
Epoch 14/100, Loss: 2.7932237088680267
Epoch 15/100, Loss: 3.0441326797008514
Epoch 16/100, Loss: 2.9668832421302795
Epoch 17/100, Loss: 2.7273417487740517
Epoch 18/100, Loss: 3.174343705177307
Epoch 19/100, Loss: 2.7376217171549797
Epoch 20/100, Loss: 3.147294759750366
Epoch 21/100, Loss: 2.7477276250720024
Epoch 22/100, Loss: 2.8172657415270805
Epoch 23/100, Loss: 2.9956475347280502
Epoch 24/100, Loss: 2.8897750601172447
Epoch 25/100, Loss: 2.9239947348833084
Epoch 26/100, Loss: 3.059881702065468
Epoch 27/100, Loss: 2.946924425661564
Epoch 28/100, Loss: 2.8369186967611313
Epoch 29/100, Loss: 2.793608747422695
Epoch 30/100, Loss: 2.8078459054231644

Epoch 31/100, Loss: 3.0241686552762985
Epoch 32/100, Loss: 2.7010071128606796
Epoch 33/100, Loss: 2.7096399664878845
Epoch 34/100, Loss: 2.7928435802459717
Epoch 35/100, Loss: 2.7011498510837555
Epoch 36/100, Loss: 2.8809263110160828
Epoch 37/100, Loss: 2.914757713675499
Epoch 38/100, Loss: 2.8967480808496475
Epoch 39/100, Loss: 3.0961355417966843
Epoch 40/100, Loss: 2.8759089335799217
Epoch 41/100, Loss: 2.7632723599672318
Epoch 42/100, Loss: 2.7023247107863426
Epoch 43/100, Loss: 2.9091630429029465
Epoch 44/100, Loss: 2.8952011168003082
Epoch 45/100, Loss: 2.9183623045682907
Epoch 46/100, Loss: 2.9358411729335785
Epoch 47/100, Loss: 3.039269581437111

Epoch 48/100, Loss: 2.6273336187005043
Epoch 49/100, Loss: 3.007330536842346
Epoch 50/100, Loss: 3.080989897251129
Epoch 51/100, Loss: 3.0794434994459152
Epoch 52/100, Loss: 2.9119133353233337
Epoch 53/100, Loss: 2.9560037180781364
Epoch 54/100, Loss: 2.868828073143959
Epoch 55/100, Loss: 2.846837282180786
Epoch 56/100, Loss: 2.9094676226377487
Epoch 57/100, Loss: 2.747522532939911
Epoch 58/100, Loss: 2.7409989535808563
Epoch 59/100, Loss: 2.893196776509285
Epoch 60/100, Loss: 3.024896964430809
Epoch 61/100, Loss: 3.1854988262057304
Epoch 62/100, Loss: 2.8326840102672577
Epoch 63/100, Loss: 3.0003815293312073
Epoch 64/100, Loss: 2.8550995737314224
Epoch 65/100, Loss: 2.971591666340828

Epoch 66/100, Loss: 2.9902091175317764
Epoch 67/100, Loss: 2.9067598283290863
Epoch 68/100, Loss: 2.972569413483143
Epoch 69/100, Loss: 3.034905605018139
Epoch 70/100, Loss: 2.8536883518099785
Epoch 71/100, Loss: 2.995185635983944
Epoch 72/100, Loss: 2.8841214329004288
Epoch 73/100, Loss: 3.083922356367111
Epoch 74/100, Loss: 2.8796823918819427
Epoch 75/100, Loss: 2.8982683271169662
Epoch 76/100, Loss: 2.9200063049793243
Epoch 77/100, Loss: 2.8342673927545547
Epoch 78/100, Loss: 2.9362602531909943
Epoch 79/100, Loss: 2.827209174633026
Epoch 80/100, Loss: 3.0299170464277267
Epoch 81/100, Loss: 2.727018468081951
Epoch 82/100, Loss: 2.9811390936374664
Epoch 83/100, Loss: 2.7692444398999214

Epoch 84/100, Loss: 2.896260656416416
Epoch 85/100, Loss: 2.878194972872734
Epoch 86/100, Loss: 2.9395750761032104
Epoch 87/100, Loss: 2.8350622802972794
Epoch 88/100, Loss: 2.9460655599832535
Epoch 89/100, Loss: 3.072058320045471
Epoch 90/100, Loss: 2.7935170233249664
Epoch 91/100, Loss: 2.9992001056671143
Epoch 92/100, Loss: 2.9622403010725975
Epoch 93/100, Loss: 2.937581218779087
Epoch 94/100, Loss: 3.0307158157229424
Epoch 95/100, Loss: 3.1520219296216965
Epoch 96/100, Loss: 2.9948222041130066
Epoch 97/100, Loss: 2.7886072024703026
Epoch 98/100, Loss: 2.863723561167717
Epoch 99/100, Loss: 3.4126179441809654
Epoch 100/100, Loss: 2.9391247630119324
Fold 5/5 done

In [11]:
ap = average_precision_score(y_true, anomaly_scores)
print(f"Deep SVDD AP (5-fold CV) = {ap:.4f}")
sb.glue("GBG500_ap_spectral_deep_svdd", float(ap))

Deep SVDD AP (5-fold CV) = 0.4936