In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import average_precision_score
from sklearn.model_selection import StratifiedKFold
from pyod.models.deep_svdd import DeepSVDD
import sys
import scrapbook as sb

sys.path.append('..')
from utils import reshape_to_numpy, interpolate_missing_values, denoise_data, compute_spectrograms, time_avg_pooling

In [2]:
seed = 1
sampling_rate = 10
nperseg=64
noverlap=32
accel_cutoff = 0.4
accel_order = 30
gyro_cutoff = 0.6
gyro_order = 20
batch_size = 32
epochs = 100
hidden_neurons = [128, 64, 32]
n_splits = 5

In [3]:
# Parameters
seed = 14

In [4]:
rng = np.random.RandomState(seed)

In [5]:
data = pd.read_parquet("../data/GBG500.parquet")
data

,ride_id,time_index,ax,ay,az,rx,ry,rz
0,005043f1a7520cebf1e17fd166a00a3190e2433530f236...,0,-2.512796,-9.385012,-1.053078,-0.009155,0.009155,-0.201416
1,005043f1a7520cebf1e17fd166a00a3190e2433530f236...,100,-2.491268,-9.385012,-1.079390,-0.036621,0.027465,-0.155639
2,005043f1a7520cebf1e17fd166a00a3190e2433530f236...,200,-2.534324,-9.382022,-1.030952,0.036621,0.027465,-0.073242
3,005043f1a7520cebf1e17fd166a00a3190e2433530f236...,300,-2.488278,-9.383218,-1.091948,-0.045776,0.036621,-0.183105
4,005043f1a7520cebf1e17fd166a00a3190e2433530f236...,400,-2.483494,-9.382022,-1.100320,-0.045776,0.027465,-0.192260
...,...,...,...,...,...,...,...,...
1529542,ffb6f2f5dc6ba768d88dc0bc1af4cad235526aa9e24168...,241300,0.459862,-9.140430,-3.318900,1.556396,-0.091552,0.274658
1529543,ffb6f2f5dc6ba768d88dc0bc1af4cad235526aa9e24168...,241400,0.455676,-9.140430,-3.321292,1.583861,-0.119018,0.274658
1529544,ffb6f2f5dc6ba768d88dc0bc1af4cad235526aa9e24168...,241500,0.459862,-9.139832,-3.317704,1.583861,-0.109863,0.274658
1529545,ffb6f2f5dc6ba768d88dc0bc1af4cad235526aa9e24168...,241600,0.456274,-9.142224,-3.321292,1.574707,-0.137329,0.283813
1529546,ffb6f2f5dc6ba768d88dc0bc1af4cad235526aa9e24168...,241700,0.458666,-9.139832,-3.320694,1.574707,-0.137329,0.274658

In [6]:
labels = pd.read_csv("../data/GBG500_labels.csv")
labels.columns = labels.columns.str.lower()
ride_order_df = pd.DataFrame({"ride_id": data["ride_id"].unique()})
labels_sorted = ride_order_df.merge(
    labels,
    on="ride_id",
    how="left"
)
labels_sorted

                                               ride_id        label
0    005043f1a7520cebf1e17fd166a00a3190e2433530f236...         Safe
1    00d223cb7aecc9c0cc5871e32a6c45027a068eba07c572...     Reckless
2    02288a4aeca044203394e982e76b87818021dea2b34df9...         Safe
3    0236bdcf13d473ea24d97f5eaeea459f257dffac005694...  Bad weather
4    0238e5dd85143f1b6c59b200bc32f14361b8fc84c51a87...         Safe
..                                                 ...          ...
495  fe5d7f84d692bbccad8bd566a3ad5c3108fa9f90acd671...         Safe
496  fe67169632306d4668b2affedef510df2cb43e2fb41220...         Safe
497  fee44667fdc8ab4995c702fc3bd36178de0b1ca2c64687...         Safe
498  ff79b2e945b93c2a5efc3a06365267b3a160e7849ba57d...         Safe
499  ffb6f2f5dc6ba768d88dc0bc1af4cad235526aa9e24168...         Safe

[500 rows x 2 columns]

In [7]:
data_np = reshape_to_numpy(
    data,
    features = ["ax", "ay", "az", "rx", "ry", "rz"],
    max_timestamps = 4800
)

data_np_clean = interpolate_missing_values(
    data_np,
    method='linear',
    limit=None
)

data_np_clean = denoise_data(
    data=data_np_clean,
    accel_indices=[0, 1, 2],
    gyro_indices=[3, 4, 5],
    accel_cutoff=accel_cutoff,
    accel_order=accel_order,
    gyro_cutoff=gyro_cutoff,
    gyro_order=gyro_order,
)

In [8]:
# Compute spectrograms for all rides
spectrograms_array = compute_spectrograms(data_np_clean, sampling_rate, nperseg, noverlap)
spectrograms_array.shape

(500, 149, 6, 33)

In [9]:
# Aggregate spectrograms using time-averaged pooling
X_feat = time_avg_pooling(spectrograms_array)
X_feat.shape

(500, 198)

In [10]:
# 5-fold stratified CV with Deep SVDD
skf = StratifiedKFold(n_splits=n_splits, shuffle=True, random_state=rng.randint(1000))
y_true = (labels_sorted['label'] == 'Reckless').astype(int).values
anomaly_scores = np.full(len(y_true), np.nan)

for fold, (train_idx, test_idx) in enumerate(skf.split(X_feat, y_true)):
    sc = StandardScaler()
    X_train = sc.fit_transform(X_feat[train_idx])
    X_test = sc.transform(X_feat[test_idx])

    np.random.seed(rng.randint(1000))
    model = DeepSVDD(
        n_features=X_train.shape[1],
        hidden_neurons=hidden_neurons,
        epochs=epochs,
        batch_size=batch_size,
        random_state=rng.randint(1000),
    )
    model.fit(X_train)
    anomaly_scores[test_idx] = model.decision_function(X_test)
    print(f"Fold {fold+1}/{n_splits} done")

Epoch 1/100, Loss: 2.4426666498184204
Epoch 2/100, Loss: 2.608601853251457
Epoch 3/100, Loss: 2.5902160704135895
Epoch 4/100, Loss: 2.5618813782930374
Epoch 5/100, Loss: 2.631891056895256
Epoch 6/100, Loss: 2.637956030666828
Epoch 7/100, Loss: 2.616042733192444
Epoch 8/100, Loss: 2.450037993490696
Epoch 9/100, Loss: 2.946452982723713
Epoch 10/100, Loss: 2.6029019877314568
Epoch 11/100, Loss: 2.6086739227175713
Epoch 12/100, Loss: 2.463593363761902
Epoch 13/100, Loss: 2.486408054828644
Epoch 14/100, Loss: 2.7008191496133804

Epoch 15/100, Loss: 2.466580606997013
Epoch 16/100, Loss: 2.6656754687428474
Epoch 17/100, Loss: 2.575024664402008
Epoch 18/100, Loss: 2.5677152797579765
Epoch 19/100, Loss: 2.5226596891880035
Epoch 20/100, Loss: 2.4809425622224808
Epoch 21/100, Loss: 2.6371935531497
Epoch 22/100, Loss: 2.696437254548073
Epoch 23/100, Loss: 2.5583334490656853
Epoch 24/100, Loss: 2.6157729104161263
Epoch 25/100, Loss: 2.6852881386876106

Epoch 26/100, Loss: 2.6538574919104576
Epoch 27/100, Loss: 2.58663809299469
Epoch 28/100, Loss: 2.5691468566656113
Epoch 29/100, Loss: 2.480208098888397
Epoch 30/100, Loss: 2.6003874987363815
Epoch 31/100, Loss: 2.6029820889234543
Epoch 32/100, Loss: 2.5285900309681892
Epoch 33/100, Loss: 2.411407455801964
Epoch 34/100, Loss: 2.6274554058909416
Epoch 35/100, Loss: 2.6335165798664093
Epoch 36/100, Loss: 2.6856530904769897
Epoch 37/100, Loss: 2.531921550631523

Epoch 38/100, Loss: 2.457483872771263
Epoch 39/100, Loss: 2.5966762006282806
Epoch 40/100, Loss: 2.516511969268322
Epoch 41/100, Loss: 2.5109338387846947
Epoch 42/100, Loss: 2.668545126914978
Epoch 43/100, Loss: 2.5622042790055275
Epoch 44/100, Loss: 2.5229716449975967
Epoch 45/100, Loss: 2.6206256076693535
Epoch 46/100, Loss: 2.500844292342663
Epoch 47/100, Loss: 2.6514531821012497
Epoch 48/100, Loss: 2.568036139011383
Epoch 49/100, Loss: 2.5494880378246307
Epoch 50/100, Loss: 2.5031222254037857

Epoch 51/100, Loss: 2.6693407371640205
Epoch 52/100, Loss: 2.5849233344197273
Epoch 53/100, Loss: 2.618251569569111
Epoch 54/100, Loss: 2.3543727099895477
Epoch 55/100, Loss: 2.3260765448212624
Epoch 56/100, Loss: 2.526831716299057
Epoch 57/100, Loss: 2.486838199198246
Epoch 58/100, Loss: 2.651527613401413
Epoch 59/100, Loss: 2.529101699590683
Epoch 60/100, Loss: 2.5535852313041687
Epoch 61/100, Loss: 2.691743016242981
Epoch 62/100, Loss: 2.5449487194418907
Epoch 63/100, Loss: 2.6030604541301727
Epoch 64/100, Loss: 2.616456024348736
Epoch 65/100, Loss: 2.5750406682491302

Epoch 66/100, Loss: 2.690275698900223
Epoch 67/100, Loss: 2.613594703376293
Epoch 68/100, Loss: 2.5739569142460823
Epoch 69/100, Loss: 2.6361759454011917
Epoch 70/100, Loss: 2.4862426072359085
Epoch 71/100, Loss: 2.4709545746445656
Epoch 72/100, Loss: 3.0943876802921295
Epoch 73/100, Loss: 2.4606697410345078
Epoch 74/100, Loss: 2.4686145037412643
Epoch 75/100, Loss: 2.5557847023010254
Epoch 76/100, Loss: 2.615127556025982
Epoch 77/100, Loss: 2.5560515001416206
Epoch 78/100, Loss: 2.497788868844509
Epoch 79/100, Loss: 2.476018838584423
Epoch 80/100, Loss: 2.587979808449745

Epoch 81/100, Loss: 2.5030564069747925
Epoch 82/100, Loss: 2.588134802877903
Epoch 83/100, Loss: 2.485089987516403
Epoch 84/100, Loss: 2.637935161590576
Epoch 85/100, Loss: 2.537602946162224
Epoch 86/100, Loss: 2.498028129339218
Epoch 87/100, Loss: 2.6109579727053642
Epoch 88/100, Loss: 2.450122334063053
Epoch 89/100, Loss: 2.580076739192009
Epoch 90/100, Loss: 2.520221285521984
Epoch 91/100, Loss: 2.5978163555264473
Epoch 92/100, Loss: 2.6924272552132607
Epoch 93/100, Loss: 2.57845526188612
Epoch 94/100, Loss: 2.4510586112737656
Epoch 95/100, Loss: 2.634682483971119
Epoch 96/100, Loss: 2.695569135248661

Epoch 97/100, Loss: 2.6762245893478394
Epoch 98/100, Loss: 2.6275786757469177
Epoch 99/100, Loss: 2.4709243178367615
Epoch 100/100, Loss: 2.372426390647888
Fold 1/5 done
Epoch 1/100, Loss: 2.804963655769825
Epoch 2/100, Loss: 2.808381639420986
Epoch 3/100, Loss: 2.60467179864645
Epoch 4/100, Loss: 2.9044775515794754
Epoch 5/100, Loss: 2.7851492762565613
Epoch 6/100, Loss: 2.973475143313408
Epoch 7/100, Loss: 2.7384356781840324
Epoch 8/100, Loss: 2.9247263222932816
Epoch 9/100, Loss: 2.879259832203388
Epoch 10/100, Loss: 2.3020105063915253
Epoch 11/100, Loss: 2.6279167234897614

Epoch 12/100, Loss: 2.690968081355095
Epoch 13/100, Loss: 2.89240775257349
Epoch 14/100, Loss: 2.469385676085949
Epoch 15/100, Loss: 2.685308948159218
Epoch 16/100, Loss: 2.61955089867115
Epoch 17/100, Loss: 2.839220531284809
Epoch 18/100, Loss: 2.6766594126820564
Epoch 19/100, Loss: 2.8858702704310417
Epoch 20/100, Loss: 2.494925305247307
Epoch 21/100, Loss: 2.6162999644875526
Epoch 22/100, Loss: 2.671487018465996
Epoch 23/100, Loss: 2.893850088119507
Epoch 24/100, Loss: 2.7931639924645424
Epoch 25/100, Loss: 2.8778616189956665
Epoch 26/100, Loss: 2.5496466606855392

Epoch 27/100, Loss: 2.7154948711395264
Epoch 28/100, Loss: 2.769590303301811
Epoch 29/100, Loss: 2.813950337469578
Epoch 30/100, Loss: 2.5403600707650185
Epoch 31/100, Loss: 2.5954817682504654
Epoch 32/100, Loss: 2.730974391102791
Epoch 33/100, Loss: 2.733038477599621
Epoch 34/100, Loss: 2.8124023154377937
Epoch 35/100, Loss: 2.571252316236496
Epoch 36/100, Loss: 2.8754605278372765
Epoch 37/100, Loss: 3.093862473964691
Epoch 38/100, Loss: 2.6356659904122353
Epoch 39/100, Loss: 2.6384351328015327
Epoch 40/100, Loss: 2.88486947119236
Epoch 41/100, Loss: 2.629185065627098

Epoch 42/100, Loss: 2.8538855090737343
Epoch 43/100, Loss: 2.7117769569158554
Epoch 44/100, Loss: 2.7840046286582947
Epoch 45/100, Loss: 2.627015195786953
Epoch 46/100, Loss: 2.6611821055412292
Epoch 47/100, Loss: 2.551621451973915
Epoch 48/100, Loss: 2.5541709288954735
Epoch 49/100, Loss: 2.785832457244396
Epoch 50/100, Loss: 2.836390443146229
Epoch 51/100, Loss: 2.885863810777664
Epoch 52/100, Loss: 2.579604923725128
Epoch 53/100, Loss: 2.855658747255802
Epoch 54/100, Loss: 2.4568043872714043
Epoch 55/100, Loss: 2.9219009205698967
Epoch 56/100, Loss: 2.680375210940838

Epoch 57/100, Loss: 2.741954490542412
Epoch 58/100, Loss: 2.9413318559527397
Epoch 59/100, Loss: 2.6554424315690994
Epoch 60/100, Loss: 2.2807396724820137
Epoch 61/100, Loss: 2.7376167327165604
Epoch 62/100, Loss: 2.7003290951251984
Epoch 63/100, Loss: 2.736717641353607
Epoch 64/100, Loss: 2.8718650192022324
Epoch 65/100, Loss: 2.796227440237999
Epoch 66/100, Loss: 2.7513594776391983
Epoch 67/100, Loss: 2.7476716563105583
Epoch 68/100, Loss: 2.7213051468133926
Epoch 69/100, Loss: 2.8071464225649834
Epoch 70/100, Loss: 2.5693364664912224
Epoch 71/100, Loss: 2.656827598810196

Epoch 72/100, Loss: 2.6353013291954994
Epoch 73/100, Loss: 2.7049862816929817
Epoch 74/100, Loss: 2.461368590593338
Epoch 75/100, Loss: 2.5124833807349205
Epoch 76/100, Loss: 2.764551527798176
Epoch 77/100, Loss: 2.574294961988926
Epoch 78/100, Loss: 2.7525188997387886
Epoch 79/100, Loss: 2.677490718662739
Epoch 80/100, Loss: 2.8641209304332733
Epoch 81/100, Loss: 2.7036511227488518
Epoch 82/100, Loss: 2.5551595985889435
Epoch 83/100, Loss: 2.4877312555909157
Epoch 84/100, Loss: 2.8044364601373672
Epoch 85/100, Loss: 2.5314381644129753
Epoch 86/100, Loss: 2.5771286636590958

Epoch 87/100, Loss: 2.785586081445217
Epoch 88/100, Loss: 2.538870446383953
Epoch 89/100, Loss: 2.7356027588248253
Epoch 90/100, Loss: 2.5217459574341774
Epoch 91/100, Loss: 2.577597163617611
Epoch 92/100, Loss: 2.7937879785895348
Epoch 93/100, Loss: 2.7412290424108505
Epoch 94/100, Loss: 2.731364890933037
Epoch 95/100, Loss: 2.6828625947237015
Epoch 96/100, Loss: 2.4085037633776665
Epoch 97/100, Loss: 2.7614535614848137
Epoch 98/100, Loss: 2.7760001868009567
Epoch 99/100, Loss: 2.6258284151554108
Epoch 100/100, Loss: 2.470638729631901
Fold 2/5 done

Epoch 1/100, Loss: 2.4366756081581116
Epoch 2/100, Loss: 2.535406030714512
Epoch 3/100, Loss: 2.4691661596298218
Epoch 4/100, Loss: 2.5064386054873466
Epoch 5/100, Loss: 2.347194664180279
Epoch 6/100, Loss: 2.405923418700695
Epoch 7/100, Loss: 2.5781837850809097
Epoch 8/100, Loss: 2.4552192240953445
Epoch 9/100, Loss: 2.470640666782856
Epoch 10/100, Loss: 2.4745001047849655
Epoch 11/100, Loss: 2.4557111337780952
Epoch 12/100, Loss: 2.536790505051613
Epoch 13/100, Loss: 2.4884786307811737
Epoch 14/100, Loss: 2.5161316096782684
Epoch 15/100, Loss: 2.505627825856209

Epoch 16/100, Loss: 2.6693890541791916
Epoch 17/100, Loss: 2.4270349889993668
Epoch 18/100, Loss: 2.4929274320602417
Epoch 19/100, Loss: 2.4931860640645027
Epoch 20/100, Loss: 2.3979534953832626
Epoch 21/100, Loss: 2.5906223952770233
Epoch 22/100, Loss: 2.5082553923130035
Epoch 23/100, Loss: 2.409055471420288
Epoch 24/100, Loss: 2.531887613236904
Epoch 25/100, Loss: 2.5800261348485947
Epoch 26/100, Loss: 2.5093297213315964
Epoch 27/100, Loss: 2.479329265654087
Epoch 28/100, Loss: 2.501391179859638
Epoch 29/100, Loss: 2.911250539124012
Epoch 30/100, Loss: 2.508013926446438

Epoch 31/100, Loss: 2.5290164053440094
Epoch 32/100, Loss: 2.448316417634487
Epoch 33/100, Loss: 2.4253634810447693
Epoch 34/100, Loss: 2.5599215477705
Epoch 35/100, Loss: 2.4017502889037132
Epoch 36/100, Loss: 2.4495006129145622
Epoch 37/100, Loss: 2.3649676367640495
Epoch 38/100, Loss: 2.421187698841095
Epoch 39/100, Loss: 2.575943686068058
Epoch 40/100, Loss: 2.4169889092445374
Epoch 41/100, Loss: 2.636133998632431
Epoch 42/100, Loss: 2.458498515188694
Epoch 43/100, Loss: 2.5323318541049957
Epoch 44/100, Loss: 2.388411268591881
Epoch 45/100, Loss: 2.5443920344114304

Epoch 46/100, Loss: 2.4891498759388924
Epoch 47/100, Loss: 2.3333056196570396
Epoch 48/100, Loss: 2.503764621913433
Epoch 49/100, Loss: 2.4406510666012764
Epoch 50/100, Loss: 2.49343803524971
Epoch 51/100, Loss: 2.4146936759352684
Epoch 52/100, Loss: 2.51290699839592
Epoch 53/100, Loss: 2.5341088473796844
Epoch 54/100, Loss: 2.5847997441887856
Epoch 55/100, Loss: 2.519855260848999
Epoch 56/100, Loss: 2.4315334856510162
Epoch 57/100, Loss: 2.497873015701771
Epoch 58/100, Loss: 2.5205682888627052
Epoch 59/100, Loss: 2.3682801499962807
Epoch 60/100, Loss: 2.444194108247757

Epoch 61/100, Loss: 2.555265262722969
Epoch 62/100, Loss: 2.4248704463243484
Epoch 63/100, Loss: 2.479840725660324
Epoch 64/100, Loss: 2.45801555365324
Epoch 65/100, Loss: 2.5320530757308006
Epoch 66/100, Loss: 2.597877010703087
Epoch 67/100, Loss: 2.44382157176733
Epoch 68/100, Loss: 2.5228834226727486
Epoch 69/100, Loss: 2.4481930136680603
Epoch 70/100, Loss: 2.584785670042038
Epoch 71/100, Loss: 2.6501032188534737
Epoch 72/100, Loss: 2.48610620200634
Epoch 73/100, Loss: 2.46782149374485
Epoch 74/100, Loss: 2.582075133919716
Epoch 75/100, Loss: 2.5274292305111885

Epoch 76/100, Loss: 2.5663897916674614
Epoch 77/100, Loss: 2.44232390075922
Epoch 78/100, Loss: 2.4195885062217712
Epoch 79/100, Loss: 2.5490637123584747
Epoch 80/100, Loss: 2.6713435128331184
Epoch 81/100, Loss: 2.527917966246605
Epoch 82/100, Loss: 2.353005141019821
Epoch 83/100, Loss: 2.7023138776421547
Epoch 84/100, Loss: 2.695359967648983
Epoch 85/100, Loss: 2.5403058603405952
Epoch 86/100, Loss: 2.5514828115701675
Epoch 87/100, Loss: 2.474931038916111
Epoch 88/100, Loss: 2.4776254519820213
Epoch 89/100, Loss: 2.5146744921803474
Epoch 90/100, Loss: 2.55417550355196

Epoch 91/100, Loss: 2.502471312880516
Epoch 92/100, Loss: 2.4983739033341408
Epoch 93/100, Loss: 2.4925991892814636
Epoch 94/100, Loss: 2.563054472208023
Epoch 95/100, Loss: 2.4993880093097687
Epoch 96/100, Loss: 2.376354932785034
Epoch 97/100, Loss: 2.5302306413650513
Epoch 98/100, Loss: 2.427752174437046
Epoch 99/100, Loss: 2.4804814904928207
Epoch 100/100, Loss: 2.4093554615974426
Fold 3/5 done
Epoch 1/100, Loss: 2.9047188609838486
Epoch 2/100, Loss: 3.00610588490963
Epoch 3/100, Loss: 2.734479159116745
Epoch 4/100, Loss: 2.917658030986786

Epoch 5/100, Loss: 2.8835118636488914
Epoch 6/100, Loss: 2.801597975194454
Epoch 7/100, Loss: 2.862164728343487
Epoch 8/100, Loss: 2.834549032151699
Epoch 9/100, Loss: 2.7347549572587013
Epoch 10/100, Loss: 2.9530538767576218
Epoch 11/100, Loss: 2.954017475247383
Epoch 12/100, Loss: 2.9779650792479515
Epoch 13/100, Loss: 2.886599212884903
Epoch 14/100, Loss: 3.021311953663826
Epoch 15/100, Loss: 2.8263103365898132
Epoch 16/100, Loss: 2.8837647438049316
Epoch 17/100, Loss: 2.993462346494198
Epoch 18/100, Loss: 2.7617585957050323
Epoch 19/100, Loss: 2.9793366342782974

Epoch 20/100, Loss: 2.8771729692816734
Epoch 21/100, Loss: 2.8847064673900604
Epoch 22/100, Loss: 2.9229332134127617
Epoch 23/100, Loss: 2.822692610323429
Epoch 24/100, Loss: 2.7431208044290543
Epoch 25/100, Loss: 2.9308618530631065
Epoch 26/100, Loss: 2.959562234580517
Epoch 27/100, Loss: 2.7383091375231743
Epoch 28/100, Loss: 2.8240651041269302
Epoch 29/100, Loss: 3.062223143875599
Epoch 30/100, Loss: 2.9014324843883514
Epoch 31/100, Loss: 2.8527047485113144
Epoch 32/100, Loss: 2.820639505982399
Epoch 33/100, Loss: 2.8463174998760223
Epoch 34/100, Loss: 2.780085578560829

Epoch 35/100, Loss: 2.986306317150593
Epoch 36/100, Loss: 2.8828099444508553
Epoch 37/100, Loss: 2.890767440199852
Epoch 38/100, Loss: 2.990255333483219
Epoch 39/100, Loss: 2.8450523912906647
Epoch 40/100, Loss: 2.83726654201746
Epoch 41/100, Loss: 2.982913665473461
Epoch 42/100, Loss: 2.8275895714759827
Epoch 43/100, Loss: 2.9125013053417206
Epoch 44/100, Loss: 3.12620659917593
Epoch 45/100, Loss: 2.9333009719848633
Epoch 46/100, Loss: 2.845905415713787
Epoch 47/100, Loss: 2.8928245902061462
Epoch 48/100, Loss: 2.9954326450824738
Epoch 49/100, Loss: 2.976724646985531
Epoch 50/100, Loss: 2.8492333069443703
Epoch 51/100, Loss: 2.6996615901589394

Epoch 52/100, Loss: 2.9100586622953415
Epoch 53/100, Loss: 2.8217867389321327
Epoch 54/100, Loss: 2.965738944709301
Epoch 55/100, Loss: 2.962065950036049
Epoch 56/100, Loss: 3.0490569323301315
Epoch 57/100, Loss: 3.25006964802742
Epoch 58/100, Loss: 2.860904075205326
Epoch 59/100, Loss: 2.910513900220394
Epoch 60/100, Loss: 2.879270426928997
Epoch 61/100, Loss: 2.9822802990674973
Epoch 62/100, Loss: 2.973856672644615
Epoch 63/100, Loss: 2.9157626032829285
Epoch 64/100, Loss: 2.9049200415611267
Epoch 65/100, Loss: 3.0956043154001236
Epoch 66/100, Loss: 2.906506448984146
Epoch 67/100, Loss: 2.9337373301386833
Epoch 68/100, Loss: 2.779710106551647

Epoch 69/100, Loss: 2.7865521758794785
Epoch 70/100, Loss: 2.881694659590721
Epoch 71/100, Loss: 2.997689962387085
Epoch 72/100, Loss: 2.7956887260079384
Epoch 73/100, Loss: 3.0010693669319153
Epoch 74/100, Loss: 2.677526645362377
Epoch 75/100, Loss: 2.8570876494050026
Epoch 76/100, Loss: 2.930364467203617
Epoch 77/100, Loss: 2.91232617944479
Epoch 78/100, Loss: 2.813901051878929
Epoch 79/100, Loss: 3.071714870631695
Epoch 80/100, Loss: 3.055644616484642
Epoch 81/100, Loss: 2.8495154306292534
Epoch 82/100, Loss: 2.9056867361068726
Epoch 83/100, Loss: 2.9351143538951874

Epoch 84/100, Loss: 2.9250261038541794
Epoch 85/100, Loss: 2.9441117346286774
Epoch 86/100, Loss: 2.7936889827251434
Epoch 87/100, Loss: 2.964582495391369
Epoch 88/100, Loss: 2.8884263709187508
Epoch 89/100, Loss: 2.9198954701423645
Epoch 90/100, Loss: 2.8405522629618645
Epoch 91/100, Loss: 3.0006772950291634
Epoch 92/100, Loss: 2.93817900121212
Epoch 93/100, Loss: 2.860661081969738
Epoch 94/100, Loss: 2.7914643734693527
Epoch 95/100, Loss: 2.9689234122633934

Epoch 96/100, Loss: 3.0578708127141
Epoch 97/100, Loss: 2.9977409169077873
Epoch 98/100, Loss: 3.065604843199253
Epoch 99/100, Loss: 3.044529601931572
Epoch 100/100, Loss: 3.0660106539726257
Fold 4/5 done
Epoch 1/100, Loss: 2.1765248775482178
Epoch 2/100, Loss: 2.1578541547060013
Epoch 3/100, Loss: 2.1052590161561966
Epoch 4/100, Loss: 2.704017661511898
Epoch 5/100, Loss: 2.134036235511303

Epoch 6/100, Loss: 1.8556721359491348
Epoch 7/100, Loss: 2.1109198927879333
Epoch 8/100, Loss: 2.176115445792675
Epoch 9/100, Loss: 2.2442865148186684
Epoch 10/100, Loss: 2.3880404457449913
Epoch 11/100, Loss: 1.9642831683158875
Epoch 12/100, Loss: 2.0520403534173965
Epoch 13/100, Loss: 1.9584779664874077
Epoch 14/100, Loss: 2.076628290116787
Epoch 15/100, Loss: 2.152023531496525
Epoch 16/100, Loss: 2.632565550506115

Epoch 17/100, Loss: 1.8841624855995178
Epoch 18/100, Loss: 2.111700937151909
Epoch 19/100, Loss: 2.089124344289303
Epoch 20/100, Loss: 2.2096841521561146
Epoch 21/100, Loss: 1.9146865829825401
Epoch 22/100, Loss: 1.9093150608241558
Epoch 23/100, Loss: 2.1796270608901978
Epoch 24/100, Loss: 2.1417098343372345
Epoch 25/100, Loss: 2.297151640057564
Epoch 26/100, Loss: 2.1733956076204777
Epoch 27/100, Loss: 2.124841623008251
Epoch 28/100, Loss: 2.137786313891411
Epoch 29/100, Loss: 1.9678930714726448

Epoch 30/100, Loss: 2.170343339443207
Epoch 31/100, Loss: 2.216292627155781
Epoch 32/100, Loss: 2.0516935363411903
Epoch 33/100, Loss: 2.1305867582559586
Epoch 34/100, Loss: 2.126267835497856
Epoch 35/100, Loss: 2.167370520532131
Epoch 36/100, Loss: 2.1492114514112473
Epoch 37/100, Loss: 1.9032099172472954
Epoch 38/100, Loss: 1.9987109899520874
Epoch 39/100, Loss: 2.2356559485197067
Epoch 40/100, Loss: 2.353522799909115
Epoch 41/100, Loss: 2.1228377670049667
Epoch 42/100, Loss: 2.217687301337719
Epoch 43/100, Loss: 2.0478165671229362
Epoch 44/100, Loss: 2.066004306077957
Epoch 45/100, Loss: 2.088765934109688

Epoch 46/100, Loss: 2.1438718736171722
Epoch 47/100, Loss: 2.1868271082639694
Epoch 48/100, Loss: 2.009961064904928
Epoch 49/100, Loss: 2.1698475182056427
Epoch 50/100, Loss: 2.328298419713974
Epoch 51/100, Loss: 2.220586620271206
Epoch 52/100, Loss: 1.9495709538459778
Epoch 53/100, Loss: 2.189121685922146
Epoch 54/100, Loss: 2.133744701743126
Epoch 55/100, Loss: 2.270007811486721
Epoch 56/100, Loss: 2.2384551018476486
Epoch 57/100, Loss: 2.143809035420418
Epoch 58/100, Loss: 1.9191867485642433
Epoch 59/100, Loss: 2.096892476081848
Epoch 60/100, Loss: 1.987608090043068
Epoch 61/100, Loss: 2.214928977191448
Epoch 62/100, Loss: 2.52737570554018

Epoch 63/100, Loss: 2.1192757040262222
Epoch 64/100, Loss: 2.0524149164557457
Epoch 65/100, Loss: 2.1129558756947517
Epoch 66/100, Loss: 2.103533662855625
Epoch 67/100, Loss: 2.1681125164031982
Epoch 68/100, Loss: 1.9835579469799995
Epoch 69/100, Loss: 2.040022075176239
Epoch 70/100, Loss: 2.1089195385575294
Epoch 71/100, Loss: 2.2433940693736076
Epoch 72/100, Loss: 2.0917571410536766
Epoch 73/100, Loss: 2.0287961140275
Epoch 74/100, Loss: 1.89654341340065
Epoch 75/100, Loss: 2.0613269731402397
Epoch 76/100, Loss: 2.1451771780848503
Epoch 77/100, Loss: 2.078535333275795
Epoch 78/100, Loss: 2.1128569319844246
Epoch 79/100, Loss: 1.9845228046178818

Epoch 80/100, Loss: 2.258721563965082
Epoch 81/100, Loss: 2.1533425599336624
Epoch 82/100, Loss: 2.0134895890951157
Epoch 83/100, Loss: 1.9264230355620384
Epoch 84/100, Loss: 2.6590181291103363
Epoch 85/100, Loss: 1.9948744177818298
Epoch 86/100, Loss: 2.131309397518635
Epoch 87/100, Loss: 2.0955545976758003
Epoch 88/100, Loss: 2.1932923644781113
Epoch 89/100, Loss: 2.1611455604434013
Epoch 90/100, Loss: 1.9370846524834633
Epoch 91/100, Loss: 2.1689850240945816
Epoch 92/100, Loss: 2.0426853597164154
Epoch 93/100, Loss: 1.9128656163811684
Epoch 94/100, Loss: 2.033068284392357
Epoch 95/100, Loss: 2.2448842003941536
Epoch 96/100, Loss: 1.9683327078819275

Epoch 97/100, Loss: 2.0151682272553444
Epoch 98/100, Loss: 1.8863408118486404
Epoch 99/100, Loss: 2.1496087685227394
Epoch 100/100, Loss: 1.9495989754796028
Fold 5/5 done

In [11]:
ap = average_precision_score(y_true, anomaly_scores)
print(f"Deep SVDD AP (5-fold CV) = {ap:.4f}")
sb.glue("GBG500_ap_spectral_deep_svdd", float(ap))

Deep SVDD AP (5-fold CV) = 0.4886