In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import average_precision_score
from sklearn.model_selection import StratifiedKFold
from pyod.models.deep_svdd import DeepSVDD
import sys
import scrapbook as sb

sys.path.append('..')
from utils import reshape_to_numpy, interpolate_missing_values, denoise_data, compute_spectrograms, time_avg_pooling

In [2]:
seed = 1
sampling_rate = 10
nperseg=64
noverlap=32
accel_cutoff = 0.4
accel_order = 30
gyro_cutoff = 0.6
gyro_order = 20
batch_size = 32
epochs = 100
hidden_neurons = [128, 64, 32]
n_splits = 5

In [3]:
# Parameters
seed = 5

In [4]:
rng = np.random.RandomState(seed)

In [5]:
data = pd.read_parquet("../data/GBG500.parquet")
data

,ride_id,time_index,ax,ay,az,rx,ry,rz
0,005043f1a7520cebf1e17fd166a00a3190e2433530f236...,0,-2.512796,-9.385012,-1.053078,-0.009155,0.009155,-0.201416
1,005043f1a7520cebf1e17fd166a00a3190e2433530f236...,100,-2.491268,-9.385012,-1.079390,-0.036621,0.027465,-0.155639
2,005043f1a7520cebf1e17fd166a00a3190e2433530f236...,200,-2.534324,-9.382022,-1.030952,0.036621,0.027465,-0.073242
3,005043f1a7520cebf1e17fd166a00a3190e2433530f236...,300,-2.488278,-9.383218,-1.091948,-0.045776,0.036621,-0.183105
4,005043f1a7520cebf1e17fd166a00a3190e2433530f236...,400,-2.483494,-9.382022,-1.100320,-0.045776,0.027465,-0.192260
...,...,...,...,...,...,...,...,...
1529542,ffb6f2f5dc6ba768d88dc0bc1af4cad235526aa9e24168...,241300,0.459862,-9.140430,-3.318900,1.556396,-0.091552,0.274658
1529543,ffb6f2f5dc6ba768d88dc0bc1af4cad235526aa9e24168...,241400,0.455676,-9.140430,-3.321292,1.583861,-0.119018,0.274658
1529544,ffb6f2f5dc6ba768d88dc0bc1af4cad235526aa9e24168...,241500,0.459862,-9.139832,-3.317704,1.583861,-0.109863,0.274658
1529545,ffb6f2f5dc6ba768d88dc0bc1af4cad235526aa9e24168...,241600,0.456274,-9.142224,-3.321292,1.574707,-0.137329,0.283813
1529546,ffb6f2f5dc6ba768d88dc0bc1af4cad235526aa9e24168...,241700,0.458666,-9.139832,-3.320694,1.574707,-0.137329,0.274658

In [6]:
labels = pd.read_csv("../data/GBG500_labels.csv")
labels.columns = labels.columns.str.lower()
ride_order_df = pd.DataFrame({"ride_id": data["ride_id"].unique()})
labels_sorted = ride_order_df.merge(
    labels,
    on="ride_id",
    how="left"
)
labels_sorted

                                               ride_id        label
0    005043f1a7520cebf1e17fd166a00a3190e2433530f236...         Safe
1    00d223cb7aecc9c0cc5871e32a6c45027a068eba07c572...     Reckless
2    02288a4aeca044203394e982e76b87818021dea2b34df9...         Safe
3    0236bdcf13d473ea24d97f5eaeea459f257dffac005694...  Bad weather
4    0238e5dd85143f1b6c59b200bc32f14361b8fc84c51a87...         Safe
..                                                 ...          ...
495  fe5d7f84d692bbccad8bd566a3ad5c3108fa9f90acd671...         Safe
496  fe67169632306d4668b2affedef510df2cb43e2fb41220...         Safe
497  fee44667fdc8ab4995c702fc3bd36178de0b1ca2c64687...         Safe
498  ff79b2e945b93c2a5efc3a06365267b3a160e7849ba57d...         Safe
499  ffb6f2f5dc6ba768d88dc0bc1af4cad235526aa9e24168...         Safe

[500 rows x 2 columns]

In [7]:
data_np = reshape_to_numpy(
    data,
    features = ["ax", "ay", "az", "rx", "ry", "rz"],
    max_timestamps = 4800
)

data_np_clean = interpolate_missing_values(
    data_np,
    method='linear',
    limit=None
)

data_np_clean = denoise_data(
    data=data_np_clean,
    accel_indices=[0, 1, 2],
    gyro_indices=[3, 4, 5],
    accel_cutoff=accel_cutoff,
    accel_order=accel_order,
    gyro_cutoff=gyro_cutoff,
    gyro_order=gyro_order,
)

In [8]:
# Compute spectrograms for all rides
spectrograms_array = compute_spectrograms(data_np_clean, sampling_rate, nperseg, noverlap)
spectrograms_array.shape

(500, 149, 6, 33)

In [9]:
# Aggregate spectrograms using time-averaged pooling
X_feat = time_avg_pooling(spectrograms_array)
X_feat.shape

(500, 198)

In [10]:
# 5-fold stratified CV with Deep SVDD
skf = StratifiedKFold(n_splits=n_splits, shuffle=True, random_state=rng.randint(1000))
y_true = (labels_sorted['label'] == 'Reckless').astype(int).values
anomaly_scores = np.full(len(y_true), np.nan)

for fold, (train_idx, test_idx) in enumerate(skf.split(X_feat, y_true)):
    sc = StandardScaler()
    X_train = sc.fit_transform(X_feat[train_idx])
    X_test = sc.transform(X_feat[test_idx])

    np.random.seed(rng.randint(1000))
    model = DeepSVDD(
        n_features=X_train.shape[1],
        hidden_neurons=hidden_neurons,
        epochs=epochs,
        batch_size=batch_size,
        random_state=rng.randint(1000),
    )
    model.fit(X_train)
    anomaly_scores[test_idx] = model.decision_function(X_test)
    print(f"Fold {fold+1}/{n_splits} done")

Epoch 1/100, Loss: 1.6262583881616592
Epoch 2/100, Loss: 1.7118563428521156
Epoch 3/100, Loss: 1.6691074073314667
Epoch 4/100, Loss: 1.7657701894640923
Epoch 5/100, Loss: 1.7789205946028233
Epoch 6/100, Loss: 1.614033356308937
Epoch 7/100, Loss: 1.6438283994793892
Epoch 8/100, Loss: 1.6657912135124207
Epoch 9/100, Loss: 1.5589835792779922
Epoch 10/100, Loss: 1.6175701692700386
Epoch 11/100, Loss: 1.6457806900143623
Epoch 12/100, Loss: 1.6617464870214462
Epoch 13/100, Loss: 1.6706591919064522
Epoch 14/100, Loss: 1.7715276703238487
Epoch 15/100, Loss: 1.693850614130497
Epoch 16/100, Loss: 1.622896820306778

Epoch 17/100, Loss: 1.7082300707697868
Epoch 18/100, Loss: 1.6378674507141113
Epoch 19/100, Loss: 1.676350198686123
Epoch 20/100, Loss: 1.6708998084068298
Epoch 21/100, Loss: 1.6171588376164436
Epoch 22/100, Loss: 1.6656839177012444
Epoch 23/100, Loss: 1.653546191751957
Epoch 24/100, Loss: 1.6632384955883026
Epoch 25/100, Loss: 1.6626197844743729
Epoch 26/100, Loss: 1.720491923391819
Epoch 27/100, Loss: 1.6637282818555832
Epoch 28/100, Loss: 1.5871332809329033
Epoch 29/100, Loss: 1.6709652990102768
Epoch 30/100, Loss: 1.6565144807100296
Epoch 31/100, Loss: 1.7219942286610603
Epoch 32/100, Loss: 1.688039056956768
Epoch 33/100, Loss: 1.6519825533032417

Epoch 34/100, Loss: 1.6566752567887306
Epoch 35/100, Loss: 1.708702053874731
Epoch 36/100, Loss: 1.718976803123951
Epoch 37/100, Loss: 1.6605894342064857
Epoch 38/100, Loss: 1.63645950704813
Epoch 39/100, Loss: 1.7132385596632957
Epoch 40/100, Loss: 1.6856501623988152
Epoch 41/100, Loss: 1.6613697856664658
Epoch 42/100, Loss: 1.6163360923528671
Epoch 43/100, Loss: 1.6704741194844246
Epoch 44/100, Loss: 1.6413547992706299
Epoch 45/100, Loss: 1.6098841801285744

Epoch 46/100, Loss: 1.5722157768905163
Epoch 47/100, Loss: 1.5966141819953918
Epoch 48/100, Loss: 1.6452529430389404
Epoch 49/100, Loss: 1.6848254650831223
Epoch 50/100, Loss: 1.7064484655857086
Epoch 51/100, Loss: 1.5910964608192444
Epoch 52/100, Loss: 1.6939346119761467
Epoch 53/100, Loss: 1.719371072947979
Epoch 54/100, Loss: 1.6264567375183105
Epoch 55/100, Loss: 1.6337088197469711
Epoch 56/100, Loss: 1.7079849019646645
Epoch 57/100, Loss: 1.6548756025731564
Epoch 58/100, Loss: 1.7335083931684494
Epoch 59/100, Loss: 1.6653303802013397
Epoch 60/100, Loss: 1.6426807418465614

Epoch 61/100, Loss: 1.856975071132183
Epoch 62/100, Loss: 1.72404994815588
Epoch 63/100, Loss: 1.6682732999324799
Epoch 64/100, Loss: 1.7441477328538895
Epoch 65/100, Loss: 1.60919239372015
Epoch 66/100, Loss: 1.6432043761014938
Epoch 67/100, Loss: 1.658076211810112
Epoch 68/100, Loss: 1.6577771976590157
Epoch 69/100, Loss: 1.6465725153684616
Epoch 70/100, Loss: 1.6426509767770767
Epoch 71/100, Loss: 1.6790865361690521
Epoch 72/100, Loss: 1.6045178323984146
Epoch 73/100, Loss: 1.7144941911101341
Epoch 74/100, Loss: 1.667393058538437
Epoch 75/100, Loss: 1.636790670454502

Epoch 76/100, Loss: 1.6399383321404457
Epoch 77/100, Loss: 1.5740111023187637
Epoch 78/100, Loss: 1.6374504044651985
Epoch 79/100, Loss: 1.6763340905308723
Epoch 80/100, Loss: 1.6461377143859863
Epoch 81/100, Loss: 1.6423450708389282
Epoch 82/100, Loss: 1.6476077698171139
Epoch 83/100, Loss: 1.6259282752871513
Epoch 84/100, Loss: 1.6667393818497658
Epoch 85/100, Loss: 1.6541729047894478
Epoch 86/100, Loss: 1.6688442453742027
Epoch 87/100, Loss: 1.665064424276352
Epoch 88/100, Loss: 1.7056047841906548
Epoch 89/100, Loss: 1.683096133172512
Epoch 90/100, Loss: 1.6325020492076874

Epoch 91/100, Loss: 1.6676532104611397
Epoch 92/100, Loss: 1.656669095158577
Epoch 93/100, Loss: 1.618507906794548
Epoch 94/100, Loss: 1.5670668929815292
Epoch 95/100, Loss: 1.72007405012846
Epoch 96/100, Loss: 1.6239540241658688
Epoch 97/100, Loss: 1.6740191206336021
Epoch 98/100, Loss: 1.5835044905543327
Epoch 99/100, Loss: 1.6207795217633247
Epoch 100/100, Loss: 1.7074934765696526
Fold 1/5 done
Epoch 1/100, Loss: 1.7201940640807152

Epoch 2/100, Loss: 1.677994228899479
Epoch 3/100, Loss: 1.8584665656089783
Epoch 4/100, Loss: 1.6703444421291351
Epoch 5/100, Loss: 1.8282892629504204
Epoch 6/100, Loss: 1.7688500210642815
Epoch 7/100, Loss: 1.7979887872934341
Epoch 8/100, Loss: 1.9452391788363457
Epoch 9/100, Loss: 1.9493429139256477
Epoch 10/100, Loss: 1.7640504464507103
Epoch 11/100, Loss: 1.83042349293828
Epoch 12/100, Loss: 1.7949763499200344
Epoch 13/100, Loss: 1.8029685765504837

Epoch 14/100, Loss: 1.7006356492638588
Epoch 15/100, Loss: 1.9184931069612503
Epoch 16/100, Loss: 1.764336034655571
Epoch 17/100, Loss: 1.6827510073781013
Epoch 18/100, Loss: 1.6419643945991993
Epoch 19/100, Loss: 1.6299412697553635
Epoch 20/100, Loss: 1.7776850163936615
Epoch 21/100, Loss: 1.7265292555093765
Epoch 22/100, Loss: 1.7770855352282524
Epoch 23/100, Loss: 1.711243785917759
Epoch 24/100, Loss: 1.6963629499077797
Epoch 25/100, Loss: 1.8527290970087051
Epoch 26/100, Loss: 1.72084229439497

Epoch 27/100, Loss: 1.804517149925232
Epoch 28/100, Loss: 1.698473021388054
Epoch 29/100, Loss: 1.6684983633458614
Epoch 30/100, Loss: 1.684726171195507
Epoch 31/100, Loss: 2.2200616002082825
Epoch 32/100, Loss: 1.694419339299202
Epoch 33/100, Loss: 1.8807911425828934
Epoch 34/100, Loss: 2.164550729095936
Epoch 35/100, Loss: 2.0294188410043716
Epoch 36/100, Loss: 1.9408070221543312
Epoch 37/100, Loss: 1.7584844529628754
Epoch 38/100, Loss: 1.776718184351921
Epoch 39/100, Loss: 1.9609556421637535
Epoch 40/100, Loss: 1.7582990899682045
Epoch 41/100, Loss: 1.6283274292945862
Epoch 42/100, Loss: 1.8618099614977837

Epoch 43/100, Loss: 1.954761192202568
Epoch 44/100, Loss: 1.6780650615692139
Epoch 45/100, Loss: 1.6873361729085445
Epoch 46/100, Loss: 1.881032805889845
Epoch 47/100, Loss: 1.6560705825686455
Epoch 48/100, Loss: 1.9195157811045647
Epoch 49/100, Loss: 1.7401183024048805
Epoch 50/100, Loss: 1.695175625383854
Epoch 51/100, Loss: 1.7084899544715881
Epoch 52/100, Loss: 1.8659333288669586
Epoch 53/100, Loss: 1.8064290508627892
Epoch 54/100, Loss: 1.804192192852497
Epoch 55/100, Loss: 1.6315941512584686
Epoch 56/100, Loss: 1.7628471851348877
Epoch 57/100, Loss: 1.6228845044970512
Epoch 58/100, Loss: 1.6822652146220207
Epoch 59/100, Loss: 1.7136010229587555

Epoch 60/100, Loss: 1.7074565589427948
Epoch 61/100, Loss: 1.7095717303454876
Epoch 62/100, Loss: 1.7184985652565956
Epoch 63/100, Loss: 1.7392080053687096
Epoch 64/100, Loss: 1.9427009150385857
Epoch 65/100, Loss: 1.9084642305970192
Epoch 66/100, Loss: 1.8354038447141647
Epoch 67/100, Loss: 2.41349920630455
Epoch 68/100, Loss: 1.706662230193615
Epoch 69/100, Loss: 1.8073745667934418
Epoch 70/100, Loss: 1.794882521033287
Epoch 71/100, Loss: 1.8854589238762856
Epoch 72/100, Loss: 1.815037116408348
Epoch 73/100, Loss: 1.780656859278679
Epoch 74/100, Loss: 1.6370208710432053
Epoch 75/100, Loss: 1.886983908712864
Epoch 76/100, Loss: 1.5624331384897232

Epoch 77/100, Loss: 1.6779446229338646
Epoch 78/100, Loss: 1.843202631920576
Epoch 79/100, Loss: 1.8861626610159874
Epoch 80/100, Loss: 1.7796027287840843
Epoch 81/100, Loss: 1.790534295141697
Epoch 82/100, Loss: 1.7468604147434235
Epoch 83/100, Loss: 1.9057983830571175
Epoch 84/100, Loss: 1.6740814670920372
Epoch 85/100, Loss: 1.7797354608774185
Epoch 86/100, Loss: 1.6980616077780724
Epoch 87/100, Loss: 1.724639505147934
Epoch 88/100, Loss: 1.7246708869934082
Epoch 89/100, Loss: 1.7536057382822037
Epoch 90/100, Loss: 1.7478594332933426
Epoch 91/100, Loss: 1.8967861384153366
Epoch 92/100, Loss: 1.8274218812584877
Epoch 93/100, Loss: 1.74135123193264

Epoch 94/100, Loss: 1.710200309753418
Epoch 95/100, Loss: 1.8199098110198975
Epoch 96/100, Loss: 1.7733025215566158
Epoch 97/100, Loss: 2.164954401552677
Epoch 98/100, Loss: 1.5940546616911888
Epoch 99/100, Loss: 1.874594859778881
Epoch 100/100, Loss: 1.6840215399861336
Fold 2/5 done
Epoch 1/100, Loss: 1.7097668275237083
Epoch 2/100, Loss: 1.67922243475914
Epoch 3/100, Loss: 1.7650889083743095
Epoch 4/100, Loss: 1.6401942744851112
Epoch 5/100, Loss: 1.8348868638277054
Epoch 6/100, Loss: 1.6129018366336823
Epoch 7/100, Loss: 1.9075289145112038
Epoch 8/100, Loss: 1.7572222799062729

Epoch 9/100, Loss: 1.7706160247325897
Epoch 10/100, Loss: 1.6583452671766281
Epoch 11/100, Loss: 1.685657560825348
Epoch 12/100, Loss: 1.7521193325519562
Epoch 13/100, Loss: 2.0324011594057083
Epoch 14/100, Loss: 1.6424671486020088
Epoch 15/100, Loss: 1.7506057545542717
Epoch 16/100, Loss: 1.7251298055052757
Epoch 17/100, Loss: 1.7347776517271996
Epoch 18/100, Loss: 1.7338363155722618
Epoch 19/100, Loss: 1.7054802179336548
Epoch 20/100, Loss: 1.8501134291291237
Epoch 21/100, Loss: 1.7264286205172539
Epoch 22/100, Loss: 1.7608079388737679
Epoch 23/100, Loss: 1.6718403920531273
Epoch 24/100, Loss: 1.5477750301361084

Epoch 25/100, Loss: 1.6662798002362251
Epoch 26/100, Loss: 1.7336193546652794
Epoch 27/100, Loss: 1.6864157393574715
Epoch 28/100, Loss: 1.795316331088543
Epoch 29/100, Loss: 1.8031939715147018
Epoch 30/100, Loss: 1.6831027492880821
Epoch 31/100, Loss: 1.7384791746735573
Epoch 32/100, Loss: 1.8441956788301468
Epoch 33/100, Loss: 1.6876760423183441
Epoch 34/100, Loss: 1.6567306742072105
Epoch 35/100, Loss: 1.7988622188568115
Epoch 36/100, Loss: 1.7318136468529701
Epoch 37/100, Loss: 1.746334120631218
Epoch 38/100, Loss: 1.7037976458668709
Epoch 39/100, Loss: 1.7473026886582375
Epoch 40/100, Loss: 1.5404453948140144
Epoch 41/100, Loss: 1.7350877150893211

Epoch 42/100, Loss: 1.6051807925105095
Epoch 43/100, Loss: 1.659195862710476
Epoch 44/100, Loss: 1.7263615727424622
Epoch 45/100, Loss: 1.7472793385386467
Epoch 46/100, Loss: 1.7514501959085464
Epoch 47/100, Loss: 1.7191285640001297
Epoch 48/100, Loss: 1.744713045656681
Epoch 49/100, Loss: 1.7766089588403702
Epoch 50/100, Loss: 1.7425543516874313
Epoch 51/100, Loss: 1.6249261274933815
Epoch 52/100, Loss: 1.799486666917801
Epoch 53/100, Loss: 1.6606015413999557
Epoch 54/100, Loss: 1.8749313354492188
Epoch 55/100, Loss: 1.6283885687589645
Epoch 56/100, Loss: 1.7008459717035294
Epoch 57/100, Loss: 1.7527644634246826

Epoch 58/100, Loss: 1.7039507031440735
Epoch 59/100, Loss: 1.7796081975102425
Epoch 60/100, Loss: 1.7110477164387703
Epoch 61/100, Loss: 1.6180741041898727
Epoch 62/100, Loss: 1.6945418640971184
Epoch 63/100, Loss: 1.6422584801912308
Epoch 64/100, Loss: 1.7209217101335526
Epoch 65/100, Loss: 1.7148905992507935
Epoch 66/100, Loss: 1.7514493316411972
Epoch 67/100, Loss: 1.7511379271745682
Epoch 68/100, Loss: 1.7187142744660378
Epoch 69/100, Loss: 1.603542760014534
Epoch 70/100, Loss: 1.8266077935695648
Epoch 71/100, Loss: 1.7739709243178368
Epoch 72/100, Loss: 1.8097053691744804
Epoch 73/100, Loss: 1.778779849410057
Epoch 74/100, Loss: 1.676283836364746

Epoch 75/100, Loss: 1.8352786153554916
Epoch 76/100, Loss: 1.735133908689022
Epoch 77/100, Loss: 1.5894839763641357
Epoch 78/100, Loss: 1.5926487371325493
Epoch 79/100, Loss: 1.7275677248835564
Epoch 80/100, Loss: 1.6648980602622032
Epoch 81/100, Loss: 1.7786540612578392
Epoch 82/100, Loss: 1.7621446624398232
Epoch 83/100, Loss: 2.0282807797193527
Epoch 84/100, Loss: 1.6591475680470467
Epoch 85/100, Loss: 1.8596636354923248
Epoch 86/100, Loss: 1.8077082186937332
Epoch 87/100, Loss: 1.7209100276231766
Epoch 88/100, Loss: 1.7466299682855606
Epoch 89/100, Loss: 1.6745998188853264
Epoch 90/100, Loss: 1.6971253380179405
Epoch 91/100, Loss: 1.6992875933647156

Epoch 92/100, Loss: 1.7594401463866234
Epoch 93/100, Loss: 1.8377477079629898
Epoch 94/100, Loss: 1.8441234976053238
Epoch 95/100, Loss: 1.7031569629907608
Epoch 96/100, Loss: 1.640607662498951
Epoch 97/100, Loss: 1.7385154739022255
Epoch 98/100, Loss: 1.6384360417723656
Epoch 99/100, Loss: 1.6931485682725906
Epoch 100/100, Loss: 1.7703700363636017
Fold 3/5 done
Epoch 1/100, Loss: 1.2252210043370724
Epoch 2/100, Loss: 1.4395388513803482
Epoch 3/100, Loss: 1.5643202066421509
Epoch 4/100, Loss: 1.297182533890009

Epoch 5/100, Loss: 1.3779999390244484
Epoch 6/100, Loss: 1.225589457899332
Epoch 7/100, Loss: 1.345872737467289
Epoch 8/100, Loss: 1.3255991898477077
Epoch 9/100, Loss: 1.2377565670758486
Epoch 10/100, Loss: 1.2610777467489243
Epoch 11/100, Loss: 1.1607345752418041
Epoch 12/100, Loss: 1.3245160952210426
Epoch 13/100, Loss: 1.875754676759243
Epoch 14/100, Loss: 1.2630491852760315
Epoch 15/100, Loss: 1.5326829962432384
Epoch 16/100, Loss: 1.2719814106822014
Epoch 17/100, Loss: 1.4452787674963474
Epoch 18/100, Loss: 2.025837827473879
Epoch 19/100, Loss: 1.201153427362442
Epoch 20/100, Loss: 1.346801795065403
Epoch 21/100, Loss: 1.3151488155126572
Epoch 22/100, Loss: 1.2933766804635525

Epoch 23/100, Loss: 1.3328612633049488
Epoch 24/100, Loss: 1.3321823850274086
Epoch 25/100, Loss: 1.4194399826228619
Epoch 26/100, Loss: 1.191424559801817
Epoch 27/100, Loss: 2.108004529029131
Epoch 28/100, Loss: 1.308384019881487
Epoch 29/100, Loss: 1.2933040335774422
Epoch 30/100, Loss: 1.192739624530077
Epoch 31/100, Loss: 1.4182400740683079
Epoch 32/100, Loss: 1.2825503312051296
Epoch 33/100, Loss: 1.3619047105312347
Epoch 34/100, Loss: 1.2230328470468521

Epoch 35/100, Loss: 1.5184494704008102
Epoch 36/100, Loss: 1.3272279351949692
Epoch 37/100, Loss: 1.3898146860301495
Epoch 38/100, Loss: 1.5348223708570004
Epoch 39/100, Loss: 1.2535291351377964
Epoch 40/100, Loss: 1.365864846855402
Epoch 41/100, Loss: 1.2809204123914242
Epoch 42/100, Loss: 1.3741830848157406
Epoch 43/100, Loss: 1.443978302180767
Epoch 44/100, Loss: 1.4960669204592705
Epoch 45/100, Loss: 1.5444908365607262
Epoch 46/100, Loss: 1.2440038919448853
Epoch 47/100, Loss: 1.231073435395956
Epoch 48/100, Loss: 1.3675649911165237

Epoch 49/100, Loss: 1.230352509766817
Epoch 50/100, Loss: 1.4487022459506989
Epoch 51/100, Loss: 1.2336603254079819
Epoch 52/100, Loss: 1.2475543320178986
Epoch 53/100, Loss: 1.385184671729803
Epoch 54/100, Loss: 1.089463021606207
Epoch 55/100, Loss: 1.326839618384838
Epoch 56/100, Loss: 1.0502823367714882
Epoch 57/100, Loss: 1.3297000341117382
Epoch 58/100, Loss: 1.1575791202485561
Epoch 59/100, Loss: 2.0686109997332096
Epoch 60/100, Loss: 1.4351069182157516

Epoch 61/100, Loss: 1.3495663292706013
Epoch 62/100, Loss: 1.3110437504947186
Epoch 63/100, Loss: 1.2017454020678997
Epoch 64/100, Loss: 1.534561948850751
Epoch 65/100, Loss: 1.3522702790796757
Epoch 66/100, Loss: 1.3733744751662016
Epoch 67/100, Loss: 1.2365781143307686
Epoch 68/100, Loss: 1.3955807127058506
Epoch 69/100, Loss: 1.161699578166008
Epoch 70/100, Loss: 1.1042367722839117
Epoch 71/100, Loss: 1.2627056539058685
Epoch 72/100, Loss: 1.4221051149070263
Epoch 73/100, Loss: 1.3124714009463787
Epoch 74/100, Loss: 1.1499351188540459
Epoch 75/100, Loss: 1.3248918019235134
Epoch 76/100, Loss: 1.2226662375032902

Epoch 77/100, Loss: 1.476768247783184
Epoch 78/100, Loss: 1.238289125263691
Epoch 79/100, Loss: 1.538784597069025
Epoch 80/100, Loss: 1.4713048823177814
Epoch 81/100, Loss: 1.2367342375218868
Epoch 82/100, Loss: 1.3643938414752483
Epoch 83/100, Loss: 1.2854782454669476
Epoch 84/100, Loss: 1.2806873470544815
Epoch 85/100, Loss: 1.2507324498146772
Epoch 86/100, Loss: 1.2710048630833626
Epoch 87/100, Loss: 1.3830627351999283
Epoch 88/100, Loss: 1.3864149115979671
Epoch 89/100, Loss: 1.227469276636839
Epoch 90/100, Loss: 1.3235086761415005
Epoch 91/100, Loss: 1.3875170443207026
Epoch 92/100, Loss: 1.2876505330204964
Epoch 93/100, Loss: 1.2082754913717508
Epoch 94/100, Loss: 1.0923693962395191

Epoch 95/100, Loss: 1.2662492021918297
Epoch 96/100, Loss: 1.2255029678344727
Epoch 97/100, Loss: 1.5683940052986145
Epoch 98/100, Loss: 1.2768807336688042
Epoch 99/100, Loss: 1.3952314034104347
Epoch 100/100, Loss: 1.7896736487746239
Fold 4/5 done
Epoch 1/100, Loss: 2.714586965739727
Epoch 2/100, Loss: 2.577907554805279
Epoch 3/100, Loss: 2.766246013343334
Epoch 4/100, Loss: 2.727697364985943
Epoch 5/100, Loss: 2.653543181717396
Epoch 6/100, Loss: 2.731655053794384
Epoch 7/100, Loss: 2.7956819757819176
Epoch 8/100, Loss: 2.4597772508859634
Epoch 9/100, Loss: 2.415614075958729

Epoch 10/100, Loss: 2.7570593655109406
Epoch 11/100, Loss: 2.7863230407238007
Epoch 12/100, Loss: 2.7780494391918182
Epoch 13/100, Loss: 2.583355352282524
Epoch 14/100, Loss: 2.624611258506775
Epoch 15/100, Loss: 2.8829421028494835
Epoch 16/100, Loss: 2.746039666235447
Epoch 17/100, Loss: 2.787061758339405
Epoch 18/100, Loss: 2.5740506276488304
Epoch 19/100, Loss: 2.5712544694542885
Epoch 20/100, Loss: 2.80879233032465
Epoch 21/100, Loss: 2.7635409086942673
Epoch 22/100, Loss: 2.8248584270477295
Epoch 23/100, Loss: 2.512472629547119
Epoch 24/100, Loss: 2.514122575521469
Epoch 25/100, Loss: 2.779621012508869

Epoch 26/100, Loss: 2.7686269506812096
Epoch 27/100, Loss: 2.531442940235138
Epoch 28/100, Loss: 2.6637111455202103
Epoch 29/100, Loss: 2.622016504406929
Epoch 30/100, Loss: 2.604912541806698
Epoch 31/100, Loss: 2.525516264140606
Epoch 32/100, Loss: 2.667979620397091
Epoch 33/100, Loss: 2.6598584353923798
Epoch 34/100, Loss: 2.4832020476460457
Epoch 35/100, Loss: 2.7336410582065582
Epoch 36/100, Loss: 2.644721694290638
Epoch 37/100, Loss: 2.756087303161621
Epoch 38/100, Loss: 2.5921481996774673

Epoch 39/100, Loss: 2.8406969383358955
Epoch 40/100, Loss: 2.8047315031290054
Epoch 41/100, Loss: 2.663146622478962
Epoch 42/100, Loss: 2.4388476088643074
Epoch 43/100, Loss: 2.548871234059334
Epoch 44/100, Loss: 2.712403267621994
Epoch 45/100, Loss: 2.7862106263637543
Epoch 46/100, Loss: 2.6620109006762505
Epoch 47/100, Loss: 3.4354204684495926
Epoch 48/100, Loss: 2.963871121406555
Epoch 49/100, Loss: 2.663363203406334
Epoch 50/100, Loss: 2.73380895704031
Epoch 51/100, Loss: 2.649555414915085
Epoch 52/100, Loss: 2.793110929429531
Epoch 53/100, Loss: 2.843827746808529
Epoch 54/100, Loss: 2.5095711052417755
Epoch 55/100, Loss: 2.5479510501027107

Epoch 56/100, Loss: 2.7781970277428627
Epoch 57/100, Loss: 2.6429812982678413
Epoch 58/100, Loss: 2.774746686220169
Epoch 59/100, Loss: 2.8008231222629547
Epoch 60/100, Loss: 2.982605718076229
Epoch 61/100, Loss: 2.3986879885196686
Epoch 62/100, Loss: 2.9599144235253334
Epoch 63/100, Loss: 2.5495382845401764
Epoch 64/100, Loss: 2.493255950510502
Epoch 65/100, Loss: 2.6697338819503784
Epoch 66/100, Loss: 2.8067704141139984
Epoch 67/100, Loss: 2.497072272002697
Epoch 68/100, Loss: 2.613462455570698
Epoch 69/100, Loss: 2.844176806509495
Epoch 70/100, Loss: 2.5992341935634613
Epoch 71/100, Loss: 2.6744366958737373

Epoch 72/100, Loss: 2.7849233373999596
Epoch 73/100, Loss: 2.656895585358143
Epoch 74/100, Loss: 2.586073860526085
Epoch 75/100, Loss: 2.5927793383598328
Epoch 76/100, Loss: 2.5704193860292435
Epoch 77/100, Loss: 2.393093816936016
Epoch 78/100, Loss: 2.556046210229397
Epoch 79/100, Loss: 2.6299502104520798
Epoch 80/100, Loss: 2.7576603144407272
Epoch 81/100, Loss: 2.8507591262459755
Epoch 82/100, Loss: 2.6723501086235046
Epoch 83/100, Loss: 2.485676921904087
Epoch 84/100, Loss: 2.627681501209736
Epoch 85/100, Loss: 2.936231069266796
Epoch 86/100, Loss: 2.795879326760769
Epoch 87/100, Loss: 2.753302216529846
Epoch 88/100, Loss: 2.434103786945343

Epoch 89/100, Loss: 2.5367953702807426
Epoch 90/100, Loss: 2.597625881433487
Epoch 91/100, Loss: 2.666776664555073
Epoch 92/100, Loss: 2.761579044163227
Epoch 93/100, Loss: 2.607075184583664
Epoch 94/100, Loss: 2.430142365396023
Epoch 95/100, Loss: 2.7342517226934433
Epoch 96/100, Loss: 2.926254153251648
Epoch 97/100, Loss: 2.6771984100341797
Epoch 98/100, Loss: 2.5935251340270042
Epoch 99/100, Loss: 2.8129759207367897
Epoch 100/100, Loss: 3.4032923206686974
Fold 5/5 done

In [11]:
ap = average_precision_score(y_true, anomaly_scores)
print(f"Deep SVDD AP (5-fold CV) = {ap:.4f}")
sb.glue("GBG500_ap_spectral_deep_svdd", float(ap))

Deep SVDD AP (5-fold CV) = 0.5861