In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import average_precision_score
from sklearn.model_selection import StratifiedKFold
from pyod.models.deep_svdd import DeepSVDD
import sys
import scrapbook as sb

sys.path.append('..')
from utils import reshape_to_numpy, interpolate_missing_values, denoise_data, compute_spectrograms, time_avg_pooling

In [2]:
seed = 1
sampling_rate = 10
nperseg=64
noverlap=32
accel_cutoff = 0.4
accel_order = 30
gyro_cutoff = 0.6
gyro_order = 20
batch_size = 32
epochs = 100
hidden_neurons = [128, 64, 32]
n_splits = 5

In [3]:
# Parameters
seed = 11

In [4]:
rng = np.random.RandomState(seed)

In [5]:
data = pd.read_parquet("../data/GBG500.parquet")
data

,ride_id,time_index,ax,ay,az,rx,ry,rz
0,005043f1a7520cebf1e17fd166a00a3190e2433530f236...,0,-2.512796,-9.385012,-1.053078,-0.009155,0.009155,-0.201416
1,005043f1a7520cebf1e17fd166a00a3190e2433530f236...,100,-2.491268,-9.385012,-1.079390,-0.036621,0.027465,-0.155639
2,005043f1a7520cebf1e17fd166a00a3190e2433530f236...,200,-2.534324,-9.382022,-1.030952,0.036621,0.027465,-0.073242
3,005043f1a7520cebf1e17fd166a00a3190e2433530f236...,300,-2.488278,-9.383218,-1.091948,-0.045776,0.036621,-0.183105
4,005043f1a7520cebf1e17fd166a00a3190e2433530f236...,400,-2.483494,-9.382022,-1.100320,-0.045776,0.027465,-0.192260
...,...,...,...,...,...,...,...,...
1529542,ffb6f2f5dc6ba768d88dc0bc1af4cad235526aa9e24168...,241300,0.459862,-9.140430,-3.318900,1.556396,-0.091552,0.274658
1529543,ffb6f2f5dc6ba768d88dc0bc1af4cad235526aa9e24168...,241400,0.455676,-9.140430,-3.321292,1.583861,-0.119018,0.274658
1529544,ffb6f2f5dc6ba768d88dc0bc1af4cad235526aa9e24168...,241500,0.459862,-9.139832,-3.317704,1.583861,-0.109863,0.274658
1529545,ffb6f2f5dc6ba768d88dc0bc1af4cad235526aa9e24168...,241600,0.456274,-9.142224,-3.321292,1.574707,-0.137329,0.283813
1529546,ffb6f2f5dc6ba768d88dc0bc1af4cad235526aa9e24168...,241700,0.458666,-9.139832,-3.320694,1.574707,-0.137329,0.274658

In [6]:
labels = pd.read_csv("../data/GBG500_labels.csv")
labels.columns = labels.columns.str.lower()
ride_order_df = pd.DataFrame({"ride_id": data["ride_id"].unique()})
labels_sorted = ride_order_df.merge(
    labels,
    on="ride_id",
    how="left"
)
labels_sorted

                                               ride_id        label
0    005043f1a7520cebf1e17fd166a00a3190e2433530f236...         Safe
1    00d223cb7aecc9c0cc5871e32a6c45027a068eba07c572...     Reckless
2    02288a4aeca044203394e982e76b87818021dea2b34df9...         Safe
3    0236bdcf13d473ea24d97f5eaeea459f257dffac005694...  Bad weather
4    0238e5dd85143f1b6c59b200bc32f14361b8fc84c51a87...         Safe
..                                                 ...          ...
495  fe5d7f84d692bbccad8bd566a3ad5c3108fa9f90acd671...         Safe
496  fe67169632306d4668b2affedef510df2cb43e2fb41220...         Safe
497  fee44667fdc8ab4995c702fc3bd36178de0b1ca2c64687...         Safe
498  ff79b2e945b93c2a5efc3a06365267b3a160e7849ba57d...         Safe
499  ffb6f2f5dc6ba768d88dc0bc1af4cad235526aa9e24168...         Safe

[500 rows x 2 columns]

In [7]:
data_np = reshape_to_numpy(
    data,
    features = ["ax", "ay", "az", "rx", "ry", "rz"],
    max_timestamps = 4800
)

data_np_clean = interpolate_missing_values(
    data_np,
    method='linear',
    limit=None
)

data_np_clean = denoise_data(
    data=data_np_clean,
    accel_indices=[0, 1, 2],
    gyro_indices=[3, 4, 5],
    accel_cutoff=accel_cutoff,
    accel_order=accel_order,
    gyro_cutoff=gyro_cutoff,
    gyro_order=gyro_order,
)

In [8]:
# Compute spectrograms for all rides
spectrograms_array = compute_spectrograms(data_np_clean, sampling_rate, nperseg, noverlap)
spectrograms_array.shape

(500, 149, 6, 33)

In [9]:
# Aggregate spectrograms using time-averaged pooling
X_feat = time_avg_pooling(spectrograms_array)
X_feat.shape

(500, 198)

In [10]:
# 5-fold stratified CV with Deep SVDD
skf = StratifiedKFold(n_splits=n_splits, shuffle=True, random_state=rng.randint(1000))
y_true = (labels_sorted['label'] == 'Reckless').astype(int).values
anomaly_scores = np.full(len(y_true), np.nan)

for fold, (train_idx, test_idx) in enumerate(skf.split(X_feat, y_true)):
    sc = StandardScaler()
    X_train = sc.fit_transform(X_feat[train_idx])
    X_test = sc.transform(X_feat[test_idx])

    np.random.seed(rng.randint(1000))
    model = DeepSVDD(
        n_features=X_train.shape[1],
        hidden_neurons=hidden_neurons,
        epochs=epochs,
        batch_size=batch_size,
        random_state=rng.randint(1000),
    )
    model.fit(X_train)
    anomaly_scores[test_idx] = model.decision_function(X_test)
    print(f"Fold {fold+1}/{n_splits} done")

Epoch 1/100, Loss: 2.609221749007702
Epoch 2/100, Loss: 2.4459606632590294
Epoch 3/100, Loss: 2.4771324545145035
Epoch 4/100, Loss: 2.5794943645596504
Epoch 5/100, Loss: 2.5366047620773315
Epoch 6/100, Loss: 2.494461126625538
Epoch 7/100, Loss: 2.3925967812538147
Epoch 8/100, Loss: 2.7009518444538116
Epoch 9/100, Loss: 2.4879960492253304
Epoch 10/100, Loss: 2.457835301756859
Epoch 11/100, Loss: 2.3445565178990364
Epoch 12/100, Loss: 2.5918062180280685
Epoch 13/100, Loss: 2.4315365739166737
Epoch 14/100, Loss: 2.5754426643252373
Epoch 15/100, Loss: 3.0957513004541397
Epoch 16/100, Loss: 2.631595730781555
Epoch 17/100, Loss: 2.7033082246780396

Epoch 18/100, Loss: 2.4927254393696785
Epoch 19/100, Loss: 2.2310572415590286
Epoch 20/100, Loss: 2.4485263526439667
Epoch 21/100, Loss: 2.5679445937275887
Epoch 22/100, Loss: 2.3504332825541496
Epoch 23/100, Loss: 2.494469068944454
Epoch 24/100, Loss: 2.5504394099116325
Epoch 25/100, Loss: 2.6893958896398544
Epoch 26/100, Loss: 2.4947719126939774
Epoch 27/100, Loss: 2.5574314519762993
Epoch 28/100, Loss: 2.4267420172691345
Epoch 29/100, Loss: 2.4964586719870567
Epoch 30/100, Loss: 2.5154936462640762
Epoch 31/100, Loss: 2.441619075834751
Epoch 32/100, Loss: 2.381852760910988
Epoch 33/100, Loss: 2.564363531768322
Epoch 34/100, Loss: 2.3853904083371162

Epoch 35/100, Loss: 2.5144168958067894
Epoch 36/100, Loss: 2.593670703470707
Epoch 37/100, Loss: 2.647905595600605
Epoch 38/100, Loss: 2.5775167047977448
Epoch 39/100, Loss: 2.5770293846726418
Epoch 40/100, Loss: 2.489797279238701
Epoch 41/100, Loss: 2.65754321962595
Epoch 42/100, Loss: 2.515278458595276
Epoch 43/100, Loss: 2.59809809923172
Epoch 44/100, Loss: 2.361557260155678
Epoch 45/100, Loss: 2.586212210357189
Epoch 46/100, Loss: 2.4099755361676216
Epoch 47/100, Loss: 2.5647121742367744
Epoch 48/100, Loss: 2.6343067958950996
Epoch 49/100, Loss: 2.4433158338069916
Epoch 50/100, Loss: 2.819645047187805
Epoch 51/100, Loss: 2.4750514775514603

Epoch 52/100, Loss: 2.5308874621987343
Epoch 53/100, Loss: 2.408222980797291
Epoch 54/100, Loss: 2.466579094529152
Epoch 55/100, Loss: 2.2522589191794395
Epoch 56/100, Loss: 2.496432699263096
Epoch 57/100, Loss: 3.1716118454933167
Epoch 58/100, Loss: 2.602905608713627
Epoch 59/100, Loss: 2.5436235517263412
Epoch 60/100, Loss: 2.5401155948638916
Epoch 61/100, Loss: 2.6101967245340347
Epoch 62/100, Loss: 2.333831164985895
Epoch 63/100, Loss: 2.597722090780735
Epoch 64/100, Loss: 2.5410186797380447
Epoch 65/100, Loss: 2.515992186963558
Epoch 66/100, Loss: 2.47756227850914
Epoch 67/100, Loss: 2.415529102087021
Epoch 68/100, Loss: 2.4268108010292053

Epoch 69/100, Loss: 2.474801667034626
Epoch 70/100, Loss: 2.6625565513968468
Epoch 71/100, Loss: 2.4976409897208214
Epoch 72/100, Loss: 2.4844680726528168
Epoch 73/100, Loss: 2.7773054242134094
Epoch 74/100, Loss: 2.405972495675087
Epoch 75/100, Loss: 2.473934903740883
Epoch 76/100, Loss: 2.473983481526375
Epoch 77/100, Loss: 2.658280149102211
Epoch 78/100, Loss: 2.5138888135552406
Epoch 79/100, Loss: 2.5689857229590416
Epoch 80/100, Loss: 2.3460301533341408
Epoch 81/100, Loss: 2.594384215772152
Epoch 82/100, Loss: 2.386183299124241
Epoch 83/100, Loss: 2.369439549744129
Epoch 84/100, Loss: 2.5794462338089943
Epoch 85/100, Loss: 2.4723986387252808

Epoch 86/100, Loss: 2.6006357222795486
Epoch 87/100, Loss: 2.5390433073043823
Epoch 88/100, Loss: 2.455972634255886
Epoch 89/100, Loss: 2.6212934777140617
Epoch 90/100, Loss: 2.6356264799833298
Epoch 91/100, Loss: 2.5170295983552933
Epoch 92/100, Loss: 2.3893978744745255
Epoch 93/100, Loss: 2.5350023061037064
Epoch 94/100, Loss: 2.2996136471629143
Epoch 95/100, Loss: 2.9927090629935265
Epoch 96/100, Loss: 2.246202103793621
Epoch 97/100, Loss: 2.6785220578312874
Epoch 98/100, Loss: 2.623884841799736
Epoch 99/100, Loss: 2.250121630728245
Epoch 100/100, Loss: 2.657049208879471
Fold 1/5 done

Epoch 1/100, Loss: 3.326416939496994
Epoch 2/100, Loss: 2.971262738108635
Epoch 3/100, Loss: 3.2663229256868362
Epoch 4/100, Loss: 3.757386825978756
Epoch 5/100, Loss: 3.0392832905054092
Epoch 6/100, Loss: 3.3053214251995087
Epoch 7/100, Loss: 3.4088356494903564
Epoch 8/100, Loss: 3.1350884810090065
Epoch 9/100, Loss: 3.2222252786159515
Epoch 10/100, Loss: 3.3360998183488846
Epoch 11/100, Loss: 3.3966584652662277
Epoch 12/100, Loss: 3.2423529624938965
Epoch 13/100, Loss: 3.177007794380188
Epoch 14/100, Loss: 3.4108525663614273
Epoch 15/100, Loss: 3.665483608841896
Epoch 16/100, Loss: 3.272461920976639
Epoch 17/100, Loss: 3.139512613415718

Epoch 18/100, Loss: 3.9771718084812164
Epoch 19/100, Loss: 3.1514249071478844
Epoch 20/100, Loss: 3.482146382331848
Epoch 21/100, Loss: 3.4677317440509796
Epoch 22/100, Loss: 3.3882508128881454
Epoch 23/100, Loss: 3.397213339805603
Epoch 24/100, Loss: 3.415082708001137
Epoch 25/100, Loss: 3.367711752653122
Epoch 26/100, Loss: 3.4616715759038925
Epoch 27/100, Loss: 3.399211972951889
Epoch 28/100, Loss: 3.215959854424
Epoch 29/100, Loss: 3.2256806045770645
Epoch 30/100, Loss: 3.4097748696804047
Epoch 31/100, Loss: 3.2681681513786316
Epoch 32/100, Loss: 3.3132710680365562
Epoch 33/100, Loss: 3.6132623106241226
Epoch 34/100, Loss: 3.3610981553792953

Epoch 35/100, Loss: 3.427766837179661
Epoch 36/100, Loss: 3.204172767698765
Epoch 37/100, Loss: 3.3738978505134583
Epoch 38/100, Loss: 3.451353818178177
Epoch 39/100, Loss: 2.950007379055023
Epoch 40/100, Loss: 3.311433866620064
Epoch 41/100, Loss: 3.508691370487213
Epoch 42/100, Loss: 3.2839537411928177
Epoch 43/100, Loss: 3.2240367084741592
Epoch 44/100, Loss: 3.380467802286148
Epoch 45/100, Loss: 3.4906316101551056
Epoch 46/100, Loss: 3.276680752635002
Epoch 47/100, Loss: 3.1265415251255035
Epoch 48/100, Loss: 3.4003103524446487
Epoch 49/100, Loss: 3.3755393251776695
Epoch 50/100, Loss: 3.5060008764266968
Epoch 51/100, Loss: 3.6758040860295296

Epoch 52/100, Loss: 3.401501417160034
Epoch 53/100, Loss: 3.0247447416186333
Epoch 54/100, Loss: 3.2883079946041107
Epoch 55/100, Loss: 3.1910567209124565
Epoch 56/100, Loss: 3.2085814997553825
Epoch 57/100, Loss: 3.23908793926239
Epoch 58/100, Loss: 3.1147961616516113
Epoch 59/100, Loss: 3.327126234769821
Epoch 60/100, Loss: 3.314189225435257
Epoch 61/100, Loss: 3.2322834953665733
Epoch 62/100, Loss: 3.316698968410492
Epoch 63/100, Loss: 3.319626607000828
Epoch 64/100, Loss: 3.2498821318149567
Epoch 65/100, Loss: 3.3086167573928833
Epoch 66/100, Loss: 3.2249390482902527
Epoch 67/100, Loss: 3.795644074678421
Epoch 68/100, Loss: 3.385768696665764

Epoch 69/100, Loss: 3.4425552040338516
Epoch 70/100, Loss: 3.4129044115543365
Epoch 71/100, Loss: 3.2358610779047012
Epoch 72/100, Loss: 3.336834594607353
Epoch 73/100, Loss: 3.2418187856674194
Epoch 74/100, Loss: 3.5127744525671005
Epoch 75/100, Loss: 3.403250589966774
Epoch 76/100, Loss: 3.2603838369250298
Epoch 77/100, Loss: 3.432577669620514
Epoch 78/100, Loss: 3.308755338191986
Epoch 79/100, Loss: 3.131213366985321
Epoch 80/100, Loss: 3.3679610937833786
Epoch 81/100, Loss: 3.3804714307188988
Epoch 82/100, Loss: 3.075895607471466
Epoch 83/100, Loss: 3.1285740807652473

Epoch 84/100, Loss: 3.412897728383541
Epoch 85/100, Loss: 3.3219108134508133
Epoch 86/100, Loss: 3.4937357008457184
Epoch 87/100, Loss: 3.2713309824466705
Epoch 88/100, Loss: 3.4741641730070114
Epoch 89/100, Loss: 3.507208615541458
Epoch 90/100, Loss: 3.2818565741181374
Epoch 91/100, Loss: 3.4751328080892563
Epoch 92/100, Loss: 3.2755008041858673
Epoch 93/100, Loss: 3.3495975583791733
Epoch 94/100, Loss: 3.1028412878513336
Epoch 95/100, Loss: 3.4960869550704956
Epoch 96/100, Loss: 3.3653804883360863
Epoch 97/100, Loss: 3.3398968279361725
Epoch 98/100, Loss: 3.2911396473646164
Epoch 99/100, Loss: 3.3665022999048233
Epoch 100/100, Loss: 3.0267259255051613
Fold 2/5 done

Epoch 1/100, Loss: 1.2055819854140282
Epoch 2/100, Loss: 1.2148254700005054
Epoch 3/100, Loss: 1.1654012836515903
Epoch 4/100, Loss: 1.198636632412672
Epoch 5/100, Loss: 1.2953717187047005
Epoch 6/100, Loss: 1.223604742437601
Epoch 7/100, Loss: 1.2656681686639786
Epoch 8/100, Loss: 1.1911095529794693
Epoch 9/100, Loss: 1.2196992225944996
Epoch 10/100, Loss: 1.1950379759073257
Epoch 11/100, Loss: 1.320210125297308
Epoch 12/100, Loss: 1.2778031639754772
Epoch 13/100, Loss: 1.1686158776283264
Epoch 14/100, Loss: 1.1959532015025616
Epoch 15/100, Loss: 1.2628074958920479
Epoch 16/100, Loss: 1.2652022019028664
Epoch 17/100, Loss: 1.210144031792879

Epoch 18/100, Loss: 1.158242654055357
Epoch 19/100, Loss: 1.2072348706424236
Epoch 20/100, Loss: 1.1818550117313862
Epoch 21/100, Loss: 1.2304833754897118
Epoch 22/100, Loss: 1.1831765100359917
Epoch 23/100, Loss: 1.2830863036215305
Epoch 24/100, Loss: 1.2179631479084492
Epoch 25/100, Loss: 1.3104869164526463
Epoch 26/100, Loss: 1.2319084778428078
Epoch 27/100, Loss: 1.2714074179530144
Epoch 28/100, Loss: 1.240106638520956
Epoch 29/100, Loss: 1.262138519436121
Epoch 30/100, Loss: 1.2678102441132069
Epoch 31/100, Loss: 1.2281525284051895
Epoch 32/100, Loss: 1.297700796276331

Epoch 33/100, Loss: 1.228525549173355
Epoch 34/100, Loss: 1.2074559405446053
Epoch 35/100, Loss: 1.2002602331340313
Epoch 36/100, Loss: 1.1761081963777542
Epoch 37/100, Loss: 1.2553602904081345
Epoch 38/100, Loss: 1.2512854561209679
Epoch 39/100, Loss: 1.250111736357212
Epoch 40/100, Loss: 1.2300366088747978
Epoch 41/100, Loss: 1.2434721924364567
Epoch 42/100, Loss: 1.2139020785689354
Epoch 43/100, Loss: 1.210451453924179
Epoch 44/100, Loss: 1.1771531142294407
Epoch 45/100, Loss: 1.2361156083643436
Epoch 46/100, Loss: 1.2333755493164062
Epoch 47/100, Loss: 1.2777014449238777
Epoch 48/100, Loss: 1.2261283360421658
Epoch 49/100, Loss: 1.1851380243897438

Epoch 50/100, Loss: 1.2995349541306496
Epoch 51/100, Loss: 1.225815735757351
Epoch 52/100, Loss: 1.2674312181770802
Epoch 53/100, Loss: 1.1612586379051208
Epoch 54/100, Loss: 1.162617515772581
Epoch 55/100, Loss: 1.2838025204837322
Epoch 56/100, Loss: 1.1854023039340973
Epoch 57/100, Loss: 1.2176020257174969
Epoch 58/100, Loss: 1.1801673024892807
Epoch 59/100, Loss: 1.2498507164418697
Epoch 60/100, Loss: 1.2787074819207191
Epoch 61/100, Loss: 1.2050345689058304
Epoch 62/100, Loss: 1.2249906212091446
Epoch 63/100, Loss: 1.197312243282795
Epoch 64/100, Loss: 1.1973293758928776
Epoch 65/100, Loss: 1.222242895513773

Epoch 66/100, Loss: 1.2650835551321507
Epoch 67/100, Loss: 1.2364999800920486
Epoch 68/100, Loss: 1.2324262894690037
Epoch 69/100, Loss: 1.277836687862873
Epoch 70/100, Loss: 1.2375874072313309
Epoch 71/100, Loss: 1.1954544261097908
Epoch 72/100, Loss: 1.2627381309866905
Epoch 73/100, Loss: 1.1812839470803738
Epoch 74/100, Loss: 1.2330305948853493
Epoch 75/100, Loss: 1.1968531087040901
Epoch 76/100, Loss: 1.2112901471555233

Epoch 77/100, Loss: 1.2029411867260933
Epoch 78/100, Loss: 1.2523898892104626
Epoch 79/100, Loss: 1.1832290589809418
Epoch 80/100, Loss: 1.2354992590844631
Epoch 81/100, Loss: 1.1995597705245018
Epoch 82/100, Loss: 1.184187676757574
Epoch 83/100, Loss: 1.2037680745124817
Epoch 84/100, Loss: 1.229392383247614
Epoch 85/100, Loss: 1.3216597959399223
Epoch 86/100, Loss: 1.1701256670057774
Epoch 87/100, Loss: 1.2078693397343159

Epoch 88/100, Loss: 1.2277005016803741
Epoch 89/100, Loss: 1.265742652118206
Epoch 90/100, Loss: 1.2597502917051315
Epoch 91/100, Loss: 1.2542593479156494
Epoch 92/100, Loss: 1.176327895373106
Epoch 93/100, Loss: 1.195484720170498
Epoch 94/100, Loss: 1.1984112188220024
Epoch 95/100, Loss: 1.2520506009459496
Epoch 96/100, Loss: 1.2388597875833511
Epoch 97/100, Loss: 1.2745180800557137
Epoch 98/100, Loss: 1.2704616263508797

Epoch 99/100, Loss: 1.179284393787384
Epoch 100/100, Loss: 1.2089300192892551
Fold 3/5 done
Epoch 1/100, Loss: 3.066123254597187
Epoch 2/100, Loss: 3.1636801287531853
Epoch 3/100, Loss: 2.7916779443621635
Epoch 4/100, Loss: 2.864155799150467
Epoch 5/100, Loss: 3.051868326961994
Epoch 6/100, Loss: 3.199243426322937
Epoch 7/100, Loss: 3.1375011056661606
Epoch 8/100, Loss: 3.0564520210027695
Epoch 9/100, Loss: 3.0098727494478226
Epoch 10/100, Loss: 3.115361340343952
Epoch 11/100, Loss: 3.100503697991371
Epoch 12/100, Loss: 2.8301607817411423

Epoch 13/100, Loss: 2.957304537296295
Epoch 14/100, Loss: 3.0625566840171814
Epoch 15/100, Loss: 2.7543242052197456
Epoch 16/100, Loss: 2.973116919398308
Epoch 17/100, Loss: 2.6607700660824776
Epoch 18/100, Loss: 3.134653225541115
Epoch 19/100, Loss: 3.2223740071058273
Epoch 20/100, Loss: 3.1434392109513283
Epoch 21/100, Loss: 3.1853076815605164
Epoch 22/100, Loss: 3.218813255429268
Epoch 23/100, Loss: 3.3255628421902657
Epoch 24/100, Loss: 3.429613009095192
Epoch 25/100, Loss: 2.921751707792282
Epoch 26/100, Loss: 3.2587592601776123
Epoch 27/100, Loss: 3.1689737364649773

Epoch 28/100, Loss: 3.1378727331757545
Epoch 29/100, Loss: 2.8845252320170403
Epoch 30/100, Loss: 3.309656545519829
Epoch 31/100, Loss: 3.239905819296837
Epoch 32/100, Loss: 3.323778621852398
Epoch 33/100, Loss: 2.8971031457185745
Epoch 34/100, Loss: 3.0018677935004234
Epoch 35/100, Loss: 2.8206081464886665
Epoch 36/100, Loss: 2.928258053958416
Epoch 37/100, Loss: 3.1082284450531006
Epoch 38/100, Loss: 2.9565568044781685
Epoch 39/100, Loss: 2.9768905490636826
Epoch 40/100, Loss: 2.938448116183281
Epoch 41/100, Loss: 3.0404670387506485
Epoch 42/100, Loss: 2.971882775425911

Epoch 43/100, Loss: 3.4337585046887398
Epoch 44/100, Loss: 3.1695737913250923
Epoch 45/100, Loss: 2.862872488796711
Epoch 46/100, Loss: 3.248152531683445
Epoch 47/100, Loss: 3.0438502803444862
Epoch 48/100, Loss: 3.2028642520308495
Epoch 49/100, Loss: 2.7385424450039864
Epoch 50/100, Loss: 2.91407673060894
Epoch 51/100, Loss: 2.81224125623703
Epoch 52/100, Loss: 3.186890736222267
Epoch 53/100, Loss: 3.042776346206665
Epoch 54/100, Loss: 3.3157074078917503

Epoch 55/100, Loss: 3.0949854515492916
Epoch 56/100, Loss: 2.740160658955574
Epoch 57/100, Loss: 2.9748775735497475
Epoch 58/100, Loss: 3.2307636216282845
Epoch 59/100, Loss: 3.3530593663454056
Epoch 60/100, Loss: 3.0246178060770035
Epoch 61/100, Loss: 2.9806826561689377
Epoch 62/100, Loss: 2.963541254401207
Epoch 63/100, Loss: 3.1282285675406456
Epoch 64/100, Loss: 3.2933743074536324
Epoch 65/100, Loss: 2.961083270609379

Epoch 66/100, Loss: 3.1357233077287674
Epoch 67/100, Loss: 3.016116201877594
Epoch 68/100, Loss: 2.8005300015211105
Epoch 69/100, Loss: 3.057969681918621
Epoch 70/100, Loss: 3.421333208680153
Epoch 71/100, Loss: 3.3104864209890366
Epoch 72/100, Loss: 3.28312998265028
Epoch 73/100, Loss: 3.155017241835594
Epoch 74/100, Loss: 2.876853682100773
Epoch 75/100, Loss: 3.0583963617682457
Epoch 76/100, Loss: 3.324868008494377
Epoch 77/100, Loss: 3.0643285512924194

Epoch 78/100, Loss: 2.891442783176899
Epoch 79/100, Loss: 2.9293870851397514
Epoch 80/100, Loss: 2.9858583733439445
Epoch 81/100, Loss: 3.1027792617678642
Epoch 82/100, Loss: 2.9893914237618446
Epoch 83/100, Loss: 3.044383727014065
Epoch 84/100, Loss: 2.9822933226823807
Epoch 85/100, Loss: 2.915240839123726
Epoch 86/100, Loss: 2.9315347895026207
Epoch 87/100, Loss: 2.8784864842891693
Epoch 88/100, Loss: 3.008346304297447
Epoch 89/100, Loss: 2.9405292198061943

Epoch 90/100, Loss: 3.0465573891997337
Epoch 91/100, Loss: 3.1756857708096504
Epoch 92/100, Loss: 3.328761413693428
Epoch 93/100, Loss: 3.019396498799324
Epoch 94/100, Loss: 3.196335345506668
Epoch 95/100, Loss: 3.1662522181868553
Epoch 96/100, Loss: 2.8697953298687935
Epoch 97/100, Loss: 3.060578815639019
Epoch 98/100, Loss: 2.8790487721562386
Epoch 99/100, Loss: 2.9799296855926514
Epoch 100/100, Loss: 2.7855743691325188
Fold 4/5 done

Epoch 1/100, Loss: 1.91192077845335
Epoch 2/100, Loss: 1.7007695063948631
Epoch 3/100, Loss: 2.018141746520996
Epoch 4/100, Loss: 1.7860613204538822
Epoch 5/100, Loss: 1.6798116602003574
Epoch 6/100, Loss: 1.707430887967348
Epoch 7/100, Loss: 1.8092649467289448
Epoch 8/100, Loss: 1.8741380646824837
Epoch 9/100, Loss: 2.01104673743248
Epoch 10/100, Loss: 2.0705485939979553
Epoch 11/100, Loss: 1.9101771414279938

Epoch 12/100, Loss: 1.8578960485756397
Epoch 13/100, Loss: 1.801729902625084
Epoch 14/100, Loss: 1.9209840260446072
Epoch 15/100, Loss: 1.9851775169372559
Epoch 16/100, Loss: 2.092861033976078
Epoch 17/100, Loss: 2.1116901263594627
Epoch 18/100, Loss: 1.549941748380661
Epoch 19/100, Loss: 1.7898590564727783
Epoch 20/100, Loss: 1.57273281365633
Epoch 21/100, Loss: 2.0567969866096973
Epoch 22/100, Loss: 2.123704545199871

Epoch 23/100, Loss: 1.7966973036527634
Epoch 24/100, Loss: 2.012089490890503
Epoch 25/100, Loss: 1.9015320092439651
Epoch 26/100, Loss: 2.08640019595623
Epoch 27/100, Loss: 2.174352701753378
Epoch 28/100, Loss: 1.5473094768822193
Epoch 29/100, Loss: 1.7531861811876297
Epoch 30/100, Loss: 2.099583864212036
Epoch 31/100, Loss: 1.9601907767355442
Epoch 32/100, Loss: 1.9496609829366207
Epoch 33/100, Loss: 1.6759799495339394

Epoch 34/100, Loss: 2.3452230766415596
Epoch 35/100, Loss: 1.7531178444623947
Epoch 36/100, Loss: 2.1934009343385696
Epoch 37/100, Loss: 1.727634321898222
Epoch 38/100, Loss: 2.0584064461290836
Epoch 39/100, Loss: 2.1202717795968056
Epoch 40/100, Loss: 1.785425879061222
Epoch 41/100, Loss: 1.9058335945010185
Epoch 42/100, Loss: 2.0778768807649612
Epoch 43/100, Loss: 1.6605501174926758
Epoch 44/100, Loss: 1.9117427095770836
Epoch 45/100, Loss: 2.059589944779873
Epoch 46/100, Loss: 2.264635570347309
Epoch 47/100, Loss: 1.6193677373230457
Epoch 48/100, Loss: 2.212457500398159
Epoch 49/100, Loss: 2.0692755468189716
Epoch 50/100, Loss: 1.774107437580824
Epoch 51/100, Loss: 2.028343390673399

Epoch 52/100, Loss: 2.148788668215275
Epoch 53/100, Loss: 1.9551063179969788
Epoch 54/100, Loss: 1.8836794383823872
Epoch 55/100, Loss: 1.8189442940056324
Epoch 56/100, Loss: 1.8721905946731567
Epoch 57/100, Loss: 1.865684948861599
Epoch 58/100, Loss: 2.2295323349535465
Epoch 59/100, Loss: 1.858375422656536
Epoch 60/100, Loss: 2.238897319883108
Epoch 61/100, Loss: 2.372430719435215
Epoch 62/100, Loss: 1.8878282234072685
Epoch 63/100, Loss: 1.7326361387968063

Epoch 64/100, Loss: 2.1653399541974068
Epoch 65/100, Loss: 1.888366211205721
Epoch 66/100, Loss: 1.9545510970056057
Epoch 67/100, Loss: 1.988158904016018
Epoch 68/100, Loss: 1.9093416295945644
Epoch 69/100, Loss: 1.8941664770245552
Epoch 70/100, Loss: 2.427762895822525
Epoch 71/100, Loss: 1.5756388194859028
Epoch 72/100, Loss: 2.013338875025511
Epoch 73/100, Loss: 1.5188488103449345
Epoch 74/100, Loss: 1.8430057354271412
Epoch 75/100, Loss: 1.83644225820899
Epoch 76/100, Loss: 2.9384645894169807

Epoch 77/100, Loss: 1.6776548996567726
Epoch 78/100, Loss: 1.8926027715206146
Epoch 79/100, Loss: 1.9187960997223854
Epoch 80/100, Loss: 1.678288571536541
Epoch 81/100, Loss: 2.013811245560646
Epoch 82/100, Loss: 2.015066225081682
Epoch 83/100, Loss: 2.0419316589832306
Epoch 84/100, Loss: 1.8133759945631027
Epoch 85/100, Loss: 2.0585696138441563
Epoch 86/100, Loss: 2.5611723884940147
Epoch 87/100, Loss: 2.1674607768654823
Epoch 88/100, Loss: 2.0931705124676228
Epoch 89/100, Loss: 2.083685837686062

Epoch 90/100, Loss: 2.108265731483698
Epoch 91/100, Loss: 1.7492974884808064
Epoch 92/100, Loss: 2.0146694630384445
Epoch 93/100, Loss: 1.6148098707199097
Epoch 94/100, Loss: 1.768626183271408
Epoch 95/100, Loss: 1.74943857640028
Epoch 96/100, Loss: 1.6133918277919292
Epoch 97/100, Loss: 1.530499018728733
Epoch 98/100, Loss: 2.2490188144147396
Epoch 99/100, Loss: 2.0003980584442616

Epoch 100/100, Loss: 1.911668837070465
Fold 5/5 done

In [11]:
ap = average_precision_score(y_true, anomaly_scores)
print(f"Deep SVDD AP (5-fold CV) = {ap:.4f}")
sb.glue("GBG500_ap_spectral_deep_svdd", float(ap))

Deep SVDD AP (5-fold CV) = 0.6455