In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import average_precision_score
from sklearn.model_selection import StratifiedKFold
from pyod.models.deep_svdd import DeepSVDD
import sys
import scrapbook as sb

sys.path.append('..')
from utils import reshape_to_numpy, interpolate_missing_values, denoise_data, compute_spectrograms, time_avg_pooling

In [2]:
seed = 1
sampling_rate = 10
nperseg=64
noverlap=32
accel_cutoff = 0.4
accel_order = 30
gyro_cutoff = 0.6
gyro_order = 20
batch_size = 32
epochs = 100
hidden_neurons = [128, 64, 32]
n_splits = 5

In [3]:
# Parameters
seed = 7

In [4]:
rng = np.random.RandomState(seed)

In [5]:
data = pd.read_parquet("../data/GBG500.parquet")
data

,ride_id,time_index,ax,ay,az,rx,ry,rz
0,005043f1a7520cebf1e17fd166a00a3190e2433530f236...,0,-2.512796,-9.385012,-1.053078,-0.009155,0.009155,-0.201416
1,005043f1a7520cebf1e17fd166a00a3190e2433530f236...,100,-2.491268,-9.385012,-1.079390,-0.036621,0.027465,-0.155639
2,005043f1a7520cebf1e17fd166a00a3190e2433530f236...,200,-2.534324,-9.382022,-1.030952,0.036621,0.027465,-0.073242
3,005043f1a7520cebf1e17fd166a00a3190e2433530f236...,300,-2.488278,-9.383218,-1.091948,-0.045776,0.036621,-0.183105
4,005043f1a7520cebf1e17fd166a00a3190e2433530f236...,400,-2.483494,-9.382022,-1.100320,-0.045776,0.027465,-0.192260
...,...,...,...,...,...,...,...,...
1529542,ffb6f2f5dc6ba768d88dc0bc1af4cad235526aa9e24168...,241300,0.459862,-9.140430,-3.318900,1.556396,-0.091552,0.274658
1529543,ffb6f2f5dc6ba768d88dc0bc1af4cad235526aa9e24168...,241400,0.455676,-9.140430,-3.321292,1.583861,-0.119018,0.274658
1529544,ffb6f2f5dc6ba768d88dc0bc1af4cad235526aa9e24168...,241500,0.459862,-9.139832,-3.317704,1.583861,-0.109863,0.274658
1529545,ffb6f2f5dc6ba768d88dc0bc1af4cad235526aa9e24168...,241600,0.456274,-9.142224,-3.321292,1.574707,-0.137329,0.283813
1529546,ffb6f2f5dc6ba768d88dc0bc1af4cad235526aa9e24168...,241700,0.458666,-9.139832,-3.320694,1.574707,-0.137329,0.274658

In [6]:
labels = pd.read_csv("../data/GBG500_labels.csv")
labels.columns = labels.columns.str.lower()
ride_order_df = pd.DataFrame({"ride_id": data["ride_id"].unique()})
labels_sorted = ride_order_df.merge(
    labels,
    on="ride_id",
    how="left"
)
labels_sorted

                                               ride_id        label
0    005043f1a7520cebf1e17fd166a00a3190e2433530f236...         Safe
1    00d223cb7aecc9c0cc5871e32a6c45027a068eba07c572...     Reckless
2    02288a4aeca044203394e982e76b87818021dea2b34df9...         Safe
3    0236bdcf13d473ea24d97f5eaeea459f257dffac005694...  Bad weather
4    0238e5dd85143f1b6c59b200bc32f14361b8fc84c51a87...         Safe
..                                                 ...          ...
495  fe5d7f84d692bbccad8bd566a3ad5c3108fa9f90acd671...         Safe
496  fe67169632306d4668b2affedef510df2cb43e2fb41220...         Safe
497  fee44667fdc8ab4995c702fc3bd36178de0b1ca2c64687...         Safe
498  ff79b2e945b93c2a5efc3a06365267b3a160e7849ba57d...         Safe
499  ffb6f2f5dc6ba768d88dc0bc1af4cad235526aa9e24168...         Safe

[500 rows x 2 columns]

In [7]:
data_np = reshape_to_numpy(
    data,
    features = ["ax", "ay", "az", "rx", "ry", "rz"],
    max_timestamps = 4800
)

data_np_clean = interpolate_missing_values(
    data_np,
    method='linear',
    limit=None
)

data_np_clean = denoise_data(
    data=data_np_clean,
    accel_indices=[0, 1, 2],
    gyro_indices=[3, 4, 5],
    accel_cutoff=accel_cutoff,
    accel_order=accel_order,
    gyro_cutoff=gyro_cutoff,
    gyro_order=gyro_order,
)

In [8]:
# Compute spectrograms for all rides
spectrograms_array = compute_spectrograms(data_np_clean, sampling_rate, nperseg, noverlap)
spectrograms_array.shape

(500, 149, 6, 33)

In [9]:
# Aggregate spectrograms using time-averaged pooling
X_feat = time_avg_pooling(spectrograms_array)
X_feat.shape

(500, 198)

In [10]:
# 5-fold stratified CV with Deep SVDD
skf = StratifiedKFold(n_splits=n_splits, shuffle=True, random_state=rng.randint(1000))
y_true = (labels_sorted['label'] == 'Reckless').astype(int).values
anomaly_scores = np.full(len(y_true), np.nan)

for fold, (train_idx, test_idx) in enumerate(skf.split(X_feat, y_true)):
    sc = StandardScaler()
    X_train = sc.fit_transform(X_feat[train_idx])
    X_test = sc.transform(X_feat[test_idx])

    np.random.seed(rng.randint(1000))
    model = DeepSVDD(
        n_features=X_train.shape[1],
        hidden_neurons=hidden_neurons,
        epochs=epochs,
        batch_size=batch_size,
        random_state=rng.randint(1000),
    )
    model.fit(X_train)
    anomaly_scores[test_idx] = model.decision_function(X_test)
    print(f"Fold {fold+1}/{n_splits} done")

Epoch 1/100, Loss: 2.480626977980137
Epoch 2/100, Loss: 2.223680555820465
Epoch 3/100, Loss: 2.0442496240139008
Epoch 4/100, Loss: 2.3881320729851723
Epoch 5/100, Loss: 2.3346633166074753
Epoch 6/100, Loss: 2.371195562183857
Epoch 7/100, Loss: 2.321855142712593
Epoch 8/100, Loss: 2.197446748614311
Epoch 9/100, Loss: 2.283734455704689
Epoch 10/100, Loss: 2.229678638279438
Epoch 11/100, Loss: 2.380580112338066
Epoch 12/100, Loss: 2.2964107170701027
Epoch 13/100, Loss: 2.3758918419480324

Epoch 14/100, Loss: 2.215927168726921
Epoch 15/100, Loss: 2.3479418605566025
Epoch 16/100, Loss: 2.2494197711348534
Epoch 17/100, Loss: 2.30117604136467
Epoch 18/100, Loss: 2.1517966762185097
Epoch 19/100, Loss: 2.113001599907875
Epoch 20/100, Loss: 2.430112846195698
Epoch 21/100, Loss: 2.308952644467354
Epoch 22/100, Loss: 2.313068211078644
Epoch 23/100, Loss: 2.205165594816208
Epoch 24/100, Loss: 2.4303023889660835
Epoch 25/100, Loss: 3.0137993693351746
Epoch 26/100, Loss: 2.476198688149452
Epoch 27/100, Loss: 2.105695754289627
Epoch 28/100, Loss: 2.2678909078240395
Epoch 29/100, Loss: 2.2178980857133865

Epoch 30/100, Loss: 2.1127709299325943
Epoch 31/100, Loss: 2.2315320298075676
Epoch 32/100, Loss: 2.197834827005863
Epoch 33/100, Loss: 2.213390029966831
Epoch 34/100, Loss: 2.235645644366741
Epoch 35/100, Loss: 2.11887289583683
Epoch 36/100, Loss: 2.4171052053570747
Epoch 37/100, Loss: 2.252612166106701
Epoch 38/100, Loss: 2.109278604388237
Epoch 39/100, Loss: 2.3840047419071198
Epoch 40/100, Loss: 2.2904757037758827
Epoch 41/100, Loss: 2.4502880722284317
Epoch 42/100, Loss: 2.2359855249524117
Epoch 43/100, Loss: 2.374554380774498
Epoch 44/100, Loss: 2.2537521943449974
Epoch 45/100, Loss: 2.500761851668358
Epoch 46/100, Loss: 2.240357778966427

Epoch 47/100, Loss: 2.2919858396053314
Epoch 48/100, Loss: 2.206377513706684
Epoch 49/100, Loss: 2.052030049264431
Epoch 50/100, Loss: 2.332518197596073
Epoch 51/100, Loss: 2.3589997738599777
Epoch 52/100, Loss: 2.5547488257288933
Epoch 53/100, Loss: 2.1542973071336746
Epoch 54/100, Loss: 2.129869431257248
Epoch 55/100, Loss: 2.2552609518170357
Epoch 56/100, Loss: 2.383612923324108
Epoch 57/100, Loss: 2.4064295142889023
Epoch 58/100, Loss: 2.341582752764225
Epoch 59/100, Loss: 2.2279864475131035
Epoch 60/100, Loss: 2.2628786638379097
Epoch 61/100, Loss: 1.981223288923502
Epoch 62/100, Loss: 2.2104636430740356
Epoch 63/100, Loss: 2.321546792984009
Epoch 64/100, Loss: 2.2818131744861603

Epoch 65/100, Loss: 2.3855917155742645
Epoch 66/100, Loss: 2.1924814954400063
Epoch 67/100, Loss: 2.3117478638887405
Epoch 68/100, Loss: 2.168741226196289
Epoch 69/100, Loss: 2.438064582645893
Epoch 70/100, Loss: 2.2127014100551605
Epoch 71/100, Loss: 2.1021128594875336
Epoch 72/100, Loss: 2.1407655999064445
Epoch 73/100, Loss: 2.230172999203205
Epoch 74/100, Loss: 2.3308120146393776
Epoch 75/100, Loss: 2.2291010320186615
Epoch 76/100, Loss: 2.393808327615261
Epoch 77/100, Loss: 2.160465721040964
Epoch 78/100, Loss: 2.2913262844085693
Epoch 79/100, Loss: 2.7260944098234177
Epoch 80/100, Loss: 2.3697289675474167
Epoch 81/100, Loss: 2.6936553567647934

Epoch 82/100, Loss: 2.2081484124064445
Epoch 83/100, Loss: 2.3447358310222626
Epoch 84/100, Loss: 2.1957155987620354
Epoch 85/100, Loss: 2.3455174192786217
Epoch 86/100, Loss: 2.426067739725113
Epoch 87/100, Loss: 2.22479996830225
Epoch 88/100, Loss: 2.374566897749901
Epoch 89/100, Loss: 2.1657700911164284
Epoch 90/100, Loss: 2.470429189503193
Epoch 91/100, Loss: 2.23130352050066
Epoch 92/100, Loss: 2.3247909545898438
Epoch 93/100, Loss: 2.296947196125984
Epoch 94/100, Loss: 2.209229677915573
Epoch 95/100, Loss: 2.4991312325000763
Epoch 96/100, Loss: 2.31420336663723
Epoch 97/100, Loss: 2.3512074798345566
Epoch 98/100, Loss: 2.349947839975357

Epoch 99/100, Loss: 2.3201681450009346
Epoch 100/100, Loss: 2.353427805006504
Fold 1/5 done
Epoch 1/100, Loss: 1.486972637474537
Epoch 2/100, Loss: 1.5193948037922382
Epoch 3/100, Loss: 1.4269855916500092
Epoch 4/100, Loss: 1.433601040393114
Epoch 5/100, Loss: 1.481872297823429
Epoch 6/100, Loss: 1.4601618722081184
Epoch 7/100, Loss: 1.609649758785963
Epoch 8/100, Loss: 1.503127969801426
Epoch 9/100, Loss: 1.4898611679673195
Epoch 10/100, Loss: 1.4865070059895515
Epoch 11/100, Loss: 1.4643970914185047
Epoch 12/100, Loss: 1.5740866102278233

Epoch 13/100, Loss: 1.4678836464881897
Epoch 14/100, Loss: 1.4847501814365387
Epoch 15/100, Loss: 1.4175787009298801
Epoch 16/100, Loss: 1.5404577627778053
Epoch 17/100, Loss: 1.5431169718503952
Epoch 18/100, Loss: 1.4888103529810905
Epoch 19/100, Loss: 1.51743333786726
Epoch 20/100, Loss: 1.5782202929258347
Epoch 21/100, Loss: 1.4639980345964432
Epoch 22/100, Loss: 1.521189596503973
Epoch 23/100, Loss: 1.423811674118042
Epoch 24/100, Loss: 1.568744145333767
Epoch 25/100, Loss: 1.527554240077734

Epoch 26/100, Loss: 1.5480930469930172
Epoch 27/100, Loss: 1.5357851758599281
Epoch 28/100, Loss: 1.5200122185051441
Epoch 29/100, Loss: 1.516508512198925
Epoch 30/100, Loss: 1.5064999721944332
Epoch 31/100, Loss: 1.5852569863200188
Epoch 32/100, Loss: 1.5661086663603783
Epoch 33/100, Loss: 1.4384336024522781
Epoch 34/100, Loss: 1.5496778264641762
Epoch 35/100, Loss: 1.5080273561179638
Epoch 36/100, Loss: 1.5917515009641647
Epoch 37/100, Loss: 1.5056790858507156
Epoch 38/100, Loss: 1.5045029893517494

Epoch 39/100, Loss: 1.662485048174858
Epoch 40/100, Loss: 1.5278099849820137
Epoch 41/100, Loss: 1.4951808229088783
Epoch 42/100, Loss: 1.4856526739895344
Epoch 43/100, Loss: 1.447281651198864
Epoch 44/100, Loss: 1.445078268647194
Epoch 45/100, Loss: 1.5182218179106712
Epoch 46/100, Loss: 1.4124517813324928
Epoch 47/100, Loss: 1.4036932811141014
Epoch 48/100, Loss: 1.5535316318273544
Epoch 49/100, Loss: 1.5582851618528366
Epoch 50/100, Loss: 1.3657702803611755
Epoch 51/100, Loss: 1.4830523803830147
Epoch 52/100, Loss: 1.5508981868624687
Epoch 53/100, Loss: 1.588618479669094
Epoch 54/100, Loss: 1.4110845103859901
Epoch 55/100, Loss: 1.4766004346311092

Epoch 56/100, Loss: 1.5401021912693977
Epoch 57/100, Loss: 1.5311291962862015
Epoch 58/100, Loss: 1.4908353388309479
Epoch 59/100, Loss: 1.4657856188714504
Epoch 60/100, Loss: 1.5206057541072369
Epoch 61/100, Loss: 1.5193158388137817
Epoch 62/100, Loss: 1.4632550701498985
Epoch 63/100, Loss: 1.5155118703842163
Epoch 64/100, Loss: 1.5375647768378258
Epoch 65/100, Loss: 1.5410194359719753
Epoch 66/100, Loss: 1.534112811088562
Epoch 67/100, Loss: 1.4568994417786598
Epoch 68/100, Loss: 1.4358925968408585
Epoch 69/100, Loss: 1.5112487860023975
Epoch 70/100, Loss: 1.5927317589521408

Epoch 71/100, Loss: 1.5124001540243626
Epoch 72/100, Loss: 1.4219506569206715
Epoch 73/100, Loss: 1.4936864748597145
Epoch 74/100, Loss: 1.5962179452180862
Epoch 75/100, Loss: 1.437855701893568
Epoch 76/100, Loss: 1.5180280432105064
Epoch 77/100, Loss: 1.558880690485239
Epoch 78/100, Loss: 1.6738533303141594
Epoch 79/100, Loss: 1.4219899624586105
Epoch 80/100, Loss: 1.582401767373085
Epoch 81/100, Loss: 1.411808229982853
Epoch 82/100, Loss: 1.5630011186003685
Epoch 83/100, Loss: 1.4843225106596947
Epoch 84/100, Loss: 1.5605457909405231
Epoch 85/100, Loss: 1.557304423302412
Epoch 86/100, Loss: 1.510976381599903

Epoch 87/100, Loss: 1.4443440921604633
Epoch 88/100, Loss: 1.5623300895094872
Epoch 89/100, Loss: 1.5372623205184937
Epoch 90/100, Loss: 1.5332982391119003
Epoch 91/100, Loss: 1.5023846477270126
Epoch 92/100, Loss: 1.5816602557897568
Epoch 93/100, Loss: 1.5993595197796822
Epoch 94/100, Loss: 1.5277794674038887
Epoch 95/100, Loss: 1.5409574769437313
Epoch 96/100, Loss: 1.5428561307489872
Epoch 97/100, Loss: 1.4091284684836864
Epoch 98/100, Loss: 1.5477724149823189
Epoch 99/100, Loss: 1.618419662117958
Epoch 100/100, Loss: 1.4857105128467083
Fold 2/5 done
Epoch 1/100, Loss: 2.192569449543953
Epoch 2/100, Loss: 2.046735294163227

Epoch 3/100, Loss: 2.110587328672409
Epoch 4/100, Loss: 2.1201324835419655
Epoch 5/100, Loss: 2.188178613781929
Epoch 6/100, Loss: 2.0102451220154762
Epoch 7/100, Loss: 2.0954402536153793
Epoch 8/100, Loss: 1.9703214839100838
Epoch 9/100, Loss: 2.166767179965973
Epoch 10/100, Loss: 2.113806404173374
Epoch 11/100, Loss: 2.1979117318987846
Epoch 12/100, Loss: 2.173609606921673
Epoch 13/100, Loss: 2.167479529976845
Epoch 14/100, Loss: 1.991030491888523

Epoch 15/100, Loss: 2.0012550577521324
Epoch 16/100, Loss: 2.1076466366648674
Epoch 17/100, Loss: 2.1057586893439293
Epoch 18/100, Loss: 2.0949887484312057
Epoch 19/100, Loss: 2.0759870037436485
Epoch 20/100, Loss: 2.1641159281134605
Epoch 21/100, Loss: 2.110531099140644
Epoch 22/100, Loss: 2.215063191950321
Epoch 23/100, Loss: 2.0279634222388268
Epoch 24/100, Loss: 2.1062864661216736
Epoch 25/100, Loss: 2.018911212682724
Epoch 26/100, Loss: 2.068104200065136
Epoch 27/100, Loss: 2.0511369183659554
Epoch 28/100, Loss: 2.16535135358572

Epoch 29/100, Loss: 2.0639693289995193
Epoch 30/100, Loss: 2.019662894308567
Epoch 31/100, Loss: 1.9614584743976593
Epoch 32/100, Loss: 2.0618440210819244
Epoch 33/100, Loss: 1.97887621819973
Epoch 34/100, Loss: 2.151730515062809
Epoch 35/100, Loss: 2.159222759306431
Epoch 36/100, Loss: 2.139670543372631
Epoch 37/100, Loss: 1.8888274803757668
Epoch 38/100, Loss: 2.2727692052721977
Epoch 39/100, Loss: 2.0561500936746597

Epoch 40/100, Loss: 2.0747069492936134
Epoch 41/100, Loss: 1.9838208332657814
Epoch 42/100, Loss: 2.3524255454540253
Epoch 43/100, Loss: 2.1430211067199707
Epoch 44/100, Loss: 2.143609382212162
Epoch 45/100, Loss: 2.175408788025379
Epoch 46/100, Loss: 2.0427447706460953
Epoch 47/100, Loss: 2.0843505859375
Epoch 48/100, Loss: 2.2211541905999184
Epoch 49/100, Loss: 2.0113355442881584
Epoch 50/100, Loss: 2.197759509086609
Epoch 51/100, Loss: 2.572612889111042
Epoch 52/100, Loss: 2.0471275448799133
Epoch 53/100, Loss: 2.2299692183732986

Epoch 54/100, Loss: 2.2357150614261627
Epoch 55/100, Loss: 2.1386189833283424
Epoch 56/100, Loss: 2.001720108091831
Epoch 57/100, Loss: 2.0203107967972755
Epoch 58/100, Loss: 1.9097867608070374
Epoch 59/100, Loss: 2.0432877019047737
Epoch 60/100, Loss: 1.992026999592781
Epoch 61/100, Loss: 2.1977498680353165
Epoch 62/100, Loss: 1.9518955424427986
Epoch 63/100, Loss: 2.053134225308895
Epoch 64/100, Loss: 2.1909985318779945
Epoch 65/100, Loss: 2.176840715110302
Epoch 66/100, Loss: 2.0126932486891747

Epoch 67/100, Loss: 2.1548181027173996
Epoch 68/100, Loss: 2.0842693522572517
Epoch 69/100, Loss: 2.2254810854792595
Epoch 70/100, Loss: 2.2039885967969894
Epoch 71/100, Loss: 2.1893020793795586
Epoch 72/100, Loss: 2.427778832614422
Epoch 73/100, Loss: 2.045793153345585
Epoch 74/100, Loss: 2.1366530880331993
Epoch 75/100, Loss: 2.200989916920662
Epoch 76/100, Loss: 2.1919055432081223
Epoch 77/100, Loss: 2.134892724454403
Epoch 78/100, Loss: 1.9962477535009384

Epoch 79/100, Loss: 2.0741963535547256
Epoch 80/100, Loss: 2.0575564429163933
Epoch 81/100, Loss: 2.0818216279149055
Epoch 82/100, Loss: 1.9801960811018944
Epoch 83/100, Loss: 2.1665087044239044
Epoch 84/100, Loss: 2.14708012342453
Epoch 85/100, Loss: 2.213561788201332
Epoch 86/100, Loss: 2.0196679830551147
Epoch 87/100, Loss: 1.949081413447857
Epoch 88/100, Loss: 2.134653188288212
Epoch 89/100, Loss: 2.1034336015582085
Epoch 90/100, Loss: 2.067862279713154

Epoch 91/100, Loss: 2.158849775791168
Epoch 92/100, Loss: 2.1582530215382576
Epoch 93/100, Loss: 2.054611846804619
Epoch 94/100, Loss: 1.9449871852993965
Epoch 95/100, Loss: 2.011600226163864
Epoch 96/100, Loss: 1.9479475244879723
Epoch 97/100, Loss: 2.670181430876255
Epoch 98/100, Loss: 2.078750677406788
Epoch 99/100, Loss: 2.046163685619831
Epoch 100/100, Loss: 2.141401991248131
Fold 3/5 done
Epoch 1/100, Loss: 2.879396229982376

Epoch 2/100, Loss: 2.8777303993701935
Epoch 3/100, Loss: 3.098528213799
Epoch 4/100, Loss: 2.8389275297522545
Epoch 5/100, Loss: 2.9252450317144394
Epoch 6/100, Loss: 2.8923453986644745
Epoch 7/100, Loss: 2.8170199543237686
Epoch 8/100, Loss: 3.020730674266815
Epoch 9/100, Loss: 2.9925514459609985
Epoch 10/100, Loss: 2.9546468406915665
Epoch 11/100, Loss: 3.087916225194931
Epoch 12/100, Loss: 2.9725789055228233
Epoch 13/100, Loss: 2.6675129011273384

Epoch 14/100, Loss: 2.857607424259186
Epoch 15/100, Loss: 2.8622363805770874
Epoch 16/100, Loss: 2.966875731945038
Epoch 17/100, Loss: 2.8690491765737534
Epoch 18/100, Loss: 3.0269448831677437
Epoch 19/100, Loss: 2.923013523221016
Epoch 20/100, Loss: 2.829139456152916
Epoch 21/100, Loss: 2.923613667488098
Epoch 22/100, Loss: 3.018573522567749
Epoch 23/100, Loss: 3.039380133152008
Epoch 24/100, Loss: 2.803112730383873
Epoch 25/100, Loss: 2.8878240287303925

Epoch 26/100, Loss: 2.9534168392419815
Epoch 27/100, Loss: 2.818127989768982
Epoch 28/100, Loss: 3.0657411366701126
Epoch 29/100, Loss: 2.7247157022356987
Epoch 30/100, Loss: 2.9417482912540436
Epoch 31/100, Loss: 2.9528592377901077
Epoch 32/100, Loss: 2.8492512330412865
Epoch 33/100, Loss: 2.9112297743558884
Epoch 34/100, Loss: 3.01145538687706
Epoch 35/100, Loss: 3.0172208696603775
Epoch 36/100, Loss: 2.8801964595913887
Epoch 37/100, Loss: 2.85320682823658
Epoch 38/100, Loss: 2.843965023756027
Epoch 39/100, Loss: 2.911047838628292
Epoch 40/100, Loss: 2.8049879521131516

Epoch 41/100, Loss: 3.035501852631569
Epoch 42/100, Loss: 2.995339572429657
Epoch 43/100, Loss: 2.761061206459999
Epoch 44/100, Loss: 2.9625230208039284
Epoch 45/100, Loss: 2.9496058225631714
Epoch 46/100, Loss: 2.947828844189644
Epoch 47/100, Loss: 3.292591482400894
Epoch 48/100, Loss: 2.9147273898124695
Epoch 49/100, Loss: 3.061354637145996
Epoch 50/100, Loss: 2.9169491603970528
Epoch 51/100, Loss: 3.007130116224289
Epoch 52/100, Loss: 2.8328032791614532
Epoch 53/100, Loss: 2.923281766474247

Epoch 54/100, Loss: 3.037880837917328
Epoch 55/100, Loss: 2.8241586834192276
Epoch 56/100, Loss: 3.098258689045906
Epoch 57/100, Loss: 2.9844466000795364
Epoch 58/100, Loss: 2.766840323805809
Epoch 59/100, Loss: 2.9092319309711456
Epoch 60/100, Loss: 2.9182967096567154
Epoch 61/100, Loss: 2.985650449991226
Epoch 62/100, Loss: 2.8089709877967834
Epoch 63/100, Loss: 2.840678386390209
Epoch 64/100, Loss: 2.870283454656601

Epoch 65/100, Loss: 3.0092547982931137
Epoch 66/100, Loss: 2.8328783810138702
Epoch 67/100, Loss: 3.08410881459713
Epoch 68/100, Loss: 2.8470818996429443
Epoch 69/100, Loss: 3.00583715736866
Epoch 70/100, Loss: 3.052538216114044
Epoch 71/100, Loss: 2.976617231965065
Epoch 72/100, Loss: 2.914707764983177
Epoch 73/100, Loss: 2.964134603738785
Epoch 74/100, Loss: 3.0932256877422333
Epoch 75/100, Loss: 3.0289047062397003

Epoch 76/100, Loss: 2.8519036695361137
Epoch 77/100, Loss: 2.9756047278642654
Epoch 78/100, Loss: 2.8501188829541206
Epoch 79/100, Loss: 2.923208601772785
Epoch 80/100, Loss: 2.8892959505319595
Epoch 81/100, Loss: 2.9368696361780167
Epoch 82/100, Loss: 2.9273400753736496
Epoch 83/100, Loss: 2.887073516845703
Epoch 84/100, Loss: 2.834282122552395
Epoch 85/100, Loss: 2.9237067103385925
Epoch 86/100, Loss: 2.9487009793519974

Epoch 87/100, Loss: 2.973815143108368
Epoch 88/100, Loss: 3.074029043316841
Epoch 89/100, Loss: 2.8496286123991013
Epoch 90/100, Loss: 2.8264854103326797
Epoch 91/100, Loss: 2.8726654648780823
Epoch 92/100, Loss: 2.978281781077385
Epoch 93/100, Loss: 2.9349378049373627
Epoch 94/100, Loss: 2.8807903230190277
Epoch 95/100, Loss: 2.818686783313751
Epoch 96/100, Loss: 2.9515291526913643
Epoch 97/100, Loss: 2.917381428182125
Epoch 98/100, Loss: 2.919917017221451

Epoch 99/100, Loss: 2.9530917555093765
Epoch 100/100, Loss: 2.8732114657759666
Fold 4/5 done
Epoch 1/100, Loss: 2.218086004257202
Epoch 2/100, Loss: 2.146233059465885
Epoch 3/100, Loss: 2.0389532521367073
Epoch 4/100, Loss: 2.0636016502976418
Epoch 5/100, Loss: 2.1825426518917084
Epoch 6/100, Loss: 2.0943549424409866
Epoch 7/100, Loss: 2.1176485642790794
Epoch 8/100, Loss: 2.0190680027008057
Epoch 9/100, Loss: 2.2391821667551994

Epoch 10/100, Loss: 2.1588883623480797
Epoch 11/100, Loss: 2.0525666177272797
Epoch 12/100, Loss: 2.1440141648054123
Epoch 13/100, Loss: 2.086343504488468
Epoch 14/100, Loss: 2.2845860943198204
Epoch 15/100, Loss: 1.9833882004022598
Epoch 16/100, Loss: 2.1177000999450684
Epoch 17/100, Loss: 2.0630931183695793
Epoch 18/100, Loss: 2.1302767023444176
Epoch 19/100, Loss: 2.061375841498375
Epoch 20/100, Loss: 2.122127763926983
Epoch 21/100, Loss: 2.1351545453071594

Epoch 22/100, Loss: 2.002641774713993
Epoch 23/100, Loss: 2.114341624081135
Epoch 24/100, Loss: 2.2106135487556458
Epoch 25/100, Loss: 2.022884912788868
Epoch 26/100, Loss: 2.1219586804509163
Epoch 27/100, Loss: 2.187747687101364
Epoch 28/100, Loss: 2.1522285789251328
Epoch 29/100, Loss: 2.1647974103689194
Epoch 30/100, Loss: 2.177036829292774
Epoch 31/100, Loss: 2.24856611341238
Epoch 32/100, Loss: 2.0447490140795708
Epoch 33/100, Loss: 2.0921853110194206

Epoch 34/100, Loss: 2.0995666161179543
Epoch 35/100, Loss: 2.1212755143642426
Epoch 36/100, Loss: 2.1546171233057976
Epoch 37/100, Loss: 2.0825662910938263
Epoch 38/100, Loss: 2.1053971722722054
Epoch 39/100, Loss: 2.1421447321772575
Epoch 40/100, Loss: 2.1625735983252525
Epoch 41/100, Loss: 2.032958433032036
Epoch 42/100, Loss: 2.060432218015194
Epoch 43/100, Loss: 2.1222429051995277
Epoch 44/100, Loss: 2.054679714143276
Epoch 45/100, Loss: 1.9913929626345634

Epoch 46/100, Loss: 2.1458038613200188
Epoch 47/100, Loss: 2.061771832406521
Epoch 48/100, Loss: 2.219875618815422
Epoch 49/100, Loss: 2.1733668446540833
Epoch 50/100, Loss: 1.9971708357334137
Epoch 51/100, Loss: 2.191361904144287
Epoch 52/100, Loss: 2.043178290128708
Epoch 53/100, Loss: 1.9649239033460617
Epoch 54/100, Loss: 2.162031002342701
Epoch 55/100, Loss: 2.1539072394371033
Epoch 56/100, Loss: 2.0973666310310364
Epoch 57/100, Loss: 2.124430112540722

Epoch 58/100, Loss: 2.0192531794309616
Epoch 59/100, Loss: 2.0074498876929283
Epoch 60/100, Loss: 2.0608309507369995
Epoch 61/100, Loss: 2.177150011062622
Epoch 62/100, Loss: 2.071597643196583
Epoch 63/100, Loss: 2.052926354110241
Epoch 64/100, Loss: 2.1433739364147186
Epoch 65/100, Loss: 2.114037111401558
Epoch 66/100, Loss: 2.1341497749090195
Epoch 67/100, Loss: 2.0690767094492912
Epoch 68/100, Loss: 2.098940595984459
Epoch 69/100, Loss: 2.044538915157318
Epoch 70/100, Loss: 2.1797594279050827
Epoch 71/100, Loss: 2.1171073243021965
Epoch 72/100, Loss: 2.0816774740815163
Epoch 73/100, Loss: 2.3203962296247482
Epoch 74/100, Loss: 2.097874879837036

Epoch 75/100, Loss: 2.1062845960259438
Epoch 76/100, Loss: 1.9830825552344322
Epoch 77/100, Loss: 2.040193483233452
Epoch 78/100, Loss: 2.1362826600670815
Epoch 79/100, Loss: 2.1297972425818443
Epoch 80/100, Loss: 2.1507687717676163
Epoch 81/100, Loss: 2.054323695600033
Epoch 82/100, Loss: 2.2144846841692924
Epoch 83/100, Loss: 2.0170069336891174
Epoch 84/100, Loss: 2.079614944756031
Epoch 85/100, Loss: 2.219583176076412
Epoch 86/100, Loss: 2.2273652106523514
Epoch 87/100, Loss: 2.1799968257546425
Epoch 88/100, Loss: 2.1206018030643463
Epoch 89/100, Loss: 2.1514230966567993

Epoch 90/100, Loss: 2.164983779191971
Epoch 91/100, Loss: 2.175075612962246
Epoch 92/100, Loss: 2.0341009199619293
Epoch 93/100, Loss: 2.055366925895214
Epoch 94/100, Loss: 2.1180111467838287
Epoch 95/100, Loss: 2.197652667760849
Epoch 96/100, Loss: 2.0567188188433647
Epoch 97/100, Loss: 2.1588582769036293
Epoch 98/100, Loss: 2.0918185487389565
Epoch 99/100, Loss: 2.131632551550865
Epoch 100/100, Loss: 2.0320114344358444
Fold 5/5 done

In [11]:
ap = average_precision_score(y_true, anomaly_scores)
print(f"Deep SVDD AP (5-fold CV) = {ap:.4f}")
sb.glue("GBG500_ap_spectral_deep_svdd", float(ap))

Deep SVDD AP (5-fold CV) = 0.5459