In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import average_precision_score
from sklearn.model_selection import StratifiedKFold
from pyod.models.deep_svdd import DeepSVDD
import sys
import scrapbook as sb

sys.path.append('..')
from utils import reshape_to_numpy, interpolate_missing_values, denoise_data, compute_spectrograms, time_avg_pooling

In [2]:
seed = 1
sampling_rate = 10
nperseg=64
noverlap=32
accel_cutoff = 0.4
accel_order = 30
gyro_cutoff = 0.6
gyro_order = 20
batch_size = 32
epochs = 100
hidden_neurons = [128, 64, 32]
n_splits = 5

In [3]:
# Parameters
seed = 10

In [4]:
rng = np.random.RandomState(seed)

In [5]:
data = pd.read_parquet("../data/GBG500.parquet")
data

,ride_id,time_index,ax,ay,az,rx,ry,rz
0,005043f1a7520cebf1e17fd166a00a3190e2433530f236...,0,-2.512796,-9.385012,-1.053078,-0.009155,0.009155,-0.201416
1,005043f1a7520cebf1e17fd166a00a3190e2433530f236...,100,-2.491268,-9.385012,-1.079390,-0.036621,0.027465,-0.155639
2,005043f1a7520cebf1e17fd166a00a3190e2433530f236...,200,-2.534324,-9.382022,-1.030952,0.036621,0.027465,-0.073242
3,005043f1a7520cebf1e17fd166a00a3190e2433530f236...,300,-2.488278,-9.383218,-1.091948,-0.045776,0.036621,-0.183105
4,005043f1a7520cebf1e17fd166a00a3190e2433530f236...,400,-2.483494,-9.382022,-1.100320,-0.045776,0.027465,-0.192260
...,...,...,...,...,...,...,...,...
1529542,ffb6f2f5dc6ba768d88dc0bc1af4cad235526aa9e24168...,241300,0.459862,-9.140430,-3.318900,1.556396,-0.091552,0.274658
1529543,ffb6f2f5dc6ba768d88dc0bc1af4cad235526aa9e24168...,241400,0.455676,-9.140430,-3.321292,1.583861,-0.119018,0.274658
1529544,ffb6f2f5dc6ba768d88dc0bc1af4cad235526aa9e24168...,241500,0.459862,-9.139832,-3.317704,1.583861,-0.109863,0.274658
1529545,ffb6f2f5dc6ba768d88dc0bc1af4cad235526aa9e24168...,241600,0.456274,-9.142224,-3.321292,1.574707,-0.137329,0.283813
1529546,ffb6f2f5dc6ba768d88dc0bc1af4cad235526aa9e24168...,241700,0.458666,-9.139832,-3.320694,1.574707,-0.137329,0.274658

In [6]:
labels = pd.read_csv("../data/GBG500_labels.csv")
labels.columns = labels.columns.str.lower()
ride_order_df = pd.DataFrame({"ride_id": data["ride_id"].unique()})
labels_sorted = ride_order_df.merge(
    labels,
    on="ride_id",
    how="left"
)
labels_sorted

                                               ride_id        label
0    005043f1a7520cebf1e17fd166a00a3190e2433530f236...         Safe
1    00d223cb7aecc9c0cc5871e32a6c45027a068eba07c572...     Reckless
2    02288a4aeca044203394e982e76b87818021dea2b34df9...         Safe
3    0236bdcf13d473ea24d97f5eaeea459f257dffac005694...  Bad weather
4    0238e5dd85143f1b6c59b200bc32f14361b8fc84c51a87...         Safe
..                                                 ...          ...
495  fe5d7f84d692bbccad8bd566a3ad5c3108fa9f90acd671...         Safe
496  fe67169632306d4668b2affedef510df2cb43e2fb41220...         Safe
497  fee44667fdc8ab4995c702fc3bd36178de0b1ca2c64687...         Safe
498  ff79b2e945b93c2a5efc3a06365267b3a160e7849ba57d...         Safe
499  ffb6f2f5dc6ba768d88dc0bc1af4cad235526aa9e24168...         Safe

[500 rows x 2 columns]

In [7]:
data_np = reshape_to_numpy(
    data,
    features = ["ax", "ay", "az", "rx", "ry", "rz"],
    max_timestamps = 4800
)

data_np_clean = interpolate_missing_values(
    data_np,
    method='linear',
    limit=None
)

data_np_clean = denoise_data(
    data=data_np_clean,
    accel_indices=[0, 1, 2],
    gyro_indices=[3, 4, 5],
    accel_cutoff=accel_cutoff,
    accel_order=accel_order,
    gyro_cutoff=gyro_cutoff,
    gyro_order=gyro_order,
)

In [8]:
# Compute spectrograms for all rides
spectrograms_array = compute_spectrograms(data_np_clean, sampling_rate, nperseg, noverlap)
spectrograms_array.shape

(500, 149, 6, 33)

In [9]:
# Aggregate spectrograms using time-averaged pooling
X_feat = time_avg_pooling(spectrograms_array)
X_feat.shape

(500, 198)

In [10]:
# 5-fold stratified CV with Deep SVDD
skf = StratifiedKFold(n_splits=n_splits, shuffle=True, random_state=rng.randint(1000))
y_true = (labels_sorted['label'] == 'Reckless').astype(int).values
anomaly_scores = np.full(len(y_true), np.nan)

for fold, (train_idx, test_idx) in enumerate(skf.split(X_feat, y_true)):
    sc = StandardScaler()
    X_train = sc.fit_transform(X_feat[train_idx])
    X_test = sc.transform(X_feat[test_idx])

    np.random.seed(rng.randint(1000))
    model = DeepSVDD(
        n_features=X_train.shape[1],
        hidden_neurons=hidden_neurons,
        epochs=epochs,
        batch_size=batch_size,
        random_state=rng.randint(1000),
    )
    model.fit(X_train)
    anomaly_scores[test_idx] = model.decision_function(X_test)
    print(f"Fold {fold+1}/{n_splits} done")

Epoch 1/100, Loss: 2.7337168753147125
Epoch 2/100, Loss: 2.7302338406443596
Epoch 3/100, Loss: 3.0357079580426216
Epoch 4/100, Loss: 3.2690871357917786
Epoch 5/100, Loss: 2.5035408437252045
Epoch 6/100, Loss: 3.2735675126314163
Epoch 7/100, Loss: 2.5745821744203568
Epoch 8/100, Loss: 2.559894844889641
Epoch 9/100, Loss: 2.7290377616882324
Epoch 10/100, Loss: 2.8923652544617653
Epoch 11/100, Loss: 3.077162116765976
Epoch 12/100, Loss: 2.746838830411434
Epoch 13/100, Loss: 2.92381202429533
Epoch 14/100, Loss: 2.4565949514508247
Epoch 15/100, Loss: 2.4977508261799812
Epoch 16/100, Loss: 2.5896700844168663
Epoch 17/100, Loss: 3.6647697910666466

Epoch 18/100, Loss: 2.538254290819168
Epoch 19/100, Loss: 3.1665839180350304
Epoch 20/100, Loss: 2.621709242463112
Epoch 21/100, Loss: 2.800230532884598
Epoch 22/100, Loss: 2.862464725971222
Epoch 23/100, Loss: 2.801221713423729
Epoch 24/100, Loss: 3.088426485657692
Epoch 25/100, Loss: 2.6065587624907494
Epoch 26/100, Loss: 3.438803344964981
Epoch 27/100, Loss: 2.7559598609805107
Epoch 28/100, Loss: 2.810886934399605
Epoch 29/100, Loss: 2.7731908708810806
Epoch 30/100, Loss: 3.274043545126915

Epoch 31/100, Loss: 2.803301766514778
Epoch 32/100, Loss: 2.747450463473797
Epoch 33/100, Loss: 3.156467705965042
Epoch 34/100, Loss: 2.8124116882681847
Epoch 35/100, Loss: 2.6648919880390167
Epoch 36/100, Loss: 3.0633168518543243
Epoch 37/100, Loss: 3.2623305320739746
Epoch 38/100, Loss: 2.563201457262039
Epoch 39/100, Loss: 2.736765719950199
Epoch 40/100, Loss: 2.752391129732132
Epoch 41/100, Loss: 3.106877364218235
Epoch 42/100, Loss: 2.8098677694797516
Epoch 43/100, Loss: 2.9984136894345284
Epoch 44/100, Loss: 3.0638600140810013
Epoch 45/100, Loss: 3.186799369752407
Epoch 46/100, Loss: 2.9063624814152718

Epoch 47/100, Loss: 2.4907381758093834
Epoch 48/100, Loss: 2.8318695202469826
Epoch 49/100, Loss: 3.312658116221428
Epoch 50/100, Loss: 2.6203112974762917
Epoch 51/100, Loss: 2.7435004338622093
Epoch 52/100, Loss: 2.629369743168354
Epoch 53/100, Loss: 2.9081513956189156
Epoch 54/100, Loss: 2.60598386824131
Epoch 55/100, Loss: 2.5275545865297318
Epoch 56/100, Loss: 2.789253629744053
Epoch 57/100, Loss: 3.126452349126339
Epoch 58/100, Loss: 3.1295663863420486
Epoch 59/100, Loss: 3.1253997907042503
Epoch 60/100, Loss: 3.2813093215227127
Epoch 61/100, Loss: 2.840199537575245
Epoch 62/100, Loss: 2.8054833188652992
Epoch 63/100, Loss: 2.7908602505922318
Epoch 64/100, Loss: 2.680377572774887

Epoch 65/100, Loss: 2.6463449969887733
Epoch 66/100, Loss: 2.971904829144478
Epoch 67/100, Loss: 2.843291997909546
Epoch 68/100, Loss: 2.919420689344406
Epoch 69/100, Loss: 3.1346609070897102
Epoch 70/100, Loss: 2.9815763980150223
Epoch 71/100, Loss: 2.707494981586933
Epoch 72/100, Loss: 2.8484889194369316
Epoch 73/100, Loss: 2.5308615416288376
Epoch 74/100, Loss: 3.008345253765583
Epoch 75/100, Loss: 2.7854294031858444
Epoch 76/100, Loss: 2.540107846260071
Epoch 77/100, Loss: 2.468180052936077
Epoch 78/100, Loss: 3.1235897466540337
Epoch 79/100, Loss: 3.234384000301361
Epoch 80/100, Loss: 2.45659851282835
Epoch 81/100, Loss: 2.882581204175949
Epoch 82/100, Loss: 3.115098938345909

Epoch 83/100, Loss: 2.668861672282219
Epoch 84/100, Loss: 2.708075612783432
Epoch 85/100, Loss: 2.72624384611845
Epoch 86/100, Loss: 2.942381888628006
Epoch 87/100, Loss: 3.097282037138939
Epoch 88/100, Loss: 2.6419175639748573
Epoch 89/100, Loss: 3.221235603094101
Epoch 90/100, Loss: 3.0640409141778946
Epoch 91/100, Loss: 2.8455171808600426
Epoch 92/100, Loss: 3.0149168595671654
Epoch 93/100, Loss: 2.5780608654022217
Epoch 94/100, Loss: 3.276522882282734
Epoch 95/100, Loss: 2.8458411023020744
Epoch 96/100, Loss: 2.7722008153796196
Epoch 97/100, Loss: 2.792638786137104
Epoch 98/100, Loss: 2.564440332353115
Epoch 99/100, Loss: 3.0378440991044044
Epoch 100/100, Loss: 3.095322273671627
Fold 1/5 done

Epoch 1/100, Loss: 1.9837545156478882
Epoch 2/100, Loss: 1.8603809252381325
Epoch 3/100, Loss: 2.072944797575474
Epoch 4/100, Loss: 2.0624415054917336
Epoch 5/100, Loss: 2.1512653678655624
Epoch 6/100, Loss: 2.066312976181507
Epoch 7/100, Loss: 1.866735778748989
Epoch 8/100, Loss: 2.12044208496809
Epoch 9/100, Loss: 2.0443814024329185
Epoch 10/100, Loss: 1.95369553565979
Epoch 11/100, Loss: 2.087759420275688
Epoch 12/100, Loss: 2.0375486239790916
Epoch 13/100, Loss: 1.9520395025610924
Epoch 14/100, Loss: 1.9878519400954247
Epoch 15/100, Loss: 1.8861056417226791
Epoch 16/100, Loss: 2.090158574283123
Epoch 17/100, Loss: 1.9057092666625977
Epoch 18/100, Loss: 2.044049307703972

Epoch 19/100, Loss: 1.9780122190713882
Epoch 20/100, Loss: 2.0159852653741837
Epoch 21/100, Loss: 2.082035630941391
Epoch 22/100, Loss: 2.045867048203945
Epoch 23/100, Loss: 2.0546721145510674
Epoch 24/100, Loss: 1.8913154602050781
Epoch 25/100, Loss: 1.9283621981739998
Epoch 26/100, Loss: 1.9142721816897392
Epoch 27/100, Loss: 2.040998660027981
Epoch 28/100, Loss: 2.0728994831442833
Epoch 29/100, Loss: 1.8559977561235428
Epoch 30/100, Loss: 1.9096719697117805
Epoch 31/100, Loss: 1.8612183332443237
Epoch 32/100, Loss: 1.9752028584480286
Epoch 33/100, Loss: 2.126697674393654
Epoch 34/100, Loss: 1.964762918651104

Epoch 35/100, Loss: 2.0608277320861816
Epoch 36/100, Loss: 2.0147358775138855
Epoch 37/100, Loss: 1.9898963794112206
Epoch 38/100, Loss: 2.0086621791124344
Epoch 39/100, Loss: 1.9029825180768967
Epoch 40/100, Loss: 1.9687283635139465
Epoch 41/100, Loss: 1.954487405717373
Epoch 42/100, Loss: 2.064955919981003
Epoch 43/100, Loss: 1.9859369471669197
Epoch 44/100, Loss: 2.034032441675663
Epoch 45/100, Loss: 1.9050393402576447
Epoch 46/100, Loss: 1.9349608346819878
Epoch 47/100, Loss: 2.010938599705696
Epoch 48/100, Loss: 2.0460969731211662
Epoch 49/100, Loss: 1.7804818153381348
Epoch 50/100, Loss: 1.9638010412454605
Epoch 51/100, Loss: 2.1525032222270966

Epoch 52/100, Loss: 1.84945959597826
Epoch 53/100, Loss: 1.9727271422743797
Epoch 54/100, Loss: 1.9943233206868172
Epoch 55/100, Loss: 2.004136599600315
Epoch 56/100, Loss: 1.9660861417651176
Epoch 57/100, Loss: 1.877300150692463
Epoch 58/100, Loss: 1.9200091361999512
Epoch 59/100, Loss: 2.0699621811509132
Epoch 60/100, Loss: 1.7513052746653557
Epoch 61/100, Loss: 2.018376760184765
Epoch 62/100, Loss: 1.7759296298027039
Epoch 63/100, Loss: 1.9223843216896057
Epoch 64/100, Loss: 1.9371087849140167
Epoch 65/100, Loss: 2.094064086675644
Epoch 66/100, Loss: 2.053202137351036
Epoch 67/100, Loss: 2.1890290826559067
Epoch 68/100, Loss: 2.0582819879055023
Epoch 69/100, Loss: 2.053562253713608

Epoch 70/100, Loss: 1.9130006954073906
Epoch 71/100, Loss: 2.073950842022896
Epoch 72/100, Loss: 2.116559825837612
Epoch 73/100, Loss: 2.099735088646412
Epoch 74/100, Loss: 2.0685974285006523
Epoch 75/100, Loss: 1.9755876064300537
Epoch 76/100, Loss: 1.8857928588986397
Epoch 77/100, Loss: 2.075659856200218
Epoch 78/100, Loss: 2.041736848652363
Epoch 79/100, Loss: 1.98379298299551
Epoch 80/100, Loss: 2.1782241091132164
Epoch 81/100, Loss: 1.8405964151024818
Epoch 82/100, Loss: 1.9486772865056992
Epoch 83/100, Loss: 1.978951372206211
Epoch 84/100, Loss: 1.9333625882863998
Epoch 85/100, Loss: 2.1432824954390526
Epoch 86/100, Loss: 1.8852052316069603

Epoch 87/100, Loss: 1.9538865014910698
Epoch 88/100, Loss: 1.8257324993610382
Epoch 89/100, Loss: 1.833676777780056
Epoch 90/100, Loss: 1.894093744456768
Epoch 91/100, Loss: 1.9105792343616486
Epoch 92/100, Loss: 1.9915598779916763
Epoch 93/100, Loss: 2.0364410430192947
Epoch 94/100, Loss: 1.9704185873270035
Epoch 95/100, Loss: 1.9965102151036263
Epoch 96/100, Loss: 1.9436000511050224
Epoch 97/100, Loss: 1.9535238221287727
Epoch 98/100, Loss: 2.029824525117874
Epoch 99/100, Loss: 2.095183603465557
Epoch 100/100, Loss: 1.9465864449739456
Fold 2/5 done
Epoch 1/100, Loss: 1.607492621988058
Epoch 2/100, Loss: 1.9021316394209862

Epoch 3/100, Loss: 1.8892412185668945
Epoch 4/100, Loss: 1.6962904408574104
Epoch 5/100, Loss: 1.8670949190855026
Epoch 6/100, Loss: 1.8145051933825016
Epoch 7/100, Loss: 1.8076815083622932
Epoch 8/100, Loss: 1.8388194628059864
Epoch 9/100, Loss: 1.9152102395892143
Epoch 10/100, Loss: 2.3609028309583664
Epoch 11/100, Loss: 1.85720219835639
Epoch 12/100, Loss: 1.9325992949306965
Epoch 13/100, Loss: 1.8847462832927704
Epoch 14/100, Loss: 1.9054521322250366
Epoch 15/100, Loss: 1.7570489160716534
Epoch 16/100, Loss: 1.7039135321974754
Epoch 17/100, Loss: 1.8389711044728756
Epoch 18/100, Loss: 1.7037473395466805
Epoch 19/100, Loss: 1.614297404885292
Epoch 20/100, Loss: 1.9220866411924362

Epoch 21/100, Loss: 1.7415387369692326
Epoch 22/100, Loss: 1.9486671388149261
Epoch 23/100, Loss: 1.7749591208994389
Epoch 24/100, Loss: 2.0416920073330402
Epoch 25/100, Loss: 1.6667436063289642
Epoch 26/100, Loss: 1.8519888073205948
Epoch 27/100, Loss: 1.6797604151070118
Epoch 28/100, Loss: 1.6252163834869862
Epoch 29/100, Loss: 1.9439612403512
Epoch 30/100, Loss: 1.765633724629879
Epoch 31/100, Loss: 1.862583078444004
Epoch 32/100, Loss: 2.0589191541075706
Epoch 33/100, Loss: 1.7867059335112572
Epoch 34/100, Loss: 1.918301247060299
Epoch 35/100, Loss: 1.6439351364970207
Epoch 36/100, Loss: 1.7033373787999153
Epoch 37/100, Loss: 1.74460931122303
Epoch 38/100, Loss: 1.8772581554949284

Epoch 39/100, Loss: 1.7403502687811852
Epoch 40/100, Loss: 2.5231367126107216
Epoch 41/100, Loss: 1.84636040776968
Epoch 42/100, Loss: 2.0007086992263794
Epoch 43/100, Loss: 1.7710872367024422
Epoch 44/100, Loss: 1.8708775341510773
Epoch 45/100, Loss: 1.6457023099064827
Epoch 46/100, Loss: 1.9582288265228271
Epoch 47/100, Loss: 1.950029157102108
Epoch 48/100, Loss: 1.6476179175078869
Epoch 49/100, Loss: 1.8295616395771503
Epoch 50/100, Loss: 1.9243242964148521
Epoch 51/100, Loss: 1.7640946134924889
Epoch 52/100, Loss: 1.7256081849336624
Epoch 53/100, Loss: 2.2683170586824417
Epoch 54/100, Loss: 1.8406014516949654
Epoch 55/100, Loss: 1.7001972943544388
Epoch 56/100, Loss: 2.0230057016015053

Epoch 57/100, Loss: 2.2206579968333244
Epoch 58/100, Loss: 2.0843428149819374
Epoch 59/100, Loss: 1.887980729341507
Epoch 60/100, Loss: 1.7207674905657768
Epoch 61/100, Loss: 2.3739153183996677
Epoch 62/100, Loss: 1.8852841034531593
Epoch 63/100, Loss: 1.7493423819541931
Epoch 64/100, Loss: 1.8146197572350502
Epoch 65/100, Loss: 1.9778006821870804
Epoch 66/100, Loss: 1.835735760629177
Epoch 67/100, Loss: 1.9941321425139904
Epoch 68/100, Loss: 1.761278871446848
Epoch 69/100, Loss: 1.7650144211947918
Epoch 70/100, Loss: 1.8067111521959305
Epoch 71/100, Loss: 1.9228688813745975
Epoch 72/100, Loss: 1.8884018622338772
Epoch 73/100, Loss: 1.7484804578125477
Epoch 74/100, Loss: 1.8633537851274014

Epoch 75/100, Loss: 1.9643253274261951
Epoch 76/100, Loss: 1.5879006423056126
Epoch 77/100, Loss: 1.8216829299926758
Epoch 78/100, Loss: 1.7582046650350094
Epoch 79/100, Loss: 1.8702719770371914
Epoch 80/100, Loss: 1.7045412361621857
Epoch 81/100, Loss: 1.9187211692333221
Epoch 82/100, Loss: 1.7603105381131172
Epoch 83/100, Loss: 1.8462424501776695
Epoch 84/100, Loss: 1.8493109941482544
Epoch 85/100, Loss: 1.9515889212489128
Epoch 86/100, Loss: 2.187438488006592
Epoch 87/100, Loss: 1.8019844815135002
Epoch 88/100, Loss: 1.96611088514328
Epoch 89/100, Loss: 1.877349965274334
Epoch 90/100, Loss: 1.8440892174839973
Epoch 91/100, Loss: 1.9930910915136337

Epoch 92/100, Loss: 1.9794239178299904
Epoch 93/100, Loss: 1.9108321592211723
Epoch 94/100, Loss: 2.305729366838932
Epoch 95/100, Loss: 1.8835052475333214
Epoch 96/100, Loss: 1.7289043180644512
Epoch 97/100, Loss: 1.8012202940881252
Epoch 98/100, Loss: 1.9784383662045002
Epoch 99/100, Loss: 1.916542824357748
Epoch 100/100, Loss: 1.9202602095901966
Fold 3/5 done
Epoch 1/100, Loss: 2.837136887013912
Epoch 2/100, Loss: 2.8619676157832146
Epoch 3/100, Loss: 2.8085938543081284
Epoch 4/100, Loss: 2.8466159477829933
Epoch 5/100, Loss: 2.907217562198639
Epoch 6/100, Loss: 2.9690420627593994
Epoch 7/100, Loss: 3.0075284987688065

Epoch 8/100, Loss: 2.795919455587864
Epoch 9/100, Loss: 2.7960255667567253
Epoch 10/100, Loss: 3.545301139354706
Epoch 11/100, Loss: 2.8809545189142227
Epoch 12/100, Loss: 3.0323819518089294
Epoch 13/100, Loss: 2.968839481472969
Epoch 14/100, Loss: 2.9806921631097794
Epoch 15/100, Loss: 2.924722284078598
Epoch 16/100, Loss: 2.7440356239676476
Epoch 17/100, Loss: 2.7511897534132004
Epoch 18/100, Loss: 3.1543330773711205
Epoch 19/100, Loss: 3.0283977687358856
Epoch 20/100, Loss: 2.630940966308117
Epoch 21/100, Loss: 2.71891737729311
Epoch 22/100, Loss: 2.8707693740725517
Epoch 23/100, Loss: 2.785368174314499
Epoch 24/100, Loss: 2.66501148045063

Epoch 25/100, Loss: 2.907755360007286
Epoch 26/100, Loss: 2.7921335697174072
Epoch 27/100, Loss: 2.886750929057598
Epoch 28/100, Loss: 2.8428584411740303
Epoch 29/100, Loss: 2.9697190448641777
Epoch 30/100, Loss: 3.0865931287407875
Epoch 31/100, Loss: 2.8875520899891853
Epoch 32/100, Loss: 2.7418809682130814
Epoch 33/100, Loss: 2.637532614171505
Epoch 34/100, Loss: 2.792128637433052
Epoch 35/100, Loss: 2.728854462504387
Epoch 36/100, Loss: 2.8808131217956543
Epoch 37/100, Loss: 3.1137225925922394
Epoch 38/100, Loss: 2.909815177321434
Epoch 39/100, Loss: 2.850399561226368
Epoch 40/100, Loss: 2.7148016914725304
Epoch 41/100, Loss: 3.079538568854332

Epoch 42/100, Loss: 3.4310891702771187
Epoch 43/100, Loss: 3.0351257994771004
Epoch 44/100, Loss: 2.898262582719326
Epoch 45/100, Loss: 2.8260294646024704
Epoch 46/100, Loss: 3.1575942635536194
Epoch 47/100, Loss: 2.7635017558932304
Epoch 48/100, Loss: 2.769483856856823
Epoch 49/100, Loss: 2.751363269984722
Epoch 50/100, Loss: 2.936118520796299
Epoch 51/100, Loss: 2.9084006026387215
Epoch 52/100, Loss: 2.963177226483822
Epoch 53/100, Loss: 2.6162208020687103

Epoch 54/100, Loss: 2.9142100289463997
Epoch 55/100, Loss: 3.2016886696219444
Epoch 56/100, Loss: 2.6255193576216698
Epoch 57/100, Loss: 2.9207330644130707
Epoch 58/100, Loss: 2.835935227572918
Epoch 59/100, Loss: 3.046999827027321
Epoch 60/100, Loss: 2.612740993499756
Epoch 61/100, Loss: 3.0811967700719833
Epoch 62/100, Loss: 2.8550858348608017
Epoch 63/100, Loss: 2.8623783960938454
Epoch 64/100, Loss: 2.8779378831386566
Epoch 65/100, Loss: 2.803865469992161
Epoch 66/100, Loss: 2.955996334552765
Epoch 67/100, Loss: 2.868597574532032
Epoch 68/100, Loss: 2.7786662951111794
Epoch 69/100, Loss: 2.8279390558600426

Epoch 70/100, Loss: 2.7504076808691025
Epoch 71/100, Loss: 2.7678813487291336
Epoch 72/100, Loss: 2.8826738372445107
Epoch 73/100, Loss: 2.9976688101887703
Epoch 74/100, Loss: 2.942035995423794
Epoch 75/100, Loss: 3.0331450030207634
Epoch 76/100, Loss: 2.821279287338257
Epoch 77/100, Loss: 2.841909147799015
Epoch 78/100, Loss: 3.115211956202984
Epoch 79/100, Loss: 2.667002819478512
Epoch 80/100, Loss: 2.9144019782543182
Epoch 81/100, Loss: 3.014557920396328
Epoch 82/100, Loss: 2.804820403456688
Epoch 83/100, Loss: 2.687673382461071
Epoch 84/100, Loss: 2.933037482202053
Epoch 85/100, Loss: 2.7732896134257317
Epoch 86/100, Loss: 2.8234524726867676

Epoch 87/100, Loss: 2.7429899647831917
Epoch 88/100, Loss: 2.9451598450541496
Epoch 89/100, Loss: 2.807019390165806
Epoch 90/100, Loss: 2.9162895157933235
Epoch 91/100, Loss: 2.743852414190769
Epoch 92/100, Loss: 2.8087420016527176
Epoch 93/100, Loss: 2.7819038182497025
Epoch 94/100, Loss: 2.7224265187978745
Epoch 95/100, Loss: 3.0011930987238884
Epoch 96/100, Loss: 2.93790602684021
Epoch 97/100, Loss: 2.8802786767482758
Epoch 98/100, Loss: 2.821450613439083
Epoch 99/100, Loss: 2.8209569305181503
Epoch 100/100, Loss: 2.8881931453943253
Fold 4/5 done
Epoch 1/100, Loss: 1.940813697874546

Epoch 2/100, Loss: 1.987514890730381
Epoch 3/100, Loss: 2.078093245625496
Epoch 4/100, Loss: 2.1746701449155807
Epoch 5/100, Loss: 1.877218410372734
Epoch 6/100, Loss: 2.074446387588978
Epoch 7/100, Loss: 2.0219365134835243
Epoch 8/100, Loss: 1.9442583099007607
Epoch 9/100, Loss: 1.881723441183567
Epoch 10/100, Loss: 2.0709353536367416
Epoch 11/100, Loss: 1.9914544373750687
Epoch 12/100, Loss: 1.8539010435342789
Epoch 13/100, Loss: 2.0120747163891792
Epoch 14/100, Loss: 1.9483521804213524
Epoch 15/100, Loss: 2.028311602771282
Epoch 16/100, Loss: 1.9263622611761093
Epoch 17/100, Loss: 1.9627462849020958
Epoch 18/100, Loss: 2.032900359481573

Epoch 19/100, Loss: 1.9577667638659477
Epoch 20/100, Loss: 1.9741334691643715
Epoch 21/100, Loss: 1.9707183614373207
Epoch 22/100, Loss: 1.9015917032957077
Epoch 23/100, Loss: 2.0217158421874046
Epoch 24/100, Loss: 1.9637291580438614
Epoch 25/100, Loss: 2.0292802527546883
Epoch 26/100, Loss: 2.031376674771309
Epoch 27/100, Loss: 2.071919970214367
Epoch 28/100, Loss: 1.934984140098095
Epoch 29/100, Loss: 2.0266380831599236
Epoch 30/100, Loss: 2.184231676161289
Epoch 31/100, Loss: 2.0348090082406998
Epoch 32/100, Loss: 1.9416528716683388
Epoch 33/100, Loss: 2.061344064772129
Epoch 34/100, Loss: 2.094379723072052
Epoch 35/100, Loss: 2.022395893931389

Epoch 36/100, Loss: 1.9863765388727188
Epoch 37/100, Loss: 1.9087652489542961
Epoch 38/100, Loss: 2.1406190171837807
Epoch 39/100, Loss: 2.0112396627664566
Epoch 40/100, Loss: 2.1081808358430862
Epoch 41/100, Loss: 2.059292145073414
Epoch 42/100, Loss: 1.961548000574112
Epoch 43/100, Loss: 2.050445109605789
Epoch 44/100, Loss: 1.9779767468571663
Epoch 45/100, Loss: 1.9014254808425903
Epoch 46/100, Loss: 2.084978297352791
Epoch 47/100, Loss: 1.9245680533349514
Epoch 48/100, Loss: 1.9117961302399635
Epoch 49/100, Loss: 2.075766757130623
Epoch 50/100, Loss: 1.9089673683047295
Epoch 51/100, Loss: 1.8396358042955399
Epoch 52/100, Loss: 1.8857063576579094

Epoch 53/100, Loss: 1.9669331200420856
Epoch 54/100, Loss: 1.9659971594810486
Epoch 55/100, Loss: 1.9513743966817856
Epoch 56/100, Loss: 2.00663585960865
Epoch 57/100, Loss: 2.0324851870536804
Epoch 58/100, Loss: 2.1050940454006195
Epoch 59/100, Loss: 2.0546351447701454
Epoch 60/100, Loss: 2.0079597383737564
Epoch 61/100, Loss: 2.0662890672683716
Epoch 62/100, Loss: 1.9432703629136086
Epoch 63/100, Loss: 1.9951411038637161
Epoch 64/100, Loss: 2.061807744204998
Epoch 65/100, Loss: 1.9871901869773865
Epoch 66/100, Loss: 2.008197121322155
Epoch 67/100, Loss: 2.1942691579461098
Epoch 68/100, Loss: 2.038957104086876
Epoch 69/100, Loss: 1.9459349885582924

Epoch 70/100, Loss: 2.0692763328552246
Epoch 71/100, Loss: 1.9954404905438423
Epoch 72/100, Loss: 1.928309105336666
Epoch 73/100, Loss: 1.95933049172163
Epoch 74/100, Loss: 1.90286935120821
Epoch 75/100, Loss: 1.9840053543448448
Epoch 76/100, Loss: 1.9610862657427788
Epoch 77/100, Loss: 2.186746396124363
Epoch 78/100, Loss: 1.980754777789116
Epoch 79/100, Loss: 1.885779395699501
Epoch 80/100, Loss: 1.9037374258041382
Epoch 81/100, Loss: 1.990569956600666
Epoch 82/100, Loss: 1.9498741999268532
Epoch 83/100, Loss: 2.0263502299785614
Epoch 84/100, Loss: 1.8848160654306412
Epoch 85/100, Loss: 2.0705652460455894
Epoch 86/100, Loss: 2.0774721279740334

Epoch 87/100, Loss: 2.0138765200972557
Epoch 88/100, Loss: 2.071864202618599
Epoch 89/100, Loss: 2.0125782266259193
Epoch 90/100, Loss: 1.970723681151867
Epoch 91/100, Loss: 2.218948796391487
Epoch 92/100, Loss: 2.0287037566304207
Epoch 93/100, Loss: 1.8996108993887901
Epoch 94/100, Loss: 2.0644555389881134
Epoch 95/100, Loss: 2.0044837221503258
Epoch 96/100, Loss: 2.1798882633447647
Epoch 97/100, Loss: 1.9341654255986214
Epoch 98/100, Loss: 2.006088934838772

Epoch 99/100, Loss: 2.1258654445409775
Epoch 100/100, Loss: 2.0418042838573456
Fold 5/5 done

In [11]:
ap = average_precision_score(y_true, anomaly_scores)
print(f"Deep SVDD AP (5-fold CV) = {ap:.4f}")
sb.glue("GBG500_ap_spectral_deep_svdd", float(ap))

Deep SVDD AP (5-fold CV) = 0.7476