In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import average_precision_score
from sklearn.model_selection import StratifiedKFold
from pyod.models.deep_svdd import DeepSVDD
import sys
import scrapbook as sb

sys.path.append('..')
from utils import reshape_to_numpy, interpolate_missing_values, denoise_data, compute_spectrograms, time_avg_pooling

In [2]:
seed = 1
sampling_rate = 10
nperseg=64
noverlap=32
accel_cutoff = 0.4
accel_order = 30
gyro_cutoff = 0.6
gyro_order = 20
batch_size = 32
epochs = 100
hidden_neurons = [128, 64, 32]
n_splits = 5

In [3]:
# Parameters
seed = 3

In [4]:
rng = np.random.RandomState(seed)

In [5]:
data = pd.read_parquet("../data/GBG500.parquet")
data

,ride_id,time_index,ax,ay,az,rx,ry,rz
0,005043f1a7520cebf1e17fd166a00a3190e2433530f236...,0,-2.512796,-9.385012,-1.053078,-0.009155,0.009155,-0.201416
1,005043f1a7520cebf1e17fd166a00a3190e2433530f236...,100,-2.491268,-9.385012,-1.079390,-0.036621,0.027465,-0.155639
2,005043f1a7520cebf1e17fd166a00a3190e2433530f236...,200,-2.534324,-9.382022,-1.030952,0.036621,0.027465,-0.073242
3,005043f1a7520cebf1e17fd166a00a3190e2433530f236...,300,-2.488278,-9.383218,-1.091948,-0.045776,0.036621,-0.183105
4,005043f1a7520cebf1e17fd166a00a3190e2433530f236...,400,-2.483494,-9.382022,-1.100320,-0.045776,0.027465,-0.192260
...,...,...,...,...,...,...,...,...
1529542,ffb6f2f5dc6ba768d88dc0bc1af4cad235526aa9e24168...,241300,0.459862,-9.140430,-3.318900,1.556396,-0.091552,0.274658
1529543,ffb6f2f5dc6ba768d88dc0bc1af4cad235526aa9e24168...,241400,0.455676,-9.140430,-3.321292,1.583861,-0.119018,0.274658
1529544,ffb6f2f5dc6ba768d88dc0bc1af4cad235526aa9e24168...,241500,0.459862,-9.139832,-3.317704,1.583861,-0.109863,0.274658
1529545,ffb6f2f5dc6ba768d88dc0bc1af4cad235526aa9e24168...,241600,0.456274,-9.142224,-3.321292,1.574707,-0.137329,0.283813
1529546,ffb6f2f5dc6ba768d88dc0bc1af4cad235526aa9e24168...,241700,0.458666,-9.139832,-3.320694,1.574707,-0.137329,0.274658

In [6]:
labels = pd.read_csv("../data/GBG500_labels.csv")
labels.columns = labels.columns.str.lower()
ride_order_df = pd.DataFrame({"ride_id": data["ride_id"].unique()})
labels_sorted = ride_order_df.merge(
    labels,
    on="ride_id",
    how="left"
)
labels_sorted

                                               ride_id        label
0    005043f1a7520cebf1e17fd166a00a3190e2433530f236...         Safe
1    00d223cb7aecc9c0cc5871e32a6c45027a068eba07c572...     Reckless
2    02288a4aeca044203394e982e76b87818021dea2b34df9...         Safe
3    0236bdcf13d473ea24d97f5eaeea459f257dffac005694...  Bad weather
4    0238e5dd85143f1b6c59b200bc32f14361b8fc84c51a87...         Safe
..                                                 ...          ...
495  fe5d7f84d692bbccad8bd566a3ad5c3108fa9f90acd671...         Safe
496  fe67169632306d4668b2affedef510df2cb43e2fb41220...         Safe
497  fee44667fdc8ab4995c702fc3bd36178de0b1ca2c64687...         Safe
498  ff79b2e945b93c2a5efc3a06365267b3a160e7849ba57d...         Safe
499  ffb6f2f5dc6ba768d88dc0bc1af4cad235526aa9e24168...         Safe

[500 rows x 2 columns]

In [7]:
data_np = reshape_to_numpy(
    data,
    features = ["ax", "ay", "az", "rx", "ry", "rz"],
    max_timestamps = 4800
)

data_np_clean = interpolate_missing_values(
    data_np,
    method='linear',
    limit=None
)

data_np_clean = denoise_data(
    data=data_np_clean,
    accel_indices=[0, 1, 2],
    gyro_indices=[3, 4, 5],
    accel_cutoff=accel_cutoff,
    accel_order=accel_order,
    gyro_cutoff=gyro_cutoff,
    gyro_order=gyro_order,
)

In [8]:
# Compute spectrograms for all rides
spectrograms_array = compute_spectrograms(data_np_clean, sampling_rate, nperseg, noverlap)
spectrograms_array.shape

(500, 149, 6, 33)

In [9]:
# Aggregate spectrograms using time-averaged pooling
X_feat = time_avg_pooling(spectrograms_array)
X_feat.shape

(500, 198)

In [10]:
# 5-fold stratified CV with Deep SVDD
skf = StratifiedKFold(n_splits=n_splits, shuffle=True, random_state=rng.randint(1000))
y_true = (labels_sorted['label'] == 'Reckless').astype(int).values
anomaly_scores = np.full(len(y_true), np.nan)

for fold, (train_idx, test_idx) in enumerate(skf.split(X_feat, y_true)):
    sc = StandardScaler()
    X_train = sc.fit_transform(X_feat[train_idx])
    X_test = sc.transform(X_feat[test_idx])

    np.random.seed(rng.randint(1000))
    model = DeepSVDD(
        n_features=X_train.shape[1],
        hidden_neurons=hidden_neurons,
        epochs=epochs,
        batch_size=batch_size,
        random_state=rng.randint(1000),
    )
    model.fit(X_train)
    anomaly_scores[test_idx] = model.decision_function(X_test)
    print(f"Fold {fold+1}/{n_splits} done")

Epoch 1/100, Loss: 1.7515603825449944
Epoch 2/100, Loss: 1.9104669392108917
Epoch 3/100, Loss: 1.8990277200937271
Epoch 4/100, Loss: 1.8212538361549377
Epoch 5/100, Loss: 1.7625631764531136
Epoch 6/100, Loss: 1.8159158825874329
Epoch 7/100, Loss: 1.8337312042713165
Epoch 8/100, Loss: 1.8432239815592766
Epoch 9/100, Loss: 1.801715448498726
Epoch 10/100, Loss: 1.9521240964531898
Epoch 11/100, Loss: 1.7448914423584938
Epoch 12/100, Loss: 1.820160612463951
Epoch 13/100, Loss: 1.9187781661748886
Epoch 14/100, Loss: 1.8736721351742744
Epoch 15/100, Loss: 1.7790972292423248
Epoch 16/100, Loss: 1.858100451529026

Epoch 17/100, Loss: 1.7972641810774803
Epoch 18/100, Loss: 1.8827858194708824
Epoch 19/100, Loss: 1.7391528561711311
Epoch 20/100, Loss: 1.8635438606142998
Epoch 21/100, Loss: 1.895273707807064
Epoch 22/100, Loss: 1.8618924841284752
Epoch 23/100, Loss: 1.7889448329806328
Epoch 24/100, Loss: 1.7419726848602295
Epoch 25/100, Loss: 1.7977091819047928
Epoch 26/100, Loss: 1.8700201362371445
Epoch 27/100, Loss: 1.8974376320838928
Epoch 28/100, Loss: 1.8559366762638092
Epoch 29/100, Loss: 1.8099554926156998
Epoch 30/100, Loss: 1.7221157625317574
Epoch 31/100, Loss: 1.848528191447258

Epoch 32/100, Loss: 1.804016150534153
Epoch 33/100, Loss: 1.8852509409189224
Epoch 34/100, Loss: 1.89764154702425
Epoch 35/100, Loss: 1.8015763312578201
Epoch 36/100, Loss: 1.7985130921006203
Epoch 37/100, Loss: 1.931572251021862
Epoch 38/100, Loss: 1.8058183118700981
Epoch 39/100, Loss: 1.8330544233322144
Epoch 40/100, Loss: 1.7564648762345314
Epoch 41/100, Loss: 1.826874129474163
Epoch 42/100, Loss: 1.7586960345506668
Epoch 43/100, Loss: 1.832995429635048
Epoch 44/100, Loss: 1.8580921068787575
Epoch 45/100, Loss: 1.7149827033281326
Epoch 46/100, Loss: 1.8503417745232582
Epoch 47/100, Loss: 1.7632745504379272

Epoch 48/100, Loss: 1.8211930692195892
Epoch 49/100, Loss: 1.7871555760502815
Epoch 50/100, Loss: 2.03624127805233
Epoch 51/100, Loss: 1.841316170990467
Epoch 52/100, Loss: 1.768935687839985
Epoch 53/100, Loss: 1.7524097487330437
Epoch 54/100, Loss: 1.7770256772637367
Epoch 55/100, Loss: 1.779124230146408
Epoch 56/100, Loss: 1.7822710573673248
Epoch 57/100, Loss: 1.9992993846535683
Epoch 58/100, Loss: 1.891787402331829
Epoch 59/100, Loss: 1.869819588959217
Epoch 60/100, Loss: 1.805646888911724
Epoch 61/100, Loss: 1.7944625206291676

Epoch 62/100, Loss: 1.8401687666773796
Epoch 63/100, Loss: 1.7542677819728851
Epoch 64/100, Loss: 1.8225600942969322
Epoch 65/100, Loss: 1.8033502995967865
Epoch 66/100, Loss: 1.8360947780311108
Epoch 67/100, Loss: 1.8618725910782814
Epoch 68/100, Loss: 1.8274338021874428
Epoch 69/100, Loss: 1.921421855688095
Epoch 70/100, Loss: 1.9003936871886253
Epoch 71/100, Loss: 1.698292389512062
Epoch 72/100, Loss: 1.8409631699323654
Epoch 73/100, Loss: 1.8799307346343994

Epoch 74/100, Loss: 1.8147118911147118
Epoch 75/100, Loss: 1.7841478288173676
Epoch 76/100, Loss: 1.8502079546451569
Epoch 77/100, Loss: 1.7257926911115646
Epoch 78/100, Loss: 1.8120142668485641
Epoch 79/100, Loss: 1.8720921650528908
Epoch 80/100, Loss: 1.8058408200740814
Epoch 81/100, Loss: 1.7378283888101578
Epoch 82/100, Loss: 1.9189762622117996
Epoch 83/100, Loss: 1.7805234789848328
Epoch 84/100, Loss: 1.7603330686688423
Epoch 85/100, Loss: 1.7918282523751259
Epoch 86/100, Loss: 1.8825257197022438
Epoch 87/100, Loss: 1.9491171091794968

Epoch 88/100, Loss: 1.840879611670971
Epoch 89/100, Loss: 1.803660660982132
Epoch 90/100, Loss: 2.066652536392212
Epoch 91/100, Loss: 1.8828493803739548
Epoch 92/100, Loss: 1.7969587445259094
Epoch 93/100, Loss: 1.8597817718982697
Epoch 94/100, Loss: 1.9387279152870178
Epoch 95/100, Loss: 1.939008466899395
Epoch 96/100, Loss: 1.8775881826877594
Epoch 97/100, Loss: 1.71394445002079
Epoch 98/100, Loss: 1.7911000326275826
Epoch 99/100, Loss: 1.8079980835318565
Epoch 100/100, Loss: 1.8954734057188034
Fold 1/5 done

Epoch 1/100, Loss: 2.463042140007019
Epoch 2/100, Loss: 2.506669834256172
Epoch 3/100, Loss: 2.516272157430649
Epoch 4/100, Loss: 2.553857646882534
Epoch 5/100, Loss: 2.466062270104885
Epoch 6/100, Loss: 2.491022750735283
Epoch 7/100, Loss: 2.5097437128424644
Epoch 8/100, Loss: 2.518183708190918
Epoch 9/100, Loss: 2.505082219839096
Epoch 10/100, Loss: 2.3361801430583
Epoch 11/100, Loss: 2.4501394256949425
Epoch 12/100, Loss: 2.4214767664670944
Epoch 13/100, Loss: 2.5146735459566116

Epoch 14/100, Loss: 2.4009984359145164
Epoch 15/100, Loss: 2.399721682071686
Epoch 16/100, Loss: 2.4878308475017548
Epoch 17/100, Loss: 2.484616443514824
Epoch 18/100, Loss: 2.606890745460987
Epoch 19/100, Loss: 2.6186690479516983
Epoch 20/100, Loss: 2.6969412863254547
Epoch 21/100, Loss: 2.5721569806337357
Epoch 22/100, Loss: 2.5507409423589706
Epoch 23/100, Loss: 2.6615043580532074
Epoch 24/100, Loss: 3.216456100344658
Epoch 25/100, Loss: 2.620292194187641
Epoch 26/100, Loss: 2.241315521299839

Epoch 27/100, Loss: 2.6829048171639442
Epoch 28/100, Loss: 2.5906989201903343
Epoch 29/100, Loss: 2.4435038939118385
Epoch 30/100, Loss: 2.4950554221868515
Epoch 31/100, Loss: 2.6197398602962494
Epoch 32/100, Loss: 2.597573958337307
Epoch 33/100, Loss: 2.5215031802654266
Epoch 34/100, Loss: 3.072945974767208
Epoch 35/100, Loss: 2.660693109035492
Epoch 36/100, Loss: 2.58761964738369
Epoch 37/100, Loss: 2.4033085107803345
Epoch 38/100, Loss: 3.081684894859791
Epoch 39/100, Loss: 2.308888331055641
Epoch 40/100, Loss: 2.4359602481126785
Epoch 41/100, Loss: 2.5674809366464615

Epoch 42/100, Loss: 2.594057746231556
Epoch 43/100, Loss: 2.4358324706554413
Epoch 44/100, Loss: 2.5230284556746483
Epoch 45/100, Loss: 2.548048533499241
Epoch 46/100, Loss: 2.492345906794071
Epoch 47/100, Loss: 2.276268392801285
Epoch 48/100, Loss: 3.039876699447632
Epoch 49/100, Loss: 2.352054461836815
Epoch 50/100, Loss: 2.458973027765751
Epoch 51/100, Loss: 2.4632302597165108
Epoch 52/100, Loss: 2.2938890755176544
Epoch 53/100, Loss: 2.427262522280216
Epoch 54/100, Loss: 2.718147173523903
Epoch 55/100, Loss: 2.559317521750927
Epoch 56/100, Loss: 2.595453903079033

Epoch 57/100, Loss: 2.418199196457863
Epoch 58/100, Loss: 2.604416571557522
Epoch 59/100, Loss: 2.461147792637348
Epoch 60/100, Loss: 2.551998510956764
Epoch 61/100, Loss: 2.5107706636190414
Epoch 62/100, Loss: 2.6708248928189278
Epoch 63/100, Loss: 2.554505355656147
Epoch 64/100, Loss: 2.5067280754446983
Epoch 65/100, Loss: 2.6937109380960464
Epoch 66/100, Loss: 2.4503336027264595
Epoch 67/100, Loss: 2.4026503786444664
Epoch 68/100, Loss: 2.4971434995532036
Epoch 69/100, Loss: 2.364082746207714
Epoch 70/100, Loss: 2.5170776546001434
Epoch 71/100, Loss: 2.729661598801613
Epoch 72/100, Loss: 2.5552661269903183
Epoch 73/100, Loss: 2.5799220129847527

Epoch 74/100, Loss: 2.5836834460496902
Epoch 75/100, Loss: 2.4929504692554474
Epoch 76/100, Loss: 2.510038383305073
Epoch 77/100, Loss: 2.626637928187847
Epoch 78/100, Loss: 2.4611367359757423
Epoch 79/100, Loss: 2.435464486479759
Epoch 80/100, Loss: 2.309943214058876
Epoch 81/100, Loss: 2.5890507474541664
Epoch 82/100, Loss: 2.431352384388447
Epoch 83/100, Loss: 2.508227691054344
Epoch 84/100, Loss: 2.3614994436502457
Epoch 85/100, Loss: 2.6454382315278053
Epoch 86/100, Loss: 2.634970374405384
Epoch 87/100, Loss: 2.430346116423607
Epoch 88/100, Loss: 2.471476048231125
Epoch 89/100, Loss: 2.4231577664613724

Epoch 90/100, Loss: 2.5036438032984734
Epoch 91/100, Loss: 2.589343287050724
Epoch 92/100, Loss: 2.4846616685390472
Epoch 93/100, Loss: 2.430170826613903
Epoch 94/100, Loss: 2.3149689212441444
Epoch 95/100, Loss: 2.4782662093639374
Epoch 96/100, Loss: 2.6144999340176582
Epoch 97/100, Loss: 2.5738178119063377
Epoch 98/100, Loss: 2.5857616141438484
Epoch 99/100, Loss: 2.4694289714097977
Epoch 100/100, Loss: 2.5914795249700546
Fold 2/5 done
Epoch 1/100, Loss: 2.0283083096146584
Epoch 2/100, Loss: 2.0141483545303345

Epoch 3/100, Loss: 1.9934165067970753
Epoch 4/100, Loss: 1.7738192155957222
Epoch 5/100, Loss: 1.9940221384167671
Epoch 6/100, Loss: 2.01066642254591
Epoch 7/100, Loss: 1.814017504453659
Epoch 8/100, Loss: 1.8811654411256313
Epoch 9/100, Loss: 1.7667785845696926
Epoch 10/100, Loss: 1.9873893335461617
Epoch 11/100, Loss: 1.7001514062285423
Epoch 12/100, Loss: 1.9699688702821732
Epoch 13/100, Loss: 1.81199299544096
Epoch 14/100, Loss: 1.937311563640833
Epoch 15/100, Loss: 1.8428938798606396

Epoch 16/100, Loss: 1.9916359931230545
Epoch 17/100, Loss: 1.9182954281568527
Epoch 18/100, Loss: 1.7049120515584946
Epoch 19/100, Loss: 1.9517760463058949
Epoch 20/100, Loss: 1.8538087010383606
Epoch 21/100, Loss: 1.990831084549427
Epoch 22/100, Loss: 1.797141369432211
Epoch 23/100, Loss: 1.7579600252211094
Epoch 24/100, Loss: 2.0612258911132812
Epoch 25/100, Loss: 1.7028138786554337
Epoch 26/100, Loss: 1.7451642900705338
Epoch 27/100, Loss: 1.9221621081233025
Epoch 28/100, Loss: 2.59557668492198
Epoch 29/100, Loss: 1.859668206423521
Epoch 30/100, Loss: 1.8444037921726704
Epoch 31/100, Loss: 2.1032077744603157
Epoch 32/100, Loss: 2.0176000371575356

Epoch 33/100, Loss: 2.011952556669712
Epoch 34/100, Loss: 1.9206777811050415
Epoch 35/100, Loss: 1.736285012215376
Epoch 36/100, Loss: 1.9575281254947186
Epoch 37/100, Loss: 1.8809538073837757
Epoch 38/100, Loss: 1.9452118687331676
Epoch 39/100, Loss: 1.7367016486823559
Epoch 40/100, Loss: 2.00369992852211
Epoch 41/100, Loss: 1.8411337211728096
Epoch 42/100, Loss: 1.9221915528178215
Epoch 43/100, Loss: 1.9283921346068382
Epoch 44/100, Loss: 1.8448364809155464
Epoch 45/100, Loss: 2.047246988862753
Epoch 46/100, Loss: 2.395557150244713
Epoch 47/100, Loss: 2.072139233350754
Epoch 48/100, Loss: 2.088393162935972

Epoch 49/100, Loss: 2.690281666815281
Epoch 50/100, Loss: 1.7894200943410397
Epoch 51/100, Loss: 1.9140707477927208
Epoch 52/100, Loss: 2.1008724495768547
Epoch 53/100, Loss: 1.8779434338212013
Epoch 54/100, Loss: 1.7742153257131577
Epoch 55/100, Loss: 1.955300360918045
Epoch 56/100, Loss: 1.8506363667547703
Epoch 57/100, Loss: 1.9262450970709324
Epoch 58/100, Loss: 1.8200532421469688
Epoch 59/100, Loss: 1.7092396132647991
Epoch 60/100, Loss: 1.890581838786602
Epoch 61/100, Loss: 1.9936165064573288
Epoch 62/100, Loss: 2.255116030573845
Epoch 63/100, Loss: 2.070307683199644
Epoch 64/100, Loss: 1.759930893778801

Epoch 65/100, Loss: 2.0708949640393257
Epoch 66/100, Loss: 2.0257271230220795
Epoch 67/100, Loss: 2.03882809728384
Epoch 68/100, Loss: 2.0619803480803967
Epoch 69/100, Loss: 1.80205599963665
Epoch 70/100, Loss: 1.9778162762522697
Epoch 71/100, Loss: 1.9694925546646118
Epoch 72/100, Loss: 1.6760058477520943
Epoch 73/100, Loss: 1.8882361315190792
Epoch 74/100, Loss: 1.9170015417039394
Epoch 75/100, Loss: 1.9269620850682259
Epoch 76/100, Loss: 1.90846798568964
Epoch 77/100, Loss: 1.8018035292625427

Epoch 78/100, Loss: 1.8732192926108837
Epoch 79/100, Loss: 1.845660261809826
Epoch 80/100, Loss: 1.8699310049414635
Epoch 81/100, Loss: 1.8607997633516788
Epoch 82/100, Loss: 1.8779686093330383
Epoch 83/100, Loss: 2.106255631893873
Epoch 84/100, Loss: 1.9458441697061062
Epoch 85/100, Loss: 1.9752509109675884
Epoch 86/100, Loss: 1.675753340125084
Epoch 87/100, Loss: 1.904721800237894
Epoch 88/100, Loss: 2.058577813208103
Epoch 89/100, Loss: 1.8958300054073334
Epoch 90/100, Loss: 1.9276792779564857
Epoch 91/100, Loss: 1.897838819772005
Epoch 92/100, Loss: 1.9531595036387444
Epoch 93/100, Loss: 2.0334506668150425

Epoch 94/100, Loss: 1.8105512745678425
Epoch 95/100, Loss: 2.075253013521433
Epoch 96/100, Loss: 1.9599205441772938
Epoch 97/100, Loss: 1.9266037568449974
Epoch 98/100, Loss: 1.7771633937954903
Epoch 99/100, Loss: 1.7976727485656738
Epoch 100/100, Loss: 1.8411167785525322
Fold 3/5 done
Epoch 1/100, Loss: 2.5715413093566895
Epoch 2/100, Loss: 3.048551246523857
Epoch 3/100, Loss: 2.816063806414604
Epoch 4/100, Loss: 2.471118502318859
Epoch 5/100, Loss: 2.8864197954535484
Epoch 6/100, Loss: 2.7546461075544357
Epoch 7/100, Loss: 2.9081016555428505
Epoch 8/100, Loss: 2.8352962359786034
Epoch 9/100, Loss: 2.7774030938744545

Epoch 10/100, Loss: 2.9325952604413033
Epoch 11/100, Loss: 2.7197862192988396
Epoch 12/100, Loss: 3.0615747198462486
Epoch 13/100, Loss: 2.98039647936821
Epoch 14/100, Loss: 2.66362564265728
Epoch 15/100, Loss: 2.9224878400564194
Epoch 16/100, Loss: 3.071431837975979
Epoch 17/100, Loss: 2.7329938411712646
Epoch 18/100, Loss: 3.1268592849373817
Epoch 19/100, Loss: 2.910817801952362
Epoch 20/100, Loss: 3.0403604209423065
Epoch 21/100, Loss: 3.480114720761776
Epoch 22/100, Loss: 2.763115681707859
Epoch 23/100, Loss: 2.642748437821865

Epoch 24/100, Loss: 2.9990586563944817
Epoch 25/100, Loss: 3.006723642349243
Epoch 26/100, Loss: 2.782367080450058
Epoch 27/100, Loss: 2.834898591041565
Epoch 28/100, Loss: 3.0654677525162697
Epoch 29/100, Loss: 2.739491745829582
Epoch 30/100, Loss: 2.751871146261692
Epoch 31/100, Loss: 3.0108115896582603
Epoch 32/100, Loss: 2.6917222291231155
Epoch 33/100, Loss: 2.862810418009758
Epoch 34/100, Loss: 2.8150010257959366
Epoch 35/100, Loss: 2.884224072098732
Epoch 36/100, Loss: 2.9628009498119354
Epoch 37/100, Loss: 2.973260834813118
Epoch 38/100, Loss: 2.792896181344986
Epoch 39/100, Loss: 2.590686060488224

Epoch 40/100, Loss: 2.8923889324069023
Epoch 41/100, Loss: 2.7143904715776443
Epoch 42/100, Loss: 2.8320778608322144
Epoch 43/100, Loss: 2.901684246957302
Epoch 44/100, Loss: 3.0030277743935585
Epoch 45/100, Loss: 2.8546590730547905
Epoch 46/100, Loss: 2.9711027666926384
Epoch 47/100, Loss: 2.78474722802639
Epoch 48/100, Loss: 3.0853706374764442
Epoch 49/100, Loss: 2.6066847443580627
Epoch 50/100, Loss: 3.0706739127635956
Epoch 51/100, Loss: 2.5956407487392426
Epoch 52/100, Loss: 2.72599146515131
Epoch 53/100, Loss: 2.727441795170307
Epoch 54/100, Loss: 2.719684310257435
Epoch 55/100, Loss: 2.8096824288368225

Epoch 56/100, Loss: 3.1594044268131256
Epoch 57/100, Loss: 2.8327061906456947
Epoch 58/100, Loss: 2.9469306766986847
Epoch 59/100, Loss: 2.7441276535391808
Epoch 60/100, Loss: 2.7669523134827614
Epoch 61/100, Loss: 2.9777534902095795
Epoch 62/100, Loss: 2.953253887593746
Epoch 63/100, Loss: 2.8808073699474335
Epoch 64/100, Loss: 2.7871457934379578
Epoch 65/100, Loss: 2.298314593732357
Epoch 66/100, Loss: 2.692731335759163
Epoch 67/100, Loss: 2.7278537824749947
Epoch 68/100, Loss: 2.7978496849536896
Epoch 69/100, Loss: 2.9337282925844193
Epoch 70/100, Loss: 2.38274734467268

Epoch 71/100, Loss: 2.6289405152201653
Epoch 72/100, Loss: 3.0962482392787933
Epoch 73/100, Loss: 2.85600858181715
Epoch 74/100, Loss: 3.004739187657833
Epoch 75/100, Loss: 2.7193224877119064
Epoch 76/100, Loss: 2.9010188430547714
Epoch 77/100, Loss: 2.7192059010267258
Epoch 78/100, Loss: 2.544846050441265
Epoch 79/100, Loss: 2.8445461690425873
Epoch 80/100, Loss: 2.989543929696083
Epoch 81/100, Loss: 2.741300992667675
Epoch 82/100, Loss: 3.020204357802868
Epoch 83/100, Loss: 2.9696307331323624
Epoch 84/100, Loss: 3.1078799962997437
Epoch 85/100, Loss: 3.615592308342457
Epoch 86/100, Loss: 2.9819865822792053
Epoch 87/100, Loss: 2.7663744688034058
Epoch 88/100, Loss: 2.8999636247754097

Epoch 89/100, Loss: 2.7141007110476494
Epoch 90/100, Loss: 2.7836779356002808
Epoch 91/100, Loss: 2.8972200751304626
Epoch 92/100, Loss: 2.899412050843239
Epoch 93/100, Loss: 2.692555420100689
Epoch 94/100, Loss: 3.1751374527812004
Epoch 95/100, Loss: 2.9220107048749924
Epoch 96/100, Loss: 2.7050500363111496
Epoch 97/100, Loss: 2.612612761557102
Epoch 98/100, Loss: 2.6506385803222656
Epoch 99/100, Loss: 3.018984764814377
Epoch 100/100, Loss: 2.9602942913770676
Fold 4/5 done

Epoch 1/100, Loss: 2.8201718777418137
Epoch 2/100, Loss: 2.9390874207019806
Epoch 3/100, Loss: 3.1996123641729355
Epoch 4/100, Loss: 3.2957129552960396
Epoch 5/100, Loss: 3.2155061215162277
Epoch 6/100, Loss: 3.0161028280854225
Epoch 7/100, Loss: 3.479648157954216
Epoch 8/100, Loss: 3.3550177067518234
Epoch 9/100, Loss: 3.269933730363846
Epoch 10/100, Loss: 3.1820764988660812
Epoch 11/100, Loss: 3.210738092660904
Epoch 12/100, Loss: 3.1457454934716225
Epoch 13/100, Loss: 2.922316461801529
Epoch 14/100, Loss: 3.079325497150421
Epoch 15/100, Loss: 3.146115891635418
Epoch 16/100, Loss: 3.2042900919914246

Epoch 17/100, Loss: 3.2636528834700584
Epoch 18/100, Loss: 2.705317445099354
Epoch 19/100, Loss: 3.3515719175338745
Epoch 20/100, Loss: 3.160163104534149
Epoch 21/100, Loss: 3.1040930822491646
Epoch 22/100, Loss: 3.2217749506235123
Epoch 23/100, Loss: 2.5074894428253174
Epoch 24/100, Loss: 3.3927697017788887
Epoch 25/100, Loss: 2.8096285089850426
Epoch 26/100, Loss: 3.4577397108078003
Epoch 27/100, Loss: 2.8281955793499947
Epoch 28/100, Loss: 3.007853239774704
Epoch 29/100, Loss: 3.316128581762314

Epoch 30/100, Loss: 2.8394449949264526
Epoch 31/100, Loss: 3.3680094331502914
Epoch 32/100, Loss: 3.093258172273636
Epoch 33/100, Loss: 3.3825193643569946
Epoch 34/100, Loss: 3.239716738462448
Epoch 35/100, Loss: 2.84143877774477
Epoch 36/100, Loss: 2.996789902448654
Epoch 37/100, Loss: 3.3833324909210205
Epoch 38/100, Loss: 3.2678209841251373
Epoch 39/100, Loss: 3.1179490983486176
Epoch 40/100, Loss: 2.756670691072941
Epoch 41/100, Loss: 3.3364897966384888
Epoch 42/100, Loss: 4.203021466732025
Epoch 43/100, Loss: 2.9476373344659805
Epoch 44/100, Loss: 3.1126283705234528
Epoch 45/100, Loss: 3.5232329815626144

Epoch 46/100, Loss: 2.876725323498249
Epoch 47/100, Loss: 3.2332330271601677
Epoch 48/100, Loss: 3.2340055406093597
Epoch 49/100, Loss: 3.249439150094986
Epoch 50/100, Loss: 2.7818220406770706
Epoch 51/100, Loss: 3.1941023617982864
Epoch 52/100, Loss: 3.2713362127542496
Epoch 53/100, Loss: 3.3078852593898773
Epoch 54/100, Loss: 3.2311978936195374
Epoch 55/100, Loss: 2.738066628575325
Epoch 56/100, Loss: 3.1258737295866013
Epoch 57/100, Loss: 3.127941206097603
Epoch 58/100, Loss: 3.113676443696022
Epoch 59/100, Loss: 2.812264032661915
Epoch 60/100, Loss: 3.9764060229063034
Epoch 61/100, Loss: 3.333815887570381
Epoch 62/100, Loss: 2.8706598430871964

Epoch 63/100, Loss: 3.166857086122036
Epoch 64/100, Loss: 3.2696578353643417
Epoch 65/100, Loss: 3.155875764787197
Epoch 66/100, Loss: 3.254523366689682
Epoch 67/100, Loss: 3.0339681804180145
Epoch 68/100, Loss: 2.9474261850118637
Epoch 69/100, Loss: 3.1353594809770584
Epoch 70/100, Loss: 2.7716362178325653
Epoch 71/100, Loss: 3.2452556639909744
Epoch 72/100, Loss: 3.254907451570034
Epoch 73/100, Loss: 3.5806362479925156
Epoch 74/100, Loss: 2.8939796090126038
Epoch 75/100, Loss: 3.0942001566290855
Epoch 76/100, Loss: 3.092727445065975
Epoch 77/100, Loss: 3.3802905455231667
Epoch 78/100, Loss: 3.2012377232313156

Epoch 79/100, Loss: 3.1878518760204315
Epoch 80/100, Loss: 4.023049421608448
Epoch 81/100, Loss: 2.7271576449275017
Epoch 82/100, Loss: 2.8689316883683205
Epoch 83/100, Loss: 2.9835325106978416
Epoch 84/100, Loss: 2.7281745076179504
Epoch 85/100, Loss: 3.739524982869625
Epoch 86/100, Loss: 3.203171283006668
Epoch 87/100, Loss: 2.842701569199562
Epoch 88/100, Loss: 2.953139975667
Epoch 89/100, Loss: 3.133902594447136
Epoch 90/100, Loss: 2.9068827480077744
Epoch 91/100, Loss: 3.0733401626348495
Epoch 92/100, Loss: 3.309524931013584
Epoch 93/100, Loss: 3.2334972620010376
Epoch 94/100, Loss: 3.003682255744934

Epoch 95/100, Loss: 3.167065054178238
Epoch 96/100, Loss: 3.0856754407286644
Epoch 97/100, Loss: 3.2245699018239975
Epoch 98/100, Loss: 2.77441792935133
Epoch 99/100, Loss: 3.011268526315689
Epoch 100/100, Loss: 3.5695887207984924
Fold 5/5 done

In [11]:
ap = average_precision_score(y_true, anomaly_scores)
print(f"Deep SVDD AP (5-fold CV) = {ap:.4f}")
sb.glue("GBG500_ap_spectral_deep_svdd", float(ap))

Deep SVDD AP (5-fold CV) = 0.5607