In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import average_precision_score
from sklearn.model_selection import StratifiedKFold
from pyod.models.deep_svdd import DeepSVDD
import sys
import scrapbook as sb

sys.path.append('..')
from utils import reshape_to_numpy, interpolate_missing_values, denoise_data, compute_spectrograms, time_avg_pooling

In [2]:
seed = 1
sampling_rate = 10
nperseg=64
noverlap=32
accel_cutoff = 0.4
accel_order = 30
gyro_cutoff = 0.6
gyro_order = 20
batch_size = 32
epochs = 100
hidden_neurons = [128, 64, 32]
n_splits = 5

In [3]:
# Parameters
seed = 19

In [4]:
rng = np.random.RandomState(seed)

In [5]:
data = pd.read_parquet("../data/GBG500.parquet")
data

,ride_id,time_index,ax,ay,az,rx,ry,rz
0,005043f1a7520cebf1e17fd166a00a3190e2433530f236...,0,-2.512796,-9.385012,-1.053078,-0.009155,0.009155,-0.201416
1,005043f1a7520cebf1e17fd166a00a3190e2433530f236...,100,-2.491268,-9.385012,-1.079390,-0.036621,0.027465,-0.155639
2,005043f1a7520cebf1e17fd166a00a3190e2433530f236...,200,-2.534324,-9.382022,-1.030952,0.036621,0.027465,-0.073242
3,005043f1a7520cebf1e17fd166a00a3190e2433530f236...,300,-2.488278,-9.383218,-1.091948,-0.045776,0.036621,-0.183105
4,005043f1a7520cebf1e17fd166a00a3190e2433530f236...,400,-2.483494,-9.382022,-1.100320,-0.045776,0.027465,-0.192260
...,...,...,...,...,...,...,...,...
1529542,ffb6f2f5dc6ba768d88dc0bc1af4cad235526aa9e24168...,241300,0.459862,-9.140430,-3.318900,1.556396,-0.091552,0.274658
1529543,ffb6f2f5dc6ba768d88dc0bc1af4cad235526aa9e24168...,241400,0.455676,-9.140430,-3.321292,1.583861,-0.119018,0.274658
1529544,ffb6f2f5dc6ba768d88dc0bc1af4cad235526aa9e24168...,241500,0.459862,-9.139832,-3.317704,1.583861,-0.109863,0.274658
1529545,ffb6f2f5dc6ba768d88dc0bc1af4cad235526aa9e24168...,241600,0.456274,-9.142224,-3.321292,1.574707,-0.137329,0.283813
1529546,ffb6f2f5dc6ba768d88dc0bc1af4cad235526aa9e24168...,241700,0.458666,-9.139832,-3.320694,1.574707,-0.137329,0.274658

In [6]:
labels = pd.read_csv("../data/GBG500_labels.csv")
labels.columns = labels.columns.str.lower()
ride_order_df = pd.DataFrame({"ride_id": data["ride_id"].unique()})
labels_sorted = ride_order_df.merge(
    labels,
    on="ride_id",
    how="left"
)
labels_sorted

                                               ride_id        label
0    005043f1a7520cebf1e17fd166a00a3190e2433530f236...         Safe
1    00d223cb7aecc9c0cc5871e32a6c45027a068eba07c572...     Reckless
2    02288a4aeca044203394e982e76b87818021dea2b34df9...         Safe
3    0236bdcf13d473ea24d97f5eaeea459f257dffac005694...  Bad weather
4    0238e5dd85143f1b6c59b200bc32f14361b8fc84c51a87...         Safe
..                                                 ...          ...
495  fe5d7f84d692bbccad8bd566a3ad5c3108fa9f90acd671...         Safe
496  fe67169632306d4668b2affedef510df2cb43e2fb41220...         Safe
497  fee44667fdc8ab4995c702fc3bd36178de0b1ca2c64687...         Safe
498  ff79b2e945b93c2a5efc3a06365267b3a160e7849ba57d...         Safe
499  ffb6f2f5dc6ba768d88dc0bc1af4cad235526aa9e24168...         Safe

[500 rows x 2 columns]

In [7]:
data_np = reshape_to_numpy(
    data,
    features = ["ax", "ay", "az", "rx", "ry", "rz"],
    max_timestamps = 4800
)

data_np_clean = interpolate_missing_values(
    data_np,
    method='linear',
    limit=None
)

data_np_clean = denoise_data(
    data=data_np_clean,
    accel_indices=[0, 1, 2],
    gyro_indices=[3, 4, 5],
    accel_cutoff=accel_cutoff,
    accel_order=accel_order,
    gyro_cutoff=gyro_cutoff,
    gyro_order=gyro_order,
)

In [8]:
# Compute spectrograms for all rides
spectrograms_array = compute_spectrograms(data_np_clean, sampling_rate, nperseg, noverlap)
spectrograms_array.shape

(500, 149, 6, 33)

In [9]:
# Aggregate spectrograms using time-averaged pooling
X_feat = time_avg_pooling(spectrograms_array)
X_feat.shape

(500, 198)

In [10]:
# 5-fold stratified CV with Deep SVDD
skf = StratifiedKFold(n_splits=n_splits, shuffle=True, random_state=rng.randint(1000))
y_true = (labels_sorted['label'] == 'Reckless').astype(int).values
anomaly_scores = np.full(len(y_true), np.nan)

for fold, (train_idx, test_idx) in enumerate(skf.split(X_feat, y_true)):
    sc = StandardScaler()
    X_train = sc.fit_transform(X_feat[train_idx])
    X_test = sc.transform(X_feat[test_idx])

    np.random.seed(rng.randint(1000))
    model = DeepSVDD(
        n_features=X_train.shape[1],
        hidden_neurons=hidden_neurons,
        epochs=epochs,
        batch_size=batch_size,
        random_state=rng.randint(1000),
    )
    model.fit(X_train)
    anomaly_scores[test_idx] = model.decision_function(X_test)
    print(f"Fold {fold+1}/{n_splits} done")

Epoch 1/100, Loss: 3.8266801685094833
Epoch 2/100, Loss: 3.9017274528741837
Epoch 3/100, Loss: 3.8683845549821854
Epoch 4/100, Loss: 3.8324596285820007
Epoch 5/100, Loss: 3.8568407744169235
Epoch 6/100, Loss: 3.5690263360738754
Epoch 7/100, Loss: 3.2194144129753113
Epoch 8/100, Loss: 3.4425197392702103
Epoch 9/100, Loss: 3.7947756499052048
Epoch 10/100, Loss: 3.910467177629471
Epoch 11/100, Loss: 3.816099099814892

Epoch 12/100, Loss: 3.520236775279045
Epoch 13/100, Loss: 3.919036567211151
Epoch 14/100, Loss: 3.5385866686701775
Epoch 15/100, Loss: 3.6147948130965233
Epoch 16/100, Loss: 3.883748948574066
Epoch 17/100, Loss: 3.5045972988009453
Epoch 18/100, Loss: 3.4265563637018204
Epoch 19/100, Loss: 3.5542204529047012
Epoch 20/100, Loss: 3.7634765058755875
Epoch 21/100, Loss: 3.7782819718122482
Epoch 22/100, Loss: 3.8340120017528534
Epoch 23/100, Loss: 3.9229934364557266

Epoch 24/100, Loss: 3.4934798032045364
Epoch 25/100, Loss: 4.003281280398369
Epoch 26/100, Loss: 3.3680643141269684
Epoch 27/100, Loss: 3.6578859388828278
Epoch 28/100, Loss: 3.677228033542633
Epoch 29/100, Loss: 3.7755416855216026
Epoch 30/100, Loss: 3.8309423476457596
Epoch 31/100, Loss: 3.9262941405177116
Epoch 32/100, Loss: 3.540925294160843
Epoch 33/100, Loss: 3.575592577457428
Epoch 34/100, Loss: 3.8866679444909096

Epoch 35/100, Loss: 3.9675141870975494
Epoch 36/100, Loss: 3.706845134496689
Epoch 37/100, Loss: 3.8477499037981033
Epoch 38/100, Loss: 3.7034248411655426
Epoch 39/100, Loss: 3.7597203478217125
Epoch 40/100, Loss: 3.6919088661670685
Epoch 41/100, Loss: 3.698540970683098
Epoch 42/100, Loss: 3.8576692789793015
Epoch 43/100, Loss: 3.908907875418663
Epoch 44/100, Loss: 3.6543520092964172
Epoch 45/100, Loss: 3.6281170025467873

Epoch 46/100, Loss: 3.729173995554447
Epoch 47/100, Loss: 3.8575748652219772
Epoch 48/100, Loss: 3.346373163163662
Epoch 49/100, Loss: 3.2141584679484367
Epoch 50/100, Loss: 3.2252571433782578
Epoch 51/100, Loss: 3.7562811374664307
Epoch 52/100, Loss: 3.715036541223526
Epoch 53/100, Loss: 3.644934356212616
Epoch 54/100, Loss: 3.808081239461899
Epoch 55/100, Loss: 3.9533345252275467
Epoch 56/100, Loss: 3.860452100634575
Epoch 57/100, Loss: 3.5244970694184303

Epoch 58/100, Loss: 3.635277174413204
Epoch 59/100, Loss: 3.3732317313551903
Epoch 60/100, Loss: 3.934339202940464
Epoch 61/100, Loss: 3.6000117510557175
Epoch 62/100, Loss: 3.3438765481114388
Epoch 63/100, Loss: 3.9523515701293945
Epoch 64/100, Loss: 3.8705475330352783
Epoch 65/100, Loss: 3.7930799946188927
Epoch 66/100, Loss: 3.55683995783329
Epoch 67/100, Loss: 3.4774364680051804
Epoch 68/100, Loss: 3.3487544283270836
Epoch 69/100, Loss: 4.394404903054237

Epoch 70/100, Loss: 3.763652853667736
Epoch 71/100, Loss: 4.000565737485886
Epoch 72/100, Loss: 3.557288318872452
Epoch 73/100, Loss: 3.7806895971298218
Epoch 74/100, Loss: 3.7441066056489944
Epoch 75/100, Loss: 3.4613774716854095
Epoch 76/100, Loss: 3.2710293978452682
Epoch 77/100, Loss: 3.959898367524147
Epoch 78/100, Loss: 3.7903395742177963
Epoch 79/100, Loss: 3.8161709010601044

Epoch 80/100, Loss: 3.3541208654642105
Epoch 81/100, Loss: 3.7445083558559418
Epoch 82/100, Loss: 3.737658143043518
Epoch 83/100, Loss: 3.399589367210865
Epoch 84/100, Loss: 3.7862163111567497
Epoch 85/100, Loss: 3.8044543266296387
Epoch 86/100, Loss: 3.885019965469837
Epoch 87/100, Loss: 3.7628128826618195
Epoch 88/100, Loss: 3.301291599869728
Epoch 89/100, Loss: 3.9325171783566475
Epoch 90/100, Loss: 3.5644946172833443

Epoch 91/100, Loss: 3.590078830718994
Epoch 92/100, Loss: 3.8386941105127335
Epoch 93/100, Loss: 3.366548426449299
Epoch 94/100, Loss: 3.485029548406601
Epoch 95/100, Loss: 3.5669249296188354
Epoch 96/100, Loss: 3.3999191150069237
Epoch 97/100, Loss: 3.7145943492650986
Epoch 98/100, Loss: 3.6515596508979797
Epoch 99/100, Loss: 3.9337605834007263
Epoch 100/100, Loss: 3.7958053201436996
Fold 1/5 done
Epoch 1/100, Loss: 2.1684487238526344

Epoch 2/100, Loss: 2.1418083384633064
Epoch 3/100, Loss: 2.090132847428322
Epoch 4/100, Loss: 2.1072609797120094
Epoch 5/100, Loss: 2.041521556675434
Epoch 6/100, Loss: 2.0036139339208603
Epoch 7/100, Loss: 2.063743643462658
Epoch 8/100, Loss: 2.038542039692402
Epoch 9/100, Loss: 2.108137458562851
Epoch 10/100, Loss: 2.2803645581007004
Epoch 11/100, Loss: 1.9726249128580093
Epoch 12/100, Loss: 2.097482956945896

Epoch 13/100, Loss: 1.9883858114480972
Epoch 14/100, Loss: 2.123459152877331
Epoch 15/100, Loss: 2.2020523473620415
Epoch 16/100, Loss: 2.077160581946373
Epoch 17/100, Loss: 2.1303509399294853
Epoch 18/100, Loss: 2.0262119472026825
Epoch 19/100, Loss: 2.000111863017082
Epoch 20/100, Loss: 2.025351010262966
Epoch 21/100, Loss: 2.110547497868538
Epoch 22/100, Loss: 2.1005407869815826
Epoch 23/100, Loss: 2.127474032342434

Epoch 24/100, Loss: 2.149150066077709
Epoch 25/100, Loss: 2.2342136800289154
Epoch 26/100, Loss: 2.1819961965084076
Epoch 27/100, Loss: 2.1804044246673584
Epoch 28/100, Loss: 2.0266884341835976
Epoch 29/100, Loss: 2.1870654299855232
Epoch 30/100, Loss: 2.025685764849186
Epoch 31/100, Loss: 2.117114081978798
Epoch 32/100, Loss: 2.126975730061531
Epoch 33/100, Loss: 2.175024077296257
Epoch 34/100, Loss: 1.9863243326544762
Epoch 35/100, Loss: 2.051159620285034
Epoch 36/100, Loss: 2.09157282859087

Epoch 37/100, Loss: 2.083258129656315
Epoch 38/100, Loss: 1.9817464500665665
Epoch 39/100, Loss: 1.886352688074112
Epoch 40/100, Loss: 2.0472326800227165
Epoch 41/100, Loss: 2.084815889596939
Epoch 42/100, Loss: 1.9990738928318024
Epoch 43/100, Loss: 2.1272840723395348
Epoch 44/100, Loss: 2.157355912029743
Epoch 45/100, Loss: 2.4437641575932503
Epoch 46/100, Loss: 2.527305118739605
Epoch 47/100, Loss: 2.140556715428829
Epoch 48/100, Loss: 2.1105291694402695

Epoch 49/100, Loss: 2.1536999344825745
Epoch 50/100, Loss: 2.1931504160165787
Epoch 51/100, Loss: 2.0576913729310036
Epoch 52/100, Loss: 2.362109750509262
Epoch 53/100, Loss: 2.078298859298229
Epoch 54/100, Loss: 2.1914482340216637
Epoch 55/100, Loss: 2.358880251646042
Epoch 56/100, Loss: 2.127175897359848
Epoch 57/100, Loss: 2.0932881236076355
Epoch 58/100, Loss: 2.1345545053482056
Epoch 59/100, Loss: 2.1714083924889565
Epoch 60/100, Loss: 2.1270532459020615
Epoch 61/100, Loss: 2.140265591442585

Epoch 62/100, Loss: 2.11445439606905
Epoch 63/100, Loss: 2.2249911054968834
Epoch 64/100, Loss: 2.182336449623108
Epoch 65/100, Loss: 2.162643700838089
Epoch 66/100, Loss: 2.208273760974407
Epoch 67/100, Loss: 1.9563433453440666
Epoch 68/100, Loss: 2.228965900838375
Epoch 69/100, Loss: 2.321769878268242
Epoch 70/100, Loss: 2.3176411613821983
Epoch 71/100, Loss: 2.1234600991010666
Epoch 72/100, Loss: 2.165576972067356
Epoch 73/100, Loss: 2.0565409138798714
Epoch 74/100, Loss: 1.9074504673480988
Epoch 75/100, Loss: 2.1437100544571877
Epoch 76/100, Loss: 2.225664809346199
Epoch 77/100, Loss: 2.0230249986052513
Epoch 78/100, Loss: 2.156400464475155
Epoch 79/100, Loss: 1.984514407813549

Epoch 80/100, Loss: 2.024486780166626
Epoch 81/100, Loss: 2.1431119963526726
Epoch 82/100, Loss: 2.2422319054603577
Epoch 83/100, Loss: 2.0713704377412796
Epoch 84/100, Loss: 2.0648791640996933
Epoch 85/100, Loss: 2.1510342359542847
Epoch 86/100, Loss: 1.9757322445511818
Epoch 87/100, Loss: 2.0964005440473557
Epoch 88/100, Loss: 2.175895541906357
Epoch 89/100, Loss: 2.1164693534374237
Epoch 90/100, Loss: 2.1640493869781494
Epoch 91/100, Loss: 2.2433717772364616
Epoch 92/100, Loss: 2.2108012959361076
Epoch 93/100, Loss: 2.185241661965847
Epoch 94/100, Loss: 2.1126229241490364
Epoch 95/100, Loss: 2.0372130647301674
Epoch 96/100, Loss: 1.9914788007736206
Epoch 97/100, Loss: 2.276320867240429

Epoch 98/100, Loss: 2.0617939084768295
Epoch 99/100, Loss: 2.2558277249336243
Epoch 100/100, Loss: 2.1934019923210144
Fold 2/5 done
Epoch 1/100, Loss: 2.3218404054641724
Epoch 2/100, Loss: 2.5649650543928146
Epoch 3/100, Loss: 2.522075928747654
Epoch 4/100, Loss: 2.380578860640526
Epoch 5/100, Loss: 2.6034077629446983
Epoch 6/100, Loss: 2.41046129912138
Epoch 7/100, Loss: 2.4588101729750633
Epoch 8/100, Loss: 2.338166058063507
Epoch 9/100, Loss: 2.53436841070652
Epoch 10/100, Loss: 2.337281808257103
Epoch 11/100, Loss: 2.5273376777768135
Epoch 12/100, Loss: 2.546480283141136
Epoch 13/100, Loss: 2.398920387029648
Epoch 14/100, Loss: 2.449034571647644

Epoch 15/100, Loss: 2.3711650520563126
Epoch 16/100, Loss: 2.2443494647741318
Epoch 17/100, Loss: 2.308062009513378
Epoch 18/100, Loss: 2.4024118706583977
Epoch 19/100, Loss: 2.3385631889104843
Epoch 20/100, Loss: 2.453188493847847
Epoch 21/100, Loss: 2.4213397949934006
Epoch 22/100, Loss: 2.4247902110219
Epoch 23/100, Loss: 2.4928003698587418
Epoch 24/100, Loss: 2.462083265185356
Epoch 25/100, Loss: 2.334710456430912
Epoch 26/100, Loss: 2.378523662686348
Epoch 27/100, Loss: 2.453938812017441
Epoch 28/100, Loss: 2.270409010350704
Epoch 29/100, Loss: 2.362175166606903
Epoch 30/100, Loss: 2.3605654016137123
Epoch 31/100, Loss: 2.472279690206051
Epoch 32/100, Loss: 2.4366874918341637

Epoch 33/100, Loss: 2.5424901247024536
Epoch 34/100, Loss: 2.4036636501550674
Epoch 35/100, Loss: 2.7151516377925873
Epoch 36/100, Loss: 2.3941280096769333
Epoch 37/100, Loss: 2.5327486246824265
Epoch 38/100, Loss: 2.5991992130875587
Epoch 39/100, Loss: 2.535508766770363
Epoch 40/100, Loss: 2.400676555931568
Epoch 41/100, Loss: 2.2672833874821663
Epoch 42/100, Loss: 2.4294251576066017
Epoch 43/100, Loss: 2.3537151888012886
Epoch 44/100, Loss: 2.4073529690504074
Epoch 45/100, Loss: 2.2492886260151863
Epoch 46/100, Loss: 2.3473959118127823
Epoch 47/100, Loss: 2.4458470717072487
Epoch 48/100, Loss: 2.4573540538549423
Epoch 49/100, Loss: 2.5793707445263863
Epoch 50/100, Loss: 2.5198065489530563

Epoch 51/100, Loss: 2.2484201341867447
Epoch 52/100, Loss: 2.335870750248432
Epoch 53/100, Loss: 2.4924366921186447
Epoch 54/100, Loss: 2.533890187740326
Epoch 55/100, Loss: 2.5589431822299957
Epoch 56/100, Loss: 2.4096078649163246
Epoch 57/100, Loss: 2.3691921085119247
Epoch 58/100, Loss: 2.332263134419918
Epoch 59/100, Loss: 2.4375799521803856
Epoch 60/100, Loss: 2.316329650580883
Epoch 61/100, Loss: 2.3214140236377716
Epoch 62/100, Loss: 2.3453415036201477
Epoch 63/100, Loss: 2.4470344930887222

Epoch 64/100, Loss: 2.464206911623478
Epoch 65/100, Loss: 2.422708570957184
Epoch 66/100, Loss: 2.483988143503666
Epoch 67/100, Loss: 2.308122903108597
Epoch 68/100, Loss: 2.2912902012467384
Epoch 69/100, Loss: 2.4153724536299706
Epoch 70/100, Loss: 2.3648785650730133
Epoch 71/100, Loss: 2.4063844308257103
Epoch 72/100, Loss: 2.446104221045971
Epoch 73/100, Loss: 2.3045637533068657
Epoch 74/100, Loss: 2.1993546560406685

Epoch 75/100, Loss: 2.455666184425354
Epoch 76/100, Loss: 2.8429400473833084
Epoch 77/100, Loss: 2.3853767588734627
Epoch 78/100, Loss: 2.4660171195864677
Epoch 79/100, Loss: 2.2560210451483727
Epoch 80/100, Loss: 2.378265969455242
Epoch 81/100, Loss: 2.498971812427044
Epoch 82/100, Loss: 2.4933871254324913
Epoch 83/100, Loss: 2.3505828380584717
Epoch 84/100, Loss: 2.567722901701927
Epoch 85/100, Loss: 2.439633399248123
Epoch 86/100, Loss: 2.391756221652031

Epoch 87/100, Loss: 2.4120963886380196
Epoch 88/100, Loss: 2.3454244658350945
Epoch 89/100, Loss: 2.4562284722924232
Epoch 90/100, Loss: 2.5316202864050865
Epoch 91/100, Loss: 2.3888985365629196
Epoch 92/100, Loss: 2.573700323700905
Epoch 93/100, Loss: 2.3732221201062202
Epoch 94/100, Loss: 2.49834331125021
Epoch 95/100, Loss: 2.283276952803135
Epoch 96/100, Loss: 2.484086334705353
Epoch 97/100, Loss: 2.423542559146881
Epoch 98/100, Loss: 2.313503623008728

Epoch 99/100, Loss: 2.427497908473015
Epoch 100/100, Loss: 2.4377419501543045
Fold 3/5 done
Epoch 1/100, Loss: 1.6743239536881447
Epoch 2/100, Loss: 1.5777948424220085
Epoch 3/100, Loss: 1.715706542134285
Epoch 4/100, Loss: 1.696796864271164
Epoch 5/100, Loss: 1.6844530627131462
Epoch 6/100, Loss: 1.7265857011079788
Epoch 7/100, Loss: 1.6351614817976952
Epoch 8/100, Loss: 1.6772148460149765
Epoch 9/100, Loss: 1.6087757423520088

Epoch 10/100, Loss: 1.6165971532464027
Epoch 11/100, Loss: 1.7638798281550407
Epoch 12/100, Loss: 1.8091595470905304
Epoch 13/100, Loss: 1.6859373152256012
Epoch 14/100, Loss: 1.628139242529869
Epoch 15/100, Loss: 1.6206633895635605
Epoch 16/100, Loss: 1.7208901420235634
Epoch 17/100, Loss: 1.672898754477501
Epoch 18/100, Loss: 1.6811322793364525
Epoch 19/100, Loss: 1.5987098067998886
Epoch 20/100, Loss: 1.7166929841041565
Epoch 21/100, Loss: 1.6444523483514786

Epoch 22/100, Loss: 1.6683978140354156
Epoch 23/100, Loss: 1.620415098965168
Epoch 24/100, Loss: 1.6011241599917412
Epoch 25/100, Loss: 1.727178007364273
Epoch 26/100, Loss: 1.541566513478756
Epoch 27/100, Loss: 1.7025980353355408
Epoch 28/100, Loss: 1.6864017583429813
Epoch 29/100, Loss: 1.5660756826400757
Epoch 30/100, Loss: 1.7025796547532082
Epoch 31/100, Loss: 1.5880586877465248
Epoch 32/100, Loss: 1.6841507852077484
Epoch 33/100, Loss: 1.6072160601615906

Epoch 34/100, Loss: 1.6041497960686684
Epoch 35/100, Loss: 1.6690764427185059
Epoch 36/100, Loss: 1.6160115152597427
Epoch 37/100, Loss: 1.6621494889259338
Epoch 38/100, Loss: 1.720775805413723
Epoch 39/100, Loss: 1.6972851380705833
Epoch 40/100, Loss: 1.5803403705358505
Epoch 41/100, Loss: 1.5937370881438255
Epoch 42/100, Loss: 1.6350718215107918
Epoch 43/100, Loss: 1.732848048210144
Epoch 44/100, Loss: 1.544467568397522
Epoch 45/100, Loss: 1.721339464187622

Epoch 46/100, Loss: 1.690872311592102
Epoch 47/100, Loss: 1.6569289490580559
Epoch 48/100, Loss: 1.6752180829644203
Epoch 49/100, Loss: 1.635761320590973
Epoch 50/100, Loss: 1.6509836465120316
Epoch 51/100, Loss: 1.7064401879906654
Epoch 52/100, Loss: 1.627277433872223
Epoch 53/100, Loss: 1.7043259516358376
Epoch 54/100, Loss: 1.5528756156563759
Epoch 55/100, Loss: 1.5685579925775528
Epoch 56/100, Loss: 1.6699974536895752

Epoch 57/100, Loss: 1.675000548362732
Epoch 58/100, Loss: 1.6001430377364159
Epoch 59/100, Loss: 1.7653314992785454
Epoch 60/100, Loss: 1.630010835826397
Epoch 61/100, Loss: 1.4990143030881882
Epoch 62/100, Loss: 1.587320514023304
Epoch 63/100, Loss: 1.6007929667830467
Epoch 64/100, Loss: 1.601598858833313
Epoch 65/100, Loss: 1.6424724087119102
Epoch 66/100, Loss: 1.7631413862109184
Epoch 67/100, Loss: 1.5941592678427696
Epoch 68/100, Loss: 1.6959219425916672

Epoch 69/100, Loss: 1.6589280515909195
Epoch 70/100, Loss: 1.6232634037733078
Epoch 71/100, Loss: 1.6569123342633247
Epoch 72/100, Loss: 1.689625047147274
Epoch 73/100, Loss: 1.6003643497824669
Epoch 74/100, Loss: 1.6794112548232079
Epoch 75/100, Loss: 1.645832322537899
Epoch 76/100, Loss: 1.7027366980910301
Epoch 77/100, Loss: 1.5901115834712982
Epoch 78/100, Loss: 1.7521530613303185
Epoch 79/100, Loss: 1.7305519208312035

Epoch 80/100, Loss: 1.7586968168616295
Epoch 81/100, Loss: 1.5834198594093323
Epoch 82/100, Loss: 1.5883498638868332
Epoch 83/100, Loss: 1.6562714502215385
Epoch 84/100, Loss: 1.6718742921948433
Epoch 85/100, Loss: 1.5749611556529999
Epoch 86/100, Loss: 1.6443204060196877
Epoch 87/100, Loss: 1.7443358153104782
Epoch 88/100, Loss: 1.5623179525136948
Epoch 89/100, Loss: 1.6184635907411575
Epoch 90/100, Loss: 1.5906522125005722

Epoch 91/100, Loss: 1.7333016693592072
Epoch 92/100, Loss: 1.672265112400055
Epoch 93/100, Loss: 1.633148968219757
Epoch 94/100, Loss: 1.5999217703938484
Epoch 95/100, Loss: 1.6725352481007576
Epoch 96/100, Loss: 1.5870991051197052
Epoch 97/100, Loss: 1.71018398553133
Epoch 98/100, Loss: 1.6890371665358543
Epoch 99/100, Loss: 1.805979199707508
Epoch 100/100, Loss: 1.6862629130482674
Fold 4/5 done
Epoch 1/100, Loss: 1.9585690349340439
Epoch 2/100, Loss: 1.9458563029766083

Epoch 3/100, Loss: 2.0277569219470024
Epoch 4/100, Loss: 1.8724435791373253
Epoch 5/100, Loss: 1.944113329052925
Epoch 6/100, Loss: 1.9578614234924316
Epoch 7/100, Loss: 1.932476133108139
Epoch 8/100, Loss: 1.8997798338532448
Epoch 9/100, Loss: 1.9820574298501015
Epoch 10/100, Loss: 1.8109977692365646
Epoch 11/100, Loss: 1.8817991241812706
Epoch 12/100, Loss: 1.8752026781439781
Epoch 13/100, Loss: 1.9694276303052902

Epoch 14/100, Loss: 1.9286031126976013
Epoch 15/100, Loss: 1.8632145002484322
Epoch 16/100, Loss: 2.0502281188964844
Epoch 17/100, Loss: 2.0173435509204865
Epoch 18/100, Loss: 1.8662390932440758
Epoch 19/100, Loss: 1.8058424890041351
Epoch 20/100, Loss: 1.886006847023964
Epoch 21/100, Loss: 1.935032181441784
Epoch 22/100, Loss: 1.8542582616209984
Epoch 23/100, Loss: 1.9171616584062576
Epoch 24/100, Loss: 1.8888984322547913
Epoch 25/100, Loss: 1.9321490935981274
Epoch 26/100, Loss: 1.9877939671278
Epoch 27/100, Loss: 1.9059941992163658
Epoch 28/100, Loss: 1.8796060308814049

Epoch 29/100, Loss: 1.8802501857280731
Epoch 30/100, Loss: 1.881369449198246
Epoch 31/100, Loss: 1.8581175804138184
Epoch 32/100, Loss: 1.9503894224762917
Epoch 33/100, Loss: 1.9225239604711533
Epoch 34/100, Loss: 1.9219208285212517
Epoch 35/100, Loss: 1.8441737666726112
Epoch 36/100, Loss: 1.952710174024105
Epoch 37/100, Loss: 1.9097493514418602
Epoch 38/100, Loss: 1.8718701675534248
Epoch 39/100, Loss: 1.9585497677326202
Epoch 40/100, Loss: 1.8802310600876808
Epoch 41/100, Loss: 1.958050288259983
Epoch 42/100, Loss: 1.9871834516525269
Epoch 43/100, Loss: 1.9772472232580185

Epoch 44/100, Loss: 1.984911248087883
Epoch 45/100, Loss: 1.9062564186751842
Epoch 46/100, Loss: 1.90795286744833
Epoch 47/100, Loss: 1.933620236814022
Epoch 48/100, Loss: 1.9275238364934921
Epoch 49/100, Loss: 2.013308972120285
Epoch 50/100, Loss: 1.8463918566703796
Epoch 51/100, Loss: 1.9348467886447906
Epoch 52/100, Loss: 1.879821516573429
Epoch 53/100, Loss: 1.8881775215268135
Epoch 54/100, Loss: 1.9815171658992767
Epoch 55/100, Loss: 1.8511261269450188
Epoch 56/100, Loss: 1.9740051180124283
Epoch 57/100, Loss: 1.9983704164624214
Epoch 58/100, Loss: 1.9867114797234535

Epoch 59/100, Loss: 1.9274633005261421
Epoch 60/100, Loss: 1.894498959183693
Epoch 61/100, Loss: 2.0903030410408974
Epoch 62/100, Loss: 1.9648971036076546
Epoch 63/100, Loss: 1.898339994251728
Epoch 64/100, Loss: 1.9652885347604752
Epoch 65/100, Loss: 1.9362775012850761
Epoch 66/100, Loss: 1.9415520653128624
Epoch 67/100, Loss: 1.8297626078128815
Epoch 68/100, Loss: 1.938528448343277
Epoch 69/100, Loss: 1.8626821637153625
Epoch 70/100, Loss: 1.898349568247795
Epoch 71/100, Loss: 1.878764845430851
Epoch 72/100, Loss: 1.9514448046684265
Epoch 73/100, Loss: 1.823836199939251

Epoch 74/100, Loss: 1.9564805254340172
Epoch 75/100, Loss: 1.9030485525727272
Epoch 76/100, Loss: 1.9339545369148254
Epoch 77/100, Loss: 1.8643614053726196
Epoch 78/100, Loss: 1.892007738351822
Epoch 79/100, Loss: 1.847023919224739
Epoch 80/100, Loss: 1.9675718694925308
Epoch 81/100, Loss: 1.9580830559134483
Epoch 82/100, Loss: 1.9136268347501755
Epoch 83/100, Loss: 1.9129740744829178
Epoch 84/100, Loss: 1.8149800077080727
Epoch 85/100, Loss: 1.9942160546779633
Epoch 86/100, Loss: 1.8644409403204918
Epoch 87/100, Loss: 2.0238108187913895
Epoch 88/100, Loss: 1.929457500576973

Epoch 89/100, Loss: 1.8887943550944328
Epoch 90/100, Loss: 1.9181177616119385
Epoch 91/100, Loss: 1.9310107752680779
Epoch 92/100, Loss: 1.853210136294365
Epoch 93/100, Loss: 1.8714705258607864
Epoch 94/100, Loss: 1.899749018251896
Epoch 95/100, Loss: 1.917404644191265
Epoch 96/100, Loss: 1.877234973013401
Epoch 97/100, Loss: 2.0030161887407303
Epoch 98/100, Loss: 2.0415618121623993
Epoch 99/100, Loss: 1.901619203388691
Epoch 100/100, Loss: 1.9327102228999138
Fold 5/5 done

In [11]:
ap = average_precision_score(y_true, anomaly_scores)
print(f"Deep SVDD AP (5-fold CV) = {ap:.4f}")
sb.glue("GBG500_ap_spectral_deep_svdd", float(ap))

Deep SVDD AP (5-fold CV) = 0.4735