In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import average_precision_score
from sklearn.model_selection import StratifiedKFold
from pyod.models.deep_svdd import DeepSVDD
import sys
import scrapbook as sb

sys.path.append('..')
from utils import reshape_to_numpy, interpolate_missing_values, denoise_data, compute_spectrograms, time_avg_pooling

In [2]:
seed = 1
sampling_rate = 10
nperseg=64
noverlap=32
accel_cutoff = 0.4
accel_order = 30
gyro_cutoff = 0.6
gyro_order = 20
batch_size = 32
epochs = 100
hidden_neurons = [128, 64, 32]
n_splits = 5

In [3]:
# Parameters
seed = 9

In [4]:
rng = np.random.RandomState(seed)

In [5]:
data = pd.read_parquet("../data/GBG500.parquet")
data

,ride_id,time_index,ax,ay,az,rx,ry,rz
0,005043f1a7520cebf1e17fd166a00a3190e2433530f236...,0,-2.512796,-9.385012,-1.053078,-0.009155,0.009155,-0.201416
1,005043f1a7520cebf1e17fd166a00a3190e2433530f236...,100,-2.491268,-9.385012,-1.079390,-0.036621,0.027465,-0.155639
2,005043f1a7520cebf1e17fd166a00a3190e2433530f236...,200,-2.534324,-9.382022,-1.030952,0.036621,0.027465,-0.073242
3,005043f1a7520cebf1e17fd166a00a3190e2433530f236...,300,-2.488278,-9.383218,-1.091948,-0.045776,0.036621,-0.183105
4,005043f1a7520cebf1e17fd166a00a3190e2433530f236...,400,-2.483494,-9.382022,-1.100320,-0.045776,0.027465,-0.192260
...,...,...,...,...,...,...,...,...
1529542,ffb6f2f5dc6ba768d88dc0bc1af4cad235526aa9e24168...,241300,0.459862,-9.140430,-3.318900,1.556396,-0.091552,0.274658
1529543,ffb6f2f5dc6ba768d88dc0bc1af4cad235526aa9e24168...,241400,0.455676,-9.140430,-3.321292,1.583861,-0.119018,0.274658
1529544,ffb6f2f5dc6ba768d88dc0bc1af4cad235526aa9e24168...,241500,0.459862,-9.139832,-3.317704,1.583861,-0.109863,0.274658
1529545,ffb6f2f5dc6ba768d88dc0bc1af4cad235526aa9e24168...,241600,0.456274,-9.142224,-3.321292,1.574707,-0.137329,0.283813
1529546,ffb6f2f5dc6ba768d88dc0bc1af4cad235526aa9e24168...,241700,0.458666,-9.139832,-3.320694,1.574707,-0.137329,0.274658

In [6]:
labels = pd.read_csv("../data/GBG500_labels.csv")
labels.columns = labels.columns.str.lower()
ride_order_df = pd.DataFrame({"ride_id": data["ride_id"].unique()})
labels_sorted = ride_order_df.merge(
    labels,
    on="ride_id",
    how="left"
)
labels_sorted

                                               ride_id        label
0    005043f1a7520cebf1e17fd166a00a3190e2433530f236...         Safe
1    00d223cb7aecc9c0cc5871e32a6c45027a068eba07c572...     Reckless
2    02288a4aeca044203394e982e76b87818021dea2b34df9...         Safe
3    0236bdcf13d473ea24d97f5eaeea459f257dffac005694...  Bad weather
4    0238e5dd85143f1b6c59b200bc32f14361b8fc84c51a87...         Safe
..                                                 ...          ...
495  fe5d7f84d692bbccad8bd566a3ad5c3108fa9f90acd671...         Safe
496  fe67169632306d4668b2affedef510df2cb43e2fb41220...         Safe
497  fee44667fdc8ab4995c702fc3bd36178de0b1ca2c64687...         Safe
498  ff79b2e945b93c2a5efc3a06365267b3a160e7849ba57d...         Safe
499  ffb6f2f5dc6ba768d88dc0bc1af4cad235526aa9e24168...         Safe

[500 rows x 2 columns]

In [7]:
data_np = reshape_to_numpy(
    data,
    features = ["ax", "ay", "az", "rx", "ry", "rz"],
    max_timestamps = 4800
)

data_np_clean = interpolate_missing_values(
    data_np,
    method='linear',
    limit=None
)

data_np_clean = denoise_data(
    data=data_np_clean,
    accel_indices=[0, 1, 2],
    gyro_indices=[3, 4, 5],
    accel_cutoff=accel_cutoff,
    accel_order=accel_order,
    gyro_cutoff=gyro_cutoff,
    gyro_order=gyro_order,
)

In [8]:
# Compute spectrograms for all rides
spectrograms_array = compute_spectrograms(data_np_clean, sampling_rate, nperseg, noverlap)
spectrograms_array.shape

(500, 149, 6, 33)

In [9]:
# Aggregate spectrograms using time-averaged pooling
X_feat = time_avg_pooling(spectrograms_array)
X_feat.shape

(500, 198)

In [10]:
# 5-fold stratified CV with Deep SVDD
skf = StratifiedKFold(n_splits=n_splits, shuffle=True, random_state=rng.randint(1000))
y_true = (labels_sorted['label'] == 'Reckless').astype(int).values
anomaly_scores = np.full(len(y_true), np.nan)

for fold, (train_idx, test_idx) in enumerate(skf.split(X_feat, y_true)):
    sc = StandardScaler()
    X_train = sc.fit_transform(X_feat[train_idx])
    X_test = sc.transform(X_feat[test_idx])

    np.random.seed(rng.randint(1000))
    model = DeepSVDD(
        n_features=X_train.shape[1],
        hidden_neurons=hidden_neurons,
        epochs=epochs,
        batch_size=batch_size,
        random_state=rng.randint(1000),
    )
    model.fit(X_train)
    anomaly_scores[test_idx] = model.decision_function(X_test)
    print(f"Fold {fold+1}/{n_splits} done")

Epoch 1/100, Loss: 3.7199578136205673
Epoch 2/100, Loss: 3.7182872965931892
Epoch 3/100, Loss: 3.5706899017095566
Epoch 4/100, Loss: 3.5669682696461678
Epoch 5/100, Loss: 3.2780843377113342
Epoch 6/100, Loss: 3.720730096101761
Epoch 7/100, Loss: 3.371754363179207
Epoch 8/100, Loss: 3.4919983819127083
Epoch 9/100, Loss: 3.367808520793915
Epoch 10/100, Loss: 3.4190922379493713
Epoch 11/100, Loss: 3.3853906095027924
Epoch 12/100, Loss: 3.137272484600544
Epoch 13/100, Loss: 3.2745786905288696
Epoch 14/100, Loss: 3.3826003298163414
Epoch 15/100, Loss: 3.444114252924919
Epoch 16/100, Loss: 3.6381419971585274

Epoch 17/100, Loss: 3.563033200800419
Epoch 18/100, Loss: 3.06746743619442
Epoch 19/100, Loss: 3.117598555982113
Epoch 20/100, Loss: 3.103740446269512
Epoch 21/100, Loss: 3.281360685825348
Epoch 22/100, Loss: 3.0922300294041634
Epoch 23/100, Loss: 3.1734316051006317
Epoch 24/100, Loss: 3.470989443361759
Epoch 25/100, Loss: 3.5510887801647186
Epoch 26/100, Loss: 4.033645816147327
Epoch 27/100, Loss: 3.1393388509750366
Epoch 28/100, Loss: 3.3487640097737312
Epoch 29/100, Loss: 3.375172294676304
Epoch 30/100, Loss: 2.895311616361141
Epoch 31/100, Loss: 2.8340402469038963
Epoch 32/100, Loss: 3.466525934636593
Epoch 33/100, Loss: 3.5088183358311653

Epoch 34/100, Loss: 3.467977650463581
Epoch 35/100, Loss: 3.3356440514326096
Epoch 36/100, Loss: 3.596568800508976
Epoch 37/100, Loss: 3.461627669632435
Epoch 38/100, Loss: 3.387589767575264
Epoch 39/100, Loss: 3.5587241873145103
Epoch 40/100, Loss: 3.287279672920704
Epoch 41/100, Loss: 3.245750941336155
Epoch 42/100, Loss: 3.221146784722805
Epoch 43/100, Loss: 3.4930632784962654
Epoch 44/100, Loss: 3.602897897362709
Epoch 45/100, Loss: 3.1814039796590805
Epoch 46/100, Loss: 2.8235175162553787

Epoch 47/100, Loss: 3.7491756677627563
Epoch 48/100, Loss: 3.3079160526394844
Epoch 49/100, Loss: 3.3020636811852455
Epoch 50/100, Loss: 3.2478305399417877
Epoch 51/100, Loss: 3.2379269152879715
Epoch 52/100, Loss: 4.428581342101097
Epoch 53/100, Loss: 3.289524368941784
Epoch 54/100, Loss: 3.2270707190036774
Epoch 55/100, Loss: 3.4859494492411613
Epoch 56/100, Loss: 3.530057266354561
Epoch 57/100, Loss: 3.5336447283625603
Epoch 58/100, Loss: 3.240125611424446
Epoch 59/100, Loss: 3.307643212378025
Epoch 60/100, Loss: 3.246477499604225
Epoch 61/100, Loss: 3.600582130253315
Epoch 62/100, Loss: 3.1843531727790833
Epoch 63/100, Loss: 3.1842210218310356

Epoch 64/100, Loss: 3.3326354697346687
Epoch 65/100, Loss: 3.577835887670517
Epoch 66/100, Loss: 3.2944493517279625
Epoch 67/100, Loss: 3.449589304625988
Epoch 68/100, Loss: 4.497655890882015
Epoch 69/100, Loss: 4.255186915397644
Epoch 70/100, Loss: 3.5978747829794884
Epoch 71/100, Loss: 3.3073591962456703
Epoch 72/100, Loss: 3.2414151579141617
Epoch 73/100, Loss: 3.570717342197895
Epoch 74/100, Loss: 3.2335276678204536
Epoch 75/100, Loss: 3.5532966554164886
Epoch 76/100, Loss: 3.247092120349407
Epoch 77/100, Loss: 3.6305154860019684
Epoch 78/100, Loss: 4.600147031247616
Epoch 79/100, Loss: 3.2902094200253487
Epoch 80/100, Loss: 3.400944374501705
Epoch 81/100, Loss: 3.1098847091197968

Epoch 82/100, Loss: 3.358035810291767
Epoch 83/100, Loss: 3.2366359308362007
Epoch 84/100, Loss: 3.6298835650086403
Epoch 85/100, Loss: 3.3113216012716293
Epoch 86/100, Loss: 3.1591056808829308
Epoch 87/100, Loss: 3.1436583027243614
Epoch 88/100, Loss: 3.346442900598049
Epoch 89/100, Loss: 3.5154151394963264
Epoch 90/100, Loss: 3.3772939294576645
Epoch 91/100, Loss: 3.457957699894905
Epoch 92/100, Loss: 3.367296263575554
Epoch 93/100, Loss: 3.491656355559826
Epoch 94/100, Loss: 3.2627400755882263
Epoch 95/100, Loss: 3.251667819917202
Epoch 96/100, Loss: 3.587251700460911
Epoch 97/100, Loss: 3.4453569650650024
Epoch 98/100, Loss: 3.6498994678258896
Epoch 99/100, Loss: 3.7610975429415703
Epoch 100/100, Loss: 3.528936117887497

Fold 1/5 done
Epoch 1/100, Loss: 2.777408927679062
Epoch 2/100, Loss: 2.8683948069810867
Epoch 3/100, Loss: 2.55772165954113
Epoch 4/100, Loss: 2.478548027575016
Epoch 5/100, Loss: 2.974979467689991
Epoch 6/100, Loss: 2.711111344397068
Epoch 7/100, Loss: 2.6843404173851013
Epoch 8/100, Loss: 2.5692774280905724
Epoch 9/100, Loss: 2.6703940331935883
Epoch 10/100, Loss: 2.704792395234108
Epoch 11/100, Loss: 2.5609143674373627
Epoch 12/100, Loss: 2.6313337981700897
Epoch 13/100, Loss: 2.595275357365608
Epoch 14/100, Loss: 2.630679987370968
Epoch 15/100, Loss: 2.6684612184762955
Epoch 16/100, Loss: 2.4387595131993294
Epoch 17/100, Loss: 3.0894874781370163

Epoch 18/100, Loss: 2.6276952624320984
Epoch 19/100, Loss: 2.604065887629986
Epoch 20/100, Loss: 2.59291709959507
Epoch 21/100, Loss: 2.385131597518921
Epoch 22/100, Loss: 2.551027297973633
Epoch 23/100, Loss: 2.807381108403206
Epoch 24/100, Loss: 2.638466753065586
Epoch 25/100, Loss: 2.513532981276512
Epoch 26/100, Loss: 2.5692310705780983
Epoch 27/100, Loss: 2.7268211618065834
Epoch 28/100, Loss: 2.6966629549860954
Epoch 29/100, Loss: 2.7370246574282646
Epoch 30/100, Loss: 2.4832132682204247
Epoch 31/100, Loss: 2.756808578968048
Epoch 32/100, Loss: 2.7604204416275024
Epoch 33/100, Loss: 2.642153114080429
Epoch 34/100, Loss: 2.752408340573311
Epoch 35/100, Loss: 2.682513140141964

Epoch 36/100, Loss: 2.533319592475891
Epoch 37/100, Loss: 2.740532271564007
Epoch 38/100, Loss: 2.4805650636553764
Epoch 39/100, Loss: 2.6224933937191963
Epoch 40/100, Loss: 2.8172414898872375
Epoch 41/100, Loss: 2.6118148863315582
Epoch 42/100, Loss: 2.6503741443157196
Epoch 43/100, Loss: 2.6616943702101707
Epoch 44/100, Loss: 2.4918169155716896
Epoch 45/100, Loss: 2.4355188384652138
Epoch 46/100, Loss: 2.6990614756941795
Epoch 47/100, Loss: 2.7123492658138275
Epoch 48/100, Loss: 2.6349798664450645
Epoch 49/100, Loss: 2.562208741903305
Epoch 50/100, Loss: 2.9716611206531525
Epoch 51/100, Loss: 2.5225853696465492
Epoch 52/100, Loss: 2.5767871290445328
Epoch 53/100, Loss: 2.6138269379734993
Epoch 54/100, Loss: 2.7944036945700645

Epoch 55/100, Loss: 2.732908971607685
Epoch 56/100, Loss: 2.462864302098751
Epoch 57/100, Loss: 2.462259143590927
Epoch 58/100, Loss: 2.527226097881794
Epoch 59/100, Loss: 2.437759220600128
Epoch 60/100, Loss: 2.5469963997602463
Epoch 61/100, Loss: 2.6609293445944786
Epoch 62/100, Loss: 2.5265824645757675
Epoch 63/100, Loss: 2.4176016226410866
Epoch 64/100, Loss: 2.503593936562538
Epoch 65/100, Loss: 2.5833842009305954
Epoch 66/100, Loss: 2.4330090135335922

Epoch 67/100, Loss: 2.8908033668994904
Epoch 68/100, Loss: 2.7869158759713173
Epoch 69/100, Loss: 2.5763920471072197
Epoch 70/100, Loss: 2.534482143819332
Epoch 71/100, Loss: 2.6038509011268616
Epoch 72/100, Loss: 2.8717948272824287
Epoch 73/100, Loss: 2.5941007360816
Epoch 74/100, Loss: 2.856120251119137
Epoch 75/100, Loss: 2.837803602218628
Epoch 76/100, Loss: 2.540297269821167
Epoch 77/100, Loss: 2.7827778309583664
Epoch 78/100, Loss: 2.6965262070298195
Epoch 79/100, Loss: 2.6060776486992836
Epoch 80/100, Loss: 2.6630821600556374

Epoch 81/100, Loss: 2.779443770647049
Epoch 82/100, Loss: 2.645440086722374
Epoch 83/100, Loss: 2.629423148930073
Epoch 84/100, Loss: 2.7965284436941147
Epoch 85/100, Loss: 2.6238057911396027
Epoch 86/100, Loss: 2.475898690521717
Epoch 87/100, Loss: 2.630535162985325
Epoch 88/100, Loss: 2.7104623839259148
Epoch 89/100, Loss: 2.6861506700515747
Epoch 90/100, Loss: 2.4613096490502357
Epoch 91/100, Loss: 2.6508793011307716
Epoch 92/100, Loss: 2.543686680495739
Epoch 93/100, Loss: 2.805099755525589
Epoch 94/100, Loss: 2.638536751270294
Epoch 95/100, Loss: 2.5527371913194656
Epoch 96/100, Loss: 2.6920219734311104
Epoch 97/100, Loss: 2.6154857501387596

Epoch 98/100, Loss: 2.654639333486557
Epoch 99/100, Loss: 2.599617876112461
Epoch 100/100, Loss: 2.630662754178047
Fold 2/5 done
Epoch 1/100, Loss: 1.8051793090999126
Epoch 2/100, Loss: 1.6179811507463455
Epoch 3/100, Loss: 1.4411844685673714
Epoch 4/100, Loss: 1.5520933642983437
Epoch 5/100, Loss: 1.5077029317617416
Epoch 6/100, Loss: 1.5220184177160263
Epoch 7/100, Loss: 1.8122209124267101
Epoch 8/100, Loss: 1.701205164194107
Epoch 9/100, Loss: 1.4947164431214333
Epoch 10/100, Loss: 1.5167811140418053
Epoch 11/100, Loss: 1.493047021329403
Epoch 12/100, Loss: 1.5587450340390205
Epoch 13/100, Loss: 1.6297688148915768
Epoch 14/100, Loss: 1.5121688321232796

Epoch 15/100, Loss: 1.4356760084629059
Epoch 16/100, Loss: 1.5198683999478817
Epoch 17/100, Loss: 1.382764995098114
Epoch 18/100, Loss: 1.6982513442635536
Epoch 19/100, Loss: 1.4744254127144814
Epoch 20/100, Loss: 1.6971144899725914
Epoch 21/100, Loss: 1.6450415812432766
Epoch 22/100, Loss: 1.671663947403431
Epoch 23/100, Loss: 1.6243505105376244
Epoch 24/100, Loss: 1.663777232170105
Epoch 25/100, Loss: 1.5805649124085903
Epoch 26/100, Loss: 1.5794878341257572
Epoch 27/100, Loss: 1.5173539370298386
Epoch 28/100, Loss: 1.5678512565791607
Epoch 29/100, Loss: 1.7043223790824413
Epoch 30/100, Loss: 1.533195972442627
Epoch 31/100, Loss: 1.765286322683096
Epoch 32/100, Loss: 1.6943671144545078

Epoch 33/100, Loss: 1.5534060038626194
Epoch 34/100, Loss: 1.7179765962064266
Epoch 35/100, Loss: 1.7707926370203495
Epoch 36/100, Loss: 1.6851054206490517
Epoch 37/100, Loss: 1.613418161869049
Epoch 38/100, Loss: 1.4600507095456123
Epoch 39/100, Loss: 1.656948309391737
Epoch 40/100, Loss: 1.645609438419342
Epoch 41/100, Loss: 1.6182522848248482
Epoch 42/100, Loss: 1.6974088326096535
Epoch 43/100, Loss: 1.4881240352988243
Epoch 44/100, Loss: 1.5961993224918842
Epoch 45/100, Loss: 1.507126659154892
Epoch 46/100, Loss: 1.4247267320752144
Epoch 47/100, Loss: 1.5501957908272743
Epoch 48/100, Loss: 1.4205897226929665
Epoch 49/100, Loss: 1.5822701342403889
Epoch 50/100, Loss: 1.6228555515408516

Epoch 51/100, Loss: 1.570657156407833
Epoch 52/100, Loss: 1.5218483284115791
Epoch 53/100, Loss: 1.3862855732440948
Epoch 54/100, Loss: 1.640791792422533
Epoch 55/100, Loss: 1.7918541766703129
Epoch 56/100, Loss: 1.4727953560650349
Epoch 57/100, Loss: 1.440352402627468
Epoch 58/100, Loss: 1.5847241804003716
Epoch 59/100, Loss: 1.4311233311891556
Epoch 60/100, Loss: 1.5739539340138435
Epoch 61/100, Loss: 1.5560102574527264
Epoch 62/100, Loss: 1.5654863752424717
Epoch 63/100, Loss: 2.033653449267149
Epoch 64/100, Loss: 1.9440953060984612
Epoch 65/100, Loss: 1.6455582156777382
Epoch 66/100, Loss: 1.7499749213457108
Epoch 67/100, Loss: 1.8355082385241985
Epoch 68/100, Loss: 1.6023072190582752

Epoch 69/100, Loss: 1.6675621718168259
Epoch 70/100, Loss: 1.5813365764915943
Epoch 71/100, Loss: 1.6105069369077682
Epoch 72/100, Loss: 1.5198869742453098
Epoch 73/100, Loss: 1.525127962231636
Epoch 74/100, Loss: 1.6438620686531067
Epoch 75/100, Loss: 1.4651727601885796
Epoch 76/100, Loss: 1.6798630990087986
Epoch 77/100, Loss: 1.797098558396101
Epoch 78/100, Loss: 1.5773225910961628
Epoch 79/100, Loss: 1.5643573850393295
Epoch 80/100, Loss: 1.5906921476125717
Epoch 81/100, Loss: 1.777654580771923
Epoch 82/100, Loss: 1.5413253903388977
Epoch 83/100, Loss: 1.730993665754795
Epoch 84/100, Loss: 1.6892422996461391
Epoch 85/100, Loss: 1.7570195980370045
Epoch 86/100, Loss: 1.7045129127800465

Epoch 87/100, Loss: 1.4749997779726982
Epoch 88/100, Loss: 1.6043946593999863
Epoch 89/100, Loss: 1.5697065442800522
Epoch 90/100, Loss: 1.5591902546584606
Epoch 91/100, Loss: 1.7534232959151268
Epoch 92/100, Loss: 1.5750098638236523
Epoch 93/100, Loss: 1.6961767487227917
Epoch 94/100, Loss: 1.598466221243143
Epoch 95/100, Loss: 1.5341962911188602
Epoch 96/100, Loss: 1.6008439622819424
Epoch 97/100, Loss: 1.8841364458203316
Epoch 98/100, Loss: 1.6776475086808205
Epoch 99/100, Loss: 1.8999710865318775
Epoch 100/100, Loss: 1.5515929274260998
Fold 3/5 done
Epoch 1/100, Loss: 3.541580706834793
Epoch 2/100, Loss: 3.2825527489185333
Epoch 3/100, Loss: 3.2064384669065475

Epoch 4/100, Loss: 3.352886453270912
Epoch 5/100, Loss: 3.556110307574272
Epoch 6/100, Loss: 3.294513449072838
Epoch 7/100, Loss: 3.2956668734550476
Epoch 8/100, Loss: 3.3519424498081207
Epoch 9/100, Loss: 3.539846733212471
Epoch 10/100, Loss: 3.4501486271619797
Epoch 11/100, Loss: 3.260207623243332
Epoch 12/100, Loss: 3.5001160353422165
Epoch 13/100, Loss: 3.220455825328827
Epoch 14/100, Loss: 3.5573152154684067
Epoch 15/100, Loss: 3.3939303159713745
Epoch 16/100, Loss: 3.4056890308856964
Epoch 17/100, Loss: 4.243048682808876
Epoch 18/100, Loss: 3.594837263226509
Epoch 19/100, Loss: 3.465938299894333
Epoch 20/100, Loss: 3.313767910003662

Epoch 21/100, Loss: 3.1509928852319717
Epoch 22/100, Loss: 3.261340320110321
Epoch 23/100, Loss: 3.4036309123039246
Epoch 24/100, Loss: 3.248286172747612
Epoch 25/100, Loss: 3.380278304219246
Epoch 26/100, Loss: 3.5240460485219955
Epoch 27/100, Loss: 3.3865961879491806
Epoch 28/100, Loss: 3.5087163001298904
Epoch 29/100, Loss: 3.43193157017231
Epoch 30/100, Loss: 3.52386774122715
Epoch 31/100, Loss: 3.3229504004120827
Epoch 32/100, Loss: 3.268872708082199
Epoch 33/100, Loss: 3.2321900874376297
Epoch 34/100, Loss: 3.1676464825868607
Epoch 35/100, Loss: 3.442768856883049
Epoch 36/100, Loss: 3.322834834456444
Epoch 37/100, Loss: 3.496830031275749
Epoch 38/100, Loss: 3.4289181977510452

Epoch 39/100, Loss: 2.983130469918251
Epoch 40/100, Loss: 3.4594685062766075
Epoch 41/100, Loss: 3.491348221898079
Epoch 42/100, Loss: 3.324465036392212
Epoch 43/100, Loss: 3.5481464713811874
Epoch 44/100, Loss: 3.4135904014110565
Epoch 45/100, Loss: 3.0499171391129494
Epoch 46/100, Loss: 3.514233946800232
Epoch 47/100, Loss: 3.2298105657100677
Epoch 48/100, Loss: 3.504380129277706
Epoch 49/100, Loss: 3.3083658069372177
Epoch 50/100, Loss: 3.1754442900419235
Epoch 51/100, Loss: 3.522523656487465
Epoch 52/100, Loss: 3.323433756828308
Epoch 53/100, Loss: 3.2697953209280968
Epoch 54/100, Loss: 3.5312924534082413
Epoch 55/100, Loss: 3.349023401737213
Epoch 56/100, Loss: 3.4884146600961685

Epoch 57/100, Loss: 3.26996049284935
Epoch 58/100, Loss: 3.0866888612508774
Epoch 59/100, Loss: 3.2544782161712646
Epoch 60/100, Loss: 3.4632704704999924
Epoch 61/100, Loss: 3.3118550330400467
Epoch 62/100, Loss: 3.4877731949090958
Epoch 63/100, Loss: 3.6859823763370514
Epoch 64/100, Loss: 3.4477109611034393
Epoch 65/100, Loss: 3.4159065932035446
Epoch 66/100, Loss: 3.5055964589118958
Epoch 67/100, Loss: 3.684337481856346
Epoch 68/100, Loss: 3.655217617750168
Epoch 69/100, Loss: 3.525256857275963
Epoch 70/100, Loss: 3.4305236637592316
Epoch 71/100, Loss: 3.551133170723915
Epoch 72/100, Loss: 3.129076585173607
Epoch 73/100, Loss: 3.421671435236931
Epoch 74/100, Loss: 3.414780855178833

Epoch 75/100, Loss: 3.559850201010704
Epoch 76/100, Loss: 3.36318302154541
Epoch 77/100, Loss: 3.4722271114587784
Epoch 78/100, Loss: 3.187671035528183
Epoch 79/100, Loss: 3.4093076437711716
Epoch 80/100, Loss: 3.165544882416725
Epoch 81/100, Loss: 3.166755571961403
Epoch 82/100, Loss: 3.3686982691287994
Epoch 83/100, Loss: 3.4325708895921707
Epoch 84/100, Loss: 3.189663305878639
Epoch 85/100, Loss: 3.2183179408311844
Epoch 86/100, Loss: 3.225194498896599
Epoch 87/100, Loss: 3.5220789313316345
Epoch 88/100, Loss: 3.4600063860416412
Epoch 89/100, Loss: 3.4972749203443527
Epoch 90/100, Loss: 3.2548564970493317
Epoch 91/100, Loss: 3.41321924328804
Epoch 92/100, Loss: 3.1854146271944046

Epoch 93/100, Loss: 3.2357852458953857
Epoch 94/100, Loss: 3.277322545647621
Epoch 95/100, Loss: 3.3754154592752457
Epoch 96/100, Loss: 3.5627509355545044
Epoch 97/100, Loss: 3.512451857328415
Epoch 98/100, Loss: 3.398882821202278
Epoch 99/100, Loss: 3.5300371646881104
Epoch 100/100, Loss: 3.5379699915647507
Fold 4/5 done
Epoch 1/100, Loss: 2.0131728500127792
Epoch 2/100, Loss: 2.0904311761260033
Epoch 3/100, Loss: 2.1517693251371384
Epoch 4/100, Loss: 2.0921037793159485
Epoch 5/100, Loss: 2.020963244140148
Epoch 6/100, Loss: 2.1446446031332016
Epoch 7/100, Loss: 2.1167911142110825
Epoch 8/100, Loss: 2.1438279896974564
Epoch 9/100, Loss: 2.0368010997772217

Epoch 10/100, Loss: 2.1643686667084694
Epoch 11/100, Loss: 2.031697638332844
Epoch 12/100, Loss: 2.0934137627482414
Epoch 13/100, Loss: 2.1285235062241554
Epoch 14/100, Loss: 2.116984076797962
Epoch 15/100, Loss: 2.2820380851626396
Epoch 16/100, Loss: 2.057275630533695
Epoch 17/100, Loss: 2.0513063818216324
Epoch 18/100, Loss: 2.098486043512821
Epoch 19/100, Loss: 2.1539982855319977
Epoch 20/100, Loss: 2.255077950656414
Epoch 21/100, Loss: 2.1192269176244736
Epoch 22/100, Loss: 2.3454384356737137
Epoch 23/100, Loss: 2.2006764635443687
Epoch 24/100, Loss: 2.286723807454109
Epoch 25/100, Loss: 2.1742741093039513
Epoch 26/100, Loss: 2.3370214626193047

Epoch 27/100, Loss: 2.1641431227326393
Epoch 28/100, Loss: 1.9420833140611649
Epoch 29/100, Loss: 2.037737987935543
Epoch 30/100, Loss: 2.156177170574665
Epoch 31/100, Loss: 2.100159525871277
Epoch 32/100, Loss: 2.117270030081272
Epoch 33/100, Loss: 2.070302374660969
Epoch 34/100, Loss: 2.1987309604883194
Epoch 35/100, Loss: 2.1881012320518494
Epoch 36/100, Loss: 2.0700634717941284
Epoch 37/100, Loss: 2.1329702362418175
Epoch 38/100, Loss: 2.066109284758568
Epoch 39/100, Loss: 2.1122723296284676
Epoch 40/100, Loss: 2.1266877949237823
Epoch 41/100, Loss: 2.182592123746872
Epoch 42/100, Loss: 2.058465339243412
Epoch 43/100, Loss: 2.093743659555912
Epoch 44/100, Loss: 2.193540185689926

Epoch 45/100, Loss: 2.187866725027561
Epoch 46/100, Loss: 2.0570753291249275
Epoch 47/100, Loss: 2.177008792757988
Epoch 48/100, Loss: 2.2665006294846535
Epoch 49/100, Loss: 2.2005822733044624
Epoch 50/100, Loss: 2.1936435252428055
Epoch 51/100, Loss: 2.150972805917263
Epoch 52/100, Loss: 2.1326941400766373
Epoch 53/100, Loss: 2.1164422407746315
Epoch 54/100, Loss: 2.1277750059962273
Epoch 55/100, Loss: 2.1123837754130363
Epoch 56/100, Loss: 2.169858083128929
Epoch 57/100, Loss: 2.0621099323034286
Epoch 58/100, Loss: 2.3214476481080055
Epoch 59/100, Loss: 2.1921027824282646
Epoch 60/100, Loss: 2.2308334335684776
Epoch 61/100, Loss: 2.043168179690838

Epoch 62/100, Loss: 2.2022342458367348
Epoch 63/100, Loss: 2.2912934198975563
Epoch 64/100, Loss: 1.9520652890205383
Epoch 65/100, Loss: 2.1960667222738266
Epoch 66/100, Loss: 2.1337594985961914
Epoch 67/100, Loss: 2.1050184220075607
Epoch 68/100, Loss: 2.128612421452999
Epoch 69/100, Loss: 2.13801446557045
Epoch 70/100, Loss: 2.1798294112086296
Epoch 71/100, Loss: 2.1376819908618927
Epoch 72/100, Loss: 2.1615057587623596
Epoch 73/100, Loss: 2.1073620840907097
Epoch 74/100, Loss: 2.1844445392489433
Epoch 75/100, Loss: 2.231766700744629
Epoch 76/100, Loss: 2.2187138944864273
Epoch 77/100, Loss: 2.16849447786808
Epoch 78/100, Loss: 2.2457421123981476

Epoch 79/100, Loss: 2.1827515214681625
Epoch 80/100, Loss: 1.9967439696192741
Epoch 81/100, Loss: 2.2366557493805885
Epoch 82/100, Loss: 2.2089874744415283
Epoch 83/100, Loss: 2.1223436444997787
Epoch 84/100, Loss: 2.1899722665548325
Epoch 85/100, Loss: 2.0628085657954216
Epoch 86/100, Loss: 2.0650573670864105
Epoch 87/100, Loss: 2.2118449211120605
Epoch 88/100, Loss: 2.334926590323448
Epoch 89/100, Loss: 2.1566963642835617
Epoch 90/100, Loss: 2.0194173231720924
Epoch 91/100, Loss: 2.1508122235536575
Epoch 92/100, Loss: 2.0654619187116623
Epoch 93/100, Loss: 2.196831628680229
Epoch 94/100, Loss: 2.1326340585947037
Epoch 95/100, Loss: 2.243595838546753
Epoch 96/100, Loss: 2.1405412778258324

Epoch 97/100, Loss: 2.136247042566538
Epoch 98/100, Loss: 2.161115847527981
Epoch 99/100, Loss: 2.03836752474308
Epoch 100/100, Loss: 2.189760237932205
Fold 5/5 done

In [11]:
ap = average_precision_score(y_true, anomaly_scores)
print(f"Deep SVDD AP (5-fold CV) = {ap:.4f}")
sb.glue("GBG500_ap_spectral_deep_svdd", float(ap))

Deep SVDD AP (5-fold CV) = 0.5960