In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import average_precision_score
from sklearn.model_selection import StratifiedKFold
from pyod.models.deep_svdd import DeepSVDD
import sys
import scrapbook as sb

sys.path.append('..')
from utils import reshape_to_numpy, interpolate_missing_values, denoise_data, compute_spectrograms, time_avg_pooling

In [2]:
seed = 1
sampling_rate = 10
nperseg=64
noverlap=32
accel_cutoff = 0.4
accel_order = 30
gyro_cutoff = 0.6
gyro_order = 20
batch_size = 32
epochs = 100
hidden_neurons = [128, 64, 32]
n_splits = 5

In [3]:
# Parameters
seed = 29

In [4]:
rng = np.random.RandomState(seed)

In [5]:
data = pd.read_parquet("../data/GBG500.parquet")
data

,ride_id,time_index,ax,ay,az,rx,ry,rz
0,005043f1a7520cebf1e17fd166a00a3190e2433530f236...,0,-2.512796,-9.385012,-1.053078,-0.009155,0.009155,-0.201416
1,005043f1a7520cebf1e17fd166a00a3190e2433530f236...,100,-2.491268,-9.385012,-1.079390,-0.036621,0.027465,-0.155639
2,005043f1a7520cebf1e17fd166a00a3190e2433530f236...,200,-2.534324,-9.382022,-1.030952,0.036621,0.027465,-0.073242
3,005043f1a7520cebf1e17fd166a00a3190e2433530f236...,300,-2.488278,-9.383218,-1.091948,-0.045776,0.036621,-0.183105
4,005043f1a7520cebf1e17fd166a00a3190e2433530f236...,400,-2.483494,-9.382022,-1.100320,-0.045776,0.027465,-0.192260
...,...,...,...,...,...,...,...,...
1529542,ffb6f2f5dc6ba768d88dc0bc1af4cad235526aa9e24168...,241300,0.459862,-9.140430,-3.318900,1.556396,-0.091552,0.274658
1529543,ffb6f2f5dc6ba768d88dc0bc1af4cad235526aa9e24168...,241400,0.455676,-9.140430,-3.321292,1.583861,-0.119018,0.274658
1529544,ffb6f2f5dc6ba768d88dc0bc1af4cad235526aa9e24168...,241500,0.459862,-9.139832,-3.317704,1.583861,-0.109863,0.274658
1529545,ffb6f2f5dc6ba768d88dc0bc1af4cad235526aa9e24168...,241600,0.456274,-9.142224,-3.321292,1.574707,-0.137329,0.283813
1529546,ffb6f2f5dc6ba768d88dc0bc1af4cad235526aa9e24168...,241700,0.458666,-9.139832,-3.320694,1.574707,-0.137329,0.274658

In [6]:
labels = pd.read_csv("../data/GBG500_labels.csv")
labels.columns = labels.columns.str.lower()
ride_order_df = pd.DataFrame({"ride_id": data["ride_id"].unique()})
labels_sorted = ride_order_df.merge(
    labels,
    on="ride_id",
    how="left"
)
labels_sorted

                                               ride_id        label
0    005043f1a7520cebf1e17fd166a00a3190e2433530f236...         Safe
1    00d223cb7aecc9c0cc5871e32a6c45027a068eba07c572...     Reckless
2    02288a4aeca044203394e982e76b87818021dea2b34df9...         Safe
3    0236bdcf13d473ea24d97f5eaeea459f257dffac005694...  Bad weather
4    0238e5dd85143f1b6c59b200bc32f14361b8fc84c51a87...         Safe
..                                                 ...          ...
495  fe5d7f84d692bbccad8bd566a3ad5c3108fa9f90acd671...         Safe
496  fe67169632306d4668b2affedef510df2cb43e2fb41220...         Safe
497  fee44667fdc8ab4995c702fc3bd36178de0b1ca2c64687...         Safe
498  ff79b2e945b93c2a5efc3a06365267b3a160e7849ba57d...         Safe
499  ffb6f2f5dc6ba768d88dc0bc1af4cad235526aa9e24168...         Safe

[500 rows x 2 columns]

In [7]:
data_np = reshape_to_numpy(
    data,
    features = ["ax", "ay", "az", "rx", "ry", "rz"],
    max_timestamps = 4800
)

data_np_clean = interpolate_missing_values(
    data_np,
    method='linear',
    limit=None
)

data_np_clean = denoise_data(
    data=data_np_clean,
    accel_indices=[0, 1, 2],
    gyro_indices=[3, 4, 5],
    accel_cutoff=accel_cutoff,
    accel_order=accel_order,
    gyro_cutoff=gyro_cutoff,
    gyro_order=gyro_order,
)

In [8]:
# Compute spectrograms for all rides
spectrograms_array = compute_spectrograms(data_np_clean, sampling_rate, nperseg, noverlap)
spectrograms_array.shape

(500, 149, 6, 33)

In [9]:
# Aggregate spectrograms using time-averaged pooling
X_feat = time_avg_pooling(spectrograms_array)
X_feat.shape

(500, 198)

In [10]:
# 5-fold stratified CV with Deep SVDD
skf = StratifiedKFold(n_splits=n_splits, shuffle=True, random_state=rng.randint(1000))
y_true = (labels_sorted['label'] == 'Reckless').astype(int).values
anomaly_scores = np.full(len(y_true), np.nan)

for fold, (train_idx, test_idx) in enumerate(skf.split(X_feat, y_true)):
    sc = StandardScaler()
    X_train = sc.fit_transform(X_feat[train_idx])
    X_test = sc.transform(X_feat[test_idx])

    np.random.seed(rng.randint(1000))
    model = DeepSVDD(
        n_features=X_train.shape[1],
        hidden_neurons=hidden_neurons,
        epochs=epochs,
        batch_size=batch_size,
        random_state=rng.randint(1000),
    )
    model.fit(X_train)
    anomaly_scores[test_idx] = model.decision_function(X_test)
    print(f"Fold {fold+1}/{n_splits} done")

Epoch 1/100, Loss: 1.6233303733170033
Epoch 2/100, Loss: 1.794529341161251
Epoch 3/100, Loss: 1.9204813167452812
Epoch 4/100, Loss: 1.6438475847244263
Epoch 5/100, Loss: 1.766414813697338
Epoch 6/100, Loss: 1.8139455392956734
Epoch 7/100, Loss: 1.695086233317852
Epoch 8/100, Loss: 1.8511410057544708
Epoch 9/100, Loss: 1.8941239230334759
Epoch 10/100, Loss: 1.732495117932558
Epoch 11/100, Loss: 1.7502440102398396
Epoch 12/100, Loss: 1.855854220688343
Epoch 13/100, Loss: 2.104090176522732
Epoch 14/100, Loss: 1.6092447564005852
Epoch 15/100, Loss: 1.8245963156223297
Epoch 16/100, Loss: 2.0752538591623306
Epoch 17/100, Loss: 1.9006211273372173
Epoch 18/100, Loss: 1.5982604622840881
Epoch 19/100, Loss: 1.893095813691616

Epoch 20/100, Loss: 1.8135642781853676
Epoch 21/100, Loss: 1.8934879004955292
Epoch 22/100, Loss: 1.8886251002550125
Epoch 23/100, Loss: 1.7850342094898224
Epoch 24/100, Loss: 1.8924572467803955
Epoch 25/100, Loss: 1.7790706679224968
Epoch 26/100, Loss: 1.6689226627349854
Epoch 27/100, Loss: 1.831064447760582
Epoch 28/100, Loss: 1.8490043580532074
Epoch 29/100, Loss: 1.8123226165771484
Epoch 30/100, Loss: 1.8308930061757565
Epoch 31/100, Loss: 1.880980245769024
Epoch 32/100, Loss: 1.8386360108852386
Epoch 33/100, Loss: 1.7584707215428352
Epoch 34/100, Loss: 1.901836521923542
Epoch 35/100, Loss: 1.9455020651221275
Epoch 36/100, Loss: 1.6971843019127846
Epoch 37/100, Loss: 1.6501362770795822

Epoch 38/100, Loss: 1.9050055891275406
Epoch 39/100, Loss: 1.702194668352604
Epoch 40/100, Loss: 1.8142004013061523
Epoch 41/100, Loss: 1.6799414940178394
Epoch 42/100, Loss: 1.740301139652729
Epoch 43/100, Loss: 1.8797597736120224
Epoch 44/100, Loss: 1.8031042367219925
Epoch 45/100, Loss: 1.6484192945063114
Epoch 46/100, Loss: 1.7365874908864498
Epoch 47/100, Loss: 1.8455307632684708
Epoch 48/100, Loss: 1.7639618143439293
Epoch 49/100, Loss: 1.796413041651249
Epoch 50/100, Loss: 1.8982476890087128
Epoch 51/100, Loss: 1.8926247954368591
Epoch 52/100, Loss: 1.77288818359375
Epoch 53/100, Loss: 1.767230562865734
Epoch 54/100, Loss: 1.7809526026248932
Epoch 55/100, Loss: 1.7423739098012447

Epoch 56/100, Loss: 1.852908506989479
Epoch 57/100, Loss: 1.7958464622497559
Epoch 58/100, Loss: 1.710267223417759
Epoch 59/100, Loss: 1.6329475976526737
Epoch 60/100, Loss: 1.9454140365123749
Epoch 61/100, Loss: 1.7271243706345558
Epoch 62/100, Loss: 1.77119380235672
Epoch 63/100, Loss: 1.8646778166294098
Epoch 64/100, Loss: 1.796438328921795
Epoch 65/100, Loss: 1.7061492428183556
Epoch 66/100, Loss: 1.8415989056229591
Epoch 67/100, Loss: 1.8177480027079582
Epoch 68/100, Loss: 1.7884052023291588
Epoch 69/100, Loss: 1.886004276573658
Epoch 70/100, Loss: 1.858305163681507
Epoch 71/100, Loss: 1.761992760002613
Epoch 72/100, Loss: 1.8299240805208683
Epoch 73/100, Loss: 1.7891704328358173

Epoch 74/100, Loss: 1.6550149098038673
Epoch 75/100, Loss: 1.6084844693541527
Epoch 76/100, Loss: 1.7850634008646011
Epoch 77/100, Loss: 1.7884960174560547
Epoch 78/100, Loss: 1.6189666017889977
Epoch 79/100, Loss: 2.054045271128416
Epoch 80/100, Loss: 1.7875980995595455
Epoch 81/100, Loss: 1.9193192422389984
Epoch 82/100, Loss: 1.7574251145124435
Epoch 83/100, Loss: 1.8108321577310562
Epoch 84/100, Loss: 1.7325320318341255
Epoch 85/100, Loss: 1.986321747303009
Epoch 86/100, Loss: 1.7822225391864777
Epoch 87/100, Loss: 1.887823037803173
Epoch 88/100, Loss: 1.7981762327253819
Epoch 89/100, Loss: 1.8455718234181404
Epoch 90/100, Loss: 1.7540008053183556
Epoch 91/100, Loss: 1.8684296160936356

Epoch 92/100, Loss: 1.8097522631287575
Epoch 93/100, Loss: 1.6016578562557697
Epoch 94/100, Loss: 1.7089474648237228
Epoch 95/100, Loss: 1.8263103514909744
Epoch 96/100, Loss: 1.800070933997631
Epoch 97/100, Loss: 1.912081740796566
Epoch 98/100, Loss: 1.9523226469755173
Epoch 99/100, Loss: 1.7683619633316994
Epoch 100/100, Loss: 1.8977231942117214
Fold 1/5 done
Epoch 1/100, Loss: 3.3020664155483246
Epoch 2/100, Loss: 3.762707255780697
Epoch 3/100, Loss: 4.082164287567139
Epoch 4/100, Loss: 3.4450835660099983
Epoch 5/100, Loss: 3.704527422785759
Epoch 6/100, Loss: 3.481388859450817
Epoch 7/100, Loss: 3.5889337360858917
Epoch 8/100, Loss: 4.20159300416708

Epoch 9/100, Loss: 3.671609416604042
Epoch 10/100, Loss: 3.263826258480549
Epoch 11/100, Loss: 3.430588185787201
Epoch 12/100, Loss: 3.4574779346585274
Epoch 13/100, Loss: 3.711834892630577
Epoch 14/100, Loss: 3.773247167468071
Epoch 15/100, Loss: 3.493105098605156
Epoch 16/100, Loss: 3.593500867486
Epoch 17/100, Loss: 3.445277288556099
Epoch 18/100, Loss: 3.5505923852324486
Epoch 19/100, Loss: 3.3566005304455757
Epoch 20/100, Loss: 3.4390290826559067
Epoch 21/100, Loss: 3.3836463391780853
Epoch 22/100, Loss: 3.612102210521698
Epoch 23/100, Loss: 3.6075303852558136
Epoch 24/100, Loss: 3.505497522652149
Epoch 25/100, Loss: 3.580029472708702
Epoch 26/100, Loss: 3.2943901643157005

Epoch 27/100, Loss: 3.3879872485995293
Epoch 28/100, Loss: 3.312572367489338
Epoch 29/100, Loss: 2.9743115305900574
Epoch 30/100, Loss: 3.4166940674185753
Epoch 31/100, Loss: 3.585257075726986
Epoch 32/100, Loss: 3.483059249818325
Epoch 33/100, Loss: 3.3610412180423737
Epoch 34/100, Loss: 3.3491184413433075
Epoch 35/100, Loss: 3.4200142547488213
Epoch 36/100, Loss: 3.279730699956417
Epoch 37/100, Loss: 3.6340328007936478
Epoch 38/100, Loss: 3.5316345244646072
Epoch 39/100, Loss: 3.7037766724824905
Epoch 40/100, Loss: 3.4238318651914597
Epoch 41/100, Loss: 3.381176233291626
Epoch 42/100, Loss: 3.1921215802431107
Epoch 43/100, Loss: 3.6128041744232178

Epoch 44/100, Loss: 3.345585808157921
Epoch 45/100, Loss: 3.5223448276519775
Epoch 46/100, Loss: 3.3973016515374184
Epoch 47/100, Loss: 3.401269569993019
Epoch 48/100, Loss: 3.27787147462368
Epoch 49/100, Loss: 3.8862102180719376
Epoch 50/100, Loss: 3.3989882692694664
Epoch 51/100, Loss: 3.4026142209768295
Epoch 52/100, Loss: 3.4296450316905975
Epoch 53/100, Loss: 3.2539033368229866
Epoch 54/100, Loss: 3.3537523075938225
Epoch 55/100, Loss: 3.673270858824253
Epoch 56/100, Loss: 3.414665400981903
Epoch 57/100, Loss: 3.3500247970223427
Epoch 58/100, Loss: 3.634429305791855
Epoch 59/100, Loss: 3.3830117732286453
Epoch 60/100, Loss: 3.460621699690819

Epoch 61/100, Loss: 3.361350141465664
Epoch 62/100, Loss: 3.6956391781568527
Epoch 63/100, Loss: 3.4335871189832687
Epoch 64/100, Loss: 3.565940946340561
Epoch 65/100, Loss: 3.929862305521965
Epoch 66/100, Loss: 3.448623575270176
Epoch 67/100, Loss: 3.3555498123168945
Epoch 68/100, Loss: 4.4522219598293304
Epoch 69/100, Loss: 4.481605187058449
Epoch 70/100, Loss: 3.9190526753664017
Epoch 71/100, Loss: 3.4766029119491577
Epoch 72/100, Loss: 3.2700861915946007
Epoch 73/100, Loss: 3.3617554306983948
Epoch 74/100, Loss: 3.389563538134098
Epoch 75/100, Loss: 3.6097163408994675
Epoch 76/100, Loss: 3.344113916158676
Epoch 77/100, Loss: 3.1566598936915398
Epoch 78/100, Loss: 3.4428232982754707

Epoch 79/100, Loss: 3.5007980912923813
Epoch 80/100, Loss: 3.4173616841435432
Epoch 81/100, Loss: 3.7193477153778076
Epoch 82/100, Loss: 3.4536666870117188
Epoch 83/100, Loss: 3.7062922418117523
Epoch 84/100, Loss: 3.7296784296631813
Epoch 85/100, Loss: 3.4264769107103348
Epoch 86/100, Loss: 3.3650584742426872
Epoch 87/100, Loss: 3.263339288532734
Epoch 88/100, Loss: 3.3553078174591064
Epoch 89/100, Loss: 3.79706147313118
Epoch 90/100, Loss: 3.3538373336195946
Epoch 91/100, Loss: 3.6883837580680847
Epoch 92/100, Loss: 3.411899946630001
Epoch 93/100, Loss: 3.4263140186667442
Epoch 94/100, Loss: 3.336261734366417
Epoch 95/100, Loss: 3.6562316715717316
Epoch 96/100, Loss: 3.5893485248088837

Epoch 97/100, Loss: 3.6267692297697067
Epoch 98/100, Loss: 3.3402630910277367
Epoch 99/100, Loss: 3.54312851279974
Epoch 100/100, Loss: 3.7221474051475525
Fold 2/5 done
Epoch 1/100, Loss: 2.9650056958198547
Epoch 2/100, Loss: 2.893456846475601
Epoch 3/100, Loss: 3.3019369393587112
Epoch 4/100, Loss: 2.8970682099461555
Epoch 5/100, Loss: 3.06046923995018
Epoch 6/100, Loss: 2.7942523136734962
Epoch 7/100, Loss: 2.8358679562807083
Epoch 8/100, Loss: 2.7372575476765633
Epoch 9/100, Loss: 2.6985017508268356
Epoch 10/100, Loss: 2.7423514053225517
Epoch 11/100, Loss: 2.8900526091456413
Epoch 12/100, Loss: 2.9454691782593727
Epoch 13/100, Loss: 2.9088043496012688

Epoch 14/100, Loss: 2.9185561686754227
Epoch 15/100, Loss: 2.878541238605976
Epoch 16/100, Loss: 2.716587394475937
Epoch 17/100, Loss: 3.0786697268486023
Epoch 18/100, Loss: 2.843453072011471
Epoch 19/100, Loss: 2.832961529493332
Epoch 20/100, Loss: 3.029541067779064
Epoch 21/100, Loss: 2.879069246351719
Epoch 22/100, Loss: 2.9609931856393814
Epoch 23/100, Loss: 2.7600374594330788
Epoch 24/100, Loss: 2.9692670553922653
Epoch 25/100, Loss: 2.774911843240261
Epoch 26/100, Loss: 2.8203116059303284
Epoch 27/100, Loss: 3.045352764427662
Epoch 28/100, Loss: 2.8039083778858185
Epoch 29/100, Loss: 2.8572813123464584
Epoch 30/100, Loss: 2.913859575986862

Epoch 31/100, Loss: 2.808022491633892
Epoch 32/100, Loss: 2.9904920533299446
Epoch 33/100, Loss: 2.772252209484577
Epoch 34/100, Loss: 3.0357313007116318
Epoch 35/100, Loss: 3.001248851418495
Epoch 36/100, Loss: 2.5253140181303024
Epoch 37/100, Loss: 2.787919983267784
Epoch 38/100, Loss: 2.7959920316934586
Epoch 39/100, Loss: 3.329223521053791
Epoch 40/100, Loss: 2.804480493068695
Epoch 41/100, Loss: 2.727160133421421
Epoch 42/100, Loss: 2.9652933850884438
Epoch 43/100, Loss: 2.9582586362957954
Epoch 44/100, Loss: 3.021419659256935
Epoch 45/100, Loss: 2.8774228543043137
Epoch 46/100, Loss: 2.836171805858612
Epoch 47/100, Loss: 3.3732250183820724
Epoch 48/100, Loss: 2.9913860112428665

Epoch 49/100, Loss: 3.153054431080818
Epoch 50/100, Loss: 2.697883941233158
Epoch 51/100, Loss: 2.811121106147766
Epoch 52/100, Loss: 2.928159549832344
Epoch 53/100, Loss: 2.8515563309192657
Epoch 54/100, Loss: 2.990382134914398
Epoch 55/100, Loss: 3.6097529754042625
Epoch 56/100, Loss: 2.809457413852215
Epoch 57/100, Loss: 2.7258167266845703
Epoch 58/100, Loss: 2.9867840334773064
Epoch 59/100, Loss: 2.8916688188910484
Epoch 60/100, Loss: 2.8620096668601036
Epoch 61/100, Loss: 2.7235810086131096
Epoch 62/100, Loss: 2.814372330904007
Epoch 63/100, Loss: 2.6044112741947174
Epoch 64/100, Loss: 2.849598541855812
Epoch 65/100, Loss: 2.7037467882037163
Epoch 66/100, Loss: 3.1479086130857468

Epoch 67/100, Loss: 2.715789921581745
Epoch 68/100, Loss: 2.762295350432396
Epoch 69/100, Loss: 2.8478359282016754
Epoch 70/100, Loss: 2.6443392857909203
Epoch 71/100, Loss: 2.715287536382675
Epoch 72/100, Loss: 3.009724348783493
Epoch 73/100, Loss: 2.911304496228695
Epoch 74/100, Loss: 2.6051896139979362
Epoch 75/100, Loss: 2.7843917533755302
Epoch 76/100, Loss: 2.9802618622779846
Epoch 77/100, Loss: 2.6921043545007706
Epoch 78/100, Loss: 2.801268056035042
Epoch 79/100, Loss: 2.78779299557209
Epoch 80/100, Loss: 2.778898186981678
Epoch 81/100, Loss: 2.825315371155739
Epoch 82/100, Loss: 2.9934085607528687
Epoch 83/100, Loss: 2.782195560634136
Epoch 84/100, Loss: 2.8393910080194473

Epoch 85/100, Loss: 3.0004968643188477
Epoch 86/100, Loss: 2.8917722702026367
Epoch 87/100, Loss: 2.8452649787068367
Epoch 88/100, Loss: 2.953977771103382
Epoch 89/100, Loss: 2.5904670357704163
Epoch 90/100, Loss: 3.109716981649399
Epoch 91/100, Loss: 2.7896048426628113
Epoch 92/100, Loss: 2.8109038919210434
Epoch 93/100, Loss: 2.92819831520319
Epoch 94/100, Loss: 2.7705328837037086
Epoch 95/100, Loss: 2.780956894159317
Epoch 96/100, Loss: 2.8542000502347946
Epoch 97/100, Loss: 2.811369337141514
Epoch 98/100, Loss: 2.7951180040836334
Epoch 99/100, Loss: 3.0404331386089325
Epoch 100/100, Loss: 2.8202799186110497
Fold 3/5 done
Epoch 1/100, Loss: 4.118576020002365

Epoch 2/100, Loss: 4.239043116569519
Epoch 3/100, Loss: 4.244198873639107
Epoch 4/100, Loss: 4.085038632154465
Epoch 5/100, Loss: 4.250459998846054
Epoch 6/100, Loss: 3.9601251035928726
Epoch 7/100, Loss: 4.067255660891533
Epoch 8/100, Loss: 4.086356654763222
Epoch 9/100, Loss: 4.106375142931938
Epoch 10/100, Loss: 4.13731974363327
Epoch 11/100, Loss: 4.195095911622047
Epoch 12/100, Loss: 4.03489126265049
Epoch 13/100, Loss: 4.186242878437042
Epoch 14/100, Loss: 4.184798792004585
Epoch 15/100, Loss: 4.142484292387962
Epoch 16/100, Loss: 4.139491394162178
Epoch 17/100, Loss: 4.073228597640991
Epoch 18/100, Loss: 4.342547506093979
Epoch 19/100, Loss: 4.100616842508316

Epoch 20/100, Loss: 4.138747125864029
Epoch 21/100, Loss: 4.261925473809242
Epoch 22/100, Loss: 3.936455950140953
Epoch 23/100, Loss: 4.236215576529503
Epoch 24/100, Loss: 4.2979733645915985
Epoch 25/100, Loss: 4.2382586151361465
Epoch 26/100, Loss: 4.207163214683533
Epoch 27/100, Loss: 4.181849777698517
Epoch 28/100, Loss: 4.216744005680084
Epoch 29/100, Loss: 3.909372314810753
Epoch 30/100, Loss: 4.112120866775513
Epoch 31/100, Loss: 3.9913495033979416
Epoch 32/100, Loss: 4.147941827774048
Epoch 33/100, Loss: 4.3194903284311295
Epoch 34/100, Loss: 3.9465194791555405
Epoch 35/100, Loss: 3.9665320217609406
Epoch 36/100, Loss: 4.090719640254974
Epoch 37/100, Loss: 4.0937952399253845

Epoch 38/100, Loss: 4.0659220069646835
Epoch 39/100, Loss: 4.353406563401222
Epoch 40/100, Loss: 4.319603070616722
Epoch 41/100, Loss: 4.056495800614357
Epoch 42/100, Loss: 4.016239240765572
Epoch 43/100, Loss: 4.053972899913788
Epoch 44/100, Loss: 4.073360726237297
Epoch 45/100, Loss: 4.176625698804855
Epoch 46/100, Loss: 3.986319065093994
Epoch 47/100, Loss: 4.270106106996536
Epoch 48/100, Loss: 4.094776973128319
Epoch 49/100, Loss: 4.139559507369995
Epoch 50/100, Loss: 4.354791671037674
Epoch 51/100, Loss: 3.872221738100052
Epoch 52/100, Loss: 4.045113444328308
Epoch 53/100, Loss: 4.153325706720352
Epoch 54/100, Loss: 4.062185063958168
Epoch 55/100, Loss: 4.1308880895376205

Epoch 56/100, Loss: 4.131554022431374
Epoch 57/100, Loss: 4.121870398521423
Epoch 58/100, Loss: 4.113657519221306
Epoch 59/100, Loss: 4.0579515397548676
Epoch 60/100, Loss: 4.164056599140167
Epoch 61/100, Loss: 4.1628579050302505
Epoch 62/100, Loss: 4.026111796498299
Epoch 63/100, Loss: 4.2121370285749435
Epoch 64/100, Loss: 4.088303253054619
Epoch 65/100, Loss: 4.233906656503677
Epoch 66/100, Loss: 4.230919569730759
Epoch 67/100, Loss: 4.143136419355869
Epoch 68/100, Loss: 4.13942988216877
Epoch 69/100, Loss: 4.207960948348045
Epoch 70/100, Loss: 4.154007241129875
Epoch 71/100, Loss: 3.9620996862649918
Epoch 72/100, Loss: 4.323675706982613
Epoch 73/100, Loss: 4.158050984144211

Epoch 74/100, Loss: 4.240026637911797
Epoch 75/100, Loss: 4.191523477435112
Epoch 76/100, Loss: 4.300474599003792
Epoch 77/100, Loss: 4.217912793159485
Epoch 78/100, Loss: 3.9131267815828323
Epoch 79/100, Loss: 3.928644508123398
Epoch 80/100, Loss: 4.091761127114296
Epoch 81/100, Loss: 4.2488671243190765
Epoch 82/100, Loss: 4.043380960822105
Epoch 83/100, Loss: 4.015544816851616
Epoch 84/100, Loss: 3.98013174533844
Epoch 85/100, Loss: 4.0335321724414825
Epoch 86/100, Loss: 4.2218363136053085
Epoch 87/100, Loss: 3.983522981405258
Epoch 88/100, Loss: 4.125896126031876
Epoch 89/100, Loss: 4.0169558972120285
Epoch 90/100, Loss: 4.160338714718819
Epoch 91/100, Loss: 4.3688962161540985

Epoch 92/100, Loss: 4.083984687924385
Epoch 93/100, Loss: 4.172792047262192
Epoch 94/100, Loss: 4.119155690073967
Epoch 95/100, Loss: 4.2043642699718475
Epoch 96/100, Loss: 4.129065692424774
Epoch 97/100, Loss: 4.306628376245499
Epoch 98/100, Loss: 4.132489159703255
Epoch 99/100, Loss: 3.9955774396657944
Epoch 100/100, Loss: 4.169461354613304
Fold 4/5 done
Epoch 1/100, Loss: 1.4617286622524261
Epoch 2/100, Loss: 1.533352293074131
Epoch 3/100, Loss: 1.5533398762345314
Epoch 4/100, Loss: 1.5147574543952942
Epoch 5/100, Loss: 1.5456801354885101
Epoch 6/100, Loss: 1.5108079984784126
Epoch 7/100, Loss: 1.5667745620012283
Epoch 8/100, Loss: 1.443877525627613
Epoch 9/100, Loss: 1.6659530103206635

Epoch 10/100, Loss: 1.5047696009278297
Epoch 11/100, Loss: 1.5497945994138718
Epoch 12/100, Loss: 1.5210253819823265
Epoch 13/100, Loss: 1.4766047596931458
Epoch 14/100, Loss: 1.5537107288837433
Epoch 15/100, Loss: 1.5642765387892723
Epoch 16/100, Loss: 1.499333769083023
Epoch 17/100, Loss: 1.5042614042758942
Epoch 18/100, Loss: 1.604661650955677
Epoch 19/100, Loss: 1.544258013367653
Epoch 20/100, Loss: 1.515917792916298
Epoch 21/100, Loss: 1.5618745610117912
Epoch 22/100, Loss: 1.478341706097126
Epoch 23/100, Loss: 1.5419260188937187
Epoch 24/100, Loss: 1.415182150900364
Epoch 25/100, Loss: 1.5431738942861557
Epoch 26/100, Loss: 1.4797919020056725
Epoch 27/100, Loss: 1.5730926916003227
Epoch 28/100, Loss: 1.52423395216465

Epoch 29/100, Loss: 1.4544041529297829
Epoch 30/100, Loss: 1.5175209641456604
Epoch 31/100, Loss: 1.5060740858316422
Epoch 32/100, Loss: 1.4487155377864838
Epoch 33/100, Loss: 1.3962467014789581
Epoch 34/100, Loss: 1.4406951069831848
Epoch 35/100, Loss: 1.5776900947093964
Epoch 36/100, Loss: 1.4725606814026833
Epoch 37/100, Loss: 1.4602159038186073
Epoch 38/100, Loss: 1.5428539738059044
Epoch 39/100, Loss: 1.5365237221121788
Epoch 40/100, Loss: 1.5186742469668388
Epoch 41/100, Loss: 1.5635004863142967
Epoch 42/100, Loss: 1.5796352475881577
Epoch 43/100, Loss: 1.665969267487526
Epoch 44/100, Loss: 1.4277668446302414
Epoch 45/100, Loss: 1.5317831486463547
Epoch 46/100, Loss: 1.6520654559135437
Epoch 47/100, Loss: 1.6253500282764435

Epoch 48/100, Loss: 1.629794456064701
Epoch 49/100, Loss: 1.5787662118673325
Epoch 50/100, Loss: 1.5713825970888138
Epoch 51/100, Loss: 1.5561320781707764
Epoch 52/100, Loss: 1.547835573554039
Epoch 53/100, Loss: 1.52768025547266
Epoch 54/100, Loss: 1.5264136865735054
Epoch 55/100, Loss: 1.6449898481369019
Epoch 56/100, Loss: 1.5066108256578445
Epoch 57/100, Loss: 1.4858613908290863
Epoch 58/100, Loss: 1.4961174950003624
Epoch 59/100, Loss: 1.6234946623444557
Epoch 60/100, Loss: 1.5240928679704666
Epoch 61/100, Loss: 1.5256245285272598
Epoch 62/100, Loss: 1.4711915701627731
Epoch 63/100, Loss: 1.5869898423552513
Epoch 64/100, Loss: 1.4344416707754135
Epoch 65/100, Loss: 1.4353443384170532

Epoch 66/100, Loss: 1.524223156273365
Epoch 67/100, Loss: 1.6616937518119812
Epoch 68/100, Loss: 1.5272523611783981
Epoch 69/100, Loss: 1.6111400052905083
Epoch 70/100, Loss: 1.5047585219144821
Epoch 71/100, Loss: 1.4869650453329086
Epoch 72/100, Loss: 1.502409189939499
Epoch 73/100, Loss: 1.5538410395383835
Epoch 74/100, Loss: 1.5819921270012856
Epoch 75/100, Loss: 1.5466314256191254
Epoch 76/100, Loss: 1.5760621801018715
Epoch 77/100, Loss: 1.4901115074753761
Epoch 78/100, Loss: 1.5274161398410797
Epoch 79/100, Loss: 1.6149084940552711
Epoch 80/100, Loss: 1.4685022234916687
Epoch 81/100, Loss: 1.5374886617064476
Epoch 82/100, Loss: 1.473382592201233
Epoch 83/100, Loss: 1.5360546931624413

Epoch 84/100, Loss: 1.5526961833238602
Epoch 85/100, Loss: 1.5706058889627457
Epoch 86/100, Loss: 1.4604935869574547
Epoch 87/100, Loss: 1.4524644613265991
Epoch 88/100, Loss: 1.5053951814770699
Epoch 89/100, Loss: 1.6329554915428162
Epoch 90/100, Loss: 1.487163431942463
Epoch 91/100, Loss: 1.4431887790560722
Epoch 92/100, Loss: 1.4579074531793594
Epoch 93/100, Loss: 1.487896852195263
Epoch 94/100, Loss: 1.582346886396408
Epoch 95/100, Loss: 1.5532917007803917
Epoch 96/100, Loss: 1.5069417282938957
Epoch 97/100, Loss: 1.5210383161902428
Epoch 98/100, Loss: 1.5717246383428574
Epoch 99/100, Loss: 1.482140228152275
Epoch 100/100, Loss: 1.5326082557439804
Fold 5/5 done

In [11]:
ap = average_precision_score(y_true, anomaly_scores)
print(f"Deep SVDD AP (5-fold CV) = {ap:.4f}")
sb.glue("GBG500_ap_spectral_deep_svdd", float(ap))

Deep SVDD AP (5-fold CV) = 0.4523