In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import average_precision_score
from sklearn.model_selection import StratifiedKFold
from pyod.models.deep_svdd import DeepSVDD
import sys
import scrapbook as sb

sys.path.append('..')
from utils import reshape_to_numpy, interpolate_missing_values, denoise_data, compute_spectrograms, time_avg_pooling

In [2]:
seed = 1
sampling_rate = 10
nperseg=64
noverlap=32
accel_cutoff = 0.4
accel_order = 30
gyro_cutoff = 0.6
gyro_order = 20
batch_size = 32
epochs = 100
hidden_neurons = [128, 64, 32]
n_splits = 5

In [3]:
# Parameters
seed = 16

In [4]:
rng = np.random.RandomState(seed)

In [5]:
data = pd.read_parquet("../data/GBG500.parquet")
data

,ride_id,time_index,ax,ay,az,rx,ry,rz
0,005043f1a7520cebf1e17fd166a00a3190e2433530f236...,0,-2.512796,-9.385012,-1.053078,-0.009155,0.009155,-0.201416
1,005043f1a7520cebf1e17fd166a00a3190e2433530f236...,100,-2.491268,-9.385012,-1.079390,-0.036621,0.027465,-0.155639
2,005043f1a7520cebf1e17fd166a00a3190e2433530f236...,200,-2.534324,-9.382022,-1.030952,0.036621,0.027465,-0.073242
3,005043f1a7520cebf1e17fd166a00a3190e2433530f236...,300,-2.488278,-9.383218,-1.091948,-0.045776,0.036621,-0.183105
4,005043f1a7520cebf1e17fd166a00a3190e2433530f236...,400,-2.483494,-9.382022,-1.100320,-0.045776,0.027465,-0.192260
...,...,...,...,...,...,...,...,...
1529542,ffb6f2f5dc6ba768d88dc0bc1af4cad235526aa9e24168...,241300,0.459862,-9.140430,-3.318900,1.556396,-0.091552,0.274658
1529543,ffb6f2f5dc6ba768d88dc0bc1af4cad235526aa9e24168...,241400,0.455676,-9.140430,-3.321292,1.583861,-0.119018,0.274658
1529544,ffb6f2f5dc6ba768d88dc0bc1af4cad235526aa9e24168...,241500,0.459862,-9.139832,-3.317704,1.583861,-0.109863,0.274658
1529545,ffb6f2f5dc6ba768d88dc0bc1af4cad235526aa9e24168...,241600,0.456274,-9.142224,-3.321292,1.574707,-0.137329,0.283813
1529546,ffb6f2f5dc6ba768d88dc0bc1af4cad235526aa9e24168...,241700,0.458666,-9.139832,-3.320694,1.574707,-0.137329,0.274658

In [6]:
labels = pd.read_csv("../data/GBG500_labels.csv")
labels.columns = labels.columns.str.lower()
ride_order_df = pd.DataFrame({"ride_id": data["ride_id"].unique()})
labels_sorted = ride_order_df.merge(
    labels,
    on="ride_id",
    how="left"
)
labels_sorted

                                               ride_id        label
0    005043f1a7520cebf1e17fd166a00a3190e2433530f236...         Safe
1    00d223cb7aecc9c0cc5871e32a6c45027a068eba07c572...     Reckless
2    02288a4aeca044203394e982e76b87818021dea2b34df9...         Safe
3    0236bdcf13d473ea24d97f5eaeea459f257dffac005694...  Bad weather
4    0238e5dd85143f1b6c59b200bc32f14361b8fc84c51a87...         Safe
..                                                 ...          ...
495  fe5d7f84d692bbccad8bd566a3ad5c3108fa9f90acd671...         Safe
496  fe67169632306d4668b2affedef510df2cb43e2fb41220...         Safe
497  fee44667fdc8ab4995c702fc3bd36178de0b1ca2c64687...         Safe
498  ff79b2e945b93c2a5efc3a06365267b3a160e7849ba57d...         Safe
499  ffb6f2f5dc6ba768d88dc0bc1af4cad235526aa9e24168...         Safe

[500 rows x 2 columns]

In [7]:
data_np = reshape_to_numpy(
    data,
    features = ["ax", "ay", "az", "rx", "ry", "rz"],
    max_timestamps = 4800
)

data_np_clean = interpolate_missing_values(
    data_np,
    method='linear',
    limit=None
)

data_np_clean = denoise_data(
    data=data_np_clean,
    accel_indices=[0, 1, 2],
    gyro_indices=[3, 4, 5],
    accel_cutoff=accel_cutoff,
    accel_order=accel_order,
    gyro_cutoff=gyro_cutoff,
    gyro_order=gyro_order,
)

In [8]:
# Compute spectrograms for all rides
spectrograms_array = compute_spectrograms(data_np_clean, sampling_rate, nperseg, noverlap)
spectrograms_array.shape

(500, 149, 6, 33)

In [9]:
# Aggregate spectrograms using time-averaged pooling
X_feat = time_avg_pooling(spectrograms_array)
X_feat.shape

(500, 198)

In [10]:
# 5-fold stratified CV with Deep SVDD
skf = StratifiedKFold(n_splits=n_splits, shuffle=True, random_state=rng.randint(1000))
y_true = (labels_sorted['label'] == 'Reckless').astype(int).values
anomaly_scores = np.full(len(y_true), np.nan)

for fold, (train_idx, test_idx) in enumerate(skf.split(X_feat, y_true)):
    sc = StandardScaler()
    X_train = sc.fit_transform(X_feat[train_idx])
    X_test = sc.transform(X_feat[test_idx])

    np.random.seed(rng.randint(1000))
    model = DeepSVDD(
        n_features=X_train.shape[1],
        hidden_neurons=hidden_neurons,
        epochs=epochs,
        batch_size=batch_size,
        random_state=rng.randint(1000),
    )
    model.fit(X_train)
    anomaly_scores[test_idx] = model.decision_function(X_test)
    print(f"Fold {fold+1}/{n_splits} done")

Epoch 1/100, Loss: 2.55338017642498
Epoch 2/100, Loss: 2.695490352809429
Epoch 3/100, Loss: 2.797163747251034
Epoch 4/100, Loss: 2.7398133724927902
Epoch 5/100, Loss: 2.3424980491399765
Epoch 6/100, Loss: 2.822334349155426
Epoch 7/100, Loss: 2.8525632172822952
Epoch 8/100, Loss: 2.6562384516000748
Epoch 9/100, Loss: 2.546669267117977
Epoch 10/100, Loss: 2.915204681456089
Epoch 11/100, Loss: 2.6510131135582924
Epoch 12/100, Loss: 2.5145634710788727
Epoch 13/100, Loss: 2.5083244666457176
Epoch 14/100, Loss: 2.7076574862003326
Epoch 15/100, Loss: 2.5864038169384003

Epoch 16/100, Loss: 2.533773384988308
Epoch 17/100, Loss: 2.736528903245926
Epoch 18/100, Loss: 2.489161938428879
Epoch 19/100, Loss: 2.7320399582386017
Epoch 20/100, Loss: 2.531670033931732
Epoch 21/100, Loss: 2.828640639781952
Epoch 22/100, Loss: 2.765851892530918
Epoch 23/100, Loss: 2.747167728841305
Epoch 24/100, Loss: 2.8095337599515915
Epoch 25/100, Loss: 2.9569828808307648
Epoch 26/100, Loss: 2.680164374411106
Epoch 27/100, Loss: 2.8049691393971443
Epoch 28/100, Loss: 2.898306220769882
Epoch 29/100, Loss: 2.760156363248825
Epoch 30/100, Loss: 2.827836751937866

Epoch 31/100, Loss: 2.7523029893636703
Epoch 32/100, Loss: 2.7423907071352005
Epoch 33/100, Loss: 2.797538012266159
Epoch 34/100, Loss: 2.7237603589892387
Epoch 35/100, Loss: 2.696680448949337
Epoch 36/100, Loss: 2.7173379212617874
Epoch 37/100, Loss: 2.835376352071762
Epoch 38/100, Loss: 2.6067269295454025
Epoch 39/100, Loss: 2.850962519645691
Epoch 40/100, Loss: 2.5342081859707832
Epoch 41/100, Loss: 2.7634591832756996
Epoch 42/100, Loss: 2.498912163078785
Epoch 43/100, Loss: 2.723916471004486
Epoch 44/100, Loss: 2.744577996432781
Epoch 45/100, Loss: 2.578026369214058

Epoch 46/100, Loss: 2.775046654045582
Epoch 47/100, Loss: 2.5988893657922745
Epoch 48/100, Loss: 2.726002410054207
Epoch 49/100, Loss: 2.6842555105686188
Epoch 50/100, Loss: 2.6797557175159454
Epoch 51/100, Loss: 2.489896535873413
Epoch 52/100, Loss: 2.8072312250733376
Epoch 53/100, Loss: 2.629721350967884
Epoch 54/100, Loss: 2.875641703605652
Epoch 55/100, Loss: 2.715119369328022
Epoch 56/100, Loss: 2.7696256563067436

Epoch 57/100, Loss: 2.664498634636402
Epoch 58/100, Loss: 2.7409841120243073
Epoch 59/100, Loss: 2.5336210057139397
Epoch 60/100, Loss: 2.6459884494543076
Epoch 61/100, Loss: 2.6599235236644745
Epoch 62/100, Loss: 2.588060364127159
Epoch 63/100, Loss: 2.8535437136888504
Epoch 64/100, Loss: 2.6448590755462646
Epoch 65/100, Loss: 2.6605181246995926
Epoch 66/100, Loss: 2.550495631992817
Epoch 67/100, Loss: 2.5923682749271393

Epoch 68/100, Loss: 3.013537712395191
Epoch 69/100, Loss: 2.7766341492533684
Epoch 70/100, Loss: 2.450836658477783
Epoch 71/100, Loss: 2.5379489809274673
Epoch 72/100, Loss: 2.4361736699938774
Epoch 73/100, Loss: 2.7637774869799614
Epoch 74/100, Loss: 2.913906291127205
Epoch 75/100, Loss: 2.703649081289768
Epoch 76/100, Loss: 2.8761093467473984
Epoch 77/100, Loss: 2.627753719687462
Epoch 78/100, Loss: 2.8434671238064766

Epoch 79/100, Loss: 2.680908001959324
Epoch 80/100, Loss: 2.8752753138542175
Epoch 81/100, Loss: 2.69411251693964
Epoch 82/100, Loss: 3.2729170098900795
Epoch 83/100, Loss: 2.8629897981882095
Epoch 84/100, Loss: 2.7543675377964973
Epoch 85/100, Loss: 2.881039008498192
Epoch 86/100, Loss: 2.3767319917678833
Epoch 87/100, Loss: 2.8409407511353493
Epoch 88/100, Loss: 2.9324567914009094
Epoch 89/100, Loss: 2.6724534928798676

Epoch 90/100, Loss: 2.5512905195355415
Epoch 91/100, Loss: 2.850465640425682
Epoch 92/100, Loss: 2.6582048907876015
Epoch 93/100, Loss: 2.5165913105010986
Epoch 94/100, Loss: 2.669753886759281
Epoch 95/100, Loss: 2.51231350004673
Epoch 96/100, Loss: 2.87550950050354
Epoch 97/100, Loss: 2.779681369662285
Epoch 98/100, Loss: 2.4310788065195084
Epoch 99/100, Loss: 2.6085666865110397
Epoch 100/100, Loss: 2.6140457093715668

Fold 1/5 done
Epoch 1/100, Loss: 3.349887326359749
Epoch 2/100, Loss: 3.27003176510334
Epoch 3/100, Loss: 3.2978539019823074
Epoch 4/100, Loss: 3.152682565152645
Epoch 5/100, Loss: 3.355358839035034
Epoch 6/100, Loss: 3.1904936134815216
Epoch 7/100, Loss: 3.326429933309555
Epoch 8/100, Loss: 3.289764568209648
Epoch 9/100, Loss: 3.341019257903099
Epoch 10/100, Loss: 3.3054577708244324
Epoch 11/100, Loss: 3.023690737783909
Epoch 12/100, Loss: 3.6737117916345596
Epoch 13/100, Loss: 3.3037208691239357

Epoch 14/100, Loss: 3.3610203117132187
Epoch 15/100, Loss: 3.1065191105008125
Epoch 16/100, Loss: 3.157501243054867
Epoch 17/100, Loss: 3.506226673722267
Epoch 18/100, Loss: 3.2988061755895615
Epoch 19/100, Loss: 3.3885965645313263
Epoch 20/100, Loss: 3.334422931075096
Epoch 21/100, Loss: 3.4839199781417847
Epoch 22/100, Loss: 3.0043663531541824
Epoch 23/100, Loss: 3.2899052649736404
Epoch 24/100, Loss: 3.682281479239464
Epoch 25/100, Loss: 3.2490057796239853
Epoch 26/100, Loss: 3.392866902053356
Epoch 27/100, Loss: 3.1060076281428337
Epoch 28/100, Loss: 3.4744898974895477

Epoch 29/100, Loss: 3.278147667646408
Epoch 30/100, Loss: 3.5292201042175293
Epoch 31/100, Loss: 3.118534192442894
Epoch 32/100, Loss: 3.146347589790821
Epoch 33/100, Loss: 3.189341202378273
Epoch 34/100, Loss: 3.3090772181749344
Epoch 35/100, Loss: 3.383729502558708
Epoch 36/100, Loss: 3.376125141978264
Epoch 37/100, Loss: 2.9338928684592247
Epoch 38/100, Loss: 3.453113332390785
Epoch 39/100, Loss: 3.4097796007990837
Epoch 40/100, Loss: 3.1759944707155228
Epoch 41/100, Loss: 3.26251669973135
Epoch 42/100, Loss: 3.5193556994199753
Epoch 43/100, Loss: 3.2706204056739807

Epoch 44/100, Loss: 3.4530749917030334
Epoch 45/100, Loss: 3.166263535618782
Epoch 46/100, Loss: 3.5590082854032516
Epoch 47/100, Loss: 2.912547253072262
Epoch 48/100, Loss: 3.4616086333990097
Epoch 49/100, Loss: 3.137041762471199
Epoch 50/100, Loss: 3.234810382127762
Epoch 51/100, Loss: 3.2771940529346466
Epoch 52/100, Loss: 3.369679346680641
Epoch 53/100, Loss: 3.1366856545209885
Epoch 54/100, Loss: 3.0669586211442947
Epoch 55/100, Loss: 3.780223958194256
Epoch 56/100, Loss: 3.379946708679199
Epoch 57/100, Loss: 3.0735916942358017
Epoch 58/100, Loss: 3.4297767654061317

Epoch 59/100, Loss: 3.0672767162323
Epoch 60/100, Loss: 3.291453242301941
Epoch 61/100, Loss: 3.1590005084872246
Epoch 62/100, Loss: 3.48080937564373
Epoch 63/100, Loss: 3.223028391599655
Epoch 64/100, Loss: 3.444692276418209
Epoch 65/100, Loss: 3.3573393747210503
Epoch 66/100, Loss: 3.5845808312296867
Epoch 67/100, Loss: 3.233990117907524
Epoch 68/100, Loss: 3.3195077925920486
Epoch 69/100, Loss: 3.032755009829998

Epoch 70/100, Loss: 3.486325040459633
Epoch 71/100, Loss: 3.4724543541669846
Epoch 72/100, Loss: 3.213797390460968
Epoch 73/100, Loss: 3.4665848091244698
Epoch 74/100, Loss: 3.04448252171278
Epoch 75/100, Loss: 3.386013984680176
Epoch 76/100, Loss: 3.233573153614998
Epoch 77/100, Loss: 3.241259917616844
Epoch 78/100, Loss: 3.2882489040493965
Epoch 79/100, Loss: 3.5590399354696274
Epoch 80/100, Loss: 3.5239428132772446

Epoch 81/100, Loss: 3.413645789027214
Epoch 82/100, Loss: 3.4748930037021637
Epoch 83/100, Loss: 3.429087072610855
Epoch 84/100, Loss: 3.178793914616108
Epoch 85/100, Loss: 3.445779174566269
Epoch 86/100, Loss: 4.107676565647125
Epoch 87/100, Loss: 3.2659886330366135
Epoch 88/100, Loss: 3.2481679171323776
Epoch 89/100, Loss: 3.4463014900684357
Epoch 90/100, Loss: 3.4833346903324127
Epoch 91/100, Loss: 3.398556485772133

Epoch 92/100, Loss: 3.4578238427639008
Epoch 93/100, Loss: 3.2031581327319145
Epoch 94/100, Loss: 3.4279918372631073
Epoch 95/100, Loss: 3.139336794614792
Epoch 96/100, Loss: 2.989496625959873
Epoch 97/100, Loss: 3.280404195189476
Epoch 98/100, Loss: 3.169561043381691
Epoch 99/100, Loss: 3.4696973264217377
Epoch 100/100, Loss: 3.0039104372262955
Fold 2/5 done
Epoch 1/100, Loss: 3.070072829723358
Epoch 2/100, Loss: 3.0672630220651627
Epoch 3/100, Loss: 2.756578713655472
Epoch 4/100, Loss: 3.1602980494499207
Epoch 5/100, Loss: 3.146673373878002

Epoch 6/100, Loss: 2.736085630953312
Epoch 7/100, Loss: 2.8961420580744743
Epoch 8/100, Loss: 2.850047543644905
Epoch 9/100, Loss: 3.104624830186367
Epoch 10/100, Loss: 2.945460245013237
Epoch 11/100, Loss: 2.985646039247513
Epoch 12/100, Loss: 2.692217119038105
Epoch 13/100, Loss: 3.2806871607899666
Epoch 14/100, Loss: 3.67171011865139
Epoch 15/100, Loss: 3.0670982748270035
Epoch 16/100, Loss: 2.8664742708206177
Epoch 17/100, Loss: 3.0070854648947716
Epoch 18/100, Loss: 2.9621402323246
Epoch 19/100, Loss: 2.959549732506275
Epoch 20/100, Loss: 2.9690172746777534
Epoch 21/100, Loss: 3.07805135846138
Epoch 22/100, Loss: 2.9955347403883934

Epoch 23/100, Loss: 2.941026084125042
Epoch 24/100, Loss: 2.9607504084706306
Epoch 25/100, Loss: 2.997410699725151
Epoch 26/100, Loss: 2.9518133997917175
Epoch 27/100, Loss: 3.009977273643017
Epoch 28/100, Loss: 3.1528159603476524
Epoch 29/100, Loss: 3.106072425842285
Epoch 30/100, Loss: 2.957863502204418
Epoch 31/100, Loss: 2.9688451439142227
Epoch 32/100, Loss: 3.0404022186994553
Epoch 33/100, Loss: 3.3315312936902046
Epoch 34/100, Loss: 3.117525652050972
Epoch 35/100, Loss: 2.9884693697094917
Epoch 36/100, Loss: 3.0406612381339073
Epoch 37/100, Loss: 2.93423131108284
Epoch 38/100, Loss: 2.976874276995659
Epoch 39/100, Loss: 3.2286965921521187

Epoch 40/100, Loss: 2.957128755748272
Epoch 41/100, Loss: 3.033748187124729
Epoch 42/100, Loss: 2.6562188640236855
Epoch 43/100, Loss: 3.0030944272875786
Epoch 44/100, Loss: 3.6205146312713623
Epoch 45/100, Loss: 2.9677487313747406
Epoch 46/100, Loss: 2.8842418119311333
Epoch 47/100, Loss: 2.452327497303486
Epoch 48/100, Loss: 3.001460626721382
Epoch 49/100, Loss: 2.828684501349926
Epoch 50/100, Loss: 2.9370134472846985
Epoch 51/100, Loss: 2.9660671576857567
Epoch 52/100, Loss: 3.1667868196964264
Epoch 53/100, Loss: 2.7630435824394226
Epoch 54/100, Loss: 3.23723591119051
Epoch 55/100, Loss: 2.9767543375492096
Epoch 56/100, Loss: 2.7553842589259148

Epoch 57/100, Loss: 2.900642655789852
Epoch 58/100, Loss: 3.017090491950512
Epoch 59/100, Loss: 3.1078107431530952
Epoch 60/100, Loss: 3.1535703986883163
Epoch 61/100, Loss: 2.9726457223296165
Epoch 62/100, Loss: 2.931245766580105
Epoch 63/100, Loss: 2.855976916849613
Epoch 64/100, Loss: 2.8703786358237267
Epoch 65/100, Loss: 2.648353323340416
Epoch 66/100, Loss: 2.9218353256583214
Epoch 67/100, Loss: 2.843952253460884
Epoch 68/100, Loss: 3.0772355645895004
Epoch 69/100, Loss: 2.965509571135044
Epoch 70/100, Loss: 2.73571764677763
Epoch 71/100, Loss: 3.124516263604164
Epoch 72/100, Loss: 2.7708850130438805
Epoch 73/100, Loss: 2.986378960311413

Epoch 74/100, Loss: 3.578112870454788
Epoch 75/100, Loss: 3.9375984147191048
Epoch 76/100, Loss: 2.922275960445404
Epoch 77/100, Loss: 3.020557425916195
Epoch 78/100, Loss: 3.153107427060604
Epoch 79/100, Loss: 3.036152496933937
Epoch 80/100, Loss: 2.936376340687275
Epoch 81/100, Loss: 3.1618825793266296
Epoch 82/100, Loss: 3.0764647498726845
Epoch 83/100, Loss: 2.918941542506218
Epoch 84/100, Loss: 3.0758273899555206
Epoch 85/100, Loss: 2.9370332211256027
Epoch 86/100, Loss: 2.9343827217817307

Epoch 87/100, Loss: 3.0388490334153175
Epoch 88/100, Loss: 3.1848597824573517
Epoch 89/100, Loss: 3.106731191277504
Epoch 90/100, Loss: 3.0375183895230293
Epoch 91/100, Loss: 2.807103879749775
Epoch 92/100, Loss: 3.034530222415924
Epoch 93/100, Loss: 2.7958256378769875
Epoch 94/100, Loss: 3.0326701924204826
Epoch 95/100, Loss: 2.622039169073105
Epoch 96/100, Loss: 3.0827856734395027
Epoch 97/100, Loss: 3.133515901863575
Epoch 98/100, Loss: 3.591306820511818
Epoch 99/100, Loss: 3.0195596367120743
Epoch 100/100, Loss: 3.1821909844875336
Fold 3/5 done
Epoch 1/100, Loss: 1.3391770161688328

Epoch 2/100, Loss: 1.3248822093009949
Epoch 3/100, Loss: 1.2680459804832935
Epoch 4/100, Loss: 1.2975014448165894
Epoch 5/100, Loss: 1.4150448590517044
Epoch 6/100, Loss: 1.3248034864664078
Epoch 7/100, Loss: 1.2753804177045822
Epoch 8/100, Loss: 1.362334169447422
Epoch 9/100, Loss: 1.345911219716072
Epoch 10/100, Loss: 1.4007564187049866
Epoch 11/100, Loss: 1.3413419127464294
Epoch 12/100, Loss: 1.3216281905770302
Epoch 13/100, Loss: 1.3381379470229149
Epoch 14/100, Loss: 1.3056113496422768

Epoch 15/100, Loss: 1.3398185148835182
Epoch 16/100, Loss: 1.2811229676008224
Epoch 17/100, Loss: 1.2590589299798012
Epoch 18/100, Loss: 1.3444303460419178
Epoch 19/100, Loss: 1.331236943602562
Epoch 20/100, Loss: 1.231738917529583
Epoch 21/100, Loss: 1.2864945977926254
Epoch 22/100, Loss: 1.3369472101330757
Epoch 23/100, Loss: 1.3569069504737854
Epoch 24/100, Loss: 1.320641614496708
Epoch 25/100, Loss: 1.3196199238300323
Epoch 26/100, Loss: 1.3125456720590591
Epoch 27/100, Loss: 1.2697906084358692

Epoch 28/100, Loss: 1.3155727609992027
Epoch 29/100, Loss: 1.3482709787786007
Epoch 30/100, Loss: 1.341906562447548
Epoch 31/100, Loss: 1.354684866964817
Epoch 32/100, Loss: 1.3402961418032646
Epoch 33/100, Loss: 1.4891339838504791
Epoch 34/100, Loss: 1.3735223039984703
Epoch 35/100, Loss: 1.3350718095898628
Epoch 36/100, Loss: 1.3598000556230545
Epoch 37/100, Loss: 1.3301788792014122

Epoch 38/100, Loss: 1.3158577233552933
Epoch 39/100, Loss: 1.312630370259285
Epoch 40/100, Loss: 1.2818568646907806
Epoch 41/100, Loss: 1.3007993437349796
Epoch 42/100, Loss: 1.4236953593790531
Epoch 43/100, Loss: 1.2860313951969147
Epoch 44/100, Loss: 1.3077766448259354
Epoch 45/100, Loss: 1.367749162018299
Epoch 46/100, Loss: 1.4453511983156204
Epoch 47/100, Loss: 1.2905581593513489
Epoch 48/100, Loss: 1.2216132879257202

Epoch 49/100, Loss: 1.2804770916700363
Epoch 50/100, Loss: 1.3029284626245499
Epoch 51/100, Loss: 1.3271048218011856
Epoch 52/100, Loss: 1.362653061747551
Epoch 53/100, Loss: 1.3758874982595444
Epoch 54/100, Loss: 1.34804467856884
Epoch 55/100, Loss: 1.2863697782158852
Epoch 56/100, Loss: 1.339695319533348
Epoch 57/100, Loss: 1.3219341710209846
Epoch 58/100, Loss: 1.2610736936330795
Epoch 59/100, Loss: 1.3537916839122772

Epoch 60/100, Loss: 1.3123242482542992
Epoch 61/100, Loss: 1.4703480824828148
Epoch 62/100, Loss: 1.3432903811335564
Epoch 63/100, Loss: 1.3332330659031868
Epoch 64/100, Loss: 1.252835676074028
Epoch 65/100, Loss: 1.3893869742751122
Epoch 66/100, Loss: 1.2916394621133804
Epoch 67/100, Loss: 1.3186259716749191
Epoch 68/100, Loss: 1.3471738696098328
Epoch 69/100, Loss: 1.287770889699459
Epoch 70/100, Loss: 1.2840066850185394
Epoch 71/100, Loss: 1.2315973341464996
Epoch 72/100, Loss: 1.3172605782747269
Epoch 73/100, Loss: 1.2765430808067322
Epoch 74/100, Loss: 1.1967253610491753
Epoch 75/100, Loss: 1.3244583904743195
Epoch 76/100, Loss: 1.3423348926007748

Epoch 77/100, Loss: 1.2962184324860573
Epoch 78/100, Loss: 1.3347873240709305
Epoch 79/100, Loss: 1.3046184480190277
Epoch 80/100, Loss: 1.3030510544776917
Epoch 81/100, Loss: 1.2731431499123573
Epoch 82/100, Loss: 1.2442705929279327
Epoch 83/100, Loss: 1.257060393691063
Epoch 84/100, Loss: 1.3216436356306076
Epoch 85/100, Loss: 1.2944626957178116
Epoch 86/100, Loss: 1.2572830319404602
Epoch 87/100, Loss: 1.2719503492116928
Epoch 88/100, Loss: 1.439353957772255
Epoch 89/100, Loss: 1.356065809726715
Epoch 90/100, Loss: 1.3636540994048119
Epoch 91/100, Loss: 1.2880155853927135
Epoch 92/100, Loss: 1.4365859515964985
Epoch 93/100, Loss: 1.3193823173642159
Epoch 94/100, Loss: 1.3335807248950005

Epoch 95/100, Loss: 1.415894754230976
Epoch 96/100, Loss: 1.2353225275874138
Epoch 97/100, Loss: 1.3361794725060463
Epoch 98/100, Loss: 1.3013959899544716
Epoch 99/100, Loss: 1.2376052290201187
Epoch 100/100, Loss: 1.3306665308773518
Fold 4/5 done
Epoch 1/100, Loss: 3.055035799741745
Epoch 2/100, Loss: 3.051982916891575
Epoch 3/100, Loss: 3.0148974284529686
Epoch 4/100, Loss: 3.095549590885639
Epoch 5/100, Loss: 2.9621525555849075
Epoch 6/100, Loss: 3.1567882671952248
Epoch 7/100, Loss: 3.2435514330863953
Epoch 8/100, Loss: 3.037319555878639
Epoch 9/100, Loss: 3.162377744913101
Epoch 10/100, Loss: 2.9434681981801987
Epoch 11/100, Loss: 3.1211534664034843

Epoch 12/100, Loss: 3.1899686455726624
Epoch 13/100, Loss: 3.2994094863533974
Epoch 14/100, Loss: 3.021749347448349
Epoch 15/100, Loss: 3.013542316854
Epoch 16/100, Loss: 3.198282830417156
Epoch 17/100, Loss: 3.0943378061056137
Epoch 18/100, Loss: 3.306327745318413
Epoch 19/100, Loss: 3.0212747007608414
Epoch 20/100, Loss: 3.0985694527626038
Epoch 21/100, Loss: 2.950143873691559
Epoch 22/100, Loss: 3.2684327960014343
Epoch 23/100, Loss: 3.12808321416378
Epoch 24/100, Loss: 3.0174945816397667
Epoch 25/100, Loss: 2.9465440958738327
Epoch 26/100, Loss: 3.095221258699894
Epoch 27/100, Loss: 3.220550552010536
Epoch 28/100, Loss: 3.225690573453903
Epoch 29/100, Loss: 3.01111800968647

Epoch 30/100, Loss: 2.9856832176446915
Epoch 31/100, Loss: 3.091893121600151
Epoch 32/100, Loss: 3.054154135286808
Epoch 33/100, Loss: 3.014682114124298
Epoch 34/100, Loss: 3.1413410753011703
Epoch 35/100, Loss: 3.233639135956764
Epoch 36/100, Loss: 3.135672688484192
Epoch 37/100, Loss: 3.016893371939659
Epoch 38/100, Loss: 3.0361188799142838
Epoch 39/100, Loss: 3.100283995270729
Epoch 40/100, Loss: 3.158794641494751
Epoch 41/100, Loss: 3.044174924492836
Epoch 42/100, Loss: 3.1397349685430527
Epoch 43/100, Loss: 3.0048436000943184
Epoch 44/100, Loss: 2.9736141115427017
Epoch 45/100, Loss: 3.0367296636104584
Epoch 46/100, Loss: 3.040349170565605
Epoch 47/100, Loss: 3.200237289071083
Epoch 48/100, Loss: 3.158343121409416

Epoch 49/100, Loss: 3.1417464315891266
Epoch 50/100, Loss: 3.1333883181214333
Epoch 51/100, Loss: 3.0409176126122475
Epoch 52/100, Loss: 3.157706595957279
Epoch 53/100, Loss: 3.064804494380951
Epoch 54/100, Loss: 3.1635373681783676
Epoch 55/100, Loss: 3.2336739897727966
Epoch 56/100, Loss: 3.031351923942566
Epoch 57/100, Loss: 2.9957756623625755
Epoch 58/100, Loss: 3.141853243112564
Epoch 59/100, Loss: 3.0311252400279045
Epoch 60/100, Loss: 3.085537478327751
Epoch 61/100, Loss: 3.1011264994740486
Epoch 62/100, Loss: 2.923849791288376
Epoch 63/100, Loss: 2.9246416464447975
Epoch 64/100, Loss: 2.9919104874134064
Epoch 65/100, Loss: 2.98945552110672
Epoch 66/100, Loss: 3.136084273457527

Epoch 67/100, Loss: 2.9902343824505806
Epoch 68/100, Loss: 3.113886520266533
Epoch 69/100, Loss: 3.0051100850105286
Epoch 70/100, Loss: 2.927602842450142
Epoch 71/100, Loss: 3.0932881236076355
Epoch 72/100, Loss: 3.004216253757477
Epoch 73/100, Loss: 3.057995945215225
Epoch 74/100, Loss: 2.9932969510555267
Epoch 75/100, Loss: 3.100516200065613
Epoch 76/100, Loss: 3.0616241842508316
Epoch 77/100, Loss: 3.14070875197649
Epoch 78/100, Loss: 3.2086053490638733
Epoch 79/100, Loss: 3.0232267007231712
Epoch 80/100, Loss: 3.173859938979149
Epoch 81/100, Loss: 3.111284926533699
Epoch 82/100, Loss: 3.0898988470435143
Epoch 83/100, Loss: 3.1475241407752037

Epoch 84/100, Loss: 3.089424565434456
Epoch 85/100, Loss: 3.0281419903039932
Epoch 86/100, Loss: 3.1115743443369865
Epoch 87/100, Loss: 3.219314455986023
Epoch 88/100, Loss: 3.123009294271469
Epoch 89/100, Loss: 3.032406009733677
Epoch 90/100, Loss: 3.1806648075580597
Epoch 91/100, Loss: 3.0112043619155884
Epoch 92/100, Loss: 3.0510179698467255
Epoch 93/100, Loss: 3.1856153681874275
Epoch 94/100, Loss: 3.144874319434166
Epoch 95/100, Loss: 3.1256134063005447
Epoch 96/100, Loss: 2.9086572229862213
Epoch 97/100, Loss: 3.0703356117010117
Epoch 98/100, Loss: 3.009650945663452
Epoch 99/100, Loss: 3.1697809398174286
Epoch 100/100, Loss: 3.1314705163240433
Fold 5/5 done

In [11]:
ap = average_precision_score(y_true, anomaly_scores)
print(f"Deep SVDD AP (5-fold CV) = {ap:.4f}")
sb.glue("GBG500_ap_spectral_deep_svdd", float(ap))

Deep SVDD AP (5-fold CV) = 0.4986