In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import average_precision_score
from sklearn.model_selection import StratifiedKFold
from pyod.models.deep_svdd import DeepSVDD
import sys
import scrapbook as sb

sys.path.append('..')
from utils import reshape_to_numpy, interpolate_missing_values, denoise_data, compute_spectrograms, time_avg_pooling

In [2]:
seed = 1
sampling_rate = 10
nperseg=64
noverlap=32
accel_cutoff = 0.4
accel_order = 30
gyro_cutoff = 0.6
gyro_order = 20
batch_size = 32
epochs = 100
hidden_neurons = [128, 64, 32]
n_splits = 5

In [3]:
# Parameters
seed = 25

In [4]:
rng = np.random.RandomState(seed)

In [5]:
data = pd.read_parquet("../data/GBG500.parquet")
data

,ride_id,time_index,ax,ay,az,rx,ry,rz
0,005043f1a7520cebf1e17fd166a00a3190e2433530f236...,0,-2.512796,-9.385012,-1.053078,-0.009155,0.009155,-0.201416
1,005043f1a7520cebf1e17fd166a00a3190e2433530f236...,100,-2.491268,-9.385012,-1.079390,-0.036621,0.027465,-0.155639
2,005043f1a7520cebf1e17fd166a00a3190e2433530f236...,200,-2.534324,-9.382022,-1.030952,0.036621,0.027465,-0.073242
3,005043f1a7520cebf1e17fd166a00a3190e2433530f236...,300,-2.488278,-9.383218,-1.091948,-0.045776,0.036621,-0.183105
4,005043f1a7520cebf1e17fd166a00a3190e2433530f236...,400,-2.483494,-9.382022,-1.100320,-0.045776,0.027465,-0.192260
...,...,...,...,...,...,...,...,...
1529542,ffb6f2f5dc6ba768d88dc0bc1af4cad235526aa9e24168...,241300,0.459862,-9.140430,-3.318900,1.556396,-0.091552,0.274658
1529543,ffb6f2f5dc6ba768d88dc0bc1af4cad235526aa9e24168...,241400,0.455676,-9.140430,-3.321292,1.583861,-0.119018,0.274658
1529544,ffb6f2f5dc6ba768d88dc0bc1af4cad235526aa9e24168...,241500,0.459862,-9.139832,-3.317704,1.583861,-0.109863,0.274658
1529545,ffb6f2f5dc6ba768d88dc0bc1af4cad235526aa9e24168...,241600,0.456274,-9.142224,-3.321292,1.574707,-0.137329,0.283813
1529546,ffb6f2f5dc6ba768d88dc0bc1af4cad235526aa9e24168...,241700,0.458666,-9.139832,-3.320694,1.574707,-0.137329,0.274658

In [6]:
labels = pd.read_csv("../data/GBG500_labels.csv")
labels.columns = labels.columns.str.lower()
ride_order_df = pd.DataFrame({"ride_id": data["ride_id"].unique()})
labels_sorted = ride_order_df.merge(
    labels,
    on="ride_id",
    how="left"
)
labels_sorted

                                               ride_id        label
0    005043f1a7520cebf1e17fd166a00a3190e2433530f236...         Safe
1    00d223cb7aecc9c0cc5871e32a6c45027a068eba07c572...     Reckless
2    02288a4aeca044203394e982e76b87818021dea2b34df9...         Safe
3    0236bdcf13d473ea24d97f5eaeea459f257dffac005694...  Bad weather
4    0238e5dd85143f1b6c59b200bc32f14361b8fc84c51a87...         Safe
..                                                 ...          ...
495  fe5d7f84d692bbccad8bd566a3ad5c3108fa9f90acd671...         Safe
496  fe67169632306d4668b2affedef510df2cb43e2fb41220...         Safe
497  fee44667fdc8ab4995c702fc3bd36178de0b1ca2c64687...         Safe
498  ff79b2e945b93c2a5efc3a06365267b3a160e7849ba57d...         Safe
499  ffb6f2f5dc6ba768d88dc0bc1af4cad235526aa9e24168...         Safe

[500 rows x 2 columns]

In [7]:
data_np = reshape_to_numpy(
    data,
    features = ["ax", "ay", "az", "rx", "ry", "rz"],
    max_timestamps = 4800
)

data_np_clean = interpolate_missing_values(
    data_np,
    method='linear',
    limit=None
)

data_np_clean = denoise_data(
    data=data_np_clean,
    accel_indices=[0, 1, 2],
    gyro_indices=[3, 4, 5],
    accel_cutoff=accel_cutoff,
    accel_order=accel_order,
    gyro_cutoff=gyro_cutoff,
    gyro_order=gyro_order,
)

In [8]:
# Compute spectrograms for all rides
spectrograms_array = compute_spectrograms(data_np_clean, sampling_rate, nperseg, noverlap)
spectrograms_array.shape

(500, 149, 6, 33)

In [9]:
# Aggregate spectrograms using time-averaged pooling
X_feat = time_avg_pooling(spectrograms_array)
X_feat.shape

(500, 198)

In [10]:
# 5-fold stratified CV with Deep SVDD
skf = StratifiedKFold(n_splits=n_splits, shuffle=True, random_state=rng.randint(1000))
y_true = (labels_sorted['label'] == 'Reckless').astype(int).values
anomaly_scores = np.full(len(y_true), np.nan)

for fold, (train_idx, test_idx) in enumerate(skf.split(X_feat, y_true)):
    sc = StandardScaler()
    X_train = sc.fit_transform(X_feat[train_idx])
    X_test = sc.transform(X_feat[test_idx])

    np.random.seed(rng.randint(1000))
    model = DeepSVDD(
        n_features=X_train.shape[1],
        hidden_neurons=hidden_neurons,
        epochs=epochs,
        batch_size=batch_size,
        random_state=rng.randint(1000),
    )
    model.fit(X_train)
    anomaly_scores[test_idx] = model.decision_function(X_test)
    print(f"Fold {fold+1}/{n_splits} done")

Epoch 1/100, Loss: 1.367602925747633
Epoch 2/100, Loss: 1.2885583154857159
Epoch 3/100, Loss: 1.377865243703127
Epoch 4/100, Loss: 1.311681054532528
Epoch 5/100, Loss: 1.3777991272509098
Epoch 6/100, Loss: 1.309329330921173
Epoch 7/100, Loss: 1.422533992677927
Epoch 8/100, Loss: 1.3402817845344543
Epoch 9/100, Loss: 1.33986447006464
Epoch 10/100, Loss: 1.433325245976448
Epoch 11/100, Loss: 1.3501390740275383
Epoch 12/100, Loss: 1.3180335722863674
Epoch 13/100, Loss: 1.3431347236037254
Epoch 14/100, Loss: 1.4492721036076546
Epoch 15/100, Loss: 1.3575992435216904

Epoch 16/100, Loss: 1.4017279222607613
Epoch 17/100, Loss: 1.4256810694932938
Epoch 18/100, Loss: 1.2631438560783863
Epoch 19/100, Loss: 1.5494520030915737
Epoch 20/100, Loss: 1.2646828815340996
Epoch 21/100, Loss: 1.397046908736229
Epoch 22/100, Loss: 1.4555854760110378
Epoch 23/100, Loss: 1.3111934401094913
Epoch 24/100, Loss: 1.3471871726214886
Epoch 25/100, Loss: 1.333457324653864
Epoch 26/100, Loss: 1.66649279743433
Epoch 27/100, Loss: 1.368477936834097
Epoch 28/100, Loss: 1.4536998346447945
Epoch 29/100, Loss: 1.4392304867506027
Epoch 30/100, Loss: 1.521172922104597

Epoch 31/100, Loss: 1.3879291117191315
Epoch 32/100, Loss: 1.2425982765853405
Epoch 33/100, Loss: 1.3890261799097061
Epoch 34/100, Loss: 1.4316660948097706
Epoch 35/100, Loss: 1.403300128877163
Epoch 36/100, Loss: 1.3394816033542156
Epoch 37/100, Loss: 1.3855503611266613
Epoch 38/100, Loss: 1.366177886724472
Epoch 39/100, Loss: 1.4672570265829563
Epoch 40/100, Loss: 1.306336011737585
Epoch 41/100, Loss: 1.355732899159193
Epoch 42/100, Loss: 1.4731609672307968
Epoch 43/100, Loss: 1.4046719260513783
Epoch 44/100, Loss: 1.3692686781287193
Epoch 45/100, Loss: 1.4137968011200428

Epoch 46/100, Loss: 1.3839510455727577
Epoch 47/100, Loss: 1.4672730825841427
Epoch 48/100, Loss: 1.335895575582981
Epoch 49/100, Loss: 1.2664295583963394
Epoch 50/100, Loss: 1.4403954446315765
Epoch 51/100, Loss: 1.303394541144371
Epoch 52/100, Loss: 1.2466616779565811
Epoch 53/100, Loss: 1.3344763405621052
Epoch 54/100, Loss: 1.35344710201025
Epoch 55/100, Loss: 1.6978360824286938
Epoch 56/100, Loss: 1.3640297651290894
Epoch 57/100, Loss: 1.3262880332767963
Epoch 58/100, Loss: 1.6779332049190998
Epoch 59/100, Loss: 1.2930389568209648
Epoch 60/100, Loss: 1.347729541361332

Epoch 61/100, Loss: 1.3659018501639366
Epoch 62/100, Loss: 1.394734624773264
Epoch 63/100, Loss: 1.340853314846754
Epoch 64/100, Loss: 1.346323885023594
Epoch 65/100, Loss: 1.3249513618648052
Epoch 66/100, Loss: 1.437639456242323
Epoch 67/100, Loss: 1.1850440837442875
Epoch 68/100, Loss: 1.3097799383103848
Epoch 69/100, Loss: 1.3094795569777489
Epoch 70/100, Loss: 1.6463765650987625
Epoch 71/100, Loss: 1.3481537401676178
Epoch 72/100, Loss: 1.3559296019375324
Epoch 73/100, Loss: 1.354762002825737

Epoch 74/100, Loss: 1.3682381100952625
Epoch 75/100, Loss: 1.6735365353524685
Epoch 76/100, Loss: 1.3171623907983303
Epoch 77/100, Loss: 1.4317634478211403
Epoch 78/100, Loss: 1.376044262200594
Epoch 79/100, Loss: 1.2974594309926033
Epoch 80/100, Loss: 1.318356204777956
Epoch 81/100, Loss: 1.4312847517430782
Epoch 82/100, Loss: 1.3255506940186024
Epoch 83/100, Loss: 1.4241169542074203
Epoch 84/100, Loss: 1.4306964874267578
Epoch 85/100, Loss: 1.361010167747736
Epoch 86/100, Loss: 1.4106461554765701
Epoch 87/100, Loss: 1.3918852396309376
Epoch 88/100, Loss: 1.4928497783839703
Epoch 89/100, Loss: 1.4231631197035313
Epoch 90/100, Loss: 1.285297866910696

Epoch 91/100, Loss: 1.3288185223937035
Epoch 92/100, Loss: 1.472899578511715
Epoch 93/100, Loss: 1.4314877167344093
Epoch 94/100, Loss: 1.332714058458805
Epoch 95/100, Loss: 1.4868472032248974
Epoch 96/100, Loss: 1.2502996325492859
Epoch 97/100, Loss: 1.3515805080533028
Epoch 98/100, Loss: 1.4766261503100395
Epoch 99/100, Loss: 1.3358626402914524
Epoch 100/100, Loss: 1.2650860622525215
Fold 1/5 done
Epoch 1/100, Loss: 1.8770526051521301
Epoch 2/100, Loss: 1.818405032157898
Epoch 3/100, Loss: 1.747405007481575
Epoch 4/100, Loss: 1.9176559373736382
Epoch 5/100, Loss: 1.9728276580572128
Epoch 6/100, Loss: 1.8766645677387714

Epoch 7/100, Loss: 1.6786158084869385
Epoch 8/100, Loss: 1.773394152522087
Epoch 9/100, Loss: 1.8529515862464905
Epoch 10/100, Loss: 1.8461058288812637
Epoch 11/100, Loss: 1.9016988053917885
Epoch 12/100, Loss: 2.026228651404381
Epoch 13/100, Loss: 1.7312806472182274
Epoch 14/100, Loss: 1.861666202545166
Epoch 15/100, Loss: 1.8932340368628502
Epoch 16/100, Loss: 1.6938342452049255
Epoch 17/100, Loss: 1.8838870376348495
Epoch 18/100, Loss: 1.642728865146637
Epoch 19/100, Loss: 1.6835167482495308
Epoch 20/100, Loss: 1.8664082512259483
Epoch 21/100, Loss: 1.84420745074749
Epoch 22/100, Loss: 1.7292805835604668
Epoch 23/100, Loss: 2.366903454065323

Epoch 24/100, Loss: 1.9812722280621529
Epoch 25/100, Loss: 1.8641288988292217
Epoch 26/100, Loss: 2.1703021824359894
Epoch 27/100, Loss: 1.8612816482782364
Epoch 28/100, Loss: 1.9314834102988243
Epoch 29/100, Loss: 1.7770908325910568
Epoch 30/100, Loss: 1.8906942456960678
Epoch 31/100, Loss: 2.0167066901922226
Epoch 32/100, Loss: 1.8215243369340897
Epoch 33/100, Loss: 1.7933816984295845
Epoch 34/100, Loss: 1.9904882535338402
Epoch 35/100, Loss: 1.5441253930330276
Epoch 36/100, Loss: 1.909182958304882
Epoch 37/100, Loss: 1.893813244998455
Epoch 38/100, Loss: 1.7910209521651268
Epoch 39/100, Loss: 1.8987158238887787
Epoch 40/100, Loss: 1.8412258252501488

Epoch 41/100, Loss: 1.9750288501381874
Epoch 42/100, Loss: 1.726706638932228
Epoch 43/100, Loss: 1.794142670929432
Epoch 44/100, Loss: 1.835778847336769
Epoch 45/100, Loss: 1.756141610443592
Epoch 46/100, Loss: 1.835306465625763
Epoch 47/100, Loss: 1.7613326907157898
Epoch 48/100, Loss: 1.7190628498792648
Epoch 49/100, Loss: 1.7389747276902199
Epoch 50/100, Loss: 1.821863241493702
Epoch 51/100, Loss: 1.8907247558236122
Epoch 52/100, Loss: 1.9255006238818169
Epoch 53/100, Loss: 1.8358006700873375
Epoch 54/100, Loss: 1.8773948773741722
Epoch 55/100, Loss: 1.8931162357330322
Epoch 56/100, Loss: 2.008862853050232
Epoch 57/100, Loss: 1.968153916299343
Epoch 58/100, Loss: 1.7408459037542343

Epoch 59/100, Loss: 1.8338877260684967
Epoch 60/100, Loss: 1.7092605382204056
Epoch 61/100, Loss: 1.8512842953205109
Epoch 62/100, Loss: 1.8032630234956741
Epoch 63/100, Loss: 1.8255633041262627
Epoch 64/100, Loss: 1.837546557188034
Epoch 65/100, Loss: 1.871037494391203
Epoch 66/100, Loss: 1.8825292736291885
Epoch 67/100, Loss: 1.825103022158146
Epoch 68/100, Loss: 1.7734020873904228
Epoch 69/100, Loss: 1.7580126523971558
Epoch 70/100, Loss: 1.8181550055742264
Epoch 71/100, Loss: 1.9275232031941414
Epoch 72/100, Loss: 1.7956345677375793
Epoch 73/100, Loss: 1.7949657142162323
Epoch 74/100, Loss: 1.8655574396252632
Epoch 75/100, Loss: 2.245575338602066

Epoch 76/100, Loss: 2.0127269327640533
Epoch 77/100, Loss: 1.9923981353640556
Epoch 78/100, Loss: 1.9353346526622772
Epoch 79/100, Loss: 1.8865491077303886
Epoch 80/100, Loss: 1.8771445825695992
Epoch 81/100, Loss: 1.8398627787828445
Epoch 82/100, Loss: 1.8146292567253113
Epoch 83/100, Loss: 1.78165652602911
Epoch 84/100, Loss: 1.8600133582949638
Epoch 85/100, Loss: 1.7938893511891365
Epoch 86/100, Loss: 1.7647325173020363
Epoch 87/100, Loss: 2.010975755751133
Epoch 88/100, Loss: 1.9447690322995186
Epoch 89/100, Loss: 1.7619984969496727
Epoch 90/100, Loss: 1.7711009681224823
Epoch 91/100, Loss: 1.8754434883594513
Epoch 92/100, Loss: 1.8794181048870087
Epoch 93/100, Loss: 1.8072358965873718

Epoch 94/100, Loss: 1.775563545525074
Epoch 95/100, Loss: 1.953704223036766
Epoch 96/100, Loss: 1.7807095497846603
Epoch 97/100, Loss: 1.9126780480146408
Epoch 98/100, Loss: 1.8391252718865871
Epoch 99/100, Loss: 1.9428159967064857
Epoch 100/100, Loss: 1.8476977348327637
Fold 2/5 done
Epoch 1/100, Loss: 3.022460587322712
Epoch 2/100, Loss: 2.9545301496982574
Epoch 3/100, Loss: 3.0895232036709785
Epoch 4/100, Loss: 2.9596832543611526
Epoch 5/100, Loss: 3.043651983141899
Epoch 6/100, Loss: 2.733995832502842
Epoch 7/100, Loss: 2.8346951603889465
Epoch 8/100, Loss: 2.9588661938905716
Epoch 9/100, Loss: 2.896887421607971
Epoch 10/100, Loss: 2.973161667585373

Epoch 11/100, Loss: 3.256259962916374
Epoch 12/100, Loss: 3.1070714443922043
Epoch 13/100, Loss: 3.1476907059550285
Epoch 14/100, Loss: 2.8511579781770706
Epoch 15/100, Loss: 2.930431254208088
Epoch 16/100, Loss: 2.83047304302454
Epoch 17/100, Loss: 3.0051204562187195
Epoch 18/100, Loss: 3.066307730972767
Epoch 19/100, Loss: 2.8152374029159546
Epoch 20/100, Loss: 2.770832486450672
Epoch 21/100, Loss: 3.0212342441082
Epoch 22/100, Loss: 2.9886231794953346
Epoch 23/100, Loss: 3.017166331410408
Epoch 24/100, Loss: 3.10425728559494
Epoch 25/100, Loss: 2.8533874452114105
Epoch 26/100, Loss: 2.8123630061745644
Epoch 27/100, Loss: 2.8788740038871765
Epoch 28/100, Loss: 2.938494995236397

Epoch 29/100, Loss: 2.861102595925331
Epoch 30/100, Loss: 2.93790902197361
Epoch 31/100, Loss: 2.968332663178444
Epoch 32/100, Loss: 3.2491649389266968
Epoch 33/100, Loss: 2.944335177540779
Epoch 34/100, Loss: 2.8797523230314255
Epoch 35/100, Loss: 2.853797025978565
Epoch 36/100, Loss: 3.0862024649977684
Epoch 37/100, Loss: 2.9185813069343567
Epoch 38/100, Loss: 3.034626752138138
Epoch 39/100, Loss: 3.006442569196224
Epoch 40/100, Loss: 2.9189368411898613
Epoch 41/100, Loss: 3.054031655192375
Epoch 42/100, Loss: 2.9573569893836975
Epoch 43/100, Loss: 2.9999099522829056
Epoch 44/100, Loss: 2.9940886348485947
Epoch 45/100, Loss: 3.0680676326155663

Epoch 46/100, Loss: 2.949480354785919
Epoch 47/100, Loss: 2.946275867521763
Epoch 48/100, Loss: 2.940128408372402
Epoch 49/100, Loss: 3.002280041575432
Epoch 50/100, Loss: 3.0638294965028763
Epoch 51/100, Loss: 2.904864862561226
Epoch 52/100, Loss: 3.1399420127272606
Epoch 53/100, Loss: 2.955591894686222
Epoch 54/100, Loss: 3.0825051441788673
Epoch 55/100, Loss: 2.8994160592556
Epoch 56/100, Loss: 2.9742941111326218
Epoch 57/100, Loss: 2.9150477051734924
Epoch 58/100, Loss: 3.011375054717064
Epoch 59/100, Loss: 3.0114554092288017
Epoch 60/100, Loss: 2.8621383905410767
Epoch 61/100, Loss: 3.099946141242981

Epoch 62/100, Loss: 3.10843039304018
Epoch 63/100, Loss: 2.8490812480449677
Epoch 64/100, Loss: 3.0681905150413513
Epoch 65/100, Loss: 2.925763316452503
Epoch 66/100, Loss: 3.06064735352993
Epoch 67/100, Loss: 2.807922288775444
Epoch 68/100, Loss: 2.898488000035286
Epoch 69/100, Loss: 3.01232086122036
Epoch 70/100, Loss: 2.9319639205932617
Epoch 71/100, Loss: 3.1346859261393547
Epoch 72/100, Loss: 2.8439383283257484
Epoch 73/100, Loss: 2.9674425050616264
Epoch 74/100, Loss: 2.963647447526455
Epoch 75/100, Loss: 2.8159203976392746
Epoch 76/100, Loss: 2.9470455646514893

Epoch 77/100, Loss: 3.0969401001930237
Epoch 78/100, Loss: 3.012546956539154
Epoch 79/100, Loss: 2.8043437376618385
Epoch 80/100, Loss: 2.8059103563427925
Epoch 81/100, Loss: 2.899532914161682
Epoch 82/100, Loss: 3.0396305173635483
Epoch 83/100, Loss: 2.9426289945840836
Epoch 84/100, Loss: 3.1740930378437042
Epoch 85/100, Loss: 3.1157358288764954
Epoch 86/100, Loss: 2.9422896951436996
Epoch 87/100, Loss: 2.926060102880001
Epoch 88/100, Loss: 3.346456453204155
Epoch 89/100, Loss: 2.859814874827862
Epoch 90/100, Loss: 3.045832082629204
Epoch 91/100, Loss: 2.9558907598257065
Epoch 92/100, Loss: 2.9021383449435234
Epoch 93/100, Loss: 2.9838147461414337
Epoch 94/100, Loss: 3.0653268545866013

Epoch 95/100, Loss: 2.9986327439546585
Epoch 96/100, Loss: 2.939781092107296
Epoch 97/100, Loss: 2.8620160445570946
Epoch 98/100, Loss: 3.0726343393325806
Epoch 99/100, Loss: 2.9114819020032883
Epoch 100/100, Loss: 2.843204103410244
Fold 3/5 done
Epoch 1/100, Loss: 1.6162031330168247
Epoch 2/100, Loss: 1.3460720032453537
Epoch 3/100, Loss: 1.3752416782081127
Epoch 4/100, Loss: 1.607610747218132
Epoch 5/100, Loss: 1.4767454117536545
Epoch 6/100, Loss: 1.3512827716767788
Epoch 7/100, Loss: 1.5427244678139687
Epoch 8/100, Loss: 1.4357157722115517

Epoch 9/100, Loss: 1.4450644366443157
Epoch 10/100, Loss: 1.2936409786343575
Epoch 11/100, Loss: 1.3506306409835815
Epoch 12/100, Loss: 1.4398756138980389
Epoch 13/100, Loss: 1.267312541604042
Epoch 14/100, Loss: 1.7586059644818306
Epoch 15/100, Loss: 1.4196664690971375
Epoch 16/100, Loss: 1.4715051390230656
Epoch 17/100, Loss: 1.4076515659689903
Epoch 18/100, Loss: 1.2901754826307297
Epoch 19/100, Loss: 1.536827776581049
Epoch 20/100, Loss: 1.228349070996046
Epoch 21/100, Loss: 1.2662907615303993

Epoch 22/100, Loss: 1.515248291194439
Epoch 23/100, Loss: 1.4127583727240562
Epoch 24/100, Loss: 1.3442078977823257
Epoch 25/100, Loss: 1.4207674600183964
Epoch 26/100, Loss: 1.4417258277535439
Epoch 27/100, Loss: 1.3203205578029156
Epoch 28/100, Loss: 1.4111118018627167
Epoch 29/100, Loss: 1.4196354262530804
Epoch 30/100, Loss: 1.4541998095810413
Epoch 31/100, Loss: 1.3237446062266827
Epoch 32/100, Loss: 1.367681559175253
Epoch 33/100, Loss: 1.4502272680401802
Epoch 34/100, Loss: 1.4890828654170036
Epoch 35/100, Loss: 1.4258448705077171
Epoch 36/100, Loss: 1.451328182592988
Epoch 37/100, Loss: 1.303582163527608

Epoch 38/100, Loss: 1.2543152421712875
Epoch 39/100, Loss: 1.4479340761899948
Epoch 40/100, Loss: 1.422310546040535
Epoch 41/100, Loss: 1.4003545716404915
Epoch 42/100, Loss: 1.5482453107833862
Epoch 43/100, Loss: 1.319619357585907
Epoch 44/100, Loss: 1.479864601045847
Epoch 45/100, Loss: 1.550989855080843
Epoch 46/100, Loss: 1.464421709999442
Epoch 47/100, Loss: 1.4905430749058723
Epoch 48/100, Loss: 1.3918010890483856
Epoch 49/100, Loss: 1.4263392724096775
Epoch 50/100, Loss: 1.5078583471477032
Epoch 51/100, Loss: 1.469732480123639
Epoch 52/100, Loss: 1.2714309245347977

Epoch 53/100, Loss: 1.4409833438694477
Epoch 54/100, Loss: 1.3753253817558289
Epoch 55/100, Loss: 1.31466693431139
Epoch 56/100, Loss: 1.311127956956625
Epoch 57/100, Loss: 1.3726175762712955
Epoch 58/100, Loss: 1.2779363356530666
Epoch 59/100, Loss: 1.4431566633284092
Epoch 60/100, Loss: 1.33182561583817
Epoch 61/100, Loss: 1.3225726261734962
Epoch 62/100, Loss: 1.4963047839701176
Epoch 63/100, Loss: 1.4587760120630264
Epoch 64/100, Loss: 1.4607852809131145
Epoch 65/100, Loss: 1.2314470447599888
Epoch 66/100, Loss: 1.375843271613121

Epoch 67/100, Loss: 1.3680288717150688
Epoch 68/100, Loss: 1.423137053847313
Epoch 69/100, Loss: 1.545578233897686
Epoch 70/100, Loss: 1.4204754568636417
Epoch 71/100, Loss: 1.392930582165718
Epoch 72/100, Loss: 1.4159216657280922
Epoch 73/100, Loss: 1.4881809912621975
Epoch 74/100, Loss: 1.4935286156833172
Epoch 75/100, Loss: 1.3114167898893356
Epoch 76/100, Loss: 1.3404644913971424
Epoch 77/100, Loss: 1.4162157475948334
Epoch 78/100, Loss: 1.2435957044363022
Epoch 79/100, Loss: 1.2972329370677471
Epoch 80/100, Loss: 1.2936485577374697

Epoch 81/100, Loss: 1.5240714251995087
Epoch 82/100, Loss: 1.6379622891545296
Epoch 83/100, Loss: 1.4282234385609627
Epoch 84/100, Loss: 1.4151044711470604
Epoch 85/100, Loss: 1.458755899220705
Epoch 86/100, Loss: 1.362768515944481
Epoch 87/100, Loss: 1.4651497974991798
Epoch 88/100, Loss: 1.2966527938842773
Epoch 89/100, Loss: 1.2854249365627766
Epoch 90/100, Loss: 1.3829722963273525
Epoch 91/100, Loss: 1.5074026957154274
Epoch 92/100, Loss: 1.2880675308406353
Epoch 93/100, Loss: 1.4081701375544071
Epoch 94/100, Loss: 1.4706126600503922
Epoch 95/100, Loss: 1.4891917631030083

Epoch 96/100, Loss: 1.3361787106841803
Epoch 97/100, Loss: 1.3402541913092136
Epoch 98/100, Loss: 1.3601296842098236
Epoch 99/100, Loss: 1.3031948544085026
Epoch 100/100, Loss: 1.4931634590029716
Fold 4/5 done
Epoch 1/100, Loss: 1.9519907608628273
Epoch 2/100, Loss: 2.1676314771175385
Epoch 3/100, Loss: 2.358749285340309
Epoch 4/100, Loss: 2.2324306070804596
Epoch 5/100, Loss: 2.1936026588082314
Epoch 6/100, Loss: 2.1426825299859047
Epoch 7/100, Loss: 2.18692459911108
Epoch 8/100, Loss: 2.1735814660787582
Epoch 9/100, Loss: 1.9989968687295914

Epoch 10/100, Loss: 2.2215436324477196
Epoch 11/100, Loss: 2.1892081424593925
Epoch 12/100, Loss: 1.9526641517877579
Epoch 13/100, Loss: 2.2276770547032356
Epoch 14/100, Loss: 2.023758701980114
Epoch 15/100, Loss: 2.5826136767864227
Epoch 16/100, Loss: 2.123667798936367
Epoch 17/100, Loss: 2.0740611627697945
Epoch 18/100, Loss: 1.8056120947003365
Epoch 19/100, Loss: 2.1971603706479073
Epoch 20/100, Loss: 2.065283425152302
Epoch 21/100, Loss: 2.327590689063072
Epoch 22/100, Loss: 2.1945380493998528
Epoch 23/100, Loss: 2.1877245754003525
Epoch 24/100, Loss: 2.0170429944992065

Epoch 25/100, Loss: 1.9141515716910362
Epoch 26/100, Loss: 2.0978480726480484
Epoch 27/100, Loss: 1.9441277012228966
Epoch 28/100, Loss: 1.9846079647541046
Epoch 29/100, Loss: 2.1225070506334305
Epoch 30/100, Loss: 2.0209924653172493
Epoch 31/100, Loss: 1.8994956612586975
Epoch 32/100, Loss: 1.8645075261592865
Epoch 33/100, Loss: 2.2497868463397026
Epoch 34/100, Loss: 2.11280570179224
Epoch 35/100, Loss: 1.9618922844529152
Epoch 36/100, Loss: 2.0572793558239937
Epoch 37/100, Loss: 2.1542331501841545
Epoch 38/100, Loss: 2.1617360189557076
Epoch 39/100, Loss: 2.1159436479210854
Epoch 40/100, Loss: 2.113968387246132
Epoch 41/100, Loss: 2.092355765402317
Epoch 42/100, Loss: 2.1974405720829964

Epoch 43/100, Loss: 2.1553621739149094
Epoch 44/100, Loss: 2.1378308907151222
Epoch 45/100, Loss: 2.072175994515419
Epoch 46/100, Loss: 2.2570207938551903
Epoch 47/100, Loss: 2.2106983363628387
Epoch 48/100, Loss: 2.0990361720323563
Epoch 49/100, Loss: 2.0647548139095306
Epoch 50/100, Loss: 2.026636689901352
Epoch 51/100, Loss: 2.090229742228985
Epoch 52/100, Loss: 2.003439776599407
Epoch 53/100, Loss: 2.051235370337963
Epoch 54/100, Loss: 1.9544221386313438
Epoch 55/100, Loss: 2.0659151524305344
Epoch 56/100, Loss: 2.0225946828722954

Epoch 57/100, Loss: 1.8334097787737846
Epoch 58/100, Loss: 2.102478176355362
Epoch 59/100, Loss: 2.287470407783985
Epoch 60/100, Loss: 2.684462547302246
Epoch 61/100, Loss: 2.0252553522586823
Epoch 62/100, Loss: 2.0767867118120193
Epoch 63/100, Loss: 2.035148397088051
Epoch 64/100, Loss: 2.0821004658937454
Epoch 65/100, Loss: 2.079880081117153
Epoch 66/100, Loss: 2.0322166457772255
Epoch 67/100, Loss: 1.9644887447357178
Epoch 68/100, Loss: 1.888758584856987
Epoch 69/100, Loss: 2.096751593053341
Epoch 70/100, Loss: 2.1417941078543663
Epoch 71/100, Loss: 2.2036653831601143
Epoch 72/100, Loss: 2.162134572863579

Epoch 73/100, Loss: 2.1017395108938217
Epoch 74/100, Loss: 1.9284226298332214
Epoch 75/100, Loss: 1.9798932000994682
Epoch 76/100, Loss: 2.072380229830742
Epoch 77/100, Loss: 2.1268218606710434
Epoch 78/100, Loss: 2.0290692895650864
Epoch 79/100, Loss: 2.189333952963352
Epoch 80/100, Loss: 2.136449307203293
Epoch 81/100, Loss: 2.0402229130268097
Epoch 82/100, Loss: 2.066027410328388
Epoch 83/100, Loss: 1.8633805885910988
Epoch 84/100, Loss: 2.129885397851467
Epoch 85/100, Loss: 1.9193779341876507
Epoch 86/100, Loss: 2.1367395222187042
Epoch 87/100, Loss: 2.114750474691391
Epoch 88/100, Loss: 2.1284139901399612
Epoch 89/100, Loss: 2.0094793513417244

Epoch 90/100, Loss: 1.8666162192821503
Epoch 91/100, Loss: 2.069741301238537
Epoch 92/100, Loss: 1.9821178391575813
Epoch 93/100, Loss: 2.013818956911564
Epoch 94/100, Loss: 2.156256467103958
Epoch 95/100, Loss: 2.116410069167614
Epoch 96/100, Loss: 2.0543883442878723
Epoch 97/100, Loss: 2.0056143701076508
Epoch 98/100, Loss: 2.2050529047846794
Epoch 99/100, Loss: 2.1930426880717278
Epoch 100/100, Loss: 2.028275929391384
Fold 5/5 done

In [11]:
ap = average_precision_score(y_true, anomaly_scores)
print(f"Deep SVDD AP (5-fold CV) = {ap:.4f}")
sb.glue("GBG500_ap_spectral_deep_svdd", float(ap))

Deep SVDD AP (5-fold CV) = 0.5037