In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import average_precision_score
from sklearn.model_selection import StratifiedKFold
from pyod.models.deep_svdd import DeepSVDD
import sys
import scrapbook as sb

sys.path.append('..')
from utils import reshape_to_numpy, interpolate_missing_values, denoise_data, compute_spectrograms, time_avg_pooling

In [2]:
seed = 1
sampling_rate = 10
nperseg=64
noverlap=32
accel_cutoff = 0.4
accel_order = 30
gyro_cutoff = 0.6
gyro_order = 20
batch_size = 32
epochs = 100
hidden_neurons = [128, 64, 32]
n_splits = 5

In [3]:
# Parameters
seed = 17

In [4]:
rng = np.random.RandomState(seed)

In [5]:
data = pd.read_parquet("../data/GBG500.parquet")
data

,ride_id,time_index,ax,ay,az,rx,ry,rz
0,005043f1a7520cebf1e17fd166a00a3190e2433530f236...,0,-2.512796,-9.385012,-1.053078,-0.009155,0.009155,-0.201416
1,005043f1a7520cebf1e17fd166a00a3190e2433530f236...,100,-2.491268,-9.385012,-1.079390,-0.036621,0.027465,-0.155639
2,005043f1a7520cebf1e17fd166a00a3190e2433530f236...,200,-2.534324,-9.382022,-1.030952,0.036621,0.027465,-0.073242
3,005043f1a7520cebf1e17fd166a00a3190e2433530f236...,300,-2.488278,-9.383218,-1.091948,-0.045776,0.036621,-0.183105
4,005043f1a7520cebf1e17fd166a00a3190e2433530f236...,400,-2.483494,-9.382022,-1.100320,-0.045776,0.027465,-0.192260
...,...,...,...,...,...,...,...,...
1529542,ffb6f2f5dc6ba768d88dc0bc1af4cad235526aa9e24168...,241300,0.459862,-9.140430,-3.318900,1.556396,-0.091552,0.274658
1529543,ffb6f2f5dc6ba768d88dc0bc1af4cad235526aa9e24168...,241400,0.455676,-9.140430,-3.321292,1.583861,-0.119018,0.274658
1529544,ffb6f2f5dc6ba768d88dc0bc1af4cad235526aa9e24168...,241500,0.459862,-9.139832,-3.317704,1.583861,-0.109863,0.274658
1529545,ffb6f2f5dc6ba768d88dc0bc1af4cad235526aa9e24168...,241600,0.456274,-9.142224,-3.321292,1.574707,-0.137329,0.283813
1529546,ffb6f2f5dc6ba768d88dc0bc1af4cad235526aa9e24168...,241700,0.458666,-9.139832,-3.320694,1.574707,-0.137329,0.274658

In [6]:
labels = pd.read_csv("../data/GBG500_labels.csv")
labels.columns = labels.columns.str.lower()
ride_order_df = pd.DataFrame({"ride_id": data["ride_id"].unique()})
labels_sorted = ride_order_df.merge(
    labels,
    on="ride_id",
    how="left"
)
labels_sorted

                                               ride_id        label
0    005043f1a7520cebf1e17fd166a00a3190e2433530f236...         Safe
1    00d223cb7aecc9c0cc5871e32a6c45027a068eba07c572...     Reckless
2    02288a4aeca044203394e982e76b87818021dea2b34df9...         Safe
3    0236bdcf13d473ea24d97f5eaeea459f257dffac005694...  Bad weather
4    0238e5dd85143f1b6c59b200bc32f14361b8fc84c51a87...         Safe
..                                                 ...          ...
495  fe5d7f84d692bbccad8bd566a3ad5c3108fa9f90acd671...         Safe
496  fe67169632306d4668b2affedef510df2cb43e2fb41220...         Safe
497  fee44667fdc8ab4995c702fc3bd36178de0b1ca2c64687...         Safe
498  ff79b2e945b93c2a5efc3a06365267b3a160e7849ba57d...         Safe
499  ffb6f2f5dc6ba768d88dc0bc1af4cad235526aa9e24168...         Safe

[500 rows x 2 columns]

In [7]:
data_np = reshape_to_numpy(
    data,
    features = ["ax", "ay", "az", "rx", "ry", "rz"],
    max_timestamps = 4800
)

data_np_clean = interpolate_missing_values(
    data_np,
    method='linear',
    limit=None
)

data_np_clean = denoise_data(
    data=data_np_clean,
    accel_indices=[0, 1, 2],
    gyro_indices=[3, 4, 5],
    accel_cutoff=accel_cutoff,
    accel_order=accel_order,
    gyro_cutoff=gyro_cutoff,
    gyro_order=gyro_order,
)

In [8]:
# Compute spectrograms for all rides
spectrograms_array = compute_spectrograms(data_np_clean, sampling_rate, nperseg, noverlap)
spectrograms_array.shape

(500, 149, 6, 33)

In [9]:
# Aggregate spectrograms using time-averaged pooling
X_feat = time_avg_pooling(spectrograms_array)
X_feat.shape

(500, 198)

In [10]:
# 5-fold stratified CV with Deep SVDD
skf = StratifiedKFold(n_splits=n_splits, shuffle=True, random_state=rng.randint(1000))
y_true = (labels_sorted['label'] == 'Reckless').astype(int).values
anomaly_scores = np.full(len(y_true), np.nan)

for fold, (train_idx, test_idx) in enumerate(skf.split(X_feat, y_true)):
    sc = StandardScaler()
    X_train = sc.fit_transform(X_feat[train_idx])
    X_test = sc.transform(X_feat[test_idx])

    np.random.seed(rng.randint(1000))
    model = DeepSVDD(
        n_features=X_train.shape[1],
        hidden_neurons=hidden_neurons,
        epochs=epochs,
        batch_size=batch_size,
        random_state=rng.randint(1000),
    )
    model.fit(X_train)
    anomaly_scores[test_idx] = model.decision_function(X_test)
    print(f"Fold {fold+1}/{n_splits} done")

Epoch 1/100, Loss: 3.220177970826626
Epoch 2/100, Loss: 3.2946626096963882
Epoch 3/100, Loss: 2.9108799025416374
Epoch 4/100, Loss: 2.780594825744629
Epoch 5/100, Loss: 2.7089645341038704
Epoch 6/100, Loss: 2.9518554657697678
Epoch 7/100, Loss: 3.169661320745945
Epoch 8/100, Loss: 3.3719179034233093
Epoch 9/100, Loss: 3.358076274394989
Epoch 10/100, Loss: 2.9740401282906532
Epoch 11/100, Loss: 3.104072652757168
Epoch 12/100, Loss: 2.5323802679777145
Epoch 13/100, Loss: 3.042662225663662
Epoch 14/100, Loss: 3.1814008578658104
Epoch 15/100, Loss: 2.920693077147007
Epoch 16/100, Loss: 3.4273706898093224
Epoch 17/100, Loss: 3.394430197775364

Epoch 18/100, Loss: 3.2393247708678246
Epoch 19/100, Loss: 2.944789670407772
Epoch 20/100, Loss: 2.5040613785386086
Epoch 21/100, Loss: 2.9604366049170494
Epoch 22/100, Loss: 2.606214888393879
Epoch 23/100, Loss: 2.6415571123361588
Epoch 24/100, Loss: 2.9473049342632294
Epoch 25/100, Loss: 3.466454356908798
Epoch 26/100, Loss: 3.181276135146618
Epoch 27/100, Loss: 2.8558930307626724
Epoch 28/100, Loss: 3.3609613478183746
Epoch 29/100, Loss: 2.836013026535511
Epoch 30/100, Loss: 2.7633543387055397
Epoch 31/100, Loss: 3.234404109418392

Epoch 32/100, Loss: 2.9210914447903633
Epoch 33/100, Loss: 2.99090788513422
Epoch 34/100, Loss: 3.2359130531549454
Epoch 35/100, Loss: 3.137990318238735
Epoch 36/100, Loss: 3.1652712374925613
Epoch 37/100, Loss: 2.8790626749396324
Epoch 38/100, Loss: 2.9359904527664185
Epoch 39/100, Loss: 3.3936280384659767
Epoch 40/100, Loss: 3.0210972279310226
Epoch 41/100, Loss: 3.3107111752033234
Epoch 42/100, Loss: 3.104798302054405
Epoch 43/100, Loss: 2.465897612273693
Epoch 44/100, Loss: 3.4011047184467316
Epoch 45/100, Loss: 2.687566392123699
Epoch 46/100, Loss: 3.0588990598917007
Epoch 47/100, Loss: 2.5144796296954155
Epoch 48/100, Loss: 2.899511307477951
Epoch 49/100, Loss: 2.8127253502607346

Epoch 50/100, Loss: 2.911402516067028
Epoch 51/100, Loss: 2.5655637234449387
Epoch 52/100, Loss: 2.82315231859684
Epoch 53/100, Loss: 2.983627274632454
Epoch 54/100, Loss: 3.124625600874424
Epoch 55/100, Loss: 2.8433491960167885
Epoch 56/100, Loss: 2.9473506063222885
Epoch 57/100, Loss: 2.700312338769436
Epoch 58/100, Loss: 2.56844948977232
Epoch 59/100, Loss: 2.956121362745762
Epoch 60/100, Loss: 3.1195111498236656
Epoch 61/100, Loss: 3.205742746591568
Epoch 62/100, Loss: 3.174479231238365
Epoch 63/100, Loss: 3.101216897368431
Epoch 64/100, Loss: 3.285276748239994
Epoch 65/100, Loss: 3.0550319626927376
Epoch 66/100, Loss: 2.940324991941452
Epoch 67/100, Loss: 3.0022691786289215

Epoch 68/100, Loss: 3.320753738284111
Epoch 69/100, Loss: 3.0609924718737602
Epoch 70/100, Loss: 2.500774271786213
Epoch 71/100, Loss: 2.8480304479599
Epoch 72/100, Loss: 3.8760014101862907
Epoch 73/100, Loss: 3.10883579403162
Epoch 74/100, Loss: 2.919016696512699
Epoch 75/100, Loss: 2.702549748122692
Epoch 76/100, Loss: 3.026038996875286
Epoch 77/100, Loss: 3.188251718878746
Epoch 78/100, Loss: 2.4111677706241608
Epoch 79/100, Loss: 2.977522023022175
Epoch 80/100, Loss: 3.2659203857183456
Epoch 81/100, Loss: 2.829516664147377
Epoch 82/100, Loss: 3.0797249525785446
Epoch 83/100, Loss: 3.3872137367725372
Epoch 84/100, Loss: 3.2675506621599197
Epoch 85/100, Loss: 3.0307698994874954

Epoch 86/100, Loss: 2.9532554298639297
Epoch 87/100, Loss: 3.005731984972954
Epoch 88/100, Loss: 2.722606398165226
Epoch 89/100, Loss: 3.2430493906140327
Epoch 90/100, Loss: 2.6870414093136787
Epoch 91/100, Loss: 2.6788967326283455
Epoch 92/100, Loss: 2.982980467379093
Epoch 93/100, Loss: 3.3388971239328384
Epoch 94/100, Loss: 2.7572995498776436
Epoch 95/100, Loss: 2.961092844605446
Epoch 96/100, Loss: 3.134649023413658
Epoch 97/100, Loss: 2.9903288036584854
Epoch 98/100, Loss: 2.6085359379649162
Epoch 99/100, Loss: 2.7698115706443787
Epoch 100/100, Loss: 3.3463269025087357
Fold 1/5 done
Epoch 1/100, Loss: 1.995396725833416
Epoch 2/100, Loss: 2.379646886140108

Epoch 3/100, Loss: 2.0486694388091564
Epoch 4/100, Loss: 2.0084254443645477
Epoch 5/100, Loss: 1.8090020343661308
Epoch 6/100, Loss: 2.090358715504408
Epoch 7/100, Loss: 2.085873603820801
Epoch 8/100, Loss: 2.3552531488239765
Epoch 9/100, Loss: 2.1855180226266384
Epoch 10/100, Loss: 2.38144164532423
Epoch 11/100, Loss: 2.433065377175808
Epoch 12/100, Loss: 2.6111082062125206
Epoch 13/100, Loss: 2.1494228467345238
Epoch 14/100, Loss: 2.1934285014867783
Epoch 15/100, Loss: 1.9502455778419971
Epoch 16/100, Loss: 2.172646015882492
Epoch 17/100, Loss: 2.099030554294586
Epoch 18/100, Loss: 1.856396123766899
Epoch 19/100, Loss: 2.3450768813490868
Epoch 20/100, Loss: 1.7384036555886269
Epoch 21/100, Loss: 2.3915365636348724

Epoch 22/100, Loss: 2.104200467467308
Epoch 23/100, Loss: 1.9115472361445427
Epoch 24/100, Loss: 2.289900004863739
Epoch 25/100, Loss: 2.2064907178282738
Epoch 26/100, Loss: 1.844464398920536
Epoch 27/100, Loss: 2.131758891046047
Epoch 28/100, Loss: 2.3601162061095238
Epoch 29/100, Loss: 2.354756861925125
Epoch 30/100, Loss: 2.1277863569557667
Epoch 31/100, Loss: 2.1110865101218224
Epoch 32/100, Loss: 2.315581791102886
Epoch 33/100, Loss: 2.231289066374302
Epoch 34/100, Loss: 1.9683072566986084
Epoch 35/100, Loss: 2.1262511238455772
Epoch 36/100, Loss: 2.135240338742733
Epoch 37/100, Loss: 2.1501911990344524
Epoch 38/100, Loss: 2.1110468693077564
Epoch 39/100, Loss: 1.5380559526383877

Epoch 40/100, Loss: 1.9430934339761734
Epoch 41/100, Loss: 2.0496045388281345
Epoch 42/100, Loss: 2.1249258890748024
Epoch 43/100, Loss: 1.7764033004641533
Epoch 44/100, Loss: 2.123173203319311
Epoch 45/100, Loss: 2.1772980839014053
Epoch 46/100, Loss: 2.0408253222703934
Epoch 47/100, Loss: 2.1807445473968983
Epoch 48/100, Loss: 2.3065302073955536
Epoch 49/100, Loss: 2.2938371896743774
Epoch 50/100, Loss: 2.202434040606022
Epoch 51/100, Loss: 2.087859719991684
Epoch 52/100, Loss: 2.149541422724724
Epoch 53/100, Loss: 1.9587721899151802
Epoch 54/100, Loss: 2.368494391441345
Epoch 55/100, Loss: 1.8883429020643234
Epoch 56/100, Loss: 2.2390568777918816
Epoch 57/100, Loss: 2.360698916018009

Epoch 58/100, Loss: 2.208901032805443
Epoch 59/100, Loss: 2.1826115176081657
Epoch 60/100, Loss: 2.6669719591736794
Epoch 61/100, Loss: 2.164050057530403
Epoch 62/100, Loss: 2.2476911321282387
Epoch 63/100, Loss: 2.7396734207868576
Epoch 64/100, Loss: 1.900997094810009
Epoch 65/100, Loss: 1.807753600180149
Epoch 66/100, Loss: 2.2254748046398163
Epoch 67/100, Loss: 1.7928348258137703
Epoch 68/100, Loss: 2.2799974903464317
Epoch 69/100, Loss: 2.1836102977395058
Epoch 70/100, Loss: 1.828130528330803

Epoch 71/100, Loss: 2.3712074644863605
Epoch 72/100, Loss: 1.8936054185032845
Epoch 73/100, Loss: 2.202301800251007
Epoch 74/100, Loss: 2.3748395517468452
Epoch 75/100, Loss: 2.292611200362444
Epoch 76/100, Loss: 2.3579230085015297
Epoch 77/100, Loss: 2.130974441766739
Epoch 78/100, Loss: 1.96376633644104
Epoch 79/100, Loss: 2.145472675561905
Epoch 80/100, Loss: 2.044788934290409
Epoch 81/100, Loss: 2.4413146525621414
Epoch 82/100, Loss: 1.944153942167759
Epoch 83/100, Loss: 1.8439681231975555
Epoch 84/100, Loss: 2.2468159273266792
Epoch 85/100, Loss: 2.1928834095597267
Epoch 86/100, Loss: 2.4403752125799656
Epoch 87/100, Loss: 1.9117704555392265

Epoch 88/100, Loss: 1.9122827425599098
Epoch 89/100, Loss: 1.9233051426708698
Epoch 90/100, Loss: 2.0056272633373737
Epoch 91/100, Loss: 2.188899151980877
Epoch 92/100, Loss: 2.319567408412695
Epoch 93/100, Loss: 1.985828921198845
Epoch 94/100, Loss: 2.207869950681925
Epoch 95/100, Loss: 1.9573004133999348
Epoch 96/100, Loss: 2.185396645218134
Epoch 97/100, Loss: 1.9923276901245117
Epoch 98/100, Loss: 1.9613407105207443
Epoch 99/100, Loss: 1.9744500145316124
Epoch 100/100, Loss: 2.3172437958419323
Fold 2/5 done
Epoch 1/100, Loss: 1.8234959095716476
Epoch 2/100, Loss: 1.776844598352909

Epoch 3/100, Loss: 1.8513340801000595
Epoch 4/100, Loss: 1.7494862154126167
Epoch 5/100, Loss: 1.781991995871067
Epoch 6/100, Loss: 1.934049867093563
Epoch 7/100, Loss: 1.9002778381109238
Epoch 8/100, Loss: 1.8597280234098434
Epoch 9/100, Loss: 1.7361082583665848
Epoch 10/100, Loss: 1.7555907219648361
Epoch 11/100, Loss: 1.875207968056202
Epoch 12/100, Loss: 1.8937186896800995
Epoch 13/100, Loss: 1.8169885352253914
Epoch 14/100, Loss: 1.9155277013778687
Epoch 15/100, Loss: 1.827067956328392

Epoch 16/100, Loss: 1.7785382568836212
Epoch 17/100, Loss: 1.6910602748394012
Epoch 18/100, Loss: 1.8364267945289612
Epoch 19/100, Loss: 1.880497731268406
Epoch 20/100, Loss: 1.845394715666771
Epoch 21/100, Loss: 1.8032153844833374
Epoch 22/100, Loss: 1.9668995216488838
Epoch 23/100, Loss: 1.871907778084278
Epoch 24/100, Loss: 1.892303429543972
Epoch 25/100, Loss: 1.8996207192540169
Epoch 26/100, Loss: 1.903742041438818
Epoch 27/100, Loss: 1.7732584550976753
Epoch 28/100, Loss: 1.7562722265720367
Epoch 29/100, Loss: 1.7531389258801937
Epoch 30/100, Loss: 1.8175052851438522
Epoch 31/100, Loss: 1.7576940655708313
Epoch 32/100, Loss: 1.7896353900432587

Epoch 33/100, Loss: 1.811866320669651
Epoch 34/100, Loss: 1.7022863700985909
Epoch 35/100, Loss: 1.8054103404283524
Epoch 36/100, Loss: 1.7604345604777336
Epoch 37/100, Loss: 1.8697755970060825
Epoch 38/100, Loss: 1.8314840719103813
Epoch 39/100, Loss: 1.8712150007486343
Epoch 40/100, Loss: 1.7331314757466316
Epoch 41/100, Loss: 1.9010496586561203
Epoch 42/100, Loss: 1.7594365999102592
Epoch 43/100, Loss: 1.7977365478873253
Epoch 44/100, Loss: 1.8278999850153923

Epoch 45/100, Loss: 1.8298817873001099
Epoch 46/100, Loss: 1.8237142786383629
Epoch 47/100, Loss: 1.7369243875145912
Epoch 48/100, Loss: 1.81464434415102
Epoch 49/100, Loss: 1.8413425981998444
Epoch 50/100, Loss: 1.75752542167902
Epoch 51/100, Loss: 1.867162249982357
Epoch 52/100, Loss: 1.8007092624902725
Epoch 53/100, Loss: 1.8211640864610672
Epoch 54/100, Loss: 1.9315798804163933
Epoch 55/100, Loss: 1.773133210837841

Epoch 56/100, Loss: 1.8546869829297066
Epoch 57/100, Loss: 1.8442758843302727
Epoch 58/100, Loss: 1.8114622384309769
Epoch 59/100, Loss: 1.8763748183846474
Epoch 60/100, Loss: 1.7708372622728348
Epoch 61/100, Loss: 1.80386483669281
Epoch 62/100, Loss: 1.8192452937364578
Epoch 63/100, Loss: 1.8384012803435326
Epoch 64/100, Loss: 1.8017061576247215
Epoch 65/100, Loss: 1.7466886639595032
Epoch 66/100, Loss: 1.6542946510016918
Epoch 67/100, Loss: 1.7869560196995735

Epoch 68/100, Loss: 1.7682327628135681
Epoch 69/100, Loss: 1.7965943217277527
Epoch 70/100, Loss: 1.8408266231417656
Epoch 71/100, Loss: 1.8221354261040688
Epoch 72/100, Loss: 1.834316447377205
Epoch 73/100, Loss: 1.8019022345542908
Epoch 74/100, Loss: 1.771744042634964
Epoch 75/100, Loss: 1.9110365435481071
Epoch 76/100, Loss: 1.8573633059859276
Epoch 77/100, Loss: 1.7577948197722435
Epoch 78/100, Loss: 1.8318809568881989

Epoch 79/100, Loss: 1.7411372512578964
Epoch 80/100, Loss: 1.8197966367006302
Epoch 81/100, Loss: 1.7282194048166275
Epoch 82/100, Loss: 1.7742102518677711
Epoch 83/100, Loss: 1.7697070240974426
Epoch 84/100, Loss: 1.765775389969349
Epoch 85/100, Loss: 1.785712219774723
Epoch 86/100, Loss: 1.8123906031250954
Epoch 87/100, Loss: 1.7595127075910568
Epoch 88/100, Loss: 1.901397429406643
Epoch 89/100, Loss: 1.7724486142396927

Epoch 90/100, Loss: 1.7480545043945312
Epoch 91/100, Loss: 1.834453009068966
Epoch 92/100, Loss: 1.7171630412340164
Epoch 93/100, Loss: 1.8348091095685959
Epoch 94/100, Loss: 1.780300334095955
Epoch 95/100, Loss: 1.7359516471624374
Epoch 96/100, Loss: 1.7532151192426682
Epoch 97/100, Loss: 1.8047181889414787
Epoch 98/100, Loss: 1.801921583712101
Epoch 99/100, Loss: 1.8576771393418312
Epoch 100/100, Loss: 1.7739878222346306
Fold 3/5 done

Epoch 1/100, Loss: 2.139164537191391
Epoch 2/100, Loss: 2.032366968691349
Epoch 3/100, Loss: 2.5655189529061317
Epoch 4/100, Loss: 2.2897486686706543
Epoch 5/100, Loss: 2.2531296610832214
Epoch 6/100, Loss: 2.246436782181263
Epoch 7/100, Loss: 1.9465144723653793
Epoch 8/100, Loss: 2.0305654257535934
Epoch 9/100, Loss: 2.296591266989708
Epoch 10/100, Loss: 2.2543555945158005
Epoch 11/100, Loss: 2.2047652825713158

Epoch 12/100, Loss: 2.256822608411312
Epoch 13/100, Loss: 2.298063427209854
Epoch 14/100, Loss: 2.319763444364071
Epoch 15/100, Loss: 2.0921954214572906
Epoch 16/100, Loss: 2.2346188127994537
Epoch 17/100, Loss: 2.428296610713005
Epoch 18/100, Loss: 2.3852544724941254
Epoch 19/100, Loss: 2.2836082503199577
Epoch 20/100, Loss: 2.047577828168869
Epoch 21/100, Loss: 2.344998277723789
Epoch 22/100, Loss: 2.2023721113801003

Epoch 23/100, Loss: 2.0905742794275284
Epoch 24/100, Loss: 2.637171693146229
Epoch 25/100, Loss: 2.310296319425106
Epoch 26/100, Loss: 2.065806955099106
Epoch 27/100, Loss: 1.9813172072172165
Epoch 28/100, Loss: 2.6403568387031555
Epoch 29/100, Loss: 2.184353705495596
Epoch 30/100, Loss: 2.170385964214802
Epoch 31/100, Loss: 2.0053439885377884
Epoch 32/100, Loss: 2.330566890537739
Epoch 33/100, Loss: 2.5605520382523537

Epoch 34/100, Loss: 2.2230841293931007
Epoch 35/100, Loss: 1.9285298138856888
Epoch 36/100, Loss: 2.423100382089615
Epoch 37/100, Loss: 2.408389423042536
Epoch 38/100, Loss: 3.141457848250866
Epoch 39/100, Loss: 1.9476590007543564
Epoch 40/100, Loss: 2.047392699867487
Epoch 41/100, Loss: 2.284556068480015
Epoch 42/100, Loss: 2.3784479573369026
Epoch 43/100, Loss: 2.24740819260478
Epoch 44/100, Loss: 2.278670497238636
Epoch 45/100, Loss: 2.1731885224580765

Epoch 46/100, Loss: 2.352529987692833
Epoch 47/100, Loss: 2.012586608529091
Epoch 48/100, Loss: 2.3921112827956676
Epoch 49/100, Loss: 2.2627907022833824
Epoch 50/100, Loss: 2.3865963369607925
Epoch 51/100, Loss: 2.0846134647727013
Epoch 52/100, Loss: 2.294962413609028
Epoch 53/100, Loss: 2.333542563021183
Epoch 54/100, Loss: 2.369756154716015
Epoch 55/100, Loss: 2.6901071667671204
Epoch 56/100, Loss: 1.9603527337312698

Epoch 57/100, Loss: 2.411526173353195
Epoch 58/100, Loss: 2.15888961404562
Epoch 59/100, Loss: 2.2485782727599144
Epoch 60/100, Loss: 2.4691116586327553
Epoch 61/100, Loss: 2.1094534397125244
Epoch 62/100, Loss: 1.9831218346953392
Epoch 63/100, Loss: 2.0212748125195503
Epoch 64/100, Loss: 2.275676019489765
Epoch 65/100, Loss: 1.9169491343200207
Epoch 66/100, Loss: 2.1007249280810356
Epoch 67/100, Loss: 2.3798972219228745
Epoch 68/100, Loss: 2.2606340870261192

Epoch 69/100, Loss: 2.4327678978443146
Epoch 70/100, Loss: 2.4099372252821922
Epoch 71/100, Loss: 2.078570194542408
Epoch 72/100, Loss: 2.4584405794739723
Epoch 73/100, Loss: 2.2731722481548786
Epoch 74/100, Loss: 2.2991913855075836
Epoch 75/100, Loss: 2.075897753238678
Epoch 76/100, Loss: 2.2420376986265182
Epoch 77/100, Loss: 2.0269417092204094
Epoch 78/100, Loss: 2.2278250381350517
Epoch 79/100, Loss: 2.218994066119194

Epoch 80/100, Loss: 2.278786726295948
Epoch 81/100, Loss: 2.2158311307430267
Epoch 82/100, Loss: 2.290326565504074
Epoch 83/100, Loss: 2.2237299904227257
Epoch 84/100, Loss: 2.2933206781744957
Epoch 85/100, Loss: 2.3078261464834213
Epoch 86/100, Loss: 2.34794432669878
Epoch 87/100, Loss: 2.4347488656640053
Epoch 88/100, Loss: 2.309685230255127
Epoch 89/100, Loss: 1.8154762759804726
Epoch 90/100, Loss: 2.764186628162861
Epoch 91/100, Loss: 2.397302806377411

Epoch 92/100, Loss: 2.3092129044234753
Epoch 93/100, Loss: 2.165741205215454
Epoch 94/100, Loss: 1.9895535111427307
Epoch 95/100, Loss: 1.9976305440068245
Epoch 96/100, Loss: 2.359708935022354
Epoch 97/100, Loss: 2.2826540917158127
Epoch 98/100, Loss: 2.392035871744156
Epoch 99/100, Loss: 2.377618446946144
Epoch 100/100, Loss: 2.1259858906269073
Fold 4/5 done
Epoch 1/100, Loss: 1.450478058308363
Epoch 2/100, Loss: 1.2782104313373566
Epoch 3/100, Loss: 1.3165436200797558
Epoch 4/100, Loss: 1.5220782607793808
Epoch 5/100, Loss: 1.383408360183239
Epoch 6/100, Loss: 1.4052726440131664
Epoch 7/100, Loss: 1.4022058211266994

Epoch 8/100, Loss: 1.2602533102035522
Epoch 9/100, Loss: 1.2167445458471775
Epoch 10/100, Loss: 1.3355809040367603
Epoch 11/100, Loss: 1.4199551083147526
Epoch 12/100, Loss: 1.6171865016222
Epoch 13/100, Loss: 1.4543417058885098
Epoch 14/100, Loss: 1.2418582886457443
Epoch 15/100, Loss: 1.3546949215233326
Epoch 16/100, Loss: 1.3599436655640602
Epoch 17/100, Loss: 1.465211983770132
Epoch 18/100, Loss: 1.339336596429348
Epoch 19/100, Loss: 1.4840394891798496
Epoch 20/100, Loss: 1.2080465890467167
Epoch 21/100, Loss: 1.3537318632006645
Epoch 22/100, Loss: 1.3889230079948902
Epoch 23/100, Loss: 1.3513913080096245

Epoch 24/100, Loss: 1.4215452745556831
Epoch 25/100, Loss: 1.4467428177595139
Epoch 26/100, Loss: 1.34921046346426
Epoch 27/100, Loss: 1.4102842435240746
Epoch 28/100, Loss: 1.3538193702697754
Epoch 29/100, Loss: 1.4898586459457874
Epoch 30/100, Loss: 1.2247243449091911
Epoch 31/100, Loss: 1.508617028594017
Epoch 32/100, Loss: 1.4380981996655464
Epoch 33/100, Loss: 1.4394028522074223
Epoch 34/100, Loss: 1.4834838807582855
Epoch 35/100, Loss: 1.4838044941425323
Epoch 36/100, Loss: 1.1732566840946674
Epoch 37/100, Loss: 1.268317885696888
Epoch 38/100, Loss: 1.3243778012692928
Epoch 39/100, Loss: 1.3397939652204514
Epoch 40/100, Loss: 1.4356773681938648

Epoch 41/100, Loss: 1.3764756880700588
Epoch 42/100, Loss: 1.2187106274068356
Epoch 43/100, Loss: 1.334678042680025
Epoch 44/100, Loss: 1.35208261013031
Epoch 45/100, Loss: 1.520542424172163
Epoch 46/100, Loss: 1.3606662042438984
Epoch 47/100, Loss: 1.301673948764801
Epoch 48/100, Loss: 1.4179662577807903
Epoch 49/100, Loss: 1.3128732778131962
Epoch 50/100, Loss: 1.4759175851941109
Epoch 51/100, Loss: 1.2880827337503433
Epoch 52/100, Loss: 1.3598748818039894
Epoch 53/100, Loss: 1.3681999817490578
Epoch 54/100, Loss: 1.2023664005100727
Epoch 55/100, Loss: 1.2856913655996323

Epoch 56/100, Loss: 1.5636460967361927
Epoch 57/100, Loss: 1.275397527962923
Epoch 58/100, Loss: 1.3364901058375835
Epoch 59/100, Loss: 1.208368968218565
Epoch 60/100, Loss: 1.5290706753730774
Epoch 61/100, Loss: 1.2076259665191174
Epoch 62/100, Loss: 1.402006808668375
Epoch 63/100, Loss: 1.3145335912704468
Epoch 64/100, Loss: 1.2569491304457188
Epoch 65/100, Loss: 1.3656842857599258
Epoch 66/100, Loss: 1.2562622055411339
Epoch 67/100, Loss: 1.3815204165875912
Epoch 68/100, Loss: 1.327040009200573
Epoch 69/100, Loss: 1.5080317668616772
Epoch 70/100, Loss: 1.1909778974950314

Epoch 71/100, Loss: 1.3399258963763714
Epoch 72/100, Loss: 1.4150159172713757
Epoch 73/100, Loss: 1.3533318750560284
Epoch 74/100, Loss: 1.3724414259195328
Epoch 75/100, Loss: 1.2116827890276909
Epoch 76/100, Loss: 1.400583241134882
Epoch 77/100, Loss: 1.5045307651162148
Epoch 78/100, Loss: 1.318667646497488
Epoch 79/100, Loss: 1.3797575123608112
Epoch 80/100, Loss: 1.3554354943335056
Epoch 81/100, Loss: 1.1777246333658695
Epoch 82/100, Loss: 1.3635064475238323
Epoch 83/100, Loss: 1.247484840452671
Epoch 84/100, Loss: 1.4268770925700665
Epoch 85/100, Loss: 1.384051401168108

Epoch 86/100, Loss: 1.3538228869438171
Epoch 87/100, Loss: 1.245988130569458
Epoch 88/100, Loss: 1.341013964265585
Epoch 89/100, Loss: 1.230606246739626
Epoch 90/100, Loss: 1.4472165927290916
Epoch 91/100, Loss: 1.594719361513853
Epoch 92/100, Loss: 1.3758226595818996
Epoch 93/100, Loss: 1.205508302897215
Epoch 94/100, Loss: 1.5281909219920635
Epoch 95/100, Loss: 1.3451565317809582
Epoch 96/100, Loss: 1.382330697029829
Epoch 97/100, Loss: 1.3709632977843285
Epoch 98/100, Loss: 1.4355743415653706
Epoch 99/100, Loss: 1.3645697683095932
Epoch 100/100, Loss: 1.236259564757347
Fold 5/5 done

In [11]:
ap = average_precision_score(y_true, anomaly_scores)
print(f"Deep SVDD AP (5-fold CV) = {ap:.4f}")
sb.glue("GBG500_ap_spectral_deep_svdd", float(ap))

Deep SVDD AP (5-fold CV) = 0.5806