In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import average_precision_score
from sklearn.model_selection import StratifiedKFold
from pyod.models.deep_svdd import DeepSVDD
import sys
import scrapbook as sb

sys.path.append('..')
from utils import reshape_to_numpy, interpolate_missing_values, denoise_data, compute_spectrograms, time_avg_pooling

In [2]:
seed = 1
sampling_rate = 10
nperseg=64
noverlap=32
accel_cutoff = 0.4
accel_order = 30
gyro_cutoff = 0.6
gyro_order = 20
batch_size = 32
epochs = 100
hidden_neurons = [128, 64, 32]
n_splits = 5

In [3]:
# Parameters
seed = 24

In [4]:
rng = np.random.RandomState(seed)

In [5]:
data = pd.read_parquet("../data/GBG500.parquet")
data

,ride_id,time_index,ax,ay,az,rx,ry,rz
0,005043f1a7520cebf1e17fd166a00a3190e2433530f236...,0,-2.512796,-9.385012,-1.053078,-0.009155,0.009155,-0.201416
1,005043f1a7520cebf1e17fd166a00a3190e2433530f236...,100,-2.491268,-9.385012,-1.079390,-0.036621,0.027465,-0.155639
2,005043f1a7520cebf1e17fd166a00a3190e2433530f236...,200,-2.534324,-9.382022,-1.030952,0.036621,0.027465,-0.073242
3,005043f1a7520cebf1e17fd166a00a3190e2433530f236...,300,-2.488278,-9.383218,-1.091948,-0.045776,0.036621,-0.183105
4,005043f1a7520cebf1e17fd166a00a3190e2433530f236...,400,-2.483494,-9.382022,-1.100320,-0.045776,0.027465,-0.192260
...,...,...,...,...,...,...,...,...
1529542,ffb6f2f5dc6ba768d88dc0bc1af4cad235526aa9e24168...,241300,0.459862,-9.140430,-3.318900,1.556396,-0.091552,0.274658
1529543,ffb6f2f5dc6ba768d88dc0bc1af4cad235526aa9e24168...,241400,0.455676,-9.140430,-3.321292,1.583861,-0.119018,0.274658
1529544,ffb6f2f5dc6ba768d88dc0bc1af4cad235526aa9e24168...,241500,0.459862,-9.139832,-3.317704,1.583861,-0.109863,0.274658
1529545,ffb6f2f5dc6ba768d88dc0bc1af4cad235526aa9e24168...,241600,0.456274,-9.142224,-3.321292,1.574707,-0.137329,0.283813
1529546,ffb6f2f5dc6ba768d88dc0bc1af4cad235526aa9e24168...,241700,0.458666,-9.139832,-3.320694,1.574707,-0.137329,0.274658

In [6]:
labels = pd.read_csv("../data/GBG500_labels.csv")
labels.columns = labels.columns.str.lower()
ride_order_df = pd.DataFrame({"ride_id": data["ride_id"].unique()})
labels_sorted = ride_order_df.merge(
    labels,
    on="ride_id",
    how="left"
)
labels_sorted

                                               ride_id        label
0    005043f1a7520cebf1e17fd166a00a3190e2433530f236...         Safe
1    00d223cb7aecc9c0cc5871e32a6c45027a068eba07c572...     Reckless
2    02288a4aeca044203394e982e76b87818021dea2b34df9...         Safe
3    0236bdcf13d473ea24d97f5eaeea459f257dffac005694...  Bad weather
4    0238e5dd85143f1b6c59b200bc32f14361b8fc84c51a87...         Safe
..                                                 ...          ...
495  fe5d7f84d692bbccad8bd566a3ad5c3108fa9f90acd671...         Safe
496  fe67169632306d4668b2affedef510df2cb43e2fb41220...         Safe
497  fee44667fdc8ab4995c702fc3bd36178de0b1ca2c64687...         Safe
498  ff79b2e945b93c2a5efc3a06365267b3a160e7849ba57d...         Safe
499  ffb6f2f5dc6ba768d88dc0bc1af4cad235526aa9e24168...         Safe

[500 rows x 2 columns]

In [7]:
data_np = reshape_to_numpy(
    data,
    features = ["ax", "ay", "az", "rx", "ry", "rz"],
    max_timestamps = 4800
)

data_np_clean = interpolate_missing_values(
    data_np,
    method='linear',
    limit=None
)

data_np_clean = denoise_data(
    data=data_np_clean,
    accel_indices=[0, 1, 2],
    gyro_indices=[3, 4, 5],
    accel_cutoff=accel_cutoff,
    accel_order=accel_order,
    gyro_cutoff=gyro_cutoff,
    gyro_order=gyro_order,
)

In [8]:
# Compute spectrograms for all rides
spectrograms_array = compute_spectrograms(data_np_clean, sampling_rate, nperseg, noverlap)
spectrograms_array.shape

(500, 149, 6, 33)

In [9]:
# Aggregate spectrograms using time-averaged pooling
X_feat = time_avg_pooling(spectrograms_array)
X_feat.shape

(500, 198)

In [10]:
# 5-fold stratified CV with Deep SVDD
skf = StratifiedKFold(n_splits=n_splits, shuffle=True, random_state=rng.randint(1000))
y_true = (labels_sorted['label'] == 'Reckless').astype(int).values
anomaly_scores = np.full(len(y_true), np.nan)

for fold, (train_idx, test_idx) in enumerate(skf.split(X_feat, y_true)):
    sc = StandardScaler()
    X_train = sc.fit_transform(X_feat[train_idx])
    X_test = sc.transform(X_feat[test_idx])

    np.random.seed(rng.randint(1000))
    model = DeepSVDD(
        n_features=X_train.shape[1],
        hidden_neurons=hidden_neurons,
        epochs=epochs,
        batch_size=batch_size,
        random_state=rng.randint(1000),
    )
    model.fit(X_train)
    anomaly_scores[test_idx] = model.decision_function(X_test)
    print(f"Fold {fold+1}/{n_splits} done")

Epoch 1/100, Loss: 3.3871522545814514
Epoch 2/100, Loss: 3.110112726688385
Epoch 3/100, Loss: 3.5756892189383507
Epoch 4/100, Loss: 3.4043615609407425
Epoch 5/100, Loss: 3.13773126155138
Epoch 6/100, Loss: 2.994248650968075
Epoch 7/100, Loss: 3.1750553622841835
Epoch 8/100, Loss: 3.437043257057667
Epoch 9/100, Loss: 3.120813399553299
Epoch 10/100, Loss: 3.7185876816511154
Epoch 11/100, Loss: 3.408920004963875
Epoch 12/100, Loss: 3.4017453864216805
Epoch 13/100, Loss: 3.564692460000515
Epoch 14/100, Loss: 3.223409526050091
Epoch 15/100, Loss: 3.5263360738754272
Epoch 16/100, Loss: 2.9409516379237175
Epoch 17/100, Loss: 3.6640551909804344

Epoch 18/100, Loss: 3.4472208470106125
Epoch 19/100, Loss: 3.27838134765625
Epoch 20/100, Loss: 3.482903391122818
Epoch 21/100, Loss: 3.5613007321953773
Epoch 22/100, Loss: 3.396634340286255
Epoch 23/100, Loss: 3.18790639936924
Epoch 24/100, Loss: 3.4604018926620483
Epoch 25/100, Loss: 3.339185245335102
Epoch 26/100, Loss: 3.534979499876499
Epoch 27/100, Loss: 3.6531809270381927
Epoch 28/100, Loss: 3.196453794836998
Epoch 29/100, Loss: 3.386891260743141
Epoch 30/100, Loss: 3.0168882608413696
Epoch 31/100, Loss: 3.225889764726162
Epoch 32/100, Loss: 3.742921195924282
Epoch 33/100, Loss: 3.1970741525292397
Epoch 34/100, Loss: 3.4376433193683624

Epoch 35/100, Loss: 3.2675831988453865
Epoch 36/100, Loss: 3.1935247629880905
Epoch 37/100, Loss: 3.1354561671614647
Epoch 38/100, Loss: 3.33726504445076
Epoch 39/100, Loss: 4.6093210726976395
Epoch 40/100, Loss: 3.241439498960972
Epoch 41/100, Loss: 3.58886232227087
Epoch 42/100, Loss: 3.6528222486376762
Epoch 43/100, Loss: 3.3455981612205505
Epoch 44/100, Loss: 3.4312222003936768
Epoch 45/100, Loss: 3.310652807354927
Epoch 46/100, Loss: 3.2272687926888466
Epoch 47/100, Loss: 3.176228918135166
Epoch 48/100, Loss: 3.519497886300087
Epoch 49/100, Loss: 3.612541474401951
Epoch 50/100, Loss: 3.259974353015423

Epoch 51/100, Loss: 3.2686657086014748
Epoch 52/100, Loss: 3.4269435554742813
Epoch 53/100, Loss: 3.2319383025169373
Epoch 54/100, Loss: 3.2640643790364265
Epoch 55/100, Loss: 2.8626462295651436
Epoch 56/100, Loss: 3.329521596431732
Epoch 57/100, Loss: 3.237585760653019
Epoch 58/100, Loss: 4.077956475317478
Epoch 59/100, Loss: 3.2497930228710175
Epoch 60/100, Loss: 3.228603795170784

Epoch 61/100, Loss: 3.391651064157486
Epoch 62/100, Loss: 3.6218282282352448
Epoch 63/100, Loss: 3.5137480050325394
Epoch 64/100, Loss: 3.5873124822974205
Epoch 65/100, Loss: 3.362672232091427
Epoch 66/100, Loss: 3.531105153262615
Epoch 67/100, Loss: 3.339432343840599
Epoch 68/100, Loss: 3.28959359228611
Epoch 69/100, Loss: 3.180084355175495
Epoch 70/100, Loss: 3.461190938949585

Epoch 71/100, Loss: 3.470999114215374
Epoch 72/100, Loss: 3.3473282381892204
Epoch 73/100, Loss: 3.613589733839035
Epoch 74/100, Loss: 3.654939331114292
Epoch 75/100, Loss: 3.283198796212673
Epoch 76/100, Loss: 3.310753546655178
Epoch 77/100, Loss: 3.2403105944395065
Epoch 78/100, Loss: 3.767582669854164
Epoch 79/100, Loss: 3.538785181939602
Epoch 80/100, Loss: 3.412026457488537
Epoch 81/100, Loss: 3.129735343158245
Epoch 82/100, Loss: 3.710639640688896
Epoch 83/100, Loss: 3.2529244422912598
Epoch 84/100, Loss: 2.9564834907650948
Epoch 85/100, Loss: 3.089264892041683
Epoch 86/100, Loss: 3.110611267387867
Epoch 87/100, Loss: 3.212104693055153

Epoch 88/100, Loss: 3.436860628426075
Epoch 89/100, Loss: 3.479972682893276
Epoch 90/100, Loss: 3.4522053226828575
Epoch 91/100, Loss: 3.614791326224804
Epoch 92/100, Loss: 3.381525546312332
Epoch 93/100, Loss: 3.123803026974201
Epoch 94/100, Loss: 3.6284072026610374
Epoch 95/100, Loss: 3.068532906472683
Epoch 96/100, Loss: 3.52606413513422
Epoch 97/100, Loss: 3.1359659507870674
Epoch 98/100, Loss: 3.020221136510372
Epoch 99/100, Loss: 3.116516523063183
Epoch 100/100, Loss: 3.1402406319975853
Fold 1/5 done
Epoch 1/100, Loss: 3.4350351467728615
Epoch 2/100, Loss: 3.253151513636112

Epoch 3/100, Loss: 3.5397397577762604
Epoch 4/100, Loss: 3.1750624999403954
Epoch 5/100, Loss: 3.4988089725375175
Epoch 6/100, Loss: 3.5317022651433945
Epoch 7/100, Loss: 3.4189219921827316
Epoch 8/100, Loss: 3.0794519186019897
Epoch 9/100, Loss: 3.0395229682326317
Epoch 10/100, Loss: 3.3077856451272964
Epoch 11/100, Loss: 3.4782516211271286
Epoch 12/100, Loss: 2.944420300424099
Epoch 13/100, Loss: 2.969202511012554
Epoch 14/100, Loss: 3.5430470928549767
Epoch 15/100, Loss: 3.3465146496891975
Epoch 16/100, Loss: 3.2871209159493446
Epoch 17/100, Loss: 3.5553907305002213
Epoch 18/100, Loss: 3.31144430488348
Epoch 19/100, Loss: 3.372342936694622
Epoch 20/100, Loss: 3.309611812233925

Epoch 21/100, Loss: 3.8988342955708504
Epoch 22/100, Loss: 3.458843842148781
Epoch 23/100, Loss: 4.260585084557533
Epoch 24/100, Loss: 3.547931306064129
Epoch 25/100, Loss: 3.024084709584713
Epoch 26/100, Loss: 3.1490853503346443
Epoch 27/100, Loss: 3.1519227772951126
Epoch 28/100, Loss: 3.2819189950823784
Epoch 29/100, Loss: 3.640456922352314
Epoch 30/100, Loss: 3.382651999592781
Epoch 31/100, Loss: 3.6097017377614975
Epoch 32/100, Loss: 3.4470662102103233
Epoch 33/100, Loss: 3.1510049179196358
Epoch 34/100, Loss: 3.1659522727131844
Epoch 35/100, Loss: 3.5072908252477646

Epoch 36/100, Loss: 3.131414406001568
Epoch 37/100, Loss: 3.1889043897390366
Epoch 38/100, Loss: 3.7801525220274925
Epoch 39/100, Loss: 3.1762137189507484
Epoch 40/100, Loss: 3.675499066710472
Epoch 41/100, Loss: 3.0786530524492264
Epoch 42/100, Loss: 3.098149672150612
Epoch 43/100, Loss: 3.532229207456112
Epoch 44/100, Loss: 3.1272862404584885
Epoch 45/100, Loss: 3.177131600677967
Epoch 46/100, Loss: 3.3717044219374657
Epoch 47/100, Loss: 3.561548076570034
Epoch 48/100, Loss: 3.1615067198872566
Epoch 49/100, Loss: 3.3231136202812195
Epoch 50/100, Loss: 3.582325927913189
Epoch 51/100, Loss: 3.3501091301441193
Epoch 52/100, Loss: 3.0767029002308846

Epoch 53/100, Loss: 3.2981290221214294
Epoch 54/100, Loss: 3.144433081150055
Epoch 55/100, Loss: 3.3952454403042793
Epoch 56/100, Loss: 3.545714497566223
Epoch 57/100, Loss: 3.211292400956154
Epoch 58/100, Loss: 3.0180616825819016
Epoch 59/100, Loss: 3.3015753105282784
Epoch 60/100, Loss: 3.1580666080117226
Epoch 61/100, Loss: 3.3506077975034714
Epoch 62/100, Loss: 4.2212575152516365
Epoch 63/100, Loss: 3.3724346607923508
Epoch 64/100, Loss: 3.3531603887677193
Epoch 65/100, Loss: 3.3929812759160995
Epoch 66/100, Loss: 3.2556480765342712
Epoch 67/100, Loss: 3.3448276594281197
Epoch 68/100, Loss: 3.2110485658049583
Epoch 69/100, Loss: 3.4545419737696648
Epoch 70/100, Loss: 3.2683152556419373

Epoch 71/100, Loss: 3.4260119199752808
Epoch 72/100, Loss: 3.2045336589217186
Epoch 73/100, Loss: 3.4175891801714897
Epoch 74/100, Loss: 3.581826575100422
Epoch 75/100, Loss: 3.0695121735334396
Epoch 76/100, Loss: 3.196253575384617
Epoch 77/100, Loss: 3.010812647640705
Epoch 78/100, Loss: 3.1272078678011894
Epoch 79/100, Loss: 2.996679127216339
Epoch 80/100, Loss: 3.2338304296135902
Epoch 81/100, Loss: 3.4956468790769577
Epoch 82/100, Loss: 3.4096947237849236
Epoch 83/100, Loss: 3.400495357811451
Epoch 84/100, Loss: 3.4122894927859306
Epoch 85/100, Loss: 3.598291501402855
Epoch 86/100, Loss: 3.499720849096775
Epoch 87/100, Loss: 3.546942360699177

Epoch 88/100, Loss: 3.3191202208399773
Epoch 89/100, Loss: 3.0555966645479202
Epoch 90/100, Loss: 3.3487517312169075
Epoch 91/100, Loss: 2.9714212492108345
Epoch 92/100, Loss: 3.363935597240925
Epoch 93/100, Loss: 3.406395874917507
Epoch 94/100, Loss: 3.4670266434550285
Epoch 95/100, Loss: 3.3464721217751503
Epoch 96/100, Loss: 3.2483798190951347
Epoch 97/100, Loss: 4.088999152183533
Epoch 98/100, Loss: 3.5814936757087708
Epoch 99/100, Loss: 3.4248777255415916
Epoch 100/100, Loss: 3.4117091298103333
Fold 2/5 done
Epoch 1/100, Loss: 3.2703448832035065
Epoch 2/100, Loss: 3.3583658933639526
Epoch 3/100, Loss: 3.298217698931694

Epoch 4/100, Loss: 3.094472825527191
Epoch 5/100, Loss: 3.348888836801052
Epoch 6/100, Loss: 3.166817381978035
Epoch 7/100, Loss: 3.2583387792110443
Epoch 8/100, Loss: 3.1868086606264114
Epoch 9/100, Loss: 2.946555718779564
Epoch 10/100, Loss: 3.2377032786607742
Epoch 11/100, Loss: 3.186623841524124
Epoch 12/100, Loss: 3.0149794965982437
Epoch 13/100, Loss: 3.0059937983751297
Epoch 14/100, Loss: 2.92239061743021
Epoch 15/100, Loss: 3.0908015072345734

Epoch 16/100, Loss: 3.1523120552301407
Epoch 17/100, Loss: 3.298431694507599
Epoch 18/100, Loss: 3.040325626730919
Epoch 19/100, Loss: 3.046567291021347
Epoch 20/100, Loss: 3.0731792896986008
Epoch 21/100, Loss: 3.1016497015953064
Epoch 22/100, Loss: 3.1667065024375916
Epoch 23/100, Loss: 2.7565290182828903
Epoch 24/100, Loss: 3.277707099914551
Epoch 25/100, Loss: 2.9559508189558983
Epoch 26/100, Loss: 3.2420412600040436
Epoch 27/100, Loss: 3.2725322023034096
Epoch 28/100, Loss: 3.3920409083366394
Epoch 29/100, Loss: 2.9069556519389153
Epoch 30/100, Loss: 3.036189079284668
Epoch 31/100, Loss: 3.327293246984482
Epoch 32/100, Loss: 3.1335198283195496

Epoch 33/100, Loss: 3.172002360224724
Epoch 34/100, Loss: 2.9777584224939346
Epoch 35/100, Loss: 2.9769562482833862
Epoch 36/100, Loss: 3.2569083273410797
Epoch 37/100, Loss: 3.0578505396842957
Epoch 38/100, Loss: 3.2823599576950073
Epoch 39/100, Loss: 3.2244412899017334
Epoch 40/100, Loss: 3.0299061834812164
Epoch 41/100, Loss: 3.1653355956077576
Epoch 42/100, Loss: 3.1096426248550415
Epoch 43/100, Loss: 3.2885637879371643
Epoch 44/100, Loss: 3.0388823822140694
Epoch 45/100, Loss: 3.19372471421957
Epoch 46/100, Loss: 3.1104766279459
Epoch 47/100, Loss: 3.255959391593933
Epoch 48/100, Loss: 3.0789857506752014

Epoch 49/100, Loss: 3.1167775839567184
Epoch 50/100, Loss: 3.1499582082033157
Epoch 51/100, Loss: 3.1982186883687973
Epoch 52/100, Loss: 3.472606882452965
Epoch 53/100, Loss: 3.1768802255392075
Epoch 54/100, Loss: 3.148771047592163
Epoch 55/100, Loss: 3.13105471432209
Epoch 56/100, Loss: 3.017885982990265
Epoch 57/100, Loss: 3.226213276386261
Epoch 58/100, Loss: 3.021916851401329
Epoch 59/100, Loss: 3.1528966426849365
Epoch 60/100, Loss: 2.8378616273403168
Epoch 61/100, Loss: 3.0195817053318024
Epoch 62/100, Loss: 2.9130960404872894
Epoch 63/100, Loss: 2.912156820297241
Epoch 64/100, Loss: 3.1929598450660706

Epoch 65/100, Loss: 3.1882877498865128
Epoch 66/100, Loss: 3.138209745287895
Epoch 67/100, Loss: 3.0391703993082047
Epoch 68/100, Loss: 2.9928354024887085
Epoch 69/100, Loss: 2.9355151653289795
Epoch 70/100, Loss: 2.9605274200439453
Epoch 71/100, Loss: 2.952873542904854
Epoch 72/100, Loss: 3.030978851020336
Epoch 73/100, Loss: 3.731795147061348
Epoch 74/100, Loss: 3.1031577736139297
Epoch 75/100, Loss: 2.9907703027129173
Epoch 76/100, Loss: 3.126678094267845
Epoch 77/100, Loss: 3.3433594554662704
Epoch 78/100, Loss: 3.1043486297130585
Epoch 79/100, Loss: 3.0624840706586838
Epoch 80/100, Loss: 3.0006897151470184

Epoch 81/100, Loss: 2.9551103711128235
Epoch 82/100, Loss: 3.222685694694519
Epoch 83/100, Loss: 3.1406520530581474
Epoch 84/100, Loss: 3.066857300698757
Epoch 85/100, Loss: 3.1004349142313004
Epoch 86/100, Loss: 3.03126922249794
Epoch 87/100, Loss: 2.8744535222649574
Epoch 88/100, Loss: 3.0824482291936874
Epoch 89/100, Loss: 2.951770916581154
Epoch 90/100, Loss: 3.275956377387047
Epoch 91/100, Loss: 3.1682727485895157
Epoch 92/100, Loss: 2.894149050116539
Epoch 93/100, Loss: 3.225595138967037
Epoch 94/100, Loss: 3.0802185386419296
Epoch 95/100, Loss: 3.1886942461133003
Epoch 96/100, Loss: 3.048454985022545
Epoch 97/100, Loss: 3.1500377357006073

Epoch 98/100, Loss: 3.234658420085907
Epoch 99/100, Loss: 3.134654611349106
Epoch 100/100, Loss: 3.154142364859581
Fold 3/5 done
Epoch 1/100, Loss: 1.630980771034956
Epoch 2/100, Loss: 1.9402978122234344
Epoch 3/100, Loss: 1.8912904746830463
Epoch 4/100, Loss: 1.8231040835380554
Epoch 5/100, Loss: 1.8561196364462376
Epoch 6/100, Loss: 1.7852734290063381
Epoch 7/100, Loss: 1.6540012136101723
Epoch 8/100, Loss: 1.9935632720589638
Epoch 9/100, Loss: 1.9074416980147362
Epoch 10/100, Loss: 2.4964835792779922
Epoch 11/100, Loss: 1.8700434938073158
Epoch 12/100, Loss: 1.9895519763231277
Epoch 13/100, Loss: 1.8740842565894127

Epoch 14/100, Loss: 1.8897779695689678
Epoch 15/100, Loss: 1.8330212458968163
Epoch 16/100, Loss: 1.6462813764810562
Epoch 17/100, Loss: 1.941219538450241
Epoch 18/100, Loss: 1.628522515296936
Epoch 19/100, Loss: 1.5974431075155735
Epoch 20/100, Loss: 1.9850080609321594
Epoch 21/100, Loss: 1.87321050837636
Epoch 22/100, Loss: 1.9518265649676323
Epoch 23/100, Loss: 1.810825165361166
Epoch 24/100, Loss: 1.9441821202635765
Epoch 25/100, Loss: 1.686856146901846
Epoch 26/100, Loss: 1.8751593455672264
Epoch 27/100, Loss: 1.6597106903791428
Epoch 28/100, Loss: 1.6825678572058678
Epoch 29/100, Loss: 1.9495183825492859
Epoch 30/100, Loss: 1.8209495171904564
Epoch 31/100, Loss: 1.983756560832262

Epoch 32/100, Loss: 1.9020419605076313
Epoch 33/100, Loss: 1.8894541151821613
Epoch 34/100, Loss: 1.877826675772667
Epoch 35/100, Loss: 1.6285448484122753
Epoch 36/100, Loss: 1.7364161387085915
Epoch 37/100, Loss: 1.7838600277900696
Epoch 38/100, Loss: 1.8988286219537258
Epoch 39/100, Loss: 1.8059612140059471
Epoch 40/100, Loss: 2.4650006145238876
Epoch 41/100, Loss: 1.8155646175146103
Epoch 42/100, Loss: 2.028020143508911
Epoch 43/100, Loss: 1.8139730095863342
Epoch 44/100, Loss: 1.9290627986192703
Epoch 45/100, Loss: 1.514715526252985
Epoch 46/100, Loss: 1.8903898485004902
Epoch 47/100, Loss: 1.9655151404440403
Epoch 48/100, Loss: 1.6853130012750626
Epoch 49/100, Loss: 1.7912267968058586

Epoch 50/100, Loss: 1.8928181044757366
Epoch 51/100, Loss: 1.7914958819746971
Epoch 52/100, Loss: 1.8178060501813889
Epoch 53/100, Loss: 2.2469253167510033
Epoch 54/100, Loss: 1.8897282592952251
Epoch 55/100, Loss: 1.7033702954649925
Epoch 56/100, Loss: 1.9490469619631767
Epoch 57/100, Loss: 2.237479977309704
Epoch 58/100, Loss: 2.0981427654623985
Epoch 59/100, Loss: 2.114274062216282
Epoch 60/100, Loss: 1.6490386612713337
Epoch 61/100, Loss: 2.281573861837387
Epoch 62/100, Loss: 1.9070037081837654
Epoch 63/100, Loss: 1.7457220405340195
Epoch 64/100, Loss: 1.7986476346850395
Epoch 65/100, Loss: 2.0066611729562283
Epoch 66/100, Loss: 1.882479052990675

Epoch 67/100, Loss: 1.8400545716285706
Epoch 68/100, Loss: 1.755655761808157
Epoch 69/100, Loss: 1.7306276485323906
Epoch 70/100, Loss: 1.9262819066643715
Epoch 71/100, Loss: 1.9337255544960499
Epoch 72/100, Loss: 1.7823657840490341
Epoch 73/100, Loss: 1.684789463877678
Epoch 74/100, Loss: 1.917160652577877
Epoch 75/100, Loss: 1.9877424389123917
Epoch 76/100, Loss: 1.589595515280962
Epoch 77/100, Loss: 1.860073335468769
Epoch 78/100, Loss: 1.7478746250271797
Epoch 79/100, Loss: 1.9787084683775902
Epoch 80/100, Loss: 1.773933868855238
Epoch 81/100, Loss: 1.95100087672472
Epoch 82/100, Loss: 1.7862896174192429

Epoch 83/100, Loss: 1.825192578136921
Epoch 84/100, Loss: 1.8688213974237442
Epoch 85/100, Loss: 1.9215255305171013
Epoch 86/100, Loss: 2.093508217483759
Epoch 87/100, Loss: 1.8776977881789207
Epoch 88/100, Loss: 2.012734740972519
Epoch 89/100, Loss: 1.9141338467597961
Epoch 90/100, Loss: 1.9085785821080208
Epoch 91/100, Loss: 1.8769825622439384
Epoch 92/100, Loss: 1.9649791307747364
Epoch 93/100, Loss: 1.9499088451266289
Epoch 94/100, Loss: 2.166022427380085
Epoch 95/100, Loss: 1.8255429826676846
Epoch 96/100, Loss: 1.6605016216635704
Epoch 97/100, Loss: 1.7693874463438988
Epoch 98/100, Loss: 1.9327800273895264
Epoch 99/100, Loss: 1.910774800926447

Epoch 100/100, Loss: 1.8372120186686516
Fold 4/5 done
Epoch 1/100, Loss: 1.952946200966835
Epoch 2/100, Loss: 1.9363941848278046
Epoch 3/100, Loss: 1.9080401584506035
Epoch 4/100, Loss: 2.054859347641468
Epoch 5/100, Loss: 1.9608598500490189
Epoch 6/100, Loss: 1.8989386409521103
Epoch 7/100, Loss: 2.08512382209301
Epoch 8/100, Loss: 1.998252384364605
Epoch 9/100, Loss: 1.876833327114582
Epoch 10/100, Loss: 1.9738464877009392
Epoch 11/100, Loss: 2.0375447645783424
Epoch 12/100, Loss: 2.020904019474983
Epoch 13/100, Loss: 1.9934610426425934
Epoch 14/100, Loss: 2.0056429728865623

Epoch 15/100, Loss: 1.96946220099926
Epoch 16/100, Loss: 1.954966478049755
Epoch 17/100, Loss: 2.066236026585102
Epoch 18/100, Loss: 1.9421352073550224
Epoch 19/100, Loss: 1.8962170779705048
Epoch 20/100, Loss: 1.9801665395498276
Epoch 21/100, Loss: 2.0155769661068916
Epoch 22/100, Loss: 1.9391374215483665
Epoch 23/100, Loss: 1.9339938759803772
Epoch 24/100, Loss: 1.947157584130764
Epoch 25/100, Loss: 1.9793902784585953
Epoch 26/100, Loss: 2.0159060955047607
Epoch 27/100, Loss: 1.8948350250720978
Epoch 28/100, Loss: 1.9840438216924667
Epoch 29/100, Loss: 2.010784365236759

Epoch 30/100, Loss: 2.0040870308876038
Epoch 31/100, Loss: 2.0013138577342033
Epoch 32/100, Loss: 2.020134150981903
Epoch 33/100, Loss: 1.968207836151123
Epoch 34/100, Loss: 2.005934461951256
Epoch 35/100, Loss: 1.9408423751592636
Epoch 36/100, Loss: 1.9378948211669922
Epoch 37/100, Loss: 1.9995232298970222
Epoch 38/100, Loss: 2.0767873004078865
Epoch 39/100, Loss: 2.0712301209568977
Epoch 40/100, Loss: 1.9418208301067352
Epoch 41/100, Loss: 2.0159241184592247
Epoch 42/100, Loss: 1.9375062957406044
Epoch 43/100, Loss: 1.9616874232888222
Epoch 44/100, Loss: 2.2624702900648117
Epoch 45/100, Loss: 1.9615385830402374

Epoch 46/100, Loss: 2.0463357493281364
Epoch 47/100, Loss: 2.021151728928089
Epoch 48/100, Loss: 2.0300913751125336
Epoch 49/100, Loss: 1.953770138323307
Epoch 50/100, Loss: 2.005867585539818
Epoch 51/100, Loss: 2.132169984281063
Epoch 52/100, Loss: 1.9421334639191628
Epoch 53/100, Loss: 1.9314763247966766
Epoch 54/100, Loss: 1.9872559905052185
Epoch 55/100, Loss: 2.090036928653717
Epoch 56/100, Loss: 1.9254038482904434
Epoch 57/100, Loss: 1.9145777598023415
Epoch 58/100, Loss: 1.9764912948012352
Epoch 59/100, Loss: 1.9225260019302368
Epoch 60/100, Loss: 1.9930684119462967
Epoch 61/100, Loss: 1.9785223230719566
Epoch 62/100, Loss: 2.153491973876953

Epoch 63/100, Loss: 2.1413977295160294
Epoch 64/100, Loss: 1.975173905491829
Epoch 65/100, Loss: 1.9341546893119812
Epoch 66/100, Loss: 2.0437394604086876
Epoch 67/100, Loss: 2.1116612628102303
Epoch 68/100, Loss: 2.036270745098591
Epoch 69/100, Loss: 1.9741676226258278
Epoch 70/100, Loss: 1.8991370648145676
Epoch 71/100, Loss: 1.9943536594510078
Epoch 72/100, Loss: 2.031346894800663
Epoch 73/100, Loss: 2.009469397366047
Epoch 74/100, Loss: 1.955900028347969
Epoch 75/100, Loss: 1.9927426800131798
Epoch 76/100, Loss: 2.1703555434942245
Epoch 77/100, Loss: 2.0413437709212303

Epoch 78/100, Loss: 2.002725824713707
Epoch 79/100, Loss: 2.052963376045227
Epoch 80/100, Loss: 2.0422235652804375
Epoch 81/100, Loss: 2.036149024963379
Epoch 82/100, Loss: 1.964496023952961
Epoch 83/100, Loss: 1.8979908898472786
Epoch 84/100, Loss: 2.024006024003029
Epoch 85/100, Loss: 1.9163884073495865
Epoch 86/100, Loss: 1.927446387708187
Epoch 87/100, Loss: 2.044370822608471
Epoch 88/100, Loss: 2.020404174923897
Epoch 89/100, Loss: 2.00876072794199
Epoch 90/100, Loss: 1.9506068155169487
Epoch 91/100, Loss: 2.069646269083023
Epoch 92/100, Loss: 1.9397407844662666

Epoch 93/100, Loss: 2.176242917776108
Epoch 94/100, Loss: 1.9726872369647026
Epoch 95/100, Loss: 2.0470929369330406
Epoch 96/100, Loss: 1.9964414089918137
Epoch 97/100, Loss: 2.018549233675003
Epoch 98/100, Loss: 2.02573125064373
Epoch 99/100, Loss: 2.059466354548931
Epoch 100/100, Loss: 1.9373375251889229
Fold 5/5 done

In [11]:
ap = average_precision_score(y_true, anomaly_scores)
print(f"Deep SVDD AP (5-fold CV) = {ap:.4f}")
sb.glue("GBG500_ap_spectral_deep_svdd", float(ap))

Deep SVDD AP (5-fold CV) = 0.6816