In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import average_precision_score
from sklearn.model_selection import StratifiedKFold
from pyod.models.deep_svdd import DeepSVDD
import sys
import scrapbook as sb

sys.path.append('..')
from utils import reshape_to_numpy, interpolate_missing_values, denoise_data, compute_spectrograms, time_avg_pooling

In [2]:
seed = 1
sampling_rate = 10
nperseg=64
noverlap=32
accel_cutoff = 0.4
accel_order = 30
gyro_cutoff = 0.6
gyro_order = 20
batch_size = 32
epochs = 100
hidden_neurons = [128, 64, 32]
n_splits = 5

In [3]:
# Parameters
seed = 12

In [4]:
rng = np.random.RandomState(seed)

In [5]:
data = pd.read_parquet("../data/GBG500.parquet")
data

,ride_id,time_index,ax,ay,az,rx,ry,rz
0,005043f1a7520cebf1e17fd166a00a3190e2433530f236...,0,-2.512796,-9.385012,-1.053078,-0.009155,0.009155,-0.201416
1,005043f1a7520cebf1e17fd166a00a3190e2433530f236...,100,-2.491268,-9.385012,-1.079390,-0.036621,0.027465,-0.155639
2,005043f1a7520cebf1e17fd166a00a3190e2433530f236...,200,-2.534324,-9.382022,-1.030952,0.036621,0.027465,-0.073242
3,005043f1a7520cebf1e17fd166a00a3190e2433530f236...,300,-2.488278,-9.383218,-1.091948,-0.045776,0.036621,-0.183105
4,005043f1a7520cebf1e17fd166a00a3190e2433530f236...,400,-2.483494,-9.382022,-1.100320,-0.045776,0.027465,-0.192260
...,...,...,...,...,...,...,...,...
1529542,ffb6f2f5dc6ba768d88dc0bc1af4cad235526aa9e24168...,241300,0.459862,-9.140430,-3.318900,1.556396,-0.091552,0.274658
1529543,ffb6f2f5dc6ba768d88dc0bc1af4cad235526aa9e24168...,241400,0.455676,-9.140430,-3.321292,1.583861,-0.119018,0.274658
1529544,ffb6f2f5dc6ba768d88dc0bc1af4cad235526aa9e24168...,241500,0.459862,-9.139832,-3.317704,1.583861,-0.109863,0.274658
1529545,ffb6f2f5dc6ba768d88dc0bc1af4cad235526aa9e24168...,241600,0.456274,-9.142224,-3.321292,1.574707,-0.137329,0.283813
1529546,ffb6f2f5dc6ba768d88dc0bc1af4cad235526aa9e24168...,241700,0.458666,-9.139832,-3.320694,1.574707,-0.137329,0.274658

In [6]:
labels = pd.read_csv("../data/GBG500_labels.csv")
labels.columns = labels.columns.str.lower()
ride_order_df = pd.DataFrame({"ride_id": data["ride_id"].unique()})
labels_sorted = ride_order_df.merge(
    labels,
    on="ride_id",
    how="left"
)
labels_sorted

                                               ride_id        label
0    005043f1a7520cebf1e17fd166a00a3190e2433530f236...         Safe
1    00d223cb7aecc9c0cc5871e32a6c45027a068eba07c572...     Reckless
2    02288a4aeca044203394e982e76b87818021dea2b34df9...         Safe
3    0236bdcf13d473ea24d97f5eaeea459f257dffac005694...  Bad weather
4    0238e5dd85143f1b6c59b200bc32f14361b8fc84c51a87...         Safe
..                                                 ...          ...
495  fe5d7f84d692bbccad8bd566a3ad5c3108fa9f90acd671...         Safe
496  fe67169632306d4668b2affedef510df2cb43e2fb41220...         Safe
497  fee44667fdc8ab4995c702fc3bd36178de0b1ca2c64687...         Safe
498  ff79b2e945b93c2a5efc3a06365267b3a160e7849ba57d...         Safe
499  ffb6f2f5dc6ba768d88dc0bc1af4cad235526aa9e24168...         Safe

[500 rows x 2 columns]

In [7]:
data_np = reshape_to_numpy(
    data,
    features = ["ax", "ay", "az", "rx", "ry", "rz"],
    max_timestamps = 4800
)

data_np_clean = interpolate_missing_values(
    data_np,
    method='linear',
    limit=None
)

data_np_clean = denoise_data(
    data=data_np_clean,
    accel_indices=[0, 1, 2],
    gyro_indices=[3, 4, 5],
    accel_cutoff=accel_cutoff,
    accel_order=accel_order,
    gyro_cutoff=gyro_cutoff,
    gyro_order=gyro_order,
)

In [8]:
# Compute spectrograms for all rides
spectrograms_array = compute_spectrograms(data_np_clean, sampling_rate, nperseg, noverlap)
spectrograms_array.shape

(500, 149, 6, 33)

In [9]:
# Aggregate spectrograms using time-averaged pooling
X_feat = time_avg_pooling(spectrograms_array)
X_feat.shape

(500, 198)

In [10]:
# 5-fold stratified CV with Deep SVDD
skf = StratifiedKFold(n_splits=n_splits, shuffle=True, random_state=rng.randint(1000))
y_true = (labels_sorted['label'] == 'Reckless').astype(int).values
anomaly_scores = np.full(len(y_true), np.nan)

for fold, (train_idx, test_idx) in enumerate(skf.split(X_feat, y_true)):
    sc = StandardScaler()
    X_train = sc.fit_transform(X_feat[train_idx])
    X_test = sc.transform(X_feat[test_idx])

    np.random.seed(rng.randint(1000))
    model = DeepSVDD(
        n_features=X_train.shape[1],
        hidden_neurons=hidden_neurons,
        epochs=epochs,
        batch_size=batch_size,
        random_state=rng.randint(1000),
    )
    model.fit(X_train)
    anomaly_scores[test_idx] = model.decision_function(X_test)
    print(f"Fold {fold+1}/{n_splits} done")

Epoch 1/100, Loss: 2.868295282125473
Epoch 2/100, Loss: 2.810212306678295
Epoch 3/100, Loss: 2.549817107617855
Epoch 4/100, Loss: 2.8106565177440643
Epoch 5/100, Loss: 2.7606869488954544
Epoch 6/100, Loss: 2.8119011372327805
Epoch 7/100, Loss: 2.6536411494016647
Epoch 8/100, Loss: 2.844179183244705
Epoch 9/100, Loss: 2.7065969109535217
Epoch 10/100, Loss: 2.7378532215952873
Epoch 11/100, Loss: 2.7636166140437126
Epoch 12/100, Loss: 2.9095917493104935
Epoch 13/100, Loss: 2.7244213297963142
Epoch 14/100, Loss: 2.880185216665268
Epoch 15/100, Loss: 2.5719250068068504

Epoch 16/100, Loss: 3.000906892120838
Epoch 17/100, Loss: 2.828748159110546
Epoch 18/100, Loss: 2.695861093699932
Epoch 19/100, Loss: 2.735436387360096
Epoch 20/100, Loss: 2.537631541490555
Epoch 21/100, Loss: 2.720295250415802
Epoch 22/100, Loss: 2.7159406542778015
Epoch 23/100, Loss: 2.7967401295900345
Epoch 24/100, Loss: 2.760750725865364
Epoch 25/100, Loss: 2.6472487673163414
Epoch 26/100, Loss: 2.671936795115471
Epoch 27/100, Loss: 2.6805568486452103
Epoch 28/100, Loss: 2.832126021385193
Epoch 29/100, Loss: 2.765418477356434
Epoch 30/100, Loss: 2.683061070740223

Epoch 31/100, Loss: 2.770990289747715
Epoch 32/100, Loss: 2.790893390774727
Epoch 33/100, Loss: 2.6865833774209023
Epoch 34/100, Loss: 2.7991332188248634
Epoch 35/100, Loss: 2.4492948576807976
Epoch 36/100, Loss: 2.557679757475853
Epoch 37/100, Loss: 2.8704196959733963
Epoch 38/100, Loss: 2.574683979153633
Epoch 39/100, Loss: 2.8233013451099396
Epoch 40/100, Loss: 2.6877714321017265
Epoch 41/100, Loss: 2.721966430544853
Epoch 42/100, Loss: 3.168629303574562
Epoch 43/100, Loss: 2.6732936203479767
Epoch 44/100, Loss: 2.5892612114548683

Epoch 45/100, Loss: 2.9001322463154793
Epoch 46/100, Loss: 2.6871967390179634
Epoch 47/100, Loss: 2.7428493201732635
Epoch 48/100, Loss: 2.9938071593642235
Epoch 49/100, Loss: 2.712011367082596
Epoch 50/100, Loss: 2.8108650743961334
Epoch 51/100, Loss: 2.860709309577942
Epoch 52/100, Loss: 2.7531924098730087
Epoch 53/100, Loss: 2.938736580312252
Epoch 54/100, Loss: 2.5878573954105377
Epoch 55/100, Loss: 2.9121720641851425
Epoch 56/100, Loss: 2.7917828112840652
Epoch 57/100, Loss: 2.9532700330018997
Epoch 58/100, Loss: 2.7115465328097343
Epoch 59/100, Loss: 2.735603727400303
Epoch 60/100, Loss: 2.6428380385041237

Epoch 61/100, Loss: 2.6677844747900963
Epoch 62/100, Loss: 2.680356189608574
Epoch 63/100, Loss: 2.6682445034384727
Epoch 64/100, Loss: 2.869970865547657
Epoch 65/100, Loss: 2.6211285293102264
Epoch 66/100, Loss: 3.43291637301445
Epoch 67/100, Loss: 2.684326581656933
Epoch 68/100, Loss: 2.843555100262165
Epoch 69/100, Loss: 2.6174879893660545
Epoch 70/100, Loss: 2.770047627389431
Epoch 71/100, Loss: 3.220469683408737
Epoch 72/100, Loss: 2.695634037256241
Epoch 73/100, Loss: 2.768889605998993
Epoch 74/100, Loss: 3.196025565266609
Epoch 75/100, Loss: 2.7289060950279236
Epoch 76/100, Loss: 2.8148601725697517
Epoch 77/100, Loss: 2.8472036868333817

Epoch 78/100, Loss: 3.033627189695835
Epoch 79/100, Loss: 2.9930025935173035
Epoch 80/100, Loss: 2.8057741224765778
Epoch 81/100, Loss: 2.764728993177414
Epoch 82/100, Loss: 3.0104208514094353
Epoch 83/100, Loss: 2.808173965662718
Epoch 84/100, Loss: 2.7574137523770332
Epoch 85/100, Loss: 2.8104941695928574
Epoch 86/100, Loss: 3.016521744430065
Epoch 87/100, Loss: 2.8576231598854065
Epoch 88/100, Loss: 2.903937816619873
Epoch 89/100, Loss: 2.550646051764488

Epoch 90/100, Loss: 2.770649716258049
Epoch 91/100, Loss: 2.4785241037607193
Epoch 92/100, Loss: 2.773074448108673
Epoch 93/100, Loss: 2.7977601811289787
Epoch 94/100, Loss: 2.777910500764847
Epoch 95/100, Loss: 2.9285640195012093
Epoch 96/100, Loss: 2.666125439107418
Epoch 97/100, Loss: 2.840301990509033
Epoch 98/100, Loss: 2.621513918042183
Epoch 99/100, Loss: 2.6957773119211197
Epoch 100/100, Loss: 2.9449494257569313
Fold 1/5 done
Epoch 1/100, Loss: 1.4804705753922462
Epoch 2/100, Loss: 1.3967373818159103
Epoch 3/100, Loss: 1.4820057973265648
Epoch 4/100, Loss: 1.3761701956391335
Epoch 5/100, Loss: 1.505494236946106

Epoch 6/100, Loss: 1.4187699928879738
Epoch 7/100, Loss: 1.4101721569895744
Epoch 8/100, Loss: 1.4777866378426552
Epoch 9/100, Loss: 1.4635791927576065
Epoch 10/100, Loss: 1.6540138646960258
Epoch 11/100, Loss: 1.4594140648841858
Epoch 12/100, Loss: 1.4158683568239212
Epoch 13/100, Loss: 1.3733704015612602
Epoch 14/100, Loss: 1.4019471257925034
Epoch 15/100, Loss: 1.528738096356392
Epoch 16/100, Loss: 1.4442949704825878
Epoch 17/100, Loss: 1.3969531506299973
Epoch 18/100, Loss: 1.4028543084859848
Epoch 19/100, Loss: 1.4081019908189774
Epoch 20/100, Loss: 1.4596712291240692
Epoch 21/100, Loss: 1.488282449543476
Epoch 22/100, Loss: 1.480271652340889
Epoch 23/100, Loss: 1.4155668318271637

Epoch 24/100, Loss: 1.3712685406208038
Epoch 25/100, Loss: 1.3512664139270782
Epoch 26/100, Loss: 1.365247868001461
Epoch 27/100, Loss: 1.4827957823872566
Epoch 28/100, Loss: 1.4615492820739746
Epoch 29/100, Loss: 1.4094841033220291
Epoch 30/100, Loss: 1.3986615687608719
Epoch 31/100, Loss: 1.4046508744359016
Epoch 32/100, Loss: 1.4264035448431969
Epoch 33/100, Loss: 1.399093821644783
Epoch 34/100, Loss: 1.4096559584140778
Epoch 35/100, Loss: 1.4593024179339409
Epoch 36/100, Loss: 1.4226822257041931
Epoch 37/100, Loss: 1.453008271753788
Epoch 38/100, Loss: 1.3501745015382767
Epoch 39/100, Loss: 1.4186242893338203
Epoch 40/100, Loss: 1.3887089043855667

Epoch 41/100, Loss: 1.3620708584785461
Epoch 42/100, Loss: 1.5364051014184952
Epoch 43/100, Loss: 1.4240257665514946
Epoch 44/100, Loss: 1.4696424007415771
Epoch 45/100, Loss: 1.410426452755928
Epoch 46/100, Loss: 1.4223165810108185
Epoch 47/100, Loss: 1.412269450724125
Epoch 48/100, Loss: 1.4154630303382874
Epoch 49/100, Loss: 1.3971042484045029
Epoch 50/100, Loss: 1.4452449679374695
Epoch 51/100, Loss: 1.4299254342913628
Epoch 52/100, Loss: 1.387457437813282
Epoch 53/100, Loss: 1.4458787068724632
Epoch 54/100, Loss: 1.4195175170898438
Epoch 55/100, Loss: 1.427042841911316
Epoch 56/100, Loss: 1.421636737883091
Epoch 57/100, Loss: 1.3961657471954823
Epoch 58/100, Loss: 1.4458182603120804

Epoch 59/100, Loss: 1.4782016202807426
Epoch 60/100, Loss: 1.424085333943367
Epoch 61/100, Loss: 1.5313378870487213
Epoch 62/100, Loss: 1.5202839151024818
Epoch 63/100, Loss: 1.4504593312740326
Epoch 64/100, Loss: 1.4050633013248444
Epoch 65/100, Loss: 1.4414472058415413
Epoch 66/100, Loss: 1.3695787712931633
Epoch 67/100, Loss: 1.4890205711126328
Epoch 68/100, Loss: 1.3674143999814987
Epoch 69/100, Loss: 1.416506178677082
Epoch 70/100, Loss: 1.4948459826409817
Epoch 71/100, Loss: 1.4484342336654663
Epoch 72/100, Loss: 1.4183094948530197
Epoch 73/100, Loss: 1.5000545978546143
Epoch 74/100, Loss: 1.435991331934929
Epoch 75/100, Loss: 1.4511500522494316

Epoch 76/100, Loss: 1.4450998231768608
Epoch 77/100, Loss: 1.466579057276249
Epoch 78/100, Loss: 1.4014433845877647
Epoch 79/100, Loss: 1.4157955050468445
Epoch 80/100, Loss: 1.3925140127539635
Epoch 81/100, Loss: 1.4390220493078232
Epoch 82/100, Loss: 1.4825897440314293
Epoch 83/100, Loss: 1.3616043105721474
Epoch 84/100, Loss: 1.339501567184925
Epoch 85/100, Loss: 1.4397972896695137
Epoch 86/100, Loss: 1.4069574065506458
Epoch 87/100, Loss: 1.3890336453914642
Epoch 88/100, Loss: 1.4022055640816689
Epoch 89/100, Loss: 1.3541425541043282
Epoch 90/100, Loss: 1.3830934837460518
Epoch 91/100, Loss: 1.486153982579708
Epoch 92/100, Loss: 1.4448168985545635

Epoch 93/100, Loss: 1.4465315416455269
Epoch 94/100, Loss: 1.4181163385510445
Epoch 95/100, Loss: 1.3937836661934853
Epoch 96/100, Loss: 1.3971647769212723
Epoch 97/100, Loss: 1.4182935431599617
Epoch 98/100, Loss: 1.392623782157898
Epoch 99/100, Loss: 1.384171411395073
Epoch 100/100, Loss: 1.4002321138978004
Fold 2/5 done
Epoch 1/100, Loss: 2.4269637018442154
Epoch 2/100, Loss: 2.5065395310521126
Epoch 3/100, Loss: 2.4620255529880524
Epoch 4/100, Loss: 2.6479736268520355
Epoch 5/100, Loss: 2.349919021129608
Epoch 6/100, Loss: 2.453870043158531

Epoch 7/100, Loss: 2.6683086454868317
Epoch 8/100, Loss: 2.564456306397915
Epoch 9/100, Loss: 2.238927163183689
Epoch 10/100, Loss: 2.45428329333663
Epoch 11/100, Loss: 2.5477729737758636
Epoch 12/100, Loss: 2.319285310804844
Epoch 13/100, Loss: 2.618519753217697
Epoch 14/100, Loss: 2.2517818734049797
Epoch 15/100, Loss: 2.4745393618941307
Epoch 16/100, Loss: 2.6304135397076607
Epoch 17/100, Loss: 2.4746748581528664
Epoch 18/100, Loss: 2.532403253018856
Epoch 19/100, Loss: 2.2975064292550087
Epoch 20/100, Loss: 2.4490982592105865
Epoch 21/100, Loss: 2.3378292992711067
Epoch 22/100, Loss: 2.182179182767868
Epoch 23/100, Loss: 2.291288159787655

Epoch 24/100, Loss: 2.3412659019231796
Epoch 25/100, Loss: 2.464138299226761
Epoch 26/100, Loss: 2.506597824394703
Epoch 27/100, Loss: 2.185497745871544
Epoch 28/100, Loss: 2.4271588176488876
Epoch 29/100, Loss: 2.463053621351719
Epoch 30/100, Loss: 2.3600020855665207
Epoch 31/100, Loss: 2.562846824526787
Epoch 32/100, Loss: 2.423353910446167
Epoch 33/100, Loss: 2.3908117450773716
Epoch 34/100, Loss: 2.4139209166169167
Epoch 35/100, Loss: 2.570372112095356
Epoch 36/100, Loss: 2.4099068343639374
Epoch 37/100, Loss: 2.5306225419044495
Epoch 38/100, Loss: 2.5364181362092495

Epoch 39/100, Loss: 2.4934966787695885
Epoch 40/100, Loss: 2.549198430031538
Epoch 41/100, Loss: 2.3714671842753887
Epoch 42/100, Loss: 2.447009578347206
Epoch 43/100, Loss: 2.3887118324637413
Epoch 44/100, Loss: 2.2492879405617714
Epoch 45/100, Loss: 2.726449228823185
Epoch 46/100, Loss: 2.386213593184948
Epoch 47/100, Loss: 2.2333602383732796
Epoch 48/100, Loss: 2.511722832918167
Epoch 49/100, Loss: 2.47590072453022
Epoch 50/100, Loss: 2.4046426713466644
Epoch 51/100, Loss: 3.148896671831608
Epoch 52/100, Loss: 3.0122838094830513
Epoch 53/100, Loss: 2.4485264718532562

Epoch 54/100, Loss: 2.492363065481186
Epoch 55/100, Loss: 2.6160698756575584
Epoch 56/100, Loss: 2.410732187330723
Epoch 57/100, Loss: 2.537420280277729
Epoch 58/100, Loss: 2.4766664281487465
Epoch 59/100, Loss: 2.5568805560469627
Epoch 60/100, Loss: 2.329093836247921
Epoch 61/100, Loss: 2.3563443049788475
Epoch 62/100, Loss: 2.4250710755586624
Epoch 63/100, Loss: 2.368613138794899
Epoch 64/100, Loss: 3.110792137682438
Epoch 65/100, Loss: 2.610288254916668
Epoch 66/100, Loss: 2.31736096739769
Epoch 67/100, Loss: 2.4828590899705887
Epoch 68/100, Loss: 2.6559520214796066

Epoch 69/100, Loss: 2.27370435744524
Epoch 70/100, Loss: 2.570035520941019
Epoch 71/100, Loss: 2.539510227739811
Epoch 72/100, Loss: 2.3800926581025124
Epoch 73/100, Loss: 2.671858161687851
Epoch 74/100, Loss: 2.477456219494343
Epoch 75/100, Loss: 2.7330637499690056
Epoch 76/100, Loss: 2.3827099800109863
Epoch 77/100, Loss: 2.4789453893899918
Epoch 78/100, Loss: 2.586564339697361
Epoch 79/100, Loss: 2.448209799826145
Epoch 80/100, Loss: 2.2764749825000763
Epoch 81/100, Loss: 2.5904147773981094
Epoch 82/100, Loss: 2.459143377840519
Epoch 83/100, Loss: 2.6419144980609417

Epoch 84/100, Loss: 2.5386654660105705
Epoch 85/100, Loss: 2.3795617520809174
Epoch 86/100, Loss: 2.417401358485222
Epoch 87/100, Loss: 2.313219465315342
Epoch 88/100, Loss: 2.587329275906086
Epoch 89/100, Loss: 2.5494548827409744
Epoch 90/100, Loss: 2.7269797548651695
Epoch 91/100, Loss: 2.8224830850958824
Epoch 92/100, Loss: 2.3832545429468155
Epoch 93/100, Loss: 2.66781597211957
Epoch 94/100, Loss: 2.4545909464359283
Epoch 95/100, Loss: 2.441520970314741
Epoch 96/100, Loss: 2.46069947630167
Epoch 97/100, Loss: 2.4000802747905254
Epoch 98/100, Loss: 2.533632405102253
Epoch 99/100, Loss: 2.325062222778797

Epoch 100/100, Loss: 2.632860541343689
Fold 3/5 done
Epoch 1/100, Loss: 2.038079835474491
Epoch 2/100, Loss: 1.9371570944786072
Epoch 3/100, Loss: 2.1561575829982758
Epoch 4/100, Loss: 2.1544058322906494
Epoch 5/100, Loss: 2.162366434931755
Epoch 6/100, Loss: 2.2147346884012222
Epoch 7/100, Loss: 2.1212565153837204
Epoch 8/100, Loss: 2.179685816168785
Epoch 9/100, Loss: 2.006131537258625
Epoch 10/100, Loss: 2.1354477256536484
Epoch 11/100, Loss: 2.060925208032131
Epoch 12/100, Loss: 2.162883296608925
Epoch 13/100, Loss: 2.1153643131256104
Epoch 14/100, Loss: 2.028731048107147

Epoch 15/100, Loss: 2.195542596280575
Epoch 16/100, Loss: 2.0973590165376663
Epoch 17/100, Loss: 2.1011031046509743
Epoch 18/100, Loss: 2.0581199526786804
Epoch 19/100, Loss: 2.1251408606767654
Epoch 20/100, Loss: 2.2111218720674515
Epoch 21/100, Loss: 2.090075336396694
Epoch 22/100, Loss: 2.039076156914234
Epoch 23/100, Loss: 2.198586568236351
Epoch 24/100, Loss: 2.2432320192456245
Epoch 25/100, Loss: 2.0332734137773514
Epoch 26/100, Loss: 2.101417414844036
Epoch 27/100, Loss: 2.134056940674782
Epoch 28/100, Loss: 2.238445244729519
Epoch 29/100, Loss: 2.01100667566061

Epoch 30/100, Loss: 2.184162013232708
Epoch 31/100, Loss: 2.0777955129742622
Epoch 32/100, Loss: 2.1771460324525833
Epoch 33/100, Loss: 2.106801673769951
Epoch 34/100, Loss: 2.139738440513611
Epoch 35/100, Loss: 2.165684849023819
Epoch 36/100, Loss: 2.0795313715934753
Epoch 37/100, Loss: 2.0798682123422623
Epoch 38/100, Loss: 2.099911667406559
Epoch 39/100, Loss: 2.0538129955530167
Epoch 40/100, Loss: 2.1013201773166656
Epoch 41/100, Loss: 2.212543547153473
Epoch 42/100, Loss: 2.022518366575241
Epoch 43/100, Loss: 2.2133234664797783
Epoch 44/100, Loss: 1.9745543748140335

Epoch 45/100, Loss: 2.0280627757310867
Epoch 46/100, Loss: 2.174768216907978
Epoch 47/100, Loss: 2.1486798375844955
Epoch 48/100, Loss: 2.0514126643538475
Epoch 49/100, Loss: 2.1404846869409084
Epoch 50/100, Loss: 2.1539259627461433
Epoch 51/100, Loss: 2.0635386630892754
Epoch 52/100, Loss: 2.0297537222504616
Epoch 53/100, Loss: 2.153729386627674
Epoch 54/100, Loss: 2.1616484969854355
Epoch 55/100, Loss: 2.0672828927636147
Epoch 56/100, Loss: 2.0656646490097046
Epoch 57/100, Loss: 2.0481218323111534
Epoch 58/100, Loss: 2.149734988808632
Epoch 59/100, Loss: 2.0714816972613335

Epoch 60/100, Loss: 2.221471942961216
Epoch 61/100, Loss: 2.124355874955654
Epoch 62/100, Loss: 2.129532240331173
Epoch 63/100, Loss: 2.0846503376960754
Epoch 64/100, Loss: 2.0756493136286736
Epoch 65/100, Loss: 2.162858970463276
Epoch 66/100, Loss: 2.1653675511479378
Epoch 67/100, Loss: 2.017292983829975
Epoch 68/100, Loss: 2.0389031022787094
Epoch 69/100, Loss: 2.061956577003002
Epoch 70/100, Loss: 2.1414865851402283
Epoch 71/100, Loss: 2.0882644280791283
Epoch 72/100, Loss: 2.0819483771920204
Epoch 73/100, Loss: 2.0501895546913147
Epoch 74/100, Loss: 2.214972324669361

Epoch 75/100, Loss: 2.0855228900909424
Epoch 76/100, Loss: 2.0993495285511017
Epoch 77/100, Loss: 2.0994042828679085
Epoch 78/100, Loss: 2.108284153044224
Epoch 79/100, Loss: 2.220123253762722
Epoch 80/100, Loss: 2.088297702372074
Epoch 81/100, Loss: 2.131370574235916
Epoch 82/100, Loss: 2.0327029898762703
Epoch 83/100, Loss: 2.346423402428627
Epoch 84/100, Loss: 2.044333189725876
Epoch 85/100, Loss: 2.0229251831769943
Epoch 86/100, Loss: 2.129872277379036
Epoch 87/100, Loss: 2.058361805975437
Epoch 88/100, Loss: 1.9978213123977184
Epoch 89/100, Loss: 1.9963266253471375

Epoch 90/100, Loss: 2.113840475678444
Epoch 91/100, Loss: 2.0928277745842934
Epoch 92/100, Loss: 2.1284145042300224
Epoch 93/100, Loss: 1.874434269964695
Epoch 94/100, Loss: 2.1331225857138634
Epoch 95/100, Loss: 2.078196235001087
Epoch 96/100, Loss: 1.925702191889286
Epoch 97/100, Loss: 2.119262009859085
Epoch 98/100, Loss: 2.038920760154724
Epoch 99/100, Loss: 2.081416606903076
Epoch 100/100, Loss: 2.1035051420331
Fold 4/5 done
Epoch 1/100, Loss: 2.1784374117851257
Epoch 2/100, Loss: 2.234023317694664
Epoch 3/100, Loss: 2.118538625538349
Epoch 4/100, Loss: 2.0712127089500427

Epoch 5/100, Loss: 2.2548162564635277
Epoch 6/100, Loss: 2.2848786786198616
Epoch 7/100, Loss: 2.054518736898899
Epoch 8/100, Loss: 2.0239804424345493
Epoch 9/100, Loss: 2.0495287030935287
Epoch 10/100, Loss: 2.2896263897418976
Epoch 11/100, Loss: 1.91208915412426
Epoch 12/100, Loss: 2.6089299023151398
Epoch 13/100, Loss: 2.1424869522452354
Epoch 14/100, Loss: 2.2964027673006058
Epoch 15/100, Loss: 2.3945575580000877
Epoch 16/100, Loss: 2.2897315099835396
Epoch 17/100, Loss: 2.001661464571953
Epoch 18/100, Loss: 2.06281004101038
Epoch 19/100, Loss: 2.128353677690029

Epoch 20/100, Loss: 2.1675230860710144
Epoch 21/100, Loss: 2.334476187825203
Epoch 22/100, Loss: 2.307049736380577
Epoch 23/100, Loss: 3.0201554894447327
Epoch 24/100, Loss: 2.421745590865612
Epoch 25/100, Loss: 2.3783282563090324
Epoch 26/100, Loss: 2.458138071000576
Epoch 27/100, Loss: 2.1583949252963066
Epoch 28/100, Loss: 2.429384522140026
Epoch 29/100, Loss: 2.3350692093372345
Epoch 30/100, Loss: 2.173047661781311
Epoch 31/100, Loss: 1.9403999149799347
Epoch 32/100, Loss: 2.2228327244520187
Epoch 33/100, Loss: 2.076580986380577
Epoch 34/100, Loss: 2.156310088932514
Epoch 35/100, Loss: 2.0375506430864334

Epoch 36/100, Loss: 2.3956732973456383
Epoch 37/100, Loss: 2.270946189761162
Epoch 38/100, Loss: 2.2097123190760612
Epoch 39/100, Loss: 2.2813028544187546
Epoch 40/100, Loss: 1.907286174595356
Epoch 41/100, Loss: 2.224848687648773
Epoch 42/100, Loss: 2.1647693812847137
Epoch 43/100, Loss: 2.098192445933819
Epoch 44/100, Loss: 2.092681907117367
Epoch 45/100, Loss: 2.3504093289375305
Epoch 46/100, Loss: 2.3210410103201866
Epoch 47/100, Loss: 2.3196315616369247
Epoch 48/100, Loss: 2.313885845243931
Epoch 49/100, Loss: 2.2917060777544975
Epoch 50/100, Loss: 2.3636240735650063
Epoch 51/100, Loss: 2.134551163762808

Epoch 52/100, Loss: 2.2966303527355194
Epoch 53/100, Loss: 2.2907037809491158
Epoch 54/100, Loss: 2.4770232886075974
Epoch 55/100, Loss: 2.0135822147130966
Epoch 56/100, Loss: 2.25774297863245
Epoch 57/100, Loss: 2.18903998285532
Epoch 58/100, Loss: 2.006791479885578
Epoch 59/100, Loss: 2.323603443801403
Epoch 60/100, Loss: 2.2508522048592567
Epoch 61/100, Loss: 2.7912189811468124
Epoch 62/100, Loss: 2.23425230383873
Epoch 63/100, Loss: 2.3027994632720947
Epoch 64/100, Loss: 2.1732853576540947
Epoch 65/100, Loss: 2.2497782856225967
Epoch 66/100, Loss: 2.182107597589493
Epoch 67/100, Loss: 2.032951757311821

Epoch 68/100, Loss: 2.1076555326581
Epoch 69/100, Loss: 2.5529400408267975
Epoch 70/100, Loss: 2.164357863366604
Epoch 71/100, Loss: 2.316819652915001
Epoch 72/100, Loss: 2.254817955195904
Epoch 73/100, Loss: 3.134787030518055
Epoch 74/100, Loss: 2.0960203781723976
Epoch 75/100, Loss: 1.9401936754584312
Epoch 76/100, Loss: 2.2766953259706497
Epoch 77/100, Loss: 2.303057722747326
Epoch 78/100, Loss: 2.116179123520851
Epoch 79/100, Loss: 2.2158252000808716
Epoch 80/100, Loss: 2.1441968455910683
Epoch 81/100, Loss: 1.9900124184787273
Epoch 82/100, Loss: 2.0303879603743553

Epoch 83/100, Loss: 2.1072545796632767
Epoch 84/100, Loss: 2.3276112228631973
Epoch 85/100, Loss: 2.1595479622483253
Epoch 86/100, Loss: 2.3704449236392975
Epoch 87/100, Loss: 2.370456337928772
Epoch 88/100, Loss: 2.32900919765234
Epoch 89/100, Loss: 2.230035714805126
Epoch 90/100, Loss: 2.430184133350849
Epoch 91/100, Loss: 2.185614585876465
Epoch 92/100, Loss: 2.3789619356393814
Epoch 93/100, Loss: 2.154071532189846
Epoch 94/100, Loss: 2.0817080438137054
Epoch 95/100, Loss: 2.349464423954487
Epoch 96/100, Loss: 2.362081900238991
Epoch 97/100, Loss: 2.1426259949803352

Epoch 98/100, Loss: 2.1706060990691185
Epoch 99/100, Loss: 2.210709735751152
Epoch 100/100, Loss: 2.2211694046854973
Fold 5/5 done

In [11]:
ap = average_precision_score(y_true, anomaly_scores)
print(f"Deep SVDD AP (5-fold CV) = {ap:.4f}")
sb.glue("GBG500_ap_spectral_deep_svdd", float(ap))

Deep SVDD AP (5-fold CV) = 0.5295