In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import average_precision_score
from sklearn.model_selection import StratifiedKFold
from pyod.models.deep_svdd import DeepSVDD
import sys
import scrapbook as sb

sys.path.append('..')
from utils import reshape_to_numpy, interpolate_missing_values, denoise_data, compute_spectrograms, time_avg_pooling

In [2]:
seed = 1
sampling_rate = 10
nperseg=64
noverlap=32
accel_cutoff = 0.4
accel_order = 30
gyro_cutoff = 0.6
gyro_order = 20
batch_size = 32
epochs = 100
hidden_neurons = [128, 64, 32]
n_splits = 5

In [3]:
# Parameters
seed = 20

In [4]:
rng = np.random.RandomState(seed)

In [5]:
data = pd.read_parquet("../data/GBG500.parquet")
data

,ride_id,time_index,ax,ay,az,rx,ry,rz
0,005043f1a7520cebf1e17fd166a00a3190e2433530f236...,0,-2.512796,-9.385012,-1.053078,-0.009155,0.009155,-0.201416
1,005043f1a7520cebf1e17fd166a00a3190e2433530f236...,100,-2.491268,-9.385012,-1.079390,-0.036621,0.027465,-0.155639
2,005043f1a7520cebf1e17fd166a00a3190e2433530f236...,200,-2.534324,-9.382022,-1.030952,0.036621,0.027465,-0.073242
3,005043f1a7520cebf1e17fd166a00a3190e2433530f236...,300,-2.488278,-9.383218,-1.091948,-0.045776,0.036621,-0.183105
4,005043f1a7520cebf1e17fd166a00a3190e2433530f236...,400,-2.483494,-9.382022,-1.100320,-0.045776,0.027465,-0.192260
...,...,...,...,...,...,...,...,...
1529542,ffb6f2f5dc6ba768d88dc0bc1af4cad235526aa9e24168...,241300,0.459862,-9.140430,-3.318900,1.556396,-0.091552,0.274658
1529543,ffb6f2f5dc6ba768d88dc0bc1af4cad235526aa9e24168...,241400,0.455676,-9.140430,-3.321292,1.583861,-0.119018,0.274658
1529544,ffb6f2f5dc6ba768d88dc0bc1af4cad235526aa9e24168...,241500,0.459862,-9.139832,-3.317704,1.583861,-0.109863,0.274658
1529545,ffb6f2f5dc6ba768d88dc0bc1af4cad235526aa9e24168...,241600,0.456274,-9.142224,-3.321292,1.574707,-0.137329,0.283813
1529546,ffb6f2f5dc6ba768d88dc0bc1af4cad235526aa9e24168...,241700,0.458666,-9.139832,-3.320694,1.574707,-0.137329,0.274658

In [6]:
labels = pd.read_csv("../data/GBG500_labels.csv")
labels.columns = labels.columns.str.lower()
ride_order_df = pd.DataFrame({"ride_id": data["ride_id"].unique()})
labels_sorted = ride_order_df.merge(
    labels,
    on="ride_id",
    how="left"
)
labels_sorted

                                               ride_id        label
0    005043f1a7520cebf1e17fd166a00a3190e2433530f236...         Safe
1    00d223cb7aecc9c0cc5871e32a6c45027a068eba07c572...     Reckless
2    02288a4aeca044203394e982e76b87818021dea2b34df9...         Safe
3    0236bdcf13d473ea24d97f5eaeea459f257dffac005694...  Bad weather
4    0238e5dd85143f1b6c59b200bc32f14361b8fc84c51a87...         Safe
..                                                 ...          ...
495  fe5d7f84d692bbccad8bd566a3ad5c3108fa9f90acd671...         Safe
496  fe67169632306d4668b2affedef510df2cb43e2fb41220...         Safe
497  fee44667fdc8ab4995c702fc3bd36178de0b1ca2c64687...         Safe
498  ff79b2e945b93c2a5efc3a06365267b3a160e7849ba57d...         Safe
499  ffb6f2f5dc6ba768d88dc0bc1af4cad235526aa9e24168...         Safe

[500 rows x 2 columns]

In [7]:
data_np = reshape_to_numpy(
    data,
    features = ["ax", "ay", "az", "rx", "ry", "rz"],
    max_timestamps = 4800
)

data_np_clean = interpolate_missing_values(
    data_np,
    method='linear',
    limit=None
)

data_np_clean = denoise_data(
    data=data_np_clean,
    accel_indices=[0, 1, 2],
    gyro_indices=[3, 4, 5],
    accel_cutoff=accel_cutoff,
    accel_order=accel_order,
    gyro_cutoff=gyro_cutoff,
    gyro_order=gyro_order,
)

In [8]:
# Compute spectrograms for all rides
spectrograms_array = compute_spectrograms(data_np_clean, sampling_rate, nperseg, noverlap)
spectrograms_array.shape

(500, 149, 6, 33)

In [9]:
# Aggregate spectrograms using time-averaged pooling
X_feat = time_avg_pooling(spectrograms_array)
X_feat.shape

(500, 198)

In [10]:
# 5-fold stratified CV with Deep SVDD
skf = StratifiedKFold(n_splits=n_splits, shuffle=True, random_state=rng.randint(1000))
y_true = (labels_sorted['label'] == 'Reckless').astype(int).values
anomaly_scores = np.full(len(y_true), np.nan)

for fold, (train_idx, test_idx) in enumerate(skf.split(X_feat, y_true)):
    sc = StandardScaler()
    X_train = sc.fit_transform(X_feat[train_idx])
    X_test = sc.transform(X_feat[test_idx])

    np.random.seed(rng.randint(1000))
    model = DeepSVDD(
        n_features=X_train.shape[1],
        hidden_neurons=hidden_neurons,
        epochs=epochs,
        batch_size=batch_size,
        random_state=rng.randint(1000),
    )
    model.fit(X_train)
    anomaly_scores[test_idx] = model.decision_function(X_test)
    print(f"Fold {fold+1}/{n_splits} done")

Epoch 1/100, Loss: 1.4699185080826283
Epoch 2/100, Loss: 1.5999921187758446
Epoch 3/100, Loss: 1.5272769294679165
Epoch 4/100, Loss: 1.3943945802748203
Epoch 5/100, Loss: 1.5146292932331562
Epoch 6/100, Loss: 1.3412707149982452
Epoch 7/100, Loss: 1.3409657217562199
Epoch 8/100, Loss: 1.4419353753328323
Epoch 9/100, Loss: 1.3912780955433846
Epoch 10/100, Loss: 1.3903102204203606
Epoch 11/100, Loss: 1.409800447523594
Epoch 12/100, Loss: 1.4591867625713348
Epoch 13/100, Loss: 1.3313940428197384
Epoch 14/100, Loss: 1.421314887702465
Epoch 15/100, Loss: 1.4248622320592403
Epoch 16/100, Loss: 1.407438401132822
Epoch 17/100, Loss: 1.505916003137827

Epoch 18/100, Loss: 1.4823353849351406
Epoch 19/100, Loss: 1.3996905833482742
Epoch 20/100, Loss: 1.3757333867251873
Epoch 21/100, Loss: 1.4441151171922684
Epoch 22/100, Loss: 1.3301136568188667
Epoch 23/100, Loss: 1.4479887522757053
Epoch 24/100, Loss: 1.3440689332783222
Epoch 25/100, Loss: 1.372135415673256
Epoch 26/100, Loss: 1.4867753237485886
Epoch 27/100, Loss: 1.3626966699957848
Epoch 28/100, Loss: 1.426225669682026
Epoch 29/100, Loss: 1.3897574543952942
Epoch 30/100, Loss: 1.45130155980587
Epoch 31/100, Loss: 1.3781579658389091
Epoch 32/100, Loss: 1.5370297692716122
Epoch 33/100, Loss: 1.3341297954320908
Epoch 34/100, Loss: 1.3275795429944992

Epoch 35/100, Loss: 1.4130472615361214
Epoch 36/100, Loss: 1.4520630091428757
Epoch 37/100, Loss: 1.4208791330456734
Epoch 38/100, Loss: 1.4376038648188114
Epoch 39/100, Loss: 1.5280981920659542
Epoch 40/100, Loss: 1.4323061369359493
Epoch 41/100, Loss: 1.695399422198534
Epoch 42/100, Loss: 1.4542937204241753
Epoch 43/100, Loss: 1.3431299030780792
Epoch 44/100, Loss: 1.447010077536106
Epoch 45/100, Loss: 1.431582197546959
Epoch 46/100, Loss: 1.5685145556926727
Epoch 47/100, Loss: 1.4067529141902924
Epoch 48/100, Loss: 1.3419338688254356
Epoch 49/100, Loss: 1.4413669854402542
Epoch 50/100, Loss: 1.4590611942112446
Epoch 51/100, Loss: 1.377710223197937
Epoch 52/100, Loss: 1.5052483826875687

Epoch 53/100, Loss: 1.5020154230296612
Epoch 54/100, Loss: 1.3264003843069077
Epoch 55/100, Loss: 1.380019187927246
Epoch 56/100, Loss: 1.5464601330459118
Epoch 57/100, Loss: 1.4160213470458984
Epoch 58/100, Loss: 1.4607782065868378
Epoch 59/100, Loss: 1.4508064836263657
Epoch 60/100, Loss: 1.5267806760966778
Epoch 61/100, Loss: 1.4971781484782696
Epoch 62/100, Loss: 1.3413494378328323
Epoch 63/100, Loss: 1.386999063193798
Epoch 64/100, Loss: 1.3978578373789787
Epoch 65/100, Loss: 1.438699595630169
Epoch 66/100, Loss: 1.4171634837985039
Epoch 67/100, Loss: 1.548247143626213
Epoch 68/100, Loss: 1.4807527773082256
Epoch 69/100, Loss: 1.4495685510337353
Epoch 70/100, Loss: 1.3516088612377644

Epoch 71/100, Loss: 1.3583399020135403
Epoch 72/100, Loss: 1.3057403266429901
Epoch 73/100, Loss: 1.451989971101284
Epoch 74/100, Loss: 1.3305228166282177
Epoch 75/100, Loss: 1.430062223225832
Epoch 76/100, Loss: 1.3809420205652714
Epoch 77/100, Loss: 1.3935480415821075
Epoch 78/100, Loss: 1.4515390507876873
Epoch 79/100, Loss: 1.6064291298389435
Epoch 80/100, Loss: 1.458208929747343
Epoch 81/100, Loss: 1.5172584280371666
Epoch 82/100, Loss: 1.360037125647068
Epoch 83/100, Loss: 1.3460934795439243
Epoch 84/100, Loss: 1.6532228887081146
Epoch 85/100, Loss: 1.4646172150969505
Epoch 86/100, Loss: 1.3121405392885208
Epoch 87/100, Loss: 1.5347231775522232

Epoch 88/100, Loss: 1.2753679938614368
Epoch 89/100, Loss: 1.5075577571988106
Epoch 90/100, Loss: 1.5083779133856297
Epoch 91/100, Loss: 1.3281440697610378
Epoch 92/100, Loss: 1.506243273615837
Epoch 93/100, Loss: 1.5007615461945534
Epoch 94/100, Loss: 1.5344192124903202
Epoch 95/100, Loss: 1.362828716635704
Epoch 96/100, Loss: 1.3893882222473621
Epoch 97/100, Loss: 1.4625607542693615
Epoch 98/100, Loss: 1.5068875700235367

Epoch 99/100, Loss: 1.4505938366055489
Epoch 100/100, Loss: 1.5185435935854912
Fold 1/5 done
Epoch 1/100, Loss: 1.9150669537484646
Epoch 2/100, Loss: 1.6524723954498768
Epoch 3/100, Loss: 2.0017571039497852
Epoch 4/100, Loss: 2.2094591595232487
Epoch 5/100, Loss: 1.9034289009869099
Epoch 6/100, Loss: 1.5290453508496284
Epoch 7/100, Loss: 2.106348715722561
Epoch 8/100, Loss: 1.7340903282165527

Epoch 9/100, Loss: 1.5113922916352749
Epoch 10/100, Loss: 2.183500722050667
Epoch 11/100, Loss: 2.0358304008841515
Epoch 12/100, Loss: 1.9052474983036518
Epoch 13/100, Loss: 2.0093918591737747
Epoch 14/100, Loss: 1.7759577222168446
Epoch 15/100, Loss: 2.001019235700369
Epoch 16/100, Loss: 1.9683679640293121
Epoch 17/100, Loss: 2.326957743614912
Epoch 18/100, Loss: 1.7846133336424828
Epoch 19/100, Loss: 1.8404790051281452
Epoch 20/100, Loss: 2.072639100253582
Epoch 21/100, Loss: 2.0213924534618855
Epoch 22/100, Loss: 1.7853759303689003
Epoch 23/100, Loss: 2.233952198177576
Epoch 24/100, Loss: 1.8186373822391033
Epoch 25/100, Loss: 1.7748381234705448

Epoch 26/100, Loss: 1.840523049235344
Epoch 27/100, Loss: 1.8520802445709705
Epoch 28/100, Loss: 1.6961205080151558
Epoch 29/100, Loss: 1.7486023381352425
Epoch 30/100, Loss: 1.7478083446621895
Epoch 31/100, Loss: 1.9687642976641655
Epoch 32/100, Loss: 1.8661160953342915
Epoch 33/100, Loss: 1.766878180205822
Epoch 34/100, Loss: 1.9553088173270226
Epoch 35/100, Loss: 1.9829705730080605
Epoch 36/100, Loss: 1.683896031230688
Epoch 37/100, Loss: 2.0292279347777367
Epoch 38/100, Loss: 1.8990397900342941
Epoch 39/100, Loss: 1.9388873167335987
Epoch 40/100, Loss: 1.9630292057991028
Epoch 41/100, Loss: 1.6176439486443996
Epoch 42/100, Loss: 1.8594268001616001

Epoch 43/100, Loss: 2.063848491758108
Epoch 44/100, Loss: 1.8976354859769344
Epoch 45/100, Loss: 1.6953862123191357
Epoch 46/100, Loss: 1.80956644192338
Epoch 47/100, Loss: 1.9043119437992573
Epoch 48/100, Loss: 2.1293548718094826
Epoch 49/100, Loss: 2.485642846673727
Epoch 50/100, Loss: 1.658855713903904
Epoch 51/100, Loss: 1.8957973569631577
Epoch 52/100, Loss: 2.050716247409582
Epoch 53/100, Loss: 1.93294807523489
Epoch 54/100, Loss: 1.6195669174194336
Epoch 55/100, Loss: 1.9717820808291435
Epoch 56/100, Loss: 2.095724381506443
Epoch 57/100, Loss: 2.2140338495373726
Epoch 58/100, Loss: 1.807340208441019
Epoch 59/100, Loss: 1.691872015595436

Epoch 60/100, Loss: 1.7233693972229958
Epoch 61/100, Loss: 2.004587061703205
Epoch 62/100, Loss: 1.7562953941524029
Epoch 63/100, Loss: 1.7605542317032814
Epoch 64/100, Loss: 1.9310672283172607
Epoch 65/100, Loss: 1.8529842607676983
Epoch 66/100, Loss: 2.006988286972046
Epoch 67/100, Loss: 1.847267024219036
Epoch 68/100, Loss: 1.6603973098099232
Epoch 69/100, Loss: 1.7576639726758003
Epoch 70/100, Loss: 1.770384844392538
Epoch 71/100, Loss: 2.0367538034915924
Epoch 72/100, Loss: 2.2903140299022198
Epoch 73/100, Loss: 1.802751787006855
Epoch 74/100, Loss: 2.1781994476914406
Epoch 75/100, Loss: 1.9849958010017872
Epoch 76/100, Loss: 2.020747434347868

Epoch 77/100, Loss: 1.9281344562768936
Epoch 78/100, Loss: 2.396670375019312
Epoch 79/100, Loss: 1.6145446971058846
Epoch 80/100, Loss: 1.8565203696489334
Epoch 81/100, Loss: 3.0750747583806515
Epoch 82/100, Loss: 1.8356818929314613
Epoch 83/100, Loss: 1.9087654799222946
Epoch 84/100, Loss: 1.6899128630757332
Epoch 85/100, Loss: 1.8156716264784336
Epoch 86/100, Loss: 1.8816747032105923
Epoch 87/100, Loss: 1.9990271031856537
Epoch 88/100, Loss: 1.7731786109507084
Epoch 89/100, Loss: 2.0553370155394077
Epoch 90/100, Loss: 2.0745033733546734
Epoch 91/100, Loss: 2.2507912553846836

Epoch 92/100, Loss: 1.9730712622404099
Epoch 93/100, Loss: 2.0471425130963326
Epoch 94/100, Loss: 2.118616759777069
Epoch 95/100, Loss: 2.058279186487198
Epoch 96/100, Loss: 2.062184788286686
Epoch 97/100, Loss: 1.886178381741047
Epoch 98/100, Loss: 1.8120345063507557
Epoch 99/100, Loss: 2.0995379239320755
Epoch 100/100, Loss: 1.9755374863743782
Fold 2/5 done
Epoch 1/100, Loss: 3.5461111813783646
Epoch 2/100, Loss: 3.3059511184692383
Epoch 3/100, Loss: 3.473245248198509

Epoch 4/100, Loss: 3.5096181482076645
Epoch 5/100, Loss: 3.250910207629204
Epoch 6/100, Loss: 3.2901228815317154
Epoch 7/100, Loss: 3.45699106156826
Epoch 8/100, Loss: 3.412626028060913
Epoch 9/100, Loss: 3.3920652717351913
Epoch 10/100, Loss: 3.374323680996895
Epoch 11/100, Loss: 3.2535008937120438
Epoch 12/100, Loss: 3.2743052393198013
Epoch 13/100, Loss: 3.3129552751779556
Epoch 14/100, Loss: 3.4072678834199905
Epoch 15/100, Loss: 3.3823029845952988
Epoch 16/100, Loss: 3.512871280312538
Epoch 17/100, Loss: 3.385643497109413
Epoch 18/100, Loss: 3.471866190433502
Epoch 19/100, Loss: 3.278455078601837

Epoch 20/100, Loss: 3.273820325732231
Epoch 21/100, Loss: 3.3710309267044067
Epoch 22/100, Loss: 3.4047177135944366
Epoch 23/100, Loss: 3.409909188747406
Epoch 24/100, Loss: 3.234285205602646
Epoch 25/100, Loss: 3.460952639579773
Epoch 26/100, Loss: 3.4643812775611877
Epoch 27/100, Loss: 3.5058103501796722
Epoch 28/100, Loss: 3.3126074075698853
Epoch 29/100, Loss: 3.3371360450983047
Epoch 30/100, Loss: 3.200855851173401
Epoch 31/100, Loss: 3.4191109091043472
Epoch 32/100, Loss: 3.3657176196575165
Epoch 33/100, Loss: 3.3678883016109467
Epoch 34/100, Loss: 3.442806050181389
Epoch 35/100, Loss: 3.442168354988098
Epoch 36/100, Loss: 3.4796760976314545
Epoch 37/100, Loss: 3.427024245262146

Epoch 38/100, Loss: 3.4663349092006683
Epoch 39/100, Loss: 3.483912631869316
Epoch 40/100, Loss: 3.3743725568056107
Epoch 41/100, Loss: 3.3044374138116837
Epoch 42/100, Loss: 3.481327325105667
Epoch 43/100, Loss: 3.563385099172592
Epoch 44/100, Loss: 3.345050349831581
Epoch 45/100, Loss: 3.5590426921844482
Epoch 46/100, Loss: 3.5111248195171356
Epoch 47/100, Loss: 3.4311044961214066
Epoch 48/100, Loss: 3.591136544942856
Epoch 49/100, Loss: 3.3497148752212524
Epoch 50/100, Loss: 3.300129532814026
Epoch 51/100, Loss: 3.3848967403173447
Epoch 52/100, Loss: 3.325296327471733
Epoch 53/100, Loss: 3.3722028583288193
Epoch 54/100, Loss: 3.3325284123420715
Epoch 55/100, Loss: 3.4832531064748764

Epoch 56/100, Loss: 3.39006344974041
Epoch 57/100, Loss: 3.3980427384376526
Epoch 58/100, Loss: 3.4292619973421097
Epoch 59/100, Loss: 3.5887736827135086
Epoch 60/100, Loss: 3.3891231566667557
Epoch 61/100, Loss: 3.3235404044389725
Epoch 62/100, Loss: 3.4924983382225037
Epoch 63/100, Loss: 3.326752781867981
Epoch 64/100, Loss: 3.42326757311821
Epoch 65/100, Loss: 3.4600476771593094
Epoch 66/100, Loss: 3.2039906084537506
Epoch 67/100, Loss: 3.2676422894001007
Epoch 68/100, Loss: 3.5533812940120697
Epoch 69/100, Loss: 3.3745320588350296
Epoch 70/100, Loss: 3.3585407435894012
Epoch 71/100, Loss: 3.400834873318672
Epoch 72/100, Loss: 3.1976121962070465
Epoch 73/100, Loss: 3.385160081088543

Epoch 74/100, Loss: 3.356736570596695
Epoch 75/100, Loss: 3.4139120876789093
Epoch 76/100, Loss: 3.3780171424150467
Epoch 77/100, Loss: 3.373802825808525
Epoch 78/100, Loss: 3.440247431397438
Epoch 79/100, Loss: 3.2772713750600815
Epoch 80/100, Loss: 3.385348469018936
Epoch 81/100, Loss: 3.567815124988556
Epoch 82/100, Loss: 3.380679339170456
Epoch 83/100, Loss: 3.3186423927545547
Epoch 84/100, Loss: 3.2653821855783463
Epoch 85/100, Loss: 3.402010001242161
Epoch 86/100, Loss: 3.324271008372307
Epoch 87/100, Loss: 3.471957802772522
Epoch 88/100, Loss: 3.505380257964134
Epoch 89/100, Loss: 3.304549515247345
Epoch 90/100, Loss: 3.393148586153984

Epoch 91/100, Loss: 3.2558097392320633
Epoch 92/100, Loss: 3.377462923526764
Epoch 93/100, Loss: 3.37146757543087
Epoch 94/100, Loss: 3.365871638059616
Epoch 95/100, Loss: 3.4268826246261597
Epoch 96/100, Loss: 3.469617396593094
Epoch 97/100, Loss: 3.3934768438339233
Epoch 98/100, Loss: 3.346742868423462
Epoch 99/100, Loss: 3.408318802714348
Epoch 100/100, Loss: 3.28753125667572
Fold 3/5 done
Epoch 1/100, Loss: 3.2060610949993134
Epoch 2/100, Loss: 3.1225491166114807
Epoch 3/100, Loss: 2.878650315105915
Epoch 4/100, Loss: 3.043004795908928
Epoch 5/100, Loss: 2.9922403693199158

Epoch 6/100, Loss: 3.3079880326986313
Epoch 7/100, Loss: 3.2437619976699352
Epoch 8/100, Loss: 3.1630994006991386
Epoch 9/100, Loss: 3.346808508038521
Epoch 10/100, Loss: 3.0866246297955513
Epoch 11/100, Loss: 2.9618813768029213
Epoch 12/100, Loss: 2.7285587787628174
Epoch 13/100, Loss: 3.2078038826584816
Epoch 14/100, Loss: 3.2715748474001884
Epoch 15/100, Loss: 3.2186683118343353
Epoch 16/100, Loss: 3.111991412937641
Epoch 17/100, Loss: 3.4292506352066994
Epoch 18/100, Loss: 3.183893643319607
Epoch 19/100, Loss: 3.535197474062443
Epoch 20/100, Loss: 3.541966088116169
Epoch 21/100, Loss: 3.221773035824299
Epoch 22/100, Loss: 3.3337920531630516
Epoch 23/100, Loss: 3.4854226484894753

Epoch 24/100, Loss: 2.99078506231308
Epoch 25/100, Loss: 4.576677732169628
Epoch 26/100, Loss: 3.4025930613279343
Epoch 27/100, Loss: 3.4147856533527374
Epoch 28/100, Loss: 4.242170907557011
Epoch 29/100, Loss: 3.03118646889925
Epoch 30/100, Loss: 3.1700839698314667
Epoch 31/100, Loss: 3.269805908203125
Epoch 32/100, Loss: 3.5334793031215668
Epoch 33/100, Loss: 2.7906774803996086
Epoch 34/100, Loss: 3.4877378195524216
Epoch 35/100, Loss: 2.8879723623394966
Epoch 36/100, Loss: 3.2015075236558914
Epoch 37/100, Loss: 3.3633565977215767
Epoch 38/100, Loss: 3.3187518268823624
Epoch 39/100, Loss: 3.491996794939041
Epoch 40/100, Loss: 3.547655515372753
Epoch 41/100, Loss: 3.3023752123117447

Epoch 42/100, Loss: 3.2744745314121246
Epoch 43/100, Loss: 3.1696792319417
Epoch 44/100, Loss: 3.2240181267261505
Epoch 45/100, Loss: 3.407079115509987
Epoch 46/100, Loss: 3.412863038480282
Epoch 47/100, Loss: 3.3146453127264977
Epoch 48/100, Loss: 3.3782083988189697
Epoch 49/100, Loss: 3.2044388726353645
Epoch 50/100, Loss: 3.174698993563652
Epoch 51/100, Loss: 3.3197214528918266
Epoch 52/100, Loss: 3.3177608251571655

Epoch 53/100, Loss: 3.238438703119755
Epoch 54/100, Loss: 3.3310745880007744
Epoch 55/100, Loss: 2.929821163415909
Epoch 56/100, Loss: 2.7538293674588203
Epoch 57/100, Loss: 3.439888760447502
Epoch 58/100, Loss: 3.6205582693219185
Epoch 59/100, Loss: 2.758677192032337
Epoch 60/100, Loss: 3.387599766254425
Epoch 61/100, Loss: 3.4139238372445107
Epoch 62/100, Loss: 3.0535478070378304
Epoch 63/100, Loss: 3.3134712129831314

Epoch 64/100, Loss: 3.481703571975231
Epoch 65/100, Loss: 3.1370852440595627
Epoch 66/100, Loss: 4.445380471646786
Epoch 67/100, Loss: 3.0789142474532127
Epoch 68/100, Loss: 3.188164308667183
Epoch 69/100, Loss: 3.130841374397278
Epoch 70/100, Loss: 3.251305013895035
Epoch 71/100, Loss: 3.1230658292770386
Epoch 72/100, Loss: 3.363102078437805
Epoch 73/100, Loss: 3.2035016044974327
Epoch 74/100, Loss: 2.995614156126976

Epoch 75/100, Loss: 2.739356130361557
Epoch 76/100, Loss: 3.6128053218126297
Epoch 77/100, Loss: 3.2289000153541565
Epoch 78/100, Loss: 3.1770866438746452
Epoch 79/100, Loss: 2.978412941098213
Epoch 80/100, Loss: 3.2351875454187393
Epoch 81/100, Loss: 3.06659048050642
Epoch 82/100, Loss: 3.5218540877103806
Epoch 83/100, Loss: 3.2256029099226
Epoch 84/100, Loss: 3.2626602798700333
Epoch 85/100, Loss: 3.0526444241404533

Epoch 86/100, Loss: 3.024449050426483
Epoch 87/100, Loss: 3.3470041528344154
Epoch 88/100, Loss: 3.5498584657907486
Epoch 89/100, Loss: 3.2360527142882347
Epoch 90/100, Loss: 3.2900232896208763
Epoch 91/100, Loss: 3.4962729811668396
Epoch 92/100, Loss: 3.2386503517627716
Epoch 93/100, Loss: 2.999952659010887
Epoch 94/100, Loss: 3.253105565905571
Epoch 95/100, Loss: 3.0587659552693367
Epoch 96/100, Loss: 2.788269117474556
Epoch 97/100, Loss: 3.0185865089297295

Epoch 98/100, Loss: 3.36125635355711
Epoch 99/100, Loss: 3.146891549229622
Epoch 100/100, Loss: 2.756929636001587
Fold 4/5 done
Epoch 1/100, Loss: 2.676124759018421
Epoch 2/100, Loss: 2.6429073065519333
Epoch 3/100, Loss: 2.8365835398435593
Epoch 4/100, Loss: 2.930396504700184
Epoch 5/100, Loss: 2.6357314586639404
Epoch 6/100, Loss: 2.473312631249428
Epoch 7/100, Loss: 2.9089699015021324
Epoch 8/100, Loss: 2.8023714870214462

Epoch 9/100, Loss: 2.3888430297374725
Epoch 10/100, Loss: 2.6026379764080048
Epoch 11/100, Loss: 2.667597971856594
Epoch 12/100, Loss: 2.886514663696289
Epoch 13/100, Loss: 2.725142687559128
Epoch 14/100, Loss: 2.740548200905323
Epoch 15/100, Loss: 2.570830501616001
Epoch 16/100, Loss: 2.672855004668236
Epoch 17/100, Loss: 2.78922850638628
Epoch 18/100, Loss: 2.5341632068157196
Epoch 19/100, Loss: 2.6971995308995247
Epoch 20/100, Loss: 2.83778116106987

Epoch 21/100, Loss: 2.8439682945609093
Epoch 22/100, Loss: 2.6727316305041313
Epoch 23/100, Loss: 2.691603682935238
Epoch 24/100, Loss: 3.0103310644626617
Epoch 25/100, Loss: 2.683570019900799
Epoch 26/100, Loss: 3.0781916454434395
Epoch 27/100, Loss: 3.005948081612587
Epoch 28/100, Loss: 2.92682047188282
Epoch 29/100, Loss: 2.769636854529381
Epoch 30/100, Loss: 2.8912014961242676
Epoch 31/100, Loss: 2.8131322413682938
Epoch 32/100, Loss: 2.548566445708275

Epoch 33/100, Loss: 2.7472916916012764
Epoch 34/100, Loss: 2.5983083844184875
Epoch 35/100, Loss: 2.6742577478289604
Epoch 36/100, Loss: 2.6865837201476097
Epoch 37/100, Loss: 2.9855644553899765
Epoch 38/100, Loss: 2.7427873611450195
Epoch 39/100, Loss: 2.7603652328252792
Epoch 40/100, Loss: 2.7363205701112747
Epoch 41/100, Loss: 2.7230184450745583
Epoch 42/100, Loss: 2.751484125852585
Epoch 43/100, Loss: 2.7502768710255623

Epoch 44/100, Loss: 2.677545666694641
Epoch 45/100, Loss: 2.808522216975689
Epoch 46/100, Loss: 2.8353133127093315
Epoch 47/100, Loss: 2.6103453636169434
Epoch 48/100, Loss: 2.8684555888175964
Epoch 49/100, Loss: 2.6270106807351112
Epoch 50/100, Loss: 2.865021660923958
Epoch 51/100, Loss: 2.521541118621826
Epoch 52/100, Loss: 2.6970072090625763
Epoch 53/100, Loss: 2.496687598526478
Epoch 54/100, Loss: 2.788977660238743
Epoch 55/100, Loss: 2.557224787771702

Epoch 56/100, Loss: 2.8042506724596024
Epoch 57/100, Loss: 2.6728782951831818
Epoch 58/100, Loss: 2.742834448814392
Epoch 59/100, Loss: 3.0189418122172356
Epoch 60/100, Loss: 2.7071026414632797
Epoch 61/100, Loss: 2.6215164959430695
Epoch 62/100, Loss: 2.689526744186878
Epoch 63/100, Loss: 2.7180833742022514
Epoch 64/100, Loss: 2.834900550544262
Epoch 65/100, Loss: 2.708151489496231
Epoch 66/100, Loss: 2.7500180676579475

Epoch 67/100, Loss: 2.628180406987667
Epoch 68/100, Loss: 2.7751971632242203
Epoch 69/100, Loss: 2.634190984070301
Epoch 70/100, Loss: 2.929655075073242
Epoch 71/100, Loss: 2.8231044188141823
Epoch 72/100, Loss: 2.7021605148911476
Epoch 73/100, Loss: 2.7054394632577896
Epoch 74/100, Loss: 2.64185394346714
Epoch 75/100, Loss: 2.5804311335086823
Epoch 76/100, Loss: 2.8842284455895424
Epoch 77/100, Loss: 3.463115468621254

Epoch 78/100, Loss: 2.7161010950803757
Epoch 79/100, Loss: 2.631595440208912
Epoch 80/100, Loss: 2.7095434367656708
Epoch 81/100, Loss: 2.560461178421974
Epoch 82/100, Loss: 2.825016550719738
Epoch 83/100, Loss: 2.8333645164966583
Epoch 84/100, Loss: 3.0410724133253098
Epoch 85/100, Loss: 2.8990058228373528
Epoch 86/100, Loss: 2.710686206817627
Epoch 87/100, Loss: 2.6475762128829956
Epoch 88/100, Loss: 2.7618933990597725
Epoch 89/100, Loss: 2.8210798650979996
Epoch 90/100, Loss: 2.690017990767956
Epoch 91/100, Loss: 2.8007419034838676
Epoch 92/100, Loss: 2.718482129275799

Epoch 93/100, Loss: 2.762413941323757
Epoch 94/100, Loss: 2.9964373484253883
Epoch 95/100, Loss: 2.7936930507421494
Epoch 96/100, Loss: 2.7961505651474
Epoch 97/100, Loss: 2.857855163514614
Epoch 98/100, Loss: 2.658822387456894
Epoch 99/100, Loss: 2.7964605391025543
Epoch 100/100, Loss: 2.6911889612674713
Fold 5/5 done

In [11]:
ap = average_precision_score(y_true, anomaly_scores)
print(f"Deep SVDD AP (5-fold CV) = {ap:.4f}")
sb.glue("GBG500_ap_spectral_deep_svdd", float(ap))

Deep SVDD AP (5-fold CV) = 0.4511