In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import average_precision_score
from sklearn.model_selection import StratifiedKFold
from pyod.models.deep_svdd import DeepSVDD
import sys
import scrapbook as sb

sys.path.append('..')
from utils import reshape_to_numpy, interpolate_missing_values, denoise_data, compute_spectrograms, time_avg_pooling

In [2]:
seed = 1
sampling_rate = 10
nperseg=64
noverlap=32
accel_cutoff = 0.4
accel_order = 30
gyro_cutoff = 0.6
gyro_order = 20
batch_size = 32
epochs = 100
hidden_neurons = [128, 64, 32]
n_splits = 5

In [3]:
# Parameters
seed = 21

In [4]:
rng = np.random.RandomState(seed)

In [5]:
data = pd.read_parquet("../data/GBG500.parquet")
data

,ride_id,time_index,ax,ay,az,rx,ry,rz
0,005043f1a7520cebf1e17fd166a00a3190e2433530f236...,0,-2.512796,-9.385012,-1.053078,-0.009155,0.009155,-0.201416
1,005043f1a7520cebf1e17fd166a00a3190e2433530f236...,100,-2.491268,-9.385012,-1.079390,-0.036621,0.027465,-0.155639
2,005043f1a7520cebf1e17fd166a00a3190e2433530f236...,200,-2.534324,-9.382022,-1.030952,0.036621,0.027465,-0.073242
3,005043f1a7520cebf1e17fd166a00a3190e2433530f236...,300,-2.488278,-9.383218,-1.091948,-0.045776,0.036621,-0.183105
4,005043f1a7520cebf1e17fd166a00a3190e2433530f236...,400,-2.483494,-9.382022,-1.100320,-0.045776,0.027465,-0.192260
...,...,...,...,...,...,...,...,...
1529542,ffb6f2f5dc6ba768d88dc0bc1af4cad235526aa9e24168...,241300,0.459862,-9.140430,-3.318900,1.556396,-0.091552,0.274658
1529543,ffb6f2f5dc6ba768d88dc0bc1af4cad235526aa9e24168...,241400,0.455676,-9.140430,-3.321292,1.583861,-0.119018,0.274658
1529544,ffb6f2f5dc6ba768d88dc0bc1af4cad235526aa9e24168...,241500,0.459862,-9.139832,-3.317704,1.583861,-0.109863,0.274658
1529545,ffb6f2f5dc6ba768d88dc0bc1af4cad235526aa9e24168...,241600,0.456274,-9.142224,-3.321292,1.574707,-0.137329,0.283813
1529546,ffb6f2f5dc6ba768d88dc0bc1af4cad235526aa9e24168...,241700,0.458666,-9.139832,-3.320694,1.574707,-0.137329,0.274658

In [6]:
labels = pd.read_csv("../data/GBG500_labels.csv")
labels.columns = labels.columns.str.lower()
ride_order_df = pd.DataFrame({"ride_id": data["ride_id"].unique()})
labels_sorted = ride_order_df.merge(
    labels,
    on="ride_id",
    how="left"
)
labels_sorted

                                               ride_id        label
0    005043f1a7520cebf1e17fd166a00a3190e2433530f236...         Safe
1    00d223cb7aecc9c0cc5871e32a6c45027a068eba07c572...     Reckless
2    02288a4aeca044203394e982e76b87818021dea2b34df9...         Safe
3    0236bdcf13d473ea24d97f5eaeea459f257dffac005694...  Bad weather
4    0238e5dd85143f1b6c59b200bc32f14361b8fc84c51a87...         Safe
..                                                 ...          ...
495  fe5d7f84d692bbccad8bd566a3ad5c3108fa9f90acd671...         Safe
496  fe67169632306d4668b2affedef510df2cb43e2fb41220...         Safe
497  fee44667fdc8ab4995c702fc3bd36178de0b1ca2c64687...         Safe
498  ff79b2e945b93c2a5efc3a06365267b3a160e7849ba57d...         Safe
499  ffb6f2f5dc6ba768d88dc0bc1af4cad235526aa9e24168...         Safe

[500 rows x 2 columns]

In [7]:
data_np = reshape_to_numpy(
    data,
    features = ["ax", "ay", "az", "rx", "ry", "rz"],
    max_timestamps = 4800
)

data_np_clean = interpolate_missing_values(
    data_np,
    method='linear',
    limit=None
)

data_np_clean = denoise_data(
    data=data_np_clean,
    accel_indices=[0, 1, 2],
    gyro_indices=[3, 4, 5],
    accel_cutoff=accel_cutoff,
    accel_order=accel_order,
    gyro_cutoff=gyro_cutoff,
    gyro_order=gyro_order,
)

In [8]:
# Compute spectrograms for all rides
spectrograms_array = compute_spectrograms(data_np_clean, sampling_rate, nperseg, noverlap)
spectrograms_array.shape

(500, 149, 6, 33)

In [9]:
# Aggregate spectrograms using time-averaged pooling
X_feat = time_avg_pooling(spectrograms_array)
X_feat.shape

(500, 198)

In [10]:
# 5-fold stratified CV with Deep SVDD
skf = StratifiedKFold(n_splits=n_splits, shuffle=True, random_state=rng.randint(1000))
y_true = (labels_sorted['label'] == 'Reckless').astype(int).values
anomaly_scores = np.full(len(y_true), np.nan)

for fold, (train_idx, test_idx) in enumerate(skf.split(X_feat, y_true)):
    sc = StandardScaler()
    X_train = sc.fit_transform(X_feat[train_idx])
    X_test = sc.transform(X_feat[test_idx])

    np.random.seed(rng.randint(1000))
    model = DeepSVDD(
        n_features=X_train.shape[1],
        hidden_neurons=hidden_neurons,
        epochs=epochs,
        batch_size=batch_size,
        random_state=rng.randint(1000),
    )
    model.fit(X_train)
    anomaly_scores[test_idx] = model.decision_function(X_test)
    print(f"Fold {fold+1}/{n_splits} done")

Epoch 1/100, Loss: 2.969215080142021
Epoch 2/100, Loss: 2.979239299893379
Epoch 3/100, Loss: 3.346597172319889
Epoch 4/100, Loss: 2.8511520102620125
Epoch 5/100, Loss: 2.801318295300007
Epoch 6/100, Loss: 3.033502459526062
Epoch 7/100, Loss: 2.8382134810090065
Epoch 8/100, Loss: 2.940922886133194
Epoch 9/100, Loss: 3.021699897944927
Epoch 10/100, Loss: 3.0578396916389465
Epoch 11/100, Loss: 2.933562181890011
Epoch 12/100, Loss: 2.966615989804268
Epoch 13/100, Loss: 2.8332561925053596
Epoch 14/100, Loss: 2.843479558825493
Epoch 15/100, Loss: 3.0867812782526016

Epoch 16/100, Loss: 2.8144714534282684
Epoch 17/100, Loss: 2.994497038424015
Epoch 18/100, Loss: 3.047878809273243
Epoch 19/100, Loss: 2.8665915429592133
Epoch 20/100, Loss: 2.998001664876938
Epoch 21/100, Loss: 2.9800333976745605
Epoch 22/100, Loss: 2.7912193536758423
Epoch 23/100, Loss: 2.9165675044059753
Epoch 24/100, Loss: 2.970160588622093
Epoch 25/100, Loss: 2.8817678838968277
Epoch 26/100, Loss: 3.064101003110409
Epoch 27/100, Loss: 2.910935804247856
Epoch 28/100, Loss: 2.8026096746325493
Epoch 29/100, Loss: 2.9648825004696846
Epoch 30/100, Loss: 2.831975869834423

Epoch 31/100, Loss: 2.809829965233803
Epoch 32/100, Loss: 2.838487893342972
Epoch 33/100, Loss: 2.996773637831211
Epoch 34/100, Loss: 2.917971931397915
Epoch 35/100, Loss: 2.8404457718133926
Epoch 36/100, Loss: 2.8253123238682747
Epoch 37/100, Loss: 2.9236972257494926
Epoch 38/100, Loss: 2.873792976140976
Epoch 39/100, Loss: 2.9939015805721283
Epoch 40/100, Loss: 2.9098857045173645
Epoch 41/100, Loss: 2.9169055595993996
Epoch 42/100, Loss: 3.0006302297115326
Epoch 43/100, Loss: 3.069574475288391
Epoch 44/100, Loss: 2.9688103199005127
Epoch 45/100, Loss: 2.878281347453594

Epoch 46/100, Loss: 2.9872818514704704
Epoch 47/100, Loss: 2.8145057260990143
Epoch 48/100, Loss: 2.8764853551983833
Epoch 49/100, Loss: 2.9768344908952713
Epoch 50/100, Loss: 2.8732775896787643
Epoch 51/100, Loss: 2.960905149579048
Epoch 52/100, Loss: 2.8757039308547974
Epoch 53/100, Loss: 2.9810776337981224
Epoch 54/100, Loss: 2.969970278441906
Epoch 55/100, Loss: 2.8636528626084328
Epoch 56/100, Loss: 2.953383058309555
Epoch 57/100, Loss: 2.931519739329815
Epoch 58/100, Loss: 2.8752604946494102
Epoch 59/100, Loss: 2.916870415210724
Epoch 60/100, Loss: 2.887612819671631

Epoch 61/100, Loss: 2.921439416706562
Epoch 62/100, Loss: 2.973442420363426
Epoch 63/100, Loss: 2.8788426965475082
Epoch 64/100, Loss: 2.948086567223072
Epoch 65/100, Loss: 2.9961299672722816
Epoch 66/100, Loss: 2.9145163744688034
Epoch 67/100, Loss: 2.8890255093574524
Epoch 68/100, Loss: 2.8547732532024384
Epoch 69/100, Loss: 2.8441299945116043
Epoch 70/100, Loss: 2.9658168181777
Epoch 71/100, Loss: 2.923827037215233
Epoch 72/100, Loss: 2.9408784359693527
Epoch 73/100, Loss: 2.890777640044689
Epoch 74/100, Loss: 3.0501460805535316
Epoch 75/100, Loss: 2.943427160382271
Epoch 76/100, Loss: 2.7968073189258575

Epoch 77/100, Loss: 2.842950090765953
Epoch 78/100, Loss: 2.8262466564774513
Epoch 79/100, Loss: 3.0555385425686836
Epoch 80/100, Loss: 2.8883177787065506
Epoch 81/100, Loss: 2.923798620700836
Epoch 82/100, Loss: 2.9323218911886215
Epoch 83/100, Loss: 2.991007015109062
Epoch 84/100, Loss: 2.7706320509314537
Epoch 85/100, Loss: 2.8341480419039726
Epoch 86/100, Loss: 2.8590465039014816
Epoch 87/100, Loss: 2.950426295399666
Epoch 88/100, Loss: 2.9543957263231277
Epoch 89/100, Loss: 2.7709607258439064
Epoch 90/100, Loss: 2.905918672680855
Epoch 91/100, Loss: 2.9879052340984344
Epoch 92/100, Loss: 3.0727320313453674

Epoch 93/100, Loss: 2.899028457701206
Epoch 94/100, Loss: 2.8092191219329834
Epoch 95/100, Loss: 2.9089541137218475
Epoch 96/100, Loss: 2.9312937930226326
Epoch 97/100, Loss: 2.801345616579056
Epoch 98/100, Loss: 2.954829454421997
Epoch 99/100, Loss: 3.162103943526745
Epoch 100/100, Loss: 3.054036647081375
Fold 1/5 done
Epoch 1/100, Loss: 2.672963924705982
Epoch 2/100, Loss: 2.605754218995571
Epoch 3/100, Loss: 2.715218275785446
Epoch 4/100, Loss: 2.8982417061924934
Epoch 5/100, Loss: 2.5484372824430466
Epoch 6/100, Loss: 2.6532043293118477

Epoch 7/100, Loss: 2.6983698904514313
Epoch 8/100, Loss: 2.813604958355427
Epoch 9/100, Loss: 2.8617873042821884
Epoch 10/100, Loss: 2.5178037881851196
Epoch 11/100, Loss: 2.774900607764721
Epoch 12/100, Loss: 2.653804063796997
Epoch 13/100, Loss: 2.7100777477025986
Epoch 14/100, Loss: 2.7522506713867188
Epoch 15/100, Loss: 2.8187211006879807
Epoch 16/100, Loss: 2.8802534863352776
Epoch 17/100, Loss: 2.6007888317108154

Epoch 18/100, Loss: 2.718786284327507
Epoch 19/100, Loss: 2.649626299738884
Epoch 20/100, Loss: 2.7590419203042984
Epoch 21/100, Loss: 2.6795763671398163
Epoch 22/100, Loss: 2.7592984065413475
Epoch 23/100, Loss: 2.6255918741226196
Epoch 24/100, Loss: 2.5889147147536278
Epoch 25/100, Loss: 2.7674775421619415
Epoch 26/100, Loss: 2.561419978737831
Epoch 27/100, Loss: 2.70635224878788
Epoch 28/100, Loss: 2.629561223089695

Epoch 29/100, Loss: 2.706022784113884
Epoch 30/100, Loss: 2.754362590610981
Epoch 31/100, Loss: 2.6337404400110245
Epoch 32/100, Loss: 2.6726521998643875
Epoch 33/100, Loss: 2.6735125333070755
Epoch 34/100, Loss: 2.759686730802059
Epoch 35/100, Loss: 2.7184755355119705
Epoch 36/100, Loss: 2.8088838905096054
Epoch 37/100, Loss: 2.647785723209381
Epoch 38/100, Loss: 2.4671632573008537
Epoch 39/100, Loss: 2.8027720600366592
Epoch 40/100, Loss: 2.6694010198116302

Epoch 41/100, Loss: 2.754722833633423
Epoch 42/100, Loss: 2.8864771872758865
Epoch 43/100, Loss: 2.602872759103775
Epoch 44/100, Loss: 2.7064299136400223
Epoch 45/100, Loss: 2.766696125268936
Epoch 46/100, Loss: 2.819002315402031
Epoch 47/100, Loss: 2.5879047513008118
Epoch 48/100, Loss: 2.706703655421734
Epoch 49/100, Loss: 2.5602976232767105
Epoch 50/100, Loss: 2.842327430844307
Epoch 51/100, Loss: 2.81109656393528
Epoch 52/100, Loss: 2.846866860985756

Epoch 53/100, Loss: 2.845343068242073
Epoch 54/100, Loss: 2.8269876837730408
Epoch 55/100, Loss: 2.6987274736166
Epoch 56/100, Loss: 2.74810791015625
Epoch 57/100, Loss: 2.5553561970591545
Epoch 58/100, Loss: 2.68548721075058
Epoch 59/100, Loss: 2.6571647822856903
Epoch 60/100, Loss: 2.9334988966584206
Epoch 61/100, Loss: 2.7398210167884827
Epoch 62/100, Loss: 2.706881210207939
Epoch 63/100, Loss: 2.6597501784563065

Epoch 64/100, Loss: 2.5595051869750023
Epoch 65/100, Loss: 2.6444970220327377
Epoch 66/100, Loss: 2.641902446746826
Epoch 67/100, Loss: 2.601305142045021
Epoch 68/100, Loss: 2.8127955347299576
Epoch 69/100, Loss: 2.555691324174404
Epoch 70/100, Loss: 2.6830740496516228
Epoch 71/100, Loss: 2.671012818813324
Epoch 72/100, Loss: 2.7644528225064278
Epoch 73/100, Loss: 2.8558085188269615
Epoch 74/100, Loss: 2.601930186152458
Epoch 75/100, Loss: 2.8226157873868942

Epoch 76/100, Loss: 2.8331634029746056
Epoch 77/100, Loss: 2.716444678604603
Epoch 78/100, Loss: 2.934232883155346
Epoch 79/100, Loss: 2.7951904833316803
Epoch 80/100, Loss: 2.8177702873945236
Epoch 81/100, Loss: 2.8644188046455383
Epoch 82/100, Loss: 2.884414754807949
Epoch 83/100, Loss: 2.7434635758399963
Epoch 84/100, Loss: 2.551010876893997
Epoch 85/100, Loss: 2.822665125131607
Epoch 86/100, Loss: 3.2275340259075165
Epoch 87/100, Loss: 2.6424426212906837

Epoch 88/100, Loss: 2.658352106809616
Epoch 89/100, Loss: 2.8367920368909836
Epoch 90/100, Loss: 2.8316539525985718
Epoch 91/100, Loss: 2.7611503303050995
Epoch 92/100, Loss: 2.7108857184648514
Epoch 93/100, Loss: 2.84252018481493
Epoch 94/100, Loss: 2.8822191059589386
Epoch 95/100, Loss: 2.7395141422748566
Epoch 96/100, Loss: 2.6145511269569397
Epoch 97/100, Loss: 2.621340535581112
Epoch 98/100, Loss: 2.9748340249061584

Epoch 99/100, Loss: 2.8176011741161346
Epoch 100/100, Loss: 2.612244665622711
Fold 2/5 done
Epoch 1/100, Loss: 1.5850634574890137
Epoch 2/100, Loss: 1.6962339356541634
Epoch 3/100, Loss: 1.842786356806755
Epoch 4/100, Loss: 1.8287438303232193
Epoch 5/100, Loss: 2.01929934322834
Epoch 6/100, Loss: 1.8480768278241158
Epoch 7/100, Loss: 1.6806264743208885
Epoch 8/100, Loss: 1.882203683257103

Epoch 9/100, Loss: 1.8570649400353432
Epoch 10/100, Loss: 1.6652486622333527
Epoch 11/100, Loss: 1.9170714244246483
Epoch 12/100, Loss: 1.8258130922913551
Epoch 13/100, Loss: 1.6911991015076637
Epoch 14/100, Loss: 1.7481506615877151
Epoch 15/100, Loss: 1.8594093471765518
Epoch 16/100, Loss: 1.7440694943070412
Epoch 17/100, Loss: 1.887208916246891
Epoch 18/100, Loss: 1.7760396376252174
Epoch 19/100, Loss: 1.845841959118843
Epoch 20/100, Loss: 1.8756154254078865
Epoch 21/100, Loss: 1.8706691414117813
Epoch 22/100, Loss: 2.0319045037031174

Epoch 23/100, Loss: 1.9079941250383854
Epoch 24/100, Loss: 1.81016306579113
Epoch 25/100, Loss: 1.6873750537633896
Epoch 26/100, Loss: 2.095874357968569
Epoch 27/100, Loss: 1.7845059260725975
Epoch 28/100, Loss: 1.7716141194105148
Epoch 29/100, Loss: 1.9699751660227776
Epoch 30/100, Loss: 1.6840391904115677
Epoch 31/100, Loss: 1.8794148713350296
Epoch 32/100, Loss: 1.7756379470229149
Epoch 33/100, Loss: 1.9473112188279629
Epoch 34/100, Loss: 1.8465394750237465
Epoch 35/100, Loss: 1.9351879954338074

Epoch 36/100, Loss: 1.7700207941234112
Epoch 37/100, Loss: 1.7769345864653587
Epoch 38/100, Loss: 1.8184703439474106
Epoch 39/100, Loss: 2.0398677960038185
Epoch 40/100, Loss: 1.7583817169070244
Epoch 41/100, Loss: 1.9648575186729431
Epoch 42/100, Loss: 1.952910155057907
Epoch 43/100, Loss: 1.8914069756865501
Epoch 44/100, Loss: 2.0693728402256966
Epoch 45/100, Loss: 1.84649009257555
Epoch 46/100, Loss: 1.74076659232378

Epoch 47/100, Loss: 1.8775091022253036
Epoch 48/100, Loss: 1.8433371409773827
Epoch 49/100, Loss: 1.8893640637397766
Epoch 50/100, Loss: 1.9582335576415062
Epoch 51/100, Loss: 1.9058392271399498
Epoch 52/100, Loss: 1.9850436374545097
Epoch 53/100, Loss: 1.9273061752319336
Epoch 54/100, Loss: 1.8850326165556908
Epoch 55/100, Loss: 1.9189760237932205
Epoch 56/100, Loss: 1.9483742788434029
Epoch 57/100, Loss: 1.8798240423202515

Epoch 58/100, Loss: 1.8064364790916443
Epoch 59/100, Loss: 1.7546228393912315
Epoch 60/100, Loss: 1.877946376800537
Epoch 61/100, Loss: 1.8328073769807816
Epoch 62/100, Loss: 1.7401340752840042
Epoch 63/100, Loss: 1.9745873361825943
Epoch 64/100, Loss: 1.753778025507927
Epoch 65/100, Loss: 1.9927929267287254
Epoch 66/100, Loss: 1.765016295015812
Epoch 67/100, Loss: 1.720644861459732
Epoch 68/100, Loss: 2.033884219825268

Epoch 69/100, Loss: 1.8348340466618538
Epoch 70/100, Loss: 1.7691037505865097
Epoch 71/100, Loss: 1.8802662268280983
Epoch 72/100, Loss: 1.8875209391117096
Epoch 73/100, Loss: 1.6248742938041687
Epoch 74/100, Loss: 1.790496326982975
Epoch 75/100, Loss: 1.8932460993528366
Epoch 76/100, Loss: 1.8375142142176628
Epoch 77/100, Loss: 1.809124767780304
Epoch 78/100, Loss: 1.9872734621167183
Epoch 79/100, Loss: 1.8268903866410255

Epoch 80/100, Loss: 2.0674368366599083
Epoch 81/100, Loss: 1.7670579627156258
Epoch 82/100, Loss: 1.760630939155817
Epoch 83/100, Loss: 1.6507624387741089
Epoch 84/100, Loss: 1.970268338918686
Epoch 85/100, Loss: 1.8445053696632385
Epoch 86/100, Loss: 1.9570052474737167
Epoch 87/100, Loss: 1.642213761806488
Epoch 88/100, Loss: 1.9598298221826553
Epoch 89/100, Loss: 1.7847793400287628
Epoch 90/100, Loss: 1.7015323415398598
Epoch 91/100, Loss: 1.879502721130848
Epoch 92/100, Loss: 1.825385369360447
Epoch 93/100, Loss: 2.0784164294600487

Epoch 94/100, Loss: 1.81009179353714
Epoch 95/100, Loss: 1.8658218458294868
Epoch 96/100, Loss: 1.778842844069004
Epoch 97/100, Loss: 2.3949901536107063
Epoch 98/100, Loss: 1.7563764192163944
Epoch 99/100, Loss: 1.8226353898644447
Epoch 100/100, Loss: 1.812578707933426
Fold 3/5 done
Epoch 1/100, Loss: 3.115483947098255
Epoch 2/100, Loss: 3.535742074251175
Epoch 3/100, Loss: 3.6615599021315575
Epoch 4/100, Loss: 3.2561147063970566
Epoch 5/100, Loss: 3.4761109203100204
Epoch 6/100, Loss: 3.4430812299251556
Epoch 7/100, Loss: 2.9406812861561775
Epoch 8/100, Loss: 2.8414634615182877

Epoch 9/100, Loss: 2.9265213310718536
Epoch 10/100, Loss: 3.0693079978227615
Epoch 11/100, Loss: 3.4531525149941444
Epoch 12/100, Loss: 3.4608189463615417
Epoch 13/100, Loss: 3.04706472158432
Epoch 14/100, Loss: 2.9442796781659126
Epoch 15/100, Loss: 3.4037070646882057
Epoch 16/100, Loss: 3.039791576564312
Epoch 17/100, Loss: 3.0089294984936714
Epoch 18/100, Loss: 4.312829285860062
Epoch 19/100, Loss: 2.9800087362527847
Epoch 20/100, Loss: 3.158637508749962
Epoch 21/100, Loss: 3.0307952612638474
Epoch 22/100, Loss: 3.119815893471241
Epoch 23/100, Loss: 3.541846349835396
Epoch 24/100, Loss: 3.0111920535564423
Epoch 25/100, Loss: 3.290803946554661

Epoch 26/100, Loss: 3.2524039521813393
Epoch 27/100, Loss: 3.6793596521019936
Epoch 28/100, Loss: 3.0270032212138176
Epoch 29/100, Loss: 3.2039839401841164
Epoch 30/100, Loss: 3.02424356341362
Epoch 31/100, Loss: 3.245187669992447
Epoch 32/100, Loss: 3.2739280685782433
Epoch 33/100, Loss: 3.1641004979610443
Epoch 34/100, Loss: 3.5019399151206017
Epoch 35/100, Loss: 3.0478647276759148
Epoch 36/100, Loss: 3.479372978210449
Epoch 37/100, Loss: 3.5050197392702103
Epoch 38/100, Loss: 3.228350281715393
Epoch 39/100, Loss: 3.1015926226973534
Epoch 40/100, Loss: 2.956168830394745
Epoch 41/100, Loss: 3.55597847700119

Epoch 42/100, Loss: 2.7657954394817352
Epoch 43/100, Loss: 4.271813780069351
Epoch 44/100, Loss: 3.498973712325096
Epoch 45/100, Loss: 3.086991563439369
Epoch 46/100, Loss: 3.3604212254285812
Epoch 47/100, Loss: 3.2477037981152534
Epoch 48/100, Loss: 3.5801031291484833
Epoch 49/100, Loss: 3.916873589158058
Epoch 50/100, Loss: 3.229333885014057
Epoch 51/100, Loss: 3.1284725219011307
Epoch 52/100, Loss: 3.153907872736454
Epoch 53/100, Loss: 3.5817059502005577
Epoch 54/100, Loss: 3.2615861371159554
Epoch 55/100, Loss: 2.9403712898492813
Epoch 56/100, Loss: 3.0167547054588795
Epoch 57/100, Loss: 3.180268570780754
Epoch 58/100, Loss: 3.5164559334516525
Epoch 59/100, Loss: 3.1297944635152817

Epoch 60/100, Loss: 3.281066782772541
Epoch 61/100, Loss: 3.519106701016426
Epoch 62/100, Loss: 3.0079245194792747
Epoch 63/100, Loss: 3.0737581327557564
Epoch 64/100, Loss: 3.0250717997550964
Epoch 65/100, Loss: 3.40204156935215
Epoch 66/100, Loss: 3.5315486565232277
Epoch 67/100, Loss: 3.282765105366707
Epoch 68/100, Loss: 4.293322205543518
Epoch 69/100, Loss: 3.2096465080976486
Epoch 70/100, Loss: 3.546163886785507
Epoch 71/100, Loss: 3.3187911435961723
Epoch 72/100, Loss: 3.359676733613014
Epoch 73/100, Loss: 3.1030426546931267
Epoch 74/100, Loss: 3.1930863186717033
Epoch 75/100, Loss: 3.234608367085457
Epoch 76/100, Loss: 3.014372393488884
Epoch 77/100, Loss: 3.2179538905620575

Epoch 78/100, Loss: 2.9985919818282127
Epoch 79/100, Loss: 2.964771032333374
Epoch 80/100, Loss: 3.053671233355999
Epoch 81/100, Loss: 3.0158137530088425
Epoch 82/100, Loss: 3.3922220021486282
Epoch 83/100, Loss: 3.7299137711524963
Epoch 84/100, Loss: 3.248346172273159
Epoch 85/100, Loss: 3.3746826127171516
Epoch 86/100, Loss: 3.2328541353344917
Epoch 87/100, Loss: 3.3806723579764366
Epoch 88/100, Loss: 3.1360146030783653
Epoch 89/100, Loss: 3.3150754794478416
Epoch 90/100, Loss: 3.3522388860583305
Epoch 91/100, Loss: 3.3571801632642746
Epoch 92/100, Loss: 3.124433994293213
Epoch 93/100, Loss: 3.113113611936569
Epoch 94/100, Loss: 3.2796918228268623

Epoch 95/100, Loss: 3.005519300699234
Epoch 96/100, Loss: 3.1427491828799248
Epoch 97/100, Loss: 3.5675253197550774
Epoch 98/100, Loss: 3.5098003298044205
Epoch 99/100, Loss: 3.050812490284443
Epoch 100/100, Loss: 3.1070554479956627
Fold 4/5 done
Epoch 1/100, Loss: 1.7069954574108124
Epoch 2/100, Loss: 1.7174213752150536
Epoch 3/100, Loss: 1.768635243177414
Epoch 4/100, Loss: 1.7342887446284294
Epoch 5/100, Loss: 1.6662610620260239
Epoch 6/100, Loss: 1.6876638606190681

Epoch 7/100, Loss: 1.721661500632763
Epoch 8/100, Loss: 1.7896310910582542
Epoch 9/100, Loss: 1.738043587654829
Epoch 10/100, Loss: 1.6625470370054245
Epoch 11/100, Loss: 1.6098049730062485
Epoch 12/100, Loss: 1.806266687810421
Epoch 13/100, Loss: 1.6728035882115364
Epoch 14/100, Loss: 1.6192817986011505
Epoch 15/100, Loss: 1.6575245559215546
Epoch 16/100, Loss: 1.7046320214867592
Epoch 17/100, Loss: 1.7487002313137054
Epoch 18/100, Loss: 1.5838867202401161
Epoch 19/100, Loss: 1.6468671597540379
Epoch 20/100, Loss: 1.6356316283345222
Epoch 21/100, Loss: 1.734612874686718

Epoch 22/100, Loss: 1.67038843780756
Epoch 23/100, Loss: 1.6859115809202194
Epoch 24/100, Loss: 1.682744812220335
Epoch 25/100, Loss: 1.7778316587209702
Epoch 26/100, Loss: 1.7525271475315094
Epoch 27/100, Loss: 1.721642628312111
Epoch 28/100, Loss: 1.6990168988704681
Epoch 29/100, Loss: 1.588443148881197
Epoch 30/100, Loss: 1.6570327505469322
Epoch 31/100, Loss: 1.679975837469101
Epoch 32/100, Loss: 1.6613469570875168
Epoch 33/100, Loss: 1.7482316754758358
Epoch 34/100, Loss: 1.5957626774907112
Epoch 35/100, Loss: 1.6805567368865013
Epoch 36/100, Loss: 1.6102065369486809

Epoch 37/100, Loss: 1.575065754354
Epoch 38/100, Loss: 1.9485089033842087
Epoch 39/100, Loss: 1.7930903509259224
Epoch 40/100, Loss: 1.6064252331852913
Epoch 41/100, Loss: 1.8007291667163372
Epoch 42/100, Loss: 1.6972138807177544
Epoch 43/100, Loss: 1.7486656606197357
Epoch 44/100, Loss: 1.643850665539503
Epoch 45/100, Loss: 1.6358116194605827
Epoch 46/100, Loss: 1.7757186479866505
Epoch 47/100, Loss: 1.675596222281456
Epoch 48/100, Loss: 1.656347580254078
Epoch 49/100, Loss: 1.7064896896481514
Epoch 50/100, Loss: 1.6647423580288887
Epoch 51/100, Loss: 1.694336399435997
Epoch 52/100, Loss: 1.7733459658920765
Epoch 53/100, Loss: 1.6959257572889328
Epoch 54/100, Loss: 1.8050592839717865

Epoch 55/100, Loss: 1.7571628130972385
Epoch 56/100, Loss: 1.6552201583981514
Epoch 57/100, Loss: 1.634898267686367
Epoch 58/100, Loss: 1.7159782126545906
Epoch 59/100, Loss: 1.6302117928862572
Epoch 60/100, Loss: 1.7238698899745941
Epoch 61/100, Loss: 1.6474230736494064
Epoch 62/100, Loss: 1.9024660922586918
Epoch 63/100, Loss: 1.6449095159769058
Epoch 64/100, Loss: 1.581168346107006
Epoch 65/100, Loss: 1.67998818308115
Epoch 66/100, Loss: 1.7521563097834587
Epoch 67/100, Loss: 1.8177175223827362
Epoch 68/100, Loss: 1.6268198937177658
Epoch 69/100, Loss: 1.6648856848478317

Epoch 70/100, Loss: 1.6974961906671524
Epoch 71/100, Loss: 1.7900784835219383
Epoch 72/100, Loss: 1.72441878169775
Epoch 73/100, Loss: 1.6841182485222816
Epoch 74/100, Loss: 1.7019989639520645
Epoch 75/100, Loss: 1.6319009736180305
Epoch 76/100, Loss: 1.7308470904827118
Epoch 77/100, Loss: 1.6251276955008507
Epoch 78/100, Loss: 1.7918235212564468
Epoch 79/100, Loss: 1.7420797869563103
Epoch 80/100, Loss: 1.7175204455852509
Epoch 81/100, Loss: 1.7381179556250572
Epoch 82/100, Loss: 1.6607603281736374
Epoch 83/100, Loss: 1.7235995307564735
Epoch 84/100, Loss: 1.6933659091591835
Epoch 85/100, Loss: 1.7421742752194405

Epoch 86/100, Loss: 1.7186598144471645
Epoch 87/100, Loss: 1.7388661354780197
Epoch 88/100, Loss: 1.7082982063293457
Epoch 89/100, Loss: 1.6839435547590256
Epoch 90/100, Loss: 1.6804335415363312
Epoch 91/100, Loss: 1.8645017072558403
Epoch 92/100, Loss: 1.6129843071103096
Epoch 93/100, Loss: 1.7301015406847
Epoch 94/100, Loss: 1.7845942676067352
Epoch 95/100, Loss: 1.6230056956410408
Epoch 96/100, Loss: 1.6172618344426155
Epoch 97/100, Loss: 1.6400361955165863
Epoch 98/100, Loss: 1.7836412712931633
Epoch 99/100, Loss: 1.6813677288591862
Epoch 100/100, Loss: 1.796965777873993
Fold 5/5 done

In [11]:
ap = average_precision_score(y_true, anomaly_scores)
print(f"Deep SVDD AP (5-fold CV) = {ap:.4f}")
sb.glue("GBG500_ap_spectral_deep_svdd", float(ap))

Deep SVDD AP (5-fold CV) = 0.5711