In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import average_precision_score
from sklearn.model_selection import StratifiedKFold
from pyod.models.deep_svdd import DeepSVDD
import sys
import scrapbook as sb

sys.path.append('..')
from utils import reshape_to_numpy, interpolate_missing_values, denoise_data, compute_spectrograms, time_avg_pooling

In [2]:
seed = 1
sampling_rate = 10
nperseg=64
noverlap=32
accel_cutoff = 0.4
accel_order = 30
gyro_cutoff = 0.6
gyro_order = 20
batch_size = 32
epochs = 100
hidden_neurons = [128, 64, 32]
n_splits = 5

In [3]:
# Parameters
seed = 22

In [4]:
rng = np.random.RandomState(seed)

In [5]:
data = pd.read_parquet("../data/GBG500.parquet")
data

,ride_id,time_index,ax,ay,az,rx,ry,rz
0,005043f1a7520cebf1e17fd166a00a3190e2433530f236...,0,-2.512796,-9.385012,-1.053078,-0.009155,0.009155,-0.201416
1,005043f1a7520cebf1e17fd166a00a3190e2433530f236...,100,-2.491268,-9.385012,-1.079390,-0.036621,0.027465,-0.155639
2,005043f1a7520cebf1e17fd166a00a3190e2433530f236...,200,-2.534324,-9.382022,-1.030952,0.036621,0.027465,-0.073242
3,005043f1a7520cebf1e17fd166a00a3190e2433530f236...,300,-2.488278,-9.383218,-1.091948,-0.045776,0.036621,-0.183105
4,005043f1a7520cebf1e17fd166a00a3190e2433530f236...,400,-2.483494,-9.382022,-1.100320,-0.045776,0.027465,-0.192260
...,...,...,...,...,...,...,...,...
1529542,ffb6f2f5dc6ba768d88dc0bc1af4cad235526aa9e24168...,241300,0.459862,-9.140430,-3.318900,1.556396,-0.091552,0.274658
1529543,ffb6f2f5dc6ba768d88dc0bc1af4cad235526aa9e24168...,241400,0.455676,-9.140430,-3.321292,1.583861,-0.119018,0.274658
1529544,ffb6f2f5dc6ba768d88dc0bc1af4cad235526aa9e24168...,241500,0.459862,-9.139832,-3.317704,1.583861,-0.109863,0.274658
1529545,ffb6f2f5dc6ba768d88dc0bc1af4cad235526aa9e24168...,241600,0.456274,-9.142224,-3.321292,1.574707,-0.137329,0.283813
1529546,ffb6f2f5dc6ba768d88dc0bc1af4cad235526aa9e24168...,241700,0.458666,-9.139832,-3.320694,1.574707,-0.137329,0.274658

In [6]:
labels = pd.read_csv("../data/GBG500_labels.csv")
labels.columns = labels.columns.str.lower()
ride_order_df = pd.DataFrame({"ride_id": data["ride_id"].unique()})
labels_sorted = ride_order_df.merge(
    labels,
    on="ride_id",
    how="left"
)
labels_sorted

                                               ride_id        label
0    005043f1a7520cebf1e17fd166a00a3190e2433530f236...         Safe
1    00d223cb7aecc9c0cc5871e32a6c45027a068eba07c572...     Reckless
2    02288a4aeca044203394e982e76b87818021dea2b34df9...         Safe
3    0236bdcf13d473ea24d97f5eaeea459f257dffac005694...  Bad weather
4    0238e5dd85143f1b6c59b200bc32f14361b8fc84c51a87...         Safe
..                                                 ...          ...
495  fe5d7f84d692bbccad8bd566a3ad5c3108fa9f90acd671...         Safe
496  fe67169632306d4668b2affedef510df2cb43e2fb41220...         Safe
497  fee44667fdc8ab4995c702fc3bd36178de0b1ca2c64687...         Safe
498  ff79b2e945b93c2a5efc3a06365267b3a160e7849ba57d...         Safe
499  ffb6f2f5dc6ba768d88dc0bc1af4cad235526aa9e24168...         Safe

[500 rows x 2 columns]

In [7]:
data_np = reshape_to_numpy(
    data,
    features = ["ax", "ay", "az", "rx", "ry", "rz"],
    max_timestamps = 4800
)

data_np_clean = interpolate_missing_values(
    data_np,
    method='linear',
    limit=None
)

data_np_clean = denoise_data(
    data=data_np_clean,
    accel_indices=[0, 1, 2],
    gyro_indices=[3, 4, 5],
    accel_cutoff=accel_cutoff,
    accel_order=accel_order,
    gyro_cutoff=gyro_cutoff,
    gyro_order=gyro_order,
)

In [8]:
# Compute spectrograms for all rides
spectrograms_array = compute_spectrograms(data_np_clean, sampling_rate, nperseg, noverlap)
spectrograms_array.shape

(500, 149, 6, 33)

In [9]:
# Aggregate spectrograms using time-averaged pooling
X_feat = time_avg_pooling(spectrograms_array)
X_feat.shape

(500, 198)

In [10]:
# 5-fold stratified CV with Deep SVDD
skf = StratifiedKFold(n_splits=n_splits, shuffle=True, random_state=rng.randint(1000))
y_true = (labels_sorted['label'] == 'Reckless').astype(int).values
anomaly_scores = np.full(len(y_true), np.nan)

for fold, (train_idx, test_idx) in enumerate(skf.split(X_feat, y_true)):
    sc = StandardScaler()
    X_train = sc.fit_transform(X_feat[train_idx])
    X_test = sc.transform(X_feat[test_idx])

    np.random.seed(rng.randint(1000))
    model = DeepSVDD(
        n_features=X_train.shape[1],
        hidden_neurons=hidden_neurons,
        epochs=epochs,
        batch_size=batch_size,
        random_state=rng.randint(1000),
    )
    model.fit(X_train)
    anomaly_scores[test_idx] = model.decision_function(X_test)
    print(f"Fold {fold+1}/{n_splits} done")

Epoch 1/100, Loss: 2.014463283121586
Epoch 2/100, Loss: 2.0464963987469673
Epoch 3/100, Loss: 1.8609494641423225
Epoch 4/100, Loss: 1.943739265203476
Epoch 5/100, Loss: 1.9864753037691116
Epoch 6/100, Loss: 1.9140448048710823
Epoch 7/100, Loss: 2.0219075679779053
Epoch 8/100, Loss: 2.042791113257408
Epoch 9/100, Loss: 1.7865092009305954
Epoch 10/100, Loss: 2.0305039659142494
Epoch 11/100, Loss: 1.8495717495679855
Epoch 12/100, Loss: 1.8840836212038994
Epoch 13/100, Loss: 1.9806364551186562
Epoch 14/100, Loss: 2.1691958010196686
Epoch 15/100, Loss: 2.0472176149487495

Epoch 16/100, Loss: 2.0177528262138367
Epoch 17/100, Loss: 2.009452097117901
Epoch 18/100, Loss: 2.06561391800642
Epoch 19/100, Loss: 2.04171671718359
Epoch 20/100, Loss: 2.047280788421631
Epoch 21/100, Loss: 2.0547041594982147
Epoch 22/100, Loss: 2.0352121740579605
Epoch 23/100, Loss: 2.1120061799883842
Epoch 24/100, Loss: 1.9081853926181793
Epoch 25/100, Loss: 1.919365182518959
Epoch 26/100, Loss: 1.867351621389389
Epoch 27/100, Loss: 2.1787073761224747
Epoch 28/100, Loss: 2.0563204288482666
Epoch 29/100, Loss: 2.135510064661503
Epoch 30/100, Loss: 1.9587292149662971

Epoch 31/100, Loss: 2.195937991142273
Epoch 32/100, Loss: 1.9044745340943336
Epoch 33/100, Loss: 1.8968779668211937
Epoch 34/100, Loss: 1.9668779373168945
Epoch 35/100, Loss: 1.9298179298639297
Epoch 36/100, Loss: 2.1467130556702614
Epoch 37/100, Loss: 1.985268473625183
Epoch 38/100, Loss: 1.9676236435770988
Epoch 39/100, Loss: 1.9435829259455204
Epoch 40/100, Loss: 1.9920622557401657
Epoch 41/100, Loss: 1.9712084904313087
Epoch 42/100, Loss: 2.0855205431580544
Epoch 43/100, Loss: 2.4999751299619675
Epoch 44/100, Loss: 1.971714735031128
Epoch 45/100, Loss: 2.063270553946495

Epoch 46/100, Loss: 2.2719646468758583
Epoch 47/100, Loss: 2.0559543073177338
Epoch 48/100, Loss: 2.0322984233498573
Epoch 49/100, Loss: 2.1584637612104416
Epoch 50/100, Loss: 1.9719240963459015
Epoch 51/100, Loss: 2.1604555547237396
Epoch 52/100, Loss: 1.8601328432559967
Epoch 53/100, Loss: 2.025032326579094
Epoch 54/100, Loss: 1.9246907085180283
Epoch 55/100, Loss: 2.020775094628334
Epoch 56/100, Loss: 2.0600955113768578
Epoch 57/100, Loss: 2.047623112797737
Epoch 58/100, Loss: 2.1379852443933487
Epoch 59/100, Loss: 2.2802829444408417
Epoch 60/100, Loss: 1.7758303955197334

Epoch 61/100, Loss: 1.9240906611084938
Epoch 62/100, Loss: 2.0611970126628876
Epoch 63/100, Loss: 1.9975990802049637
Epoch 64/100, Loss: 2.077221356332302
Epoch 65/100, Loss: 2.0694601610302925
Epoch 66/100, Loss: 2.0109490007162094
Epoch 67/100, Loss: 2.0593843534588814
Epoch 68/100, Loss: 2.3480141162872314
Epoch 69/100, Loss: 2.0450645238161087
Epoch 70/100, Loss: 1.938174158334732
Epoch 71/100, Loss: 1.872788280248642
Epoch 72/100, Loss: 2.0089920088648796
Epoch 73/100, Loss: 2.0409997180104256
Epoch 74/100, Loss: 2.02852813154459
Epoch 75/100, Loss: 2.0291611552238464

Epoch 76/100, Loss: 2.175193041563034
Epoch 77/100, Loss: 2.1409614980220795
Epoch 78/100, Loss: 2.013727128505707
Epoch 79/100, Loss: 1.9585969373583794
Epoch 80/100, Loss: 1.7719859182834625
Epoch 81/100, Loss: 1.89893489331007
Epoch 82/100, Loss: 1.9504418075084686
Epoch 83/100, Loss: 2.1528570726513863
Epoch 84/100, Loss: 2.0474256798624992
Epoch 85/100, Loss: 1.9091298654675484
Epoch 86/100, Loss: 2.164155252277851
Epoch 87/100, Loss: 2.045221045613289
Epoch 88/100, Loss: 1.9213908687233925
Epoch 89/100, Loss: 2.0166587457060814
Epoch 90/100, Loss: 1.9140733554959297

Epoch 91/100, Loss: 1.8301751017570496
Epoch 92/100, Loss: 2.1173115968704224
Epoch 93/100, Loss: 1.9939652979373932
Epoch 94/100, Loss: 2.0282718017697334
Epoch 95/100, Loss: 2.075022667646408
Epoch 96/100, Loss: 2.0276331901550293
Epoch 97/100, Loss: 2.016849271953106
Epoch 98/100, Loss: 1.851677529513836
Epoch 99/100, Loss: 2.099403664469719
Epoch 100/100, Loss: 2.015916422009468
Fold 1/5 done
Epoch 1/100, Loss: 2.853786826133728
Epoch 2/100, Loss: 2.363885946571827
Epoch 3/100, Loss: 2.1563608795404434
Epoch 4/100, Loss: 2.285119764506817

Epoch 5/100, Loss: 2.117009475827217
Epoch 6/100, Loss: 2.2242462188005447
Epoch 7/100, Loss: 2.311791144311428
Epoch 8/100, Loss: 2.256658524274826
Epoch 9/100, Loss: 2.2768619060516357
Epoch 10/100, Loss: 1.9943010434508324
Epoch 11/100, Loss: 2.202252395451069
Epoch 12/100, Loss: 2.619301237165928
Epoch 13/100, Loss: 2.2470830604434013
Epoch 14/100, Loss: 2.2047778591513634
Epoch 15/100, Loss: 2.3479250073432922
Epoch 16/100, Loss: 2.3353060260415077
Epoch 17/100, Loss: 2.246978372335434
Epoch 18/100, Loss: 2.2228673920035362
Epoch 19/100, Loss: 2.1216474771499634

Epoch 20/100, Loss: 2.150760918855667
Epoch 21/100, Loss: 2.3042468577623367
Epoch 22/100, Loss: 2.3314832374453545
Epoch 23/100, Loss: 2.2002815529704094
Epoch 24/100, Loss: 2.2540343776345253
Epoch 25/100, Loss: 2.2224143519997597
Epoch 26/100, Loss: 2.4180666729807854
Epoch 27/100, Loss: 2.211466647684574
Epoch 28/100, Loss: 2.189260482788086
Epoch 29/100, Loss: 2.3469136133790016
Epoch 30/100, Loss: 2.4213302433490753
Epoch 31/100, Loss: 2.3496666103601456
Epoch 32/100, Loss: 2.2038586661219597
Epoch 33/100, Loss: 2.3720876276493073
Epoch 34/100, Loss: 2.2863636389374733

Epoch 35/100, Loss: 2.232953153550625
Epoch 36/100, Loss: 2.5566711872816086
Epoch 37/100, Loss: 2.267611548304558
Epoch 38/100, Loss: 3.1362946704030037
Epoch 39/100, Loss: 2.172131732106209
Epoch 40/100, Loss: 2.397959090769291
Epoch 41/100, Loss: 2.23156014084816
Epoch 42/100, Loss: 2.316038057208061
Epoch 43/100, Loss: 2.135500729084015
Epoch 44/100, Loss: 2.2153529599308968
Epoch 45/100, Loss: 2.3461762443184853
Epoch 46/100, Loss: 2.231390416622162
Epoch 47/100, Loss: 2.2688406631350517
Epoch 48/100, Loss: 2.3030708953738213

Epoch 49/100, Loss: 2.1917672753334045
Epoch 50/100, Loss: 2.2339910715818405
Epoch 51/100, Loss: 2.4563654363155365
Epoch 52/100, Loss: 2.436993107199669
Epoch 53/100, Loss: 2.2217312157154083
Epoch 54/100, Loss: 2.2592240050435066
Epoch 55/100, Loss: 2.141567274928093
Epoch 56/100, Loss: 2.136012576520443
Epoch 57/100, Loss: 2.2797607481479645
Epoch 58/100, Loss: 2.437747396528721
Epoch 59/100, Loss: 2.0574116557836533
Epoch 60/100, Loss: 2.348385736346245
Epoch 61/100, Loss: 2.3899273350834846
Epoch 62/100, Loss: 2.486285023391247

Epoch 63/100, Loss: 2.4324963316321373
Epoch 64/100, Loss: 2.4566324949264526
Epoch 65/100, Loss: 2.06573998183012
Epoch 66/100, Loss: 2.1816729307174683
Epoch 67/100, Loss: 2.2981790378689766
Epoch 68/100, Loss: 2.3767057433724403
Epoch 69/100, Loss: 2.3410582318902016
Epoch 70/100, Loss: 2.1931261867284775
Epoch 71/100, Loss: 2.858209013938904
Epoch 72/100, Loss: 2.3874471783638
Epoch 73/100, Loss: 2.394156113266945
Epoch 74/100, Loss: 2.1910282596945763
Epoch 75/100, Loss: 2.848830245435238
Epoch 76/100, Loss: 2.240701213479042
Epoch 77/100, Loss: 2.2519479170441628

Epoch 78/100, Loss: 2.144939973950386
Epoch 79/100, Loss: 2.328122057020664
Epoch 80/100, Loss: 2.1692186817526817
Epoch 81/100, Loss: 2.4641890227794647
Epoch 82/100, Loss: 2.003989428281784
Epoch 83/100, Loss: 2.208296813070774
Epoch 84/100, Loss: 2.387864202260971
Epoch 85/100, Loss: 2.2559400722384453
Epoch 86/100, Loss: 2.1925860345363617
Epoch 87/100, Loss: 2.3357502445578575
Epoch 88/100, Loss: 2.1941694244742393
Epoch 89/100, Loss: 2.079728350043297
Epoch 90/100, Loss: 2.4190468415617943
Epoch 91/100, Loss: 2.1365572810173035
Epoch 92/100, Loss: 2.2705036848783493

Epoch 93/100, Loss: 2.33600502461195
Epoch 94/100, Loss: 2.187330923974514
Epoch 95/100, Loss: 2.257834531366825
Epoch 96/100, Loss: 2.3389697521924973
Epoch 97/100, Loss: 2.343264661729336
Epoch 98/100, Loss: 2.3028474599123
Epoch 99/100, Loss: 2.3170283883810043
Epoch 100/100, Loss: 2.2865542843937874
Fold 2/5 done
Epoch 1/100, Loss: 2.7840844243764877
Epoch 2/100, Loss: 2.8771761655807495
Epoch 3/100, Loss: 2.522388346493244
Epoch 4/100, Loss: 3.1672167256474495
Epoch 5/100, Loss: 2.8315280079841614
Epoch 6/100, Loss: 2.787908859550953

Epoch 7/100, Loss: 2.9026902690529823
Epoch 8/100, Loss: 2.718081682920456
Epoch 9/100, Loss: 2.3134244233369827
Epoch 10/100, Loss: 3.0662916749715805
Epoch 11/100, Loss: 2.459315247833729
Epoch 12/100, Loss: 2.9878324642777443
Epoch 13/100, Loss: 2.738764025270939
Epoch 14/100, Loss: 3.0261775702238083
Epoch 15/100, Loss: 2.6486034095287323
Epoch 16/100, Loss: 2.4840061366558075
Epoch 17/100, Loss: 2.833532489836216
Epoch 18/100, Loss: 2.7944318652153015
Epoch 19/100, Loss: 2.77531336247921
Epoch 20/100, Loss: 2.7077597081661224
Epoch 21/100, Loss: 2.5157360285520554

Epoch 22/100, Loss: 2.924484819173813
Epoch 23/100, Loss: 2.858713798224926
Epoch 24/100, Loss: 2.9813093543052673
Epoch 25/100, Loss: 2.410352684557438
Epoch 26/100, Loss: 2.8508410155773163
Epoch 27/100, Loss: 2.668752670288086
Epoch 28/100, Loss: 2.8358878567814827
Epoch 29/100, Loss: 2.788334257900715
Epoch 30/100, Loss: 3.007063016295433
Epoch 31/100, Loss: 2.703336715698242
Epoch 32/100, Loss: 3.532492123544216
Epoch 33/100, Loss: 2.6843473315238953
Epoch 34/100, Loss: 2.585243195295334
Epoch 35/100, Loss: 2.6115906685590744
Epoch 36/100, Loss: 3.001566767692566

Epoch 37/100, Loss: 2.5167276710271835
Epoch 38/100, Loss: 2.7471163123846054
Epoch 39/100, Loss: 2.5860496535897255
Epoch 40/100, Loss: 2.911910232156515
Epoch 41/100, Loss: 2.8483588248491287
Epoch 42/100, Loss: 2.6532146334648132
Epoch 43/100, Loss: 2.737084373831749
Epoch 44/100, Loss: 2.5990412905812263
Epoch 45/100, Loss: 2.823952503502369
Epoch 46/100, Loss: 2.947383187711239
Epoch 47/100, Loss: 2.7503993436694145
Epoch 48/100, Loss: 2.4912470653653145
Epoch 49/100, Loss: 2.873270235955715
Epoch 50/100, Loss: 2.8063644096255302
Epoch 51/100, Loss: 2.945725865662098
Epoch 52/100, Loss: 2.5328269451856613

Epoch 53/100, Loss: 2.8303731828927994
Epoch 54/100, Loss: 2.8836900666356087
Epoch 55/100, Loss: 2.387292928993702
Epoch 56/100, Loss: 2.6616875007748604
Epoch 57/100, Loss: 2.8613921478390694
Epoch 58/100, Loss: 2.744310177862644
Epoch 59/100, Loss: 2.690963089466095
Epoch 60/100, Loss: 2.6627963557839394
Epoch 61/100, Loss: 2.838073968887329
Epoch 62/100, Loss: 2.3656895086169243
Epoch 63/100, Loss: 2.7015645429491997
Epoch 64/100, Loss: 2.7813603207468987
Epoch 65/100, Loss: 2.8621891662478447
Epoch 66/100, Loss: 2.532783195376396
Epoch 67/100, Loss: 2.381197452545166
Epoch 68/100, Loss: 2.8578439578413963
Epoch 69/100, Loss: 2.9419966861605644

Epoch 70/100, Loss: 2.542993552982807
Epoch 71/100, Loss: 2.5894050374627113
Epoch 72/100, Loss: 2.5478283017873764
Epoch 73/100, Loss: 2.680586062371731
Epoch 74/100, Loss: 2.398439086973667
Epoch 75/100, Loss: 2.9295207038521767
Epoch 76/100, Loss: 2.650373190641403
Epoch 77/100, Loss: 2.603612743318081
Epoch 78/100, Loss: 2.420075237751007
Epoch 79/100, Loss: 2.993667796254158
Epoch 80/100, Loss: 2.566135749220848
Epoch 81/100, Loss: 2.9212455078959465
Epoch 82/100, Loss: 2.8044492080807686
Epoch 83/100, Loss: 2.5291826650500298
Epoch 84/100, Loss: 3.9976715072989464
Epoch 85/100, Loss: 2.8266719058156013
Epoch 86/100, Loss: 2.7395568192005157
Epoch 87/100, Loss: 2.694528564810753

Epoch 88/100, Loss: 2.9604540318250656
Epoch 89/100, Loss: 2.5292345136404037
Epoch 90/100, Loss: 3.1167702078819275
Epoch 91/100, Loss: 2.645109213888645
Epoch 92/100, Loss: 2.7093347683548927
Epoch 93/100, Loss: 2.6943904384970665
Epoch 94/100, Loss: 2.8712414130568504
Epoch 95/100, Loss: 2.860433578491211
Epoch 96/100, Loss: 3.0378533080220222
Epoch 97/100, Loss: 2.533060558140278
Epoch 98/100, Loss: 2.5126563534140587
Epoch 99/100, Loss: 2.644840158522129
Epoch 100/100, Loss: 2.4505230709910393
Fold 3/5 done
Epoch 1/100, Loss: 3.676148660480976
Epoch 2/100, Loss: 3.6710493564605713
Epoch 3/100, Loss: 3.902415193617344

Epoch 4/100, Loss: 3.803524360060692
Epoch 5/100, Loss: 3.6063712537288666
Epoch 6/100, Loss: 4.033149257302284
Epoch 7/100, Loss: 3.322267860174179
Epoch 8/100, Loss: 3.771690085530281
Epoch 9/100, Loss: 3.4784999787807465
Epoch 10/100, Loss: 3.522433042526245
Epoch 11/100, Loss: 3.812159776687622
Epoch 12/100, Loss: 3.6077577620744705
Epoch 13/100, Loss: 3.7677036076784134
Epoch 14/100, Loss: 4.083249889314175
Epoch 15/100, Loss: 3.554000608623028
Epoch 16/100, Loss: 3.4601220935583115
Epoch 17/100, Loss: 3.3865977227687836
Epoch 18/100, Loss: 3.4883664399385452
Epoch 19/100, Loss: 3.6230909526348114
Epoch 20/100, Loss: 3.643935516476631

Epoch 21/100, Loss: 3.4678133577108383
Epoch 22/100, Loss: 3.5359463691711426
Epoch 23/100, Loss: 3.7147557586431503
Epoch 24/100, Loss: 3.4021965116262436
Epoch 25/100, Loss: 3.6106738075613976
Epoch 26/100, Loss: 3.410993270576
Epoch 27/100, Loss: 3.7378219217061996
Epoch 28/100, Loss: 3.469608783721924
Epoch 29/100, Loss: 3.7800056412816048
Epoch 30/100, Loss: 3.324436902999878
Epoch 31/100, Loss: 3.3330964148044586
Epoch 32/100, Loss: 3.727001741528511
Epoch 33/100, Loss: 3.4434655606746674
Epoch 34/100, Loss: 3.574883058667183
Epoch 35/100, Loss: 3.6335259452462196
Epoch 36/100, Loss: 3.382943645119667
Epoch 37/100, Loss: 3.537992477416992

Epoch 38/100, Loss: 3.8574788570404053
Epoch 39/100, Loss: 3.5472095906734467
Epoch 40/100, Loss: 3.4735776782035828
Epoch 41/100, Loss: 3.603980451822281
Epoch 42/100, Loss: 3.5832248851656914
Epoch 43/100, Loss: 3.3955477476119995
Epoch 44/100, Loss: 3.48092433065176
Epoch 45/100, Loss: 3.4052569046616554
Epoch 46/100, Loss: 3.4859878197312355
Epoch 47/100, Loss: 3.604169085621834
Epoch 48/100, Loss: 3.434421069920063
Epoch 49/100, Loss: 3.8022413849830627
Epoch 50/100, Loss: 3.952213242650032
Epoch 51/100, Loss: 3.5631575658917427
Epoch 52/100, Loss: 3.325033724308014
Epoch 53/100, Loss: 3.5356392711400986
Epoch 54/100, Loss: 3.615642286837101

Epoch 55/100, Loss: 3.9442036896944046
Epoch 56/100, Loss: 3.614632248878479
Epoch 57/100, Loss: 3.3994801864027977
Epoch 58/100, Loss: 3.7659043669700623
Epoch 59/100, Loss: 3.6894479021430016
Epoch 60/100, Loss: 3.7357953563332558
Epoch 61/100, Loss: 3.5387141406536102
Epoch 62/100, Loss: 3.465248256921768
Epoch 63/100, Loss: 3.7512563467025757
Epoch 64/100, Loss: 3.3901101127266884
Epoch 65/100, Loss: 3.629193089902401
Epoch 66/100, Loss: 3.370042286813259
Epoch 67/100, Loss: 3.7313754856586456
Epoch 68/100, Loss: 3.5101017504930496
Epoch 69/100, Loss: 3.577189676463604
Epoch 70/100, Loss: 3.6056231558322906
Epoch 71/100, Loss: 3.212186962366104

Epoch 72/100, Loss: 3.7266508787870407
Epoch 73/100, Loss: 3.4745801389217377
Epoch 74/100, Loss: 3.3733659982681274
Epoch 75/100, Loss: 3.5870633348822594
Epoch 76/100, Loss: 3.5965849682688713
Epoch 77/100, Loss: 3.3980613201856613
Epoch 78/100, Loss: 3.7679604589939117
Epoch 79/100, Loss: 3.4489873200654984
Epoch 80/100, Loss: 3.4997537434101105
Epoch 81/100, Loss: 3.5231520384550095
Epoch 82/100, Loss: 3.4322339594364166
Epoch 83/100, Loss: 3.547252394258976
Epoch 84/100, Loss: 3.665776416659355
Epoch 85/100, Loss: 3.439333848655224
Epoch 86/100, Loss: 3.556041456758976
Epoch 87/100, Loss: 3.731357768177986
Epoch 88/100, Loss: 3.6237868070602417

Epoch 89/100, Loss: 3.4740914776921272
Epoch 90/100, Loss: 3.631114639341831
Epoch 91/100, Loss: 3.406587526202202
Epoch 92/100, Loss: 3.5776363387703896
Epoch 93/100, Loss: 3.604960158467293
Epoch 94/100, Loss: 3.6884812861680984
Epoch 95/100, Loss: 3.5211576521396637
Epoch 96/100, Loss: 4.07072102278471
Epoch 97/100, Loss: 3.915356010198593
Epoch 98/100, Loss: 3.5476194471120834
Epoch 99/100, Loss: 3.670103684067726
Epoch 100/100, Loss: 3.77607262134552
Fold 4/5 done
Epoch 1/100, Loss: 1.7735665291547775
Epoch 2/100, Loss: 1.8304216489195824
Epoch 3/100, Loss: 1.8089128360152245
Epoch 4/100, Loss: 1.839647963643074

Epoch 5/100, Loss: 1.8621252700686455
Epoch 6/100, Loss: 1.7003589496016502
Epoch 7/100, Loss: 1.8715596124529839
Epoch 8/100, Loss: 1.8243390247225761
Epoch 9/100, Loss: 1.863011747598648
Epoch 10/100, Loss: 1.8339660614728928
Epoch 11/100, Loss: 1.813169352710247
Epoch 12/100, Loss: 1.8340039029717445
Epoch 13/100, Loss: 1.8079003244638443
Epoch 14/100, Loss: 1.7524804845452309
Epoch 15/100, Loss: 1.8493149131536484
Epoch 16/100, Loss: 1.8579855561256409
Epoch 17/100, Loss: 1.881640039384365
Epoch 18/100, Loss: 1.7538486793637276
Epoch 19/100, Loss: 1.8767124786973
Epoch 20/100, Loss: 1.7755982354283333
Epoch 21/100, Loss: 1.7263399958610535

Epoch 22/100, Loss: 1.7385343462228775
Epoch 23/100, Loss: 1.8673001006245613
Epoch 24/100, Loss: 1.768380343914032
Epoch 25/100, Loss: 1.7257449105381966
Epoch 26/100, Loss: 1.8281654566526413
Epoch 27/100, Loss: 1.7942200377583504
Epoch 28/100, Loss: 1.7786641865968704
Epoch 29/100, Loss: 1.7747187539935112
Epoch 30/100, Loss: 1.8015179932117462
Epoch 31/100, Loss: 1.8647039011120796
Epoch 32/100, Loss: 1.8139694854617119
Epoch 33/100, Loss: 1.8542261347174644
Epoch 34/100, Loss: 1.9048432782292366

Epoch 35/100, Loss: 1.7682108283042908
Epoch 36/100, Loss: 1.8480940833687782
Epoch 37/100, Loss: 1.7883743718266487
Epoch 38/100, Loss: 1.8154473900794983
Epoch 39/100, Loss: 1.7524662539362907
Epoch 40/100, Loss: 1.7614002227783203
Epoch 41/100, Loss: 1.8456996157765388
Epoch 42/100, Loss: 1.8309847488999367
Epoch 43/100, Loss: 1.7739462405443192
Epoch 44/100, Loss: 1.8482829257845879

Epoch 45/100, Loss: 1.7987365052103996
Epoch 46/100, Loss: 1.8673278540372849
Epoch 47/100, Loss: 1.7663814723491669
Epoch 48/100, Loss: 1.7571901232004166
Epoch 49/100, Loss: 1.8431956395506859
Epoch 50/100, Loss: 1.8376993238925934
Epoch 51/100, Loss: 1.7481935247778893
Epoch 52/100, Loss: 1.8237242698669434
Epoch 53/100, Loss: 1.8252007514238358
Epoch 54/100, Loss: 1.7692571803927422
Epoch 55/100, Loss: 1.767293781042099
Epoch 56/100, Loss: 1.7483011484146118
Epoch 57/100, Loss: 1.7997987046837807

Epoch 58/100, Loss: 1.7765434607863426
Epoch 59/100, Loss: 1.7858798503875732
Epoch 60/100, Loss: 1.7909551858901978
Epoch 61/100, Loss: 1.7551319748163223
Epoch 62/100, Loss: 1.8044121786952019
Epoch 63/100, Loss: 1.7839037626981735
Epoch 64/100, Loss: 1.8091571182012558
Epoch 65/100, Loss: 1.784279614686966
Epoch 66/100, Loss: 1.7732832729816437
Epoch 67/100, Loss: 1.7976123318076134
Epoch 68/100, Loss: 1.822560541331768
Epoch 69/100, Loss: 1.8472137749195099
Epoch 70/100, Loss: 1.8214752152562141
Epoch 71/100, Loss: 1.799584448337555
Epoch 72/100, Loss: 1.8296763598918915

Epoch 73/100, Loss: 1.8010955303907394
Epoch 74/100, Loss: 1.7855473756790161
Epoch 75/100, Loss: 1.8471587747335434
Epoch 76/100, Loss: 1.8313969299197197
Epoch 77/100, Loss: 1.9022913724184036
Epoch 78/100, Loss: 1.8439863100647926
Epoch 79/100, Loss: 1.878814123570919
Epoch 80/100, Loss: 1.802818924188614
Epoch 81/100, Loss: 1.8004687130451202
Epoch 82/100, Loss: 1.7656378895044327
Epoch 83/100, Loss: 1.7954719364643097
Epoch 84/100, Loss: 1.868569903075695
Epoch 85/100, Loss: 1.8493643775582314
Epoch 86/100, Loss: 1.732563130557537
Epoch 87/100, Loss: 1.7666740417480469
Epoch 88/100, Loss: 1.877040557563305
Epoch 89/100, Loss: 1.8865623250603676
Epoch 90/100, Loss: 1.8093374148011208

Epoch 91/100, Loss: 1.8210698664188385
Epoch 92/100, Loss: 1.8492885380983353
Epoch 93/100, Loss: 1.9215306788682938
Epoch 94/100, Loss: 1.828782320022583
Epoch 95/100, Loss: 1.8695293888449669
Epoch 96/100, Loss: 1.8217668682336807
Epoch 97/100, Loss: 1.7742822393774986
Epoch 98/100, Loss: 1.8419889137148857
Epoch 99/100, Loss: 1.921316459774971
Epoch 100/100, Loss: 1.896826945245266
Fold 5/5 done

In [11]:
ap = average_precision_score(y_true, anomaly_scores)
print(f"Deep SVDD AP (5-fold CV) = {ap:.4f}")
sb.glue("GBG500_ap_spectral_deep_svdd", float(ap))

Deep SVDD AP (5-fold CV) = 0.6561