In [1]:
import copy
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
from sklearn.neighbors import LocalOutlierFactor
from sklearn.model_selection import GroupKFold
import torch
import torch.nn as nn
from torch.utils.data import DataLoader, TensorDataset
import lightning as L
from lightning.pytorch.callbacks import EarlyStopping
import sys
import scrapbook as sb
from statsmodels.discrete.conditional_models import ConditionalLogit

sys.path.append('..')
from utils import reshape_to_numpy, interpolate_missing_values, denoise_data, compute_spectrograms, time_avg_pooling

/home/marco/mnt/git/reckless-riding-detection/.venv/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [2]:
seed = 1
sampling_rate = 10
topple_delta_s = 10
nperseg=64
noverlap=32
accel_cutoff = 0.4
accel_order = 30
gyro_cutoff = 0.6
gyro_order = 20
batch_size = 128
patience = 15
encoder_hidden_dim1 = 128
encoder_hidden_dim2 = 64
encoding_dim = 32
decoder_hidden_dim1 = 64
decoder_hidden_dim2 = 128
lr=0.001
n_splits = 5

In [3]:
# Parameters
seed = 14

In [4]:
rng = np.random.RandomState(seed)

In [5]:
data = pd.read_parquet("../data/SRV3490.parquet")
data

,ride_id,crash_ride_id,city,time_index,ax,ay,az,rx,ry,rz,topple
0,804e23f63ec36c94ea840b66d98e53a90e0a69d4e66f0b...,ca1e869059a8de9fe0f38760d72d2ab8b5ee2363640d26...,6,0,-1.315454,-9.585049,-1.459023,0.002901,0.000763,0.001374,0.0
1,804e23f63ec36c94ea840b66d98e53a90e0a69d4e66f0b...,ca1e869059a8de9fe0f38760d72d2ab8b5ee2363640d26...,6,100,-1.312463,-9.586245,-1.448853,0.003054,0.001069,0.001832,0.0
2,804e23f63ec36c94ea840b66d98e53a90e0a69d4e66f0b...,ca1e869059a8de9fe0f38760d72d2ab8b5ee2363640d26...,6,200,-1.316650,-9.586843,-1.450050,0.002901,0.000763,0.001679,0.0
3,804e23f63ec36c94ea840b66d98e53a90e0a69d4e66f0b...,ca1e869059a8de9fe0f38760d72d2ab8b5ee2363640d26...,6,300,-1.311864,-9.582058,-1.462612,0.003054,0.001069,0.001679,0.0
4,804e23f63ec36c94ea840b66d98e53a90e0a69d4e66f0b...,ca1e869059a8de9fe0f38760d72d2ab8b5ee2363640d26...,6,400,-1.308873,-9.588638,-1.459023,0.002901,0.000916,0.001527,0.0
...,...,...,...,...,...,...,...,...,...,...,...
16891997,32c5563db5066b783ac7be8726e4f595ce2bff7b6169db...,None,1,246200,0.329610,-9.905089,-1.114456,0.008400,-0.004886,-0.022143,0.0
16891998,32c5563db5066b783ac7be8726e4f595ce2bff7b6169db...,None,1,246300,0.335593,-9.896714,-1.114456,0.008705,-0.004733,-0.022143,0.0
16891999,32c5563db5066b783ac7be8726e4f595ce2bff7b6169db...,None,1,246400,0.337985,-9.899705,-1.114456,0.008247,-0.004275,-0.022296,0.0
16892000,32c5563db5066b783ac7be8726e4f595ce2bff7b6169db...,None,1,246500,0.339182,-9.901499,-1.116251,0.008094,-0.004580,-0.022601,0.0
16892001,32c5563db5066b783ac7be8726e4f595ce2bff7b6169db...,None,1,246600,0.334994,-9.902696,-1.118644,0.008247,-0.004886,-0.022296,0.0

In [6]:
accidents = data["crash_ride_id"].unique()
accidents

array(['ca1e869059a8de9fe0f38760d72d2ab8b5ee2363640d266436ceafa457484436',
       '0b17f099646554b0a7e0fc928a42fb9c4cbc219b674429e4c96ca3d726aa2d3a',
       '5e8d45bc0232d8bf2c8a6bedea48f0c83ace631417581587e6c5218ff7c200cb',
       'c3427b7bbccb6f1e20f3f0e6f5d4d42ded2d53739f1bf35044acea4f8f9a6a26',
       '36e645db8f924cfca6adef4837ee83ecf77ba518d69fd0b6268e02b2c7b24fbe',
       'b2bf5aa795aee4cacc8e26432c36da571ec3860fd411889e80239e46adf45df4',
       'ce92a617053d58ab76025b7f7be93f7e37c7d62b4c74bfacf49b6859ca6d03fa',
       '5811130abbd499b89cd2bd8f3cd863536fe3e19b74f7883b17129f9d312826a2',
       'f1ec010707cb8d61ab46cc9710725ff4738c9f31834d5d974c61b65838e317a3',
       '29734d7c8c366a6a85a5871c8e45b0cbed4d7118584a404f72d56f7b5a9ef2f4',
       '87c625a557a5de3574765265ff6396ae56e9e91f9b0fb60982652adb80957adb',
       'e461c20e96c6db63d3a7f1f6f84603a89252e907fefed80216c93f6c45c2fcaf',
       '1b1abc5b1e4716de0a725f9b29c4c072a31f1e057f05028fd3284672b6071f4f',
       '20804a6a305aebcf6a332d39087599841a0f15d288c78daf4f7b89ba5a564d4d',
       '88ad434751d66cb1ebd39a3baafb341b80c6a95bf0e39d337bd9f9c96a7492aa',
       '698b01dbd3bae538614a5b25cea5ed5a858ae46b1510b46515ed1e9ca0b1c060',
       '460e6b513d03e8dc774819482baae8f8e792a66edc53baaff7ae6e308604d00b',
       'a8e679a7a7f80c01f6dbbf79c4448de705aea8ed4ddfe20533a8669a5c876c87',
       '9adbd4a3bf0b5f1443bf34730d1e91371d82897aa0444bd294f0fbb1de853a96',
       'ac1c4fa04b711fd190def3bd515601ca41f9260c6f82bc142c944d5ec458ad3f',
       'e73d731d7d0fdbb11efe9650d303c1e0ffae51e2f7a00babd2103194e43a90f4',
       '7ad2b6abcc28c671dcee6fc136ccc6ac405c3a8d1690c6190ca786b30b6672c2',
       '7d5fb1e7a04e572ba2ae24ad4175f1ce274760b1744a8ff98a89a29d173b4c9a',
       '14648295a1e9ad09482319c0a7258738e11ef1958d133e42bf8f0a963aebb62d',
       '181ce5c3e4cf9e0db4b0e4867a99d597dd35eae7353a45882a277dda0d38ee04',
       '367292886db67d7b8ecc007600eea68c94cc1915037cb49442cecedc53210bec',
       '0993669e116a5e64cc3276fbdf6d4ba02dee6a7f2ef2f6761a95bc1976ebcf2c',
       'f6e753f69f529304e201f7f8f17f0158839517de6756dd351cab13f988689d73',
       'a084461bf340e2a92c127465c7aa6a848e0c0ce5a79b50f77a49b4e3837cfb28',
       '963287055490f767ea7420ccea2d2a0c38b8388b65a7909fa317062b86c5386a',
       '6d9f3f7f66665201990680e29e5089fd4f809f3c0c5c5c0b4ed0c688464a69d2',
       '845dbb4463300ccf3be92743cf54e61aaa29525dfd12d09061e19938629a8904',
       '6924378d16c3a2b4f96a276972ce77da9a06477cf78d4fd1c21e5696a3a0030f',
       '5224e60da2a11fe0f6083fdb01eb5ee5e8010d7c3213b5993b6b3bc08d699414',
       '0aca669bab188fd6fbcede3b48e9beab0085990845e82e2d0515fa07c2bf2d54',
       '299fd3f1326bd5eb4e617f25e47e80bbd315767bb8a3392e7ad01b088a9bfd63',
       '3bbadb2158865276c7beff54168493b1cb72ec72c26b2fad93151d834b8e2d08',
       'c62f1ac481cb46dc03a6c53f5b1777c448a8118e337c7e9bf4ac53db44556ba8',
       '52bcd99583715e4d5f01f8bf9283f1176862a5c8ad8411fea64e3fda6405dbb6',
       '5b4a57eafbf59e941df8f01997969fc74ce684f98a8e20ec5d3eaed926f87d90',
       '06a6e7349e3f7d600a243d794e028f1d84e052bc028ac852a9ef569ada8b0f0b',
       '3c28bc47d5549b46cec30a9a128ecf3cdfaedd926b471591addb6731220800d8',
       '7926f1baef66db6bc46191446b410aba4ff4defb43bb0873ea46e4427bf8dfac',
       'e82bde64cda04207b2097df579d23907b9feb594c47f565efdb0d2fcfd005676',
       '838babed4410853f9168b20aab378400555c971f7d03070eb78c1d4cb312ee4f',
       '2f95320ce6d5b9e0edd9ee1b3dc8aa0407cf2078a03f34cc5f343edd542c9324',
       '8cc669d76fa72b68bfe58eb4c2766b64adebd1d23f81d93c651dc9a4769a24d9',
       '1bec2f7d9c9e71d8500ab0f274c9d9ecb1a501fdee46ec5e5f479f118181337b',
       '5d4e6da252654005533f55fe632cb064bb91b6f4078c973517f97fd6720d7c1a',
       'eb2d5eb0ea23ac06c304e679391ab828dd3d96a1f72de290e21552afd37382a9',
       'c5e7eb8fbf808d4374b68fd1b9e798802e7f853c223254995a9d88b8078a1755',
       '9268d812dd55cd9cca9612af75fed975db9fdbc16e1f405233cd59482deae685',
       'a6970c0372156e83264c317fa63892e1dbde7db0ea73e5e7bec97cbd8d61cf01',
       '005ce81bf3ab629586821abb3830b5a84f8bd79e6b69d8e3b1899eecbfceff7e',
       '791081209102ecaa67f9902f511c40adeae341d08908726374a7fcdda0a3cafd',
       'fd90b8024575951a29236f32f6b7bbbaedf81609587a6cb2b845c010215bdb5b',
       'c6174be57e3b341c1862b744b52502eb856cc4001143e894e85a1ca01b8317e2',
       '6c9105855558b1edd259e04563d35ddc5cad615129ac5bef19c9065522405376',
       '432bbcd9d1237131c3f16c791017510f88c16b20c6db6210dfcae8d49f73312a',
       'e34ed99ebdbe58fc87db84ae148f4637085804de22ee49f01ae74b8a1241ee42',
       'd50dd9cfc968cfba6dfa528f9d9d8fdfd920f3df7c672ce6cb19519d28d0694e',
       'be37ca6339352d04c89285da9dff8a1a4e2987af60902fa4d1caac3c529fc81d',
       '8cd01f0b6181f7f37ca8868a5726e6dc043a1588264debb57b550cf689ca29af',
       '805ccb2ca2a4526361c439f11736c56529baf1e733fbbdece79d4b39d35535c0',
       '590562f2f3418da85da24132216e46b5f84805a963a7e8f43ed1db51f25292de',
       '10eaeb165f367a4b15fdd573b86549945b2827b08662de9d496e08ef23cb185a',
       '1c64336194d0cf76d6959e92edb5ef8c2cb47ac1ae974e953d32eb0638900303',
       'd0cdcf4fe06775074f5dcdc091222c1e51db4e5a30143835bc5c21990b46d9f0',
       '983e11b115e5c2727229c13365f71ad5df28cbb10256fbe4dac03e9b0d9b5c28',
       'c89269cdd8061a2c51fe0ff3e4b37726b345362949bef1487c15c83b96a52063',
       '4855a15969d16364938bafaccef9b192c13f74b5b1b165327de6a6076cddab58',
       'c9a45fd2b6ee62e886b64b9e4ff97201d1f2310e50ba69929982bd93b54ec535',
       '8a4f404f0ad85c8310bccb0bba739e965b1baea2ca998940052c7c99d91579f1',
       '98e8cab4575f51992db3777fc90602d85a7c62d82f2b9b332d7a4bd03e6a5a31',
       '26d6d610d1094dceb6acaef9a40bf1fb9da2a03337c1cb70d6b66004824c90f5',
       '6ed0c4a0474100c47216b5adbe75eba3aa6fd410d3559fa1a8ac145ff24d3c34',
       '2028d0a3b3f68ec43df827d2278d7c17f7b536fc660b3a18e3b2227400db024d',
       '1a4357bfa8f52bd68149f9e5e16bb3b1946f6348e1aa07172b4af58cc13f042d',
       'fc176e187a3c945e592ff0cc91267e6955f53c1c0f450b6505e581003e9fd8bf',
       '10b4bfbcb91a15691d423ff767cb1238857eb0aa857933f4d97463f0645f75d2',
       '7849f44e9c308b45159d067beb54f05fe96e7c96919c936a50f14c1f441e7923',
       '66c161a1805b7607aec17b2d0e1e6aa4b2cc5707f8459e32cb36c9ca26bca8dd',
       'e3139c8c0bf8a5363d860f85b29f40d1544dbd2dae7ba1772bf221a323dac293',
       '7483b50c7167399a3646768145361d88928a3b740005ace4708ee84716a0396b',
       'f5148a008b1f17f459ef57165d03e622f00bb6e0e7a080db443ca943c4ebc4dc',
       '2b86712c37c472371271b3366204d1a37a94475b712427b47c056f283b2cb71c',
       'f8a8fc381384ae163c2ccc6be4865b1cbe7d376d538c44a6c37f01c6f7e535ab',
       '677d09958b26f95411ccaeb48ac9731d73d19a1e9c39be5286bfd43b10b1e3b8',
       '4842afb9c4d2b0ae2296055b12f445de92b311c6550b46c25b472a13a91401df',
       '2cf63a91c5590eb15f24e6fa416ffce5b05b97c567f352e7322604c8295dc057',
       '2da38e3fb7f865800f0eedd52262f71670a804aa81e2dd1bc518d41d7be6d743',
       '27fc2df6e8e727936dc894081f3c1a141df166921bcc1b23f1c35c36e206aee7',
       '64855e380e36dad8fcef987a58fcc6086ea4cef1a2293dcf6cf5d125afb6065b',
       '81f672fe308d3459bd7aaca0f618c10c9d8f070ca97a0630486d8f31d0540e4f',
       'e902b356d6e8a6e93581ffb5d927371cf59f8999ed537301c1460132be06d115',
       '9e124633cdc0ea934c3c7a3118163dbb2207ad8b8bb29955b04660daf38170bd',
       '6cd98c38acfc4b54c292bd51e067e53356174f0f54ce8a66ea6029f37aa25178',
       '14374a3196cbadbff75eead9de120c2078e9286489167fbc26d6e74d74262af6',
       'e597dc9f07b1e46b8bf20fb4c6d3dccdcf85325c47c84a800fc9dc4044a00d9b',
       'c209b186372bca577151bf74f62fe4607ad7b6d8ce09e9281d6cd1e7947bf9cf',
       '10a6d8c79d3247aea9f8d0cdb82493a900c938b580e0986d11ca5cc2d707a20e',
       '51e691d3367a26262b52221e305b3fa02cbe2778e7af84e148e8aec8263b189e',
       '859a87c1cd57f27c323ef9e5420e12299791c3309e6332a3c2cb5cbacf86cac8',
       'f08d641f3261f4ce676a3d99f4ef433d283dbe1ce466603d11123a885a31c602',
       'dbbcac3dba806a1595a98ec377ae2e3cb49be34df37ad8c242499a54d42298e0',
       '67fe9433d618c30a6fd9560eb8bdd34f12728b65579f6f71e1cbae728b0044a1',
       '64fa291521168aea5ffa49bc472c527ceef6c153c95b515ad0538cbc6de1de26',
       '2244e10930f39ca91be0eb7c4b9c2b8619691ea4bdd7fa5af509326843045542',
       '5812c75004c9bb8b4ac5be6eea3da6ef114645621fa19a6e7e3b4fa1fc24dadf',
       '4d9fc1547c1dc40b02d5b95d7552fd47b079989d16c6c284523fddc4abcc6baa',
       '6db5bb27040354aa6ecf2016eb512ff45d32000dab70e8e5a315f9919c53634a',
       '63c0cb838f7460a967e7053688310bc1f714c1d9423e3604b92a37c39f275041',
       'f02aded17a28bebd81fbf31f47e00cd158d629999acddc8a9adaac75731da2b0',
       '4c51be39cf72b2856d5798c2f13f22c8f01dec1772573cdeff5a5b688af9c053',
       'd7e7eb38ec9d69ba16b635197a7a05e237454174185f0e0365292b1a56de25a4',
       'a76838b0b1000958bce1e0126d78a311ed4e80fb229b6991ca1bc7c5da44d16b',
       '52cda89e67b9c1627ed9faa193408885f0ff1d933b384bd1e203bee98d8e09f2',
       'a8c6f1297edfd6471aabc4e608cc1b7ba63cc6d9b60a7e060ff5f24ed848ccc8',
       '81986c811cca5194f577a9ac4f2531d122787fbbc8b5747b3d7b8c93f58f66e0',
       'c345b7e5e2c8b8889fc52fcfed8f685dc0ab1e39dc7dda8c4ead63a9585db6ce',
       '4e463cc6077dd8ca5bf8554b096268c10033f8073d0285d41872273673c13888',
       'b02b311b6e18bde21cc4bad812cc0ba97bf84e8b27211bc2bbdfda05b21b00d1',
       '339b05d6ed3d01fda1f01848e59f9fdb3c52ae909ace2b440ab653c7930096bf',
       'a28e575c05993f89d972f8fa9c49785821a7d1f7bf2f9526c5e556adc2819753',
       'c4a2c565f1a75c3409e53d4837a0baafc76fc5b3170dc457a58595c76fff07a0',
       '956f0d1aefcacb23bfe6bebedb807ec1beb462beb1532c3690365f076a3227fd',
       '761e61269a044c2ff0a12f7d5f8f21b87cccbcf35eb2106c2382184c70bcd0ef',
       '29ac1b084d2b0c3fe19aeb1e6803e342e38a3177664d0d169ac1c34bbc4cd169',
       'ec7409dc8aae5123d46174ab436c959ca4387585fdd2979ce3f21210be16c663',
       '2a67a0b9a90efbc412d9b23f02f6abb41bb54990ceab8ec6e142238a56e034f6',
       'a2bf428ddd0dd004dc30b0fdfde9292d874f681f624c59f9a99d60f32823ddc6',
       '44fd22bd436803201f001c933caa54751cff3c8b0f2f8db1823988eb12e2a76c',
       '1ae4c5cfcc330ba1123a664308cba80a683ab05de54d402f67a4b562a582808c',
       'ca2ee80538455bd07346e9661229e1f088350589cafc14e69f790d3bbb6b005f',
       'd594683b0a1855e8d4cbd998b75607d1745baa3273d0d1cde40d8c46327988e1',
       '4cba351608a81f0dd515a596bf778a8756b4b6220e8e4516cbb44d20aeef8339',
       '9a8c96b393e7b60254847254974c1d8b3dfe930e4eb02d54c8155f230b4e857d',
       'aaf9f12f6dc6da758f1d155bc8b566c4b5f1e4f7e8243a881b0eb07e6a532384',
       'a24304dda55dfffa55617dd1a1030c5e1dba3b9cbe1f7650fc20f590e5735a06',
       '068ffb8c12a7a5d9b8dd9aa929410f6c54887cb1b24118ae1831dfb287607a6f',
       '813e042afccd2dc433c0a6e699fbb73e3a655e1f568330ff1f710667cab2fb3f',
       '84cff5a62b9289e2e082f192e29e847dc5a7e9b560c3c45e83326e732add5987',
       '489c1cac3013d114b27ce6f0b7df14224439e8d4ac85f6dea6832abcd01dbc5c',
       '32c5563db5066b783ac7be8726e4f595ce2bff7b6169dbe0b9082c64f0b46a7a',
       '68a773db9878a5a88dc30c9b09406ac32a7de2f41cb53295808e0b010ecbd398',
       '34407f4aa4813a8375c7be7b3018d3b7a734bb832bee23d3f873f36e4827c182',
       '778307cbefedeabca1f62ac8ea2acbaa6355207235fa7a2dd0b8fa3ff3cc2d1f',
       '98e015efa53bb0050e164961f3be9b20b443c4309ff0bbc260f9434a6ca69f66',
       'c3881fd29f2338c4cfb8ee0161c1871ce06483f653971dfad3b1cd8016aee6aa',
       '71a5a461723061e4fc22566fddcb8d6bd884017262aaaae53533dc1e25b1a70d',
       '0a2aabb5591077670541dcc4b9822a082a36adc53edd2570c2db8e62ccf36402',
       'bd465f2db5a222bc5abeb3f34ce06dee44e46af80d85b84e222b0e75fc23b533',
       '2e01a5935f983da497e1130ca9167fbecdb243fcefee78eca3dbd92d03c0f3ed',
       '85ab8ef4a8d4fb85b15ca515a056012564c394da52832453ac986a835252ff7f',
       '468509fda54cb5058c9e48f14990ac119cdd3a48993c6b7918d290fc1a6b43fb',
       '44dbdb3353a0370aa3a550d25d4c544bd4af34b5c29bba6e0c5f0a96b217227d',
       'a07b7c3f00017d57d0431cc287a28bfd24636a2003f105b5c6104ff813c6c424',
       '134077725f75b9fb7d887271408f66e856682b147106f9314a6a751344353e84',
       '0eda6b0fee229a670efb2e20e280f0c2ca964519341b828c01c41ac0345ac447',
       '857c4840431e2ce7b8c9aef65fc5f1d2e9321db336933316f9732aca72578076',
       'e2092656948b2e8503a47aca091cc1d40b41a814a5ea04774a2354d6798169a7',
       '792249c68fe904a83ecc3d15f76ac2c2e9d548177ec3cd188e71fac75784b5ea',
       'b3a6ca5880c8b2e453b8f63eddfe91871a5ce89de98364e7db0ee924caabfb92',
       '9a8c7bdafdd5d5fe42bf44d6064fad5f4266369a11342c081358fdc405a463fb',
       '3a4135a6f23032026380932cb0d14c08b2b559eb09598c9aaf5dde963d6a4d67',
       '0775d58f12a050faa59eaa0d4746e130e3a5cf453ecae07370d052972b7a7b0e',
       '434fce3d03d016c452f595b69596f938fb6a44ba9c6cd95df37e3deae40cb05a',
       '8a8a59a9cc18303ccdf756b8f08a4dc40e035c23cce88a977df6c8523f008379',
       'eb5d0c1a8eb1cdb1d07646aed0b53b669f70720a44231c6af2cd3cd8d9d609f3',
       '71cddeefee82028257c1ac564d2e078ee307d56aa9f44c6646c82d853108d0c3',
       '334998173bc54d187c447e3a4b96bbd516da74244f8174542c2e4eb9fbcd1898',
       'a4579f5a408ca9a5b7930f3dcc7c959edf468be470faf22f4c53e9237a93369c',
       '6cb34ee5efe5fffb3851473e418aa07734640d53227679d8cff881047123f4c1',
       '3b08fec082f10023bfe4244ca9ec5fe4da534e0f877da01185b459b68853868c',
       'f3baafcfa62af3dde8e6a68fcd41298509a0ac052a5ad451d902f75c20116dfe',
       'a62b2034520c952bbd4fa4a5b4abcd488453decaaeeaa967e47fa93135b82e92',
       '9d1a609c83158b9c1f921dbeacebbf79a5fa204fff0f34d33aab4fbd2df3cbb3',
       '96467b1b0ad89df16c6624816b9bafb4c195ddafe5716983f53676fd3065d979',
       '821d7ba17194253d5a69c7b7f90f6299a6923e1a0ff5f380d6abe3d016be9bc2',
       'fac42337eb72f472a9ff42d534f4e302861d23d4119ded0a7d4808590a52bfab',
       '22ba8a6d446719ee2246bb92f1488e334e7e0311d92eaba06bccfd6c30b4bb10',
       'ee991e3b1b7a8d879b232653b67fbf4f1d3d6ddac71b127fa2d9c2d55c008f37',
       'a0aef732f38f489bcdd33c9abb109d2c619fd593e074e37102a360deeb2a9bd0',
       '6e23dfa59afb592e7bff328e721dc5a14710e170ecc70bca2abe2021ee6a8a51',
       'd9c204f07648077fc7519148db64f137c6f0a5969111b36f91bd7187e8841359',
       '14b8ecc7305f09a1c6669ad6ea162f43a12cbffdc7d9c220f4d108a20e743f29',
       'ed42e5e07cafd30621576883d6ea1f88dd328da50be7a1a820674ac97701ef84',
       '0ef064d7c1577aaff4949cb256c305486f3c10d8ab4cbd71d974977dca441998',
       'b8d2f7d0ec24bdaa1115599e20e212575c79f7fb9ab79548b7c16e78ff55ece7',
       '6a28a14919b58be2db15eb2de6c0444ba1e6931acd077691928124850c2a9439',
       '6d2a198f83ff1415405743055b73668705ba30a187867268020ad37ef922680b',
       '38627e4640707cd30a3cbdee8574615c588b3b50aabb423fbdea306a51a7ddc2',
       '153dcfcb62e5f543aab31b016aa006174e8ef1803a9ea27b19d4ac6a606ab6a1',
       'b569516ada13241ddacf1bfab0aa8c32d7ff272325623584a1793ec2cf4c9e05',
       '59f40f47b825af7cceb03e2be1b681a99b8b763a145612086b49e4bf59bcc2f2',
       '3625a5982312018f11a7e24001d5f500655893bfa26048c10fa37c17c3c62be6',
       '82d978e8cdd1603a0bf29c9e79509a3c744b6bddd1a4c1f4164101fd08c86b48',
       'ba6b0f2415f6f7e2233f92a4a89246ed348a136bee291648e7a861b4af7e74f6',
       'a9e966b6b6b8dd3512108f6d345b5cc6700bb87b3965ef06ca36031bad10bcfa',
       '1bd76ca73e806ba8fe9ad62c621d163e59d5aade3b6f95967f2cc279c3a5edb2',
       '9a7cacd65258f743b3dea01568d356ca877fdcc5f858bc5b67f1c06b3fd70b1e',
       'c2ffd88166ea8f8d48deb7bfac956c5896267ffc081e0608d59887c09f6aa964',
       '95891aeb2460b649fd0a79b4b34c37f68b8445ab35a3c844c5e041e8c604c633',
       '8bd2e2645d8a3472dceff3a489173c2fb75fb4cafe88233a7084a96ba786cfe7',
       '64073ad4a0f322e0f6c9f7a98f6357a6feccf022ee41779f797a6fe52213a90b',
       '9c9373363ced33e59f0b453949ccaefb1ab88e0cc39e9f8d869ceae7e1c29df4',
       '2d3bbaeab1b1492c35409fa7f0201f105f58f8a379de6557d541185e6cc97db8',
       'fc237690c42d7f661c4b07614fd727edd3060b25067b05ed6edb42df2ae1d7e5',
       'd5157618ed74bb7405f66bd5ad6551ea5e33961f93a2a4db1015465e9df4f8da',
       'eb06ba11fd8593f340efad7643d32d8194a5332b9fd525e6f35406c56ec06e23',
       '565ba611465f2e44dad375f7185eec7485f95abe669f556a215e4910feebe964',
       'e46767739f626a5ccd37b08313a0612dbd5383df12bea65ae9c92da6ff9794a1',
       '9062e1cb738b407a213383f4677a748207d8296b5a105f638e57f8d0bec16a51',
       '447f3a13be2832c2dd24463d67c1347ce2650db7ffbf944357ec7c4dca51dd5a',
       '8be5cd29a39a7810a1937b23271c30d2025fac1e2aea070f11e26f863ac25075',
       'e0ab53711362de601749d4f1dd61d42ba1fa36ae296a7764ddde133f0838c953',
       '3ea0e4b43a1b546d39b234d3f96a39aa913cebdefe9e400e73e1727aae4de8c5',
       'fddad49e9d3f9b578ed02d200776790bd25ccbb158a0e57514b5c288358efa27',
       'd554887c1f87741f365dbee233ed41246cab4abb8dd073f293d18e64f4fca118',
       '6dfc3472a5cb588000dfed5172f84d576fc53a3122ef9e5d8cb679a1e485526c',
       '05865846f00ad67a5e6f9bfd1ea22a2dc4c2156d287bbd6ee871eef6300436b3',
       'f4fd03338f5120ac8ada8e09e46727d62492cdf35894dea1bac1dbc47b4d3432',
       '07bb88c233d8a7772eb3c7d6242f646f1bad782d4f1689e862efd0e7b4e0776e',
       '7afc022a942a0f2312c0b9ec56c76f0d3818ec40d307fd554a7a60d7017078c9',
       '4615607a008c6e848b505fb54c2e6295c460edf3a6cf31bfb90605c03586d542',
       'e7c46fd7731e523e82524ca9a2271c9fc3fbac2297e0886d1c3269ee5e46b986',
       'b1aa13a4410c266aaf704dece28e74999ed8b9abb54a7f404a362ce907471375',
       '639d5a618573261be9976c11968767e35e17f2995e506a690b53c2ca54be609e',
       'f9b6ed366d6e6362ecd6a05b069294ec231b947a702b1a54064985758b60ded9',
       'c2dae8e2ce8d47b57307cc44fe6b022d92583b775753f15757b373b2c628ab3f',
       '5945f6c86bbb4d88fd06a2b48c43adf611e7b227e53554a72c31954650bac1bc',
       '29e3c86a2e20db5e47710f97252598cfc2b29b90ee21d15d2d6a1f4ab22122cf',
       '3103882abfff5a5cf2aa4b92cdb8ccb48c220a4b04689d29e7c813b97d7e8f2e',
       '7f581bacee1e1fc28f5d6c50007534fa0ac9c1f4c4949b3c643763c1dc9c3098',
       '3d21ab57d39bd5d91e2901dc0904e4914be0a83f6a95bc4ecae09feb1abd6173',
       'c3c6cab7ad9b816870ae99ecc81d30377a975040b569972e52b1ce1b21e3d86b',
       '7bf5d4a5745467e260da39b3d40afba60cf2f91e1e53b688aa867f59ac4538eb',
       'f005074d18e160ec0e6ab7ab2575560c8d32b1422c0bc56c9b0d7cd84cae2b17',
       'be9223d8760ba46c353f09a34b2cbd23c6fed7b9b93c13dd6162c2b81f5b5987',
       '069542d3e78cc9f4d7ceb450ec3cc59f7629f8e2eefc60371a78bd9a71bf62b8',
       '6d82b4a75e2734d772536c4793264889e76e90dec73294e6e9a47dcbad82412c',
       'c53dfc4ff4749181f71138c1a23a3b2f9fcd8ae63623d76003229c21f30c0700',
       'ffb13ce99cc70250c59291da01c5f21b64678943cc513ba6ac372b76e90d2fbc',
       '39093b6ef17c2408ba339079b422d436f032de4a1ab5f184f22edbada98e2441',
       'b3308a5c7e17f9e14ecdea94809c2d8fcb4afcc09b5c244d92e7345b74127f82',
       'dcc2e0a23ab2e4a497d1464b9e3f44156627b12f1710c89c411d62dcef58b11d',
       '4974c8446e7f5788ac6eb01e8b5193d700b37b7b7f56998919394a1d737c9603',
       'b68971610987c35b7363108d65dc5d2736db1fb19de714a39436d1e650e2960c',
       'da4dd524cb81f580e863b49118211930022036ee023f75a23bfb7854931c9bf7',
       'a9f761786c55245f93a5b330c3155454f4fa47fd5585b52b40748e1164e82e1f',
       '8e0e8d8e8e4153471491ee0a0e513552cd1a5e506b04c753ec8bf5034b14e24f',
       'de98d9c5923f94753bb0077e03348a6118ecb604afae64daa13e7b6a856382c7',
       'e7e0423b76e52b6cc1b51394e8999fb2c774f5c4fde7bc6801e66e83383f79c8',
       '6bb494afac37ee658dfd01cdf848b7d92066180edb2cca57946b8dfe60b4f572',
       'c56ff3d19c50a1e0063915df35801664505ca4c18ea9d148fda358cf3649457b',
       'a55d9c2d21fbc951bce5f87cf58ed18371f0257a135b0b383140543c0aba1594',
       '4117393ac6dc514cab3a127a11edab8575f3a44f73bef92418b55aa413ee310e',
       'b03146f1cc88409b5cb64898fb3300c55bfb392363238982f2f16376a76eff1b',
       '1762816ee67a80fa5a93fe465b022c3b52c7cf390e3ad3a5417126dd41b41e26',
       'e9110bce04fd00387eee4c545e55be161a838e6de4e535de96c4b5c2d4d3086b',
       'adc5dd5c8ae04807c64a37cc5adc90b45ed585f0e2a902e0ccce017d9a873cd4',
       '78690e18267115c7d2bf3526e084fde60547a62ad470eeea216fe9e81d11d278',
       '16fd695cc6a900a27fdf5f7deaf7c8043bb19ac0cf769a4b53cb0f510d037fe3',
       '028c26f27f95b223b118a4bd2dc4a1a57ba3b481fbbf6c25b449683672ce0786',
       'b62b386b5a988b5415098cd81141aa60187d5a80147a738bda5f09336b323fac',
       '813fcab115127a056d805a35a0957a3c1bfbbbd44f33d2733d8197e2ca5b8d61',

In [7]:
# truncate all rides to topple_delta_s before first topple
# accidents use their own ride_id; baselines use crash_ride_id (linked accident)
first_topple_idx = data[data["topple"] == 1].groupby("ride_id")["time_index"].min()
topple_delta_idx = int(topple_delta_s * sampling_rate)
cutoff_map = (first_topple_idx - topple_delta_idx).to_dict()

lookup_id = data["crash_ride_id"].fillna(data["ride_id"])
data = data[data["time_index"] < lookup_id.map(cutoff_map)]
data

,ride_id,crash_ride_id,city,time_index,ax,ay,az,rx,ry,rz,topple
0,804e23f63ec36c94ea840b66d98e53a90e0a69d4e66f0b...,ca1e869059a8de9fe0f38760d72d2ab8b5ee2363640d26...,6,0,-1.315454,-9.585049,-1.459023,0.002901,0.000763,0.001374,0.0
1,804e23f63ec36c94ea840b66d98e53a90e0a69d4e66f0b...,ca1e869059a8de9fe0f38760d72d2ab8b5ee2363640d26...,6,100,-1.312463,-9.586245,-1.448853,0.003054,0.001069,0.001832,0.0
2,804e23f63ec36c94ea840b66d98e53a90e0a69d4e66f0b...,ca1e869059a8de9fe0f38760d72d2ab8b5ee2363640d26...,6,200,-1.316650,-9.586843,-1.450050,0.002901,0.000763,0.001679,0.0
3,804e23f63ec36c94ea840b66d98e53a90e0a69d4e66f0b...,ca1e869059a8de9fe0f38760d72d2ab8b5ee2363640d26...,6,300,-1.311864,-9.582058,-1.462612,0.003054,0.001069,0.001679,0.0
4,804e23f63ec36c94ea840b66d98e53a90e0a69d4e66f0b...,ca1e869059a8de9fe0f38760d72d2ab8b5ee2363640d26...,6,400,-1.308873,-9.588638,-1.459023,0.002901,0.000916,0.001527,0.0
...,...,...,...,...,...,...,...,...,...,...,...
16891224,32c5563db5066b783ac7be8726e4f595ce2bff7b6169db...,None,1,168900,-5.531607,-3.449253,7.308876,0.008092,-0.004581,-0.022143,0.0
16891225,32c5563db5066b783ac7be8726e4f595ce2bff7b6169db...,None,1,169000,-5.531607,-3.453440,7.305885,0.008092,-0.004734,-0.021838,0.0
16891226,32c5563db5066b783ac7be8726e4f595ce2bff7b6169db...,None,1,169100,-5.529214,-3.449253,7.308278,0.008246,-0.004734,-0.022143,0.0
16891227,32c5563db5066b783ac7be8726e4f595ce2bff7b6169db...,None,1,169200,-5.529214,-3.446860,7.310073,0.008246,-0.004581,-0.021991,0.0
16891228,32c5563db5066b783ac7be8726e4f595ce2bff7b6169db...,None,1,169300,-5.528018,-3.446860,7.305885,0.008246,-0.004428,-0.021991,0.0

In [8]:
ride_ids = data.groupby("ride_id").first().index.values
ride_ids

array(['00133d30cd80ea11fa0fcf81febdabe9db6076d17f4676499ecad4fe0e95eaf8',
       '0025c3e35ffcf388b78af62162dc62bc1f0876d5adcc458660a956d2f4f5954f',
       '003140ddd2e09d04f6d84ceecd290ce4092a210603d78750087840ba97405ec7',
       ...,
       'ffb13ce99cc70250c59291da01c5f21b64678943cc513ba6ac372b76e90d2fbc',
       'ffb96b0d53ddc3713570000f404be911e7f4b090984221a56f670713203c89e8',
       'ffd656df844640713a8323cfa8774f50fb0994aa0ae897321b4f4fd8656806c7'],
      shape=(3490,), dtype=object)

In [9]:
labels = pd.DataFrame({
    'ride_id': ride_ids
})
labels['label'] = labels['ride_id'].isin(accidents).map({True: 'accident', False: 'normal'})
labels['crash_group'] = labels['ride_id'].map(
    data.groupby("ride_id")["crash_ride_id"].first()
).fillna(labels['ride_id'])
labels['label'].value_counts()

label
normal      2792
accident     698
Name: count, dtype: int64

In [10]:
features = ["ax", "ay", "az", "rx", "ry", "rz"]

data_np = reshape_to_numpy(
    data,
    features = features
)

data_np_clean = interpolate_missing_values(
    data_np,
    method='linear',
    limit=None
)

data_np_clean = denoise_data(
    data=data_np_clean,
    accel_indices=[0, 1, 2],
    gyro_indices=[3, 4, 5],
    accel_cutoff=accel_cutoff,
    accel_order=accel_order,
    gyro_cutoff=gyro_cutoff,
    gyro_order=gyro_order,
)

In [11]:
# Compute spectrograms for all rides
spectrograms_array = compute_spectrograms(data_np_clean, sampling_rate, nperseg, noverlap)
spectrograms_array.shape

(3490, 320, 6, 33)

In [12]:
# Aggregate spectrograms using time-averaged pooling
X_feat = time_avg_pooling(spectrograms_array)
X_feat.shape

(3490, 198)

In [13]:
# Define Autoencoder architecture with Lightning
class Autoencoder(L.LightningModule):
    def __init__(
        self,
        input_dim,
        encoding_dim,
        encoder_hidden_dim1,
        encoder_hidden_dim2,
        decoder_hidden_dim1,
        decoder_hidden_dim2,
        lr,
    ):
        super().__init__()
        self.save_hyperparameters()
        
        self.encoder = nn.Sequential(
            nn.Linear(input_dim, encoder_hidden_dim1),
            nn.ReLU(),
            nn.Linear(encoder_hidden_dim1, encoder_hidden_dim2),
            nn.ReLU(),
            nn.Linear(encoder_hidden_dim2, encoding_dim)
        )
        self.decoder = nn.Sequential(
            nn.Linear(encoding_dim, decoder_hidden_dim1),
            nn.ReLU(),
            nn.Linear(decoder_hidden_dim1, decoder_hidden_dim2),
            nn.ReLU(),
            nn.Linear(decoder_hidden_dim2, input_dim)
        )
        self.criterion = nn.MSELoss()
    
    def forward(self, x):
        encoded = self.encoder(x)
        decoded = self.decoder(encoded)
        return decoded
    
    def encode(self, x):
        return self.encoder(x)
    
    def training_step(self, batch, batch_idx):
        x, _ = batch
        x_hat = self.forward(x)
        loss = self.criterion(x_hat, x)
        self.log('train_loss', loss, prog_bar=True)
        return loss
    
    def configure_optimizers(self):
        return torch.optim.Adam(self.parameters(), lr=self.hparams.lr)

In [14]:
# 5-fold group CV with AE
y_true = (labels['label'] == 'accident').astype(int).values
groups = labels['crash_group'].values
gkf = GroupKFold(n_splits=n_splits)
anomaly_scores = np.full(len(y_true), np.nan)

for fold, (train_idx, test_idx) in enumerate(gkf.split(X_feat, y_true, groups)):
    fold_scaler = StandardScaler()
    X_train = fold_scaler.fit_transform(X_feat[train_idx])
    X_test = fold_scaler.transform(X_feat[test_idx])

    pca = PCA(n_components=encoding_dim).fit(X_train)
    print(f"Variance explained (train): {sum(pca.explained_variance_ratio_):.4f}")

    L.seed_everything(rng.randint(1000))
    autoencoder = Autoencoder(
        input_dim=X_train.shape[1],
        encoding_dim=encoding_dim,
        encoder_hidden_dim1=encoder_hidden_dim1,
        encoder_hidden_dim2=encoder_hidden_dim2,
        decoder_hidden_dim1=decoder_hidden_dim1,
        decoder_hidden_dim2=decoder_hidden_dim2,
        lr=lr,
    )

    X_train_tensor = torch.FloatTensor(X_train)
    dataset = TensorDataset(X_train_tensor, X_train_tensor)
    dataloader = DataLoader(dataset, batch_size=batch_size, shuffle=True)

    state = {'best_ewm_loss': float('inf'), 'best_state': None, 'ewm': None}

    class FoldLossTracker(L.pytorch.callbacks.Callback):
        def on_train_epoch_end(self, trainer, pl_module):
            loss = float(trainer.callback_metrics['train_loss'])
            if state['ewm'] is None:
                state['ewm'] = loss
            else:
                state['ewm'] = 0.2 * loss + 0.8 * state['ewm']
            if state['ewm'] < state['best_ewm_loss']:
                state['best_ewm_loss'] = state['ewm']
                state['best_state'] = copy.deepcopy(pl_module.state_dict())
            pl_module.log('train_loss_ewm_avg', state['ewm'])

    trainer = L.Trainer(
        max_epochs=300, accelerator='auto', devices=1,
        callbacks=[
            EarlyStopping(monitor='train_loss_ewm_avg', patience=patience,
                          verbose=False, mode='min', check_on_train_epoch_end=True),
            FoldLossTracker(),
        ],
        enable_progress_bar=False,
    )
    trainer.fit(autoencoder, dataloader)

    if state['best_state'] is not None:
        autoencoder.load_state_dict(state['best_state'])

    autoencoder.eval()
    X_test_tensor = torch.FloatTensor(X_test)
    with torch.no_grad():
        Z_train = autoencoder.encode(X_train_tensor).numpy()
        Z_test = autoencoder.encode(X_test_tensor).numpy()

    enc_scaler = StandardScaler()
    Z_train = enc_scaler.fit_transform(Z_train)
    Z_test = enc_scaler.transform(Z_test)

    lof = LocalOutlierFactor(n_neighbors=20, novelty=True)
    lof.fit(Z_train)
    anomaly_scores[test_idx] = -lof.score_samples(Z_test)

    print(f"Fold {fold+1}/{n_splits} done")

assert not np.isnan(anomaly_scores).any(), "NaN found in anomaly scores"
labels['anomaly_score'] = anomaly_scores

Seed set to 619

Variance explained (train): 0.9519

💡 Tip: For seamless cloud uploads and versioning, try installing [litmodels](https://pypi.org/project/litmodels/) to enable LitModelCheckpoint, which syncs automatically with the Lightning model registry.

GPU available: True (cuda), used: True

TPU available: False, using: 0 TPU cores

LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

  | Name      | Type       | Params | Mode
-------------------------------------------------
0 | encoder   | Sequential | 35.8 K | train
1 | decoder   | Sequential | 36.0 K | train
2 | criterion | MSELoss    | 0      | train
-------------------------------------------------
71.8 K    Trainable params
0         Non-trainable params
71.8 K    Total params
0.287     Total estimated model params size (MB)
13        Modules in train mode
0         Modules in eval mode

/home/marco/mnt/git/reckless-riding-detection/.venv/lib/python3.10/site-packages/lightning/pytorch/trainer/connectors/data_connector.py:433: The 'train_dataloader' does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` to `num_workers=15` in the `DataLoader` to improve performance.
/home/marco/mnt/git/reckless-riding-detection/.venv/lib/python3.10/site-packages/lightning/pytorch/loops/fit_loop.py:310: The number of training batches (22) is smaller than the logging interval Trainer(log_every_n_steps=50). Set a lower value for log_every_n_steps if you want to see logs for the training epoch.

Seed set to 344

💡 Tip: For seamless cloud uploads and versioning, try installing [litmodels](https://pypi.org/project/litmodels/) to enable LitModelCheckpoint, which syncs automatically with the Lightning model registry.

GPU available: True (cuda), used: True

TPU available: False, using: 0 TPU cores

LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

  | Name      | Type       | Params | Mode
-------------------------------------------------
0 | encoder   | Sequential | 35.8 K | train
1 | decoder   | Sequential | 36.0 K | train
2 | criterion | MSELoss    | 0      | train
-------------------------------------------------
71.8 K    Trainable params
0         Non-trainable params
71.8 K    Total params
0.287     Total estimated model params size (MB)
13        Modules in train mode
0         Modules in eval mode

Fold 1/5 done
Variance explained (train): 0.9537

/home/marco/mnt/git/reckless-riding-detection/.venv/lib/python3.10/site-packages/lightning/pytorch/trainer/connectors/data_connector.py:433: The 'train_dataloader' does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` to `num_workers=15` in the `DataLoader` to improve performance.
/home/marco/mnt/git/reckless-riding-detection/.venv/lib/python3.10/site-packages/lightning/pytorch/loops/fit_loop.py:310: The number of training batches (22) is smaller than the logging interval Trainer(log_every_n_steps=50). Set a lower value for log_every_n_steps if you want to see logs for the training epoch.

Seed set to 268

💡 Tip: For seamless cloud uploads and versioning, try installing [litmodels](https://pypi.org/project/litmodels/) to enable LitModelCheckpoint, which syncs automatically with the Lightning model registry.

GPU available: True (cuda), used: True

TPU available: False, using: 0 TPU cores

LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

  | Name      | Type       | Params | Mode
-------------------------------------------------
0 | encoder   | Sequential | 35.8 K | train
1 | decoder   | Sequential | 36.0 K | train
2 | criterion | MSELoss    | 0      | train
-------------------------------------------------
71.8 K    Trainable params
0         Non-trainable params
71.8 K    Total params
0.287     Total estimated model params size (MB)
13        Modules in train mode
0         Modules in eval mode

Fold 2/5 done
Variance explained (train): 0.9513

/home/marco/mnt/git/reckless-riding-detection/.venv/lib/python3.10/site-packages/lightning/pytorch/trainer/connectors/data_connector.py:433: The 'train_dataloader' does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` to `num_workers=15` in the `DataLoader` to improve performance.
/home/marco/mnt/git/reckless-riding-detection/.venv/lib/python3.10/site-packages/lightning/pytorch/loops/fit_loop.py:310: The number of training batches (22) is smaller than the logging interval Trainer(log_every_n_steps=50). Set a lower value for log_every_n_steps if you want to see logs for the training epoch.

Seed set to 406

💡 Tip: For seamless cloud uploads and versioning, try installing [litmodels](https://pypi.org/project/litmodels/) to enable LitModelCheckpoint, which syncs automatically with the Lightning model registry.

GPU available: True (cuda), used: True

TPU available: False, using: 0 TPU cores

LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

  | Name      | Type       | Params | Mode
-------------------------------------------------
0 | encoder   | Sequential | 35.8 K | train
1 | decoder   | Sequential | 36.0 K | train
2 | criterion | MSELoss    | 0      | train
-------------------------------------------------
71.8 K    Trainable params
0         Non-trainable params
71.8 K    Total params
0.287     Total estimated model params size (MB)
13        Modules in train mode
0         Modules in eval mode

Fold 3/5 done
Variance explained (train): 0.9525

/home/marco/mnt/git/reckless-riding-detection/.venv/lib/python3.10/site-packages/lightning/pytorch/trainer/connectors/data_connector.py:433: The 'train_dataloader' does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` to `num_workers=15` in the `DataLoader` to improve performance.
/home/marco/mnt/git/reckless-riding-detection/.venv/lib/python3.10/site-packages/lightning/pytorch/loops/fit_loop.py:310: The number of training batches (22) is smaller than the logging interval Trainer(log_every_n_steps=50). Set a lower value for log_every_n_steps if you want to see logs for the training epoch.

Seed set to 327

💡 Tip: For seamless cloud uploads and versioning, try installing [litmodels](https://pypi.org/project/litmodels/) to enable LitModelCheckpoint, which syncs automatically with the Lightning model registry.

GPU available: True (cuda), used: True

TPU available: False, using: 0 TPU cores

LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

  | Name      | Type       | Params | Mode
-------------------------------------------------
0 | encoder   | Sequential | 35.8 K | train
1 | decoder   | Sequential | 36.0 K | train
2 | criterion | MSELoss    | 0      | train
-------------------------------------------------
71.8 K    Trainable params
0         Non-trainable params
71.8 K    Total params
0.287     Total estimated model params size (MB)
13        Modules in train mode
0         Modules in eval mode

Fold 4/5 done
Variance explained (train): 0.9538

/home/marco/mnt/git/reckless-riding-detection/.venv/lib/python3.10/site-packages/lightning/pytorch/trainer/connectors/data_connector.py:433: The 'train_dataloader' does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` to `num_workers=15` in the `DataLoader` to improve performance.
/home/marco/mnt/git/reckless-riding-detection/.venv/lib/python3.10/site-packages/lightning/pytorch/loops/fit_loop.py:310: The number of training batches (22) is smaller than the logging interval Trainer(log_every_n_steps=50). Set a lower value for log_every_n_steps if you want to see logs for the training epoch.

Fold 5/5 done

In [15]:
# Conditional logistic regression: top quantile indicator → accident, stratified by crash_group
endog = (labels['label'] == 'accident').astype(int)
quantiles = [0.95, 0.99]

results = []
for q in quantiles:
    q_pct = int(q * 100)
    top = (labels['anomaly_score'] >= labels['anomaly_score'].quantile(q)).astype(int)

    clogit = ConditionalLogit(
        endog=endog,
        exog=top,
        groups=labels['crash_group'],
    ).fit(disp=False)

    or_ = float(np.exp(clogit.params.iloc[0]))
    ci = np.exp(clogit.conf_int().iloc[0])
    results.append({'quantile': q_pct, 'or': or_, 'ci_l': float(ci[0]), 'ci_u': float(ci[1]), 'pval': float(clogit.pvalues.iloc[0])})

res = pd.DataFrame(results)

# Glue key quantiles
for q in quantiles:
    q_pct = int(q * 100)
    row = res[res['quantile'] == q_pct].iloc[0]
    sb.glue(f"SRV3490_q{q_pct}_or", row['or'])
    sb.glue(f"SRV3490_q{q_pct}_pval", row['pval'])
    sb.glue(f"SRV3490_q{q_pct}_sig05", int(row['pval'] < 0.05))
    sb.glue(f"SRV3490_q{q_pct}_sig01", int(row['pval'] < 0.01))
    sb.glue(f"SRV3490_q{q_pct}_sig001", int(row['pval'] < 0.001))
res

   quantile        or      ci_l      ci_u          pval
0        95  4.699911  3.394006  6.508285  1.191835e-20
1        99  3.547630  1.784803  7.051582  3.029590e-04

In [16]:
# Conditional logistic regression: continuous anomaly score (linear) → accident
endog_cont = (labels['label'] == 'accident').astype(int)

clogit_cont = ConditionalLogit(
    endog=endog_cont,
    exog=labels[['anomaly_score']] / labels['anomaly_score'].std(),
    groups=labels['crash_group'],
).fit(disp=False)

or_cont = float(np.exp(clogit_cont.params.iloc[0]))
ci_cont = np.exp(clogit_cont.conf_int().iloc[0])
pval_cont = float(clogit_cont.pvalues.iloc[0])

print(f"OR per 1-SD = {or_cont:.4f} [{ci_cont[0]:.4f}, {ci_cont[1]:.4f}], p = {pval_cont:.4g}")
sb.glue("SRV3490_cont_or", or_cont)
sb.glue("SRV3490_cont_pval", pval_cont)
sb.glue("SRV3490_cont_sig05", int(pval_cont < 0.05))
sb.glue("SRV3490_cont_sig01", int(pval_cont < 0.01))
sb.glue("SRV3490_cont_sig001", int(pval_cont < 0.001))

OR per 1-SD = 2.5150 [2.2625, 2.7956], p = 1.764e-65